#ifndef ILPLIB_VERSION_H
#define ILPLIB_VERSION_H

#define ILPLIB_VERSION_MAJOR @CPACK_PACKAGE_VERSION_MAJOR@
#define ILPLIB_VERSION_MINOR @CPACK_PACKAGE_VERSION_MINOR@
#define ILPLIB_VERSION_PATCH @CPACK_PACKAGE_VERSION_PATCH@

#define ILPLIB_VERSION "@CPACK_PACKAGE_VERSION_MAJOR@.@CPACK_PACKAGE_VERSION_MINOR@.@CPACK_PACKAGE_VERSION_PATCH@"

#endif