/disk/workspace-cpp/la-manager/include/stem/api.h File Reference
Classes
struct SN_env
Typedefs
typedef unsigned char symbol
Functions
struct SN_env * SN_create_env (int S_size, int I_size, int B_size)
void SN_close_env (struct SN_env *z, int S_size)
int SN_set_current (struct SN_env *z, int size, const symbol *s)
Typedef Documentation
typedef unsigned char symbol
Definition at line 7 of file api.h.
Function Documentation
void SN_close_env (struct SN_env * z, int S_size)
Definition at line 45 of file api.cpp.
References SN_env::B, SN_env::I, lose_s(), SN_env::p, and SN_env::S.
Referenced by danish_UTF_8_close_env(), dutch_UTF_8_close_env(), english_UTF_8_close_env(), finnish_UTF_8_close_env(), french_UTF_8_close_env(), german_UTF_8_close_env(), hungarian_UTF_8_close_env(), italian_UTF_8_close_env(), norwegian_UTF_8_close_env(), portuguese_UTF_8_close_env(), romanian_UTF_8_close_env(), russian_UTF_8_close_env(), SN_create_env(), spanish_UTF_8_close_env(), swedish_UTF_8_close_env(), and turkish_UTF_8_close_env().
struct SN_env* SN_create_env (int S_size, int I_size, int B_size) [read]
Definition at line 8 of file api.cpp.
References SN_env::B, create_s(), SN_env::I, SN_env::p, SN_env::S, and SN_close_env().
Referenced by danish_UTF_8_create_env(), dutch_UTF_8_create_env(), english_UTF_8_create_env(), finnish_UTF_8_create_env(), french_UTF_8_create_env(), german_UTF_8_create_env(), hungarian_UTF_8_create_env(), italian_UTF_8_create_env(), norwegian_UTF_8_create_env(), portuguese_UTF_8_create_env(), romanian_UTF_8_create_env(), russian_UTF_8_create_env(), spanish_UTF_8_create_env(), swedish_UTF_8_create_env(), and turkish_UTF_8_create_env().
int SN_set_current (struct SN_env * z, int size, const symbol * s)
Definition at line 63 of file api.cpp.
References SN_env::c, SN_env::l, and replace_s().
Referenced by la_manager::stem::Stemmer::stem().