/disk/workspace-cpp/la-manager/include/pos/bidir.h File Reference
#include <pos/common.h>
Classes
struct Hypothesis
struct hashfun_str
class ParenConverter
Functions
void tokenize (const string &s1, list< string > &lt)
string normalize (const string &s)
ME_Sample mesample (const vector< Token > &vt, int i, const string &pos_left2, const string &pos_left1, const string &pos_right1, const string &pos_right2)
ME_Sample mesample (const vector< Token > &vt, int i, const string &prepos)
double entropy (const vector< double > &v)
int bidir_train (const vector< Sentence > &vs, int para)
void generate_hypotheses (const int order, const Hypothesis &h, const multimap< string, string > &tag_dictionary, const vector< ME_Model > &vme, list< Hypothesis > &vh)
void bidir_decode_beam (vector< Token > &vt, const multimap< string, string > &tag_dictionary, const vector< ME_Model > &vme)
void decode_no_context (vector< Token > &vt, const ME_Model &me_none)
string bidir_postag (const string &s, const vector< ME_Model > &vme)
int push_stop_watch ()
void bidir_postagging (vector< Sentence > &vs, const multimap< string, string > &tag_dictionary, const vector< ME_Model > &vme)
Variables
const int UPDATE_WINDOW_SIZE = 2
const int BEAM_NUM = 1
const double BEAM_WINDOW = 0.01
const bool ONLY_VERTICAL_FEATURES = false
Function Documentation
void bidir_decode_beam (vector< Token > & vt, const multimap< string, string > & tag_dictionary, const vector< ME_Model > & vme)
Definition at line 292 of file bidir.cpp.
References BEAM_NUM, generate_hypotheses(), and Hypothesis::vt.
Referenced by bidir_postag(), bidir_postagging(), and la_manager::POSTaggerEnglish::tag().
string bidir_postag (const string & s, const vector< ME_Model > & vme)
Definition at line 347 of file bidir.cpp.
References bidir_decode_beam(), and tokenize().
void bidir_postagging (vector< Sentence > & vs, const multimap< string, string > & tag_dictionary, const vector< ME_Model > & vme)
Definition at line 402 of file bidir.cpp.
References bidir_decode_beam(), and push_stop_watch().
int bidir_train (const vector< Sentence > & vs, int para)
Definition at line 201 of file bidir.cpp.
References mesample(), ME_Model::save_to_file(), and ME_Model::train().
void decode_no_context (vector< Token > & vt, const ME_Model & me_none)
Definition at line 326 of file bidir.cpp.
References ME_Model::classify(), ME_Sample::label, and mesample().
double entropy (const vector< double > & v)
Definition at line 188 of file bidir.cpp.
Referenced by Hypothesis::Update().
void generate_hypotheses (const int order, const Hypothesis & h, const multimap< string, string > & tag_dictionary, const vector< ME_Model > & vme, list< Hypothesis > & vh)
Definition at line 251 of file bidir.cpp.
References Hypothesis::order, Hypothesis::prob, Hypothesis::Update(), UPDATE_WINDOW_SIZE, Hypothesis::vent, Hypothesis::vt, and Hypothesis::vvp.
Referenced by bidir_decode_beam().
ME_Sample mesample (const vector< Token > & vt, int i, const string & prepos)
Definition at line 148 of file bidir.cpp.
References ME_Sample::features, ME_Sample::label, and normalize().
ME_Sample mesample (const vector< Token > & vt, int i, const string & pos_left2, const string & pos_left1, const string & pos_right1, const string & pos_right2)
Definition at line 25 of file bidir.cpp.
References ME_Sample::features, ME_Sample::label, and ONLY_VERTICAL_FEATURES.
Referenced by bidir_train(), decode_no_context(), Hypothesis::Update(), and viterbi().
string normalize (const string & s)
Definition at line 22 of file postag.cpp.
Referenced by mesample().
int push_stop_watch ()
Definition at line 383 of file bidir.cpp.
Referenced by bidir_postagging().
void tokenize (const string & s1, list< string > & lt)
Definition at line 11 of file tokenize.cpp.
Referenced by bidir_postag(), and postag().
Variable Documentation
const int BEAM_NUM = 1
Definition at line 16 of file bidir.h.
Referenced by bidir_decode_beam().
const double BEAM_WINDOW = 0.01
Definition at line 17 of file bidir.h.
Referenced by Hypothesis::Update().
const bool ONLY_VERTICAL_FEATURES = false
Definition at line 19 of file bidir.h.
Referenced by mesample().
const int UPDATE_WINDOW_SIZE = 2
Definition at line 14 of file bidir.h.
Referenced by generate_hypotheses().