kmaOrange::WK_DaTrie_Node Class Reference
#include <daTrie.h>
Public Member Functions
WK_DaTrie_Node ()
void setRoot (void)
int getData (void)
void setData (int data)
Public Attributes
int mState
unsigned char * mpData
Detailed Description
Definition at line 45 of file daTrie.h.
Constructor & Destructor Documentation
kmaOrange::WK_DaTrie_Node::WK_DaTrie_Node () [inline]
Definition at line 51 of file daTrie.h.
References setRoot().
Member Function Documentation
int kmaOrange::WK_DaTrie_Node::getData (void) [inline]
Definition at line 293 of file daTrie.h.
References mpData.
Referenced by kmaOrange::SynonymContainer::insertSynonym(), kmaOrange::Dictionary::loadPreAnalysis(), kmaOrange::Dictionary::readCommonDictionary(), kmaOrange::Dictionary::readJosaEomiDictionary(), kmaOrange::AuxVerb::searchNgetInfoFromAvTrie(), kmaOrange::Dictionary::searchNgetInfoFromDivTrie(), kmaOrange::PreFinalEomi::searchNgetInfoFromEpTrie(), kmaOrange::Dictionary::searchNgetInfoFromJosaEomiTrie(), kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Dictionary::searchNgetInfoFromPosTrie(), kmaOrange::Dictionary::searchNgetInfoFromPreAnalTrie(), kmaOrange::SynonymContainer::searchNgetInfoFromSynonymTrie(), kmaOrange::PredicativeSuffix::searchNgetInfoFromXsdTrie(), kmaOrange::AuxVerb::setAVInfo(), kmaOrange::PreFinalEomi::setEPInfo(), and kmaOrange::PredicativeSuffix::setXSDInfo().
void kmaOrange::WK_DaTrie_Node::setData (int data) [inline]
Definition at line 305 of file daTrie.h.
References mpData.
Referenced by kmaOrange::SynonymContainer::insertSynonym(), kmaOrange::Dictionary::loadPreAnalysis(), kmaOrange::Dictionary::readCommonDictionary(), kmaOrange::Dictionary::readDivideInfo(), kmaOrange::Dictionary::readJosaEomiDictionary(), kmaOrange::Dictionary::readPostionInfo(), kmaOrange::AuxVerb::setAVInfo(), kmaOrange::PreFinalEomi::setEPInfo(), and kmaOrange::PredicativeSuffix::setXSDInfo().
void kmaOrange::WK_DaTrie_Node::setRoot (void) [inline]
Definition at line 287 of file daTrie.h.
References mpData, and mState.
Referenced by kmaOrange::WK_DaTrie::insertKey(), kmaOrange::WK_DaTrie::searchKey(), and WK_DaTrie_Node().
Member Data Documentation
unsigned char* kmaOrange::WK_DaTrie_Node::mpData
Definition at line 49 of file daTrie.h.
Referenced by kmaOrange::WK_DaTrie::findNode(), getData(), kmaOrange::WK_DaTrie::insertA(), kmaOrange::WK_DaTrie::insertB(), kmaOrange::WK_DaTrie::insertKey(), kmaOrange::WK_DaTrie::searchKey(), kmaOrange::AuxVerb::searchNgetInfoFromAvTrie(), kmaOrange::Dictionary::searchNgetInfoFromDivTrie(), kmaOrange::PreFinalEomi::searchNgetInfoFromEpTrie(), kmaOrange::Dictionary::searchNgetInfoFromJosaEomiTrie(), kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Dictionary::searchNgetInfoFromPosTrie(), kmaOrange::Dictionary::searchNgetInfoFromPreAnalTrie(), kmaOrange::StopWordContainer::searchNgetInfoFromStopWordTrie(), kmaOrange::SynonymContainer::searchNgetInfoFromSynonymTrie(), kmaOrange::PredicativeSuffix::searchNgetInfoFromXsdTrie(), setData(), and setRoot().
int kmaOrange::WK_DaTrie_Node::mState
Definition at line 48 of file daTrie.h.
Referenced by kmaOrange::WK_DaTrie::findNode(), kmaOrange::WK_DaTrie::insertA(), kmaOrange::WK_DaTrie::insertB(), kmaOrange::WK_DaTrie::insertKey(), kmaOrange::WK_DaTrie::searchKey(), kmaOrange::SynonymContainer::searchNgetInfoFromSynonymTrie(), and setRoot().
The documentation for this class was generated from the following file:
/disk/workspace-cpp/la-manager/include/kma/daTrie.h