kmaOrange::PredicativeSuffix Class Reference
This class manages predicative suffixes.
#include <PredicativeSuffix.h>
Public Member Functions
PredicativeSuffix ()
This function is a constructor of PredicativeSuffix object.
~PredicativeSuffix ()
This function is a destructor of PredicativeSuffix object.
int setXSDList ()
This function creates and initializes a WK_DaTrie object.
int setXSDInfo (XSDInfo &xsdInfo, int pos)
This function sets contents of static array XSDInfo structure into a WK_DaTrie object.
int searchNgetInfoFromXsdTrie (const StringEx &strex, InfoBuffer &infoBuffer, int len=0)
This function searches a WK_DaTrie object for input string.
int searchNgetInfoFromXsdTrie (const char *str, InfoBuffer &infoBuffer, int len=0)
InfoBuffer * searchNgetInfoFromXsdTrie (const StringEx &strex, int len=0)
This function searches a WK_DaTrie object for input string.
InfoBuffer * searchNgetInfoFromXsdTrie (const char *str, int len=0)
XSDInfo * getXSDInfo (int pos)
This function gets contents of static array XSDInfo structure.
Public Attributes
WK_DaTrie _xsdTrie
a WK_DaTrie object of predicative suffixes.
InfoBuffer _infoBuffer
temporary buffer.
Static Public Attributes
static XSDInfo _xsdInfoPoolList []
the list of information of predicative suffixes.
Detailed Description
This class manages predicative suffixes.
Date: 2008-11-06
Author: YoungMin Ahn & HeeGeun Park
Definition at line 38 of file PredicativeSuffix.h.
Constructor & Destructor Documentation
PredicativeSuffix::PredicativeSuffix ()
This function is a constructor of PredicativeSuffix object.
Date: 2008-11-06
Author: YoungMin Ahn & HeeGeun Park
Definition at line 19 of file PredicativeSuffix.cpp.
References setXSDList().
PredicativeSuffix::~PredicativeSuffix ()
This function is a destructor of PredicativeSuffix object.
Date: 2008-11-06
Author: YoungMin Ahn & HeeGeun Park
Definition at line 24 of file PredicativeSuffix.cpp.
Member Function Documentation
XSDInfo * PredicativeSuffix::getXSDInfo (int pos)
This function gets contents of static array XSDInfo structure.
Date: 2008-11-07
Author: YoungMin Ahn & HeeGeun Park
Parameters:
pos an integer - the index number of static array XSDInfo structure.
Returns: a pointer of XSDInfo structure - contents of static array XSDInfo structure.
Definition at line 28 of file PredicativeSuffix.cpp.
References _xsdInfoPoolList.
Referenced by kmaOrange::MAnalyzer::checkNanalyzeContraction_YUR(), and kmaOrange::MAnalyzer::checkNanalyzeXSDecliable().
InfoBuffer * PredicativeSuffix::searchNgetInfoFromXsdTrie (const char * str, int len = 0) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 132 of file PredicativeSuffix.cpp.
References _infoBuffer, kmaOrange::InfoBuffer::_posBuffer, _xsdTrie, kmaOrange::InfoBuffer::appendInfo(), kmaOrange::WK_DaTrie::findNode(), kmaOrange::WK_DaTrie_Node::getData(), and kmaOrange::WK_DaTrie_Node::mpData.
InfoBuffer * PredicativeSuffix::searchNgetInfoFromXsdTrie (const StringEx & strex, int len = 0)
This function searches a WK_DaTrie object for input string.
Date: 2008-11-07
Author: YoungMin Ahn & HeeGeun Park
Parameters:
strex an indirect referncing pointer of StringEx object - input string.
len an integer - the length of input string.
Returns: a pointer of InfoBuffer object - temporary storage.
Definition at line 127 of file PredicativeSuffix.cpp.
References StringEx::buffer(), StringEx::length(), and searchNgetInfoFromXsdTrie().
int PredicativeSuffix::searchNgetInfoFromXsdTrie (const char * str, InfoBuffer & infoBuffer, int len = 0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 95 of file PredicativeSuffix.cpp.
References _xsdTrie, kmaOrange::InfoBuffer::appendInfo(), kmaOrange::WK_DaTrie::findNode(), kmaOrange::WK_DaTrie_Node::getData(), kmaOrange::InfoBuffer::initialize(), and kmaOrange::WK_DaTrie_Node::mpData.
int PredicativeSuffix::searchNgetInfoFromXsdTrie (const StringEx & strex, InfoBuffer & infoBuffer, int len = 0)
This function searches a WK_DaTrie object for input string.
Date: 2008-11-07
Author: YoungMin Ahn & HeeGeun Park
Parameters:
strex an indirect referncing pointer of StringEx object - input string.
infoBuffer an indirect referncing pointer of InfoBuffer object - temporary storage.
len an integer - the length of input string.
Returns: an integer.
 0 - fail.
 1 - success.
Definition at line 90 of file PredicativeSuffix.cpp.
References StringEx::buffer(), and StringEx::length().
Referenced by kmaOrange::MAnalyzer::checkNanalyzeContraction_YUR(), kmaOrange::MAnalyzer::checkNanalyzeXSDecliable(), and searchNgetInfoFromXsdTrie().
int PredicativeSuffix::setXSDInfo (XSDInfo & xsdInfo, int pos)
This function sets contents of static array XSDInfo structure into a WK_DaTrie object.
Date: 2008-11-07
Author: YoungMin Ahn & HeeGeun Park
Parameters:
xsdInfo an indirect referncing pointer of XSDInfo structure - the list of predicative suffixes and these information.
pos an integer - the index number of the list of predicative suffixes and these information.
Returns: an integer.
 0 - fail.
 1 - success.
Definition at line 53 of file PredicativeSuffix.cpp.
References _xsdTrie, kmaOrange::WK_DaTrie_Node::getData(), kmaOrange::WK_DaTrie::insertKey(), kmaOrange::WK_DaTrie_Node::setData(), and kmaOrange::XSDInfo::transForm.
Referenced by setXSDList().
int PredicativeSuffix::setXSDList ()
This function creates and initializes a WK_DaTrie object.
Date: 2008-11-07
Author: YoungMin Ahn & HeeGeun Park
Returns: an integer.
 0 - fail.
 1 - success.
Definition at line 33 of file PredicativeSuffix.cpp.
References _xsdInfoPoolList, _xsdTrie, kmaOrange::WK_DaTrie::create(), and setXSDInfo().
Referenced by PredicativeSuffix().
Member Data Documentation
InfoBuffer kmaOrange::PredicativeSuffix::_infoBuffer
temporary buffer.
Definition at line 44 of file PredicativeSuffix.h.
Referenced by searchNgetInfoFromXsdTrie().
XSDInfo kmaOrange::PredicativeSuffix::_xsdInfoPoolList[] [static]
the list of information of predicative suffixes.
Definition at line 42 of file PredicativeSuffix.h.
Referenced by getXSDInfo(), and setXSDList().
WK_DaTrie kmaOrange::PredicativeSuffix::_xsdTrie
a WK_DaTrie object of predicative suffixes.
Definition at line 41 of file PredicativeSuffix.h.
Referenced by searchNgetInfoFromXsdTrie(), setXSDInfo(), and setXSDList().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/kma/PredicativeSuffix.h
/disk/workspace-cpp/la-manager/source/kma/PredicativeSuffix.cpp