kmaOrange::ExCP949 Class Reference
This class manages information of each syllable for KMA.
#include <ExtendedCP949.h>
Public Member Functions
ExCP949 ()
This function is a constructor of ExCP949 object.
~ExCP949 ()
This function is a destructor of ExCP949 object.
Static Public Member Functions
static SyllableInfo * getInfoEnd (char *strs)
This function gets the information in the list of structure SyllableInfo for the last syllable of input string.
static SyllableInfo * getInfo (char *strs)
This function gets the information in the list of structure SyllableInfo for the first syllable of input string.
static SyllableInfo * getInfo (short int pos)
This function gets the information of given index number in the list of structure SyllableInfo.
Static Public Attributes
static SyllableInfo SIT []
the list of structure SyllableInfo, which has information of each syllable.
static PositionInfo PT []
the list of structure PositionInfo, which has information for the hash operation.
static short int MAX_SIT = sizeof(SIT) / sizeof(struct SyllableInfo)
the number of elements in the list of structure SyllableInfo.
Detailed Description
This class manages information of each syllable for KMA.
Date: 2008-11-06
Author: HeeGeun Park
Definition at line 117 of file ExtendedCP949.h.
Constructor & Destructor Documentation
ExCP949::ExCP949 ()
This function is a constructor of ExCP949 object.
Date: 2008-11-06
Author: HeeGeun Park
Definition at line 12118 of file ExtendedCP949.cpp.
ExCP949::~ExCP949 ()
This function is a destructor of ExCP949 object.
Date: 2008-11-06
Author: HeeGeun Park
Definition at line 12122 of file ExtendedCP949.cpp.
Member Function Documentation
SyllableInfo * ExCP949::getInfo (short int pos) [static]
This function gets the information of given index number in the list of structure SyllableInfo.
Date: 2008-11-06
Author: HeeGeun Park
Parameters:
pos a short integer - given index number.
Returns: a pointer of a structure SyllableInfo.
Definition at line 12158 of file ExtendedCP949.cpp.
References MAX_SIT, and SIT.
SyllableInfo * ExCP949::getInfo (char * strs) [static]
This function gets the information in the list of structure SyllableInfo for the first syllable of input string.
Date: 2008-11-06
Author: HeeGeun Park
Parameters:
strs a pointer of a character - input string.
Returns: a pointer of a structure SyllableInfo.
Definition at line 12144 of file ExtendedCP949.cpp.
References MAX_SIT, PT, SIT, and kmaOrange::PositionInfo::startIndex.
Referenced by kmaOrange::MAnalyzer::analyzeSubHangulWordforSN(), kmaOrange::MAnalyzer::canBeVE(), kmaOrange::MAnalyzer::checkNanalyzeContraction_YUR(), kmaOrange::MAnalyzer::checkNanalyzeElision_hlL(), kmaOrange::MAnalyzer::checkNanalyzeElision_UH(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_BIUP(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_DIGT(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_RUH(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_RUR(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_SIOT(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_YUR(), kmaOrange::MAnalyzer::checkNanalyzePreEomi(), and kmaOrange::AuxVerb::searchNgetInfoFromAvTrie().
SyllableInfo * ExCP949::getInfoEnd (char * strs) [static]
This function gets the information in the list of structure SyllableInfo for the last syllable of input string.
Date: 2008-11-06
Author: HeeGeun Park
Parameters:
strs a pointer of a character - input string.
Returns: a pointer of a structure SyllableInfo.
Definition at line 12126 of file ExtendedCP949.cpp.
References MAX_SIT, PT, SIT, and kmaOrange::PositionInfo::startIndex.
Referenced by kmaOrange::MAnalyzer::analyzeDeclinableWord(), kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::analyzeHeadTail(), kmaOrange::MAnalyzer::analyzeSimpleWord(), kmaOrange::MAnalyzer::canBeVE(), kmaOrange::MAnalyzer::checkNanalyzeContraction_CHEE(), kmaOrange::MAnalyzer::checkNanalyzeContraction_KEE(), kmaOrange::MAnalyzer::checkNanalyzeContraction_KEH(), kmaOrange::MAnalyzer::checkNanalyzeContraction_WAE(), kmaOrange::MAnalyzer::checkNanalyzeContraction_WAHWOH(), kmaOrange::MAnalyzer::checkNanalyzeContraction_YUR(), kmaOrange::MAnalyzer::checkNanalyzeCopular(), kmaOrange::MAnalyzer::checkNanalyzeElision_hlL(), kmaOrange::MAnalyzer::checkNanalyzeElision_OO(), kmaOrange::MAnalyzer::checkNanalyzeElision_UH(), kmaOrange::MAnalyzer::checkNanalyzeElision_UR(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_BIUP(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_DIGT(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_HIUNG(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_RUH(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_RUR(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_SIOT(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_UR(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_YUR(), kmaOrange::MAnalyzer::checkNanalyzePreEomi(), kmaOrange::MAnalyzer::checkNanalyzeV_(), and kmaOrange::MAnalyzer::checkNanalyzeXSDecliable().
Member Data Documentation
short int ExCP949::MAX_SIT = sizeof(SIT) / sizeof(struct SyllableInfo) [static]
the number of elements in the list of structure SyllableInfo.
Definition at line 122 of file ExtendedCP949.h.
Referenced by getInfo(), and getInfoEnd().
PositionInfo ExCP949::PT [static]
Initial value:
 {

        { 0, DIV1 },    { 190,DIV1 },   { 380,DIV1 },   { 570,DIV1 },   { 760,DIV1 },   { 950,DIV1 },   { 1140,DIV1 },  { 1330,DIV1 },
        { 1520,DIV1 },  { 1710,DIV1 },  { 1900,DIV1 },  { 2090,DIV1 },  { 2280,DIV1 },  { 2470,DIV1 },  { 2660,DIV1 },  { 2850,DIV1 },
        { 3040,DIV1 },  { 3230,DIV1 },  { 3420,DIV1 },  { 3610,DIV1 },  { 3800,DIV1 },  { 3990,DIV1 },  { 4180,DIV1 },  { 4370,DIV1 },
        { 4560,DIV1 },  { 4750,DIV1 },  { 4940,DIV1 },  { 5130,DIV1 },  { 5320,DIV1 },  { 5510,DIV1 },  { 5700,DIV1 },  { 5890,DIV1 },
        { 6080,DIV1 },  { 6176,DIV1 },  { 6272,DIV1 },  { 6368,DIV1 },  { 6464,DIV1 },  { 6560,DIV1 },  { 6656,DIV1 },  { 6752,DIV1 },
        { 6848,DIV1 },  { 6944,DIV1 },  { 7040,DIV1 },  { 7136,DIV1 },  { 7232,DIV1 },  { 7328,DIV1 },  { 7424,DIV1 },  { 7520,DIV1 },
        { 7710,DIV1 },  { 7900,DIV1 },  { 8090,DIV1 },  { 8280,DIV1 },  { 8470,DIV1 },  { 8660,DIV1 },  { 8850,DIV1 },  { 9040,DIV1 },
        { 9230,DIV1 },  { 9420,DIV1 },  { 9610,DIV1 },  { 9800,DIV1 },  { 9990,DIV1 },  { 10180,DIV1 }, { 10370,DIV1 }, { 10560,DIV1 },
        { 10750,DIV1 }, { 10940,DIV1 }, { 11130,DIV1 }, { 11320,DIV1 }, { 11510,DIV1 }, { 11700,DIV1 }, { 11890,DIV2 }, { 11984,DIV2 }

}
the list of structure PositionInfo, which has information for the hash operation.
Definition at line 121 of file ExtendedCP949.h.
Referenced by getInfo(), and getInfoEnd().
SyllableInfo kmaOrange::ExCP949::SIT[] [static]
the list of structure SyllableInfo, which has information of each syllable.
Definition at line 120 of file ExtendedCP949.h.
Referenced by kmaOrange::MAnalyzer::checkNanalyzeContraction_WAE(), kmaOrange::MAnalyzer::checkNanalyzeContraction_WAHWOH(), kmaOrange::MAnalyzer::checkNanalyzeContraction_YUR(), kmaOrange::MAnalyzer::checkNanalyzeElision_hlL(), kmaOrange::MAnalyzer::checkNanalyzeElision_OO(), kmaOrange::MAnalyzer::checkNanalyzeElision_UH(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_BIUP(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_DIGT(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_HIUNG(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_RUH(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_RUR(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_SIOT(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_UR(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_YUR(), kmaOrange::MAnalyzer::checkNanalyzePreEomi(), kmaOrange::MAnalyzer::checkNanalyzeV_(), kmaOrange::MAnalyzer::checkNanalyzeXSDecliable(), getInfo(), and getInfoEnd().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/kma/ExtendedCP949.h
/disk/workspace-cpp/la-manager/source/kma/ExtendedCP949.cpp