la_manager::KoreanNounFilter Class Reference
#include <NounFilter.h>
Public Member Functions
KoreanNounFilter (string knowledgePath=`../resource/knowledge`)
~KoreanNounFilter ()
bool analyze (const TermList &Input, TermList &Output)
analyze interface
bool analyze (TermList &InOutPut)
analyze interface
Static Public Attributes
static const int sTagSetNOUN_ = (NNG|NNP|NNU|NNR)
static const int sTagSetNOUN2_ = (NNP|NNU)
static const int sTagSetJOSA_ = (JK|JX|JC|VC)
static const int sTagSetVERB_ = (VV|VA|VX)
static const int sTagSetEOMI_ = (EM|ETM|ETN|EP)
Private Attributes
WK_Knowledge * pK
WK_Eojul * pE
WK_Analyzer * pA
Detailed Description
Definition at line 40 of file NounFilter.h.
Constructor & Destructor Documentation
la_manager::KoreanNounFilter::KoreanNounFilter (string knowledgePath = `../resource/knowledge`) [inline]
< ?
Definition at line 52 of file NounFilter.h.
References WK_Analyzer::createObject(), WK_Eojul::createObject(), WK_Knowledge::createObject(), WK_Eojul::initialize(), WK_Knowledge::loadKnowledge(), WK_Knowledge::loadPreAnalysis(), WK_Knowledge::loadUserNoun(), pA, pE, pK, WK_Analyzer::setExOption(), WK_Analyzer::setOption(), TAGGING, and WKO_OPTION_N_BEST.
la_manager::KoreanNounFilter::~KoreanNounFilter () [inline]
Definition at line 69 of file NounFilter.h.
References pA, pE, and pK.
Member Function Documentation
bool la_manager::KoreanNounFilter::analyze (TermList & InOutPut) [virtual]
analyze interface
Parameters:
InOutPut input (also output) term list This class analyze input terms and generate the output
Implements la_manager::Analyzer.
Definition at line 51 of file NounFilter.cpp.
References WK_Eojul::getCount(), WK_Eojul::getOneBestIndex(), WK_Eojul::getPOS(), pA, pE, WK_Analyzer::runWithEojul(), WK_Eojul::setString(), and sTagSetNOUN_.
bool la_manager::KoreanNounFilter::analyze (const TermList & Input, TermList & Output) [virtual]
analyze interface
Parameters:
Input input term list
output output term list This class analyze input terms and generate the output
Implements la_manager::Analyzer.
Definition at line 46 of file NounFilter.cpp.
Member Data Documentation
WK_Analyzer* la_manager::KoreanNounFilter::pA [private]
Definition at line 43 of file NounFilter.h.
Referenced by analyze(), KoreanNounFilter(), and ~KoreanNounFilter().
WK_Eojul* la_manager::KoreanNounFilter::pE [private]
Definition at line 42 of file NounFilter.h.
Referenced by analyze(), KoreanNounFilter(), and ~KoreanNounFilter().
WK_Knowledge* la_manager::KoreanNounFilter::pK [private]
Definition at line 41 of file NounFilter.h.
Referenced by KoreanNounFilter(), and ~KoreanNounFilter().
const int la_manager::KoreanNounFilter::sTagSetEOMI_ = (EM|ETM|ETN|EP) [static]
Definition at line 50 of file NounFilter.h.
const int la_manager::KoreanNounFilter::sTagSetJOSA_ = (JK|JX|JC|VC) [static]
Definition at line 48 of file NounFilter.h.
const int la_manager::KoreanNounFilter::sTagSetNOUN2_ = (NNP|NNU) [static]
Definition at line 47 of file NounFilter.h.
const int la_manager::KoreanNounFilter::sTagSetNOUN_ = (NNG|NNP|NNU|NNR) [static]
Definition at line 46 of file NounFilter.h.
Referenced by analyze().
const int la_manager::KoreanNounFilter::sTagSetVERB_ = (VV|VA|VX) [static]
Definition at line 49 of file NounFilter.h.
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/NounFilter.h
/disk/workspace-cpp/la-manager/source/NounFilter.cpp