kmaOrange::DecomposeNNP Class Reference
This class manages to decompose a compound noun.
#include <DecomposeNNP.h>
Public Member Functions
DecomposeNNP ()
This function is a constructor of DecomposeNNP object.
~DecomposeNNP ()
This function is a destructor of DecomposeNNP object.
int getQueryCandidates (const StringEx &nnp)
This function gets only index words in elements of generated candidates.
void printQueries ()
This function prints only index words in elements of generated candidates on screen.
char * getDecomposedInformation (const StringEx &nnp, int mode=0)
This function gets decomposed information for an input string.
unsigned int getSyllableLength (const StringEx &word)
This function gets the syllable length of an input string.
double getWeight (int index)
This function gets the weight score of each candidate.
void setDicionary (Dictionary *dic)
This function sets the Dictionary object.
Private Member Functions
unsigned int generateCandidates (int num, int index, int cnt)
This function generates candidates of decomposing a compound noun.
void initializeCnoun ()
This function initializes several global variables and objects.
void checkPattern (int numofcandidates)
This function checks and removes overlapped candidates.
void addQuery (const StringEx &query)
This function adds a string in the list of idnex words.
void generateSimpleWord (char *divpattern)
This function generates candidates using decomposing patterns in the NNP dictionary.
void printDivPattern (char *divpattern)
This function prints candidates using decomposing patterns in the NNP dictionary on screen.
int searchAllRegisteredN_ ()
This function searches all noun class, which the partial string of input string is included in the system dictionaries.
int decomposing (const StringEx &nnp)
This function calls various functions about decomposing a compound noun.
int isDigit (const char ch)
This function checks whether an input character is a digit or not.
int isXP (const StringEx &word)
This function checks whether an input string is a prefix or not.
int isXSN (const StringEx &word)
This function checks whether an input string is a suffix or not.
int isXSNXSN (const StringEx &word)
This function checks whether an input string is a 2-syllables suffix or not.
int isCONJ (const StringEx &word)
This function checks whether an input string is a conjunction or not.
int searchList (char **list, unsigned int numoflist, const StringEx &word)
This function searches a given list for an input string.
int addTuple (int num, int cnt, int pattern, char info)
This function adds an element in the list of NounsTuple object.
int addNNP (int num, int cnt, int index, char info)
This function adds an entry of the NNP dictionary to the list of NounsTuple object.
int getFreqofPattern (int dcpattern)
This function gets the weight score of a decomposing pattern for the length of input string.
int postProcessDcInfo (int cnt, int tag, int len)
This function executes the post-process of decomposing a compound noun.
double scoringPattern (struct compoundNoun *dcpattern)
This function calculates the score of each candidate.
Private Attributes
unsigned int MAX_dcp
the number of decomposing pattern in a compound noun.
unsigned int numberofxpList
the number of 1-syllable prefixes.
unsigned int numberofxsnList
the number of 1-syllable suffixes.
unsigned int numberofxsnxsnList
the number of 2-syllables suffixes.
unsigned int numberofconjList
the number of 1-syllable conjunction.
NounsTuple tupleN_ [MAX_CANDIDATE]
the list of the list of elements in a compound noun.
double sumofweight [MAX_CANDIDATE]
the sum of weightScore in the list of elements in a compound noun.
int weightlist [MAX_CANDIDATE]
the list of the index number, which the value of variable weightScore has more than critical value.
int cntquery
the number of index words in the list of elements in a compound noun.
int _flag
this variable shows whether each starting index of elements in a compound noun is overlapped or not.
int _total
the number of the total list of decomposed elements in a compound noun.
int _addedcnt
this is a temporary variable for recursively decomposing a compound noun.
int _nnpflag
this variable shows whether the list of elements in a compound noun includes entries of the NNP dictionary or not.
int _nnplen
this is a temporary variable to add a NounsTuple object and shows the length of an element.
int _mode
StringEx querycandidates [(MAX_CANDIDATE *MAX_NOUN)]
the list of index words in the list of elements in a compound noun.
StringEx _divpt
the decomposing pattern of an entry in the NNP dictionary.
StringEx strDcInfo
StringEx tmpDcInfo
StringEx addDcInfo
this is a temporary StringEx object for pre-process and post-process of decomposing a compound noun.
StringEx _nnp
the original input string.
char DcInfo [BUFFER_SIZE_DCINFO]
the information of entirely decomposed pattern for the input string. This information is forwarded to the analyzing module.
ListEx< SearchInfo > _allN_List
the list of all noun class, which the partial string of input string is included in the system dictionaries.
Dictionary * _pdic
the object of system dictionaries.
Static Private Attributes
static struct decomposingPattern dcp []
the list of decomposing pattern in a compound noun.
static char * xpList []
the list of 1-syllable prefixes.
static char * xsnList []
the list of 1-syllable suffixes.
static char * xsnxsnList []
the list of 2-syllables suffixes.
static char * conjList []
the list of 1-syllable conjunction.
static StringEx _specialPattern = `:12:21:1U2:2U1:U12:U21:U2Y1:I2U1:2UB1:2U2:U22:U4:`
the special decomposing pattern for post-process is stored.
Detailed Description
This class manages to decompose a compound noun.
Date: 2008-11-04
Author: HeeGeun Park
Definition at line 61 of file DecomposeNNP.h.
Constructor & Destructor Documentation
DecomposeNNP::DecomposeNNP ()
This function is a constructor of DecomposeNNP object.
Date: 2008-11-05
Author: HeeGeun Park
Definition at line 84 of file DecomposeNNP.cpp.
References conjList, dcp, initializeCnoun(), MAX_dcp, numberofconjList, numberofxpList, numberofxsnList, numberofxsnxsnList, xpList, xsnList, and xsnxsnList.
DecomposeNNP::~DecomposeNNP ()
This function is a destructor of DecomposeNNP object.
Date: 2008-11-05
Author: HeeGeun Park
Definition at line 95 of file DecomposeNNP.cpp.
Member Function Documentation
int DecomposeNNP::addNNP (int num, int cnt, int index, char info) [private]
This function adds an entry of the NNP dictionary to the list of NounsTuple object.
Date: 2008-11-05
Author: HeeGeun Park
Parameters:
num an integer - the index number of the tupleN_, which is an array of NounsTuple object.
cnt an integer - the index number of the cnoun in the NounsTuple object.
index an integer - the index number of the _allN_List, which is a list of SearchInfo object.
Returns: an integer.
Definition at line 940 of file DecomposeNNP.cpp.
References _divpt, _nnpflag, addTuple(), kmaOrange::NounsTuple::cnoun, kmaOrange::NounsTuple::index, isDigit(), StringEx::length(), tupleN_, and kmaOrange::compoundNoun::weight.
Referenced by generateCandidates().
void DecomposeNNP::addQuery (const StringEx & query) [private]
This function adds a string in the list of idnex words.
Date: 2008-11-05
Author: HeeGeun Park
Parameters:
query an indirect referncing pointer of a constant StringEx object - a string.
Definition at line 765 of file DecomposeNNP.cpp.
References cntquery, and querycandidates.
Referenced by generateSimpleWord().
int DecomposeNNP::addTuple (int num, int cnt, int pattern, char info) [private]
This function adds an element in the list of NounsTuple object.
Date: 2008-11-05
Author: HeeGeun Park
Parameters:
num an integer - the index number of the tupleN_, which is an array of NounsTuple object.
cnt an integer - the index number of the cnoun in the NounsTuple object.
pattern an integer - the syllable length of an element.
info a character - the information of an element in a compound noun.
Returns: an integer.
Definition at line 906 of file DecomposeNNP.cpp.
References kmaOrange::NounsTuple::cnoun, kmaOrange::compoundNoun::info, kmaOrange::compoundNoun::pattern, tupleN_, and kmaOrange::compoundNoun::weight.
Referenced by addNNP(), and generateCandidates().
void DecomposeNNP::checkPattern (int numofcandidates) [private]
This function checks and removes overlapped candidates.
Date: 2008-11-05
Author: HeeGeun Park
Parameters:
numofcandidates an integer - the number of candidates.
Definition at line 610 of file DecomposeNNP.cpp.
References kmaOrange::NounsTuple::cnoun, MAX_NOUN, kmaOrange::compoundNoun::pattern, sumofweight, and tupleN_.
Referenced by decomposing().
int DecomposeNNP::decomposing (const StringEx & nnp) [private]
This function calls various functions about decomposing a compound noun.
Date: 2008-11-05
Author: HeeGeun Park
Parameters:
nnp an indirect referncing pointer of a constant StringEx object.
Returns: an integer - the number of decomposed candidates, which is removed duplication.
Definition at line 774 of file DecomposeNNP.cpp.
References _addedcnt, _flag, _nnp, _nnpflag, _nnplen, _pdic, _total, checkPattern(), kmaOrange::NounsTuple::cnoun, generateCandidates(), StringEx::getSubString(), getSyllableLength(), kmaOrange::compoundNoun::info, isCONJ(), isXP(), MAX_NOUN, SearchInfo::mti, NBI_INDEPENDENT, NNb, NNg, NNi, Np, kmaOrange::compoundNoun::pattern, SearchInfo::pinfoNNB, scoringPattern(), kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), sumofweight, MainTrieInfo::tag, tupleN_, kmaOrange::compoundNoun::weight, and kmaOrange::NounsTuple::weightScore.
Referenced by getDecomposedInformation(), and getQueryCandidates().
unsigned int DecomposeNNP::generateCandidates (int num, int index, int cnt) [private]
This function generates candidates of decomposing a compound noun.
Date: 2008-11-05
Author: HeeGeun Park
Parameters:
num an integer - the index number of the tupleN_, which is an array of NounsTuple object.
index an integer - the index number of the _allN_List, which is a list of SearchInfo object.
cnt an integer - the index number of the cnoun in the NounsTuple object.
Returns: an unsigned integer - the number of the total list of decomposed elements in a compound noun.
Definition at line 977 of file DecomposeNNP.cpp.
References _addedcnt, _allN_List, _divpt, _flag, _mode, _nnp, _nnpflag, _nnplen, _pdic, _total, addNNP(), addTuple(), kmaOrange::NounsTuple::cnoun, kmaOrange::NounsTuple::cntElements, StringEx::getBuffer(), StringEx::getIndex(), StringEx::getSubString(), kmaOrange::NounsTuple::index, kmaOrange::compoundNoun::info, isXP(), isXSN(), isXSNXSN(), J_, SearchJEInfo::jeti, MAX_CANDIDATE, MAX_NOUN, NNg, NNi, NNu, Np, kmaOrange::Dictionary::searchNgetInfoFromJosaEomiTrie(), JosaEomiTrieInfo::tag, tupleN_, and kmaOrange::compoundNoun::weight.
Referenced by decomposing().
void DecomposeNNP::generateSimpleWord (char * divpattern) [private]
This function generates candidates using decomposing patterns in the NNP dictionary.
Date: 2008-11-05
Author: HeeGeun Park
Parameters:
divpattern a pointer of a character - a decomposing pattern.
Definition at line 673 of file DecomposeNNP.cpp.
References _nnp, _total, addQuery(), kmaOrange::NounsTuple::cnoun, StringEx::getSubString(), kmaOrange::compoundNoun::info, MAX_NOUN, kmaOrange::compoundNoun::pattern, and tupleN_.
Referenced by getQueryCandidates().
char * DecomposeNNP::getDecomposedInformation (const StringEx & nnp, int mode = 0)
This function gets decomposed information for an input string.
Date: 2008-11-06
Author: HeeGeun Park
Parameters:
nnp an indirect referncing pointer of a constant StringEx object - input string.
mode an integer - decomposing mode.
Returns: a pointer of a character - the decomposed information.
Definition at line 177 of file DecomposeNNP.cpp.
References _divpt, _mode, _nnp, _nnplen, _pdic, BUFFER_SIZE_DCINFO, kmaOrange::NounsTuple::cnoun, CRITICAL_VALUE, DcInfo, decomposing(), StringEx::endWith(), StringEx::getBuffer(), StringEx::getIndex(), StringEx::getNumberOfChar(), kmaOrange::compoundNoun::info, initializeCnoun(), isDigit(), StringEx::isEmpty(), isXSN(), StringEx::length(), MAX_CANDIDATE, MAX_NOUN, SearchInfo::mti, N_, NBI_DEPENDENT, NBI_INDEPENDENT, NBI_UNIT, NNb, NNg, NNp, NNu, Np, kmaOrange::compoundNoun::pattern, SearchInfo::pinfoNNB, SearchInfo::pinfoNNP, SearchInfo::pinfoNNU, postProcessDcInfo(), searchAllRegisteredN_(), kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), MainTrieInfo::tag, tupleN_, and weightlist.
Referenced by kmaOrange::MAnalyzer::analyzeEojul_NNR().
int DecomposeNNP::getFreqofPattern (int dcpattern) [private]
This function gets the weight score of a decomposing pattern for the length of input string.
Date: 2008-11-05
Author: HeeGeun Park
Parameters:
dcpattern an integer - the decomposing pattern for the length of input string.
Returns: an integer - the weight score.
Definition at line 1577 of file DecomposeNNP.cpp.
References dcp, MAX_dcp, and kmaOrange::decomposingPattern::weight.
Referenced by scoringPattern().
int DecomposeNNP::getQueryCandidates (const StringEx & nnp)
This function gets only index words in elements of generated candidates.
Date: 2008-11-06
Author: HeeGeun Park
Parameters:
nnp an indirect referncing pointer of a constant StringEx object - input string.
Returns: an integer - the number of index words.
Definition at line 638 of file DecomposeNNP.cpp.
References _divpt, _nnp, _pdic, _total, cntquery, decomposing(), generateSimpleWord(), StringEx::getBuffer(), StringEx::getIndex(), StringEx::getLength(), StringEx::getSubString(), initializeCnoun(), StringEx::length(), SearchInfo::mti, NNp, SearchInfo::pinfoNNP, printDivPattern(), printQueries(), kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), and MainTrieInfo::tag.
unsigned int DecomposeNNP::getSyllableLength (const StringEx & word)
This function gets the syllable length of an input string.
Date: 2008-11-06
Author: HeeGeun Park
Parameters:
word an indirect referncing pointer of a constant StringEx object - input string.
Returns: an unsigned integer - the syllable length of an input string.
Definition at line 146 of file DecomposeNNP.cpp.
References StringEx::getLength().
Referenced by decomposing().
double DecomposeNNP::getWeight (int index)
This function gets the weight score of each candidate.
Date: 2008-11-06
Author: HeeGeun Park
Parameters:
index an integer - the index number of the tupleN_, which is an array of NounsTuple object.
Returns: a double - the weight score of each candidate.
Definition at line 171 of file DecomposeNNP.cpp.
References tupleN_, weightlist, and kmaOrange::NounsTuple::weightScore.
Referenced by kmaOrange::MAnalyzer::analyzeEojul_NNR().
void DecomposeNNP::initializeCnoun () [private]
This function initializes several global variables and objects.
Date: 2008-11-05
Author: HeeGeun Park
Definition at line 99 of file DecomposeNNP.cpp.
References cntquery, MAX_CANDIDATE, sumofweight, tupleN_, and weightlist.
Referenced by DecomposeNNP(), getDecomposedInformation(), and getQueryCandidates().
int DecomposeNNP::isCONJ (const StringEx & word) [private]
This function checks whether an input string is a conjunction or not.
Date: 2008-11-05
Author: HeeGeun Park
Parameters:
word an indirect referncing pointer of a constant StringEx object - input string.
Returns: an integer.
 -1 - not conjunction.
 1 - conjunction.
Definition at line 141 of file DecomposeNNP.cpp.
References conjList, numberofconjList, and searchList().
Referenced by decomposing().
int DecomposeNNP::isDigit (const char ch) [private]
This function checks whether an input character is a digit or not.
Date: 2008-11-05
Author: HeeGeun Park
Parameters:
ch a constant character - input character.
Returns: an integer.
 0 - not digit.
 1 - digit.
Definition at line 164 of file DecomposeNNP.cpp.
Referenced by addNNP(), and getDecomposedInformation().
int DecomposeNNP::isXP (const StringEx & word) [private]
This function checks whether an input string is a prefix or not.
Date: 2008-11-05
Author: HeeGeun Park
Parameters:
word an indirect referncing pointer of a constant StringEx object - input string.
Returns: an integer.
 -1 - not prefix.
 1 - prefix.
Definition at line 126 of file DecomposeNNP.cpp.
References numberofxpList, searchList(), and xpList.
Referenced by decomposing(), generateCandidates(), and postProcessDcInfo().
int DecomposeNNP::isXSN (const StringEx & word) [private]
This function checks whether an input string is a suffix or not.
Date: 2008-11-05
Author: HeeGeun Park
Parameters:
word an indirect referncing pointer of a constant StringEx object - input string.
Returns: an integer.
 -1 - not suffix.
 1 - suffix.
Definition at line 131 of file DecomposeNNP.cpp.
References numberofxsnList, searchList(), and xsnList.
Referenced by generateCandidates(), getDecomposedInformation(), and postProcessDcInfo().
int DecomposeNNP::isXSNXSN (const StringEx & word) [private]
This function checks whether an input string is a 2-syllables suffix or not.
Date: 2008-11-05
Author: HeeGeun Park
Parameters:
word an indirect referncing pointer of a constant StringEx object - input string.
Returns: an integer.
 -1 - not 2-syllables suffix.
 1 - 2-syllables suffix.
Definition at line 136 of file DecomposeNNP.cpp.
References numberofxsnxsnList, searchList(), and xsnxsnList.
Referenced by generateCandidates().
int DecomposeNNP::postProcessDcInfo (int cnt, int tag, int len) [private]
This function executes the post-process of decomposing a compound noun.
Date: 2008-11-05
Author: HeeGeun Park
Parameters:
cnt an integer - the number of elements in the array DcInfo.
tag an integer - the value of the POS tag for a entire input string.
len an integer - the syllable length of a input string.
Returns: an integer.
Definition at line 429 of file DecomposeNNP.cpp.
References _mode, _nnp, _pdic, _specialPattern, addDcInfo, StringEx::buffer(), DcInfo, StringEx::getBuffer(), StringEx::getIndex(), StringEx::getNumberOfChar(), StringEx::getNumberOfStr(), StringEx::getSubString(), isXP(), isXSN(), StringEx::length(), SearchInfo::mti, NNg, NNp, StringEx::replaceString(), kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), strDcInfo, MainTrieInfo::tag, and tmpDcInfo.
Referenced by getDecomposedInformation().
void DecomposeNNP::printDivPattern (char * divpattern) [private]
This function prints candidates using decomposing patterns in the NNP dictionary on screen.
Date: 2008-11-05
Author: HeeGeun Park
Parameters:
divpattern a pointer of a character - a decomposing pattern.
Definition at line 715 of file DecomposeNNP.cpp.
References _nnp, and StringEx::getSubString().
Referenced by getQueryCandidates().
void DecomposeNNP::printQueries ()
This function prints only index words in elements of generated candidates on screen.
Date: 2008-11-06
Author: HeeGeun Park
Definition at line 758 of file DecomposeNNP.cpp.
References cntquery, and querycandidates.
Referenced by getQueryCandidates().
double DecomposeNNP::scoringPattern (struct compoundNoun * dcpattern) [private]
This function calculates the score of each candidate.
Date: 2008-11-05
Author: HeeGeun Park
Parameters:
dcpattern a pointer of struct compoundNoun - the information list of generated candidates.
Returns: a double - the score of a candidate.
Definition at line 1593 of file DecomposeNNP.cpp.
References _nnp, _pdic, DivideInfo::freq, PosInfo::freq_first, PosInfo::freq_last, PosInfo::freq_middle, StringEx::getBuffer(), getFreqofPattern(), StringEx::getSubString(), MAX_NOUN, kmaOrange::compoundNoun::pattern, kmaOrange::Dictionary::searchNgetInfoFromDivTrie(), and kmaOrange::Dictionary::searchNgetInfoFromPosTrie().
Referenced by decomposing().
int DecomposeNNP::searchAllRegisteredN_ () [private]
This function searches all noun class, which the partial string of input string is included in the system dictionaries.
Date: 2008-11-05
Author: HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a constant StringEx object.
Returns: an integer.
Definition at line 880 of file DecomposeNNP.cpp.
References _allN_List, _nnp, _nnplen, _pdic, StringEx::buffer(), and kmaOrange::Dictionary::searchNgetInfoFromMainTrie().
Referenced by getDecomposedInformation().
int DecomposeNNP::searchList (char ** list, unsigned int numoflist, const StringEx & word) [private]
This function searches a given list for an input string.
Date: 2008-11-05
Author: HeeGeun Park
Parameters:
list a pointer of character pointer - given list.
numoflist an unsigned integer - the number of elements in a given list
word an indirect referncing pointer of a constant StringEx object - input string.
Returns: an integer.
 -1 - not an element of given list.
 1 - an element of given list.
Definition at line 108 of file DecomposeNNP.cpp.
Referenced by isCONJ(), isXP(), isXSN(), and isXSNXSN().
void kmaOrange::DecomposeNNP::setDicionary (Dictionary * dic) [inline]
This function sets the Dictionary object.
Date: 2008-11-06
Author: HeeGeun Park
Parameters:
dic a pointer of Dictionary object.
Definition at line 356 of file DecomposeNNP.h.
References _pdic.
Referenced by kmaOrange::MAnalyzer::setDefault(), and kmaOrange::MAnalyzer::setKnowledge().
Member Data Documentation
int kmaOrange::DecomposeNNP::_addedcnt [private]
this is a temporary variable for recursively decomposing a compound noun.
Definition at line 84 of file DecomposeNNP.h.
Referenced by decomposing(), and generateCandidates().
ListEx<SearchInfo> kmaOrange::DecomposeNNP::_allN_List [private]
the list of all noun class, which the partial string of input string is included in the system dictionaries.
Definition at line 99 of file DecomposeNNP.h.
Referenced by generateCandidates(), and searchAllRegisteredN_().
StringEx kmaOrange::DecomposeNNP::_divpt [private]
the decomposing pattern of an entry in the NNP dictionary.
Definition at line 90 of file DecomposeNNP.h.
Referenced by addNNP(), generateCandidates(), getDecomposedInformation(), and getQueryCandidates().
int kmaOrange::DecomposeNNP::_flag [private]
this variable shows whether each starting index of elements in a compound noun is overlapped or not.
Definition at line 82 of file DecomposeNNP.h.
Referenced by decomposing(), and generateCandidates().
int kmaOrange::DecomposeNNP::_mode [private]
Definition at line 87 of file DecomposeNNP.h.
Referenced by generateCandidates(), getDecomposedInformation(), and postProcessDcInfo().
StringEx kmaOrange::DecomposeNNP::_nnp [private]
the original input string.
Definition at line 93 of file DecomposeNNP.h.
Referenced by decomposing(), generateCandidates(), generateSimpleWord(), getDecomposedInformation(), getQueryCandidates(), postProcessDcInfo(), printDivPattern(), scoringPattern(), and searchAllRegisteredN_().
int kmaOrange::DecomposeNNP::_nnpflag [private]
this variable shows whether the list of elements in a compound noun includes entries of the NNP dictionary or not.
Definition at line 85 of file DecomposeNNP.h.
Referenced by addNNP(), decomposing(), and generateCandidates().
int kmaOrange::DecomposeNNP::_nnplen [private]
this is a temporary variable to add a NounsTuple object and shows the length of an element.
Definition at line 86 of file DecomposeNNP.h.
Referenced by decomposing(), generateCandidates(), getDecomposedInformation(), and searchAllRegisteredN_().
Dictionary* kmaOrange::DecomposeNNP::_pdic [private]
the object of system dictionaries.
Definition at line 100 of file DecomposeNNP.h.
Referenced by decomposing(), generateCandidates(), getDecomposedInformation(), getQueryCandidates(), postProcessDcInfo(), scoringPattern(), searchAllRegisteredN_(), and setDicionary().
StringEx DecomposeNNP::_specialPattern = `:12:21:1U2:2U1:U12:U21:U2Y1:I2U1:2UB1:2U2:U22:U4:` [static, private]
the special decomposing pattern for post-process is stored.
Definition at line 95 of file DecomposeNNP.h.
Referenced by postProcessDcInfo().
int kmaOrange::DecomposeNNP::_total [private]
the number of the total list of decomposed elements in a compound noun.
Definition at line 83 of file DecomposeNNP.h.
Referenced by decomposing(), generateCandidates(), generateSimpleWord(), and getQueryCandidates().
StringEx kmaOrange::DecomposeNNP::addDcInfo [private]
this is a temporary StringEx object for pre-process and post-process of decomposing a compound noun.
Definition at line 92 of file DecomposeNNP.h.
Referenced by postProcessDcInfo().
int kmaOrange::DecomposeNNP::cntquery [private]
the number of index words in the list of elements in a compound noun.
Definition at line 81 of file DecomposeNNP.h.
Referenced by addQuery(), getQueryCandidates(), initializeCnoun(), and printQueries().
char * DecomposeNNP::conjList [static, private]
Initial value:
 {
        "", "", "", "", "", ""
}
the list of 1-syllable conjunction.
Definition at line 68 of file DecomposeNNP.h.
Referenced by DecomposeNNP(), and isCONJ().
char kmaOrange::DecomposeNNP::DcInfo[BUFFER_SIZE_DCINFO] [private]
the information of entirely decomposed pattern for the input string. This information is forwarded to the analyzing module.
Definition at line 97 of file DecomposeNNP.h.
Referenced by getDecomposedInformation(), and postProcessDcInfo().
struct decomposingPattern kmaOrange::DecomposeNNP::dcp[] [static, read, private]
the list of decomposing pattern in a compound noun.
Definition at line 64 of file DecomposeNNP.h.
Referenced by DecomposeNNP(), and getFreqofPattern().
unsigned int kmaOrange::DecomposeNNP::MAX_dcp [private]
the number of decomposing pattern in a compound noun.
Definition at line 70 of file DecomposeNNP.h.
Referenced by DecomposeNNP(), and getFreqofPattern().
unsigned int kmaOrange::DecomposeNNP::numberofconjList [private]
the number of 1-syllable conjunction.
Definition at line 74 of file DecomposeNNP.h.
Referenced by DecomposeNNP(), and isCONJ().
unsigned int kmaOrange::DecomposeNNP::numberofxpList [private]
the number of 1-syllable prefixes.
Definition at line 71 of file DecomposeNNP.h.
Referenced by DecomposeNNP(), and isXP().
unsigned int kmaOrange::DecomposeNNP::numberofxsnList [private]
the number of 1-syllable suffixes.
Definition at line 72 of file DecomposeNNP.h.
Referenced by DecomposeNNP(), and isXSN().
unsigned int kmaOrange::DecomposeNNP::numberofxsnxsnList [private]
the number of 2-syllables suffixes.
Definition at line 73 of file DecomposeNNP.h.
Referenced by DecomposeNNP(), and isXSNXSN().
StringEx kmaOrange::DecomposeNNP::querycandidates[(MAX_CANDIDATE *MAX_NOUN)] [private]
the list of index words in the list of elements in a compound noun.
Definition at line 89 of file DecomposeNNP.h.
Referenced by addQuery(), and printQueries().
StringEx kmaOrange::DecomposeNNP::strDcInfo [private]
Definition at line 92 of file DecomposeNNP.h.
Referenced by postProcessDcInfo().
double kmaOrange::DecomposeNNP::sumofweight[MAX_CANDIDATE] [private]
the sum of weightScore in the list of elements in a compound noun.
Definition at line 78 of file DecomposeNNP.h.
Referenced by checkPattern(), decomposing(), and initializeCnoun().
StringEx kmaOrange::DecomposeNNP::tmpDcInfo [private]
Definition at line 92 of file DecomposeNNP.h.
Referenced by postProcessDcInfo().
NounsTuple kmaOrange::DecomposeNNP::tupleN_[MAX_CANDIDATE] [private]
the list of the list of elements in a compound noun.
Definition at line 76 of file DecomposeNNP.h.
Referenced by addNNP(), addTuple(), checkPattern(), decomposing(), generateCandidates(), generateSimpleWord(), getDecomposedInformation(), getWeight(), and initializeCnoun().
int kmaOrange::DecomposeNNP::weightlist[MAX_CANDIDATE] [private]
the list of the index number, which the value of variable weightScore has more than critical value.
Definition at line 79 of file DecomposeNNP.h.
Referenced by getDecomposedInformation(), getWeight(), and initializeCnoun().
char * DecomposeNNP::xpList [static, private]
Initial value:
 { 
        "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", ""
}
the list of 1-syllable prefixes.
Definition at line 65 of file DecomposeNNP.h.
Referenced by DecomposeNNP(), and isXP().
char * DecomposeNNP::xsnList [static, private]
Initial value:
 { 
        "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "",
        "", ""
}
the list of 1-syllable suffixes.
Definition at line 66 of file DecomposeNNP.h.
Referenced by DecomposeNNP(), and isXSN().
char * DecomposeNNP::xsnxsnList [static, private]
Initial value:
 {
        "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", ""
}
the list of 2-syllables suffixes.
Definition at line 67 of file DecomposeNNP.h.
Referenced by DecomposeNNP(), and isXSNXSN().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/kma/DecomposeNNP.h
/disk/workspace-cpp/la-manager/source/kma/DecomposeNNP.cpp