kmaOrange::Buffer Class Reference
This is a foundation class for a JEBuffer class.
 This class is stored the the string buffer and the information.
#include <Buffer.h>
Public Member Functions
Buffer (unsigned int sizeBuffer=DEFAULT_BUFFER_BUFFER_SIZE)
This function is a constructor of a Buffer object.
~Buffer (void)
This function is a destructor of a Buffer object.
const Buffer & operator= (const Buffer &eojul)
This function assigns a right-hand-side to a left-hand-side.
int appendBuffer (char *word, unsigned int length)
This function inserts the string of a word.
void initialize (bool willBeToTheDefaultState=false)
This function initializes a Buffer object.
void freeBuffer ()
This function frees the allocated memories for a Buffer object.
int doubleBuffer ()
This function enlarges twice the allocated memories for a Buffer object.
unsigned int getBufferPos () const
This function gets the current position of the buffer.
unsigned int getBufferSize () const
This function gets the size of the buffer.
char * getBufferPtr () const
This function gets the starting pointer of the buffer.
void setPosBuffer (int pos)
This function sets the current position of the buffer.
void setSizeBuffer (int size)
This function sets the size of the buffer.
void reserveBuffer (int size)
This function sets the size of the buffer.
Private Attributes
char * _buffer
the buffer of a word.
unsigned int _sizeBuffer
the size of the buffer.
unsigned int _posBuffer
the position of the buffer.
Detailed Description
This is a foundation class for a JEBuffer class.
 This class is stored the the string buffer and the information.
Date: 2008-11-17
Author: YoungMin Ahn
Definition at line 146 of file Buffer.h.
Constructor & Destructor Documentation
Buffer::Buffer (unsigned int sizeBuffer = DEFAULT_BUFFER_BUFFER_SIZE)
This function is a constructor of a Buffer object.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
sizeBuffer an unsigned integer - the size of a set string in a Buffer object.
Definition at line 118 of file Buffer.cpp.
References reserveBuffer().
Buffer::~Buffer (void)
This function is a destructor of a Buffer object.
Date: 2008-11-17
Author: YoungMin Ahn
Definition at line 123 of file Buffer.cpp.
References freeBuffer().
Member Function Documentation
int Buffer::appendBuffer (char * word, unsigned int length)
This function inserts the string of a word.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
word a pointer of a character - the string of a word.
length an unsigned integer - the size of the a word.
Returns: an integer.
Definition at line 167 of file Buffer.cpp.
References _buffer, _posBuffer, _sizeBuffer, and doubleBuffer().
Referenced by kmaOrange::Dictionary::makeMainTrieInfo(), kmaOrange::Dictionary::readJosaEomiDictionary(), and kmaOrange::Dictionary::setOnsetEomi().
int Buffer::doubleBuffer ()
This function enlarges twice the allocated memories for a Buffer object.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: an interger.
Definition at line 181 of file Buffer.cpp.
References _buffer, _sizeBuffer, and TWICE.
Referenced by appendBuffer().
void Buffer::freeBuffer ()
This function frees the allocated memories for a Buffer object.
Date: 2008-11-17
Author: YoungMin Ahn
Definition at line 162 of file Buffer.cpp.
References _buffer.
Referenced by initialize(), operator=(), and ~Buffer().
unsigned int kmaOrange::Buffer::getBufferPos () const [inline]
This function gets the current position of the buffer.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: an unsigned interger.
Definition at line 212 of file Buffer.h.
References _posBuffer.
Referenced by kmaOrange::Dictionary::makeMainTrieInfo(), operator=(), kmaOrange::Dictionary::readJosaEomiDictionary(), kmaOrange::Dictionary::setOnsetEomi(), kmaOrange::Dictionary::writeJosaEomiTrie(), and kmaOrange::Dictionary::writeMainTrie().
char* kmaOrange::Buffer::getBufferPtr () const [inline]
This function gets the starting pointer of the buffer.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: a pointer of a character.
Definition at line 228 of file Buffer.h.
References _buffer.
Referenced by kmaOrange::Dictionary::getBufferInfo(), kmaOrange::Dictionary::getJEInfo(), operator=(), kmaOrange::Dictionary::readJosaEomiTrie(), kmaOrange::Dictionary::readMainTrie(), kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Dictionary::writeJosaEomiTrie(), and kmaOrange::Dictionary::writeMainTrie().
unsigned int kmaOrange::Buffer::getBufferSize () const [inline]
This function gets the size of the buffer.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: an unsigned interger.
Definition at line 220 of file Buffer.h.
References _sizeBuffer.
Referenced by operator=().
void Buffer::initialize (bool willBeToTheDefaultState = false)
This function initializes a Buffer object.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
willBeToTheDefaultState a boolean.
 true - it entirely sets an InfoBuffer object to initial statement.
 false - it only sets values in an InfoBuffer object.
Definition at line 143 of file Buffer.cpp.
References _buffer, _posBuffer, _sizeBuffer, DEFAULT_BUFFER_BUFFER_SIZE, and freeBuffer().
const Buffer & Buffer::operator= (const Buffer & eojul)
This function assigns a right-hand-side to a left-hand-side.
Date: 2008-11-17
Author: YoungMin Ahn
Definition at line 199 of file Buffer.cpp.
References _buffer, _posBuffer, _sizeBuffer, freeBuffer(), getBufferPos(), getBufferPtr(), and getBufferSize().
void Buffer::reserveBuffer (int size)
This function sets the size of the buffer.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
size an integer - the size of the buffer.
Definition at line 128 of file Buffer.cpp.
References _buffer, _posBuffer, _sizeBuffer, DEFAULT_BUFFER_BUFFER_SIZE, and kmaOrange::Logger::SetMessage().
Referenced by Buffer(), kmaOrange::Dictionary::readJosaEomiTrie(), and kmaOrange::Dictionary::readMainTrie().
void kmaOrange::Buffer::setPosBuffer (int pos) [inline]
This function sets the current position of the buffer.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
pos an integer - the current position of the buffer.
Definition at line 236 of file Buffer.h.
References _posBuffer.
Referenced by kmaOrange::Dictionary::readJosaEomiTrie(), and kmaOrange::Dictionary::readMainTrie().
void kmaOrange::Buffer::setSizeBuffer (int size) [inline]
This function sets the size of the buffer.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
size an integer - the size of the buffer.
Definition at line 244 of file Buffer.h.
References _sizeBuffer.
Member Data Documentation
char* kmaOrange::Buffer::_buffer [private]
the buffer of a word.
Definition at line 255 of file Buffer.h.
Referenced by appendBuffer(), doubleBuffer(), freeBuffer(), getBufferPtr(), initialize(), operator=(), and reserveBuffer().
unsigned int kmaOrange::Buffer::_posBuffer [private]
the position of the buffer.
Definition at line 257 of file Buffer.h.
Referenced by appendBuffer(), getBufferPos(), initialize(), operator=(), reserveBuffer(), and setPosBuffer().
unsigned int kmaOrange::Buffer::_sizeBuffer [private]
the size of the buffer.
Definition at line 256 of file Buffer.h.
Referenced by appendBuffer(), doubleBuffer(), getBufferSize(), initialize(), operator=(), reserveBuffer(), and setSizeBuffer().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/kma/Buffer.h
/disk/workspace-cpp/la-manager/source/kma/Buffer.cpp