kmaOrange::StopWordContainer Class Reference
a class manages the stop-word dictionary.
#include <StopWord.h>
Public Member Functions
StopWordContainer ()
This function is a constructor of StopWordContainer object.
~StopWordContainer ()
This function is a destructor of StopWordContainer object.
int createTrie ()
This function creates and initializes a WK_DaTrie object.
int loadStopWord (StringEx pathDic=`./knowledge`, StringEx nameDic=`stopword.txt`, StringEx strID=`STW`)
This function loads contents of the stop-word dictionary file into a WK_DaTrie object.
int loadStopWord (const char *pathDic, const char *nameDic)
bool searchNgetInfoFromStopWordTrie (const char *str)
This function searches a WK_DaTrie object for input string.
Private Attributes
WK_DaTrie _stopWordTrie
a WK_DaTrie object of the stop-word dictionary.
Detailed Description
a class manages the stop-word dictionary.
Date: 2008-11-03
Author: YoungMin Ahn
Definition at line 24 of file StopWord.h.
Constructor & Destructor Documentation
StopWordContainer::StopWordContainer ()
This function is a constructor of StopWordContainer object.
Date: 2008-11-03
Author: YoungMin Ahn
Definition at line 14 of file StopWord.cpp.
StopWordContainer::~StopWordContainer ()
This function is a destructor of StopWordContainer object.
Date: 2008-11-03
Author: YoungMin Ahn
Definition at line 18 of file StopWord.cpp.
Member Function Documentation
int StopWordContainer::createTrie ()
This function creates and initializes a WK_DaTrie object.
Date: 2008-11-03
Author: YoungMin Ahn
Returns: an integer.
 0 - fail.
 1 - success.
Definition at line 22 of file StopWord.cpp.
References _stopWordTrie, kmaOrange::WK_DaTrie::create(), and TRIE_EXTEND_SIZE.
Referenced by loadStopWord().
int kmaOrange::StopWordContainer::loadStopWord (const char * pathDic, const char * nameDic) [inline, virtual]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Implements WK_StopWordContainer.
Definition at line 67 of file StopWord.h.
References loadStopWord().
Referenced by loadStopWord().
int StopWordContainer::loadStopWord (StringEx pathDic = `./knowledge`, StringEx nameDic = `stopword.txt`, StringEx strID = `STW`)
This function loads contents of the stop-word dictionary file into a WK_DaTrie object.
Date: 2008-11-03
Author: YoungMin Ahn
Parameters:
pathDic a pointer of a constant charater - the path of the directory, which the stop-word dictionary file is stored.
nameDic a pointer of a constant charater - the name of the stop-word dictionary file.
strID the ID of the stop-word dictionary.
Returns: an integer.
 0 - fail.
 1 - success.
Definition at line 34 of file StopWord.cpp.
References _stopWordTrie, StringEx::buffer(), createTrie(), StringEx::endWith(), kmaOrange::WK_DaTrie::insertKey(), StringEx::startWith(), and StringEx::trimRight().
bool StopWordContainer::searchNgetInfoFromStopWordTrie (const char * str) [virtual]
This function searches a WK_DaTrie object for input string.
Date: 2008-11-03
Author: YoungMin Ahn
Parameters:
str a pointer of a constant charater - input string.
Returns: a boolean.
 true - input string is a stop-word.
 false - input string is not a stop-word.
Implements WK_StopWordContainer.
Definition at line 92 of file StopWord.cpp.
References _stopWordTrie, kmaOrange::WK_DaTrie::findNode(), and kmaOrange::WK_DaTrie_Node::mpData.
Member Data Documentation
WK_DaTrie kmaOrange::StopWordContainer::_stopWordTrie [private]
a WK_DaTrie object of the stop-word dictionary.
Definition at line 81 of file StopWord.h.
Referenced by createTrie(), loadStopWord(), and searchNgetInfoFromStopWordTrie().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/kma/StopWord.h
/disk/workspace-cpp/la-manager/source/kma/StopWord.cpp