kmaOrange::MAnalyzer Class Reference
This class manages the Korean morphological analysis overall.
#include <MAnalyzer.h>
Public Member Functions
void setKnowledge (WK_Knowledge *pKnowledge)
This function sets a WK_Knowledge object.
void setEojul (WK_Eojul *pEojul)
This function sets a WK_Eojul object.
void setOption (int nOption, int nValue)
This function sets Korean morphological analyzing options.
void setExOption (int nOption=0)
This function sets execution options.
WK_Eojul * getEojulInSentence (int nPos)
This function gets a Eojul object for a word in a sentence.
int getEojulCountInSentence ()
This function gets the number of words in a sentence.
void composeAffixes (Eojul &pEojul)
This function composes a noun and an affix.
int getEojulOffsetInSentence (int nPos)
MAnalyzer (WK_Knowledge *pKnowledge, WK_Eojul *pEojul)
This function is a constructor of MAnalyzer object.
MAnalyzer (WK_Knowledge *pKnowledge)
MAnalyzer (const char *path)
MAnalyzer (void)
~MAnalyzer (void)
This function is a destructor of MAnalyzer object.
void makePreAnalysisDic ()
This function makes the system pre-analysis dictionary file.
ListEx< SearchInfo > * getMainList ()
This function gets the informaion list of all lexical morphemes.
ListEx< SearchJEInfo > * getJeList ()
This function gets the informaion list of all grammatical morphemes.
void setDefault ()
This function sets several options and global variables to default status.
StrStream * getStream ()
void tokenizeSentence (Sentence &sentence, const StringEx &strLine)
This function tokenizes a input string and sets a Sentence object.
int isDigit (StringEx &strex)
This function checks whether an input string is a digit or not.
int isDigit (const char ch)
int isAlphabet (StringEx &strex)
This function checks whether an input string is a alphabet or not.
int isAlphabet (const char ch)
char * convertJohabCodaToCP949Onset (unsigned char coda)
This function converts the KSSM code of onset endings('ï¿½ï¿½', 'ï¿½ï¿½', 'ï¿½ï¿½', 'ï¿½ï¿½') into the CP949 code.
int runWithEojul ()
This function executes Korean morphological analysis based on a word.
int commonRunWithStream ()
This is a common function of functions, which execute Korean morphological analysis based on a file.
int runWithStream (char *strNameInFile, char *strNameOutFile)
This function executes Korean morphological analysis based on a file.
int runWithStream (char *strNameInFile)
int runWithStream ()
int runWithString (StringEx &strLine, char *strNameOutFile)
This function executes Korean morphological analysis based on a sentence.
int runWithString (char *strLine, char *strNameOutFile)
int runWithString (StringEx &strLine)
int runWithString (char *strLine)
int preprocessBeforeAnalysis (Sentence &sentence)
This is a proprocessing function of functions, which execute Korean morphological analysis based on a file.
int analyzeEojul (Eojul &eojul)
This is a main function for morphological analysis.
int analyzeSimpleWord (Eojul &eojul)
This is a function for analyzing a word, which has only one lexical morpheme.
int analyzeHeadTail (Eojul &eojul, SearchJEInfo &sjei)
This is a function for analyzing a word, which has several lexical morphemes and grammatical morphemes.
int analyzeDeclinableWord (Eojul &eojul, SearchJEInfo &sjei)
This is a function for analyzing a declinable word.
int analyzeDigitAlphabetWord (Eojul &eojul)
This is a function for analyzing a word, which includes digit or alphabet.
int analyzeSubHangulWordforSN (Eojul &eojul, const StringEx &hangul)
This is a sub-function for analyzing a word, which includes digit or alphabet.
int analyzeSubHangulWordforFL (Eojul &eojul, const StringEx &hangul)
This is a sub-function for analyzing a word, which includes digit or alphabet.
int analyzeEojul_AuxVerb (Eojul &eojul)
This is a function for analyzing a auxiliary verb.
int analyzeEojul_Guess (Eojul &eojul)
This is a function for guessing a word, which is not analyzed.
int analyzeEojul_Guess_NJ (Eojul &eojul)
This function guesses that a word is analyzed into noun class and postposition.
int analyzeEojul_Guess_NVC (Eojul &eojul, int ret)
This function guesses that a word is analyzed into noun class and a copula.
int analyzeEojul_Guess_NXSD (Eojul &eojul)
This function guesses that a word is analyzed into noun class and a predicative suffix.
int analyzeEojul_NNR (Eojul &eojul, char mode=' ', int i=-1)
This function guesses that a word is a compound noun, so this function executes decomposing a compound noun.
int checkNanalyzeElision_UH (Eojul &eojul)
This is a detail analysis function for restoring the UH('ï¿½ï¿½') elision.
int checkNanalyzeElision_hlL (Eojul &eojul)
This is a detail analysis function for restoring the hlL('ï¿½ï¿½') elision.
int checkNanalyzeElision_OO (Eojul &eojul)
This is a detail analysis function for restoring the OO('ï¿½ï¿½') elision.
int checkNanalyzeElision_UR (Eojul &eojul, int tag=0)
This is a detail analysis function for restoring the UR('ï¿½ï¿½') elision.
int checkNanalyzeElision_HOMOPHONE (Eojul &eojul, int tag=0)
This is a detail analysis function for restoring the homophone elision.
int checkNanalyzeIrregularConjugation_SIOT (Eojul &eojul)
This is a detail analysis function for restoring the SIOT('ï¿½ï¿½') irregular conjugation.
int checkNanalyzeIrregularConjugation_DIGT (Eojul &eojul)
This is a detail analysis function for restoring the DIGT('ï¿½ï¿½') irregular conjugation.
int checkNanalyzeIrregularConjugation_BIUP (Eojul &eojul)
This is a detail analysis function for restoring the BIUP('ï¿½ï¿½') irregular conjugation.
int checkNanalyzeIrregularConjugation_RUH (Eojul &eojul)
This is a detail analysis function for restoring the RUH('ï¿½ï¿½') irregular conjugation.
int checkNanalyzeIrregularConjugation_YUR (Eojul &eojul)
This is a detail analysis function for restoring the YUR('ï¿½ï¿½') irregular conjugation.
int checkNanalyzeIrregularConjugation_RUR (Eojul &eojul)
This is a detail analysis function for restoring the RUR('ï¿½ï¿½') irregular conjugation.
int checkNanalyzeIrregularConjugation_GURRA (Eojul &eojul)
This is a detail analysis function for restoring the GURRA('ï¿½Å¶ï¿½') irregular conjugation.
int checkNanalyzeIrregularConjugation_HIUNG (Eojul &eojul)
This is a detail analysis function for restoring the HIUNG('ï¿½ï¿½') irregular conjugation.
int checkNanalyzeIrregularConjugation_UR (Eojul &eojul)
This is a detail analysis function for restoring the UR('ï¿½ï¿½') irregular conjugation.
int checkNanalyzeContraction_WAHWOH (Eojul &eojul)
This is a detail analysis function for restoring the WAHWOH('ï¿½ï¿½/ï¿½ï¿½') contraction.
int checkNanalyzeContraction_WAE (Eojul &eojul)
This is a detail analysis function for restoring the WAE('ï¿½ï¿½') contraction.
int checkNanalyzeContraction_YUR (Eojul &eojul)
This is a detail analysis function for restoring the YUR('ï¿½ï¿½') contraction.
int checkNanalyzeContraction_WEH (Eojul &eojul)
This is a detail analysis function for restoring the WEH('ï¿½ï¿½') contraction.
int checkNanalyzeContraction_UI (Eojul &eojul)
This is a detail analysis function for restoring the UI('ï¿½ï¿½') contraction.
int checkNanalyzeContraction_AE (Eojul &eojul)
This is a detail analysis function for restoring the AE('ï¿½ï¿½') contraction.
int checkNanalyzeContraction_CHEE (Eojul &eojul)
This is a detail analysis function for restoring the CHEE('Ä¡') contraction.
int checkNanalyzeContraction_KEH (Eojul &eojul)
This is a detail analysis function for restoring the KEH('ï¿½ï¿½') contraction.
int checkNanalyzeContraction_KEE (Eojul &eojul)
This is a detail analysis function for restoring the KEE('Å°') contraction.
int checkNanalyzeN_ (Eojul &eojul, unsigned int tagAllowed)
This is a function for analyzing the noun class.
int checkNanalyzeV_ (Eojul &eojul, unsigned int tagAllowed)
This is a function for analyzing the verb class.
int checkNanalyzePreEomi (Eojul &eojul, unsigned int tagAllowed)
This is a function for analyzing the prefianl ending.
int checkNanalyzeCopular (Eojul &eojul, unsigned int tagAllowed)
This is a function for analyzing the copular.
int checkNanalyzeXSDecliable (Eojul &eojul, unsigned int tagAllowed)
This is a function for analyzing the copular.
int canBeNJ (const char *front, const char *back)
This function checks whether it is possible to analyze into the noun class and postposition or not.
int canBeNJ (const StringEx &front, const StringEx &back)
int canBeNJ (SyllableInfo *psi, JEInfo &jei)
int canBeNE (const char *front, const char *back)
This function checks whether it is possible to analyze into the noun class and ending or not.
int canBeNE (const StringEx &front, const StringEx &back)
int canBeNE (SyllableInfo *psi, JEInfo &jei)
int canBeVE (const char *front, const char *back)
This function checks whether it is possible to analyze into the verb class and ending or not.
int canBeVE (const StringEx &front, const StringEx &back)
int warmUpAnalysis (Eojul &eojul, bool isVXMode)
This function sets the dictionary information for morphological analysis.
void tagging ()
Public Attributes
int isC
Private Member Functions
int makeRanking (Eojul &eojul)
This function calulates the score of each candidate in a Eojul object.
double makeSubRanking (int i, Eojul &eojul)
This function calulates the score of a candidate in a Eojul object.
Private Attributes
InfoBuffer _avIB
InfoBuffer _psIB
InfoBuffer _pfeIB
Dictionary * _dic
Eojul * _pCommonEojul
Eojul _eojul
StrStream _stream
DecomposeNNP _decomposeNNP
Tagger _tagger
Eojul _avEojul
Sentence _sentence
StringEx _strLineBuffer
HeadTailInfo _infoHT [MAX_DEPTH]
int _depthHT
StringEx _strTemp
StringEx _strTemp2
GuessCandidate _gcList
int _isAnalyzed
unsigned int _historyAnalysis
int _nnrMode
int _nnrJ
int _isSJ
unsigned char _option
int _flagV_
int _flagECN
int _flagJECN
bool _isPreAnalysisOut
int _posTail
ListEx< SearchInfo > _mainList
ListEx< SearchJEInfo > _jeList
JEInfo _jeInfo
JEInfo _jecInfo
JEInfo _emptyJEInfo
ListEx< SearchInfo > _allN_List
ListEx< vector< int > > _nnpList
bool isPerformedNNR
char mOptionNBest
char mOptionExtractAlpha
char mOptionExtractNum
char mOptionExtractVerbStems
char mOptionExtractAdnominal
char mOptionExtractAdverb
char mOptionExtractInterjection
char mOptionExtractUnknown
char mOptionExtractBoundNoun
Static Private Attributes
static char * _eomiPossibleCoda = `¤¤\0¤©\0¤±\0¤²\0`
static StringEx _charDelimiter = `?!.-,\`'()[]<>~\\:;`_/|+=*&^%$#@{}`
static StringEx _wcharDelimiter = `¤ý:£¡:£§:£¬:£®:£¯:£º:£»:£¿:£Þ:£ß:£à:£ü:£þ:¡¢:¡£:¡¤:¡¥:¡¦:¡§:¡¨:¡©:¡ª:¡«:¡¬:¡­:¢¥:¢¦:¢§:¢¨:¢©:¢ª:¢«:¢¬:¢­:¢®:¢¯:¢°:£¢:£¨:£©:£Û:£Ý:£û:£ý:¡®:¡¯:¡°:¡±:¡²:¡³:¡´:¡µ:¡¶:¡·:¡¸:¡¹:¡º:¡»:¡¼:¡½:£«:£­:£¼:£½:£¾:¡¾:¡¿:¡À:¡Á:¡Â:¡Ã:¡Ä:¡Å:¡Î:¡Ï:¡Ð:¡Ñ:¡Ò:¡Ó:¡Ô:¡Õ:¡Ö:¡ì:¡í:¡î:¡ï:¡ð:¡ñ:¡ò:¡ó:¡ô:¡õ:¡ö:¡÷:¡ø:¡ù:¡ú:¡û:¡ü:¡ý:¡þ:¢¡:¢¢:¢£:¢¤:¢±:¢²:¢³:£¤:£¥:£Ü:£Æ:¡Ç:¡È:¡É:¡Ê:¡Ë:¡Ì:¡Í:¢´:¢µ:¢¶:?:§¡:§¢:§£:§¥:§¦:§§:§¨:§©:§ª:§«:§¬:§­:§®:§¯:§°:§±:§²:§³:§´:§µ:§¶:§·:§¸:§¹:§º:§»:§¼:§½:§¾:§¿:§À:§Á:§Â:§Ã:§Ä:§Å:§Æ:§Ç:§È:§É:§Ê:§Ë:§Ì:§Í:§Î:§Ï:§Ð:§Ñ:§Ò:§Ó:§Ô:§Õ:§Ö:§×:§Ø:§Ù:§Ú:§Û:§Ü:§Ý:§Þ:§ß:§à:§á:§â:§ã:§ä:§å:§æ:§ç:§è:§é:§ê:§ë:§ì:§í:§î:§ï:££:£¦:£ª:£À:¡×:¡Ø:¡Ù:¡Ú:¡Û:¡Ü:¡Ý:¡Þ:¡ß:¡à:¡á:¡â:¡ã:¡ä:¡å:¡æ:¡ç:¡è:¡é:¡ê:¡ë:¢¹:¢¸:¢¹:¢º:¢»:¢¼:¢½:¢¾:¢¿:¢Á:¢Â:¢Ã:¢Ä:¢Å:¢Æ:¢Ç:¢È:¢É:¢Ê:¢Ë:¢Ì:¢Í:¢Î:¢Ï:¢Ð:¢Ñ:¢Ò:¢Ó:¢Ô:¢Õ:¢Ö:¢×:¢Ø:¢Ù:¢Ú:¢Û:¢Ü:¢Ý:¢Þ:¢ß:¢à:¢á:¢â:¢ã:¢ä:¢å:?:¨£:¨¬:¦¡:¦¢:¦£:¦¤:¦¥:¦¦:¦§:¦¨:¦©:¦ª:¦«:¦¬:¦­:¦®:¦¯:¦°:¦±:¦²:¦³:¦´:¦µ:¦¶:¦·:¦¸:¦¹:¦º:¦»:¦¼:¦½:¦¾:¦¿:¦À:¦Á:¦Â:¦Ã:¦Ä:¦Å:¦Æ:¦Ç:¦È:¦É:¦Ê:¦Ë:¦Ì:¦Í:¦Î:¦Ï:¦Ð:¦Ñ:¦Ò:¦Ô:¦Õ:¦Ö:¦×:¦Ø:¦Ù:¦Ú:¦Û:¦Ü:¦Ý:¦Þ:¦ß:¦à:¦á:¦â:¦ã:¦ä:¨±:¨²:¨³:¨´:¨µ:¨¶:¨·:¨¸:¨¹:¨º:¨»:¨¼:¨½:¨¾:¨¿:¨À:¨Á:¨Â:¨Ã:¨Ä:¨Å:¨Æ:¨Ç:¨È:¨É:¨Ê:¨Ë:¨Ì:©±:©²:©³:©´:©µ:©¶:©·:©¸:©¹:©º:©»:©¼:©½:©¾:©¿:©À:©Á:©Â:©Ã:©Ä:©Å:©Æ:©Ç:©È:©É:©Ê:©Ë:©Ì:¨Í:¨Î:¨Ï:¨Ð:¨Ñ:¨Ò:¨Ó:¨Ô:¨Õ:¨Ö:¨×:¨Ø:¨Ù:¨Ú:¨Û:¨Ü:¨Ý:¨Þ:¨ß:¨à:¨á:¨â:¨ã:¨ä:¨å:¨æ:¨ç:¨è:¨é:¨ê:¨ë:¨ì:¨í:¨î:¨ï:¨ð:¨ñ:¨ò:¨ó:¨ô:¨õ:©Í:©Î:©Ï:©Ð:©Ñ:©Ò:©Ó:©Ô:©Õ:©Ö:©×:©Ø:©Ù:©Ú:©Û:©Ü:©Ý:©Þ:©ß:©à:©á:©â:©ã:©ä:©å:©æ:©ç:©è:©é:©ê:©ë:©ì:©í:©î:©ï:©ð:©ñ:©ò:©ó:©ô:©õ:£°:£±:£²:£³:£´:£µ:£¶:£·:£¸:£¹:¥¡:¥¢:¥£:¥¤:¥¥:¥¦:¥§:¥¨:¥©:¥ª:¥°:¥±:¥²:¥³:¥´:¥µ:¥¶:¥·:¥¸:¥¹:¨ö:¨÷:¨ø:¨ù:¨ú:¨û:¨ü:¨ý:¨þ:©ö:©÷:©ø:©ù:©ú:©û:©ü:©ý:©þ`
static StringEx _charSpecialJosa = `´Â:¸¦:²²:À»:Àº`
static StringEx _nnrJosa = `ÀÇ`
Detailed Description
This class manages the Korean morphological analysis overall.
Date: 2008-11-12
Author: YoungMin Ahn & HeeGeun Park
See also: WK_Analyzer
Definition at line 34 of file MAnalyzer.h.
Constructor & Destructor Documentation
MAnalyzer::MAnalyzer (WK_Knowledge * pKnowledge, WK_Eojul * pEojul)
This function is a constructor of MAnalyzer object.
Date: 2008-11-12
Author: YoungMin Ahn
Parameters:
pKnowledge a pointer of a WK_Knowledge object.
pEojul a pointer of a WK_Eojul object.
Definition at line 50 of file MAnalyzer.cpp.
References _dic, _pCommonEojul, isC, and setDefault().
MAnalyzer::MAnalyzer (WK_Knowledge * pKnowledge)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 39 of file MAnalyzer.cpp.
References _dic, _pCommonEojul, isC, and setDefault().
MAnalyzer::MAnalyzer (const char * path)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 27 of file MAnalyzer.cpp.
References _dic, _pCommonEojul, isC, kmaOrange::Dictionary::loadKnowledge(), and setDefault().
MAnalyzer::MAnalyzer (void)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 21 of file MAnalyzer.cpp.
References isC, and setDefault().
MAnalyzer::~MAnalyzer (void)
This function is a destructor of MAnalyzer object.
Date: 2008-11-12
Author: YoungMin Ahn
Definition at line 60 of file MAnalyzer.cpp.
References _dic, _pCommonEojul, and isC.
Member Function Documentation
int MAnalyzer::analyzeDeclinableWord (Eojul & eojul, SearchJEInfo & sjei)
This is a function for analyzing a declinable word.
Date: 2008-11-12
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
sjei an indirect referncing pointer of a SearchJEInfo object.
Returns: an integer.
Definition at line 5752 of file MAnalyzer.cpp.
References _depthHT, _dic, _flagECN, _historyAnalysis, _infoHT, _jecInfo, _jeInfo, _posTail, canBeVE(), checkNanalyzeContraction_WAE(), checkNanalyzeContraction_WAHWOH(), checkNanalyzeContraction_YUR(), checkNanalyzeCopular(), checkNanalyzeElision_hlL(), checkNanalyzeElision_OO(), checkNanalyzeElision_UH(), checkNanalyzeIrregularConjugation_BIUP(), checkNanalyzeIrregularConjugation_DIGT(), checkNanalyzeIrregularConjugation_HIUNG(), checkNanalyzeIrregularConjugation_RUH(), checkNanalyzeIrregularConjugation_RUR(), checkNanalyzeIrregularConjugation_SIOT(), checkNanalyzeIrregularConjugation_UR(), checkNanalyzePreEomi(), checkNanalyzeV_(), checkNanalyzeXSDecliable(), JEInfo::coda, CODA, kmaOrange::SyllableInfo::coda, CODE_ERROR, CODE_FAIL, CODE_SUCCESS, CT_AE, CT_WAE, CT_WAHWOH, CT_YUR, EDI_COPULA, EDI_FLAG_ECN, EDI_RA, EDI_SEO_YA, EDI_YUR, EL_hlL, EL_OO, EL_UH, kmaOrange::Eojul::getBufferPtr(), kmaOrange::ExCP949::getInfoEnd(), kmaOrange::Dictionary::getJEInfo(), hfO, hfS, hlB, hlFILL, hlL, hlM, hlN, hmAH, hmOO, IC, kmaOrange::SyllableInfo::info, JEInfo::info, IR_DIGT, IR_HIUNG1, IR_HIUNG2, IR_RUH, IR_RUR, IR_SIOT, IR_UR, J_, MA, MM, NNP, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::onset, JEInfo::pstr, HeadTailInfo::strTail, JEInfo::tag, HeadTailInfo::tagTail, VA, VV, and VX.
Referenced by analyzeHeadTail().
int MAnalyzer::analyzeDigitAlphabetWord (Eojul & eojul)
This is a function for analyzing a word, which includes digit or alphabet.
Date: 2008-11-12
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 1369 of file MAnalyzer.cpp.
References _charDelimiter, _nnrJ, analyzeSubHangulWordforFL(), analyzeSubHangulWordforSN(), StringEx::buffer(), kmaOrange::Eojul::close(), EI_ALPHABET, EI_DIGIT, EI_HANGUL, EI_NODIVIDE, EI_OTHER, FL, kmaOrange::Eojul::getBufferPtr(), kmaOrange::Eojul::getCountsPtr(), kmaOrange::Eojul::getEojulInfo(), StringEx::getIndex(), StringEx::getSubString(), kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::Eojul::initialize(), isAlphabet(), isDigit(), StringEx::length(), kmaOrange::Eojul::merge(), NNR, SC, kmaOrange::Eojul::setEojulAndInfo(), kmaOrange::Eojul::setMorphAndTag(), SN, TEI_INCLUDESC, and UW.
Referenced by analyzeEojul().
int MAnalyzer::analyzeEojul (Eojul & eojul)
This is a main function for morphological analysis.
Date: 2008-11-12
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 1687 of file MAnalyzer.cpp.
References kmaOrange::Dictionary::_auxVerb, GuessCandidate::_avCount, _avIB, _depthHT, _dic, _eojul, _flagECN, _flagJECN, _gcList, _historyAnalysis, _infoHT, _isAnalyzed, _isPreAnalysisOut, _isSJ, _jeList, _mainList, GuessCandidate::_njCount, GuessCandidate::_njList, _nnrJ, _nnrMode, GuessCandidate::_nvcCount, GuessCandidate::_nxsdCount, _posTail, kmaOrange::Dictionary::_preanalBuffer, _strTemp, analyzeDigitAlphabetWord(), analyzeEojul_AuxVerb(), analyzeEojul_Guess(), analyzeEojul_NNR(), analyzeHeadTail(), analyzeSimpleWord(), StringEx::buffer(), kmaOrange::Eojul::close(), GuessCandidate::closeAV(), CODA, kmaOrange::tagcode::code, CODE_SUCCESS, EI_ALPHABET, EI_AUXVERB, EI_DIGIT, EI_HANGUL, EI_ILLEGAL, EI_PUNCT, EI_TOOLONG, EM, StringEx::empty(), Ep, EP_SS, StringEx::getBuffer(), kmaOrange::Eojul::getBufferPtr(), kmaOrange::Eojul::getCountsPtr(), GuessCandidate::getCurrentAV(), kmaOrange::Eojul::getEojulInfo(), kmaOrange::ExCP949::getInfoEnd(), kmaOrange::Dictionary::getJEInfo(), kmaOrange::Eojul::getListSize(), kmaOrange::InfoBuffer::getPositionByIndex(), kmaOrange::InfoBuffer::getSize(), hfN, hmAE, hmAH, kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::SyllableInfo::info, JEInfo::info, kmaOrange::Eojul::initialize(), GuessCandidate::initialize(), isPerformedNNR, J_, JDI_NOT_JX, TailInfo::jeInfo, MA, NNp, NNr, NNR, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::onset, JEInfo::pstr, SC, kmaOrange::AuxVerb::searchNgetInfoFromAvTrie(), kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Dictionary::searchNgetInfoFromPreAnalTrie(), kmaOrange::Eojul::setEojulAndInfo(), kmaOrange::Eojul::setMorphAndTag(), HeadTailInfo::strHead, kmaOrange::TagSet::stringOrderTags, HeadTailInfo::strTail, TEI_INCLUDESC, V_, VC, VX, warmUpAnalysis(), XP, XSD, and XSN.
Referenced by analyzeEojul_AuxVerb(), analyzeSubHangulWordforFL(), analyzeSubHangulWordforSN(), preprocessBeforeAnalysis(), runWithEojul(), and tokenizeSentence().
int MAnalyzer::analyzeEojul_AuxVerb (Eojul & eojul)
This is a function for analyzing a auxiliary verb.
Date: 2008-11-12
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 5937 of file MAnalyzer.cpp.
References GuessCandidate::_avCount, _avEojul, GuessCandidate::_avList, _gcList, _isAnalyzed, analyzeEojul(), E_, EI_AUXVERB, EI_AUXVERB_2LEN, EI_HANGUL, kmaOrange::Eojul::getBufferByIndex(), kmaOrange::Eojul::getBufferPtr(), kmaOrange::Eojul::getCount(), kmaOrange::Eojul::getCountsPtr(), kmaOrange::Eojul::getEojulInfo(), kmaOrange::Eojul::getListSize(), kmaOrange::Eojul::getPOS(), kmaOrange::Eojul::getTagsPtr(), kmaOrange::Eojul::initialize(), J_, kmaOrange::Eojul::merge(), kmaOrange::Eojul::setEojulAndInfo(), and V_.
Referenced by analyzeEojul().
int MAnalyzer::analyzeEojul_Guess (Eojul & eojul)
This is a function for guessing a word, which is not analyzed.
Date: 2008-11-12
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 5994 of file MAnalyzer.cpp.
References _gcList, _historyAnalysis, _isSJ, GuessCandidate::_njCount, GuessCandidate::_njList, GuessCandidate::_nvcCount, GuessCandidate::_nxsdCount, analyzeEojul_Guess_NJ(), analyzeEojul_Guess_NVC(), analyzeEojul_Guess_NXSD(), kmaOrange::Eojul::getBufferPtr(), kmaOrange::Eojul::getCountsPtr(), NNG, NNR, and TailInfo::nPos.
Referenced by analyzeEojul().
int MAnalyzer::analyzeEojul_Guess_NJ (Eojul & eojul)
This function guesses that a word is analyzed into noun class and postposition.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 6230 of file MAnalyzer.cpp.
References _charSpecialJosa, _gcList, _isSJ, GuessCandidate::_njCount, GuessCandidate::_njList, _nnrJ, GuessCandidate::_nvcCount, _strTemp, analyzeEojul_NNR(), kmaOrange::Eojul::close(), StringEx::getBuffer(), kmaOrange::Eojul::getBufferPtr(), StringEx::getIndex(), kmaOrange::Eojul::increaseAnalysisResults(), TailInfo::jeInfo, NNR, TailInfo::nPos, JEInfo::pstr, kmaOrange::Eojul::setMorphAndTag(), and JEInfo::tag.
Referenced by analyzeEojul_Guess().
int MAnalyzer::analyzeEojul_Guess_NVC (Eojul & eojul, int ret)
This function guesses that a word is analyzed into noun class and a copula.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
ret an integer - the return value.
Returns: an integer.
Definition at line 6311 of file MAnalyzer.cpp.
References _gcList, _nnrJ, GuessCandidate::_nvcCount, GuessCandidate::_nvcList, analyzeEojul_NNR(), kmaOrange::Eojul::append(), kmaOrange::Eojul::close(), kmaOrange::Eojul::getBufferPtr(), kmaOrange::Eojul::increaseAnalysisResults(), NNR, and kmaOrange::Eojul::setMorphAndTag().
Referenced by analyzeEojul_Guess().
int MAnalyzer::analyzeEojul_Guess_NXSD (Eojul & eojul)
This function guesses that a word is analyzed into noun class and a predicative suffix.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 6352 of file MAnalyzer.cpp.
References _gcList, _nnrJ, GuessCandidate::_nxsdCount, GuessCandidate::_nxsdList, analyzeEojul_NNR(), kmaOrange::Eojul::append(), kmaOrange::Eojul::close(), kmaOrange::Eojul::getBufferPtr(), kmaOrange::Eojul::increaseAnalysisResults(), NNR, and kmaOrange::Eojul::setMorphAndTag().
Referenced by analyzeEojul_Guess().
int MAnalyzer::analyzeEojul_NNR (Eojul & eojul, char mode = ' ', int i = -1)
This function guesses that a word is a compound noun, so this function executes decomposing a compound noun.
Date: 2008-11-13
Author: HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
mode a character.
i an integer.
Returns: an integer.
Definition at line 6030 of file MAnalyzer.cpp.
References _decomposeNNP, _depthHT, _dic, _gcList, _historyAnalysis, _infoHT, _isSJ, GuessCandidate::_njList, _nnrJ, _nnrMode, GuessCandidate::_nvcList, GuessCandidate::_nxsdList, _strTemp, _strTemp2, kmaOrange::Eojul::append(), StringEx::buffer(), kmaOrange::Eojul::close(), kmaOrange::Eojul::getBufferPtr(), kmaOrange::Eojul::getCountsPtr(), kmaOrange::DecomposeNNP::getDecomposedInformation(), StringEx::getIndex(), kmaOrange::Eojul::getListSize(), StringEx::getNumberOfChar(), StringEx::getSubString(), kmaOrange::DecomposeNNP::getWeight(), kmaOrange::Eojul::increaseAnalysisResults(), MainTrieInfo::isNNF, isPerformedNNR, J_, JC, TailInfo::jeInfo, StringEx::length(), makeSubRanking(), SearchInfo::mti, NNB, NNF, NNG, NNI, NNR, NNU, NP, JEInfo::pstr, kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Eojul::setMorphAndTag(), kmaOrange::Eojul::setScore(), HeadTailInfo::strHead, HeadTailInfo::strTail, JEInfo::tag, HeadTailInfo::tagTail, XP, and XSN.
Referenced by analyzeEojul(), analyzeEojul_Guess_NJ(), analyzeEojul_Guess_NVC(), analyzeEojul_Guess_NXSD(), analyzeSimpleWord(), and checkNanalyzeN_().
int MAnalyzer::analyzeHeadTail (Eojul & eojul, SearchJEInfo & sjei)
This is a function for analyzing a word, which has several lexical morphemes and grammatical morphemes.
Date: 2008-11-12
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
sjei an indirect referncing pointer of a SearchJEInfo object.
Returns: an integer.
Definition at line 4269 of file MAnalyzer.cpp.
References _depthHT, _dic, _gcList, _historyAnalysis, _infoHT, _isAnalyzed, _jecInfo, _jeInfo, _nnrJ, _posTail, GuessCandidate::addNJ(), analyzeDeclinableWord(), analyzeSimpleWord(), StringEx::buffer(), canBeNJ(), checkNanalyzeContraction_CHEE(), checkNanalyzeContraction_KEE(), checkNanalyzeContraction_KEH(), checkNanalyzeN_(), CODA, kmaOrange::SyllableInfo::coda, CODE_ERROR, CODE_FAIL, CODE_SUCCESS, CT_CHEE, CT_KEH, E_, EI_AUXVERB, EP_SS, ETN, kmaOrange::Eojul::getBufferPtr(), kmaOrange::Eojul::getEojulInfo(), kmaOrange::ExCP949::getInfoEnd(), kmaOrange::Dictionary::getJEInfo(), hfG, hfK, hfO, hlFILL, hlM, hmEE, hmUH, kmaOrange::SyllableInfo::info, JEInfo::info, J_, JDI_ONLY_N_, JDI_ONLY_NP, SearchJEInfo::jeti, MA, N_, NNB, NNG, NNI, NNP, NNU, NP, NU, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::onset, SearchJEInfo::pos, JEInfo::pstr, kmaOrange::Dictionary::searchNgetInfoFromJosaEomiTrie(), StringEx::setSubString(), HeadTailInfo::strHead, HeadTailInfo::strTail, JEInfo::tag, JosaEomiTrieInfo::tag, and HeadTailInfo::tagTail.
Referenced by analyzeEojul().
int MAnalyzer::analyzeSimpleWord (Eojul & eojul)
This is a function for analyzing a word, which has only one lexical morpheme.
Date: 2008-11-12
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 1924 of file MAnalyzer.cpp.
References _depthHT, _dic, _flagECN, _historyAnalysis, _infoHT, _jecInfo, _jeInfo, _mainList, _nnrJ, _strTemp, analyzeEojul_NNR(), checkNanalyzeContraction_CHEE(), checkNanalyzeContraction_KEE(), checkNanalyzeContraction_KEH(), checkNanalyzeContraction_WAE(), checkNanalyzeContraction_WAHWOH(), checkNanalyzeContraction_YUR(), checkNanalyzeCopular(), checkNanalyzeElision_hlL(), checkNanalyzeElision_HOMOPHONE(), checkNanalyzeElision_OO(), checkNanalyzeElision_UH(), checkNanalyzeElision_UR(), checkNanalyzeIrregularConjugation_BIUP(), checkNanalyzeIrregularConjugation_HIUNG(), checkNanalyzeIrregularConjugation_RUH(), checkNanalyzeIrregularConjugation_UR(), checkNanalyzePreEomi(), checkNanalyzeV_(), checkNanalyzeXSDecliable(), kmaOrange::Eojul::close(), kmaOrange::SyllableInfo::coda, CODA, CODE_ERROR, CODE_FAIL, CODE_GUESS, CODE_SUCCESS, CT_AE, CT_CHEE, CT_KEH, CT_WAE, CT_WAHWOH, CT_YUR, EI_2LEN, EI_AUXVERB, EL_hlL, EL_HOMOPHONE, EL_OO, EL_UH, EL_UR, StringEx::getBuffer(), kmaOrange::Eojul::getEojulInfo(), kmaOrange::ExCP949::getInfoEnd(), kmaOrange::Dictionary::getJEInfo(), hfK, hfO, hfR, hfS, hlL, hlN, hmEE, hmOO, hmUR, hmYUR, IC, kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::SyllableInfo::info, IR_HIUNG1, IR_HIUNG2, IR_RUH, IR_UR, StringEx::length(), MA, MM, N_, NNB, NNb, NNF, NNG, NNg, NNI, NNi, NNP, NNp, NNR, NNU, NNu, NP, Np, NU, Nu, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::onset, JEInfo::pstr, kmaOrange::Eojul::setMorphAndTag(), HeadTailInfo::strHead, VA, VC, VV, and VX.
Referenced by analyzeEojul(), and analyzeHeadTail().
int MAnalyzer::analyzeSubHangulWordforFL (Eojul & eojul, const StringEx & hangul)
This is a sub-function for analyzing a word, which includes digit or alphabet.
Date: 2008-11-12
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
hangul an indirect referncing pointer of a StringEx object.
Returns: an integer.
Definition at line 1304 of file MAnalyzer.cpp.
References _dic, _nnrMode, analyzeEojul(), kmaOrange::Eojul::append(), kmaOrange::Eojul::backmerge(), StringEx::buffer(), kmaOrange::Eojul::close(), EI_HANGUL, kmaOrange::Eojul::getBufferPtr(), kmaOrange::Eojul::getCountsPtr(), kmaOrange::Eojul::getEojulInfo(), kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::Eojul::initialize(), J_, SearchJEInfo::jeti, StringEx::length(), kmaOrange::Eojul::merge(), SearchInfo::mti, N_, SearchJEInfo::pos, SearchJEInfo::posEnd, kmaOrange::Dictionary::searchNgetInfoFromJosaEomiTrie(), kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Eojul::setEojulAndInfo(), kmaOrange::Eojul::setMorphAndTag(), MainTrieInfo::tag, and JosaEomiTrieInfo::tag.
Referenced by analyzeDigitAlphabetWord().
int MAnalyzer::analyzeSubHangulWordforSN (Eojul & eojul, const StringEx & hangul)
This is a sub-function for analyzing a word, which includes digit or alphabet.
Date: 2008-11-12
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
hangul an indirect referncing pointer of a StringEx object.
Returns: an integer.
Definition at line 1021 of file MAnalyzer.cpp.
References _dic, _nnrMode, analyzeEojul(), kmaOrange::Eojul::append(), kmaOrange::Eojul::backmerge(), StringEx::buffer(), kmaOrange::Eojul::close(), kmaOrange::SyllableInfo::coda, EI_HANGUL, StringEx::getBuffer(), kmaOrange::Eojul::getBufferPtr(), kmaOrange::Eojul::getCount(), kmaOrange::Eojul::getCountsPtr(), kmaOrange::Eojul::getEojulInfo(), kmaOrange::ExCP949::getInfo(), kmaOrange::Eojul::getListSize(), hfO, hlSS, hmEE, kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::Eojul::initialize(), MainTrieInfo::isNNF, J_, SearchJEInfo::jeti, StringEx::length(), MA, kmaOrange::Eojul::merge(), MM, SearchInfo::mti, N_, NNB, NNb, NNF, NNG, NNg, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::onset, SearchJEInfo::pos, SearchJEInfo::posEnd, kmaOrange::Dictionary::searchNgetInfoFromJosaEomiTrie(), kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Eojul::setEojulAndInfo(), kmaOrange::Eojul::setMorphAndTag(), JosaEomiTrieInfo::tag, MainTrieInfo::tag, and XSN.
Referenced by analyzeDigitAlphabetWord().
int MAnalyzer::canBeNE (SyllableInfo * psi, JEInfo & jei) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 4231 of file MAnalyzer.cpp.
References CODA, kmaOrange::SyllableInfo::coda, hlL, kmaOrange::SyllableInfo::info, JEInfo::info, JDI_CODA, JDI_CODA_L, and JDI_NOT_CODA.
int MAnalyzer::canBeNE (const StringEx & front, const StringEx & back) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 4226 of file MAnalyzer.cpp.
int MAnalyzer::canBeNE (const char * front, const char * back) [inline]
This function checks whether it is possible to analyze into the noun class and ending or not.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
front a pointer of constant character.
back a pointer of constant character.
Returns: an integer.
 0 - impossible.
 1 - possible.
Definition at line 4221 of file MAnalyzer.cpp.
int MAnalyzer::canBeNJ (SyllableInfo * psi, JEInfo & jei) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 4203 of file MAnalyzer.cpp.
References CODA, kmaOrange::SyllableInfo::coda, hlL, kmaOrange::SyllableInfo::info, JEInfo::info, JDI_CODA, JDI_CODA_L, and JDI_NOT_CODA.
int MAnalyzer::canBeNJ (const StringEx & front, const StringEx & back) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 4198 of file MAnalyzer.cpp.
int MAnalyzer::canBeNJ (const char * front, const char * back) [inline]
This function checks whether it is possible to analyze into the noun class and postposition or not.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
front a pointer of constant character.
back a pointer of constant character.
Returns: an integer.
 0 - impossible.
 1 - possible.
Definition at line 4193 of file MAnalyzer.cpp.
Referenced by analyzeHeadTail().
int MAnalyzer::canBeVE (const StringEx & front, const StringEx & back) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 4255 of file MAnalyzer.cpp.
References StringEx::buffer(), CODA, kmaOrange::ExCP949::getInfo(), kmaOrange::ExCP949::getInfoEnd(), hfO, hmUH, kmaOrange::SyllableInfo::info, kmaOrange::SyllableInfo::nucleus, and kmaOrange::SyllableInfo::onset.
int MAnalyzer::canBeVE (const char * front, const char * back) [inline]
This function checks whether it is possible to analyze into the verb class and ending or not.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
front a pointer of constant character.
back a pointer of constant character.
Returns: an integer.
 0 - impossible.
 1 - possible.
Definition at line 4250 of file MAnalyzer.cpp.
Referenced by analyzeDeclinableWord(), and checkNanalyzePreEomi().
int kmaOrange::MAnalyzer::checkNanalyzeContraction_AE (Eojul & eojul)
This is a detail analysis function for restoring the AE('ï¿½ï¿½') contraction.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
int MAnalyzer::checkNanalyzeContraction_CHEE (Eojul & eojul)
This is a detail analysis function for restoring the CHEE('Ä¡') contraction.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 3991 of file MAnalyzer.cpp.
References _depthHT, _dic, _historyAnalysis, _infoHT, StringEx::buffer(), kmaOrange::Eojul::close(), CODA, CODE_ERROR, CODE_FAIL, CODE_SUCCESS, E_, kmaOrange::ExCP949::getInfoEnd(), hfCH, hmEE, kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::SyllableInfo::info, MA, SearchInfo::mti, N_, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::onset, kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Eojul::setMorphAndTag(), HeadTailInfo::strHead, HeadTailInfo::strTail, MainTrieInfo::tag, HeadTailInfo::tagTail, and XSD.
Referenced by analyzeHeadTail(), and analyzeSimpleWord().
int MAnalyzer::checkNanalyzeContraction_KEE (Eojul & eojul)
This is a detail analysis function for restoring the KEE('Å°') contraction.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 4120 of file MAnalyzer.cpp.
References _depthHT, _dic, _gcList, _historyAnalysis, _infoHT, StringEx::buffer(), kmaOrange::Eojul::close(), GuessCandidate::closeNXSD(), CODA, CODE_ERROR, CODE_FAIL, CODE_GUESS, CODE_SUCCESS, E_, GuessCandidate::getCurrentNXSD(), kmaOrange::ExCP949::getInfoEnd(), hfK, hmEE, kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::SyllableInfo::info, MA, SearchInfo::mti, N_, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::onset, kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Eojul::setEojulAndInfo(), kmaOrange::Eojul::setMorphAndTag(), HeadTailInfo::strHead, HeadTailInfo::strTail, MainTrieInfo::tag, HeadTailInfo::tagTail, and XSD.
Referenced by analyzeHeadTail(), and analyzeSimpleWord().
int MAnalyzer::checkNanalyzeContraction_KEH (Eojul & eojul)
This is a detail analysis function for restoring the KEH('ï¿½ï¿½') contraction.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 4047 of file MAnalyzer.cpp.
References _depthHT, _dic, _gcList, _historyAnalysis, _infoHT, StringEx::buffer(), kmaOrange::Eojul::close(), GuessCandidate::closeNXSD(), CODA, CODE_ERROR, CODE_FAIL, CODE_GUESS, CODE_SUCCESS, E_, GuessCandidate::getCurrentNXSD(), kmaOrange::ExCP949::getInfoEnd(), hfK, hmEH, kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::SyllableInfo::info, MA, SearchInfo::mti, N_, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::onset, kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Eojul::setEojulAndInfo(), kmaOrange::Eojul::setMorphAndTag(), HeadTailInfo::strHead, HeadTailInfo::strTail, MainTrieInfo::tag, HeadTailInfo::tagTail, and XSD.
Referenced by analyzeHeadTail(), and analyzeSimpleWord().
int kmaOrange::MAnalyzer::checkNanalyzeContraction_UI (Eojul & eojul)
This is a detail analysis function for restoring the UI('ï¿½ï¿½') contraction.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
int MAnalyzer::checkNanalyzeContraction_WAE (Eojul & eojul)
This is a detail analysis function for restoring the WAE('ï¿½ï¿½') contraction.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 3642 of file MAnalyzer.cpp.
References _depthHT, _dic, _historyAnalysis, _infoHT, StringEx::buffer(), kmaOrange::Eojul::close(), CODA, CODE_ERROR, CODE_FAIL, CODE_SUCCESS, EM, kmaOrange::ExCP949::getInfoEnd(), hmWAE, kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::SyllableInfo::info, SearchInfo::mti, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::posCT_WAE, kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Eojul::setMorphAndTag(), kmaOrange::ExCP949::SIT, HeadTailInfo::strHead, HeadTailInfo::strTail, kmaOrange::SyllableInfo::syllable, MainTrieInfo::tag, HeadTailInfo::tagTail, V_, VA, Va, VV, and Vv.
Referenced by analyzeDeclinableWord(), analyzeSimpleWord(), and checkNanalyzePreEomi().
int MAnalyzer::checkNanalyzeContraction_WAHWOH (Eojul & eojul)
This is a detail analysis function for restoring the WAHWOH('ï¿½ï¿½/ï¿½ï¿½') contraction.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 3557 of file MAnalyzer.cpp.
References _depthHT, _dic, _historyAnalysis, _infoHT, StringEx::buffer(), checkNanalyzeIrregularConjugation_BIUP(), kmaOrange::Eojul::close(), CODA, CODE_ERROR, CODE_FAIL, CODE_SUCCESS, EM, kmaOrange::ExCP949::getInfoEnd(), hfO, hmWAH, hmWOH, kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::SyllableInfo::info, SearchInfo::mti, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::onset, kmaOrange::SyllableInfo::posCT_WAHWOH, kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Eojul::setMorphAndTag(), kmaOrange::ExCP949::SIT, HeadTailInfo::strHead, HeadTailInfo::strTail, kmaOrange::SyllableInfo::syllable, MainTrieInfo::tag, HeadTailInfo::tagTail, V_, VA, Va, VV, and Vv.
Referenced by analyzeDeclinableWord(), analyzeSimpleWord(), and checkNanalyzePreEomi().
int kmaOrange::MAnalyzer::checkNanalyzeContraction_WEH (Eojul & eojul)
This is a detail analysis function for restoring the WEH('ï¿½ï¿½') contraction.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
int MAnalyzer::checkNanalyzeContraction_YUR (Eojul & eojul)
This is a detail analysis function for restoring the YUR('ï¿½ï¿½') contraction.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 3711 of file MAnalyzer.cpp.
References kmaOrange::Dictionary::_auxVerb, _avIB, _depthHT, _dic, _gcList, _historyAnalysis, _infoHT, kmaOrange::Dictionary::_predicativeSuffix, _psIB, GuessCandidate::addNVC(), GuessCandidate::addNXSD(), StringEx::buffer(), checkNanalyzeN_(), kmaOrange::Eojul::close(), GuessCandidate::closeAV(), CODA, CODE_ERROR, CODE_FAIL, CODE_GUESS, CODE_SUCCESS, EI_AUXVERB, EM, GuessCandidate::getCurrentAV(), kmaOrange::Eojul::getEojulInfo(), kmaOrange::ExCP949::getInfo(), kmaOrange::InfoBuffer::getInfoByIndex(), kmaOrange::ExCP949::getInfoEnd(), kmaOrange::InfoBuffer::getPositionByIndex(), kmaOrange::InfoBuffer::getSize(), StringEx::getSubString(), kmaOrange::PredicativeSuffix::getXSDInfo(), hfH, hfO, hmAH, hmYUR, kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::SyllableInfo::info, SearchInfo::mti, N_, NNB, NNG, NNP, NNU, NP, NU, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::onset, kmaOrange::XSDInfo::orgForm, kmaOrange::SyllableInfo::posCT_YUR, kmaOrange::AuxVerb::searchNgetInfoFromAvTrie(), kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::PredicativeSuffix::searchNgetInfoFromXsdTrie(), kmaOrange::Eojul::setEojulAndInfo(), kmaOrange::Eojul::setMorphAndTag(), kmaOrange::ExCP949::SIT, HeadTailInfo::strHead, HeadTailInfo::strTail, kmaOrange::SyllableInfo::syllable, MainTrieInfo::tag, HeadTailInfo::tagTail, V_, VA, Va, VC, VV, Vv, VX, and XSD.
Referenced by analyzeDeclinableWord(), analyzeSimpleWord(), and checkNanalyzePreEomi().
int MAnalyzer::checkNanalyzeCopular (Eojul & eojul, unsigned int tagAllowed)
This is a function for analyzing the copular.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
tagAllowed an unsigned integer.
Returns: an integer.
Definition at line 5139 of file MAnalyzer.cpp.
References _depthHT, _gcList, _historyAnalysis, _infoHT, _jecInfo, _jeInfo, GuessCandidate::_nvcCount, _posTail, _strTemp, GuessCandidate::addNVC(), checkNanalyzeN_(), CODA, CODE_ERROR, CODE_FAIL, CODE_GUESS, CODE_SUCCESS, EDI_NOT_VC_ELISION, StringEx::endWith(), EP, EP_SS, kmaOrange::Eojul::getBufferPtr(), kmaOrange::Eojul::getEojulInfo(), kmaOrange::ExCP949::getInfoEnd(), hfO, hmEE, kmaOrange::SyllableInfo::info, JEInfo::info, StringEx::length(), MA, NNB, NNG, NNI, NNP, NNU, NP, NU, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::onset, JEInfo::pstr, StringEx::setSubString(), HeadTailInfo::strHead, HeadTailInfo::strTail, JEInfo::tag, HeadTailInfo::tagTail, and VC.
Referenced by analyzeDeclinableWord(), analyzeSimpleWord(), and checkNanalyzePreEomi().
int MAnalyzer::checkNanalyzeElision_hlL (Eojul & eojul)
This is a detail analysis function for restoring the hlL('ï¿½ï¿½') elision.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 2311 of file MAnalyzer.cpp.
References kmaOrange::Dictionary::_auxVerb, _avIB, _depthHT, _dic, _gcList, _historyAnalysis, _infoHT, _jecInfo, _jeInfo, _posTail, _strTemp, StringEx::buffer(), kmaOrange::Eojul::close(), GuessCandidate::closeAV(), JEInfo::coda, CODA, CODE_FAIL, CODE_SUCCESS, EI_AUXVERB, EM, EP, kmaOrange::Eojul::getBufferPtr(), GuessCandidate::getCurrentAV(), kmaOrange::Eojul::getEojulInfo(), kmaOrange::ExCP949::getInfo(), kmaOrange::ExCP949::getInfoEnd(), kmaOrange::InfoBuffer::getPositionByIndex(), kmaOrange::InfoBuffer::getSize(), hfN, hfO, hlB, hlL, hlN, hmOH, hmUH, kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::SyllableInfo::info, StringEx::length(), SearchInfo::mti, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::onset, kmaOrange::SyllableInfo::posEL_hlL, JEInfo::pstr, kmaOrange::AuxVerb::searchNgetInfoFromAvTrie(), kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Eojul::setEojulAndInfo(), kmaOrange::Eojul::setMorphAndTag(), kmaOrange::ExCP949::SIT, HeadTailInfo::strHead, HeadTailInfo::strTail, kmaOrange::SyllableInfo::syllable, JEInfo::tag, MainTrieInfo::tag, HeadTailInfo::tagTail, V_, VA, Va, VV, Vv, and VX.
Referenced by analyzeDeclinableWord(), analyzeSimpleWord(), and checkNanalyzePreEomi().
int MAnalyzer::checkNanalyzeElision_HOMOPHONE (Eojul & eojul, int tag = 0)
This is a detail analysis function for restoring the homophone elision.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
tag an integer.
Returns: an integer.
Definition at line 2551 of file MAnalyzer.cpp.
References _depthHT, _historyAnalysis, _infoHT, StringEx::buffer(), kmaOrange::Eojul::close(), CODE_FAIL, CODE_SUCCESS, EM, kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::Eojul::setMorphAndTag(), HeadTailInfo::strTail, HeadTailInfo::tagTail, V_, VA, Va, VV, Vv, and VX.
Referenced by analyzeSimpleWord().
int MAnalyzer::checkNanalyzeElision_OO (Eojul & eojul)
This is a detail analysis function for restoring the OO('ï¿½ï¿½') elision.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 2484 of file MAnalyzer.cpp.
References _depthHT, _dic, _historyAnalysis, _infoHT, StringEx::buffer(), kmaOrange::Eojul::close(), CODE_ERROR, CODE_FAIL, CODE_SUCCESS, EM, kmaOrange::ExCP949::getInfoEnd(), kmaOrange::Eojul::increaseAnalysisResults(), SearchInfo::mti, kmaOrange::SyllableInfo::posEL_OO, kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Eojul::setMorphAndTag(), kmaOrange::ExCP949::SIT, HeadTailInfo::strHead, HeadTailInfo::strTail, kmaOrange::SyllableInfo::syllable, MainTrieInfo::tag, HeadTailInfo::tagTail, V_, VA, Va, VV, and Vv.
Referenced by analyzeDeclinableWord(), analyzeSimpleWord(), and checkNanalyzePreEomi().
int MAnalyzer::checkNanalyzeElision_UH (Eojul & eojul)
This is a detail analysis function for restoring the UH('ï¿½ï¿½') elision.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 2200 of file MAnalyzer.cpp.
References _depthHT, _dic, _historyAnalysis, _infoHT, _strTemp, StringEx::buffer(), kmaOrange::Eojul::close(), kmaOrange::SyllableInfo::coda, CODA, CODE_ERROR, CODE_FAIL, CODE_SUCCESS, EM, kmaOrange::ExCP949::getInfo(), kmaOrange::ExCP949::getInfoEnd(), hfO, hlSS, hmAH, hmOH, kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::SyllableInfo::info, StringEx::length(), SearchInfo::mti, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::onset, kmaOrange::SyllableInfo::posEL_UH, kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Eojul::setMorphAndTag(), kmaOrange::ExCP949::SIT, HeadTailInfo::strHead, HeadTailInfo::strTail, kmaOrange::SyllableInfo::syllable, MainTrieInfo::tag, HeadTailInfo::tagTail, V_, VA, Va, VV, and Vv.
Referenced by analyzeDeclinableWord(), analyzeSimpleWord(), and checkNanalyzePreEomi().
int MAnalyzer::checkNanalyzeElision_UR (Eojul & eojul, int tag = 0)
This is a detail analysis function for restoring the UR('ï¿½ï¿½') elision.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
tag an integer.
Returns: an integer.
Definition at line 2611 of file MAnalyzer.cpp.
References _depthHT, _historyAnalysis, _infoHT, StringEx::buffer(), kmaOrange::Eojul::close(), CODE_ERROR, CODE_FAIL, CODE_SUCCESS, EM, kmaOrange::ExCP949::getInfoEnd(), kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::Eojul::setMorphAndTag(), HeadTailInfo::strTail, HeadTailInfo::tagTail, V_, Va, VV, Vv, and VX.
Referenced by analyzeSimpleWord().
int MAnalyzer::checkNanalyzeIrregularConjugation_BIUP (Eojul & eojul)
This is a detail analysis function for restoring the BIUP('ï¿½ï¿½') irregular conjugation.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 2823 of file MAnalyzer.cpp.
References _depthHT, _dic, _historyAnalysis, _infoHT, _jecInfo, _posTail, _strTemp, StringEx::buffer(), kmaOrange::Eojul::close(), JEInfo::coda, CODE_ERROR, CODE_FAIL, CODE_SUCCESS, convertJohabCodaToCP949Onset(), EM, StringEx::empty(), EP, ETN, kmaOrange::Eojul::getBufferPtr(), kmaOrange::ExCP949::getInfo(), kmaOrange::ExCP949::getInfoEnd(), hfR, hlB, hmUR, kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::SyllableInfo::info, IR_BIUP, StringEx::length(), SearchInfo::mti, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::onset, kmaOrange::SyllableInfo::posIR_BIUP, JEInfo::pstr, kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Eojul::setMorphAndTag(), kmaOrange::ExCP949::SIT, HeadTailInfo::strHead, HeadTailInfo::strTail, kmaOrange::SyllableInfo::syllable, JEInfo::tag, MainTrieInfo::tag, HeadTailInfo::tagTail, V_, VA, Va, VV, and Vv.
Referenced by analyzeDeclinableWord(), analyzeSimpleWord(), checkNanalyzeContraction_WAHWOH(), and checkNanalyzePreEomi().
int MAnalyzer::checkNanalyzeIrregularConjugation_DIGT (Eojul & eojul)
This is a detail analysis function for restoring the DIGT('ï¿½ï¿½') irregular conjugation.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 2754 of file MAnalyzer.cpp.
References _depthHT, _dic, _historyAnalysis, _infoHT, StringEx::buffer(), kmaOrange::Eojul::close(), kmaOrange::SyllableInfo::coda, CODE_ERROR, CODE_FAIL, CODE_SUCCESS, kmaOrange::ExCP949::getInfo(), kmaOrange::ExCP949::getInfoEnd(), hfO, hlL, hmAH, hmEE, hmOH, hmOO, hmUH, hmUR, hmYUR, kmaOrange::Eojul::increaseAnalysisResults(), SearchInfo::mti, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::onset, kmaOrange::SyllableInfo::posIR_DIGT, kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Eojul::setMorphAndTag(), kmaOrange::ExCP949::SIT, HeadTailInfo::strHead, HeadTailInfo::strTail, kmaOrange::SyllableInfo::syllable, MainTrieInfo::tag, HeadTailInfo::tagTail, V_, VA, Va, VV, and Vv.
Referenced by analyzeDeclinableWord(), and checkNanalyzePreEomi().
int MAnalyzer::checkNanalyzeIrregularConjugation_GURRA (Eojul & eojul)
This is a detail analysis function for restoring the GURRA('ï¿½Å¶ï¿½') irregular conjugation.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 3227 of file MAnalyzer.cpp.
int MAnalyzer::checkNanalyzeIrregularConjugation_HIUNG (Eojul & eojul)
This is a detail analysis function for restoring the HIUNG('ï¿½ï¿½') irregular conjugation.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 3232 of file MAnalyzer.cpp.
References kmaOrange::Dictionary::_auxVerb, _avIB, _depthHT, _dic, _gcList, _historyAnalysis, _infoHT, _jecInfo, _posTail, _strTemp, StringEx::buffer(), kmaOrange::Eojul::close(), GuessCandidate::closeAV(), kmaOrange::SyllableInfo::coda, CODE_ERROR, CODE_FAIL, CODE_SUCCESS, EI_AUXVERB, EM, kmaOrange::Eojul::getBufferPtr(), GuessCandidate::getCurrentAV(), kmaOrange::Eojul::getEojulInfo(), kmaOrange::ExCP949::getInfoEnd(), kmaOrange::Dictionary::getJEInfo(), kmaOrange::InfoBuffer::getPositionByIndex(), kmaOrange::InfoBuffer::getSize(), hfN, hlB, hlFILL, hlL, hlM, hlN, hmAE, hmAH, hmEH, hmUR, hmWAH, hmYAE, hmYAH, hmYEH, hmYUR, kmaOrange::Eojul::increaseAnalysisResults(), SearchInfo::mti, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::onset, kmaOrange::SyllableInfo::posEX_NUCLEUS, kmaOrange::SyllableInfo::posIR_HIUNG1, kmaOrange::SyllableInfo::posIR_HIUNG2, JEInfo::pstr, kmaOrange::AuxVerb::searchNgetInfoFromAvTrie(), kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Eojul::setEojulAndInfo(), kmaOrange::Eojul::setMorphAndTag(), kmaOrange::ExCP949::SIT, HeadTailInfo::strHead, HeadTailInfo::strTail, kmaOrange::SyllableInfo::syllable, MainTrieInfo::tag, JEInfo::tag, HeadTailInfo::tagTail, V_, VA, Va, VV, Vv, and VX.
Referenced by analyzeDeclinableWord(), analyzeSimpleWord(), and checkNanalyzePreEomi().
int MAnalyzer::checkNanalyzeIrregularConjugation_RUH (Eojul & eojul)
This is a detail analysis function for restoring the RUH('ï¿½ï¿½') irregular conjugation.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 2977 of file MAnalyzer.cpp.
References _depthHT, _dic, _historyAnalysis, _infoHT, StringEx::buffer(), kmaOrange::Eojul::close(), kmaOrange::SyllableInfo::coda, CODA, CODE_ERROR, CODE_FAIL, CODE_SUCCESS, EM, kmaOrange::ExCP949::getInfo(), kmaOrange::ExCP949::getInfoEnd(), hfR, hlL, hmAH, hmUR, kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::SyllableInfo::info, SearchInfo::mti, kmaOrange::SyllableInfo::noncodaposition, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::onset, kmaOrange::SyllableInfo::posIR_RUH, kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Eojul::setMorphAndTag(), kmaOrange::ExCP949::SIT, HeadTailInfo::strHead, HeadTailInfo::strTail, kmaOrange::SyllableInfo::syllable, MainTrieInfo::tag, HeadTailInfo::tagTail, V_, VA, Va, VV, Vv, and VX.
Referenced by analyzeDeclinableWord(), analyzeSimpleWord(), and checkNanalyzePreEomi().
int MAnalyzer::checkNanalyzeIrregularConjugation_RUR (Eojul & eojul)
This is a detail analysis function for restoring the RUR('ï¿½ï¿½') irregular conjugation.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 3162 of file MAnalyzer.cpp.
References _depthHT, _dic, _historyAnalysis, _infoHT, StringEx::buffer(), kmaOrange::Eojul::close(), CODA, CODE_ERROR, CODE_FAIL, CODE_SUCCESS, kmaOrange::ExCP949::getInfo(), kmaOrange::ExCP949::getInfoEnd(), hfR, hmUH, hmUR, kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::SyllableInfo::info, SearchInfo::mti, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::onset, kmaOrange::SyllableInfo::posIR_RUR, kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Eojul::setMorphAndTag(), kmaOrange::ExCP949::SIT, HeadTailInfo::strHead, HeadTailInfo::strTail, kmaOrange::SyllableInfo::syllable, MainTrieInfo::tag, HeadTailInfo::tagTail, V_, VA, Va, VV, and Vv.
Referenced by analyzeDeclinableWord().
int MAnalyzer::checkNanalyzeIrregularConjugation_SIOT (Eojul & eojul)
This is a detail analysis function for restoring the SIOT('ï¿½ï¿½') irregular conjugation.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 2674 of file MAnalyzer.cpp.
References _depthHT, _dic, _historyAnalysis, _infoHT, StringEx::buffer(), kmaOrange::Eojul::close(), CODA, CODE_ERROR, CODE_FAIL, CODE_SUCCESS, kmaOrange::ExCP949::getInfo(), kmaOrange::ExCP949::getInfoEnd(), hfO, hmAE, hmAH, hmEE, hmOH, hmOO, hmUH, hmUR, hmYUR, kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::SyllableInfo::info, SearchInfo::mti, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::onset, kmaOrange::SyllableInfo::posIR_SIOT, kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Eojul::setMorphAndTag(), kmaOrange::ExCP949::SIT, HeadTailInfo::strHead, HeadTailInfo::strTail, kmaOrange::SyllableInfo::syllable, MainTrieInfo::tag, HeadTailInfo::tagTail, V_, VA, Va, VV, and Vv.
Referenced by analyzeDeclinableWord(), and checkNanalyzePreEomi().
int MAnalyzer::checkNanalyzeIrregularConjugation_UR (Eojul & eojul)
This is a detail analysis function for restoring the UR('ï¿½ï¿½') irregular conjugation.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 3480 of file MAnalyzer.cpp.
References _depthHT, _dic, _historyAnalysis, _infoHT, _jecInfo, StringEx::buffer(), kmaOrange::Eojul::close(), CODA, CODE_ERROR, CODE_FAIL, CODE_SUCCESS, EM, kmaOrange::ExCP949::getInfoEnd(), hmAE, kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::SyllableInfo::info, SearchInfo::mti, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::posIR_UR, JEInfo::pstr, kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Eojul::setMorphAndTag(), kmaOrange::ExCP949::SIT, HeadTailInfo::strHead, HeadTailInfo::strTail, kmaOrange::SyllableInfo::syllable, MainTrieInfo::tag, HeadTailInfo::tagTail, V_, VA, Va, VV, and Vv.
Referenced by analyzeDeclinableWord(), analyzeSimpleWord(), and checkNanalyzePreEomi().
int MAnalyzer::checkNanalyzeIrregularConjugation_YUR (Eojul & eojul)
This is a detail analysis function for restoring the YUR('ï¿½ï¿½') irregular conjugation.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 3071 of file MAnalyzer.cpp.
References _depthHT, _dic, _historyAnalysis, _infoHT, _mainList, StringEx::buffer(), kmaOrange::Eojul::close(), CODA, CODE_ERROR, CODE_FAIL, CODE_SUCCESS, kmaOrange::ExCP949::getInfo(), kmaOrange::ExCP949::getInfoEnd(), hfH, hfO, hmAH, hmYUR, kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::SyllableInfo::info, MainTrieInfo::isNNF, StringEx::length(), SearchInfo::mti, N_, NNF, NNG, NNg, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::onset, kmaOrange::SyllableInfo::posIR_YEO, kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Eojul::setMorphAndTag(), kmaOrange::ExCP949::SIT, HeadTailInfo::strHead, HeadTailInfo::strTail, kmaOrange::SyllableInfo::syllable, MainTrieInfo::tag, HeadTailInfo::tagTail, V_, VA, Va, VV, Vv, and XSD.
Referenced by checkNanalyzePreEomi().
int MAnalyzer::checkNanalyzeN_ (Eojul & eojul, unsigned int tagAllowed)
This is a function for analyzing the noun class.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
tagAllowed an unsigned integer.
Returns: an integer.
Definition at line 4397 of file MAnalyzer.cpp.
References _depthHT, _dic, _flagECN, _flagJECN, _historyAnalysis, _infoHT, _jecInfo, _jeInfo, _nnrJ, _strTemp, analyzeEojul_NNR(), StringEx::buffer(), kmaOrange::Eojul::close(), CODE_FAIL, CODE_SUCCESS, StringEx::getBuffer(), kmaOrange::Eojul::getBufferPtr(), kmaOrange::Eojul::increaseAnalysisResults(), JEInfo::info, MainTrieInfo::isNNF, JDI_FLAG_ECN, Jx, StringEx::length(), MA, SearchInfo::mti, N_, NNB, NNb, NNF, NNG, NNg, NNI, NNi, NNP, NNp, NNR, NNU, NNu, NP, Np, NU, Nu, SearchInfo::pinfoNNU, JEInfo::pstr, SCORE_LEN_VALUE, SCORE_WHOLE_NNP, kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Eojul::setMorphAndTag(), kmaOrange::Eojul::setScore(), HeadTailInfo::strHead, HeadTailInfo::strTail, MainTrieInfo::tag, HeadTailInfo::tagTail, and VC.
Referenced by analyzeHeadTail(), checkNanalyzeContraction_YUR(), checkNanalyzeCopular(), and checkNanalyzeXSDecliable().
int MAnalyzer::checkNanalyzePreEomi (Eojul & eojul, unsigned int tagAllowed)
This is a function for analyzing the prefianl ending.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
tagAllowed an unsigned integer.
Returns: an integer.
Definition at line 4536 of file MAnalyzer.cpp.
References kmaOrange::Dictionary::_auxVerb, _avIB, _depthHT, _dic, _flagECN, _gcList, _historyAnalysis, _infoHT, _jecInfo, _jeInfo, _pfeIB, _posTail, kmaOrange::Dictionary::_preEomi, _strTemp, StringEx::buffer(), canBeVE(), checkNanalyzeContraction_WAE(), checkNanalyzeContraction_WAHWOH(), checkNanalyzeContraction_YUR(), checkNanalyzeCopular(), checkNanalyzeElision_hlL(), checkNanalyzeElision_OO(), checkNanalyzeElision_UH(), checkNanalyzeIrregularConjugation_BIUP(), checkNanalyzeIrregularConjugation_DIGT(), checkNanalyzeIrregularConjugation_HIUNG(), checkNanalyzeIrregularConjugation_RUH(), checkNanalyzeIrregularConjugation_SIOT(), checkNanalyzeIrregularConjugation_UR(), checkNanalyzeIrregularConjugation_YUR(), checkNanalyzeXSDecliable(), kmaOrange::Eojul::close(), GuessCandidate::closeAV(), CODA, kmaOrange::SyllableInfo::coda, CODE_ERROR, CODE_FAIL, CODE_SUCCESS, CT_AE, CT_WAE, CT_WAHWOH, CT_YUR, EI_AUXVERB, EL_hlL, EL_OO, EL_UH, EM, StringEx::empty(), StringEx::endWith(), EP, EP_SS, kmaOrange::Eojul::getBufferPtr(), GuessCandidate::getCurrentAV(), kmaOrange::Eojul::getEojulInfo(), kmaOrange::ExCP949::getInfo(), kmaOrange::ExCP949::getInfoEnd(), kmaOrange::InfoBuffer::getPositionByIndex(), kmaOrange::InfoBuffer::getSize(), StringEx::getSubString(), hfG, hfO, hfS, hlSS, hmAH, hmEE, hmEH, hmOH, hmOO, hmUH, hmUR, hmYUR, IC, kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::SyllableInfo::info, IR_DIGT, IR_HIUNG1, IR_HIUNG2, IR_RUH, IR_SIOT, IR_UR, J_, StringEx::length(), MA, MM, SearchInfo::mti, NNP, NNU, kmaOrange::SyllableInfo::noncodaposition, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::onset, kmaOrange::SyllableInfo::posCT_YUR, JEInfo::pstr, kmaOrange::AuxVerb::searchNgetInfoFromAvTrie(), kmaOrange::PreFinalEomi::searchNgetInfoFromEpTrie(), kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Eojul::setEojulAndInfo(), kmaOrange::Eojul::setMorphAndTag(), kmaOrange::ExCP949::SIT, HeadTailInfo::strHead, HeadTailInfo::strTail, kmaOrange::SyllableInfo::syllable, MainTrieInfo::tag, JEInfo::tag, HeadTailInfo::tagTail, V_, VA, Va, VV, Vv, and VX.
Referenced by analyzeDeclinableWord(), and analyzeSimpleWord().
int MAnalyzer::checkNanalyzeV_ (Eojul & eojul, unsigned int tagAllowed)
This is a function for analyzing the verb class.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
tagAllowed an unsigned integer.
Returns: an integer.
Definition at line 5557 of file MAnalyzer.cpp.
References kmaOrange::Dictionary::_auxVerb, _avIB, _depthHT, _dic, _gcList, _historyAnalysis, _infoHT, _jecInfo, _jeInfo, _mainList, _posTail, StringEx::buffer(), kmaOrange::Eojul::close(), GuessCandidate::closeAV(), kmaOrange::SyllableInfo::coda, JEInfo::coda, CODE_ERROR, CODE_FAIL, CODE_SUCCESS, EDI_NOT_VA, EI_AUXVERB, ETM, kmaOrange::Eojul::getBufferPtr(), GuessCandidate::getCurrentAV(), kmaOrange::Eojul::getEojulInfo(), kmaOrange::ExCP949::getInfoEnd(), kmaOrange::InfoBuffer::getPositionByIndex(), kmaOrange::InfoBuffer::getSize(), hlL, kmaOrange::Eojul::increaseAnalysisResults(), JEInfo::info, SearchInfo::mti, kmaOrange::SyllableInfo::noncodaposition, JEInfo::pstr, kmaOrange::AuxVerb::searchNgetInfoFromAvTrie(), kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Eojul::setEojulAndInfo(), kmaOrange::Eojul::setMorphAndTag(), kmaOrange::ExCP949::SIT, HeadTailInfo::strHead, HeadTailInfo::strTail, kmaOrange::SyllableInfo::syllable, MainTrieInfo::tag, JEInfo::tag, HeadTailInfo::tagTail, V_, VA, Va, VV, Vv, and VX.
Referenced by analyzeDeclinableWord(), and analyzeSimpleWord().
int MAnalyzer::checkNanalyzeXSDecliable (Eojul & eojul, unsigned int tagAllowed)
This is a function for analyzing the copular.
Date: 2008-11-13
Author: YoungMin Ahn & HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
tagAllowed an unsigned integer.
Returns: an integer.
Definition at line 5252 of file MAnalyzer.cpp.
References kmaOrange::Dictionary::_auxVerb, _avIB, _depthHT, _dic, _flagECN, _gcList, _historyAnalysis, _infoHT, _jecInfo, _jeInfo, _posTail, kmaOrange::Dictionary::_predicativeSuffix, _psIB, _strTemp, GuessCandidate::addNXSD(), StringEx::buffer(), checkNanalyzeN_(), kmaOrange::Eojul::close(), GuessCandidate::closeAV(), CODA, kmaOrange::SyllableInfo::coda, CODE_ERROR, CODE_FAIL, CODE_GUESS, CODE_SUCCESS, convertJohabCodaToCP949Onset(), CT_AE, CT_WAE, CT_WAHWOH, EDI_RA, EDI_SEO_YA, EI_AUXVERB, EM, EP, ETM, ETN, kmaOrange::Eojul::getBufferPtr(), GuessCandidate::getCurrentAV(), kmaOrange::Eojul::getEojulInfo(), kmaOrange::InfoBuffer::getInfoByIndex(), kmaOrange::ExCP949::getInfoEnd(), kmaOrange::InfoBuffer::getPositionByIndex(), kmaOrange::InfoBuffer::getSize(), StringEx::getSubString(), kmaOrange::PredicativeSuffix::getXSDInfo(), hfD, hfR, hmUR, kmaOrange::Eojul::increaseAnalysisResults(), JEInfo::info, kmaOrange::SyllableInfo::info, IR_BIUP, J_, StringEx::length(), SearchInfo::mti, NNB, NNG, NNP, NNU, kmaOrange::SyllableInfo::noncodaposition, NP, NU, kmaOrange::SyllableInfo::nucleus, kmaOrange::SyllableInfo::onset, kmaOrange::XSDInfo::orgForm, kmaOrange::SyllableInfo::posCT_AE, kmaOrange::SyllableInfo::posCT_WAE, kmaOrange::SyllableInfo::posCT_WAHWOH, kmaOrange::SyllableInfo::posIR_BIUP, JEInfo::pstr, kmaOrange::AuxVerb::searchNgetInfoFromAvTrie(), kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::PredicativeSuffix::searchNgetInfoFromXsdTrie(), kmaOrange::Eojul::setEojulAndInfo(), kmaOrange::Eojul::setMorphAndTag(), kmaOrange::ExCP949::SIT, HeadTailInfo::strHead, HeadTailInfo::strTail, kmaOrange::SyllableInfo::syllable, MainTrieInfo::tag, JEInfo::tag, HeadTailInfo::tagTail, V_, VA, Va, VV, Vv, VX, and XSD.
Referenced by analyzeDeclinableWord(), analyzeSimpleWord(), and checkNanalyzePreEomi().
int MAnalyzer::commonRunWithStream ()
This is a common function of functions, which execute Korean morphological analysis based on a file.
Date: 2008-11-12
Author: HeeGeun Park
Returns: an integer.
 0 - fail.
 1 - success.
Definition at line 943 of file MAnalyzer.cpp.
References _option, _sentence, _stream, _strLineBuffer, kmaOrange::StrStream::close(), DOCUMENT, Sentence::eojulList, kmaOrange::StrStream::getLine(), ListEx< T >::initialize(), StringEx::isEmpty(), kmaOrange::StrStream::isInEOF(), tagging(), TAGGING, and tokenizeSentence().
Referenced by runWithStream().
void MAnalyzer::composeAffixes (Eojul & pEojul)
This function composes a noun and an affix.
Date: 2009-01-05
Author: HeeGeun Park
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Definition at line 207 of file MAnalyzer.cpp.
References _eojul, kmaOrange::Eojul::append(), kmaOrange::Eojul::close(), kmaOrange::Eojul::getCount(), kmaOrange::Eojul::getEojulInfo(), kmaOrange::Eojul::getLexicon(), kmaOrange::Eojul::getLinkedIndex(), kmaOrange::Eojul::getListSize(), kmaOrange::Eojul::getPOS(), kmaOrange::Eojul::getScore(), kmaOrange::Eojul::getScoresPtr(), kmaOrange::Eojul::getString(), kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::Eojul::initialize(), isPerformedNNR, NNC, kmaOrange::Eojul::setEojulAndInfo(), kmaOrange::Eojul::setMorphAndTag(), kmaOrange::Eojul::setScore(), XP, and XSN.
Referenced by runWithEojul(), and tokenizeSentence().
char * MAnalyzer::convertJohabCodaToCP949Onset (unsigned char coda) [inline]
This function converts the KSSM code of onset endings('ï¿½ï¿½', 'ï¿½ï¿½', 'ï¿½ï¿½', 'ï¿½ï¿½') into the CP949 code.
Date: 2008-11-12
Author: YoungMin Ahn
Parameters:
coda an unsigned character - the KSSM code of a onset ending.
Returns: a pointer of a character - the CP949 code.
Definition at line 5119 of file MAnalyzer.cpp.
References _eomiPossibleCoda, hlB, hlL, hlM, and hlN.
Referenced by checkNanalyzeIrregularConjugation_BIUP(), and checkNanalyzeXSDecliable().
int MAnalyzer::getEojulCountInSentence (void) [virtual]
This function gets the number of words in a sentence.
Date: 2008-11-12
Author: HeeGeun Park
Returns: an integer - the number of words in a sentence.
Implements WK_Analyzer.
Definition at line 190 of file MAnalyzer.cpp.
References _sentence, and Sentence::eojulList.
WK_Eojul * MAnalyzer::getEojulInSentence (int nPos) [virtual]
This function gets a Eojul object for a word in a sentence.
Date: 2008-11-12
Author: HeeGeun Park
Parameters:
nPos an integer - the index number of a word in a sentence.
Returns: a pointer of a WK_Eojul object.
Implements WK_Analyzer.
Definition at line 195 of file MAnalyzer.cpp.
References _sentence, and Sentence::eojulList.
int MAnalyzer::getEojulOffsetInSentence (int nPos) [virtual]
Implements WK_Analyzer.
Definition at line 202 of file MAnalyzer.cpp.
References _sentence, and Sentence::eojulList.
ListEx<SearchJEInfo>* kmaOrange::MAnalyzer::getJeList () [inline]
This function gets the informaion list of all grammatical morphemes.
Date: 2008-11-12
Author: YoungMin Ahn
Returns: a pointer of SearchJEInfo object list.
Definition at line 231 of file MAnalyzer.h.
References _jeList.
ListEx<SearchInfo>* kmaOrange::MAnalyzer::getMainList () [inline]
This function gets the informaion list of all lexical morphemes.
Date: 2008-11-12
Author: YoungMin Ahn
Returns: a pointer of SearchInfo object list.
Definition at line 223 of file MAnalyzer.h.
References _mainList.
StrStream * MAnalyzer::getStream ()
Definition at line 307 of file MAnalyzer.cpp.
References _stream.
int MAnalyzer::isAlphabet (const char ch)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 340 of file MAnalyzer.cpp.
int MAnalyzer::isAlphabet (StringEx & strex)
This function checks whether an input string is a alphabet or not.
Date: 2008-11-12
Author: YoungMin Ahn
Parameters:
strex an indirect referncing pointer of StringEx object - an input string.
Returns: an integer.
 0 - not alphabet.
 1 - alphabet.
Definition at line 329 of file MAnalyzer.cpp.
References StringEx::length().
Referenced by analyzeDigitAlphabetWord().
int MAnalyzer::isDigit (const char ch)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 322 of file MAnalyzer.cpp.
int MAnalyzer::isDigit (StringEx & strex)
This function checks whether an input string is a digit or not.
Date: 2008-11-12
Author: YoungMin Ahn
Parameters:
strex an indirect referncing pointer of StringEx object - an input string.
Returns: an integer.
 0 - not digit.
 1 - digit.
Definition at line 312 of file MAnalyzer.cpp.
References StringEx::length().
Referenced by analyzeDigitAlphabetWord(), and tokenizeSentence().
void kmaOrange::MAnalyzer::makePreAnalysisDic (void) [inline, virtual]
This function makes the system pre-analysis dictionary file.
Date: 2009-01-07
Author: HeeGeun Park
Implements WK_Analyzer.
Definition at line 135 of file MAnalyzer.h.
References _isPreAnalysisOut.
int MAnalyzer::makeRanking (Eojul & eojul) [private]
This function calulates the score of each candidate in a Eojul object.
Date: 2008-11-12
Author: YoungMin Ahn
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 873 of file MAnalyzer.cpp.
References _flagV_, kmaOrange::Eojul::getListSize(), kmaOrange::Eojul::getScoresPtr(), isPerformedNNR, and makeSubRanking().
Referenced by runWithEojul(), and tokenizeSentence().
double MAnalyzer::makeSubRanking (int i, Eojul & eojul) [inline, private]
This function calulates the score of a candidate in a Eojul object.
Date: 2008-11-12
Author: YoungMin Ahn
Parameters:
eojul an indirect referncing pointer of a Eojul object.
i an integer - the index number of candidates.
Returns: a double - score.
Definition at line 726 of file MAnalyzer.cpp.
References _flagV_, E_, EP, kmaOrange::Eojul::getBufferPtr(), kmaOrange::Eojul::getCount(), kmaOrange::Eojul::getLexicon(), kmaOrange::Eojul::getPOS(), IC, J_, MA, MM, N_, NNb, NNf, NNg, NNi, NNu, Np, Nu, SCORE_IC, SCORE_LEN_VALUE, SCORE_MA, SCORE_MM, SCORE_NNB, SCORE_NNF, SCORE_NNG, SCORE_NNI, SCORE_NNU, SCORE_NP, SCORE_NU, SCORE_VA, SCORE_VV, SCORE_VX, SN, V_, Va, VC, Vv, VX, and XSD.
Referenced by analyzeEojul_NNR(), and makeRanking().
int MAnalyzer::preprocessBeforeAnalysis (Sentence & sentence)
This is a proprocessing function of functions, which execute Korean morphological analysis based on a file.
Date: 2008-11-12
Author: HeeGeun Park
Parameters:
sentence an indirect referencing pointer of a Sentence object.
Returns: an integer.
Definition at line 1000 of file MAnalyzer.cpp.
References _option, _pCommonEojul, _sentence, _stream, analyzeEojul(), Sentence::eojulList, kmaOrange::StrStream::getOutStream(), ListEx< T >::initialize(), kmaOrange::Eojul::showInfomation(), and WRITING.
int MAnalyzer::runWithEojul (void) [virtual]
This function executes Korean morphological analysis based on a word.
Date: 2008-11-12
Author: HeeGeun Park
Returns: an integer.
 0 - fail.
 1 - success.
Implements WK_Analyzer.
Definition at line 906 of file MAnalyzer.cpp.
References _option, _pCommonEojul, analyzeEojul(), COMPOSEAFFIX, composeAffixes(), kmaOrange::Eojul::makeNBest(), makeRanking(), and mOptionNBest.
int MAnalyzer::runWithStream () [virtual]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Implements WK_Analyzer.
Definition at line 922 of file MAnalyzer.cpp.
References commonRunWithStream().
int MAnalyzer::runWithStream (char * strNameInFile) [virtual]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Implements WK_Analyzer.
Definition at line 929 of file MAnalyzer.cpp.
References _stream, commonRunWithStream(), and kmaOrange::StrStream::setStream().
int MAnalyzer::runWithStream (char * strNameInFile, char * strNameOutFile) [virtual]
This function executes Korean morphological analysis based on a file.
Date: 2008-11-12
Author: HeeGeun Park
Parameters:
strNameInFile a pointer of a character - input file.
strNameOutFile a pointer of a character - output file.
Returns: an integer.
 0 - fail.
 1 - success.
Implements WK_Analyzer.
Definition at line 936 of file MAnalyzer.cpp.
References _stream, commonRunWithStream(), and kmaOrange::StrStream::setStream().
int MAnalyzer::runWithString (char * strLine) [virtual]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Implements WK_Analyzer.
Definition at line 962 of file MAnalyzer.cpp.
References _strLineBuffer, and runWithString().
int MAnalyzer::runWithString (StringEx & strLine) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 968 of file MAnalyzer.cpp.
References _sentence, _strLineBuffer, Sentence::eojulList, ListEx< T >::initialize(), StringEx::isEmpty(), and tokenizeSentence().
int MAnalyzer::runWithString (char * strLine, char * strNameOutFile) [virtual]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Implements WK_Analyzer.
Definition at line 980 of file MAnalyzer.cpp.
References _strLineBuffer, and runWithString().
int MAnalyzer::runWithString (StringEx & strLine, char * strNameOutFile) [inline]
This function executes Korean morphological analysis based on a sentence.
Date: 2008-11-12
Author: HeeGeun Park
Parameters:
strLine a pointer of a character - an input string.
strNameOutFile a pointer of a character - the name of an output file.
Returns: an integer.
 0 - fail.
 1 - success.
Definition at line 986 of file MAnalyzer.cpp.
References _sentence, _stream, _strLineBuffer, Sentence::eojulList, ListEx< T >::initialize(), StringEx::isEmpty(), kmaOrange::StrStream::setOutStream(), and tokenizeSentence().
Referenced by runWithString().
void MAnalyzer::setDefault () [inline]
This function sets several options and global variables to default status.
Date: 2008-11-12
Author: YoungMin Ahn
Definition at line 147 of file MAnalyzer.cpp.
References _decomposeNNP, _depthHT, _dic, _historyAnalysis, _infoHT, _isAnalyzed, _isPreAnalysisOut, _option, _pCommonEojul, _posTail, _stream, _strLineBuffer, _strTemp, _strTemp2, _tagger, DEFAULT_STRINGEX_BUFF_SIZE, MAX_DEPTH, kmaOrange::Eojul::mIndexTagSet, mOptionExtractAdnominal, mOptionExtractAdverb, mOptionExtractAlpha, mOptionExtractInterjection, mOptionExtractNum, mOptionExtractUnknown, mOptionExtractVerbStems, mOptionNBest, NNC, NNF, NNG, NNI, NNP, NNU, StringEx::setBufferSize(), kmaOrange::DecomposeNNP::setDicionary(), setOption(), kmaOrange::Tagger::setStream(), SIZE_LINE_BUFFER, HeadTailInfo::strHead, HeadTailInfo::strTail, HeadTailInfo::tagHead, HeadTailInfo::tagTail, and WKO_OPTION_N_BEST.
Referenced by MAnalyzer().
void kmaOrange::MAnalyzer::setEojul (WK_Eojul * pEojul) [inline, virtual]
This function sets a WK_Eojul object.
Date: 2008-11-12
Author: HeeGeun Park
Parameters:
pEojul a pointer of a WK_Eojul object.
Implements WK_Analyzer.
Definition at line 51 of file MAnalyzer.h.
References _pCommonEojul.
void kmaOrange::MAnalyzer::setExOption (int nOption = 0) [inline, virtual]
This function sets execution options.
Date: 2008-10-31
Author: HeeGeun Park
Parameters:
nOption an integer - a kind of excution options.
Implements WK_Analyzer.
Definition at line 68 of file MAnalyzer.h.
References _option.
void kmaOrange::MAnalyzer::setKnowledge (WK_Knowledge * pKnowledge) [inline, virtual]
This function sets a WK_Knowledge object.
Date: 2008-11-12
Author: HeeGeun Park
Parameters:
pKnowledge a pointer of a WK_Knowledge object.
Implements WK_Analyzer.
Definition at line 43 of file MAnalyzer.h.
References _decomposeNNP, _dic, and kmaOrange::DecomposeNNP::setDicionary().
void MAnalyzer::setOption (int nOption, int nValue) [virtual]
This function sets Korean morphological analyzing options.
Date: 2008-11-12
Author: HeeGeun Park
Parameters:
nOption an integer - a kind of analyzing options.
nValue an integer - the value of a variable nOption.
Implements WK_Analyzer.
Definition at line 74 of file MAnalyzer.cpp.
References _pCommonEojul, FL, IC, MA, kmaOrange::Eojul::mIndexLength, kmaOrange::Eojul::mIndexTagSet, MM, mOptionExtractAdnominal, mOptionExtractAdverb, mOptionExtractAlpha, mOptionExtractBoundNoun, mOptionExtractInterjection, mOptionExtractNum, mOptionExtractUnknown, mOptionExtractVerbStems, mOptionNBest, NNB, NNR, SN, VA, VV, VX, WKO_OPTION_EXTRACT_ADNOMINAL, WKO_OPTION_EXTRACT_ADVERB, WKO_OPTION_EXTRACT_ALPHA, WKO_OPTION_EXTRACT_BOUND_NOUN, WKO_OPTION_EXTRACT_INTERJECTION, WKO_OPTION_EXTRACT_NUM, WKO_OPTION_EXTRACT_UNKNOWN, WKO_OPTION_EXTRACT_VERB_STEMS, and WKO_OPTION_N_BEST.
Referenced by setDefault().
void MAnalyzer::tagging (void) [virtual]
Implements WK_Analyzer.
Definition at line 6372 of file MAnalyzer.cpp.
References _option, _sentence, _tagger, kmaOrange::Tagger::getTaggedResult(), kmaOrange::Tagger::runTagging(), kmaOrange::Tagger::setSentence(), kmaOrange::Tagger::showResult(), TAGGING, and WRITING.
Referenced by commonRunWithStream().
void MAnalyzer::tokenizeSentence (Sentence & sentence, const StringEx & strLine)
This function tokenizes a input string and sets a Sentence object.
Date: 2008-11-12
Author: YoungMin Ahn & HeeGeun Park
Parameters:
sentence an indirect referencing pointer of a Sentence object.
strLine an indirect referencing pointer of a constant StringEx object.
Definition at line 347 of file MAnalyzer.cpp.
References _isPreAnalysisOut, _option, _pCommonEojul, _stream, _wcharDelimiter, ListEx< T >::addTuple(), analyzeEojul(), COMPOSEAFFIX, composeAffixes(), kmaOrange::WK_Hanja::convertToHangul(), DEFAULT_LINE_BUFF_SIZE, DEFAULT_WORD_SIZE, DOCUMENT, EI_ALPHABET, EI_CONNECTED, EI_DIGIT, EI_HANGUL, EI_ILLEGAL, EI_NODIVIDE, EI_OTHER, EI_PUNCT, EI_TOOLONG, Sentence::eojulList, StringEx::getIndex(), kmaOrange::StrStream::getOutStream(), kmaOrange::Eojul::initialize(), isDigit(), StringEx::length(), makeRanking(), kmaOrange::Eojul::setEojulAndInfo(), kmaOrange::Logger::SetMessage(), kmaOrange::Eojul::showInfomation(), TAGGING, TEI_CONNECTED, TEI_CONTINUED, TEI_INCLUDESC, TEI_NODIVIDE, and WRITING.
Referenced by commonRunWithStream(), and runWithString().
int MAnalyzer::warmUpAnalysis (Eojul & eojul, bool isVXMode)
This function sets the dictionary information for morphological analysis.
Date: 2008-11-13
Author: YoungMin Ahn
Parameters:
eojul an indirect referncing pointer of a Eojul object.
Returns: an integer.
Definition at line 1601 of file MAnalyzer.cpp.
References _dic, _jeList, ListEx< T >::addTuple(), E_, EDI_NOT_JX, EDI_NOT_VX, Etn, kmaOrange::Eojul::getBufferPtr(), kmaOrange::Dictionary::getJEInfo(), hlFILL, JEInfo::info, J_, JDI_NOT_EM, JDI_NOT_JX, JDI_ONLY_N_, SearchJEInfo::jeti, Jx, SearchJEInfo::pos, SearchJEInfo::posEnd, kmaOrange::Dictionary::searchNgetInfoFromJosaEomiTrie(), and JosaEomiTrieInfo::tag.
Referenced by analyzeEojul().
Member Data Documentation
ListEx<SearchInfo> kmaOrange::MAnalyzer::_allN_List [private]
Definition at line 179 of file MAnalyzer.h.
Eojul kmaOrange::MAnalyzer::_avEojul [private]
Definition at line 150 of file MAnalyzer.h.
Referenced by analyzeEojul_AuxVerb().
InfoBuffer kmaOrange::MAnalyzer::_avIB [private]
Definition at line 135 of file MAnalyzer.h.
Referenced by analyzeEojul(), checkNanalyzeContraction_YUR(), checkNanalyzeElision_hlL(), checkNanalyzeIrregularConjugation_HIUNG(), checkNanalyzePreEomi(), checkNanalyzeV_(), and checkNanalyzeXSDecliable().
StringEx MAnalyzer::_charDelimiter = `?!.-,\`'()[]<>~\\:;`_/|+=*&^%$#@{}` [static, private]
Definition at line 160 of file MAnalyzer.h.
Referenced by analyzeDigitAlphabetWord().
StringEx MAnalyzer::_charSpecialJosa = `´Â:¸¦:²²:À»:Àº` [static, private]
Definition at line 162 of file MAnalyzer.h.
Referenced by analyzeEojul_Guess_NJ().
DecomposeNNP kmaOrange::MAnalyzer::_decomposeNNP [private]
Definition at line 148 of file MAnalyzer.h.
Referenced by analyzeEojul_NNR(), setDefault(), and setKnowledge().
int kmaOrange::MAnalyzer::_depthHT [private]
Definition at line 154 of file MAnalyzer.h.
Referenced by analyzeDeclinableWord(), analyzeEojul(), analyzeEojul_NNR(), analyzeHeadTail(), analyzeSimpleWord(), checkNanalyzeContraction_CHEE(), checkNanalyzeContraction_KEE(), checkNanalyzeContraction_KEH(), checkNanalyzeContraction_WAE(), checkNanalyzeContraction_WAHWOH(), checkNanalyzeContraction_YUR(), checkNanalyzeCopular(), checkNanalyzeElision_hlL(), checkNanalyzeElision_HOMOPHONE(), checkNanalyzeElision_OO(), checkNanalyzeElision_UH(), checkNanalyzeElision_UR(), checkNanalyzeIrregularConjugation_BIUP(), checkNanalyzeIrregularConjugation_DIGT(), checkNanalyzeIrregularConjugation_HIUNG(), checkNanalyzeIrregularConjugation_RUH(), checkNanalyzeIrregularConjugation_RUR(), checkNanalyzeIrregularConjugation_SIOT(), checkNanalyzeIrregularConjugation_UR(), checkNanalyzeIrregularConjugation_YUR(), checkNanalyzeN_(), checkNanalyzePreEomi(), checkNanalyzeV_(), checkNanalyzeXSDecliable(), and setDefault().
Dictionary* kmaOrange::MAnalyzer::_dic [private]
Definition at line 144 of file MAnalyzer.h.
Referenced by analyzeDeclinableWord(), analyzeEojul(), analyzeEojul_NNR(), analyzeHeadTail(), analyzeSimpleWord(), analyzeSubHangulWordforFL(), analyzeSubHangulWordforSN(), checkNanalyzeContraction_CHEE(), checkNanalyzeContraction_KEE(), checkNanalyzeContraction_KEH(), checkNanalyzeContraction_WAE(), checkNanalyzeContraction_WAHWOH(), checkNanalyzeContraction_YUR(), checkNanalyzeElision_hlL(), checkNanalyzeElision_OO(), checkNanalyzeElision_UH(), checkNanalyzeIrregularConjugation_BIUP(), checkNanalyzeIrregularConjugation_DIGT(), checkNanalyzeIrregularConjugation_HIUNG(), checkNanalyzeIrregularConjugation_RUH(), checkNanalyzeIrregularConjugation_RUR(), checkNanalyzeIrregularConjugation_SIOT(), checkNanalyzeIrregularConjugation_UR(), checkNanalyzeIrregularConjugation_YUR(), checkNanalyzeN_(), checkNanalyzePreEomi(), checkNanalyzeV_(), checkNanalyzeXSDecliable(), MAnalyzer(), setDefault(), setKnowledge(), warmUpAnalysis(), and ~MAnalyzer().
JEInfo kmaOrange::MAnalyzer::_emptyJEInfo [private]
Definition at line 178 of file MAnalyzer.h.
Eojul kmaOrange::MAnalyzer::_eojul [private]
Definition at line 146 of file MAnalyzer.h.
Referenced by analyzeEojul(), and composeAffixes().
char * MAnalyzer::_eomiPossibleCoda = `¤¤\0¤©\0¤±\0¤²\0` [static, private]
Definition at line 159 of file MAnalyzer.h.
Referenced by convertJohabCodaToCP949Onset().
int kmaOrange::MAnalyzer::_flagECN [private]
Definition at line 169 of file MAnalyzer.h.
Referenced by analyzeDeclinableWord(), analyzeEojul(), analyzeSimpleWord(), checkNanalyzeN_(), checkNanalyzePreEomi(), and checkNanalyzeXSDecliable().
int kmaOrange::MAnalyzer::_flagJECN [private]
Definition at line 170 of file MAnalyzer.h.
Referenced by analyzeEojul(), and checkNanalyzeN_().
int kmaOrange::MAnalyzer::_flagV_ [private]
Definition at line 168 of file MAnalyzer.h.
Referenced by makeRanking(), and makeSubRanking().
GuessCandidate kmaOrange::MAnalyzer::_gcList [private]
Definition at line 156 of file MAnalyzer.h.
Referenced by analyzeEojul(), analyzeEojul_AuxVerb(), analyzeEojul_Guess(), analyzeEojul_Guess_NJ(), analyzeEojul_Guess_NVC(), analyzeEojul_Guess_NXSD(), analyzeEojul_NNR(), analyzeHeadTail(), checkNanalyzeContraction_KEE(), checkNanalyzeContraction_KEH(), checkNanalyzeContraction_YUR(), checkNanalyzeCopular(), checkNanalyzeElision_hlL(), checkNanalyzeIrregularConjugation_HIUNG(), checkNanalyzePreEomi(), checkNanalyzeV_(), and checkNanalyzeXSDecliable().
unsigned int kmaOrange::MAnalyzer::_historyAnalysis [private]
Definition at line 158 of file MAnalyzer.h.
Referenced by analyzeDeclinableWord(), analyzeEojul(), analyzeEojul_Guess(), analyzeEojul_NNR(), analyzeHeadTail(), analyzeSimpleWord(), checkNanalyzeContraction_CHEE(), checkNanalyzeContraction_KEE(), checkNanalyzeContraction_KEH(), checkNanalyzeContraction_WAE(), checkNanalyzeContraction_WAHWOH(), checkNanalyzeContraction_YUR(), checkNanalyzeCopular(), checkNanalyzeElision_hlL(), checkNanalyzeElision_HOMOPHONE(), checkNanalyzeElision_OO(), checkNanalyzeElision_UH(), checkNanalyzeElision_UR(), checkNanalyzeIrregularConjugation_BIUP(), checkNanalyzeIrregularConjugation_DIGT(), checkNanalyzeIrregularConjugation_HIUNG(), checkNanalyzeIrregularConjugation_RUH(), checkNanalyzeIrregularConjugation_RUR(), checkNanalyzeIrregularConjugation_SIOT(), checkNanalyzeIrregularConjugation_UR(), checkNanalyzeIrregularConjugation_YUR(), checkNanalyzeN_(), checkNanalyzePreEomi(), checkNanalyzeV_(), checkNanalyzeXSDecliable(), and setDefault().
HeadTailInfo kmaOrange::MAnalyzer::_infoHT[MAX_DEPTH] [private]
Definition at line 153 of file MAnalyzer.h.
Referenced by analyzeDeclinableWord(), analyzeEojul(), analyzeEojul_NNR(), analyzeHeadTail(), analyzeSimpleWord(), checkNanalyzeContraction_CHEE(), checkNanalyzeContraction_KEE(), checkNanalyzeContraction_KEH(), checkNanalyzeContraction_WAE(), checkNanalyzeContraction_WAHWOH(), checkNanalyzeContraction_YUR(), checkNanalyzeCopular(), checkNanalyzeElision_hlL(), checkNanalyzeElision_HOMOPHONE(), checkNanalyzeElision_OO(), checkNanalyzeElision_UH(), checkNanalyzeElision_UR(), checkNanalyzeIrregularConjugation_BIUP(), checkNanalyzeIrregularConjugation_DIGT(), checkNanalyzeIrregularConjugation_HIUNG(), checkNanalyzeIrregularConjugation_RUH(), checkNanalyzeIrregularConjugation_RUR(), checkNanalyzeIrregularConjugation_SIOT(), checkNanalyzeIrregularConjugation_UR(), checkNanalyzeIrregularConjugation_YUR(), checkNanalyzeN_(), checkNanalyzePreEomi(), checkNanalyzeV_(), checkNanalyzeXSDecliable(), and setDefault().
int kmaOrange::MAnalyzer::_isAnalyzed [private]
Definition at line 157 of file MAnalyzer.h.
Referenced by analyzeEojul(), analyzeEojul_AuxVerb(), analyzeHeadTail(), and setDefault().
bool kmaOrange::MAnalyzer::_isPreAnalysisOut [private]
Definition at line 171 of file MAnalyzer.h.
Referenced by analyzeEojul(), makePreAnalysisDic(), setDefault(), and tokenizeSentence().
int kmaOrange::MAnalyzer::_isSJ [private]
Definition at line 166 of file MAnalyzer.h.
Referenced by analyzeEojul(), analyzeEojul_Guess(), analyzeEojul_Guess_NJ(), and analyzeEojul_NNR().
JEInfo kmaOrange::MAnalyzer::_jecInfo [private]
Definition at line 177 of file MAnalyzer.h.
Referenced by analyzeDeclinableWord(), analyzeHeadTail(), analyzeSimpleWord(), checkNanalyzeCopular(), checkNanalyzeElision_hlL(), checkNanalyzeIrregularConjugation_BIUP(), checkNanalyzeIrregularConjugation_HIUNG(), checkNanalyzeIrregularConjugation_UR(), checkNanalyzeN_(), checkNanalyzePreEomi(), checkNanalyzeV_(), and checkNanalyzeXSDecliable().
JEInfo kmaOrange::MAnalyzer::_jeInfo [private]
Definition at line 176 of file MAnalyzer.h.
Referenced by analyzeDeclinableWord(), analyzeHeadTail(), analyzeSimpleWord(), checkNanalyzeCopular(), checkNanalyzeElision_hlL(), checkNanalyzeN_(), checkNanalyzePreEomi(), checkNanalyzeV_(), and checkNanalyzeXSDecliable().
ListEx<SearchJEInfo> kmaOrange::MAnalyzer::_jeList [private]
Definition at line 175 of file MAnalyzer.h.
Referenced by analyzeEojul(), getJeList(), and warmUpAnalysis().
ListEx<SearchInfo> kmaOrange::MAnalyzer::_mainList [private]
Definition at line 174 of file MAnalyzer.h.
Referenced by analyzeEojul(), analyzeSimpleWord(), checkNanalyzeIrregularConjugation_YUR(), checkNanalyzeV_(), and getMainList().
ListEx< vector<int> > kmaOrange::MAnalyzer::_nnpList [private]
Definition at line 180 of file MAnalyzer.h.
int kmaOrange::MAnalyzer::_nnrJ [private]
Definition at line 165 of file MAnalyzer.h.
Referenced by analyzeDigitAlphabetWord(), analyzeEojul(), analyzeEojul_Guess_NJ(), analyzeEojul_Guess_NVC(), analyzeEojul_Guess_NXSD(), analyzeEojul_NNR(), analyzeHeadTail(), analyzeSimpleWord(), and checkNanalyzeN_().
StringEx MAnalyzer::_nnrJosa = `ÀÇ` [static, private]
Definition at line 163 of file MAnalyzer.h.
int kmaOrange::MAnalyzer::_nnrMode [private]
Definition at line 164 of file MAnalyzer.h.
Referenced by analyzeEojul(), analyzeEojul_NNR(), analyzeSubHangulWordforFL(), and analyzeSubHangulWordforSN().
unsigned char kmaOrange::MAnalyzer::_option [private]
Definition at line 167 of file MAnalyzer.h.
Referenced by commonRunWithStream(), preprocessBeforeAnalysis(), runWithEojul(), setDefault(), setExOption(), tagging(), and tokenizeSentence().
Eojul* kmaOrange::MAnalyzer::_pCommonEojul [private]
Definition at line 145 of file MAnalyzer.h.
Referenced by MAnalyzer(), preprocessBeforeAnalysis(), runWithEojul(), setDefault(), setEojul(), setOption(), tokenizeSentence(), and ~MAnalyzer().
InfoBuffer kmaOrange::MAnalyzer::_pfeIB [private]
Definition at line 143 of file MAnalyzer.h.
Referenced by checkNanalyzePreEomi().
int kmaOrange::MAnalyzer::_posTail [private]
Definition at line 173 of file MAnalyzer.h.
Referenced by analyzeDeclinableWord(), analyzeEojul(), analyzeHeadTail(), checkNanalyzeCopular(), checkNanalyzeElision_hlL(), checkNanalyzeIrregularConjugation_BIUP(), checkNanalyzeIrregularConjugation_HIUNG(), checkNanalyzePreEomi(), checkNanalyzeV_(), checkNanalyzeXSDecliable(), and setDefault().
InfoBuffer kmaOrange::MAnalyzer::_psIB [private]
Definition at line 142 of file MAnalyzer.h.
Referenced by checkNanalyzeContraction_YUR(), and checkNanalyzeXSDecliable().
Sentence kmaOrange::MAnalyzer::_sentence [private]
Definition at line 151 of file MAnalyzer.h.
Referenced by commonRunWithStream(), getEojulCountInSentence(), getEojulInSentence(), getEojulOffsetInSentence(), preprocessBeforeAnalysis(), runWithString(), and tagging().
StrStream kmaOrange::MAnalyzer::_stream [private]
Definition at line 147 of file MAnalyzer.h.
Referenced by commonRunWithStream(), getStream(), preprocessBeforeAnalysis(), runWithStream(), runWithString(), setDefault(), and tokenizeSentence().
StringEx kmaOrange::MAnalyzer::_strLineBuffer [private]
Definition at line 152 of file MAnalyzer.h.
Referenced by commonRunWithStream(), runWithString(), and setDefault().
StringEx kmaOrange::MAnalyzer::_strTemp [private]
Definition at line 155 of file MAnalyzer.h.
Referenced by analyzeEojul(), analyzeEojul_Guess_NJ(), analyzeEojul_NNR(), analyzeSimpleWord(), checkNanalyzeCopular(), checkNanalyzeElision_hlL(), checkNanalyzeElision_UH(), checkNanalyzeIrregularConjugation_BIUP(), checkNanalyzeIrregularConjugation_HIUNG(), checkNanalyzeN_(), checkNanalyzePreEomi(), checkNanalyzeXSDecliable(), and setDefault().
StringEx kmaOrange::MAnalyzer::_strTemp2 [private]
Definition at line 155 of file MAnalyzer.h.
Referenced by analyzeEojul_NNR(), and setDefault().
Tagger kmaOrange::MAnalyzer::_tagger [private]
Definition at line 149 of file MAnalyzer.h.
Referenced by setDefault(), and tagging().
StringEx MAnalyzer::_wcharDelimiter = `¤ý:£¡:£§:£¬:£®:£¯:£º:£»:£¿:£Þ:£ß:£à:£ü:£þ:¡¢:¡£:¡¤:¡¥:¡¦:¡§:¡¨:¡©:¡ª:¡«:¡¬:¡­:¢¥:¢¦:¢§:¢¨:¢©:¢ª:¢«:¢¬:¢­:¢®:¢¯:¢°:£¢:£¨:£©:£Û:£Ý:£û:£ý:¡®:¡¯:¡°:¡±:¡²:¡³:¡´:¡µ:¡¶:¡·:¡¸:¡¹:¡º:¡»:¡¼:¡½:£«:£­:£¼:£½:£¾:¡¾:¡¿:¡À:¡Á:¡Â:¡Ã:¡Ä:¡Å:¡Î:¡Ï:¡Ð:¡Ñ:¡Ò:¡Ó:¡Ô:¡Õ:¡Ö:¡ì:¡í:¡î:¡ï:¡ð:¡ñ:¡ò:¡ó:¡ô:¡õ:¡ö:¡÷:¡ø:¡ù:¡ú:¡û:¡ü:¡ý:¡þ:¢¡:¢¢:¢£:¢¤:¢±:¢²:¢³:£¤:£¥:£Ü:£Æ:¡Ç:¡È:¡É:¡Ê:¡Ë:¡Ì:¡Í:¢´:¢µ:¢¶:?:§¡:§¢:§£:§¥:§¦:§§:§¨:§©:§ª:§«:§¬:§­:§®:§¯:§°:§±:§²:§³:§´:§µ:§¶:§·:§¸:§¹:§º:§»:§¼:§½:§¾:§¿:§À:§Á:§Â:§Ã:§Ä:§Å:§Æ:§Ç:§È:§É:§Ê:§Ë:§Ì:§Í:§Î:§Ï:§Ð:§Ñ:§Ò:§Ó:§Ô:§Õ:§Ö:§×:§Ø:§Ù:§Ú:§Û:§Ü:§Ý:§Þ:§ß:§à:§á:§â:§ã:§ä:§å:§æ:§ç:§è:§é:§ê:§ë:§ì:§í:§î:§ï:££:£¦:£ª:£À:¡×:¡Ø:¡Ù:¡Ú:¡Û:¡Ü:¡Ý:¡Þ:¡ß:¡à:¡á:¡â:¡ã:¡ä:¡å:¡æ:¡ç:¡è:¡é:¡ê:¡ë:¢¹:¢¸:¢¹:¢º:¢»:¢¼:¢½:¢¾:¢¿:¢Á:¢Â:¢Ã:¢Ä:¢Å:¢Æ:¢Ç:¢È:¢É:¢Ê:¢Ë:¢Ì:¢Í:¢Î:¢Ï:¢Ð:¢Ñ:¢Ò:¢Ó:¢Ô:¢Õ:¢Ö:¢×:¢Ø:¢Ù:¢Ú:¢Û:¢Ü:¢Ý:¢Þ:¢ß:¢à:¢á:¢â:¢ã:¢ä:¢å:?:¨£:¨¬:¦¡:¦¢:¦£:¦¤:¦¥:¦¦:¦§:¦¨:¦©:¦ª:¦«:¦¬:¦­:¦®:¦¯:¦°:¦±:¦²:¦³:¦´:¦µ:¦¶:¦·:¦¸:¦¹:¦º:¦»:¦¼:¦½:¦¾:¦¿:¦À:¦Á:¦Â:¦Ã:¦Ä:¦Å:¦Æ:¦Ç:¦È:¦É:¦Ê:¦Ë:¦Ì:¦Í:¦Î:¦Ï:¦Ð:¦Ñ:¦Ò:¦Ô:¦Õ:¦Ö:¦×:¦Ø:¦Ù:¦Ú:¦Û:¦Ü:¦Ý:¦Þ:¦ß:¦à:¦á:¦â:¦ã:¦ä:¨±:¨²:¨³:¨´:¨µ:¨¶:¨·:¨¸:¨¹:¨º:¨»:¨¼:¨½:¨¾:¨¿:¨À:¨Á:¨Â:¨Ã:¨Ä:¨Å:¨Æ:¨Ç:¨È:¨É:¨Ê:¨Ë:¨Ì:©±:©²:©³:©´:©µ:©¶:©·:©¸:©¹:©º:©»:©¼:©½:©¾:©¿:©À:©Á:©Â:©Ã:©Ä:©Å:©Æ:©Ç:©È:©É:©Ê:©Ë:©Ì:¨Í:¨Î:¨Ï:¨Ð:¨Ñ:¨Ò:¨Ó:¨Ô:¨Õ:¨Ö:¨×:¨Ø:¨Ù:¨Ú:¨Û:¨Ü:¨Ý:¨Þ:¨ß:¨à:¨á:¨â:¨ã:¨ä:¨å:¨æ:¨ç:¨è:¨é:¨ê:¨ë:¨ì:¨í:¨î:¨ï:¨ð:¨ñ:¨ò:¨ó:¨ô:¨õ:©Í:©Î:©Ï:©Ð:©Ñ:©Ò:©Ó:©Ô:©Õ:©Ö:©×:©Ø:©Ù:©Ú:©Û:©Ü:©Ý:©Þ:©ß:©à:©á:©â:©ã:©ä:©å:©æ:©ç:©è:©é:©ê:©ë:©ì:©í:©î:©ï:©ð:©ñ:©ò:©ó:©ô:©õ:£°:£±:£²:£³:£´:£µ:£¶:£·:£¸:£¹:¥¡:¥¢:¥£:¥¤:¥¥:¥¦:¥§:¥¨:¥©:¥ª:¥°:¥±:¥²:¥³:¥´:¥µ:¥¶:¥·:¥¸:¥¹:¨ö:¨÷:¨ø:¨ù:¨ú:¨û:¨ü:¨ý:¨þ:©ö:©÷:©ø:©ù:©ú:©û:©ü:©ý:©þ` [static, private]
Definition at line 161 of file MAnalyzer.h.
Referenced by tokenizeSentence().
int kmaOrange::MAnalyzer::isC
Definition at line 827 of file MAnalyzer.h.
Referenced by MAnalyzer(), and ~MAnalyzer().
bool kmaOrange::MAnalyzer::isPerformedNNR [private]
Definition at line 181 of file MAnalyzer.h.
Referenced by analyzeEojul(), analyzeEojul_NNR(), composeAffixes(), and makeRanking().
char kmaOrange::MAnalyzer::mOptionExtractAdnominal [private]
Definition at line 187 of file MAnalyzer.h.
Referenced by setDefault(), and setOption().
char kmaOrange::MAnalyzer::mOptionExtractAdverb [private]
Definition at line 188 of file MAnalyzer.h.
Referenced by setDefault(), and setOption().
char kmaOrange::MAnalyzer::mOptionExtractAlpha [private]
Definition at line 184 of file MAnalyzer.h.
Referenced by setDefault(), and setOption().
char kmaOrange::MAnalyzer::mOptionExtractBoundNoun [private]
Definition at line 191 of file MAnalyzer.h.
Referenced by setOption().
char kmaOrange::MAnalyzer::mOptionExtractInterjection [private]
Definition at line 189 of file MAnalyzer.h.
Referenced by setDefault(), and setOption().
char kmaOrange::MAnalyzer::mOptionExtractNum [private]
Definition at line 185 of file MAnalyzer.h.
Referenced by setDefault(), and setOption().
char kmaOrange::MAnalyzer::mOptionExtractUnknown [private]
Definition at line 190 of file MAnalyzer.h.
Referenced by setDefault(), and setOption().
char kmaOrange::MAnalyzer::mOptionExtractVerbStems [private]
Definition at line 186 of file MAnalyzer.h.
Referenced by setDefault(), and setOption().
char kmaOrange::MAnalyzer::mOptionNBest [private]
Definition at line 183 of file MAnalyzer.h.
Referenced by runWithEojul(), setDefault(), and setOption().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/kma/MAnalyzer.h
/disk/workspace-cpp/la-manager/source/kma/MAnalyzer.cpp