StringEx Class Reference
#include <stringex.h>
Public Member Functions
StringEx ()
StringEx (size_t sizebuf)
StringEx (const char *str)
StringEx (const StringEx &strex)
StringEx (char *str, size_t sizebuf)
StringEx (const StringEx &strex, size_t sizebuf)
StringEx (const StringEx &strex1, const StringEx &strex2)
StringEx (char *str, const StringEx &strex)
StringEx (const StringEx &strex, char *str)
StringEx (char *str1, char *str2)
StringEx (const string &str)
~StringEx ()
char * getBuffer (size_t pos=0) const
size_t getLength () const
char * buffer (size_t pos=0) const
size_t length () const
size_t getBufferSize () const
size_t bufferSize () const
int setBufferSize (size_t sizebuf)
int setLength (size_t len)
const StringEx & operator= (const char *str)
const StringEx & operator= (const StringEx &strex)
const StringEx & operator= (const char c)
bool isStrEqual (const StringEx &strex1, const StringEx &strex2)
bool isStrEqual (const StringEx &strex1, const char *str)
const char & operator[] (size_t offset) const
char & operator[] (size_t offset)
StringEx operator+ (const char *str) const
StringEx operator+ (const StringEx &strex) const
void operator+= (const StringEx &strex)
void operator+= (const char *str)
int startWith (char *str) const
int startWith (StringEx &strex) const
int endWith (char *str) const
int endWith (StringEx &strex) const
int getNumberOfStr (char *str)
int getNumberOfChar (char ch)
int getIndex (char ch)
int getIndex (char *str)
int getIndex (const StringEx &strex)
int getIndex (size_t spos, char ch)
int getIndex (size_t spos, char *str)
int getIndex (size_t spos, const StringEx &strex)
int getIndex2 (size_t spos, char *chs)
int getIndexEnd (char ch)
int getIndexEnd (char *str)
int getIndexEnd (const StringEx &strex)
int getIndexEnd (size_t spos, char ch)
int getIndexEnd (size_t spos, char *str)
int getIndexEnd (size_t spos, const StringEx &strex)
int isPartiallyEqual (char *pstr)
StringEx getSubString (size_t posA, size_t posB) const
StringEx getSubString (size_t posA) const
void setSubString (char *str, size_t nCount)
int divideString (StringEx &frontend, StringEx &backend, char delimiter)
int divideString (StringEx &frontend, StringEx &backend, char *delimiter)
int divideStringbyOneOfChars (StringEx &frontend, StringEx &backend, char *delimiters)
int divideString2 (StringEx &frontend, StringEx &backend, char *delimiters)
void trimLeft ()
void trimLeft (char ch)
void trimRight ()
void trimRight (char ch)
void trim ()
void trim (char ch)
int replaceString (char *targetstr, char *str)
int replaceCharOneOfChars (char *targetchars, char ch)
int replaceStringFromAToB (char *A, char *B, char *str, int isIncluded)
StringEx getStringBetweenAnB (char *A, char *B, int isIncluded)
void toLowerCase ()
void toUpperCase ()
StringEx getValue (char *attr, char *delimiter)
void initialize ()
void empty ()
int isEmpty () const
int bitOR (size_t pos, unsigned char operand)
int bitAND (size_t pos, unsigned char operand)
Friends
StringEx operator+ (const char *str, const StringEx &strex1)
bool operator> (const StringEx &strex1, const StringEx &strex2)
bool operator< (const StringEx &strex1, const StringEx &strex2)
bool operator> (const StringEx &strex1, const char *str)
bool operator< (const StringEx &strex1, const char *str)
bool operator== (const StringEx &strex1, const StringEx &strex2)
bool operator== (const StringEx &strex1, const char *str)
bool operator!= (const StringEx &strex1, const StringEx &strex2)
bool operator!= (const StringEx &strex1, const char *str)
ostream & operator<< (ostream &sout, const StringEx &strex)
Detailed Description
Definition at line 11 of file stringex.h.
Constructor & Destructor Documentation
StringEx::StringEx () [inline]
Definition at line 15 of file stringex.h.
Referenced by Text::operator+().
StringEx::StringEx (size_t sizebuf) [inline]
Definition at line 19 of file stringex.h.
StringEx::StringEx (const char * str) [inline]
Definition at line 24 of file stringex.h.
StringEx::StringEx (const StringEx & strex) [inline]
Definition at line 28 of file stringex.h.
StringEx::StringEx (char * str, size_t sizebuf) [inline]
Definition at line 32 of file stringex.h.
StringEx::StringEx (const StringEx & strex, size_t sizebuf) [inline]
Definition at line 37 of file stringex.h.
StringEx::StringEx (const StringEx & strex1, const StringEx & strex2) [inline]
Definition at line 42 of file stringex.h.
StringEx::StringEx (char * str, const StringEx & strex) [inline]
Definition at line 47 of file stringex.h.
StringEx::StringEx (const StringEx & strex, char * str) [inline]
Definition at line 52 of file stringex.h.
StringEx::StringEx (char * str1, char * str2) [inline]
Definition at line 57 of file stringex.h.
StringEx::StringEx (const string & str) [inline]
Definition at line 62 of file stringex.h.
StringEx::~StringEx () [inline]
Definition at line 66 of file stringex.h.
Member Function Documentation
int StringEx::bitAND (size_t pos, unsigned char operand) [inline]
Definition at line 773 of file stringex.h.
int StringEx::bitOR (size_t pos, unsigned char operand) [inline]
Definition at line 764 of file stringex.h.
char* StringEx::buffer (size_t pos = 0) const [inline]
Definition at line 80 of file stringex.h.
Referenced by kmaOrange::MAnalyzer::analyzeDigitAlphabetWord(), kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::analyzeEojul_NNR(), kmaOrange::MAnalyzer::analyzeHeadTail(), kmaOrange::MAnalyzer::analyzeSubHangulWordforFL(), kmaOrange::MAnalyzer::analyzeSubHangulWordforSN(), kmaOrange::MAnalyzer::canBeVE(), kmaOrange::MAnalyzer::checkNanalyzeContraction_CHEE(), kmaOrange::MAnalyzer::checkNanalyzeContraction_KEE(), kmaOrange::MAnalyzer::checkNanalyzeContraction_KEH(), kmaOrange::MAnalyzer::checkNanalyzeContraction_WAE(), kmaOrange::MAnalyzer::checkNanalyzeContraction_WAHWOH(), kmaOrange::MAnalyzer::checkNanalyzeContraction_YUR(), kmaOrange::MAnalyzer::checkNanalyzeElision_hlL(), kmaOrange::MAnalyzer::checkNanalyzeElision_HOMOPHONE(), kmaOrange::MAnalyzer::checkNanalyzeElision_OO(), kmaOrange::MAnalyzer::checkNanalyzeElision_UH(), kmaOrange::MAnalyzer::checkNanalyzeElision_UR(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_BIUP(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_DIGT(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_HIUNG(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_RUH(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_RUR(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_SIOT(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_UR(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_YUR(), kmaOrange::MAnalyzer::checkNanalyzeN_(), kmaOrange::MAnalyzer::checkNanalyzePreEomi(), kmaOrange::MAnalyzer::checkNanalyzeV_(), kmaOrange::MAnalyzer::checkNanalyzeXSDecliable(), kmaOrange::SynonymContainer::insertSynonym(), kmaOrange::Dictionary::loadKnowledge(), kmaOrange::Dictionary::loadPreAnalysis(), kmaOrange::StopWordContainer::loadStopWord(), kmaOrange::SynonymContainer::loadSynonym(), kmaOrange::Dictionary::makeKnowledge(), kmaOrange::Dictionary::makeMainTrieInfo(), Text::operator+=(), operator=(), Text::operator[](), kmaOrange::DecomposeNNP::postProcessDcInfo(), kmaOrange::Dictionary::readCommonDictionary(), kmaOrange::Dictionary::readDivideInfo(), kmaOrange::Dictionary::readJosaEomiDictionary(), kmaOrange::Dictionary::readPostionInfo(), kmaOrange::DecomposeNNP::searchAllRegisteredN_(), kmaOrange::AuxVerb::searchNgetInfoFromAvTrie(), kmaOrange::Dictionary::searchNgetInfoFromDivTrie(), kmaOrange::PreFinalEomi::searchNgetInfoFromEpTrie(), kmaOrange::Dictionary::searchNgetInfoFromJosaEomiTrie(), kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Dictionary::searchNgetInfoFromPosTrie(), kmaOrange::Dictionary::searchNgetInfoFromPreAnalTrie(), and kmaOrange::PredicativeSuffix::searchNgetInfoFromXsdTrie().
size_t StringEx::bufferSize () const [inline]
Definition at line 95 of file stringex.h.
int StringEx::divideString (StringEx & frontend, StringEx & backend, char * delimiter) [inline]
Definition at line 432 of file stringex.h.
References getIndex(), and getSubString().
int StringEx::divideString (StringEx & frontend, StringEx & backend, char delimiter) [inline]
Definition at line 414 of file stringex.h.
References getIndex(), and getSubString().
int StringEx::divideString2 (StringEx & frontend, StringEx & backend, char * delimiters) [inline]
Definition at line 468 of file stringex.h.
References getIndex2(), and getSubString().
int StringEx::divideStringbyOneOfChars (StringEx & frontend, StringEx & backend, char * delimiters) [inline]
Definition at line 450 of file stringex.h.
References getIndex2(), and getSubString().
void StringEx::empty () [inline]
Definition at line 749 of file stringex.h.
Referenced by kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_BIUP(), and kmaOrange::MAnalyzer::checkNanalyzePreEomi().
int StringEx::endWith (StringEx & strex) const [inline]
Definition at line 224 of file stringex.h.
References length().
int StringEx::endWith (char * str) const [inline]
Definition at line 217 of file stringex.h.
Referenced by kmaOrange::MAnalyzer::checkNanalyzeCopular(), kmaOrange::MAnalyzer::checkNanalyzePreEomi(), kmaOrange::DecomposeNNP::getDecomposedInformation(), kmaOrange::Dictionary::loadPreAnalysis(), kmaOrange::StopWordContainer::loadStopWord(), kmaOrange::SynonymContainer::loadSynonym(), and kmaOrange::Dictionary::loadUserNoun().
char* StringEx::getBuffer (size_t pos = 0) const [inline]
Definition at line 70 of file stringex.h.
Referenced by kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NJ(), kmaOrange::MAnalyzer::analyzeSimpleWord(), kmaOrange::MAnalyzer::analyzeSubHangulWordforSN(), kmaOrange::MAnalyzer::checkNanalyzeN_(), kmaOrange::DecomposeNNP::generateCandidates(), kmaOrange::DecomposeNNP::getDecomposedInformation(), kmaOrange::DecomposeNNP::getQueryCandidates(), operator+(), Text::operator+(), operator<<(), Text::operator=(), kmaOrange::DecomposeNNP::postProcessDcInfo(), kmaOrange::DecomposeNNP::scoringPattern(), kmaOrange::StrStream::setInStream(), kmaOrange::StrStream::setOutStream(), and Text::Text().
size_t StringEx::getBufferSize () const [inline]
Definition at line 90 of file stringex.h.
Referenced by kmaOrange::StrStream::getLine().
int StringEx::getIndex (size_t spos, const StringEx & strex) [inline]
Definition at line 306 of file stringex.h.
int StringEx::getIndex (size_t spos, char * str) [inline]
Definition at line 298 of file stringex.h.
int StringEx::getIndex (size_t spos, char ch) [inline]
Definition at line 290 of file stringex.h.
int StringEx::getIndex (const StringEx & strex) [inline]
Definition at line 282 of file stringex.h.
int StringEx::getIndex (char * str) [inline]
Definition at line 274 of file stringex.h.
int StringEx::getIndex (char ch) [inline]
Definition at line 266 of file stringex.h.
Referenced by kmaOrange::MAnalyzer::analyzeDigitAlphabetWord(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NJ(), kmaOrange::MAnalyzer::analyzeEojul_NNR(), divideString(), Text::divideStrings(), kmaOrange::DecomposeNNP::generateCandidates(), kmaOrange::DecomposeNNP::getDecomposedInformation(), kmaOrange::DecomposeNNP::getQueryCandidates(), Text::getStringBetweenAnB(), getStringBetweenAnB(), getValue(), kmaOrange::Dictionary::loadPreAnalysis(), kmaOrange::SynonymContainer::loadSynonym(), kmaOrange::DecomposeNNP::postProcessDcInfo(), kmaOrange::Dictionary::readJosaEomiDictionary(), replaceString(), replaceStringFromAToB(), kmaOrange::Eojul::setString(), and kmaOrange::MAnalyzer::tokenizeSentence().
int StringEx::getIndex2 (size_t spos, char * chs) [inline]
Definition at line 314 of file stringex.h.
Referenced by divideString2(), divideStringbyOneOfChars(), Text::divideStrings2(), and replaceCharOneOfChars().
int StringEx::getIndexEnd (size_t spos, const StringEx & strex) [inline]
Definition at line 362 of file stringex.h.
int StringEx::getIndexEnd (size_t spos, char * str) [inline]
Definition at line 354 of file stringex.h.
int StringEx::getIndexEnd (size_t spos, char ch) [inline]
Definition at line 346 of file stringex.h.
int StringEx::getIndexEnd (const StringEx & strex) [inline]
Definition at line 338 of file stringex.h.
int StringEx::getIndexEnd (char * str) [inline]
Definition at line 330 of file stringex.h.
int StringEx::getIndexEnd (char ch) [inline]
Definition at line 322 of file stringex.h.
size_t StringEx::getLength () const [inline]
Definition at line 75 of file stringex.h.
References length().
Referenced by Text::divideStrings(), Text::divideStrings2(), kmaOrange::DecomposeNNP::getQueryCandidates(), and kmaOrange::DecomposeNNP::getSyllableLength().
int StringEx::getNumberOfChar (char ch) [inline]
Definition at line 250 of file stringex.h.
Referenced by kmaOrange::MAnalyzer::analyzeEojul_NNR(), kmaOrange::DecomposeNNP::getDecomposedInformation(), and kmaOrange::DecomposeNNP::postProcessDcInfo().
int StringEx::getNumberOfStr (char * str) [inline]
Definition at line 231 of file stringex.h.
Referenced by kmaOrange::DecomposeNNP::postProcessDcInfo().
StringEx StringEx::getStringBetweenAnB (char * A, char * B, int isIncluded) [inline]
Reimplemented in Text.
Definition at line 657 of file stringex.h.
References getIndex(), and getSubString().
StringEx StringEx::getSubString (size_t posA) const [inline]
Definition at line 393 of file stringex.h.
References length().
StringEx StringEx::getSubString (size_t posA, size_t posB) const [inline]
Definition at line 377 of file stringex.h.
References length().
Referenced by kmaOrange::MAnalyzer::analyzeDigitAlphabetWord(), kmaOrange::MAnalyzer::analyzeEojul_NNR(), kmaOrange::MAnalyzer::checkNanalyzeContraction_YUR(), kmaOrange::MAnalyzer::checkNanalyzePreEomi(), kmaOrange::MAnalyzer::checkNanalyzeXSDecliable(), kmaOrange::DecomposeNNP::decomposing(), divideString(), divideString2(), divideStringbyOneOfChars(), Text::divideStrings(), Text::divideStrings2(), kmaOrange::DecomposeNNP::generateCandidates(), kmaOrange::DecomposeNNP::generateSimpleWord(), kmaOrange::DecomposeNNP::getQueryCandidates(), Text::getStringBetweenAnB(), getStringBetweenAnB(), kmaOrange::Dictionary::loadPreAnalysis(), kmaOrange::DecomposeNNP::postProcessDcInfo(), kmaOrange::DecomposeNNP::printDivPattern(), kmaOrange::Dictionary::readJosaEomiDictionary(), and kmaOrange::DecomposeNNP::scoringPattern().
StringEx StringEx::getValue (char * attr, char * delimiter) [inline]
Definition at line 706 of file stringex.h.
References getIndex().
void StringEx::initialize () [inline]
Definition at line 740 of file stringex.h.
int StringEx::isEmpty () const [inline]
Definition at line 758 of file stringex.h.
Referenced by kmaOrange::MAnalyzer::commonRunWithStream(), kmaOrange::DecomposeNNP::getDecomposedInformation(), kmaOrange::Dictionary::makeMainTrieInfo(), Text::operator+=(), kmaOrange::Dictionary::readCommonDictionary(), kmaOrange::MAnalyzer::runWithString(), trimLeft(), and trimRight().
int StringEx::isPartiallyEqual (char * pstr) [inline]
Definition at line 370 of file stringex.h.
bool StringEx::isStrEqual (const StringEx & strex1, const char * str) [inline]
Definition at line 147 of file stringex.h.
bool StringEx::isStrEqual (const StringEx & strex1, const StringEx & strex2) [inline]
Definition at line 141 of file stringex.h.
size_t StringEx::length () const [inline]
Definition at line 85 of file stringex.h.
Referenced by kmaOrange::DecomposeNNP::addNNP(), kmaOrange::MAnalyzer::analyzeDigitAlphabetWord(), kmaOrange::MAnalyzer::analyzeEojul_NNR(), kmaOrange::MAnalyzer::analyzeSimpleWord(), kmaOrange::MAnalyzer::analyzeSubHangulWordforFL(), kmaOrange::MAnalyzer::analyzeSubHangulWordforSN(), kmaOrange::MAnalyzer::checkNanalyzeCopular(), kmaOrange::MAnalyzer::checkNanalyzeElision_hlL(), kmaOrange::MAnalyzer::checkNanalyzeElision_UH(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_BIUP(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_YUR(), kmaOrange::MAnalyzer::checkNanalyzeN_(), kmaOrange::MAnalyzer::checkNanalyzePreEomi(), kmaOrange::MAnalyzer::checkNanalyzeXSDecliable(), endWith(), kmaOrange::DecomposeNNP::getDecomposedInformation(), getLength(), kmaOrange::DecomposeNNP::getQueryCandidates(), getSubString(), kmaOrange::MAnalyzer::isAlphabet(), kmaOrange::MAnalyzer::isDigit(), kmaOrange::Eojul::isDigit(), kmaOrange::SynonymContainer::loadSynonym(), kmaOrange::Dictionary::makeMainTrieInfo(), Text::operator[](), kmaOrange::DecomposeNNP::postProcessDcInfo(), kmaOrange::Dictionary::readPostionInfo(), kmaOrange::AuxVerb::searchNgetInfoFromAvTrie(), kmaOrange::Dictionary::searchNgetInfoFromDivTrie(), kmaOrange::PreFinalEomi::searchNgetInfoFromEpTrie(), kmaOrange::Dictionary::searchNgetInfoFromJosaEomiTrie(), kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Dictionary::searchNgetInfoFromPosTrie(), kmaOrange::Dictionary::searchNgetInfoFromPreAnalTrie(), kmaOrange::PredicativeSuffix::searchNgetInfoFromXsdTrie(), startWith(), kmaOrange::MAnalyzer::tokenizeSentence(), and trimLeft().
StringEx StringEx::operator+ (const StringEx & strex) const [inline]
Definition at line 170 of file stringex.h.
StringEx StringEx::operator+ (const char * str) const [inline]
Definition at line 163 of file stringex.h.
void StringEx::operator+= (const char * str) [inline]
Definition at line 189 of file stringex.h.
void StringEx::operator+= (const StringEx & strex) [inline]
Reimplemented in Text.
Definition at line 184 of file stringex.h.
const StringEx& StringEx::operator= (const char c) [inline]
Definition at line 130 of file stringex.h.
const StringEx& StringEx::operator= (const StringEx & strex) [inline]
Reimplemented in Text.
Definition at line 123 of file stringex.h.
References buffer().
const StringEx& StringEx::operator= (const char * str) [inline]
Definition at line 115 of file stringex.h.
char& StringEx::operator[] (size_t offset) [inline]
Reimplemented in Text.
Definition at line 158 of file stringex.h.
const char& StringEx::operator[] (size_t offset) const [inline]
Reimplemented in Text.
Definition at line 153 of file stringex.h.
int StringEx::replaceCharOneOfChars (char * targetchars, char ch) [inline]
Definition at line 601 of file stringex.h.
References getIndex2().
int StringEx::replaceString (char * targetstr, char * str) [inline]
Definition at line 578 of file stringex.h.
References getIndex(), and replace().
Referenced by kmaOrange::SynonymContainer::insertSynonym(), kmaOrange::SynonymContainer::loadSynonym(), kmaOrange::DecomposeNNP::postProcessDcInfo(), and kmaOrange::Logger::SetMessage().
int StringEx::replaceStringFromAToB (char * A, char * B, char * str, int isIncluded) [inline]
Definition at line 621 of file stringex.h.
References getIndex(), and replace().
int StringEx::setBufferSize (size_t sizebuf) [inline]
Definition at line 100 of file stringex.h.
Referenced by kmaOrange::StrStream::getLine(), kmaOrange::Dictionary::readDivideInfo(), kmaOrange::Dictionary::readPostionInfo(), and kmaOrange::MAnalyzer::setDefault().
int StringEx::setLength (size_t len) [inline]
Definition at line 107 of file stringex.h.
Referenced by kmaOrange::StrStream::getLine().
void StringEx::setSubString (char * str, size_t nCount) [inline]
Definition at line 409 of file stringex.h.
Referenced by kmaOrange::MAnalyzer::analyzeHeadTail(), and kmaOrange::MAnalyzer::checkNanalyzeCopular().
int StringEx::startWith (StringEx & strex) const [inline]
Definition at line 210 of file stringex.h.
References length().
int StringEx::startWith (char * str) const [inline]
Definition at line 203 of file stringex.h.
Referenced by kmaOrange::Dictionary::loadPreAnalysis(), kmaOrange::StopWordContainer::loadStopWord(), kmaOrange::SynonymContainer::loadSynonym(), kmaOrange::Dictionary::readCommonDictionary(), and kmaOrange::Dictionary::readJosaEomiDictionary().
void StringEx::toLowerCase () [inline]
Definition at line 686 of file stringex.h.
Referenced by kmaOrange::SynonymContainer::loadSynonym().
void StringEx::toUpperCase () [inline]
Definition at line 696 of file stringex.h.
void StringEx::trim (char ch) [inline]
Definition at line 572 of file stringex.h.
References trimLeft(), and trimRight().
void StringEx::trim () [inline]
Definition at line 566 of file stringex.h.
References trimLeft(), and trimRight().
Referenced by kmaOrange::Dictionary::makeMainTrieInfo(), and kmaOrange::Dictionary::readCommonDictionary().
void StringEx::trimLeft (char ch) [inline]
Definition at line 506 of file stringex.h.
References isEmpty(), and length().
void StringEx::trimLeft () [inline]
Definition at line 486 of file stringex.h.
References isEmpty(), and length().
Referenced by kmaOrange::Dictionary::readCommonDictionary(), and trim().
void StringEx::trimRight (char ch) [inline]
Definition at line 546 of file stringex.h.
References isEmpty().
void StringEx::trimRight () [inline]
Definition at line 526 of file stringex.h.
References isEmpty().
Referenced by kmaOrange::Dictionary::loadPreAnalysis(), kmaOrange::StopWordContainer::loadStopWord(), kmaOrange::SynonymContainer::loadSynonym(), and trim().
Friends And Related Function Documentation
bool operator!= (const StringEx & strex1, const char * str) [friend]
Definition at line 62 of file stringex.cpp.
bool operator!= (const StringEx & strex1, const StringEx & strex2) [friend]
Definition at line 55 of file stringex.cpp.
StringEx operator+ (const char * str, const StringEx & strex1) [friend]
Definition at line 76 of file stringex.cpp.
bool operator< (const StringEx & strex1, const char * str) [friend]
Definition at line 34 of file stringex.cpp.
bool operator< (const StringEx & strex1, const StringEx & strex2) [friend]
Definition at line 20 of file stringex.cpp.
ostream& operator<< (ostream & sout, const StringEx & strex) [friend]
Definition at line 69 of file stringex.cpp.
bool operator== (const StringEx & strex1, const char * str) [friend]
Definition at line 48 of file stringex.cpp.
bool operator== (const StringEx & strex1, const StringEx & strex2) [friend]
Definition at line 41 of file stringex.cpp.
bool operator> (const StringEx & strex1, const char * str) [friend]
Definition at line 27 of file stringex.cpp.
bool operator> (const StringEx & strex1, const StringEx & strex2) [friend]
Definition at line 13 of file stringex.cpp.
The documentation for this class was generated from the following file:
/disk/workspace-cpp/la-manager/include/kma/stringex.h