Text Class Reference
#include <stringex.h>
Public Member Functions
StringEx getStringBetweenAnB (int pos, char *A, char *B, int isIncluded)
StringEx getStringBetweenAnB (char *A, char *B, int isIncluded)
void getStringsBetweenAnBs (char *A, char *B, int isIncluded)
void divideStrings (char *delimiter)
void divideStrings (char delimiter)
void divideStrings2 (char *delimiters)
char * strChrs (char *pspos, char *delimiters)
void divideStringsPtr (char *delimiter)
void divideStringsPtr (char delimiter)
void divideStrings2Ptr (char *delimiters)
StringEx * getStringExs () const
char ** getPStr () const
int getCount () const
int getStatus () const
int getPos () const
const Text & operator= (const Text &text)
const Text & operator= (const StringEx &strex)
const Text & operator= (char *str)
Text (const Text &text)
Text (const StringEx &strex)
Text (char *str)
Text (size_t sizebuf)
Text ()
~Text ()
char & operator[] (size_t offset)
char operator[] (size_t offset) const
void operator+= (const Text &text)
void operator+= (const StringEx &strex1)
void operator+= (char *str)
Text operator+ (const Text &text)
Text operator+ (const StringEx &strex1)
Text operator+ (char *str)
Private Attributes
StringEx * m_pstrex
char ** m_pstr
size_t m_num
int m_status
int m_pos
Friends
Text operator+ (char *str, Text &text)
Text operator+ (const StringEx *strex, const Text &text)
ostream & operator<< (ostream &sout, const Text &text)
Detailed Description
Definition at line 796 of file stringex.h.
Constructor & Destructor Documentation
Text::Text (const Text & text)
Definition at line 117 of file stringex.cpp.
References StringEx::getBuffer(), getCount(), getPos(), getStringExs(), m_num, m_pos, m_pstr, m_pstrex, m_status, and operator=().
Text::Text (const StringEx & strex)
Definition at line 110 of file stringex.cpp.
References m_num, m_pos, m_pstr, m_pstrex, and m_status.
Text::Text (char * str)
Definition at line 103 of file stringex.cpp.
References m_num, m_pos, m_pstr, m_pstrex, and m_status.
Text::Text (size_t sizebuf)
Definition at line 96 of file stringex.cpp.
References m_num, m_pos, m_pstr, m_pstrex, and m_status.
Text::Text ()
Definition at line 89 of file stringex.cpp.
References m_num, m_pos, m_pstr, m_pstrex, and m_status.
Referenced by operator+().
Text::~Text ()
Definition at line 138 of file stringex.cpp.
References m_pstr, and m_pstrex.
Member Function Documentation
void Text::divideStrings (char delimiter)
Definition at line 307 of file stringex.cpp.
References StringEx::getIndex(), StringEx::getLength(), StringEx::getSubString(), m_num, m_pstrex, and m_status.
void Text::divideStrings (char * delimiter)
Definition at line 356 of file stringex.cpp.
References StringEx::getIndex(), StringEx::getLength(), StringEx::getSubString(), m_num, m_pstrex, and m_status.
void Text::divideStrings2 (char * delimiters)
Definition at line 406 of file stringex.cpp.
References StringEx::getIndex2(), StringEx::getLength(), StringEx::getSubString(), m_num, m_pstrex, and m_status.
void Text::divideStrings2Ptr (char * delimiters)
Definition at line 567 of file stringex.cpp.
References DEFAULT_divide_MAX, m_num, m_pstr, m_status, and strChrs().
void Text::divideStringsPtr (char delimiter)
Definition at line 462 of file stringex.cpp.
References DEFAULT_divide_MAX, m_num, m_pstr, and m_status.
void Text::divideStringsPtr (char * delimiter)
Definition at line 507 of file stringex.cpp.
References DEFAULT_divide_MAX, m_num, m_pstr, and m_status.
Referenced by kmaOrange::Dictionary::loadPreAnalysis(), and kmaOrange::Dictionary::readJosaEomiDictionary().
int Text::getCount () const
Definition at line 730 of file stringex.cpp.
References m_num.
Referenced by kmaOrange::Dictionary::loadPreAnalysis(), operator=(), kmaOrange::Dictionary::readJosaEomiDictionary(), and Text().
int Text::getPos () const
Definition at line 740 of file stringex.cpp.
References m_pos.
Referenced by operator=(), and Text().
char** Text::getPStr () const [inline]
Definition at line 814 of file stringex.h.
References m_pstr.
Referenced by kmaOrange::Dictionary::loadPreAnalysis(), and kmaOrange::Dictionary::readJosaEomiDictionary().
int Text::getStatus () const
Definition at line 735 of file stringex.cpp.
References m_status.
StringEx Text::getStringBetweenAnB (char * A, char * B, int isIncluded)
Reimplemented from StringEx.
Definition at line 612 of file stringex.cpp.
References StringEx::getIndex(), StringEx::getSubString(), m_pos, and m_status.
StringEx Text::getStringBetweenAnB (int pos, char * A, char * B, int isIncluded)
Definition at line 650 of file stringex.cpp.
References StringEx::getIndex(), StringEx::getSubString(), m_pos, and m_status.
Referenced by getStringsBetweenAnBs().
StringEx * Text::getStringExs () const
Definition at line 745 of file stringex.cpp.
References m_pstrex.
Referenced by operator=(), and Text().
void Text::getStringsBetweenAnBs (char * A, char * B, int isIncluded)
Definition at line 690 of file stringex.cpp.
References getStringBetweenAnB(), GROWINGSIZE, m_num, m_pos, m_pstrex, and m_status.
Text Text::operator+ (char * str)
Definition at line 259 of file stringex.cpp.
References StringEx::getBuffer(), StringEx::StringEx(), and Text().
Text Text::operator+ (const StringEx & strex1)
Definition at line 266 of file stringex.cpp.
References StringEx::getBuffer(), and Text().
Text Text::operator+ (const Text & text)
Definition at line 273 of file stringex.cpp.
References StringEx::getBuffer(), and Text().
void Text::operator+= (char * str)
Definition at line 250 of file stringex.cpp.
References StringEx::buffer().
void Text::operator+= (const StringEx & strex1)
Reimplemented from StringEx.
Definition at line 241 of file stringex.cpp.
References StringEx::buffer(), and StringEx::isEmpty().
void Text::operator+= (const Text & text)
Definition at line 232 of file stringex.cpp.
References StringEx::buffer(), and StringEx::isEmpty().
const Text & Text::operator= (char * str)
Definition at line 144 of file stringex.cpp.
References m_num, m_pos, m_pstr, m_pstrex, and operator=().
const Text & Text::operator= (const StringEx & strex)
Reimplemented from StringEx.
Definition at line 161 of file stringex.cpp.
References m_num, m_pos, m_pstr, m_pstrex, and operator=().
const Text & Text::operator= (const Text & text)
Definition at line 178 of file stringex.cpp.
References StringEx::getBuffer(), getCount(), getPos(), getStringExs(), m_num, m_pos, m_pstr, and m_pstrex.
Referenced by operator=(), and Text().
char Text::operator[] (size_t offset) const
Reimplemented from StringEx.
Definition at line 223 of file stringex.cpp.
References StringEx::buffer(), and StringEx::length().
char & Text::operator[] (size_t offset)
Reimplemented from StringEx.
Definition at line 214 of file stringex.cpp.
References StringEx::buffer(), and StringEx::length().
char * Text::strChrs (char * pspos, char * delimiters)
Definition at line 553 of file stringex.cpp.
Referenced by divideStrings2Ptr().
Friends And Related Function Documentation
Text operator+ (const StringEx * strex, const Text & text) [friend]
Text operator+ (char * str, Text & text) [friend]
ostream& operator<< (ostream & sout, const Text & text) [friend]
Definition at line 208 of file stringex.cpp.
Member Data Documentation
size_t Text::m_num [private]
Definition at line 847 of file stringex.h.
Referenced by divideStrings(), divideStrings2(), divideStrings2Ptr(), divideStringsPtr(), getCount(), getStringsBetweenAnBs(), operator=(), and Text().
int Text::m_pos [private]
Definition at line 849 of file stringex.h.
Referenced by getPos(), getStringBetweenAnB(), getStringsBetweenAnBs(), operator=(), and Text().
char** Text::m_pstr [private]
Definition at line 846 of file stringex.h.
Referenced by divideStrings2Ptr(), divideStringsPtr(), getPStr(), operator=(), Text(), and ~Text().
StringEx* Text::m_pstrex [private]
Definition at line 845 of file stringex.h.
Referenced by divideStrings(), divideStrings2(), getStringExs(), getStringsBetweenAnBs(), operator=(), Text(), and ~Text().
int Text::m_status [private]
Definition at line 848 of file stringex.h.
Referenced by divideStrings(), divideStrings2(), divideStrings2Ptr(), divideStringsPtr(), getStatus(), getStringBetweenAnB(), getStringsBetweenAnBs(), and Text().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/kma/stringex.h
/disk/workspace-cpp/la-manager/source/kma/stringex.cpp