la_manager::CharTypeTable Class Reference
class of char type table This class record the char type table for tokenizer to look up
#include <Tokenizer.h>
Public Member Functions
CharTypeTable ()
void setConfig (const TokenizeConfig &conf)
change the char type table according to user's defined option list
void setDefinedType (UCS2Char c, const CharType dtype)
set the defined type for specific char
void setDefaultType (UCS2Char c, const CharType dtype)
set the default type for specific char
CharType getDefinedType (UCS2Char c)
get the defined type for specific char
CharType getDefaultType (UCS2Char c)
get the default type for specific char
bool isDefaultAllow (UCS2Char c)
check whether default allow
bool isDefaultDivide (UCS2Char c)
check whether default divide
bool isDefinedAllow (UCS2Char c)
check whether defined allow
bool isDefinedDivide (UCS2Char c)
check whether defined divide
bool isDefinedUnite (UCS2Char c)
check whether defined unit
bool isDefaultEqual (UCS2Char c1, UCS2Char c2)
check whether two chars has the same default type
bool isDefinedEqual (UCS2Char c1, UCS2Char c2)
check whether two chars has the same defined type
Static Public Attributes
static const CharType DEFAULT_ALLOW = 0x00
`xxxx 0000` use the lower 4 bit to encode default char type: char allow is to be indexed, e.g. 'A' and 'B' in `A#B`
static const CharType DEFAULT_DIVIDE = 0x01
`xxxx 0001` delimiter character that should removed and divide the string. e.g. '#' in `A#B` if we set `#` to be `divide`, and the result terms are `A`, `B`
static const CharType DEFINED_ALLOW = 0x00
`0000 xxxx` use the higher 4 bit to encode the regulator option type defined by user
static const CharType DEFINED_DIVIDE = 0x10
`0001 xxxx`
static const CharType DEFINED_UNITE = 0x20
`0010 xxxx` ignored character that should be removed but not divide the string, e.g. if we set `# to be `unite`, the result term will be `AB`
Private Attributes
CharType charTypeTable [TWO_BYPE_MAX]
Detailed Description
class of char type table This class record the char type table for tokenizer to look up
Definition at line 59 of file Tokenizer.h.
Constructor & Destructor Documentation
la_manager::CharTypeTable::CharTypeTable ()
Definition at line 12 of file Tokenizer.cpp.
References charTypeTable, DEFAULT_DIVIDE, DEFINED_DIVIDE, setDefaultType(), setDefinedType(), and la_manager::TWO_BYPE_MAX.
Member Function Documentation
CharType la_manager::CharTypeTable::getDefaultType (UCS2Char c) [inline]
get the default type for specific char
Parameters:
c char
Returns: default type
Definition at line 100 of file Tokenizer.h.
References charTypeTable.
Referenced by isDefaultAllow(), isDefaultDivide(), and isDefaultEqual().
CharType la_manager::CharTypeTable::getDefinedType (UCS2Char c) [inline]
get the defined type for specific char
Parameters:
c char
Returns: defined type
Definition at line 93 of file Tokenizer.h.
References charTypeTable.
Referenced by isDefinedAllow(), isDefinedDivide(), isDefinedEqual(), and isDefinedUnite().
bool la_manager::CharTypeTable::isDefaultAllow (UCS2Char c) [inline]
check whether default allow
Parameters:
c char
Returns: true if so, else false
Definition at line 107 of file Tokenizer.h.
References DEFAULT_ALLOW, and getDefaultType().
bool la_manager::CharTypeTable::isDefaultDivide (UCS2Char c) [inline]
check whether default divide
Parameters:
c char
Returns: true if so, else false
Definition at line 114 of file Tokenizer.h.
References DEFAULT_DIVIDE, and getDefaultType().
Referenced by la_manager::Tokenizer::tokenize().
bool la_manager::CharTypeTable::isDefaultEqual (UCS2Char c1, UCS2Char c2) [inline]
check whether two chars has the same default type
Parameters:
c char
Returns: true if so, else false
Definition at line 142 of file Tokenizer.h.
References getDefaultType().
bool la_manager::CharTypeTable::isDefinedAllow (UCS2Char c) [inline]
check whether defined allow
Parameters:
c char
Returns: true if so, else false
Definition at line 121 of file Tokenizer.h.
References DEFINED_ALLOW, and getDefinedType().
Referenced by la_manager::Tokenizer::setTermType(), and la_manager::Tokenizer::tokenize().
bool la_manager::CharTypeTable::isDefinedDivide (UCS2Char c) [inline]
check whether defined divide
Parameters:
c char
Returns: true if so, else false
Definition at line 128 of file Tokenizer.h.
References DEFINED_DIVIDE, and getDefinedType().
Referenced by la_manager::Tokenizer::tokenize().
bool la_manager::CharTypeTable::isDefinedEqual (UCS2Char c1, UCS2Char c2) [inline]
check whether two chars has the same defined type
Parameters:
c char
Returns: true if so, else false
Definition at line 149 of file Tokenizer.h.
References getDefinedType().
bool la_manager::CharTypeTable::isDefinedUnite (UCS2Char c) [inline]
check whether defined unit
Parameters:
c char
Returns: true if so, else false
Definition at line 135 of file Tokenizer.h.
References DEFINED_UNITE, and getDefinedType().
void la_manager::CharTypeTable::setConfig (const TokenizeConfig & conf)
change the char type table according to user's defined option list
Parameters:
list user defined option list
Definition at line 26 of file Tokenizer.cpp.
References la_manager::TokenizeConfig::allows, DEFINED_ALLOW, DEFINED_DIVIDE, DEFINED_UNITE, la_manager::TokenizeConfig::divides, setDefinedType(), and la_manager::TokenizeConfig::unites.
Referenced by la_manager::Tokenizer::setConfig().
void la_manager::CharTypeTable::setDefaultType (UCS2Char c, const CharType dtype) [inline]
set the default type for specific char
Parameters:
c char
dtype type
Definition at line 85 of file Tokenizer.h.
References charTypeTable.
Referenced by CharTypeTable().
void la_manager::CharTypeTable::setDefinedType (UCS2Char c, const CharType dtype) [inline]
set the defined type for specific char
Parameters:
c char
dtype type
Definition at line 77 of file Tokenizer.h.
References charTypeTable.
Referenced by CharTypeTable(), and setConfig().
Member Data Documentation
CharType la_manager::CharTypeTable::charTypeTable[TWO_BYPE_MAX] [private]
Definition at line 60 of file Tokenizer.h.
Referenced by CharTypeTable(), getDefaultType(), getDefinedType(), setDefaultType(), and setDefinedType().
const CharType la_manager::CharTypeTable::DEFAULT_ALLOW = 0x00 [static]
`xxxx 0000` use the lower 4 bit to encode default char type: char allow is to be indexed, e.g. 'A' and 'B' in `A#B`
Definition at line 62 of file Tokenizer.h.
Referenced by isDefaultAllow().
const CharType la_manager::CharTypeTable::DEFAULT_DIVIDE = 0x01 [static]
`xxxx 0001` delimiter character that should removed and divide the string. e.g. '#' in `A#B` if we set `#` to be `divide`, and the result terms are `A`, `B`
Definition at line 63 of file Tokenizer.h.
Referenced by CharTypeTable(), and isDefaultDivide().
const CharType la_manager::CharTypeTable::DEFINED_ALLOW = 0x00 [static]
`0000 xxxx` use the higher 4 bit to encode the regulator option type defined by user
Definition at line 64 of file Tokenizer.h.
Referenced by isDefinedAllow(), and setConfig().
const CharType la_manager::CharTypeTable::DEFINED_DIVIDE = 0x10 [static]
`0001 xxxx`
Definition at line 65 of file Tokenizer.h.
Referenced by CharTypeTable(), isDefinedDivide(), and setConfig().
const CharType la_manager::CharTypeTable::DEFINED_UNITE = 0x20 [static]
`0010 xxxx` ignored character that should be removed but not divide the string, e.g. if we set `# to be `unite`, the result term will be `AB`
Definition at line 66 of file Tokenizer.h.
Referenced by isDefinedUnite(), and setConfig().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/Tokenizer.h
/disk/workspace-cpp/la-manager/source/Tokenizer.cpp