kmaOrange::InfoBuffer Class Reference
This class is stored the string buffer and the information of a searched auxiliary verb, pre-final ending or predicative suffix in a word.
#include <Buffer.h>
Public Member Functions
InfoBuffer (unsigned int sizeBuffer=DEFAULT_BUFFER_BUFFER_SIZE)
This function is a constructor of an InfoBuffer object.
~InfoBuffer (void)
This function is a destructor of Eojul object.
void appendInfo (int pos, int indexInfo)
This function inserts the information about a matched word.
void initialize (bool willBeToTheDefaultState=false)
This function initializes an InfoBuffer object.
void freeBuffer ()
This function frees the allocated memories for an InfoBuffer object.
int doubleBuffer ()
This function enlarges twice the allocated memories for an InfoBuffer object.
unsigned int getBufferPos () const
This function gets the current position of the buffer.
unsigned int getBufferSize () const
This function gets the size of the buffer.
char * getBufferPtr () const
This function gets the starting pointer of the buffer.
char * getInfosPtr () const
This function gets the starting pointer of the information.
unsigned int getSize () const
This function gets the size of the buffer.
unsigned int getPositionByIndex (int index) const
This function gets the buffer of the given index number.
unsigned int getInfoByIndex (int index) const
This function gets the information of the given index number.
Public Attributes
unsigned int _posBuffer
the position of the buffer.
Private Attributes
char * _buffer
the buffer of searched auxiliary verb, pre-final ending or predicative suffix in a word.
char * _infos
the index number list of the information list for auxiliary verb, pre-final ending or predicative suffix.
unsigned int _sizeBuffer
the size of the buffer.
Detailed Description
This class is stored the string buffer and the information of a searched auxiliary verb, pre-final ending or predicative suffix in a word.
Date: 2008-11-14
Author: YoungMin Ahn
Definition at line 24 of file Buffer.h.
Constructor & Destructor Documentation
InfoBuffer::InfoBuffer (unsigned int sizeBuffer = DEFAULT_BUFFER_BUFFER_SIZE)
This function is a constructor of an InfoBuffer object.
Date: 2008-11-14
Author: YoungMin Ahn
Parameters:
sizeBuffer an unsigned integer - the size of a set string in an InfoBuffer object.
Definition at line 26 of file Buffer.cpp.
References _buffer, _infos, _posBuffer, _sizeBuffer, DEFAULT_BUFFER_BUFFER_SIZE, and kmaOrange::Logger::SetMessage().
InfoBuffer::~InfoBuffer (void)
This function is a destructor of Eojul object.
Date: 2008-11-10
Author: YoungMin Ahn
Definition at line 43 of file Buffer.cpp.
References freeBuffer().
Member Function Documentation
void InfoBuffer::appendInfo (int pos, int indexInfo)
This function inserts the information about a matched word.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
pos an integer - the starting position of an auxiliary verb, a pre-final ending or a predicative suffix in a word.
indexInfo an integer - the index number of the information list.
Definition at line 75 of file Buffer.cpp.
References _buffer, _infos, _posBuffer, _sizeBuffer, and doubleBuffer().
Referenced by kmaOrange::AuxVerb::searchNgetInfoFromAvTrie(), kmaOrange::PreFinalEomi::searchNgetInfoFromEpTrie(), and kmaOrange::PredicativeSuffix::searchNgetInfoFromXsdTrie().
int InfoBuffer::doubleBuffer ()
This function enlarges twice the allocated memories for an InfoBuffer object.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: an interger.
Definition at line 88 of file Buffer.cpp.
References _buffer, _infos, _sizeBuffer, and TWICE.
Referenced by appendInfo().
void InfoBuffer::freeBuffer ()
This function frees the allocated memories for an InfoBuffer object.
Date: 2008-11-17
Author: YoungMin Ahn
Definition at line 69 of file Buffer.cpp.
References _buffer, and _infos.
Referenced by initialize(), and ~InfoBuffer().
unsigned int kmaOrange::InfoBuffer::getBufferPos () const [inline]
This function gets the current position of the buffer.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: an unsigned interger.
Definition at line 82 of file Buffer.h.
References _posBuffer.
char* kmaOrange::InfoBuffer::getBufferPtr () const [inline]
This function gets the starting pointer of the buffer.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: a pointer of a character.
Definition at line 98 of file Buffer.h.
References _buffer.
unsigned int kmaOrange::InfoBuffer::getBufferSize () const [inline]
This function gets the size of the buffer.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: an unsigned interger.
Definition at line 90 of file Buffer.h.
References _sizeBuffer.
unsigned int kmaOrange::InfoBuffer::getInfoByIndex (int index) const [inline]
This function gets the information of the given index number.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: an unsigned interger.
Definition at line 130 of file Buffer.h.
References _infos.
Referenced by kmaOrange::MAnalyzer::checkNanalyzeContraction_YUR(), and kmaOrange::MAnalyzer::checkNanalyzeXSDecliable().
char* kmaOrange::InfoBuffer::getInfosPtr () const [inline]
This function gets the starting pointer of the information.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: a pointer of a character.
Definition at line 106 of file Buffer.h.
References _infos.
unsigned int kmaOrange::InfoBuffer::getPositionByIndex (int index) const [inline]
This function gets the buffer of the given index number.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: an unsigned interger.
Definition at line 122 of file Buffer.h.
References _buffer.
Referenced by kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::checkNanalyzeContraction_YUR(), kmaOrange::MAnalyzer::checkNanalyzeElision_hlL(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_HIUNG(), kmaOrange::MAnalyzer::checkNanalyzePreEomi(), kmaOrange::MAnalyzer::checkNanalyzeV_(), and kmaOrange::MAnalyzer::checkNanalyzeXSDecliable().
unsigned int kmaOrange::InfoBuffer::getSize () const [inline]
This function gets the size of the buffer.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: an unsigned interger.
Definition at line 114 of file Buffer.h.
References _posBuffer.
Referenced by kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::checkNanalyzeContraction_YUR(), kmaOrange::MAnalyzer::checkNanalyzeElision_hlL(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_HIUNG(), kmaOrange::MAnalyzer::checkNanalyzePreEomi(), kmaOrange::MAnalyzer::checkNanalyzeV_(), and kmaOrange::MAnalyzer::checkNanalyzeXSDecliable().
void InfoBuffer::initialize (bool willBeToTheDefaultState = false)
This function initializes an InfoBuffer object.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
willBeToTheDefaultState a boolean.
 true - it entirely sets an InfoBuffer object to initial statement.
 false - it only sets values in an InfoBuffer object.
Definition at line 48 of file Buffer.cpp.
References _buffer, _infos, _posBuffer, _sizeBuffer, DEFAULT_BUFFER_BUFFER_SIZE, and freeBuffer().
Referenced by kmaOrange::AuxVerb::searchNgetInfoFromAvTrie(), kmaOrange::PreFinalEomi::searchNgetInfoFromEpTrie(), and kmaOrange::PredicativeSuffix::searchNgetInfoFromXsdTrie().
Member Data Documentation
char* kmaOrange::InfoBuffer::_buffer [private]
the buffer of searched auxiliary verb, pre-final ending or predicative suffix in a word.
Definition at line 135 of file Buffer.h.
Referenced by appendInfo(), doubleBuffer(), freeBuffer(), getBufferPtr(), getPositionByIndex(), InfoBuffer(), and initialize().
char* kmaOrange::InfoBuffer::_infos [private]
the index number list of the information list for auxiliary verb, pre-final ending or predicative suffix.
Definition at line 136 of file Buffer.h.
Referenced by appendInfo(), doubleBuffer(), freeBuffer(), getInfoByIndex(), getInfosPtr(), InfoBuffer(), and initialize().
unsigned int kmaOrange::InfoBuffer::_posBuffer
the position of the buffer.
Definition at line 130 of file Buffer.h.
Referenced by appendInfo(), getBufferPos(), getSize(), InfoBuffer(), initialize(), kmaOrange::AuxVerb::searchNgetInfoFromAvTrie(), kmaOrange::PreFinalEomi::searchNgetInfoFromEpTrie(), and kmaOrange::PredicativeSuffix::searchNgetInfoFromXsdTrie().
unsigned int kmaOrange::InfoBuffer::_sizeBuffer [private]
the size of the buffer.
Definition at line 137 of file Buffer.h.
Referenced by appendInfo(), doubleBuffer(), getBufferSize(), InfoBuffer(), and initialize().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/kma/Buffer.h
/disk/workspace-cpp/la-manager/source/kma/Buffer.cpp