GuessCandidate Class Reference
#include <infoclass.h>
Public Member Functions
GuessCandidate ()
void initialize ()
This function initializes a GuessCandidate object.
void addNJ (unsigned int nPos, JEInfo &jeInfo)
This function adds contents to the _njList.
void addNVC (HeadTailInfo *hti, int depth, unsigned int info)
This function adds contents to the _nvcList.
void addNXSD (HeadTailInfo *hti, int depth, unsigned int info)
This function adds contents to the _nxsdList.
Eojul * getCurrentNXSD ()
This function gets currently added contents to the _nxsdList.
void closeNXSD ()
This function add 1 to the _nxsdCount.
void addAuxVerb (HeadTailInfo *hti, int depth)
This function adds contents to the _avList.
Eojul * getCurrentAV ()
This function gets currently added contents to the _avList.
Eojul * getLastAV ()
This function gets the last contents in the _avList.
void closeAV ()
This function add 1 to the _avCount.
Public Attributes
TailInfo _njList [LIST_MAX]
the list of words, which are able to guess with `noun + postposition`.
Eojul _nvcList [LIST_MAX]
the list of words, which are able to guess with `noun + copula`.
Eojul _nxsdList [LIST_MAX]
the list of words, which are able to guess with `noun + predicative suffix`.
Eojul _avList [LIST_MAX]
the list of words, which are able to guess with `auxiliary verb`.
int _njCount
the number of the word list, which are able to guess with `noun + postposition`.
int _nvcCount
the number of the word list, which are able to guess with `noun + copula`.
int _nxsdCount
the number of the word list, which are able to guess with `noun + predicative suffix`.
int _avCount
the number of the word list, which are able to guess with `auxiliary verb`.
Detailed Description
Definition at line 206 of file infoclass.h.
Constructor & Destructor Documentation
GuessCandidate::GuessCandidate () [inline]
Definition at line 219 of file infoclass.h.
Member Function Documentation
void GuessCandidate::addAuxVerb (HeadTailInfo * hti, int depth) [inline]
This function adds contents to the _avList.
Date: 2008-11-03
Author: YoungMin Ahn
Parameters:
hti the information for haed and tail part of a word.
depth the index of the HeadTailInfo lists.
Definition at line 357 of file infoclass.h.
References _avCount, _avList, kmaOrange::Eojul::close(), kmaOrange::Eojul::increaseAnalysisResults(), LIST_MAX, kmaOrange::Eojul::setEojulAndInfo(), and HeadTailInfo::tagTail.
void GuessCandidate::addNJ (unsigned int nPos, JEInfo & jeInfo) [inline]
This function adds contents to the _njList.
Date: 2008-11-03
Author: YoungMin Ahn
Parameters:
nPos the starting position of a postposition in a word.
jeInfo the information of a grammatical morpheme, which don't have a coda as the first syllable.
Definition at line 248 of file infoclass.h.
References _njCount, _njList, TailInfo::jeInfo, LIST_MAX, and TailInfo::nPos.
Referenced by kmaOrange::MAnalyzer::analyzeHeadTail().
void GuessCandidate::addNVC (HeadTailInfo * hti, int depth, unsigned int info) [inline]
This function adds contents to the _nvcList.
Date: 2008-11-03
Author: YoungMin Ahn
Parameters:
hti the information for haed and tail part of a word.
depth the index of the HeadTailInfo lists.
info the information of contents in a word.
Definition at line 266 of file infoclass.h.
References _nvcCount, _nvcList, kmaOrange::Eojul::append(), kmaOrange::Eojul::close(), EI_AUXVERB, getLastAV(), kmaOrange::Eojul::increaseAnalysisResults(), LIST_MAX, kmaOrange::Eojul::setEojulAndInfo(), and HeadTailInfo::tagTail.
Referenced by kmaOrange::MAnalyzer::checkNanalyzeContraction_YUR(), and kmaOrange::MAnalyzer::checkNanalyzeCopular().
void GuessCandidate::addNXSD (HeadTailInfo * hti, int depth, unsigned int info) [inline]
This function adds contents to the _nxsdList.
Date: 2008-11-03
Author: YoungMin Ahn
Parameters:
hti the information for haed and tail part of a word.
depth the index of the HeadTailInfo lists.
info the information of contents in a word.
Definition at line 298 of file infoclass.h.
References _nxsdCount, _nxsdList, kmaOrange::Eojul::append(), kmaOrange::Eojul::close(), EI_AUXVERB, getLastAV(), kmaOrange::Eojul::increaseAnalysisResults(), LIST_MAX, kmaOrange::Eojul::setEojulAndInfo(), and HeadTailInfo::tagTail.
Referenced by kmaOrange::MAnalyzer::checkNanalyzeContraction_YUR(), and kmaOrange::MAnalyzer::checkNanalyzeXSDecliable().
void GuessCandidate::closeAV () [inline]
This function add 1 to the _avCount.
Date: 2008-11-03
Author: YoungMin Ahn
Definition at line 412 of file infoclass.h.
References _avCount.
Referenced by kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::checkNanalyzeContraction_YUR(), kmaOrange::MAnalyzer::checkNanalyzeElision_hlL(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_HIUNG(), kmaOrange::MAnalyzer::checkNanalyzePreEomi(), kmaOrange::MAnalyzer::checkNanalyzeV_(), and kmaOrange::MAnalyzer::checkNanalyzeXSDecliable().
void GuessCandidate::closeNXSD () [inline]
This function add 1 to the _nxsdCount.
Date: 2008-11-03
Author: YoungMin Ahn
Definition at line 345 of file infoclass.h.
References _nxsdCount.
Referenced by kmaOrange::MAnalyzer::checkNanalyzeContraction_KEE(), and kmaOrange::MAnalyzer::checkNanalyzeContraction_KEH().
Eojul* GuessCandidate::getCurrentAV () [inline]
This function gets currently added contents to the _avList.
Date: 2008-11-03
Author: YoungMin Ahn
Returns: a pointer of Eojul object.
Definition at line 377 of file infoclass.h.
References _avCount, _avList, and LIST_MAX.
Referenced by kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::checkNanalyzeContraction_YUR(), kmaOrange::MAnalyzer::checkNanalyzeElision_hlL(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_HIUNG(), kmaOrange::MAnalyzer::checkNanalyzePreEomi(), kmaOrange::MAnalyzer::checkNanalyzeV_(), and kmaOrange::MAnalyzer::checkNanalyzeXSDecliable().
Eojul* GuessCandidate::getCurrentNXSD () [inline]
This function gets currently added contents to the _nxsdList.
Date: 2008-11-03
Author: YoungMin Ahn
Returns: a pointer of Eojul object.
Definition at line 328 of file infoclass.h.
References _nxsdCount, _nxsdList, and LIST_MAX.
Referenced by kmaOrange::MAnalyzer::checkNanalyzeContraction_KEE(), and kmaOrange::MAnalyzer::checkNanalyzeContraction_KEH().
Eojul* GuessCandidate::getLastAV () [inline]
This function gets the last contents in the _avList.
Date: 2008-11-03
Author: YoungMin Ahn
Returns: a pointer of Eojul object.
Definition at line 395 of file infoclass.h.
References _avCount, and _avList.
Referenced by addNVC(), and addNXSD().
void GuessCandidate::initialize () [inline]
This function initializes a GuessCandidate object.
Date: 2008-11-03
Author: YoungMin Ahn
Definition at line 226 of file infoclass.h.
References _avCount, _avList, _njCount, _nvcCount, _nvcList, _nxsdCount, and _nxsdList.
Referenced by kmaOrange::MAnalyzer::analyzeEojul().
Member Data Documentation
int GuessCandidate::_avCount
the number of the word list, which are able to guess with `auxiliary verb`.
Definition at line 217 of file infoclass.h.
Referenced by addAuxVerb(), kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::analyzeEojul_AuxVerb(), closeAV(), getCurrentAV(), getLastAV(), and initialize().
Eojul GuessCandidate::_avList[LIST_MAX]
the list of words, which are able to guess with `auxiliary verb`.
Definition at line 212 of file infoclass.h.
Referenced by addAuxVerb(), kmaOrange::MAnalyzer::analyzeEojul_AuxVerb(), getCurrentAV(), getLastAV(), and initialize().
int GuessCandidate::_njCount
the number of the word list, which are able to guess with `noun + postposition`.
Definition at line 214 of file infoclass.h.
Referenced by addNJ(), kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::analyzeEojul_Guess(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NJ(), and initialize().
TailInfo GuessCandidate::_njList[LIST_MAX]
the list of words, which are able to guess with `noun + postposition`.
Definition at line 209 of file infoclass.h.
Referenced by addNJ(), kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::analyzeEojul_Guess(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NJ(), and kmaOrange::MAnalyzer::analyzeEojul_NNR().
int GuessCandidate::_nvcCount
the number of the word list, which are able to guess with `noun + copula`.
Definition at line 215 of file infoclass.h.
Referenced by addNVC(), kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::analyzeEojul_Guess(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NJ(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NVC(), kmaOrange::MAnalyzer::checkNanalyzeCopular(), and initialize().
Eojul GuessCandidate::_nvcList[LIST_MAX]
the list of words, which are able to guess with `noun + copula`.
Definition at line 210 of file infoclass.h.
Referenced by addNVC(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NVC(), kmaOrange::MAnalyzer::analyzeEojul_NNR(), and initialize().
int GuessCandidate::_nxsdCount
the number of the word list, which are able to guess with `noun + predicative suffix`.
Definition at line 216 of file infoclass.h.
Referenced by addNXSD(), kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::analyzeEojul_Guess(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NXSD(), closeNXSD(), getCurrentNXSD(), and initialize().
Eojul GuessCandidate::_nxsdList[LIST_MAX]
the list of words, which are able to guess with `noun + predicative suffix`.
Definition at line 211 of file infoclass.h.
Referenced by addNXSD(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NXSD(), kmaOrange::MAnalyzer::analyzeEojul_NNR(), getCurrentNXSD(), and initialize().
The documentation for this class was generated from the following file:
/disk/workspace-cpp/la-manager/include/kma/infoclass.h