/disk/workspace-cpp/la-manager/test/Preprocesser.cpp File Reference
#include <boost/archive/binary_oarchive.hpp>
#include <boost/filesystem/operations.hpp>
#include <boost/filesystem/path.hpp>
#include <boost/progress.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/serialization/map.hpp>
#include <iostream>
#include <fstream>
#include <map>
#include <LAManager.h>
#include <wrapper/TermVector.h>
Functions
bool process_file (string file_path, ostream &out)
bool process_file_stat (string file_path)
int process_fold_stat (string fold, string tar_fold)
int process_fold (string fold, string tar_fold)
void feature_stat ()
void term_selection ()
int process_fold_merge (string fold, string target)
void generate_corpus (string voc_path, string wiki_file, string dir)
void generate_serialized_corpus (string voc_path, string wiki_file, string target)
int main ()
Variables
LAConfiguration laconfig
LAManager LA
TermVector gTermFreq
TermVector gDocFreq
int gcount = 0
Function Documentation
void feature_stat ()
Definition at line 257 of file Preprocesser.cpp.
void generate_corpus (string voc_path, string wiki_file, string dir)
Definition at line 418 of file Preprocesser.cpp.
void generate_serialized_corpus (string voc_path, string wiki_file, string target)
Definition at line 532 of file Preprocesser.cpp.
Referenced by main().
int main ()
Definition at line 608 of file Preprocesser.cpp.
References generate_serialized_corpus().
bool process_file (string file_path, ostream & out)
Definition at line 31 of file Preprocesser.cpp.
References la_manager::LAManager::analyze(), and gcount.
Referenced by process_fold().
bool process_file_stat (string file_path)
Definition at line 86 of file Preprocesser.cpp.
References TermVector::add().
Referenced by process_fold_stat().
int process_fold (string fold, string tar_fold)
Definition at line 193 of file Preprocesser.cpp.
References gcount, and process_file().
int process_fold_merge (string fold, string target)
Definition at line 370 of file Preprocesser.cpp.
int process_fold_stat (string fold, string tar_fold)
Definition at line 131 of file Preprocesser.cpp.
References process_file_stat().
void term_selection ()
Definition at line 297 of file Preprocesser.cpp.
Variable Documentation
int gcount = 0
Definition at line 29 of file Preprocesser.cpp.
Referenced by process_file(), and process_fold().
TermVector gDocFreq
Definition at line 27 of file Preprocesser.cpp.
TermVector gTermFreq
Definition at line 26 of file Preprocesser.cpp.
LAManager LA
Definition at line 24 of file Preprocesser.cpp.
LAConfiguration laconfig
Definition at line 23 of file Preprocesser.cpp.
Referenced by main().