/disk/workspace-cpp/la-manager/include/stem/stem_UTF_8_portuguese.h File Reference
Functions
struct SN_env * portuguese_UTF_8_create_env (void)
void portuguese_UTF_8_close_env (struct SN_env *z)
int portuguese_UTF_8_stem (struct SN_env *z)
Function Documentation
void portuguese_UTF_8_close_env (struct SN_env * z)
Definition at line 1022 of file stem_UTF_8_portuguese.cpp.
References SN_close_env().
struct SN_env * portuguese_UTF_8_create_env (void) [read]
Definition at line 1020 of file stem_UTF_8_portuguese.cpp.
References SN_create_env().
int portuguese_UTF_8_stem (struct SN_env * z)
Definition at line 932 of file stem_UTF_8_portuguese.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), SN_env::ket, SN_env::l, SN_env::lb, r_mark_regions(), r_postlude(), r_prelude(), r_residual_form(), r_residual_suffix(), r_RV(), r_standard_suffix(), r_verb_suffix(), s_16, s_17, and slice_del().