/disk/workspace-cpp/la-manager/source/stem/stem_UTF_8_finnish.cpp File Reference
#include <stem/header.h>
Functions
int finnish_UTF_8_stem (struct SN_env *z)
static int r_tidy (struct SN_env *z)
static int r_other_endings (struct SN_env *z)
static int r_t_plural (struct SN_env *z)
static int r_i_plural (struct SN_env *z)
static int r_case_ending (struct SN_env *z)
static int r_VI (struct SN_env *z)
static int r_LONG (struct SN_env *z)
static int r_possessive (struct SN_env *z)
static int r_particle_etc (struct SN_env *z)
static int r_R2 (struct SN_env *z)
static int r_mark_regions (struct SN_env *z)
struct SN_env * finnish_UTF_8_create_env (void)
void finnish_UTF_8_close_env (struct SN_env *z)
Variables
static const symbol s_0_0 [2] = { 'p', 'a' }
static const symbol s_0_1 [3] = { 's', 't', 'i' }
static const symbol s_0_2 [4] = { 'k', 'a', 'a', 'n' }
static const symbol s_0_3 [3] = { 'h', 'a', 'n' }
static const symbol s_0_4 [3] = { 'k', 'i', 'n' }
static const symbol s_0_5 [4] = { 'h', 0xC3, 0xA4, 'n' }
static const symbol s_0_6 [6] = { 'k', 0xC3, 0xA4, 0xC3, 0xA4, 'n' }
static const symbol s_0_7 [2] = { 'k', 'o' }
static const symbol s_0_8 [3] = { 'p', 0xC3, 0xA4 }
static const symbol s_0_9 [3] = { 'k', 0xC3, 0xB6 }
static struct among a_0 [10]
static const symbol s_1_0 [3] = { 'l', 'l', 'a' }
static const symbol s_1_1 [2] = { 'n', 'a' }
static const symbol s_1_2 [3] = { 's', 's', 'a' }
static const symbol s_1_3 [2] = { 't', 'a' }
static const symbol s_1_4 [3] = { 'l', 't', 'a' }
static const symbol s_1_5 [3] = { 's', 't', 'a' }
static struct among a_1 [6]
static const symbol s_2_0 [4] = { 'l', 'l', 0xC3, 0xA4 }
static const symbol s_2_1 [3] = { 'n', 0xC3, 0xA4 }
static const symbol s_2_2 [4] = { 's', 's', 0xC3, 0xA4 }
static const symbol s_2_3 [3] = { 't', 0xC3, 0xA4 }
static const symbol s_2_4 [4] = { 'l', 't', 0xC3, 0xA4 }
static const symbol s_2_5 [4] = { 's', 't', 0xC3, 0xA4 }
static struct among a_2 [6]
static const symbol s_3_0 [3] = { 'l', 'l', 'e' }
static const symbol s_3_1 [3] = { 'i', 'n', 'e' }
static struct among a_3 [2]
static const symbol s_4_0 [3] = { 'n', 's', 'a' }
static const symbol s_4_1 [3] = { 'm', 'm', 'e' }
static const symbol s_4_2 [3] = { 'n', 'n', 'e' }
static const symbol s_4_3 [2] = { 'n', 'i' }
static const symbol s_4_4 [2] = { 's', 'i' }
static const symbol s_4_5 [2] = { 'a', 'n' }
static const symbol s_4_6 [2] = { 'e', 'n' }
static const symbol s_4_7 [3] = { 0xC3, 0xA4, 'n' }
static const symbol s_4_8 [4] = { 'n', 's', 0xC3, 0xA4 }
static struct among a_4 [9]
static const symbol s_5_0 [2] = { 'a', 'a' }
static const symbol s_5_1 [2] = { 'e', 'e' }
static const symbol s_5_2 [2] = { 'i', 'i' }
static const symbol s_5_3 [2] = { 'o', 'o' }
static const symbol s_5_4 [2] = { 'u', 'u' }
static const symbol s_5_5 [4] = { 0xC3, 0xA4, 0xC3, 0xA4 }
static const symbol s_5_6 [4] = { 0xC3, 0xB6, 0xC3, 0xB6 }
static struct among a_5 [7]
static const symbol s_6_0 [1] = { 'a' }
static const symbol s_6_1 [3] = { 'l', 'l', 'a' }
static const symbol s_6_2 [2] = { 'n', 'a' }
static const symbol s_6_3 [3] = { 's', 's', 'a' }
static const symbol s_6_4 [2] = { 't', 'a' }
static const symbol s_6_5 [3] = { 'l', 't', 'a' }
static const symbol s_6_6 [3] = { 's', 't', 'a' }
static const symbol s_6_7 [3] = { 't', 't', 'a' }
static const symbol s_6_8 [3] = { 'l', 'l', 'e' }
static const symbol s_6_9 [3] = { 'i', 'n', 'e' }
static const symbol s_6_10 [3] = { 'k', 's', 'i' }
static const symbol s_6_11 [1] = { 'n' }
static const symbol s_6_12 [3] = { 'h', 'a', 'n' }
static const symbol s_6_13 [3] = { 'd', 'e', 'n' }
static const symbol s_6_14 [4] = { 's', 'e', 'e', 'n' }
static const symbol s_6_15 [3] = { 'h', 'e', 'n' }
static const symbol s_6_16 [4] = { 't', 't', 'e', 'n' }
static const symbol s_6_17 [3] = { 'h', 'i', 'n' }
static const symbol s_6_18 [4] = { 's', 'i', 'i', 'n' }
static const symbol s_6_19 [3] = { 'h', 'o', 'n' }
static const symbol s_6_20 [4] = { 'h', 0xC3, 0xA4, 'n' }
static const symbol s_6_21 [4] = { 'h', 0xC3, 0xB6, 'n' }
static const symbol s_6_22 [2] = { 0xC3, 0xA4 }
static const symbol s_6_23 [4] = { 'l', 'l', 0xC3, 0xA4 }
static const symbol s_6_24 [3] = { 'n', 0xC3, 0xA4 }
static const symbol s_6_25 [4] = { 's', 's', 0xC3, 0xA4 }
static const symbol s_6_26 [3] = { 't', 0xC3, 0xA4 }
static const symbol s_6_27 [4] = { 'l', 't', 0xC3, 0xA4 }
static const symbol s_6_28 [4] = { 's', 't', 0xC3, 0xA4 }
static const symbol s_6_29 [4] = { 't', 't', 0xC3, 0xA4 }
static struct among a_6 [30]
static const symbol s_7_0 [3] = { 'e', 'j', 'a' }
static const symbol s_7_1 [3] = { 'm', 'm', 'a' }
static const symbol s_7_2 [4] = { 'i', 'm', 'm', 'a' }
static const symbol s_7_3 [3] = { 'm', 'p', 'a' }
static const symbol s_7_4 [4] = { 'i', 'm', 'p', 'a' }
static const symbol s_7_5 [3] = { 'm', 'm', 'i' }
static const symbol s_7_6 [4] = { 'i', 'm', 'm', 'i' }
static const symbol s_7_7 [3] = { 'm', 'p', 'i' }
static const symbol s_7_8 [4] = { 'i', 'm', 'p', 'i' }
static const symbol s_7_9 [4] = { 'e', 'j', 0xC3, 0xA4 }
static const symbol s_7_10 [4] = { 'm', 'm', 0xC3, 0xA4 }
static const symbol s_7_11 [5] = { 'i', 'm', 'm', 0xC3, 0xA4 }
static const symbol s_7_12 [4] = { 'm', 'p', 0xC3, 0xA4 }
static const symbol s_7_13 [5] = { 'i', 'm', 'p', 0xC3, 0xA4 }
static struct among a_7 [14]
static const symbol s_8_0 [1] = { 'i' }
static const symbol s_8_1 [1] = { 'j' }
static struct among a_8 [2]
static const symbol s_9_0 [3] = { 'm', 'm', 'a' }
static const symbol s_9_1 [4] = { 'i', 'm', 'm', 'a' }
static struct among a_9 [2]
static const unsigned char g_AEI [] = { 17, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8 }
static const unsigned char g_V1 [] = { 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 32 }
static const unsigned char g_V2 [] = { 17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 32 }
static const unsigned char g_particle_end [] = { 17, 97, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 32 }
static const symbol s_0 [] = { 'k' }
static const symbol s_1 [] = { 'k', 's', 'e' }
static const symbol s_2 [] = { 'k', 's', 'i' }
static const symbol s_3 [] = { 'i' }
static const symbol s_4 [] = { 'a' }
static const symbol s_5 [] = { 'e' }
static const symbol s_6 [] = { 'i' }
static const symbol s_7 [] = { 'o' }
static const symbol s_8 [] = { 0xC3, 0xA4 }
static const symbol s_9 [] = { 0xC3, 0xB6 }
static const symbol s_10 [] = { 'i', 'e' }
static const symbol s_11 [] = { 'e' }
static const symbol s_12 [] = { 'p', 'o' }
static const symbol s_13 [] = { 't' }
static const symbol s_14 [] = { 'p', 'o' }
static const symbol s_15 [] = { 'j' }
static const symbol s_16 [] = { 'o' }
static const symbol s_17 [] = { 'u' }
static const symbol s_18 [] = { 'o' }
static const symbol s_19 [] = { 'j' }
Function Documentation
void finnish_UTF_8_close_env (struct SN_env * z)
struct SN_env* finnish_UTF_8_create_env (void) [read]
int finnish_UTF_8_stem (struct SN_env * z)
static int r_case_ending (struct SN_env * z) [static]
Definition at line 430 of file stem_UTF_8_finnish.cpp.
References SN_env::B, SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), g_V1, SN_env::I, in_grouping_b_U(), SN_env::ket, SN_env::l, SN_env::lb, out_grouping_b_U(), SN_env::p, r_LONG(), s_10, s_11, s_4, s_5, s_6, s_7, s_8, s_9, skip_utf8(), and slice_del().
Referenced by finnish_UTF_8_stem().
static int r_i_plural (struct SN_env * z) [static]
Definition at line 535 of file stem_UTF_8_finnish.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::I, SN_env::ket, SN_env::l, SN_env::lb, SN_env::p, and slice_del().
Referenced by finnish_UTF_8_stem().
static int r_LONG (struct SN_env * z) [static]
Definition at line 419 of file stem_UTF_8_finnish.cpp.
References find_among_b().
Referenced by r_case_ending(), and r_tidy().
static int r_mark_regions (struct SN_env * z) [static]
Definition at line 294 of file stem_UTF_8_finnish.cpp.
References SN_env::c, g_V1, SN_env::I, in_grouping_U(), SN_env::l, and out_grouping_U().
static int r_other_endings (struct SN_env * z) [static]
Definition at line 504 of file stem_UTF_8_finnish.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), SN_env::I, SN_env::ket, SN_env::l, SN_env::lb, s_12, and slice_del().
Referenced by finnish_UTF_8_stem().
static int r_particle_etc (struct SN_env * z) [static]
Definition at line 319 of file stem_UTF_8_finnish.cpp.
References SN_env::bra, SN_env::c, find_among_b(), g_particle_end, SN_env::I, in_grouping_b_U(), SN_env::ket, SN_env::l, SN_env::lb, r_R2(), and slice_del().
Referenced by finnish_UTF_8_stem().
static int r_possessive (struct SN_env * z) [static]
Definition at line 351 of file stem_UTF_8_finnish.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), SN_env::I, SN_env::ket, SN_env::l, SN_env::lb, SN_env::p, s_0, s_1, s_2, slice_del(), and slice_from_s().
Referenced by finnish_UTF_8_stem().
static int r_R2 (struct SN_env * z) [static]
Definition at line 314 of file stem_UTF_8_finnish.cpp.
References SN_env::c, and SN_env::I.
static int r_t_plural (struct SN_env * z) [static]
Definition at line 554 of file stem_UTF_8_finnish.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), g_V1, SN_env::I, in_grouping_b_U(), SN_env::ket, SN_env::l, SN_env::lb, SN_env::p, s_13, s_14, and slice_del().
Referenced by finnish_UTF_8_stem().
static int r_tidy (struct SN_env * z) [static]
Definition at line 604 of file stem_UTF_8_finnish.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), eq_v_b(), g_AEI, g_V1, SN_env::I, in_grouping_b_U(), SN_env::ket, SN_env::l, SN_env::lb, out_grouping_b_U(), SN_env::p, r_LONG(), SN_env::S, s_15, s_16, s_17, s_18, s_19, skip_utf8(), slice_del(), and slice_to().
Referenced by finnish_UTF_8_stem().
static int r_VI (struct SN_env * z) [static]
Definition at line 424 of file stem_UTF_8_finnish.cpp.
References eq_s_b(), g_V2, in_grouping_b_U(), and s_3.
Variable Documentation
struct among a_0[10] [static]
Initial value:
{
 { 2, s_0_0, -1, 1, 0},
 { 3, s_0_1, -1, 2, 0},
 { 4, s_0_2, -1, 1, 0},
 { 3, s_0_3, -1, 1, 0},
 { 3, s_0_4, -1, 1, 0},
 { 4, s_0_5, -1, 1, 0},
 { 6, s_0_6, -1, 1, 0},
 { 2, s_0_7, -1, 1, 0},
 { 3, s_0_8, -1, 1, 0},
 { 3, s_0_9, -1, 1, 0}
}
Definition at line 50 of file stem_UTF_8_finnish.cpp.
struct among a_1[6] [static]
Initial value:
{
 { 3, s_1_0, -1, -1, 0},
 { 2, s_1_1, -1, -1, 0},
 { 3, s_1_2, -1, -1, 0},
 { 2, s_1_3, -1, -1, 0},
 { 3, s_1_4, 3, -1, 0},
 { 3, s_1_5, 3, -1, 0}
}
Definition at line 71 of file stem_UTF_8_finnish.cpp.
struct among a_2[6] [static]
Initial value:
{
 { 4, s_2_0, -1, -1, 0},
 { 3, s_2_1, -1, -1, 0},
 { 4, s_2_2, -1, -1, 0},
 { 3, s_2_3, -1, -1, 0},
 { 4, s_2_4, 3, -1, 0},
 { 4, s_2_5, 3, -1, 0}
}
Definition at line 88 of file stem_UTF_8_finnish.cpp.
struct among a_3[2] [static]
Initial value:
{
 { 3, s_3_0, -1, -1, 0},
 { 3, s_3_1, -1, -1, 0}
}
Definition at line 101 of file stem_UTF_8_finnish.cpp.
struct among a_4[9] [static]
Initial value:
{
 { 3, s_4_0, -1, 3, 0},
 { 3, s_4_1, -1, 3, 0},
 { 3, s_4_2, -1, 3, 0},
 { 2, s_4_3, -1, 2, 0},
 { 2, s_4_4, -1, 1, 0},
 { 2, s_4_5, -1, 4, 0},
 { 2, s_4_6, -1, 6, 0},
 { 3, s_4_7, -1, 5, 0},
 { 4, s_4_8, -1, 3, 0}
}
Definition at line 117 of file stem_UTF_8_finnish.cpp.
struct among a_5[7] [static]
Initial value:
{
 { 2, s_5_0, -1, -1, 0},
 { 2, s_5_1, -1, -1, 0},
 { 2, s_5_2, -1, -1, 0},
 { 2, s_5_3, -1, -1, 0},
 { 2, s_5_4, -1, -1, 0},
 { 4, s_5_5, -1, -1, 0},
 { 4, s_5_6, -1, -1, 0}
}
Definition at line 138 of file stem_UTF_8_finnish.cpp.
struct among a_6[30] [static]
Definition at line 180 of file stem_UTF_8_finnish.cpp.
struct among a_7[14] [static]
Initial value:
{
 { 3, s_7_0, -1, -1, 0},
 { 3, s_7_1, -1, 1, 0},
 { 4, s_7_2, 1, -1, 0},
 { 3, s_7_3, -1, 1, 0},
 { 4, s_7_4, 3, -1, 0},
 { 3, s_7_5, -1, 1, 0},
 { 4, s_7_6, 5, -1, 0},
 { 3, s_7_7, -1, 1, 0},
 { 4, s_7_8, 7, -1, 0},
 { 4, s_7_9, -1, -1, 0},
 { 4, s_7_10, -1, 1, 0},
 { 5, s_7_11, 10, -1, 0},
 { 4, s_7_12, -1, 1, 0},
 { 5, s_7_13, 12, -1, 0}
}
Definition at line 229 of file stem_UTF_8_finnish.cpp.
struct among a_8[2] [static]
Initial value:
{
 { 1, s_8_0, -1, -1, 0},
 { 1, s_8_1, -1, -1, 0}
}
Definition at line 250 of file stem_UTF_8_finnish.cpp.
struct among a_9[2] [static]
Initial value:
{
 { 3, s_9_0, -1, 1, 0},
 { 4, s_9_1, 0, -1, 0}
}
Definition at line 259 of file stem_UTF_8_finnish.cpp.
const unsigned char g_AEI[] = { 17, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8 } [static]
Definition at line 265 of file stem_UTF_8_finnish.cpp.
Referenced by r_tidy().
const unsigned char g_particle_end[] = { 17, 97, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 32 } [static]
Definition at line 271 of file stem_UTF_8_finnish.cpp.
Referenced by r_particle_etc().
const unsigned char g_V1[] = { 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 32 } [static]
Definition at line 267 of file stem_UTF_8_finnish.cpp.
Referenced by r_case_ending(), r_mark_regions(), r_t_plural(), and r_tidy().
const unsigned char g_V2[] = { 17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 32 } [static]
Definition at line 269 of file stem_UTF_8_finnish.cpp.
Referenced by r_VI().
const symbol s_0[] = { 'k' } [static]
Definition at line 273 of file stem_UTF_8_finnish.cpp.
const symbol s_0_0[2] = { 'p', 'a' } [static]
Definition at line 39 of file stem_UTF_8_finnish.cpp.
const symbol s_0_1[3] = { 's', 't', 'i' } [static]
Definition at line 40 of file stem_UTF_8_finnish.cpp.
const symbol s_0_2[4] = { 'k', 'a', 'a', 'n' } [static]
Definition at line 41 of file stem_UTF_8_finnish.cpp.
const symbol s_0_3[3] = { 'h', 'a', 'n' } [static]
Definition at line 42 of file stem_UTF_8_finnish.cpp.
const symbol s_0_4[3] = { 'k', 'i', 'n' } [static]
Definition at line 43 of file stem_UTF_8_finnish.cpp.
const symbol s_0_5[4] = { 'h', 0xC3, 0xA4, 'n' } [static]
Definition at line 44 of file stem_UTF_8_finnish.cpp.
const symbol s_0_6[6] = { 'k', 0xC3, 0xA4, 0xC3, 0xA4, 'n' } [static]
Definition at line 45 of file stem_UTF_8_finnish.cpp.
const symbol s_0_7[2] = { 'k', 'o' } [static]
Definition at line 46 of file stem_UTF_8_finnish.cpp.
const symbol s_0_8[3] = { 'p', 0xC3, 0xA4 } [static]
Definition at line 47 of file stem_UTF_8_finnish.cpp.
const symbol s_0_9[3] = { 'k', 0xC3, 0xB6 } [static]
Definition at line 48 of file stem_UTF_8_finnish.cpp.
const symbol s_1[] = { 'k', 's', 'e' } [static]
Definition at line 274 of file stem_UTF_8_finnish.cpp.
const symbol s_10[] = { 'i', 'e' } [static]
Definition at line 283 of file stem_UTF_8_finnish.cpp.
const symbol s_11[] = { 'e' } [static]
Definition at line 284 of file stem_UTF_8_finnish.cpp.
const symbol s_12[] = { 'p', 'o' } [static]
Definition at line 285 of file stem_UTF_8_finnish.cpp.
const symbol s_13[] = { 't' } [static]
Definition at line 286 of file stem_UTF_8_finnish.cpp.
const symbol s_14[] = { 'p', 'o' } [static]
Definition at line 287 of file stem_UTF_8_finnish.cpp.
const symbol s_15[] = { 'j' } [static]
Definition at line 288 of file stem_UTF_8_finnish.cpp.
const symbol s_16[] = { 'o' } [static]
Definition at line 289 of file stem_UTF_8_finnish.cpp.
const symbol s_17[] = { 'u' } [static]
Definition at line 290 of file stem_UTF_8_finnish.cpp.
const symbol s_18[] = { 'o' } [static]
Definition at line 291 of file stem_UTF_8_finnish.cpp.
const symbol s_19[] = { 'j' } [static]
Definition at line 292 of file stem_UTF_8_finnish.cpp.
const symbol s_1_0[3] = { 'l', 'l', 'a' } [static]
Definition at line 64 of file stem_UTF_8_finnish.cpp.
const symbol s_1_1[2] = { 'n', 'a' } [static]
Definition at line 65 of file stem_UTF_8_finnish.cpp.
const symbol s_1_2[3] = { 's', 's', 'a' } [static]
Definition at line 66 of file stem_UTF_8_finnish.cpp.
const symbol s_1_3[2] = { 't', 'a' } [static]
Definition at line 67 of file stem_UTF_8_finnish.cpp.
const symbol s_1_4[3] = { 'l', 't', 'a' } [static]
Definition at line 68 of file stem_UTF_8_finnish.cpp.
const symbol s_1_5[3] = { 's', 't', 'a' } [static]
Definition at line 69 of file stem_UTF_8_finnish.cpp.
const symbol s_2[] = { 'k', 's', 'i' } [static]
Definition at line 275 of file stem_UTF_8_finnish.cpp.
const symbol s_2_0[4] = { 'l', 'l', 0xC3, 0xA4 } [static]
Definition at line 81 of file stem_UTF_8_finnish.cpp.
const symbol s_2_1[3] = { 'n', 0xC3, 0xA4 } [static]
Definition at line 82 of file stem_UTF_8_finnish.cpp.
const symbol s_2_2[4] = { 's', 's', 0xC3, 0xA4 } [static]
Definition at line 83 of file stem_UTF_8_finnish.cpp.
const symbol s_2_3[3] = { 't', 0xC3, 0xA4 } [static]
Definition at line 84 of file stem_UTF_8_finnish.cpp.
const symbol s_2_4[4] = { 'l', 't', 0xC3, 0xA4 } [static]
Definition at line 85 of file stem_UTF_8_finnish.cpp.
const symbol s_2_5[4] = { 's', 't', 0xC3, 0xA4 } [static]
Definition at line 86 of file stem_UTF_8_finnish.cpp.
const symbol s_3[] = { 'i' } [static]
Definition at line 276 of file stem_UTF_8_finnish.cpp.
const symbol s_3_0[3] = { 'l', 'l', 'e' } [static]
Definition at line 98 of file stem_UTF_8_finnish.cpp.
const symbol s_3_1[3] = { 'i', 'n', 'e' } [static]
Definition at line 99 of file stem_UTF_8_finnish.cpp.
const symbol s_4[] = { 'a' } [static]
Definition at line 277 of file stem_UTF_8_finnish.cpp.
const symbol s_4_0[3] = { 'n', 's', 'a' } [static]
Definition at line 107 of file stem_UTF_8_finnish.cpp.
const symbol s_4_1[3] = { 'm', 'm', 'e' } [static]
Definition at line 108 of file stem_UTF_8_finnish.cpp.
const symbol s_4_2[3] = { 'n', 'n', 'e' } [static]
Definition at line 109 of file stem_UTF_8_finnish.cpp.
const symbol s_4_3[2] = { 'n', 'i' } [static]
Definition at line 110 of file stem_UTF_8_finnish.cpp.
const symbol s_4_4[2] = { 's', 'i' } [static]
Definition at line 111 of file stem_UTF_8_finnish.cpp.
const symbol s_4_5[2] = { 'a', 'n' } [static]
Definition at line 112 of file stem_UTF_8_finnish.cpp.
const symbol s_4_6[2] = { 'e', 'n' } [static]
Definition at line 113 of file stem_UTF_8_finnish.cpp.
const symbol s_4_7[3] = { 0xC3, 0xA4, 'n' } [static]
Definition at line 114 of file stem_UTF_8_finnish.cpp.
const symbol s_4_8[4] = { 'n', 's', 0xC3, 0xA4 } [static]
Definition at line 115 of file stem_UTF_8_finnish.cpp.
const symbol s_5[] = { 'e' } [static]
Definition at line 278 of file stem_UTF_8_finnish.cpp.
const symbol s_5_0[2] = { 'a', 'a' } [static]
Definition at line 130 of file stem_UTF_8_finnish.cpp.
const symbol s_5_1[2] = { 'e', 'e' } [static]
Definition at line 131 of file stem_UTF_8_finnish.cpp.
const symbol s_5_2[2] = { 'i', 'i' } [static]
Definition at line 132 of file stem_UTF_8_finnish.cpp.
const symbol s_5_3[2] = { 'o', 'o' } [static]
Definition at line 133 of file stem_UTF_8_finnish.cpp.
const symbol s_5_4[2] = { 'u', 'u' } [static]
Definition at line 134 of file stem_UTF_8_finnish.cpp.
const symbol s_5_5[4] = { 0xC3, 0xA4, 0xC3, 0xA4 } [static]
Definition at line 135 of file stem_UTF_8_finnish.cpp.
const symbol s_5_6[4] = { 0xC3, 0xB6, 0xC3, 0xB6 } [static]
Definition at line 136 of file stem_UTF_8_finnish.cpp.
const symbol s_6[] = { 'i' } [static]
Definition at line 279 of file stem_UTF_8_finnish.cpp.
const symbol s_6_0[1] = { 'a' } [static]
Definition at line 149 of file stem_UTF_8_finnish.cpp.
const symbol s_6_1[3] = { 'l', 'l', 'a' } [static]
Definition at line 150 of file stem_UTF_8_finnish.cpp.
const symbol s_6_10[3] = { 'k', 's', 'i' } [static]
Definition at line 159 of file stem_UTF_8_finnish.cpp.
const symbol s_6_11[1] = { 'n' } [static]
Definition at line 160 of file stem_UTF_8_finnish.cpp.
const symbol s_6_12[3] = { 'h', 'a', 'n' } [static]
Definition at line 161 of file stem_UTF_8_finnish.cpp.
const symbol s_6_13[3] = { 'd', 'e', 'n' } [static]
Definition at line 162 of file stem_UTF_8_finnish.cpp.
const symbol s_6_14[4] = { 's', 'e', 'e', 'n' } [static]
Definition at line 163 of file stem_UTF_8_finnish.cpp.
const symbol s_6_15[3] = { 'h', 'e', 'n' } [static]
Definition at line 164 of file stem_UTF_8_finnish.cpp.
const symbol s_6_16[4] = { 't', 't', 'e', 'n' } [static]
Definition at line 165 of file stem_UTF_8_finnish.cpp.
const symbol s_6_17[3] = { 'h', 'i', 'n' } [static]
Definition at line 166 of file stem_UTF_8_finnish.cpp.
const symbol s_6_18[4] = { 's', 'i', 'i', 'n' } [static]
Definition at line 167 of file stem_UTF_8_finnish.cpp.
const symbol s_6_19[3] = { 'h', 'o', 'n' } [static]
Definition at line 168 of file stem_UTF_8_finnish.cpp.
const symbol s_6_2[2] = { 'n', 'a' } [static]
Definition at line 151 of file stem_UTF_8_finnish.cpp.
const symbol s_6_20[4] = { 'h', 0xC3, 0xA4, 'n' } [static]
Definition at line 169 of file stem_UTF_8_finnish.cpp.
const symbol s_6_21[4] = { 'h', 0xC3, 0xB6, 'n' } [static]
Definition at line 170 of file stem_UTF_8_finnish.cpp.
const symbol s_6_22[2] = { 0xC3, 0xA4 } [static]
Definition at line 171 of file stem_UTF_8_finnish.cpp.
const symbol s_6_23[4] = { 'l', 'l', 0xC3, 0xA4 } [static]
Definition at line 172 of file stem_UTF_8_finnish.cpp.
const symbol s_6_24[3] = { 'n', 0xC3, 0xA4 } [static]
Definition at line 173 of file stem_UTF_8_finnish.cpp.
const symbol s_6_25[4] = { 's', 's', 0xC3, 0xA4 } [static]
Definition at line 174 of file stem_UTF_8_finnish.cpp.
const symbol s_6_26[3] = { 't', 0xC3, 0xA4 } [static]
Definition at line 175 of file stem_UTF_8_finnish.cpp.
const symbol s_6_27[4] = { 'l', 't', 0xC3, 0xA4 } [static]
Definition at line 176 of file stem_UTF_8_finnish.cpp.
const symbol s_6_28[4] = { 's', 't', 0xC3, 0xA4 } [static]
Definition at line 177 of file stem_UTF_8_finnish.cpp.
const symbol s_6_29[4] = { 't', 't', 0xC3, 0xA4 } [static]
Definition at line 178 of file stem_UTF_8_finnish.cpp.
const symbol s_6_3[3] = { 's', 's', 'a' } [static]
Definition at line 152 of file stem_UTF_8_finnish.cpp.
const symbol s_6_4[2] = { 't', 'a' } [static]
Definition at line 153 of file stem_UTF_8_finnish.cpp.
const symbol s_6_5[3] = { 'l', 't', 'a' } [static]
Definition at line 154 of file stem_UTF_8_finnish.cpp.
const symbol s_6_6[3] = { 's', 't', 'a' } [static]
Definition at line 155 of file stem_UTF_8_finnish.cpp.
const symbol s_6_7[3] = { 't', 't', 'a' } [static]
Definition at line 156 of file stem_UTF_8_finnish.cpp.
const symbol s_6_8[3] = { 'l', 'l', 'e' } [static]
Definition at line 157 of file stem_UTF_8_finnish.cpp.
const symbol s_6_9[3] = { 'i', 'n', 'e' } [static]
Definition at line 158 of file stem_UTF_8_finnish.cpp.
const symbol s_7[] = { 'o' } [static]
Definition at line 280 of file stem_UTF_8_finnish.cpp.
const symbol s_7_0[3] = { 'e', 'j', 'a' } [static]
Definition at line 214 of file stem_UTF_8_finnish.cpp.
const symbol s_7_1[3] = { 'm', 'm', 'a' } [static]
Definition at line 215 of file stem_UTF_8_finnish.cpp.
const symbol s_7_10[4] = { 'm', 'm', 0xC3, 0xA4 } [static]
Definition at line 224 of file stem_UTF_8_finnish.cpp.
const symbol s_7_11[5] = { 'i', 'm', 'm', 0xC3, 0xA4 } [static]
Definition at line 225 of file stem_UTF_8_finnish.cpp.
const symbol s_7_12[4] = { 'm', 'p', 0xC3, 0xA4 } [static]
Definition at line 226 of file stem_UTF_8_finnish.cpp.
const symbol s_7_13[5] = { 'i', 'm', 'p', 0xC3, 0xA4 } [static]
Definition at line 227 of file stem_UTF_8_finnish.cpp.
const symbol s_7_2[4] = { 'i', 'm', 'm', 'a' } [static]
Definition at line 216 of file stem_UTF_8_finnish.cpp.
const symbol s_7_3[3] = { 'm', 'p', 'a' } [static]
Definition at line 217 of file stem_UTF_8_finnish.cpp.
const symbol s_7_4[4] = { 'i', 'm', 'p', 'a' } [static]
Definition at line 218 of file stem_UTF_8_finnish.cpp.
const symbol s_7_5[3] = { 'm', 'm', 'i' } [static]
Definition at line 219 of file stem_UTF_8_finnish.cpp.
const symbol s_7_6[4] = { 'i', 'm', 'm', 'i' } [static]
Definition at line 220 of file stem_UTF_8_finnish.cpp.
const symbol s_7_7[3] = { 'm', 'p', 'i' } [static]
Definition at line 221 of file stem_UTF_8_finnish.cpp.
const symbol s_7_8[4] = { 'i', 'm', 'p', 'i' } [static]
Definition at line 222 of file stem_UTF_8_finnish.cpp.
const symbol s_7_9[4] = { 'e', 'j', 0xC3, 0xA4 } [static]
Definition at line 223 of file stem_UTF_8_finnish.cpp.
const symbol s_8[] = { 0xC3, 0xA4 } [static]
Definition at line 281 of file stem_UTF_8_finnish.cpp.
const symbol s_8_0[1] = { 'i' } [static]
Definition at line 247 of file stem_UTF_8_finnish.cpp.
const symbol s_8_1[1] = { 'j' } [static]
Definition at line 248 of file stem_UTF_8_finnish.cpp.
const symbol s_9[] = { 0xC3, 0xB6 } [static]
Definition at line 282 of file stem_UTF_8_finnish.cpp.
const symbol s_9_0[3] = { 'm', 'm', 'a' } [static]
Definition at line 256 of file stem_UTF_8_finnish.cpp.
const symbol s_9_1[4] = { 'i', 'm', 'm', 'a' } [static]
Definition at line 257 of file stem_UTF_8_finnish.cpp.