/disk/workspace-cpp/la-manager/include/stem/stem_UTF_8_romanian.h File Reference
Functions
struct SN_env * romanian_UTF_8_create_env (void)
void romanian_UTF_8_close_env (struct SN_env *z)
int romanian_UTF_8_stem (struct SN_env *z)
Function Documentation
void romanian_UTF_8_close_env (struct SN_env * z)
Definition at line 1004 of file stem_UTF_8_romanian.cpp.
References SN_close_env().
struct SN_env * romanian_UTF_8_create_env (void) [read]
Definition at line 1002 of file stem_UTF_8_romanian.cpp.
References SN_create_env().
int romanian_UTF_8_stem (struct SN_env * z)
Definition at line 932 of file stem_UTF_8_romanian.cpp.
References SN_env::B, SN_env::c, SN_env::l, SN_env::lb, r_mark_regions(), r_postlude(), r_prelude(), r_standard_suffix(), r_step_0(), r_verb_suffix(), and r_vowel_suffix().