/disk/workspace-cpp/la-manager/include/stem/stem_UTF_8_dutch.h File Reference
Functions
struct SN_env * dutch_UTF_8_create_env (void)
void dutch_UTF_8_close_env (struct SN_env *z)
int dutch_UTF_8_stem (struct SN_env *z)
Function Documentation
void dutch_UTF_8_close_env (struct SN_env * z)
Definition at line 634 of file stem_UTF_8_dutch.cpp.
References SN_close_env().
struct SN_env * dutch_UTF_8_create_env (void) [read]
Definition at line 632 of file stem_UTF_8_dutch.cpp.
References SN_create_env().
int dutch_UTF_8_stem (struct SN_env * z)
Definition at line 593 of file stem_UTF_8_dutch.cpp.
References SN_env::c, SN_env::l, SN_env::lb, r_mark_regions(), r_postlude(), r_prelude(), and r_standard_suffix().