/disk/workspace-cpp/la-manager/include/stem/stem_UTF_8_italian.h File Reference
Functions
struct SN_env * italian_UTF_8_create_env (void)
void italian_UTF_8_close_env (struct SN_env *z)
int italian_UTF_8_stem (struct SN_env *z)
Function Documentation
void italian_UTF_8_close_env (struct SN_env * z)
Definition at line 1075 of file stem_UTF_8_italian.cpp.
References SN_close_env().
struct SN_env * italian_UTF_8_create_env (void) [read]
Definition at line 1073 of file stem_UTF_8_italian.cpp.
References SN_create_env().
int italian_UTF_8_stem (struct SN_env * z)
Definition at line 1008 of file stem_UTF_8_italian.cpp.
References SN_env::c, SN_env::l, SN_env::lb, r_attached_pronoun(), r_mark_regions(), r_postlude(), r_prelude(), r_standard_suffix(), r_verb_suffix(), and r_vowel_suffix().