/disk/workspace-cpp/la-manager/source/stem/stem_UTF_8_norwegian.cpp File Reference
#include <stem/header.h>
Functions
int norwegian_UTF_8_stem (struct SN_env *z)
static int r_other_suffix (struct SN_env *z)
static int r_consonant_pair (struct SN_env *z)
static int r_main_suffix (struct SN_env *z)
static int r_mark_regions (struct SN_env *z)
struct SN_env * norwegian_UTF_8_create_env (void)
void norwegian_UTF_8_close_env (struct SN_env *z)
Variables
static const symbol s_0_0 [1] = { 'a' }
static const symbol s_0_1 [1] = { 'e' }
static const symbol s_0_2 [3] = { 'e', 'd', 'e' }
static const symbol s_0_3 [4] = { 'a', 'n', 'd', 'e' }
static const symbol s_0_4 [4] = { 'e', 'n', 'd', 'e' }
static const symbol s_0_5 [3] = { 'a', 'n', 'e' }
static const symbol s_0_6 [3] = { 'e', 'n', 'e' }
static const symbol s_0_7 [6] = { 'h', 'e', 't', 'e', 'n', 'e' }
static const symbol s_0_8 [4] = { 'e', 'r', 't', 'e' }
static const symbol s_0_9 [2] = { 'e', 'n' }
static const symbol s_0_10 [5] = { 'h', 'e', 't', 'e', 'n' }
static const symbol s_0_11 [2] = { 'a', 'r' }
static const symbol s_0_12 [2] = { 'e', 'r' }
static const symbol s_0_13 [5] = { 'h', 'e', 't', 'e', 'r' }
static const symbol s_0_14 [1] = { 's' }
static const symbol s_0_15 [2] = { 'a', 's' }
static const symbol s_0_16 [2] = { 'e', 's' }
static const symbol s_0_17 [4] = { 'e', 'd', 'e', 's' }
static const symbol s_0_18 [5] = { 'e', 'n', 'd', 'e', 's' }
static const symbol s_0_19 [4] = { 'e', 'n', 'e', 's' }
static const symbol s_0_20 [7] = { 'h', 'e', 't', 'e', 'n', 'e', 's' }
static const symbol s_0_21 [3] = { 'e', 'n', 's' }
static const symbol s_0_22 [6] = { 'h', 'e', 't', 'e', 'n', 's' }
static const symbol s_0_23 [3] = { 'e', 'r', 's' }
static const symbol s_0_24 [3] = { 'e', 't', 's' }
static const symbol s_0_25 [2] = { 'e', 't' }
static const symbol s_0_26 [3] = { 'h', 'e', 't' }
static const symbol s_0_27 [3] = { 'e', 'r', 't' }
static const symbol s_0_28 [3] = { 'a', 's', 't' }
static struct among a_0 [29]
static const symbol s_1_0 [2] = { 'd', 't' }
static const symbol s_1_1 [2] = { 'v', 't' }
static struct among a_1 [2]
static const symbol s_2_0 [3] = { 'l', 'e', 'g' }
static const symbol s_2_1 [4] = { 'e', 'l', 'e', 'g' }
static const symbol s_2_2 [2] = { 'i', 'g' }
static const symbol s_2_3 [3] = { 'e', 'i', 'g' }
static const symbol s_2_4 [3] = { 'l', 'i', 'g' }
static const symbol s_2_5 [4] = { 'e', 'l', 'i', 'g' }
static const symbol s_2_6 [3] = { 'e', 'l', 's' }
static const symbol s_2_7 [3] = { 'l', 'o', 'v' }
static const symbol s_2_8 [4] = { 'e', 'l', 'o', 'v' }
static const symbol s_2_9 [4] = { 's', 'l', 'o', 'v' }
static const symbol s_2_10 [7] = { 'h', 'e', 't', 's', 'l', 'o', 'v' }
static struct among a_2 [11]
static const unsigned char g_v [] = { 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 0, 128 }
static const unsigned char g_s_ending [] = { 119, 125, 149, 1 }
static const symbol s_0 [] = { 'k' }
static const symbol s_1 [] = { 'e', 'r' }
Function Documentation
void norwegian_UTF_8_close_env (struct SN_env * z)
struct SN_env* norwegian_UTF_8_create_env (void) [read]
int norwegian_UTF_8_stem (struct SN_env * z)
static int r_consonant_pair (struct SN_env * z) [static]
Definition at line 205 of file stem_UTF_8_norwegian.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::I, SN_env::ket, SN_env::l, SN_env::lb, SN_env::p, skip_utf8(), and slice_del().
static int r_main_suffix (struct SN_env * z) [static]
Definition at line 160 of file stem_UTF_8_norwegian.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), g_s_ending, g_v, SN_env::I, in_grouping_b_U(), SN_env::ket, SN_env::l, SN_env::lb, out_grouping_b_U(), SN_env::p, s_0, s_1, slice_del(), and slice_from_s().
static int r_mark_regions (struct SN_env * z) [static]
Definition at line 136 of file stem_UTF_8_norwegian.cpp.
References SN_env::c, g_v, SN_env::I, in_grouping_U(), SN_env::l, out_grouping_U(), SN_env::p, and skip_utf8().
static int r_other_suffix (struct SN_env * z) [static]
Definition at line 232 of file stem_UTF_8_norwegian.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::I, SN_env::ket, SN_env::l, SN_env::lb, SN_env::p, and slice_del().
Variable Documentation
struct among a_0[29] [static]
Initial value:
{
 { 1, s_0_0, -1, 1, 0},
 { 1, s_0_1, -1, 1, 0},
 { 3, s_0_2, 1, 1, 0},
 { 4, s_0_3, 1, 1, 0},
 { 4, s_0_4, 1, 1, 0},
 { 3, s_0_5, 1, 1, 0},
 { 3, s_0_6, 1, 1, 0},
 { 6, s_0_7, 6, 1, 0},
 { 4, s_0_8, 1, 3, 0},
 { 2, s_0_9, -1, 1, 0},
 { 5, s_0_10, 9, 1, 0},
 { 2, s_0_11, -1, 1, 0},
 { 2, s_0_12, -1, 1, 0},
 { 5, s_0_13, 12, 1, 0},
 { 1, s_0_14, -1, 2, 0},
 { 2, s_0_15, 14, 1, 0},
 { 2, s_0_16, 14, 1, 0},
 { 4, s_0_17, 16, 1, 0},
 { 5, s_0_18, 16, 1, 0},
 { 4, s_0_19, 16, 1, 0},
 { 7, s_0_20, 19, 1, 0},
 { 3, s_0_21, 14, 1, 0},
 { 6, s_0_22, 21, 1, 0},
 { 3, s_0_23, 14, 1, 0},
 { 3, s_0_24, 14, 1, 0},
 { 2, s_0_25, -1, 1, 0},
 { 3, s_0_26, 25, 1, 0},
 { 3, s_0_27, -1, 3, 0},
 { 3, s_0_28, -1, 1, 0}
}
Definition at line 60 of file stem_UTF_8_norwegian.cpp.
struct among a_1[2] [static]
Initial value:
{
 { 2, s_1_0, -1, -1, 0},
 { 2, s_1_1, -1, -1, 0}
}
Definition at line 96 of file stem_UTF_8_norwegian.cpp.
struct among a_2[11] [static]
Initial value:
{
 { 3, s_2_0, -1, 1, 0},
 { 4, s_2_1, 0, 1, 0},
 { 2, s_2_2, -1, 1, 0},
 { 3, s_2_3, 2, 1, 0},
 { 3, s_2_4, 2, 1, 0},
 { 4, s_2_5, 4, 1, 0},
 { 3, s_2_6, -1, 1, 0},
 { 3, s_2_7, -1, 1, 0},
 { 4, s_2_8, 7, 1, 0},
 { 4, s_2_9, 7, 1, 0},
 { 7, s_2_10, 9, 1, 0}
}
Definition at line 114 of file stem_UTF_8_norwegian.cpp.
const unsigned char g_s_ending[] = { 119, 125, 149, 1 } [static]
Definition at line 131 of file stem_UTF_8_norwegian.cpp.
const unsigned char g_v[] = { 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 0, 128 } [static]
Definition at line 129 of file stem_UTF_8_norwegian.cpp.
const symbol s_0[] = { 'k' } [static]
Definition at line 133 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_0[1] = { 'a' } [static]
Definition at line 30 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_1[1] = { 'e' } [static]
Definition at line 31 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_10[5] = { 'h', 'e', 't', 'e', 'n' } [static]
Definition at line 40 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_11[2] = { 'a', 'r' } [static]
Definition at line 41 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_12[2] = { 'e', 'r' } [static]
Definition at line 42 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_13[5] = { 'h', 'e', 't', 'e', 'r' } [static]
Definition at line 43 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_14[1] = { 's' } [static]
Definition at line 44 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_15[2] = { 'a', 's' } [static]
Definition at line 45 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_16[2] = { 'e', 's' } [static]
Definition at line 46 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_17[4] = { 'e', 'd', 'e', 's' } [static]
Definition at line 47 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_18[5] = { 'e', 'n', 'd', 'e', 's' } [static]
Definition at line 48 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_19[4] = { 'e', 'n', 'e', 's' } [static]
Definition at line 49 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_2[3] = { 'e', 'd', 'e' } [static]
Definition at line 32 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_20[7] = { 'h', 'e', 't', 'e', 'n', 'e', 's' } [static]
Definition at line 50 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_21[3] = { 'e', 'n', 's' } [static]
Definition at line 51 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_22[6] = { 'h', 'e', 't', 'e', 'n', 's' } [static]
Definition at line 52 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_23[3] = { 'e', 'r', 's' } [static]
Definition at line 53 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_24[3] = { 'e', 't', 's' } [static]
Definition at line 54 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_25[2] = { 'e', 't' } [static]
Definition at line 55 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_26[3] = { 'h', 'e', 't' } [static]
Definition at line 56 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_27[3] = { 'e', 'r', 't' } [static]
Definition at line 57 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_28[3] = { 'a', 's', 't' } [static]
Definition at line 58 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_3[4] = { 'a', 'n', 'd', 'e' } [static]
Definition at line 33 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_4[4] = { 'e', 'n', 'd', 'e' } [static]
Definition at line 34 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_5[3] = { 'a', 'n', 'e' } [static]
Definition at line 35 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_6[3] = { 'e', 'n', 'e' } [static]
Definition at line 36 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_7[6] = { 'h', 'e', 't', 'e', 'n', 'e' } [static]
Definition at line 37 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_8[4] = { 'e', 'r', 't', 'e' } [static]
Definition at line 38 of file stem_UTF_8_norwegian.cpp.
const symbol s_0_9[2] = { 'e', 'n' } [static]
Definition at line 39 of file stem_UTF_8_norwegian.cpp.
const symbol s_1[] = { 'e', 'r' } [static]
Definition at line 134 of file stem_UTF_8_norwegian.cpp.
const symbol s_1_0[2] = { 'd', 't' } [static]
Definition at line 93 of file stem_UTF_8_norwegian.cpp.
const symbol s_1_1[2] = { 'v', 't' } [static]
Definition at line 94 of file stem_UTF_8_norwegian.cpp.
const symbol s_2_0[3] = { 'l', 'e', 'g' } [static]
Definition at line 102 of file stem_UTF_8_norwegian.cpp.
const symbol s_2_1[4] = { 'e', 'l', 'e', 'g' } [static]
Definition at line 103 of file stem_UTF_8_norwegian.cpp.
const symbol s_2_10[7] = { 'h', 'e', 't', 's', 'l', 'o', 'v' } [static]
Definition at line 112 of file stem_UTF_8_norwegian.cpp.
const symbol s_2_2[2] = { 'i', 'g' } [static]
Definition at line 104 of file stem_UTF_8_norwegian.cpp.
const symbol s_2_3[3] = { 'e', 'i', 'g' } [static]
Definition at line 105 of file stem_UTF_8_norwegian.cpp.
const symbol s_2_4[3] = { 'l', 'i', 'g' } [static]
Definition at line 106 of file stem_UTF_8_norwegian.cpp.
const symbol s_2_5[4] = { 'e', 'l', 'i', 'g' } [static]
Definition at line 107 of file stem_UTF_8_norwegian.cpp.
const symbol s_2_6[3] = { 'e', 'l', 's' } [static]
Definition at line 108 of file stem_UTF_8_norwegian.cpp.
const symbol s_2_7[3] = { 'l', 'o', 'v' } [static]
Definition at line 109 of file stem_UTF_8_norwegian.cpp.
const symbol s_2_8[4] = { 'e', 'l', 'o', 'v' } [static]
Definition at line 110 of file stem_UTF_8_norwegian.cpp.
const symbol s_2_9[4] = { 's', 'l', 'o', 'v' } [static]
Definition at line 111 of file stem_UTF_8_norwegian.cpp.