/disk/workspace-cpp/la-manager/include/stem/stem_UTF_8_english.h File Reference
Functions
struct SN_env * english_UTF_8_create_env (void)
void english_UTF_8_close_env (struct SN_env *z)
int english_UTF_8_stem (struct SN_env *z)
Function Documentation
void english_UTF_8_close_env (struct SN_env * z)
Definition at line 1125 of file stem_UTF_8_english.cpp.
References SN_close_env().
struct SN_env * english_UTF_8_create_env (void) [read]
Definition at line 1123 of file stem_UTF_8_english.cpp.
References SN_create_env().
int english_UTF_8_stem (struct SN_env * z)
Definition at line 1004 of file stem_UTF_8_english.cpp.
References SN_env::c, SN_env::l, SN_env::lb, SN_env::p, r_exception1(), r_exception2(), r_mark_regions(), r_postlude(), r_prelude(), r_Step_1a(), r_Step_1b(), r_Step_1c(), r_Step_2(), r_Step_3(), r_Step_4(), r_Step_5(), and skip_utf8().