/disk/workspace-cpp/la-manager/source/stem/stem_UTF_8_english.cpp File Reference
#include <stem/header.h>
Functions
int english_UTF_8_stem (struct SN_env *z)
static int r_exception2 (struct SN_env *z)
static int r_exception1 (struct SN_env *z)
static int r_Step_5 (struct SN_env *z)
static int r_Step_4 (struct SN_env *z)
static int r_Step_3 (struct SN_env *z)
static int r_Step_2 (struct SN_env *z)
static int r_Step_1c (struct SN_env *z)
static int r_Step_1b (struct SN_env *z)
static int r_Step_1a (struct SN_env *z)
static int r_R2 (struct SN_env *z)
static int r_R1 (struct SN_env *z)
static int r_shortv (struct SN_env *z)
static int r_mark_regions (struct SN_env *z)
static int r_postlude (struct SN_env *z)
static int r_prelude (struct SN_env *z)
struct SN_env * english_UTF_8_create_env (void)
void english_UTF_8_close_env (struct SN_env *z)
Variables
static const symbol s_0_0 [5] = { 'a', 'r', 's', 'e', 'n' }
static const symbol s_0_1 [6] = { 'c', 'o', 'm', 'm', 'u', 'n' }
static const symbol s_0_2 [5] = { 'g', 'e', 'n', 'e', 'r' }
static struct among a_0 [3]
static const symbol s_1_0 [1] = { '\'' }
static const symbol s_1_1 [3] = { '\'', 's', '\'' }
static const symbol s_1_2 [2] = { '\'', 's' }
static struct among a_1 [3]
static const symbol s_2_0 [3] = { 'i', 'e', 'd' }
static const symbol s_2_1 [1] = { 's' }
static const symbol s_2_2 [3] = { 'i', 'e', 's' }
static const symbol s_2_3 [4] = { 's', 's', 'e', 's' }
static const symbol s_2_4 [2] = { 's', 's' }
static const symbol s_2_5 [2] = { 'u', 's' }
static struct among a_2 [6]
static const symbol s_3_1 [2] = { 'b', 'b' }
static const symbol s_3_2 [2] = { 'd', 'd' }
static const symbol s_3_3 [2] = { 'f', 'f' }
static const symbol s_3_4 [2] = { 'g', 'g' }
static const symbol s_3_5 [2] = { 'b', 'l' }
static const symbol s_3_6 [2] = { 'm', 'm' }
static const symbol s_3_7 [2] = { 'n', 'n' }
static const symbol s_3_8 [2] = { 'p', 'p' }
static const symbol s_3_9 [2] = { 'r', 'r' }
static const symbol s_3_10 [2] = { 'a', 't' }
static const symbol s_3_11 [2] = { 't', 't' }
static const symbol s_3_12 [2] = { 'i', 'z' }
static struct among a_3 [13]
static const symbol s_4_0 [2] = { 'e', 'd' }
static const symbol s_4_1 [3] = { 'e', 'e', 'd' }
static const symbol s_4_2 [3] = { 'i', 'n', 'g' }
static const symbol s_4_3 [4] = { 'e', 'd', 'l', 'y' }
static const symbol s_4_4 [5] = { 'e', 'e', 'd', 'l', 'y' }
static const symbol s_4_5 [5] = { 'i', 'n', 'g', 'l', 'y' }
static struct among a_4 [6]
static const symbol s_5_0 [4] = { 'a', 'n', 'c', 'i' }
static const symbol s_5_1 [4] = { 'e', 'n', 'c', 'i' }
static const symbol s_5_2 [3] = { 'o', 'g', 'i' }
static const symbol s_5_3 [2] = { 'l', 'i' }
static const symbol s_5_4 [3] = { 'b', 'l', 'i' }
static const symbol s_5_5 [4] = { 'a', 'b', 'l', 'i' }
static const symbol s_5_6 [4] = { 'a', 'l', 'l', 'i' }
static const symbol s_5_7 [5] = { 'f', 'u', 'l', 'l', 'i' }
static const symbol s_5_8 [6] = { 'l', 'e', 's', 's', 'l', 'i' }
static const symbol s_5_9 [5] = { 'o', 'u', 's', 'l', 'i' }
static const symbol s_5_10 [5] = { 'e', 'n', 't', 'l', 'i' }
static const symbol s_5_11 [5] = { 'a', 'l', 'i', 't', 'i' }
static const symbol s_5_12 [6] = { 'b', 'i', 'l', 'i', 't', 'i' }
static const symbol s_5_13 [5] = { 'i', 'v', 'i', 't', 'i' }
static const symbol s_5_14 [6] = { 't', 'i', 'o', 'n', 'a', 'l' }
static const symbol s_5_15 [7] = { 'a', 't', 'i', 'o', 'n', 'a', 'l' }
static const symbol s_5_16 [5] = { 'a', 'l', 'i', 's', 'm' }
static const symbol s_5_17 [5] = { 'a', 't', 'i', 'o', 'n' }
static const symbol s_5_18 [7] = { 'i', 'z', 'a', 't', 'i', 'o', 'n' }
static const symbol s_5_19 [4] = { 'i', 'z', 'e', 'r' }
static const symbol s_5_20 [4] = { 'a', 't', 'o', 'r' }
static const symbol s_5_21 [7] = { 'i', 'v', 'e', 'n', 'e', 's', 's' }
static const symbol s_5_22 [7] = { 'f', 'u', 'l', 'n', 'e', 's', 's' }
static const symbol s_5_23 [7] = { 'o', 'u', 's', 'n', 'e', 's', 's' }
static struct among a_5 [24]
static const symbol s_6_0 [5] = { 'i', 'c', 'a', 't', 'e' }
static const symbol s_6_1 [5] = { 'a', 't', 'i', 'v', 'e' }
static const symbol s_6_2 [5] = { 'a', 'l', 'i', 'z', 'e' }
static const symbol s_6_3 [5] = { 'i', 'c', 'i', 't', 'i' }
static const symbol s_6_4 [4] = { 'i', 'c', 'a', 'l' }
static const symbol s_6_5 [6] = { 't', 'i', 'o', 'n', 'a', 'l' }
static const symbol s_6_6 [7] = { 'a', 't', 'i', 'o', 'n', 'a', 'l' }
static const symbol s_6_7 [3] = { 'f', 'u', 'l' }
static const symbol s_6_8 [4] = { 'n', 'e', 's', 's' }
static struct among a_6 [9]
static const symbol s_7_0 [2] = { 'i', 'c' }
static const symbol s_7_1 [4] = { 'a', 'n', 'c', 'e' }
static const symbol s_7_2 [4] = { 'e', 'n', 'c', 'e' }
static const symbol s_7_3 [4] = { 'a', 'b', 'l', 'e' }
static const symbol s_7_4 [4] = { 'i', 'b', 'l', 'e' }
static const symbol s_7_5 [3] = { 'a', 't', 'e' }
static const symbol s_7_6 [3] = { 'i', 'v', 'e' }
static const symbol s_7_7 [3] = { 'i', 'z', 'e' }
static const symbol s_7_8 [3] = { 'i', 't', 'i' }
static const symbol s_7_9 [2] = { 'a', 'l' }
static const symbol s_7_10 [3] = { 'i', 's', 'm' }
static const symbol s_7_11 [3] = { 'i', 'o', 'n' }
static const symbol s_7_12 [2] = { 'e', 'r' }
static const symbol s_7_13 [3] = { 'o', 'u', 's' }
static const symbol s_7_14 [3] = { 'a', 'n', 't' }
static const symbol s_7_15 [3] = { 'e', 'n', 't' }
static const symbol s_7_16 [4] = { 'm', 'e', 'n', 't' }
static const symbol s_7_17 [5] = { 'e', 'm', 'e', 'n', 't' }
static struct among a_7 [18]
static const symbol s_8_0 [1] = { 'e' }
static const symbol s_8_1 [1] = { 'l' }
static struct among a_8 [2]
static const symbol s_9_0 [7] = { 's', 'u', 'c', 'c', 'e', 'e', 'd' }
static const symbol s_9_1 [7] = { 'p', 'r', 'o', 'c', 'e', 'e', 'd' }
static const symbol s_9_2 [6] = { 'e', 'x', 'c', 'e', 'e', 'd' }
static const symbol s_9_3 [7] = { 'c', 'a', 'n', 'n', 'i', 'n', 'g' }
static const symbol s_9_4 [6] = { 'i', 'n', 'n', 'i', 'n', 'g' }
static const symbol s_9_5 [7] = { 'e', 'a', 'r', 'r', 'i', 'n', 'g' }
static const symbol s_9_6 [7] = { 'h', 'e', 'r', 'r', 'i', 'n', 'g' }
static const symbol s_9_7 [6] = { 'o', 'u', 't', 'i', 'n', 'g' }
static struct among a_9 [8]
static const symbol s_10_0 [5] = { 'a', 'n', 'd', 'e', 's' }
static const symbol s_10_1 [5] = { 'a', 't', 'l', 'a', 's' }
static const symbol s_10_2 [4] = { 'b', 'i', 'a', 's' }
static const symbol s_10_3 [6] = { 'c', 'o', 's', 'm', 'o', 's' }
static const symbol s_10_4 [5] = { 'd', 'y', 'i', 'n', 'g' }
static const symbol s_10_5 [5] = { 'e', 'a', 'r', 'l', 'y' }
static const symbol s_10_6 [6] = { 'g', 'e', 'n', 't', 'l', 'y' }
static const symbol s_10_7 [4] = { 'h', 'o', 'w', 'e' }
static const symbol s_10_8 [4] = { 'i', 'd', 'l', 'y' }
static const symbol s_10_9 [5] = { 'l', 'y', 'i', 'n', 'g' }
static const symbol s_10_10 [4] = { 'n', 'e', 'w', 's' }
static const symbol s_10_11 [4] = { 'o', 'n', 'l', 'y' }
static const symbol s_10_12 [6] = { 's', 'i', 'n', 'g', 'l', 'y' }
static const symbol s_10_13 [5] = { 's', 'k', 'i', 'e', 's' }
static const symbol s_10_14 [4] = { 's', 'k', 'i', 's' }
static const symbol s_10_15 [3] = { 's', 'k', 'y' }
static const symbol s_10_16 [5] = { 't', 'y', 'i', 'n', 'g' }
static const symbol s_10_17 [4] = { 'u', 'g', 'l', 'y' }
static struct among a_10 [18]
static const unsigned char g_v [] = { 17, 65, 16, 1 }
static const unsigned char g_v_WXY [] = { 1, 17, 65, 208, 1 }
static const unsigned char g_valid_LI [] = { 55, 141, 2 }
static const symbol s_0 [] = { '\'' }
static const symbol s_1 [] = { 'y' }
static const symbol s_2 [] = { 'Y' }
static const symbol s_3 [] = { 'y' }
static const symbol s_4 [] = { 'Y' }
static const symbol s_5 [] = { 's', 's' }
static const symbol s_6 [] = { 'i' }
static const symbol s_7 [] = { 'i', 'e' }
static const symbol s_8 [] = { 'e', 'e' }
static const symbol s_9 [] = { 'e' }
static const symbol s_10 [] = { 'e' }
static const symbol s_11 [] = { 'y' }
static const symbol s_12 [] = { 'Y' }
static const symbol s_13 [] = { 'i' }
static const symbol s_14 [] = { 't', 'i', 'o', 'n' }
static const symbol s_15 [] = { 'e', 'n', 'c', 'e' }
static const symbol s_16 [] = { 'a', 'n', 'c', 'e' }
static const symbol s_17 [] = { 'a', 'b', 'l', 'e' }
static const symbol s_18 [] = { 'e', 'n', 't' }
static const symbol s_19 [] = { 'i', 'z', 'e' }
static const symbol s_20 [] = { 'a', 't', 'e' }
static const symbol s_21 [] = { 'a', 'l' }
static const symbol s_22 [] = { 'f', 'u', 'l' }
static const symbol s_23 [] = { 'o', 'u', 's' }
static const symbol s_24 [] = { 'i', 'v', 'e' }
static const symbol s_25 [] = { 'b', 'l', 'e' }
static const symbol s_26 [] = { 'l' }
static const symbol s_27 [] = { 'o', 'g' }
static const symbol s_28 [] = { 'f', 'u', 'l' }
static const symbol s_29 [] = { 'l', 'e', 's', 's' }
static const symbol s_30 [] = { 't', 'i', 'o', 'n' }
static const symbol s_31 [] = { 'a', 't', 'e' }
static const symbol s_32 [] = { 'a', 'l' }
static const symbol s_33 [] = { 'i', 'c' }
static const symbol s_34 [] = { 's' }
static const symbol s_35 [] = { 't' }
static const symbol s_36 [] = { 'l' }
static const symbol s_37 [] = { 's', 'k', 'i' }
static const symbol s_38 [] = { 's', 'k', 'y' }
static const symbol s_39 [] = { 'd', 'i', 'e' }
static const symbol s_40 [] = { 'l', 'i', 'e' }
static const symbol s_41 [] = { 't', 'i', 'e' }
static const symbol s_42 [] = { 'i', 'd', 'l' }
static const symbol s_43 [] = { 'g', 'e', 'n', 't', 'l' }
static const symbol s_44 [] = { 'u', 'g', 'l', 'i' }
static const symbol s_45 [] = { 'e', 'a', 'r', 'l', 'i' }
static const symbol s_46 [] = { 'o', 'n', 'l', 'i' }
static const symbol s_47 [] = { 's', 'i', 'n', 'g', 'l' }
static const symbol s_48 [] = { 'Y' }
static const symbol s_49 [] = { 'y' }
Function Documentation
void english_UTF_8_close_env (struct SN_env * z)
struct SN_env* english_UTF_8_create_env (void) [read]
int english_UTF_8_stem (struct SN_env * z)
static int r_exception1 (struct SN_env * z) [static]
Definition at line 906 of file stem_UTF_8_english.cpp.
References SN_env::bra, SN_env::c, find_among(), SN_env::ket, SN_env::l, SN_env::p, s_37, s_38, s_39, s_40, s_41, s_42, s_43, s_44, s_45, s_46, s_47, and slice_from_s().
Referenced by english_UTF_8_stem().
static int r_exception2 (struct SN_env * z) [static]
Definition at line 897 of file stem_UTF_8_english.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::ket, SN_env::lb, and SN_env::p.
Referenced by english_UTF_8_stem().
static int r_mark_regions (struct SN_env * z) [static]
Definition at line 427 of file stem_UTF_8_english.cpp.
References SN_env::c, find_among(), g_v, SN_env::I, in_grouping_U(), SN_env::l, out_grouping_U(), and SN_env::p.
static int r_postlude (struct SN_env * z) [static]
Definition at line 975 of file stem_UTF_8_english.cpp.
References SN_env::B, SN_env::bra, SN_env::c, eq_s(), SN_env::ket, SN_env::l, SN_env::p, s_48, s_49, skip_utf8(), and slice_from_s().
static int r_prelude (struct SN_env * z) [static]
Definition at line 372 of file stem_UTF_8_english.cpp.
References SN_env::B, SN_env::bra, SN_env::c, eq_s(), g_v, in_grouping_U(), SN_env::ket, SN_env::l, SN_env::p, s_0, s_1, s_2, s_3, s_4, skip_utf8(), slice_del(), and slice_from_s().
static int r_R1 (struct SN_env * z) [static]
Definition at line 483 of file stem_UTF_8_english.cpp.
References SN_env::c, and SN_env::I.
static int r_R2 (struct SN_env * z) [static]
Definition at line 488 of file stem_UTF_8_english.cpp.
References SN_env::c, and SN_env::I.
static int r_shortv (struct SN_env * z) [static]
Definition at line 467 of file stem_UTF_8_english.cpp.
References SN_env::c, g_v, g_v_WXY, in_grouping_b_U(), SN_env::l, SN_env::lb, and out_grouping_b_U().
Referenced by r_Step_1b(), and r_Step_5().
static int r_Step_1a (struct SN_env * z) [static]
Definition at line 493 of file stem_UTF_8_english.cpp.
References SN_env::bra, SN_env::c, find_among_b(), g_v, SN_env::ket, SN_env::l, SN_env::lb, out_grouping_b_U(), SN_env::p, s_5, s_6, s_7, skip_utf8(), slice_del(), and slice_from_s().
Referenced by english_UTF_8_stem().
static int r_Step_1b (struct SN_env * z) [static]
Definition at line 560 of file stem_UTF_8_english.cpp.
References SN_env::bra, SN_env::c, find_among_b(), g_v, SN_env::I, insert_s(), SN_env::ket, SN_env::l, SN_env::lb, out_grouping_b_U(), SN_env::p, r_R1(), r_shortv(), s_10, s_8, s_9, skip_utf8(), slice_del(), and slice_from_s().
Referenced by english_UTF_8_stem().
static int r_Step_1c (struct SN_env * z) [static]
Definition at line 637 of file stem_UTF_8_english.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), g_v, SN_env::ket, SN_env::l, SN_env::lb, out_grouping_b_U(), s_11, s_12, s_13, and slice_from_s().
Referenced by english_UTF_8_stem().
static int r_Step_2 (struct SN_env * z) [static]
Definition at line 661 of file stem_UTF_8_english.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), g_valid_LI, in_grouping_b_U(), SN_env::ket, SN_env::lb, SN_env::p, r_R1(), s_14, s_15, s_16, s_17, s_18, s_19, s_20, s_21, s_22, s_23, s_24, s_25, s_26, s_27, s_28, s_29, slice_del(), and slice_from_s().
Referenced by english_UTF_8_stem().
static int r_Step_3 (struct SN_env * z) [static]
Definition at line 760 of file stem_UTF_8_english.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::ket, SN_env::lb, SN_env::p, r_R1(), r_R2(), s_30, s_31, s_32, s_33, slice_del(), and slice_from_s().
Referenced by english_UTF_8_stem().
static int r_Step_4 (struct SN_env * z) [static]
Definition at line 811 of file stem_UTF_8_english.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), SN_env::ket, SN_env::l, SN_env::lb, SN_env::p, r_R2(), s_34, s_35, and slice_del().
Referenced by english_UTF_8_stem().
static int r_Step_5 (struct SN_env * z) [static]
Definition at line 846 of file stem_UTF_8_english.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), SN_env::ket, SN_env::l, SN_env::lb, SN_env::p, r_R1(), r_R2(), r_shortv(), s_36, and slice_del().
Referenced by english_UTF_8_stem().
Variable Documentation
struct among a_0[3] [static]
Initial value:
{
 { 5, s_0_0, -1, -1, 0},
 { 6, s_0_1, -1, -1, 0},
 { 5, s_0_2, -1, -1, 0}
}
Definition at line 45 of file stem_UTF_8_english.cpp.
struct among a_1[3] [static]
Initial value:
{
 { 1, s_1_0, -1, 1, 0},
 { 3, s_1_1, 0, 1, 0},
 { 2, s_1_2, -1, 1, 0}
}
Definition at line 56 of file stem_UTF_8_english.cpp.
struct among a_10[18] [static]
Initial value:
{
 { 5, s_10_0, -1, -1, 0},
 { 5, s_10_1, -1, -1, 0},
 { 4, s_10_2, -1, -1, 0},
 { 6, s_10_3, -1, -1, 0},
 { 5, s_10_4, -1, 3, 0},
 { 5, s_10_5, -1, 9, 0},
 { 6, s_10_6, -1, 7, 0},
 { 4, s_10_7, -1, -1, 0},
 { 4, s_10_8, -1, 6, 0},
 { 5, s_10_9, -1, 4, 0},
 { 4, s_10_10, -1, -1, 0},
 { 4, s_10_11, -1, 10, 0},
 { 6, s_10_12, -1, 11, 0},
 { 5, s_10_13, -1, 2, 0},
 { 4, s_10_14, -1, 1, 0},
 { 3, s_10_15, -1, -1, 0},
 { 5, s_10_16, -1, 5, 0},
 { 4, s_10_17, -1, 8, 0}
}
Definition at line 293 of file stem_UTF_8_english.cpp.
struct among a_2[6] [static]
Initial value:
{
 { 3, s_2_0, -1, 2, 0},
 { 1, s_2_1, -1, 3, 0},
 { 3, s_2_2, 1, 2, 0},
 { 4, s_2_3, 1, 1, 0},
 { 2, s_2_4, 1, -1, 0},
 { 2, s_2_5, 1, -1, 0}
}
Definition at line 70 of file stem_UTF_8_english.cpp.
struct among a_3[13] [static]
Initial value:
{
 { 0, 0, -1, 3, 0},
 { 2, s_3_1, 0, 2, 0},
 { 2, s_3_2, 0, 2, 0},
 { 2, s_3_3, 0, 2, 0},
 { 2, s_3_4, 0, 2, 0},
 { 2, s_3_5, 0, 1, 0},
 { 2, s_3_6, 0, 2, 0},
 { 2, s_3_7, 0, 2, 0},
 { 2, s_3_8, 0, 2, 0},
 { 2, s_3_9, 0, 2, 0},
 { 2, s_3_10, 0, 1, 0},
 { 2, s_3_11, 0, 2, 0},
 { 2, s_3_12, 0, 1, 0}
}
Definition at line 93 of file stem_UTF_8_english.cpp.
struct among a_4[6] [static]
Initial value:
{
 { 2, s_4_0, -1, 2, 0},
 { 3, s_4_1, 0, 1, 0},
 { 3, s_4_2, -1, 2, 0},
 { 4, s_4_3, -1, 2, 0},
 { 5, s_4_4, 3, 1, 0},
 { 5, s_4_5, -1, 2, 0}
}
Definition at line 117 of file stem_UTF_8_english.cpp.
struct among a_5[24] [static]
Initial value:
{
 { 4, s_5_0, -1, 3, 0},
 { 4, s_5_1, -1, 2, 0},
 { 3, s_5_2, -1, 13, 0},
 { 2, s_5_3, -1, 16, 0},
 { 3, s_5_4, 3, 12, 0},
 { 4, s_5_5, 4, 4, 0},
 { 4, s_5_6, 3, 8, 0},
 { 5, s_5_7, 3, 14, 0},
 { 6, s_5_8, 3, 15, 0},
 { 5, s_5_9, 3, 10, 0},
 { 5, s_5_10, 3, 5, 0},
 { 5, s_5_11, -1, 8, 0},
 { 6, s_5_12, -1, 12, 0},
 { 5, s_5_13, -1, 11, 0},
 { 6, s_5_14, -1, 1, 0},
 { 7, s_5_15, 14, 7, 0},
 { 5, s_5_16, -1, 8, 0},
 { 5, s_5_17, -1, 7, 0},
 { 7, s_5_18, 17, 6, 0},
 { 4, s_5_19, -1, 6, 0},
 { 4, s_5_20, -1, 7, 0},
 { 7, s_5_21, -1, 11, 0},
 { 7, s_5_22, -1, 9, 0},
 { 7, s_5_23, -1, 10, 0}
}
Definition at line 152 of file stem_UTF_8_english.cpp.
struct among a_6[9] [static]
Initial value:
{
 { 5, s_6_0, -1, 4, 0},
 { 5, s_6_1, -1, 6, 0},
 { 5, s_6_2, -1, 3, 0},
 { 5, s_6_3, -1, 4, 0},
 { 4, s_6_4, -1, 4, 0},
 { 6, s_6_5, -1, 1, 0},
 { 7, s_6_6, 5, 2, 0},
 { 3, s_6_7, -1, 5, 0},
 { 4, s_6_8, -1, 5, 0}
}
Definition at line 190 of file stem_UTF_8_english.cpp.
struct among a_7[18] [static]
Initial value:
{
 { 2, s_7_0, -1, 1, 0},
 { 4, s_7_1, -1, 1, 0},
 { 4, s_7_2, -1, 1, 0},
 { 4, s_7_3, -1, 1, 0},
 { 4, s_7_4, -1, 1, 0},
 { 3, s_7_5, -1, 1, 0},
 { 3, s_7_6, -1, 1, 0},
 { 3, s_7_7, -1, 1, 0},
 { 3, s_7_8, -1, 1, 0},
 { 2, s_7_9, -1, 1, 0},
 { 3, s_7_10, -1, 1, 0},
 { 3, s_7_11, -1, 2, 0},
 { 2, s_7_12, -1, 1, 0},
 { 3, s_7_13, -1, 1, 0},
 { 3, s_7_14, -1, 1, 0},
 { 3, s_7_15, -1, 1, 0},
 { 4, s_7_16, 15, 1, 0},
 { 5, s_7_17, 16, 1, 0}
}
Definition at line 222 of file stem_UTF_8_english.cpp.
struct among a_8[2] [static]
Initial value:
{
 { 1, s_8_0, -1, 1, 0},
 { 1, s_8_1, -1, 2, 0}
}
Definition at line 247 of file stem_UTF_8_english.cpp.
struct among a_9[8] [static]
Initial value:
{
 { 7, s_9_0, -1, -1, 0},
 { 7, s_9_1, -1, -1, 0},
 { 6, s_9_2, -1, -1, 0},
 { 7, s_9_3, -1, -1, 0},
 { 6, s_9_4, -1, -1, 0},
 { 7, s_9_5, -1, -1, 0},
 { 7, s_9_6, -1, -1, 0},
 { 6, s_9_7, -1, -1, 0}
}
Definition at line 262 of file stem_UTF_8_english.cpp.
const unsigned char g_v[] = { 17, 65, 16, 1 } [static]
Definition at line 315 of file stem_UTF_8_english.cpp.
const unsigned char g_v_WXY[] = { 1, 17, 65, 208, 1 } [static]
Definition at line 317 of file stem_UTF_8_english.cpp.
Referenced by r_shortv().
const unsigned char g_valid_LI[] = { 55, 141, 2 } [static]
Definition at line 319 of file stem_UTF_8_english.cpp.
Referenced by r_Step_2().
const symbol s_0[] = { '\'' } [static]
Definition at line 321 of file stem_UTF_8_english.cpp.
const symbol s_0_0[5] = { 'a', 'r', 's', 'e', 'n' } [static]
Definition at line 41 of file stem_UTF_8_english.cpp.
const symbol s_0_1[6] = { 'c', 'o', 'm', 'm', 'u', 'n' } [static]
Definition at line 42 of file stem_UTF_8_english.cpp.
const symbol s_0_2[5] = { 'g', 'e', 'n', 'e', 'r' } [static]
Definition at line 43 of file stem_UTF_8_english.cpp.
const symbol s_1[] = { 'y' } [static]
Definition at line 322 of file stem_UTF_8_english.cpp.
const symbol s_10[] = { 'e' } [static]
Definition at line 331 of file stem_UTF_8_english.cpp.
const symbol s_10_0[5] = { 'a', 'n', 'd', 'e', 's' } [static]
Definition at line 274 of file stem_UTF_8_english.cpp.
const symbol s_10_1[5] = { 'a', 't', 'l', 'a', 's' } [static]
Definition at line 275 of file stem_UTF_8_english.cpp.
const symbol s_10_10[4] = { 'n', 'e', 'w', 's' } [static]
Definition at line 284 of file stem_UTF_8_english.cpp.
const symbol s_10_11[4] = { 'o', 'n', 'l', 'y' } [static]
Definition at line 285 of file stem_UTF_8_english.cpp.
const symbol s_10_12[6] = { 's', 'i', 'n', 'g', 'l', 'y' } [static]
Definition at line 286 of file stem_UTF_8_english.cpp.
const symbol s_10_13[5] = { 's', 'k', 'i', 'e', 's' } [static]
Definition at line 287 of file stem_UTF_8_english.cpp.
const symbol s_10_14[4] = { 's', 'k', 'i', 's' } [static]
Definition at line 288 of file stem_UTF_8_english.cpp.
const symbol s_10_15[3] = { 's', 'k', 'y' } [static]
Definition at line 289 of file stem_UTF_8_english.cpp.
const symbol s_10_16[5] = { 't', 'y', 'i', 'n', 'g' } [static]
Definition at line 290 of file stem_UTF_8_english.cpp.
const symbol s_10_17[4] = { 'u', 'g', 'l', 'y' } [static]
Definition at line 291 of file stem_UTF_8_english.cpp.
const symbol s_10_2[4] = { 'b', 'i', 'a', 's' } [static]
Definition at line 276 of file stem_UTF_8_english.cpp.
const symbol s_10_3[6] = { 'c', 'o', 's', 'm', 'o', 's' } [static]
Definition at line 277 of file stem_UTF_8_english.cpp.
const symbol s_10_4[5] = { 'd', 'y', 'i', 'n', 'g' } [static]
Definition at line 278 of file stem_UTF_8_english.cpp.
const symbol s_10_5[5] = { 'e', 'a', 'r', 'l', 'y' } [static]
Definition at line 279 of file stem_UTF_8_english.cpp.
const symbol s_10_6[6] = { 'g', 'e', 'n', 't', 'l', 'y' } [static]
Definition at line 280 of file stem_UTF_8_english.cpp.
const symbol s_10_7[4] = { 'h', 'o', 'w', 'e' } [static]
Definition at line 281 of file stem_UTF_8_english.cpp.
const symbol s_10_8[4] = { 'i', 'd', 'l', 'y' } [static]
Definition at line 282 of file stem_UTF_8_english.cpp.
const symbol s_10_9[5] = { 'l', 'y', 'i', 'n', 'g' } [static]
Definition at line 283 of file stem_UTF_8_english.cpp.
const symbol s_11[] = { 'y' } [static]
Definition at line 332 of file stem_UTF_8_english.cpp.
const symbol s_12[] = { 'Y' } [static]
Definition at line 333 of file stem_UTF_8_english.cpp.
const symbol s_13[] = { 'i' } [static]
Definition at line 334 of file stem_UTF_8_english.cpp.
const symbol s_14[] = { 't', 'i', 'o', 'n' } [static]
Definition at line 335 of file stem_UTF_8_english.cpp.
const symbol s_15[] = { 'e', 'n', 'c', 'e' } [static]
Definition at line 336 of file stem_UTF_8_english.cpp.
const symbol s_16[] = { 'a', 'n', 'c', 'e' } [static]
Definition at line 337 of file stem_UTF_8_english.cpp.
const symbol s_17[] = { 'a', 'b', 'l', 'e' } [static]
Definition at line 338 of file stem_UTF_8_english.cpp.
const symbol s_18[] = { 'e', 'n', 't' } [static]
Definition at line 339 of file stem_UTF_8_english.cpp.
const symbol s_19[] = { 'i', 'z', 'e' } [static]
Definition at line 340 of file stem_UTF_8_english.cpp.
const symbol s_1_0[1] = { '\'' } [static]
Definition at line 52 of file stem_UTF_8_english.cpp.
const symbol s_1_1[3] = { '\'', 's', '\'' } [static]
Definition at line 53 of file stem_UTF_8_english.cpp.
const symbol s_1_2[2] = { '\'', 's' } [static]
Definition at line 54 of file stem_UTF_8_english.cpp.
const symbol s_2[] = { 'Y' } [static]
Definition at line 323 of file stem_UTF_8_english.cpp.
const symbol s_20[] = { 'a', 't', 'e' } [static]
Definition at line 341 of file stem_UTF_8_english.cpp.
const symbol s_21[] = { 'a', 'l' } [static]
Definition at line 342 of file stem_UTF_8_english.cpp.
const symbol s_22[] = { 'f', 'u', 'l' } [static]
Definition at line 343 of file stem_UTF_8_english.cpp.
Referenced by r_append_U_to_stems_ending_with_d_or_g(), r_sing_owner(), r_standard_suffix(), r_Step_2(), and r_verb_suffix().
const symbol s_23[] = { 'o', 'u', 's' } [static]
Definition at line 344 of file stem_UTF_8_english.cpp.
Referenced by r_append_U_to_stems_ending_with_d_or_g(), r_sing_owner(), r_standard_suffix(), and r_Step_2().
const symbol s_24[] = { 'i', 'v', 'e' } [static]
Definition at line 345 of file stem_UTF_8_english.cpp.
Referenced by r_append_U_to_stems_ending_with_d_or_g(), r_plur_owner(), r_standard_suffix(), and r_Step_2().
const symbol s_25[] = { 'b', 'l', 'e' } [static]
Definition at line 346 of file stem_UTF_8_english.cpp.
Referenced by r_append_U_to_stems_ending_with_d_or_g(), r_plur_owner(), r_standard_suffix(), and r_Step_2().
const symbol s_26[] = { 'l' } [static]
Definition at line 347 of file stem_UTF_8_english.cpp.
Referenced by r_append_U_to_stems_ending_with_d_or_g(), r_plur_owner(), r_standard_suffix(), and r_Step_2().
const symbol s_27[] = { 'o', 'g' } [static]
Definition at line 348 of file stem_UTF_8_english.cpp.
Referenced by r_append_U_to_stems_ending_with_d_or_g(), r_plur_owner(), r_standard_suffix(), and r_Step_2().
const symbol s_28[] = { 'f', 'u', 'l' } [static]
Definition at line 349 of file stem_UTF_8_english.cpp.
Referenced by r_append_U_to_stems_ending_with_d_or_g(), r_plur_owner(), r_standard_suffix(), and r_Step_2().
const symbol s_29[] = { 'l', 'e', 's', 's' } [static]
Definition at line 350 of file stem_UTF_8_english.cpp.
Referenced by r_append_U_to_stems_ending_with_d_or_g(), r_plur_owner(), r_standard_suffix(), and r_Step_2().
const symbol s_2_0[3] = { 'i', 'e', 'd' } [static]
Definition at line 63 of file stem_UTF_8_english.cpp.
const symbol s_2_1[1] = { 's' } [static]
Definition at line 64 of file stem_UTF_8_english.cpp.
const symbol s_2_2[3] = { 'i', 'e', 's' } [static]
Definition at line 65 of file stem_UTF_8_english.cpp.
const symbol s_2_3[4] = { 's', 's', 'e', 's' } [static]
Definition at line 66 of file stem_UTF_8_english.cpp.
const symbol s_2_4[2] = { 's', 's' } [static]
Definition at line 67 of file stem_UTF_8_english.cpp.
const symbol s_2_5[2] = { 'u', 's' } [static]
Definition at line 68 of file stem_UTF_8_english.cpp.
const symbol s_3[] = { 'y' } [static]
Definition at line 324 of file stem_UTF_8_english.cpp.
const symbol s_30[] = { 't', 'i', 'o', 'n' } [static]
Definition at line 351 of file stem_UTF_8_english.cpp.
Referenced by r_append_U_to_stems_ending_with_d_or_g(), r_plur_owner(), r_standard_suffix(), and r_Step_3().
const symbol s_31[] = { 'a', 't', 'e' } [static]
Definition at line 352 of file stem_UTF_8_english.cpp.
Referenced by r_append_U_to_stems_ending_with_d_or_g(), r_plur_owner(), r_standard_suffix(), and r_Step_3().
const symbol s_32[] = { 'a', 'l' } [static]
Definition at line 353 of file stem_UTF_8_english.cpp.
Referenced by r_append_U_to_stems_ending_with_d_or_g(), r_plur_owner(), r_Step_3(), and r_verb_suffix().
const symbol s_33[] = { 'i', 'c' } [static]
Definition at line 354 of file stem_UTF_8_english.cpp.
Referenced by r_append_U_to_stems_ending_with_d_or_g(), r_plur_owner(), r_residual_suffix(), and r_Step_3().
const symbol s_34[] = { 's' } [static]
Definition at line 355 of file stem_UTF_8_english.cpp.
Referenced by r_is_reserved_word(), r_plur_owner(), r_residual_suffix(), and r_Step_4().
const symbol s_35[] = { 't' } [static]
Definition at line 356 of file stem_UTF_8_english.cpp.
Referenced by r_is_reserved_word(), r_plur_owner(), r_residual_suffix(), and r_Step_4().
const symbol s_36[] = { 'l' } [static]
Definition at line 357 of file stem_UTF_8_english.cpp.
Referenced by r_residual_suffix(), and r_Step_5().
const symbol s_37[] = { 's', 'k', 'i' } [static]
Definition at line 358 of file stem_UTF_8_english.cpp.
Referenced by r_exception1(), and r_residual_suffix().
const symbol s_38[] = { 's', 'k', 'y' } [static]
Definition at line 359 of file stem_UTF_8_english.cpp.
Referenced by r_exception1(), and r_un_accent().
const symbol s_39[] = { 'd', 'i', 'e' } [static]
Definition at line 360 of file stem_UTF_8_english.cpp.
Referenced by r_exception1(), and r_un_accent().
const symbol s_3_1[2] = { 'b', 'b' } [static]
Definition at line 80 of file stem_UTF_8_english.cpp.
const symbol s_3_10[2] = { 'a', 't' } [static]
Definition at line 89 of file stem_UTF_8_english.cpp.
const symbol s_3_11[2] = { 't', 't' } [static]
Definition at line 90 of file stem_UTF_8_english.cpp.
const symbol s_3_12[2] = { 'i', 'z' } [static]
Definition at line 91 of file stem_UTF_8_english.cpp.
const symbol s_3_2[2] = { 'd', 'd' } [static]
Definition at line 81 of file stem_UTF_8_english.cpp.
const symbol s_3_3[2] = { 'f', 'f' } [static]
Definition at line 82 of file stem_UTF_8_english.cpp.
const symbol s_3_4[2] = { 'g', 'g' } [static]
Definition at line 83 of file stem_UTF_8_english.cpp.
const symbol s_3_5[2] = { 'b', 'l' } [static]
Definition at line 84 of file stem_UTF_8_english.cpp.
const symbol s_3_6[2] = { 'm', 'm' } [static]
Definition at line 85 of file stem_UTF_8_english.cpp.
const symbol s_3_7[2] = { 'n', 'n' } [static]
Definition at line 86 of file stem_UTF_8_english.cpp.
const symbol s_3_8[2] = { 'p', 'p' } [static]
Definition at line 87 of file stem_UTF_8_english.cpp.
const symbol s_3_9[2] = { 'r', 'r' } [static]
Definition at line 88 of file stem_UTF_8_english.cpp.
const symbol s_4[] = { 'Y' } [static]
Definition at line 325 of file stem_UTF_8_english.cpp.
const symbol s_40[] = { 'l', 'i', 'e' } [static]
Definition at line 361 of file stem_UTF_8_english.cpp.
Referenced by r_exception1(), and r_un_accent().
const symbol s_41[] = { 't', 'i', 'e' } [static]
Definition at line 362 of file stem_UTF_8_english.cpp.
Referenced by french_UTF_8_stem(), and r_exception1().
const symbol s_42[] = { 'i', 'd', 'l' } [static]
Definition at line 363 of file stem_UTF_8_english.cpp.
Referenced by french_UTF_8_stem(), and r_exception1().
const symbol s_43[] = { 'g', 'e', 'n', 't', 'l' } [static]
Definition at line 364 of file stem_UTF_8_english.cpp.
Referenced by french_UTF_8_stem(), and r_exception1().
const symbol s_44[] = { 'u', 'g', 'l', 'i' } [static]
Definition at line 365 of file stem_UTF_8_english.cpp.
Referenced by french_UTF_8_stem(), and r_exception1().
const symbol s_45[] = { 'e', 'a', 'r', 'l', 'i' } [static]
Definition at line 366 of file stem_UTF_8_english.cpp.
Referenced by r_exception1().
const symbol s_46[] = { 'o', 'n', 'l', 'i' } [static]
Definition at line 367 of file stem_UTF_8_english.cpp.
Referenced by r_exception1().
const symbol s_47[] = { 's', 'i', 'n', 'g', 'l' } [static]
Definition at line 368 of file stem_UTF_8_english.cpp.
Referenced by r_exception1().
const symbol s_48[] = { 'Y' } [static]
Definition at line 369 of file stem_UTF_8_english.cpp.
Referenced by r_postlude().
const symbol s_49[] = { 'y' } [static]
Definition at line 370 of file stem_UTF_8_english.cpp.
Referenced by r_postlude().
const symbol s_4_0[2] = { 'e', 'd' } [static]
Definition at line 110 of file stem_UTF_8_english.cpp.
const symbol s_4_1[3] = { 'e', 'e', 'd' } [static]
Definition at line 111 of file stem_UTF_8_english.cpp.
const symbol s_4_2[3] = { 'i', 'n', 'g' } [static]
Definition at line 112 of file stem_UTF_8_english.cpp.
const symbol s_4_3[4] = { 'e', 'd', 'l', 'y' } [static]
Definition at line 113 of file stem_UTF_8_english.cpp.
const symbol s_4_4[5] = { 'e', 'e', 'd', 'l', 'y' } [static]
Definition at line 114 of file stem_UTF_8_english.cpp.
const symbol s_4_5[5] = { 'i', 'n', 'g', 'l', 'y' } [static]
Definition at line 115 of file stem_UTF_8_english.cpp.
const symbol s_5[] = { 's', 's' } [static]
Definition at line 326 of file stem_UTF_8_english.cpp.
const symbol s_5_0[4] = { 'a', 'n', 'c', 'i' } [static]
Definition at line 127 of file stem_UTF_8_english.cpp.
const symbol s_5_1[4] = { 'e', 'n', 'c', 'i' } [static]
Definition at line 128 of file stem_UTF_8_english.cpp.
const symbol s_5_10[5] = { 'e', 'n', 't', 'l', 'i' } [static]
Definition at line 137 of file stem_UTF_8_english.cpp.
const symbol s_5_11[5] = { 'a', 'l', 'i', 't', 'i' } [static]
Definition at line 138 of file stem_UTF_8_english.cpp.
const symbol s_5_12[6] = { 'b', 'i', 'l', 'i', 't', 'i' } [static]
Definition at line 139 of file stem_UTF_8_english.cpp.
const symbol s_5_13[5] = { 'i', 'v', 'i', 't', 'i' } [static]
Definition at line 140 of file stem_UTF_8_english.cpp.
const symbol s_5_14[6] = { 't', 'i', 'o', 'n', 'a', 'l' } [static]
Definition at line 141 of file stem_UTF_8_english.cpp.
const symbol s_5_15[7] = { 'a', 't', 'i', 'o', 'n', 'a', 'l' } [static]
Definition at line 142 of file stem_UTF_8_english.cpp.
const symbol s_5_16[5] = { 'a', 'l', 'i', 's', 'm' } [static]
Definition at line 143 of file stem_UTF_8_english.cpp.
const symbol s_5_17[5] = { 'a', 't', 'i', 'o', 'n' } [static]
Definition at line 144 of file stem_UTF_8_english.cpp.
const symbol s_5_18[7] = { 'i', 'z', 'a', 't', 'i', 'o', 'n' } [static]
Definition at line 145 of file stem_UTF_8_english.cpp.
const symbol s_5_19[4] = { 'i', 'z', 'e', 'r' } [static]
Definition at line 146 of file stem_UTF_8_english.cpp.
const symbol s_5_2[3] = { 'o', 'g', 'i' } [static]
Definition at line 129 of file stem_UTF_8_english.cpp.
const symbol s_5_20[4] = { 'a', 't', 'o', 'r' } [static]
Definition at line 147 of file stem_UTF_8_english.cpp.
const symbol s_5_21[7] = { 'i', 'v', 'e', 'n', 'e', 's', 's' } [static]
Definition at line 148 of file stem_UTF_8_english.cpp.
const symbol s_5_22[7] = { 'f', 'u', 'l', 'n', 'e', 's', 's' } [static]
Definition at line 149 of file stem_UTF_8_english.cpp.
const symbol s_5_23[7] = { 'o', 'u', 's', 'n', 'e', 's', 's' } [static]
Definition at line 150 of file stem_UTF_8_english.cpp.
const symbol s_5_3[2] = { 'l', 'i' } [static]
Definition at line 130 of file stem_UTF_8_english.cpp.
const symbol s_5_4[3] = { 'b', 'l', 'i' } [static]
Definition at line 131 of file stem_UTF_8_english.cpp.
const symbol s_5_5[4] = { 'a', 'b', 'l', 'i' } [static]
Definition at line 132 of file stem_UTF_8_english.cpp.
const symbol s_5_6[4] = { 'a', 'l', 'l', 'i' } [static]
Definition at line 133 of file stem_UTF_8_english.cpp.
const symbol s_5_7[5] = { 'f', 'u', 'l', 'l', 'i' } [static]
Definition at line 134 of file stem_UTF_8_english.cpp.
const symbol s_5_8[6] = { 'l', 'e', 's', 's', 'l', 'i' } [static]
Definition at line 135 of file stem_UTF_8_english.cpp.
const symbol s_5_9[5] = { 'o', 'u', 's', 'l', 'i' } [static]
Definition at line 136 of file stem_UTF_8_english.cpp.
const symbol s_6[] = { 'i' } [static]
Definition at line 327 of file stem_UTF_8_english.cpp.
const symbol s_6_0[5] = { 'i', 'c', 'a', 't', 'e' } [static]
Definition at line 180 of file stem_UTF_8_english.cpp.
const symbol s_6_1[5] = { 'a', 't', 'i', 'v', 'e' } [static]
Definition at line 181 of file stem_UTF_8_english.cpp.
const symbol s_6_2[5] = { 'a', 'l', 'i', 'z', 'e' } [static]
Definition at line 182 of file stem_UTF_8_english.cpp.
const symbol s_6_3[5] = { 'i', 'c', 'i', 't', 'i' } [static]
Definition at line 183 of file stem_UTF_8_english.cpp.
const symbol s_6_4[4] = { 'i', 'c', 'a', 'l' } [static]
Definition at line 184 of file stem_UTF_8_english.cpp.
const symbol s_6_5[6] = { 't', 'i', 'o', 'n', 'a', 'l' } [static]
Definition at line 185 of file stem_UTF_8_english.cpp.
const symbol s_6_6[7] = { 'a', 't', 'i', 'o', 'n', 'a', 'l' } [static]
Definition at line 186 of file stem_UTF_8_english.cpp.
const symbol s_6_7[3] = { 'f', 'u', 'l' } [static]
Definition at line 187 of file stem_UTF_8_english.cpp.
const symbol s_6_8[4] = { 'n', 'e', 's', 's' } [static]
Definition at line 188 of file stem_UTF_8_english.cpp.
const symbol s_7[] = { 'i', 'e' } [static]
Definition at line 328 of file stem_UTF_8_english.cpp.
const symbol s_7_0[2] = { 'i', 'c' } [static]
Definition at line 203 of file stem_UTF_8_english.cpp.
const symbol s_7_1[4] = { 'a', 'n', 'c', 'e' } [static]
Definition at line 204 of file stem_UTF_8_english.cpp.
const symbol s_7_10[3] = { 'i', 's', 'm' } [static]
Definition at line 213 of file stem_UTF_8_english.cpp.
const symbol s_7_11[3] = { 'i', 'o', 'n' } [static]
Definition at line 214 of file stem_UTF_8_english.cpp.
const symbol s_7_12[2] = { 'e', 'r' } [static]
Definition at line 215 of file stem_UTF_8_english.cpp.
const symbol s_7_13[3] = { 'o', 'u', 's' } [static]
Definition at line 216 of file stem_UTF_8_english.cpp.
const symbol s_7_14[3] = { 'a', 'n', 't' } [static]
Definition at line 217 of file stem_UTF_8_english.cpp.
const symbol s_7_15[3] = { 'e', 'n', 't' } [static]
Definition at line 218 of file stem_UTF_8_english.cpp.
const symbol s_7_16[4] = { 'm', 'e', 'n', 't' } [static]
Definition at line 219 of file stem_UTF_8_english.cpp.
const symbol s_7_17[5] = { 'e', 'm', 'e', 'n', 't' } [static]
Definition at line 220 of file stem_UTF_8_english.cpp.
const symbol s_7_2[4] = { 'e', 'n', 'c', 'e' } [static]
Definition at line 205 of file stem_UTF_8_english.cpp.
const symbol s_7_3[4] = { 'a', 'b', 'l', 'e' } [static]
Definition at line 206 of file stem_UTF_8_english.cpp.
const symbol s_7_4[4] = { 'i', 'b', 'l', 'e' } [static]
Definition at line 207 of file stem_UTF_8_english.cpp.
const symbol s_7_5[3] = { 'a', 't', 'e' } [static]
Definition at line 208 of file stem_UTF_8_english.cpp.
const symbol s_7_6[3] = { 'i', 'v', 'e' } [static]
Definition at line 209 of file stem_UTF_8_english.cpp.
const symbol s_7_7[3] = { 'i', 'z', 'e' } [static]
Definition at line 210 of file stem_UTF_8_english.cpp.
const symbol s_7_8[3] = { 'i', 't', 'i' } [static]
Definition at line 211 of file stem_UTF_8_english.cpp.
const symbol s_7_9[2] = { 'a', 'l' } [static]
Definition at line 212 of file stem_UTF_8_english.cpp.
const symbol s_8[] = { 'e', 'e' } [static]
Definition at line 329 of file stem_UTF_8_english.cpp.
const symbol s_8_0[1] = { 'e' } [static]
Definition at line 244 of file stem_UTF_8_english.cpp.
const symbol s_8_1[1] = { 'l' } [static]
Definition at line 245 of file stem_UTF_8_english.cpp.
const symbol s_9[] = { 'e' } [static]
Definition at line 330 of file stem_UTF_8_english.cpp.
const symbol s_9_0[7] = { 's', 'u', 'c', 'c', 'e', 'e', 'd' } [static]
Definition at line 253 of file stem_UTF_8_english.cpp.
const symbol s_9_1[7] = { 'p', 'r', 'o', 'c', 'e', 'e', 'd' } [static]
Definition at line 254 of file stem_UTF_8_english.cpp.
const symbol s_9_2[6] = { 'e', 'x', 'c', 'e', 'e', 'd' } [static]
Definition at line 255 of file stem_UTF_8_english.cpp.
const symbol s_9_3[7] = { 'c', 'a', 'n', 'n', 'i', 'n', 'g' } [static]
Definition at line 256 of file stem_UTF_8_english.cpp.
const symbol s_9_4[6] = { 'i', 'n', 'n', 'i', 'n', 'g' } [static]
Definition at line 257 of file stem_UTF_8_english.cpp.
const symbol s_9_5[7] = { 'e', 'a', 'r', 'r', 'i', 'n', 'g' } [static]
Definition at line 258 of file stem_UTF_8_english.cpp.
const symbol s_9_6[7] = { 'h', 'e', 'r', 'r', 'i', 'n', 'g' } [static]
Definition at line 259 of file stem_UTF_8_english.cpp.
const symbol s_9_7[6] = { 'o', 'u', 't', 'i', 'n', 'g' } [static]
Definition at line 260 of file stem_UTF_8_english.cpp.