/disk/workspace-cpp/la-manager/include/stem/stem_UTF_8_french.h File Reference
Functions
struct SN_env * french_UTF_8_create_env (void)
void french_UTF_8_close_env (struct SN_env *z)
int french_UTF_8_stem (struct SN_env *z)
Function Documentation
void french_UTF_8_close_env (struct SN_env * z)
Definition at line 1256 of file stem_UTF_8_french.cpp.
References SN_close_env().
struct SN_env * french_UTF_8_create_env (void) [read]
Definition at line 1254 of file stem_UTF_8_french.cpp.
References SN_create_env().
int french_UTF_8_stem (struct SN_env * z)
Definition at line 1148 of file stem_UTF_8_french.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), SN_env::ket, SN_env::l, SN_env::lb, r_i_verb_suffix(), r_mark_regions(), r_postlude(), r_prelude(), r_residual_suffix(), r_standard_suffix(), r_un_accent(), r_un_double(), r_verb_suffix(), s_41, s_42, s_43, s_44, and slice_from_s().