/disk/workspace-cpp/la-manager/include/stem/stem_UTF_8_turkish.h File Reference
Functions
struct SN_env * turkish_UTF_8_create_env (void)
void turkish_UTF_8_close_env (struct SN_env *z)
int turkish_UTF_8_stem (struct SN_env *z)
Function Documentation
void turkish_UTF_8_close_env (struct SN_env * z)
Definition at line 2205 of file stem_UTF_8_turkish.cpp.
References SN_close_env().
struct SN_env * turkish_UTF_8_create_env (void) [read]
Definition at line 2203 of file stem_UTF_8_turkish.cpp.
References SN_create_env().
int turkish_UTF_8_stem (struct SN_env * z)
Definition at line 2171 of file stem_UTF_8_turkish.cpp.
References SN_env::B, SN_env::c, SN_env::l, SN_env::lb, r_more_than_one_syllable_word(), r_postlude(), r_stem_nominal_verb_suffixes(), and r_stem_noun_suffixes().