/disk/workspace-cpp/la-manager/source/stem/stem_UTF_8_german.cpp File Reference
#include <stem/header.h>
Functions
int german_UTF_8_stem (struct SN_env *z)
static int r_standard_suffix (struct SN_env *z)
static int r_R2 (struct SN_env *z)
static int r_R1 (struct SN_env *z)
static int r_mark_regions (struct SN_env *z)
static int r_postlude (struct SN_env *z)
static int r_prelude (struct SN_env *z)
struct SN_env * german_UTF_8_create_env (void)
void german_UTF_8_close_env (struct SN_env *z)
Variables
static const symbol s_0_1 [1] = { 'U' }
static const symbol s_0_2 [1] = { 'Y' }
static const symbol s_0_3 [2] = { 0xC3, 0xA4 }
static const symbol s_0_4 [2] = { 0xC3, 0xB6 }
static const symbol s_0_5 [2] = { 0xC3, 0xBC }
static struct among a_0 [6]
static const symbol s_1_0 [1] = { 'e' }
static const symbol s_1_1 [2] = { 'e', 'm' }
static const symbol s_1_2 [2] = { 'e', 'n' }
static const symbol s_1_3 [3] = { 'e', 'r', 'n' }
static const symbol s_1_4 [2] = { 'e', 'r' }
static const symbol s_1_5 [1] = { 's' }
static const symbol s_1_6 [2] = { 'e', 's' }
static struct among a_1 [7]
static const symbol s_2_0 [2] = { 'e', 'n' }
static const symbol s_2_1 [2] = { 'e', 'r' }
static const symbol s_2_2 [2] = { 's', 't' }
static const symbol s_2_3 [3] = { 'e', 's', 't' }
static struct among a_2 [4]
static const symbol s_3_0 [2] = { 'i', 'g' }
static const symbol s_3_1 [4] = { 'l', 'i', 'c', 'h' }
static struct among a_3 [2]
static const symbol s_4_0 [3] = { 'e', 'n', 'd' }
static const symbol s_4_1 [2] = { 'i', 'g' }
static const symbol s_4_2 [3] = { 'u', 'n', 'g' }
static const symbol s_4_3 [4] = { 'l', 'i', 'c', 'h' }
static const symbol s_4_4 [4] = { 'i', 's', 'c', 'h' }
static const symbol s_4_5 [2] = { 'i', 'k' }
static const symbol s_4_6 [4] = { 'h', 'e', 'i', 't' }
static const symbol s_4_7 [4] = { 'k', 'e', 'i', 't' }
static struct among a_4 [8]
static const unsigned char g_v [] = { 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 32, 8 }
static const unsigned char g_s_ending [] = { 117, 30, 5 }
static const unsigned char g_st_ending [] = { 117, 30, 4 }
static const symbol s_0 [] = { 0xC3, 0x9F }
static const symbol s_1 [] = { 's', 's' }
static const symbol s_2 [] = { 'u' }
static const symbol s_3 [] = { 'U' }
static const symbol s_4 [] = { 'y' }
static const symbol s_5 [] = { 'Y' }
static const symbol s_6 [] = { 'y' }
static const symbol s_7 [] = { 'u' }
static const symbol s_8 [] = { 'a' }
static const symbol s_9 [] = { 'o' }
static const symbol s_10 [] = { 'u' }
static const symbol s_11 [] = { 'i', 'g' }
static const symbol s_12 [] = { 'e' }
static const symbol s_13 [] = { 'e' }
static const symbol s_14 [] = { 'e', 'r' }
static const symbol s_15 [] = { 'e', 'n' }
Function Documentation
void german_UTF_8_close_env (struct SN_env * z)
struct SN_env* german_UTF_8_create_env (void) [read]
int german_UTF_8_stem (struct SN_env * z)
static int r_mark_regions (struct SN_env * z) [static]
Definition at line 201 of file stem_UTF_8_german.cpp.
References SN_env::c, g_v, SN_env::I, in_grouping_U(), SN_env::l, out_grouping_U(), SN_env::p, and skip_utf8().
static int r_postlude (struct SN_env * z) [static]
Definition at line 241 of file stem_UTF_8_german.cpp.
References SN_env::bra, SN_env::c, find_among(), SN_env::ket, SN_env::l, SN_env::p, s_10, s_6, s_7, s_8, s_9, skip_utf8(), and slice_from_s().
static int r_prelude (struct SN_env * z) [static]
Definition at line 133 of file stem_UTF_8_german.cpp.
References SN_env::bra, SN_env::c, eq_s(), g_v, in_grouping_U(), SN_env::ket, SN_env::l, SN_env::p, s_0, s_1, s_2, s_3, s_4, s_5, skip_utf8(), and slice_from_s().
static int r_R1 (struct SN_env * z) [static]
Definition at line 291 of file stem_UTF_8_german.cpp.
References SN_env::c, and SN_env::I.
static int r_R2 (struct SN_env * z) [static]
Definition at line 296 of file stem_UTF_8_german.cpp.
References SN_env::c, and SN_env::I.
static int r_standard_suffix (struct SN_env * z) [static]
Definition at line 301 of file stem_UTF_8_german.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), g_s_ending, g_st_ending, in_grouping_b_U(), SN_env::ket, SN_env::l, SN_env::lb, SN_env::p, r_R1(), r_R2(), s_11, s_12, s_13, s_14, s_15, skip_utf8(), and slice_del().
Variable Documentation
struct among a_0[6] [static]
Initial value:
{
 { 0, 0, -1, 6, 0},
 { 1, s_0_1, 0, 2, 0},
 { 1, s_0_2, 0, 1, 0},
 { 2, s_0_3, 0, 3, 0},
 { 2, s_0_4, 0, 4, 0},
 { 2, s_0_5, 0, 5, 0}
}
Definition at line 38 of file stem_UTF_8_german.cpp.
struct among a_1[7] [static]
Initial value:
{
 { 1, s_1_0, -1, 1, 0},
 { 2, s_1_1, -1, 1, 0},
 { 2, s_1_2, -1, 1, 0},
 { 3, s_1_3, -1, 1, 0},
 { 2, s_1_4, -1, 1, 0},
 { 1, s_1_5, -1, 2, 0},
 { 2, s_1_6, 5, 1, 0}
}
Definition at line 56 of file stem_UTF_8_german.cpp.
struct among a_2[4] [static]
Initial value:
{
 { 2, s_2_0, -1, 1, 0},
 { 2, s_2_1, -1, 1, 0},
 { 2, s_2_2, -1, 2, 0},
 { 3, s_2_3, 2, 1, 0}
}
Definition at line 72 of file stem_UTF_8_german.cpp.
struct among a_3[2] [static]
Initial value:
{
 { 2, s_3_0, -1, 1, 0},
 { 4, s_3_1, -1, 1, 0}
}
Definition at line 83 of file stem_UTF_8_german.cpp.
struct among a_4[8] [static]
Initial value:
{
 { 3, s_4_0, -1, 1, 0},
 { 2, s_4_1, -1, 2, 0},
 { 3, s_4_2, -1, 1, 0},
 { 4, s_4_3, -1, 3, 0},
 { 4, s_4_4, -1, 2, 0},
 { 2, s_4_5, -1, 2, 0},
 { 4, s_4_6, -1, 3, 0},
 { 4, s_4_7, -1, 4, 0}
}
Definition at line 98 of file stem_UTF_8_german.cpp.
const unsigned char g_s_ending[] = { 117, 30, 5 } [static]
Definition at line 112 of file stem_UTF_8_german.cpp.
const unsigned char g_st_ending[] = { 117, 30, 4 } [static]
Definition at line 114 of file stem_UTF_8_german.cpp.
Referenced by r_standard_suffix().
const unsigned char g_v[] = { 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 32, 8 } [static]
Definition at line 110 of file stem_UTF_8_german.cpp.
const symbol s_0[] = { 0xC3, 0x9F } [static]
Definition at line 116 of file stem_UTF_8_german.cpp.
const symbol s_0_1[1] = { 'U' } [static]
Definition at line 32 of file stem_UTF_8_german.cpp.
const symbol s_0_2[1] = { 'Y' } [static]
Definition at line 33 of file stem_UTF_8_german.cpp.
const symbol s_0_3[2] = { 0xC3, 0xA4 } [static]
Definition at line 34 of file stem_UTF_8_german.cpp.
const symbol s_0_4[2] = { 0xC3, 0xB6 } [static]
Definition at line 35 of file stem_UTF_8_german.cpp.
const symbol s_0_5[2] = { 0xC3, 0xBC } [static]
Definition at line 36 of file stem_UTF_8_german.cpp.
const symbol s_1[] = { 's', 's' } [static]
Definition at line 117 of file stem_UTF_8_german.cpp.
const symbol s_10[] = { 'u' } [static]
Definition at line 126 of file stem_UTF_8_german.cpp.
const symbol s_11[] = { 'i', 'g' } [static]
Definition at line 127 of file stem_UTF_8_german.cpp.
const symbol s_12[] = { 'e' } [static]
Definition at line 128 of file stem_UTF_8_german.cpp.
const symbol s_13[] = { 'e' } [static]
Definition at line 129 of file stem_UTF_8_german.cpp.
const symbol s_14[] = { 'e', 'r' } [static]
Definition at line 130 of file stem_UTF_8_german.cpp.
const symbol s_15[] = { 'e', 'n' } [static]
Definition at line 131 of file stem_UTF_8_german.cpp.
const symbol s_1_0[1] = { 'e' } [static]
Definition at line 48 of file stem_UTF_8_german.cpp.
const symbol s_1_1[2] = { 'e', 'm' } [static]
Definition at line 49 of file stem_UTF_8_german.cpp.
const symbol s_1_2[2] = { 'e', 'n' } [static]
Definition at line 50 of file stem_UTF_8_german.cpp.
const symbol s_1_3[3] = { 'e', 'r', 'n' } [static]
Definition at line 51 of file stem_UTF_8_german.cpp.
const symbol s_1_4[2] = { 'e', 'r' } [static]
Definition at line 52 of file stem_UTF_8_german.cpp.
const symbol s_1_5[1] = { 's' } [static]
Definition at line 53 of file stem_UTF_8_german.cpp.
const symbol s_1_6[2] = { 'e', 's' } [static]
Definition at line 54 of file stem_UTF_8_german.cpp.
const symbol s_2[] = { 'u' } [static]
Definition at line 118 of file stem_UTF_8_german.cpp.
const symbol s_2_0[2] = { 'e', 'n' } [static]
Definition at line 67 of file stem_UTF_8_german.cpp.
const symbol s_2_1[2] = { 'e', 'r' } [static]
Definition at line 68 of file stem_UTF_8_german.cpp.
const symbol s_2_2[2] = { 's', 't' } [static]
Definition at line 69 of file stem_UTF_8_german.cpp.
const symbol s_2_3[3] = { 'e', 's', 't' } [static]
Definition at line 70 of file stem_UTF_8_german.cpp.
const symbol s_3[] = { 'U' } [static]
Definition at line 119 of file stem_UTF_8_german.cpp.
const symbol s_3_0[2] = { 'i', 'g' } [static]
Definition at line 80 of file stem_UTF_8_german.cpp.
const symbol s_3_1[4] = { 'l', 'i', 'c', 'h' } [static]
Definition at line 81 of file stem_UTF_8_german.cpp.
const symbol s_4[] = { 'y' } [static]
Definition at line 120 of file stem_UTF_8_german.cpp.
const symbol s_4_0[3] = { 'e', 'n', 'd' } [static]
Definition at line 89 of file stem_UTF_8_german.cpp.
const symbol s_4_1[2] = { 'i', 'g' } [static]
Definition at line 90 of file stem_UTF_8_german.cpp.
const symbol s_4_2[3] = { 'u', 'n', 'g' } [static]
Definition at line 91 of file stem_UTF_8_german.cpp.
const symbol s_4_3[4] = { 'l', 'i', 'c', 'h' } [static]
Definition at line 92 of file stem_UTF_8_german.cpp.
const symbol s_4_4[4] = { 'i', 's', 'c', 'h' } [static]
Definition at line 93 of file stem_UTF_8_german.cpp.
const symbol s_4_5[2] = { 'i', 'k' } [static]
Definition at line 94 of file stem_UTF_8_german.cpp.
const symbol s_4_6[4] = { 'h', 'e', 'i', 't' } [static]
Definition at line 95 of file stem_UTF_8_german.cpp.
const symbol s_4_7[4] = { 'k', 'e', 'i', 't' } [static]
Definition at line 96 of file stem_UTF_8_german.cpp.
const symbol s_5[] = { 'Y' } [static]
Definition at line 121 of file stem_UTF_8_german.cpp.
const symbol s_6[] = { 'y' } [static]
Definition at line 122 of file stem_UTF_8_german.cpp.
const symbol s_7[] = { 'u' } [static]
Definition at line 123 of file stem_UTF_8_german.cpp.
const symbol s_8[] = { 'a' } [static]
Definition at line 124 of file stem_UTF_8_german.cpp.
const symbol s_9[] = { 'o' } [static]
Definition at line 125 of file stem_UTF_8_german.cpp.