/disk/workspace-cpp/la-manager/include/stem/stem_UTF_8_spanish.h File Reference
Functions
struct SN_env * spanish_UTF_8_create_env (void)
void spanish_UTF_8_close_env (struct SN_env *z)
int spanish_UTF_8_stem (struct SN_env *z)
Function Documentation
void spanish_UTF_8_close_env (struct SN_env * z)
Definition at line 1097 of file stem_UTF_8_spanish.cpp.
References SN_close_env().
struct SN_env * spanish_UTF_8_create_env (void) [read]
Definition at line 1095 of file stem_UTF_8_spanish.cpp.
References SN_create_env().
int spanish_UTF_8_stem (struct SN_env * z)
Definition at line 1031 of file stem_UTF_8_spanish.cpp.
References SN_env::c, SN_env::l, SN_env::lb, r_attached_pronoun(), r_mark_regions(), r_postlude(), r_residual_suffix(), r_standard_suffix(), r_verb_suffix(), and r_y_verb_suffix().