/disk/workspace-cpp/la-manager/source/stem/stem_UTF_8_swedish.cpp File Reference
#include <stem/header.h>
Functions
int swedish_UTF_8_stem (struct SN_env *z)
static int r_other_suffix (struct SN_env *z)
static int r_consonant_pair (struct SN_env *z)
static int r_main_suffix (struct SN_env *z)
static int r_mark_regions (struct SN_env *z)
struct SN_env * swedish_UTF_8_create_env (void)
void swedish_UTF_8_close_env (struct SN_env *z)
Variables
static const symbol s_0_0 [1] = { 'a' }
static const symbol s_0_1 [4] = { 'a', 'r', 'n', 'a' }
static const symbol s_0_2 [4] = { 'e', 'r', 'n', 'a' }
static const symbol s_0_3 [7] = { 'h', 'e', 't', 'e', 'r', 'n', 'a' }
static const symbol s_0_4 [4] = { 'o', 'r', 'n', 'a' }
static const symbol s_0_5 [2] = { 'a', 'd' }
static const symbol s_0_6 [1] = { 'e' }
static const symbol s_0_7 [3] = { 'a', 'd', 'e' }
static const symbol s_0_8 [4] = { 'a', 'n', 'd', 'e' }
static const symbol s_0_9 [4] = { 'a', 'r', 'n', 'e' }
static const symbol s_0_10 [3] = { 'a', 'r', 'e' }
static const symbol s_0_11 [4] = { 'a', 's', 't', 'e' }
static const symbol s_0_12 [2] = { 'e', 'n' }
static const symbol s_0_13 [5] = { 'a', 'n', 'd', 'e', 'n' }
static const symbol s_0_14 [4] = { 'a', 'r', 'e', 'n' }
static const symbol s_0_15 [5] = { 'h', 'e', 't', 'e', 'n' }
static const symbol s_0_16 [3] = { 'e', 'r', 'n' }
static const symbol s_0_17 [2] = { 'a', 'r' }
static const symbol s_0_18 [2] = { 'e', 'r' }
static const symbol s_0_19 [5] = { 'h', 'e', 't', 'e', 'r' }
static const symbol s_0_20 [2] = { 'o', 'r' }
static const symbol s_0_21 [1] = { 's' }
static const symbol s_0_22 [2] = { 'a', 's' }
static const symbol s_0_23 [5] = { 'a', 'r', 'n', 'a', 's' }
static const symbol s_0_24 [5] = { 'e', 'r', 'n', 'a', 's' }
static const symbol s_0_25 [5] = { 'o', 'r', 'n', 'a', 's' }
static const symbol s_0_26 [2] = { 'e', 's' }
static const symbol s_0_27 [4] = { 'a', 'd', 'e', 's' }
static const symbol s_0_28 [5] = { 'a', 'n', 'd', 'e', 's' }
static const symbol s_0_29 [3] = { 'e', 'n', 's' }
static const symbol s_0_30 [5] = { 'a', 'r', 'e', 'n', 's' }
static const symbol s_0_31 [6] = { 'h', 'e', 't', 'e', 'n', 's' }
static const symbol s_0_32 [4] = { 'e', 'r', 'n', 's' }
static const symbol s_0_33 [2] = { 'a', 't' }
static const symbol s_0_34 [5] = { 'a', 'n', 'd', 'e', 't' }
static const symbol s_0_35 [3] = { 'h', 'e', 't' }
static const symbol s_0_36 [3] = { 'a', 's', 't' }
static struct among a_0 [37]
static const symbol s_1_0 [2] = { 'd', 'd' }
static const symbol s_1_1 [2] = { 'g', 'd' }
static const symbol s_1_2 [2] = { 'n', 'n' }
static const symbol s_1_3 [2] = { 'd', 't' }
static const symbol s_1_4 [2] = { 'g', 't' }
static const symbol s_1_5 [2] = { 'k', 't' }
static const symbol s_1_6 [2] = { 't', 't' }
static struct among a_1 [7]
static const symbol s_2_0 [2] = { 'i', 'g' }
static const symbol s_2_1 [3] = { 'l', 'i', 'g' }
static const symbol s_2_2 [3] = { 'e', 'l', 's' }
static const symbol s_2_3 [5] = { 'f', 'u', 'l', 'l', 't' }
static const symbol s_2_4 [5] = { 'l', 0xC3, 0xB6, 's', 't' }
static struct among a_2 [5]
static const unsigned char g_v [] = { 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 0, 32 }
static const unsigned char g_s_ending [] = { 119, 127, 149 }
static const symbol s_0 [] = { 'l', 0xC3, 0xB6, 's' }
static const symbol s_1 [] = { 'f', 'u', 'l', 'l' }
Function Documentation
static int r_consonant_pair (struct SN_env * z) [static]
Definition at line 206 of file stem_UTF_8_swedish.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::I, SN_env::ket, SN_env::l, SN_env::lb, SN_env::p, skip_utf8(), and slice_del().
static int r_main_suffix (struct SN_env * z) [static]
Definition at line 174 of file stem_UTF_8_swedish.cpp.
References SN_env::bra, SN_env::c, find_among_b(), g_s_ending, SN_env::I, in_grouping_b_U(), SN_env::ket, SN_env::l, SN_env::lb, SN_env::p, and slice_del().
static int r_mark_regions (struct SN_env * z) [static]
Definition at line 150 of file stem_UTF_8_swedish.cpp.
References SN_env::c, g_v, SN_env::I, in_grouping_U(), SN_env::l, out_grouping_U(), SN_env::p, and skip_utf8().
static int r_other_suffix (struct SN_env * z) [static]
Definition at line 232 of file stem_UTF_8_swedish.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::I, SN_env::ket, SN_env::l, SN_env::lb, SN_env::p, s_0, s_1, slice_del(), and slice_from_s().
void swedish_UTF_8_close_env (struct SN_env * z)
struct SN_env* swedish_UTF_8_create_env (void) [read]
int swedish_UTF_8_stem (struct SN_env * z)
Variable Documentation
struct among a_0[37] [static]
Definition at line 68 of file stem_UTF_8_swedish.cpp.
struct among a_1[7] [static]
Initial value:
{
 { 2, s_1_0, -1, -1, 0},
 { 2, s_1_1, -1, -1, 0},
 { 2, s_1_2, -1, -1, 0},
 { 2, s_1_3, -1, -1, 0},
 { 2, s_1_4, -1, -1, 0},
 { 2, s_1_5, -1, -1, 0},
 { 2, s_1_6, -1, -1, 0}
}
Definition at line 117 of file stem_UTF_8_swedish.cpp.
struct among a_2[5] [static]
Initial value:
{
 { 2, s_2_0, -1, 1, 0},
 { 3, s_2_1, 0, 1, 0},
 { 3, s_2_2, -1, 1, 0},
 { 5, s_2_3, -1, 3, 0},
 { 5, s_2_4, -1, 2, 0}
}
Definition at line 134 of file stem_UTF_8_swedish.cpp.
const unsigned char g_s_ending[] = { 119, 127, 149 } [static]
Definition at line 145 of file stem_UTF_8_swedish.cpp.
const unsigned char g_v[] = { 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 0, 32 } [static]
Definition at line 143 of file stem_UTF_8_swedish.cpp.
const symbol s_0[] = { 'l', 0xC3, 0xB6, 's' } [static]
Definition at line 147 of file stem_UTF_8_swedish.cpp.
const symbol s_0_0[1] = { 'a' } [static]
Definition at line 30 of file stem_UTF_8_swedish.cpp.
const symbol s_0_1[4] = { 'a', 'r', 'n', 'a' } [static]
Definition at line 31 of file stem_UTF_8_swedish.cpp.
const symbol s_0_10[3] = { 'a', 'r', 'e' } [static]
Definition at line 40 of file stem_UTF_8_swedish.cpp.
const symbol s_0_11[4] = { 'a', 's', 't', 'e' } [static]
Definition at line 41 of file stem_UTF_8_swedish.cpp.
const symbol s_0_12[2] = { 'e', 'n' } [static]
Definition at line 42 of file stem_UTF_8_swedish.cpp.
const symbol s_0_13[5] = { 'a', 'n', 'd', 'e', 'n' } [static]
Definition at line 43 of file stem_UTF_8_swedish.cpp.
const symbol s_0_14[4] = { 'a', 'r', 'e', 'n' } [static]
Definition at line 44 of file stem_UTF_8_swedish.cpp.
const symbol s_0_15[5] = { 'h', 'e', 't', 'e', 'n' } [static]
Definition at line 45 of file stem_UTF_8_swedish.cpp.
const symbol s_0_16[3] = { 'e', 'r', 'n' } [static]
Definition at line 46 of file stem_UTF_8_swedish.cpp.
const symbol s_0_17[2] = { 'a', 'r' } [static]
Definition at line 47 of file stem_UTF_8_swedish.cpp.
const symbol s_0_18[2] = { 'e', 'r' } [static]
Definition at line 48 of file stem_UTF_8_swedish.cpp.
const symbol s_0_19[5] = { 'h', 'e', 't', 'e', 'r' } [static]
Definition at line 49 of file stem_UTF_8_swedish.cpp.
const symbol s_0_2[4] = { 'e', 'r', 'n', 'a' } [static]
Definition at line 32 of file stem_UTF_8_swedish.cpp.
const symbol s_0_20[2] = { 'o', 'r' } [static]
Definition at line 50 of file stem_UTF_8_swedish.cpp.
const symbol s_0_21[1] = { 's' } [static]
Definition at line 51 of file stem_UTF_8_swedish.cpp.
const symbol s_0_22[2] = { 'a', 's' } [static]
Definition at line 52 of file stem_UTF_8_swedish.cpp.
const symbol s_0_23[5] = { 'a', 'r', 'n', 'a', 's' } [static]
Definition at line 53 of file stem_UTF_8_swedish.cpp.
const symbol s_0_24[5] = { 'e', 'r', 'n', 'a', 's' } [static]
Definition at line 54 of file stem_UTF_8_swedish.cpp.
const symbol s_0_25[5] = { 'o', 'r', 'n', 'a', 's' } [static]
Definition at line 55 of file stem_UTF_8_swedish.cpp.
const symbol s_0_26[2] = { 'e', 's' } [static]
Definition at line 56 of file stem_UTF_8_swedish.cpp.
const symbol s_0_27[4] = { 'a', 'd', 'e', 's' } [static]
Definition at line 57 of file stem_UTF_8_swedish.cpp.
const symbol s_0_28[5] = { 'a', 'n', 'd', 'e', 's' } [static]
Definition at line 58 of file stem_UTF_8_swedish.cpp.
const symbol s_0_29[3] = { 'e', 'n', 's' } [static]
Definition at line 59 of file stem_UTF_8_swedish.cpp.
const symbol s_0_3[7] = { 'h', 'e', 't', 'e', 'r', 'n', 'a' } [static]
Definition at line 33 of file stem_UTF_8_swedish.cpp.
const symbol s_0_30[5] = { 'a', 'r', 'e', 'n', 's' } [static]
Definition at line 60 of file stem_UTF_8_swedish.cpp.
const symbol s_0_31[6] = { 'h', 'e', 't', 'e', 'n', 's' } [static]
Definition at line 61 of file stem_UTF_8_swedish.cpp.
const symbol s_0_32[4] = { 'e', 'r', 'n', 's' } [static]
Definition at line 62 of file stem_UTF_8_swedish.cpp.
const symbol s_0_33[2] = { 'a', 't' } [static]
Definition at line 63 of file stem_UTF_8_swedish.cpp.
const symbol s_0_34[5] = { 'a', 'n', 'd', 'e', 't' } [static]
Definition at line 64 of file stem_UTF_8_swedish.cpp.
const symbol s_0_35[3] = { 'h', 'e', 't' } [static]
Definition at line 65 of file stem_UTF_8_swedish.cpp.
const symbol s_0_36[3] = { 'a', 's', 't' } [static]
Definition at line 66 of file stem_UTF_8_swedish.cpp.
const symbol s_0_4[4] = { 'o', 'r', 'n', 'a' } [static]
Definition at line 34 of file stem_UTF_8_swedish.cpp.
const symbol s_0_5[2] = { 'a', 'd' } [static]
Definition at line 35 of file stem_UTF_8_swedish.cpp.
const symbol s_0_6[1] = { 'e' } [static]
Definition at line 36 of file stem_UTF_8_swedish.cpp.
const symbol s_0_7[3] = { 'a', 'd', 'e' } [static]
Definition at line 37 of file stem_UTF_8_swedish.cpp.
const symbol s_0_8[4] = { 'a', 'n', 'd', 'e' } [static]
Definition at line 38 of file stem_UTF_8_swedish.cpp.
const symbol s_0_9[4] = { 'a', 'r', 'n', 'e' } [static]
Definition at line 39 of file stem_UTF_8_swedish.cpp.
const symbol s_1[] = { 'f', 'u', 'l', 'l' } [static]
Definition at line 148 of file stem_UTF_8_swedish.cpp.
const symbol s_1_0[2] = { 'd', 'd' } [static]
Definition at line 109 of file stem_UTF_8_swedish.cpp.
const symbol s_1_1[2] = { 'g', 'd' } [static]
Definition at line 110 of file stem_UTF_8_swedish.cpp.
const symbol s_1_2[2] = { 'n', 'n' } [static]
Definition at line 111 of file stem_UTF_8_swedish.cpp.
const symbol s_1_3[2] = { 'd', 't' } [static]
Definition at line 112 of file stem_UTF_8_swedish.cpp.
const symbol s_1_4[2] = { 'g', 't' } [static]
Definition at line 113 of file stem_UTF_8_swedish.cpp.
const symbol s_1_5[2] = { 'k', 't' } [static]
Definition at line 114 of file stem_UTF_8_swedish.cpp.
const symbol s_1_6[2] = { 't', 't' } [static]
Definition at line 115 of file stem_UTF_8_swedish.cpp.
const symbol s_2_0[2] = { 'i', 'g' } [static]
Definition at line 128 of file stem_UTF_8_swedish.cpp.
const symbol s_2_1[3] = { 'l', 'i', 'g' } [static]
Definition at line 129 of file stem_UTF_8_swedish.cpp.
const symbol s_2_2[3] = { 'e', 'l', 's' } [static]
Definition at line 130 of file stem_UTF_8_swedish.cpp.
const symbol s_2_3[5] = { 'f', 'u', 'l', 'l', 't' } [static]
Definition at line 131 of file stem_UTF_8_swedish.cpp.
const symbol s_2_4[5] = { 'l', 0xC3, 0xB6, 's', 't' } [static]
Definition at line 132 of file stem_UTF_8_swedish.cpp.