/disk/workspace-cpp/la-manager/include/stem/stem_UTF_8_swedish.h File Reference
Functions
struct SN_env * swedish_UTF_8_create_env (void)
void swedish_UTF_8_close_env (struct SN_env *z)
int swedish_UTF_8_stem (struct SN_env *z)
Function Documentation
void swedish_UTF_8_close_env (struct SN_env * z)
Definition at line 309 of file stem_UTF_8_swedish.cpp.
References SN_close_env().
struct SN_env * swedish_UTF_8_create_env (void) [read]
Definition at line 307 of file stem_UTF_8_swedish.cpp.
References SN_create_env().
int swedish_UTF_8_stem (struct SN_env * z)
Definition at line 268 of file stem_UTF_8_swedish.cpp.
References SN_env::c, SN_env::l, SN_env::lb, r_consonant_pair(), r_main_suffix(), r_mark_regions(), and r_other_suffix().