/disk/workspace-cpp/la-manager/source/stem/stem_UTF_8_portuguese.cpp File Reference
#include <stem/header.h>
Functions
int portuguese_UTF_8_stem (struct SN_env *z)
static int r_residual_form (struct SN_env *z)
static int r_residual_suffix (struct SN_env *z)
static int r_verb_suffix (struct SN_env *z)
static int r_standard_suffix (struct SN_env *z)
static int r_R2 (struct SN_env *z)
static int r_R1 (struct SN_env *z)
static int r_RV (struct SN_env *z)
static int r_mark_regions (struct SN_env *z)
static int r_postlude (struct SN_env *z)
static int r_prelude (struct SN_env *z)
struct SN_env * portuguese_UTF_8_create_env (void)
void portuguese_UTF_8_close_env (struct SN_env *z)
Variables
static const symbol s_0_1 [2] = { 0xC3, 0xA3 }
static const symbol s_0_2 [2] = { 0xC3, 0xB5 }
static struct among a_0 [3]
static const symbol s_1_1 [2] = { 'a', '~' }
static const symbol s_1_2 [2] = { 'o', '~' }
static struct among a_1 [3]
static const symbol s_2_0 [2] = { 'i', 'c' }
static const symbol s_2_1 [2] = { 'a', 'd' }
static const symbol s_2_2 [2] = { 'o', 's' }
static const symbol s_2_3 [2] = { 'i', 'v' }
static struct among a_2 [4]
static const symbol s_3_0 [4] = { 'a', 'n', 't', 'e' }
static const symbol s_3_1 [4] = { 'a', 'v', 'e', 'l' }
static const symbol s_3_2 [5] = { 0xC3, 0xAD, 'v', 'e', 'l' }
static struct among a_3 [3]
static const symbol s_4_0 [2] = { 'i', 'c' }
static const symbol s_4_1 [4] = { 'a', 'b', 'i', 'l' }
static const symbol s_4_2 [2] = { 'i', 'v' }
static struct among a_4 [3]
static const symbol s_5_0 [3] = { 'i', 'c', 'a' }
static const symbol s_5_1 [6] = { 0xC3, 0xA2, 'n', 'c', 'i', 'a' }
static const symbol s_5_2 [6] = { 0xC3, 0xAA, 'n', 'c', 'i', 'a' }
static const symbol s_5_3 [3] = { 'i', 'r', 'a' }
static const symbol s_5_4 [5] = { 'a', 'd', 'o', 'r', 'a' }
static const symbol s_5_5 [3] = { 'o', 's', 'a' }
static const symbol s_5_6 [4] = { 'i', 's', 't', 'a' }
static const symbol s_5_7 [3] = { 'i', 'v', 'a' }
static const symbol s_5_8 [3] = { 'e', 'z', 'a' }
static const symbol s_5_9 [6] = { 'l', 'o', 'g', 0xC3, 0xAD, 'a' }
static const symbol s_5_10 [5] = { 'i', 'd', 'a', 'd', 'e' }
static const symbol s_5_11 [4] = { 'a', 'n', 't', 'e' }
static const symbol s_5_12 [5] = { 'm', 'e', 'n', 't', 'e' }
static const symbol s_5_13 [6] = { 'a', 'm', 'e', 'n', 't', 'e' }
static const symbol s_5_14 [5] = { 0xC3, 0xA1, 'v', 'e', 'l' }
static const symbol s_5_15 [5] = { 0xC3, 0xAD, 'v', 'e', 'l' }
static const symbol s_5_16 [6] = { 'u', 'c', 'i', 0xC3, 0xB3, 'n' }
static const symbol s_5_17 [3] = { 'i', 'c', 'o' }
static const symbol s_5_18 [4] = { 'i', 's', 'm', 'o' }
static const symbol s_5_19 [3] = { 'o', 's', 'o' }
static const symbol s_5_20 [6] = { 'a', 'm', 'e', 'n', 't', 'o' }
static const symbol s_5_21 [6] = { 'i', 'm', 'e', 'n', 't', 'o' }
static const symbol s_5_22 [3] = { 'i', 'v', 'o' }
static const symbol s_5_23 [6] = { 'a', 0xC3, 0xA7, 'a', '~', 'o' }
static const symbol s_5_24 [4] = { 'a', 'd', 'o', 'r' }
static const symbol s_5_25 [4] = { 'i', 'c', 'a', 's' }
static const symbol s_5_26 [7] = { 0xC3, 0xAA, 'n', 'c', 'i', 'a', 's' }
static const symbol s_5_27 [4] = { 'i', 'r', 'a', 's' }
static const symbol s_5_28 [6] = { 'a', 'd', 'o', 'r', 'a', 's' }
static const symbol s_5_29 [4] = { 'o', 's', 'a', 's' }
static const symbol s_5_30 [5] = { 'i', 's', 't', 'a', 's' }
static const symbol s_5_31 [4] = { 'i', 'v', 'a', 's' }
static const symbol s_5_32 [4] = { 'e', 'z', 'a', 's' }
static const symbol s_5_33 [7] = { 'l', 'o', 'g', 0xC3, 0xAD, 'a', 's' }
static const symbol s_5_34 [6] = { 'i', 'd', 'a', 'd', 'e', 's' }
static const symbol s_5_35 [7] = { 'u', 'c', 'i', 'o', 'n', 'e', 's' }
static const symbol s_5_36 [6] = { 'a', 'd', 'o', 'r', 'e', 's' }
static const symbol s_5_37 [5] = { 'a', 'n', 't', 'e', 's' }
static const symbol s_5_38 [7] = { 'a', 0xC3, 0xA7, 'o', '~', 'e', 's' }
static const symbol s_5_39 [4] = { 'i', 'c', 'o', 's' }
static const symbol s_5_40 [5] = { 'i', 's', 'm', 'o', 's' }
static const symbol s_5_41 [4] = { 'o', 's', 'o', 's' }
static const symbol s_5_42 [7] = { 'a', 'm', 'e', 'n', 't', 'o', 's' }
static const symbol s_5_43 [7] = { 'i', 'm', 'e', 'n', 't', 'o', 's' }
static const symbol s_5_44 [4] = { 'i', 'v', 'o', 's' }
static struct among a_5 [45]
static const symbol s_6_0 [3] = { 'a', 'd', 'a' }
static const symbol s_6_1 [3] = { 'i', 'd', 'a' }
static const symbol s_6_2 [2] = { 'i', 'a' }
static const symbol s_6_3 [4] = { 'a', 'r', 'i', 'a' }
static const symbol s_6_4 [4] = { 'e', 'r', 'i', 'a' }
static const symbol s_6_5 [4] = { 'i', 'r', 'i', 'a' }
static const symbol s_6_6 [3] = { 'a', 'r', 'a' }
static const symbol s_6_7 [3] = { 'e', 'r', 'a' }
static const symbol s_6_8 [3] = { 'i', 'r', 'a' }
static const symbol s_6_9 [3] = { 'a', 'v', 'a' }
static const symbol s_6_10 [4] = { 'a', 's', 's', 'e' }
static const symbol s_6_11 [4] = { 'e', 's', 's', 'e' }
static const symbol s_6_12 [4] = { 'i', 's', 's', 'e' }
static const symbol s_6_13 [4] = { 'a', 's', 't', 'e' }
static const symbol s_6_14 [4] = { 'e', 's', 't', 'e' }
static const symbol s_6_15 [4] = { 'i', 's', 't', 'e' }
static const symbol s_6_16 [2] = { 'e', 'i' }
static const symbol s_6_17 [4] = { 'a', 'r', 'e', 'i' }
static const symbol s_6_18 [4] = { 'e', 'r', 'e', 'i' }
static const symbol s_6_19 [4] = { 'i', 'r', 'e', 'i' }
static const symbol s_6_20 [2] = { 'a', 'm' }
static const symbol s_6_21 [3] = { 'i', 'a', 'm' }
static const symbol s_6_22 [5] = { 'a', 'r', 'i', 'a', 'm' }
static const symbol s_6_23 [5] = { 'e', 'r', 'i', 'a', 'm' }
static const symbol s_6_24 [5] = { 'i', 'r', 'i', 'a', 'm' }
static const symbol s_6_25 [4] = { 'a', 'r', 'a', 'm' }
static const symbol s_6_26 [4] = { 'e', 'r', 'a', 'm' }
static const symbol s_6_27 [4] = { 'i', 'r', 'a', 'm' }
static const symbol s_6_28 [4] = { 'a', 'v', 'a', 'm' }
static const symbol s_6_29 [2] = { 'e', 'm' }
static const symbol s_6_30 [4] = { 'a', 'r', 'e', 'm' }
static const symbol s_6_31 [4] = { 'e', 'r', 'e', 'm' }
static const symbol s_6_32 [4] = { 'i', 'r', 'e', 'm' }
static const symbol s_6_33 [5] = { 'a', 's', 's', 'e', 'm' }
static const symbol s_6_34 [5] = { 'e', 's', 's', 'e', 'm' }
static const symbol s_6_35 [5] = { 'i', 's', 's', 'e', 'm' }
static const symbol s_6_36 [3] = { 'a', 'd', 'o' }
static const symbol s_6_37 [3] = { 'i', 'd', 'o' }
static const symbol s_6_38 [4] = { 'a', 'n', 'd', 'o' }
static const symbol s_6_39 [4] = { 'e', 'n', 'd', 'o' }
static const symbol s_6_40 [4] = { 'i', 'n', 'd', 'o' }
static const symbol s_6_41 [5] = { 'a', 'r', 'a', '~', 'o' }
static const symbol s_6_42 [5] = { 'e', 'r', 'a', '~', 'o' }
static const symbol s_6_43 [5] = { 'i', 'r', 'a', '~', 'o' }
static const symbol s_6_44 [2] = { 'a', 'r' }
static const symbol s_6_45 [2] = { 'e', 'r' }
static const symbol s_6_46 [2] = { 'i', 'r' }
static const symbol s_6_47 [2] = { 'a', 's' }
static const symbol s_6_48 [4] = { 'a', 'd', 'a', 's' }
static const symbol s_6_49 [4] = { 'i', 'd', 'a', 's' }
static const symbol s_6_50 [3] = { 'i', 'a', 's' }
static const symbol s_6_51 [5] = { 'a', 'r', 'i', 'a', 's' }
static const symbol s_6_52 [5] = { 'e', 'r', 'i', 'a', 's' }
static const symbol s_6_53 [5] = { 'i', 'r', 'i', 'a', 's' }
static const symbol s_6_54 [4] = { 'a', 'r', 'a', 's' }
static const symbol s_6_55 [4] = { 'e', 'r', 'a', 's' }
static const symbol s_6_56 [4] = { 'i', 'r', 'a', 's' }
static const symbol s_6_57 [4] = { 'a', 'v', 'a', 's' }
static const symbol s_6_58 [2] = { 'e', 's' }
static const symbol s_6_59 [5] = { 'a', 'r', 'd', 'e', 's' }
static const symbol s_6_60 [5] = { 'e', 'r', 'd', 'e', 's' }
static const symbol s_6_61 [5] = { 'i', 'r', 'd', 'e', 's' }
static const symbol s_6_62 [4] = { 'a', 'r', 'e', 's' }
static const symbol s_6_63 [4] = { 'e', 'r', 'e', 's' }
static const symbol s_6_64 [4] = { 'i', 'r', 'e', 's' }
static const symbol s_6_65 [5] = { 'a', 's', 's', 'e', 's' }
static const symbol s_6_66 [5] = { 'e', 's', 's', 'e', 's' }
static const symbol s_6_67 [5] = { 'i', 's', 's', 'e', 's' }
static const symbol s_6_68 [5] = { 'a', 's', 't', 'e', 's' }
static const symbol s_6_69 [5] = { 'e', 's', 't', 'e', 's' }
static const symbol s_6_70 [5] = { 'i', 's', 't', 'e', 's' }
static const symbol s_6_71 [2] = { 'i', 's' }
static const symbol s_6_72 [3] = { 'a', 'i', 's' }
static const symbol s_6_73 [3] = { 'e', 'i', 's' }
static const symbol s_6_74 [5] = { 'a', 'r', 'e', 'i', 's' }
static const symbol s_6_75 [5] = { 'e', 'r', 'e', 'i', 's' }
static const symbol s_6_76 [5] = { 'i', 'r', 'e', 'i', 's' }
static const symbol s_6_77 [6] = { 0xC3, 0xA1, 'r', 'e', 'i', 's' }
static const symbol s_6_78 [6] = { 0xC3, 0xA9, 'r', 'e', 'i', 's' }
static const symbol s_6_79 [6] = { 0xC3, 0xAD, 'r', 'e', 'i', 's' }
static const symbol s_6_80 [7] = { 0xC3, 0xA1, 's', 's', 'e', 'i', 's' }
static const symbol s_6_81 [7] = { 0xC3, 0xA9, 's', 's', 'e', 'i', 's' }
static const symbol s_6_82 [7] = { 0xC3, 0xAD, 's', 's', 'e', 'i', 's' }
static const symbol s_6_83 [6] = { 0xC3, 0xA1, 'v', 'e', 'i', 's' }
static const symbol s_6_84 [5] = { 0xC3, 0xAD, 'e', 'i', 's' }
static const symbol s_6_85 [7] = { 'a', 'r', 0xC3, 0xAD, 'e', 'i', 's' }
static const symbol s_6_86 [7] = { 'e', 'r', 0xC3, 0xAD, 'e', 'i', 's' }
static const symbol s_6_87 [7] = { 'i', 'r', 0xC3, 0xAD, 'e', 'i', 's' }
static const symbol s_6_88 [4] = { 'a', 'd', 'o', 's' }
static const symbol s_6_89 [4] = { 'i', 'd', 'o', 's' }
static const symbol s_6_90 [4] = { 'a', 'm', 'o', 's' }
static const symbol s_6_91 [7] = { 0xC3, 0xA1, 'r', 'a', 'm', 'o', 's' }
static const symbol s_6_92 [7] = { 0xC3, 0xA9, 'r', 'a', 'm', 'o', 's' }
static const symbol s_6_93 [7] = { 0xC3, 0xAD, 'r', 'a', 'm', 'o', 's' }
static const symbol s_6_94 [7] = { 0xC3, 0xA1, 'v', 'a', 'm', 'o', 's' }
static const symbol s_6_95 [6] = { 0xC3, 0xAD, 'a', 'm', 'o', 's' }
static const symbol s_6_96 [8] = { 'a', 'r', 0xC3, 0xAD, 'a', 'm', 'o', 's' }
static const symbol s_6_97 [8] = { 'e', 'r', 0xC3, 0xAD, 'a', 'm', 'o', 's' }
static const symbol s_6_98 [8] = { 'i', 'r', 0xC3, 0xAD, 'a', 'm', 'o', 's' }
static const symbol s_6_99 [4] = { 'e', 'm', 'o', 's' }
static const symbol s_6_100 [6] = { 'a', 'r', 'e', 'm', 'o', 's' }
static const symbol s_6_101 [6] = { 'e', 'r', 'e', 'm', 'o', 's' }
static const symbol s_6_102 [6] = { 'i', 'r', 'e', 'm', 'o', 's' }
static const symbol s_6_103 [8] = { 0xC3, 0xA1, 's', 's', 'e', 'm', 'o', 's' }
static const symbol s_6_104 [8] = { 0xC3, 0xAA, 's', 's', 'e', 'm', 'o', 's' }
static const symbol s_6_105 [8] = { 0xC3, 0xAD, 's', 's', 'e', 'm', 'o', 's' }
static const symbol s_6_106 [4] = { 'i', 'm', 'o', 's' }
static const symbol s_6_107 [5] = { 'a', 'r', 'm', 'o', 's' }
static const symbol s_6_108 [5] = { 'e', 'r', 'm', 'o', 's' }
static const symbol s_6_109 [5] = { 'i', 'r', 'm', 'o', 's' }
static const symbol s_6_110 [5] = { 0xC3, 0xA1, 'm', 'o', 's' }
static const symbol s_6_111 [5] = { 'a', 'r', 0xC3, 0xA1, 's' }
static const symbol s_6_112 [5] = { 'e', 'r', 0xC3, 0xA1, 's' }
static const symbol s_6_113 [5] = { 'i', 'r', 0xC3, 0xA1, 's' }
static const symbol s_6_114 [2] = { 'e', 'u' }
static const symbol s_6_115 [2] = { 'i', 'u' }
static const symbol s_6_116 [2] = { 'o', 'u' }
static const symbol s_6_117 [4] = { 'a', 'r', 0xC3, 0xA1 }
static const symbol s_6_118 [4] = { 'e', 'r', 0xC3, 0xA1 }
static const symbol s_6_119 [4] = { 'i', 'r', 0xC3, 0xA1 }
static struct among a_6 [120]
static const symbol s_7_0 [1] = { 'a' }
static const symbol s_7_1 [1] = { 'i' }
static const symbol s_7_2 [1] = { 'o' }
static const symbol s_7_3 [2] = { 'o', 's' }
static const symbol s_7_4 [2] = { 0xC3, 0xA1 }
static const symbol s_7_5 [2] = { 0xC3, 0xAD }
static const symbol s_7_6 [2] = { 0xC3, 0xB3 }
static struct among a_7 [7]
static const symbol s_8_0 [1] = { 'e' }
static const symbol s_8_1 [2] = { 0xC3, 0xA7 }
static const symbol s_8_2 [2] = { 0xC3, 0xA9 }
static const symbol s_8_3 [2] = { 0xC3, 0xAA }
static struct among a_8 [4]
static const unsigned char g_v [] = { 17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 19, 12, 2 }
static const symbol s_0 [] = { 'a', '~' }
static const symbol s_1 [] = { 'o', '~' }
static const symbol s_2 [] = { 0xC3, 0xA3 }
static const symbol s_3 [] = { 0xC3, 0xB5 }
static const symbol s_4 [] = { 'l', 'o', 'g' }
static const symbol s_5 [] = { 'u' }
static const symbol s_6 [] = { 'e', 'n', 't', 'e' }
static const symbol s_7 [] = { 'a', 't' }
static const symbol s_8 [] = { 'a', 't' }
static const symbol s_9 [] = { 'e' }
static const symbol s_10 [] = { 'i', 'r' }
static const symbol s_11 [] = { 'u' }
static const symbol s_12 [] = { 'g' }
static const symbol s_13 [] = { 'i' }
static const symbol s_14 [] = { 'c' }
static const symbol s_15 [] = { 'c' }
static const symbol s_16 [] = { 'i' }
static const symbol s_17 [] = { 'c' }
Function Documentation
void portuguese_UTF_8_close_env (struct SN_env * z)
struct SN_env* portuguese_UTF_8_create_env (void) [read]
int portuguese_UTF_8_stem (struct SN_env * z)
static int r_mark_regions (struct SN_env * z) [static]
Definition at line 519 of file stem_UTF_8_portuguese.cpp.
References SN_env::c, g_v, SN_env::I, in_grouping_U(), SN_env::l, out_grouping_U(), SN_env::p, and skip_utf8().
static int r_postlude (struct SN_env * z) [static]
Definition at line 601 of file stem_UTF_8_portuguese.cpp.
References SN_env::bra, SN_env::c, find_among(), SN_env::ket, SN_env::l, SN_env::p, s_2, s_3, skip_utf8(), and slice_from_s().
static int r_prelude (struct SN_env * z) [static]
Definition at line 483 of file stem_UTF_8_portuguese.cpp.
References SN_env::bra, SN_env::c, find_among(), SN_env::ket, SN_env::l, SN_env::p, s_0, s_1, skip_utf8(), and slice_from_s().
static int r_R1 (struct SN_env * z) [static]
Definition at line 642 of file stem_UTF_8_portuguese.cpp.
References SN_env::c, and SN_env::I.
static int r_R2 (struct SN_env * z) [static]
Definition at line 647 of file stem_UTF_8_portuguese.cpp.
References SN_env::c, and SN_env::I.
static int r_residual_form (struct SN_env * z) [static]
Definition at line 880 of file stem_UTF_8_portuguese.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), SN_env::ket, SN_env::l, r_RV(), s_11, s_12, s_13, s_14, s_15, slice_del(), and slice_from_s().
Referenced by portuguese_UTF_8_stem().
static int r_residual_suffix (struct SN_env * z) [static]
Definition at line 859 of file stem_UTF_8_portuguese.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::ket, r_RV(), and slice_del().
static int r_RV (struct SN_env * z) [static]
Definition at line 637 of file stem_UTF_8_portuguese.cpp.
References SN_env::c, and SN_env::I.
static int r_standard_suffix (struct SN_env * z) [static]
Definition at line 652 of file stem_UTF_8_portuguese.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), SN_env::ket, SN_env::l, SN_env::lb, SN_env::p, r_R1(), r_R2(), r_RV(), s_10, s_4, s_5, s_6, s_7, s_8, s_9, slice_del(), and slice_from_s().
static int r_verb_suffix (struct SN_env * z) [static]
Definition at line 834 of file stem_UTF_8_portuguese.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::I, SN_env::ket, SN_env::l, SN_env::lb, and slice_del().
Variable Documentation
struct among a_0[3] [static]
Initial value:
{
 { 0, 0, -1, 3, 0},
 { 2, s_0_1, 0, 1, 0},
 { 2, s_0_2, 0, 2, 0}
}
Definition at line 38 of file stem_UTF_8_portuguese.cpp.
struct among a_1[3] [static]
Initial value:
{
 { 0, 0, -1, 3, 0},
 { 2, s_1_1, 0, 1, 0},
 { 2, s_1_2, 0, 2, 0}
}
Definition at line 48 of file stem_UTF_8_portuguese.cpp.
struct among a_2[4] [static]
Initial value:
{
 { 2, s_2_0, -1, -1, 0},
 { 2, s_2_1, -1, -1, 0},
 { 2, s_2_2, -1, -1, 0},
 { 2, s_2_3, -1, 1, 0}
}
Definition at line 60 of file stem_UTF_8_portuguese.cpp.
struct among a_3[3] [static]
Initial value:
{
 { 4, s_3_0, -1, 1, 0},
 { 4, s_3_1, -1, 1, 0},
 { 5, s_3_2, -1, 1, 0}
}
Definition at line 72 of file stem_UTF_8_portuguese.cpp.
struct among a_4[3] [static]
Initial value:
{
 { 2, s_4_0, -1, 1, 0},
 { 4, s_4_1, -1, 1, 0},
 { 2, s_4_2, -1, 1, 0}
}
Definition at line 83 of file stem_UTF_8_portuguese.cpp.
struct among a_5[45] [static]
Definition at line 136 of file stem_UTF_8_portuguese.cpp.
struct among a_6[120] [static]
Definition at line 306 of file stem_UTF_8_portuguese.cpp.
struct among a_7[7] [static]
Initial value:
{
 { 1, s_7_0, -1, 1, 0},
 { 1, s_7_1, -1, 1, 0},
 { 1, s_7_2, -1, 1, 0},
 { 2, s_7_3, -1, 1, 0},
 { 2, s_7_4, -1, 1, 0},
 { 2, s_7_5, -1, 1, 0},
 { 2, s_7_6, -1, 1, 0}
}
Definition at line 438 of file stem_UTF_8_portuguese.cpp.
struct among a_8[4] [static]
Initial value:
{
 { 1, s_8_0, -1, 1, 0},
 { 2, s_8_1, -1, 2, 0},
 { 2, s_8_2, -1, 1, 0},
 { 2, s_8_3, -1, 1, 0}
}
Definition at line 454 of file stem_UTF_8_portuguese.cpp.
const unsigned char g_v[] = { 17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 19, 12, 2 } [static]
Definition at line 462 of file stem_UTF_8_portuguese.cpp.
const symbol s_0[] = { 'a', '~' } [static]
Definition at line 464 of file stem_UTF_8_portuguese.cpp.
const symbol s_0_1[2] = { 0xC3, 0xA3 } [static]
Definition at line 35 of file stem_UTF_8_portuguese.cpp.
const symbol s_0_2[2] = { 0xC3, 0xB5 } [static]
Definition at line 36 of file stem_UTF_8_portuguese.cpp.
const symbol s_1[] = { 'o', '~' } [static]
Definition at line 465 of file stem_UTF_8_portuguese.cpp.
const symbol s_10[] = { 'i', 'r' } [static]
Definition at line 474 of file stem_UTF_8_portuguese.cpp.
const symbol s_11[] = { 'u' } [static]
Definition at line 475 of file stem_UTF_8_portuguese.cpp.
const symbol s_12[] = { 'g' } [static]
Definition at line 476 of file stem_UTF_8_portuguese.cpp.
const symbol s_13[] = { 'i' } [static]
Definition at line 477 of file stem_UTF_8_portuguese.cpp.
const symbol s_14[] = { 'c' } [static]
Definition at line 478 of file stem_UTF_8_portuguese.cpp.
const symbol s_15[] = { 'c' } [static]
Definition at line 479 of file stem_UTF_8_portuguese.cpp.
const symbol s_16[] = { 'i' } [static]
Definition at line 480 of file stem_UTF_8_portuguese.cpp.
const symbol s_17[] = { 'c' } [static]
Definition at line 481 of file stem_UTF_8_portuguese.cpp.
const symbol s_1_1[2] = { 'a', '~' } [static]
Definition at line 45 of file stem_UTF_8_portuguese.cpp.
const symbol s_1_2[2] = { 'o', '~' } [static]
Definition at line 46 of file stem_UTF_8_portuguese.cpp.
const symbol s_2[] = { 0xC3, 0xA3 } [static]
Definition at line 466 of file stem_UTF_8_portuguese.cpp.
const symbol s_2_0[2] = { 'i', 'c' } [static]
Definition at line 55 of file stem_UTF_8_portuguese.cpp.
const symbol s_2_1[2] = { 'a', 'd' } [static]
Definition at line 56 of file stem_UTF_8_portuguese.cpp.
const symbol s_2_2[2] = { 'o', 's' } [static]
Definition at line 57 of file stem_UTF_8_portuguese.cpp.
const symbol s_2_3[2] = { 'i', 'v' } [static]
Definition at line 58 of file stem_UTF_8_portuguese.cpp.
const symbol s_3[] = { 0xC3, 0xB5 } [static]
Definition at line 467 of file stem_UTF_8_portuguese.cpp.
const symbol s_3_0[4] = { 'a', 'n', 't', 'e' } [static]
Definition at line 68 of file stem_UTF_8_portuguese.cpp.
const symbol s_3_1[4] = { 'a', 'v', 'e', 'l' } [static]
Definition at line 69 of file stem_UTF_8_portuguese.cpp.
const symbol s_3_2[5] = { 0xC3, 0xAD, 'v', 'e', 'l' } [static]
Definition at line 70 of file stem_UTF_8_portuguese.cpp.
const symbol s_4[] = { 'l', 'o', 'g' } [static]
Definition at line 468 of file stem_UTF_8_portuguese.cpp.
const symbol s_4_0[2] = { 'i', 'c' } [static]
Definition at line 79 of file stem_UTF_8_portuguese.cpp.
const symbol s_4_1[4] = { 'a', 'b', 'i', 'l' } [static]
Definition at line 80 of file stem_UTF_8_portuguese.cpp.
const symbol s_4_2[2] = { 'i', 'v' } [static]
Definition at line 81 of file stem_UTF_8_portuguese.cpp.
const symbol s_5[] = { 'u' } [static]
Definition at line 469 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_0[3] = { 'i', 'c', 'a' } [static]
Definition at line 90 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_1[6] = { 0xC3, 0xA2, 'n', 'c', 'i', 'a' } [static]
Definition at line 91 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_10[5] = { 'i', 'd', 'a', 'd', 'e' } [static]
Definition at line 100 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_11[4] = { 'a', 'n', 't', 'e' } [static]
Definition at line 101 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_12[5] = { 'm', 'e', 'n', 't', 'e' } [static]
Definition at line 102 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_13[6] = { 'a', 'm', 'e', 'n', 't', 'e' } [static]
Definition at line 103 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_14[5] = { 0xC3, 0xA1, 'v', 'e', 'l' } [static]
Definition at line 104 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_15[5] = { 0xC3, 0xAD, 'v', 'e', 'l' } [static]
Definition at line 105 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_16[6] = { 'u', 'c', 'i', 0xC3, 0xB3, 'n' } [static]
Definition at line 106 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_17[3] = { 'i', 'c', 'o' } [static]
Definition at line 107 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_18[4] = { 'i', 's', 'm', 'o' } [static]
Definition at line 108 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_19[3] = { 'o', 's', 'o' } [static]
Definition at line 109 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_2[6] = { 0xC3, 0xAA, 'n', 'c', 'i', 'a' } [static]
Definition at line 92 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_20[6] = { 'a', 'm', 'e', 'n', 't', 'o' } [static]
Definition at line 110 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_21[6] = { 'i', 'm', 'e', 'n', 't', 'o' } [static]
Definition at line 111 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_22[3] = { 'i', 'v', 'o' } [static]
Definition at line 112 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_23[6] = { 'a', 0xC3, 0xA7, 'a', '~', 'o' } [static]
Definition at line 113 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_24[4] = { 'a', 'd', 'o', 'r' } [static]
Definition at line 114 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_25[4] = { 'i', 'c', 'a', 's' } [static]
Definition at line 115 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_26[7] = { 0xC3, 0xAA, 'n', 'c', 'i', 'a', 's' } [static]
Definition at line 116 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_27[4] = { 'i', 'r', 'a', 's' } [static]
Definition at line 117 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_28[6] = { 'a', 'd', 'o', 'r', 'a', 's' } [static]
Definition at line 118 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_29[4] = { 'o', 's', 'a', 's' } [static]
Definition at line 119 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_3[3] = { 'i', 'r', 'a' } [static]
Definition at line 93 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_30[5] = { 'i', 's', 't', 'a', 's' } [static]
Definition at line 120 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_31[4] = { 'i', 'v', 'a', 's' } [static]
Definition at line 121 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_32[4] = { 'e', 'z', 'a', 's' } [static]
Definition at line 122 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_33[7] = { 'l', 'o', 'g', 0xC3, 0xAD, 'a', 's' } [static]
Definition at line 123 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_34[6] = { 'i', 'd', 'a', 'd', 'e', 's' } [static]
Definition at line 124 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_35[7] = { 'u', 'c', 'i', 'o', 'n', 'e', 's' } [static]
Definition at line 125 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_36[6] = { 'a', 'd', 'o', 'r', 'e', 's' } [static]
Definition at line 126 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_37[5] = { 'a', 'n', 't', 'e', 's' } [static]
Definition at line 127 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_38[7] = { 'a', 0xC3, 0xA7, 'o', '~', 'e', 's' } [static]
Definition at line 128 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_39[4] = { 'i', 'c', 'o', 's' } [static]
Definition at line 129 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_4[5] = { 'a', 'd', 'o', 'r', 'a' } [static]
Definition at line 94 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_40[5] = { 'i', 's', 'm', 'o', 's' } [static]
Definition at line 130 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_41[4] = { 'o', 's', 'o', 's' } [static]
Definition at line 131 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_42[7] = { 'a', 'm', 'e', 'n', 't', 'o', 's' } [static]
Definition at line 132 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_43[7] = { 'i', 'm', 'e', 'n', 't', 'o', 's' } [static]
Definition at line 133 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_44[4] = { 'i', 'v', 'o', 's' } [static]
Definition at line 134 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_5[3] = { 'o', 's', 'a' } [static]
Definition at line 95 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_6[4] = { 'i', 's', 't', 'a' } [static]
Definition at line 96 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_7[3] = { 'i', 'v', 'a' } [static]
Definition at line 97 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_8[3] = { 'e', 'z', 'a' } [static]
Definition at line 98 of file stem_UTF_8_portuguese.cpp.
const symbol s_5_9[6] = { 'l', 'o', 'g', 0xC3, 0xAD, 'a' } [static]
Definition at line 99 of file stem_UTF_8_portuguese.cpp.
const symbol s_6[] = { 'e', 'n', 't', 'e' } [static]
Definition at line 470 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_0[3] = { 'a', 'd', 'a' } [static]
Definition at line 185 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_1[3] = { 'i', 'd', 'a' } [static]
Definition at line 186 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_10[4] = { 'a', 's', 's', 'e' } [static]
Definition at line 195 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_100[6] = { 'a', 'r', 'e', 'm', 'o', 's' } [static]
Definition at line 285 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_101[6] = { 'e', 'r', 'e', 'm', 'o', 's' } [static]
Definition at line 286 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_102[6] = { 'i', 'r', 'e', 'm', 'o', 's' } [static]
Definition at line 287 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_103[8] = { 0xC3, 0xA1, 's', 's', 'e', 'm', 'o', 's' } [static]
Definition at line 288 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_104[8] = { 0xC3, 0xAA, 's', 's', 'e', 'm', 'o', 's' } [static]
Definition at line 289 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_105[8] = { 0xC3, 0xAD, 's', 's', 'e', 'm', 'o', 's' } [static]
Definition at line 290 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_106[4] = { 'i', 'm', 'o', 's' } [static]
Definition at line 291 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_107[5] = { 'a', 'r', 'm', 'o', 's' } [static]
Definition at line 292 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_108[5] = { 'e', 'r', 'm', 'o', 's' } [static]
Definition at line 293 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_109[5] = { 'i', 'r', 'm', 'o', 's' } [static]
Definition at line 294 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_11[4] = { 'e', 's', 's', 'e' } [static]
Definition at line 196 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_110[5] = { 0xC3, 0xA1, 'm', 'o', 's' } [static]
Definition at line 295 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_111[5] = { 'a', 'r', 0xC3, 0xA1, 's' } [static]
Definition at line 296 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_112[5] = { 'e', 'r', 0xC3, 0xA1, 's' } [static]
Definition at line 297 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_113[5] = { 'i', 'r', 0xC3, 0xA1, 's' } [static]
Definition at line 298 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_114[2] = { 'e', 'u' } [static]
Definition at line 299 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_115[2] = { 'i', 'u' } [static]
Definition at line 300 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_116[2] = { 'o', 'u' } [static]
Definition at line 301 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_117[4] = { 'a', 'r', 0xC3, 0xA1 } [static]
Definition at line 302 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_118[4] = { 'e', 'r', 0xC3, 0xA1 } [static]
Definition at line 303 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_119[4] = { 'i', 'r', 0xC3, 0xA1 } [static]
Definition at line 304 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_12[4] = { 'i', 's', 's', 'e' } [static]
Definition at line 197 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_13[4] = { 'a', 's', 't', 'e' } [static]
Definition at line 198 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_14[4] = { 'e', 's', 't', 'e' } [static]
Definition at line 199 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_15[4] = { 'i', 's', 't', 'e' } [static]
Definition at line 200 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_16[2] = { 'e', 'i' } [static]
Definition at line 201 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_17[4] = { 'a', 'r', 'e', 'i' } [static]
Definition at line 202 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_18[4] = { 'e', 'r', 'e', 'i' } [static]
Definition at line 203 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_19[4] = { 'i', 'r', 'e', 'i' } [static]
Definition at line 204 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_2[2] = { 'i', 'a' } [static]
Definition at line 187 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_20[2] = { 'a', 'm' } [static]
Definition at line 205 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_21[3] = { 'i', 'a', 'm' } [static]
Definition at line 206 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_22[5] = { 'a', 'r', 'i', 'a', 'm' } [static]
Definition at line 207 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_23[5] = { 'e', 'r', 'i', 'a', 'm' } [static]
Definition at line 208 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_24[5] = { 'i', 'r', 'i', 'a', 'm' } [static]
Definition at line 209 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_25[4] = { 'a', 'r', 'a', 'm' } [static]
Definition at line 210 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_26[4] = { 'e', 'r', 'a', 'm' } [static]
Definition at line 211 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_27[4] = { 'i', 'r', 'a', 'm' } [static]
Definition at line 212 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_28[4] = { 'a', 'v', 'a', 'm' } [static]
Definition at line 213 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_29[2] = { 'e', 'm' } [static]
Definition at line 214 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_3[4] = { 'a', 'r', 'i', 'a' } [static]
Definition at line 188 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_30[4] = { 'a', 'r', 'e', 'm' } [static]
Definition at line 215 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_31[4] = { 'e', 'r', 'e', 'm' } [static]
Definition at line 216 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_32[4] = { 'i', 'r', 'e', 'm' } [static]
Definition at line 217 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_33[5] = { 'a', 's', 's', 'e', 'm' } [static]
Definition at line 218 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_34[5] = { 'e', 's', 's', 'e', 'm' } [static]
Definition at line 219 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_35[5] = { 'i', 's', 's', 'e', 'm' } [static]
Definition at line 220 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_36[3] = { 'a', 'd', 'o' } [static]
Definition at line 221 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_37[3] = { 'i', 'd', 'o' } [static]
Definition at line 222 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_38[4] = { 'a', 'n', 'd', 'o' } [static]
Definition at line 223 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_39[4] = { 'e', 'n', 'd', 'o' } [static]
Definition at line 224 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_4[4] = { 'e', 'r', 'i', 'a' } [static]
Definition at line 189 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_40[4] = { 'i', 'n', 'd', 'o' } [static]
Definition at line 225 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_41[5] = { 'a', 'r', 'a', '~', 'o' } [static]
Definition at line 226 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_42[5] = { 'e', 'r', 'a', '~', 'o' } [static]
Definition at line 227 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_43[5] = { 'i', 'r', 'a', '~', 'o' } [static]
Definition at line 228 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_44[2] = { 'a', 'r' } [static]
Definition at line 229 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_45[2] = { 'e', 'r' } [static]
Definition at line 230 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_46[2] = { 'i', 'r' } [static]
Definition at line 231 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_47[2] = { 'a', 's' } [static]
Definition at line 232 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_48[4] = { 'a', 'd', 'a', 's' } [static]
Definition at line 233 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_49[4] = { 'i', 'd', 'a', 's' } [static]
Definition at line 234 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_5[4] = { 'i', 'r', 'i', 'a' } [static]
Definition at line 190 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_50[3] = { 'i', 'a', 's' } [static]
Definition at line 235 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_51[5] = { 'a', 'r', 'i', 'a', 's' } [static]
Definition at line 236 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_52[5] = { 'e', 'r', 'i', 'a', 's' } [static]
Definition at line 237 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_53[5] = { 'i', 'r', 'i', 'a', 's' } [static]
Definition at line 238 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_54[4] = { 'a', 'r', 'a', 's' } [static]
Definition at line 239 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_55[4] = { 'e', 'r', 'a', 's' } [static]
Definition at line 240 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_56[4] = { 'i', 'r', 'a', 's' } [static]
Definition at line 241 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_57[4] = { 'a', 'v', 'a', 's' } [static]
Definition at line 242 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_58[2] = { 'e', 's' } [static]
Definition at line 243 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_59[5] = { 'a', 'r', 'd', 'e', 's' } [static]
Definition at line 244 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_6[3] = { 'a', 'r', 'a' } [static]
Definition at line 191 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_60[5] = { 'e', 'r', 'd', 'e', 's' } [static]
Definition at line 245 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_61[5] = { 'i', 'r', 'd', 'e', 's' } [static]
Definition at line 246 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_62[4] = { 'a', 'r', 'e', 's' } [static]
Definition at line 247 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_63[4] = { 'e', 'r', 'e', 's' } [static]
Definition at line 248 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_64[4] = { 'i', 'r', 'e', 's' } [static]
Definition at line 249 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_65[5] = { 'a', 's', 's', 'e', 's' } [static]
Definition at line 250 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_66[5] = { 'e', 's', 's', 'e', 's' } [static]
Definition at line 251 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_67[5] = { 'i', 's', 's', 'e', 's' } [static]
Definition at line 252 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_68[5] = { 'a', 's', 't', 'e', 's' } [static]
Definition at line 253 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_69[5] = { 'e', 's', 't', 'e', 's' } [static]
Definition at line 254 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_7[3] = { 'e', 'r', 'a' } [static]
Definition at line 192 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_70[5] = { 'i', 's', 't', 'e', 's' } [static]
Definition at line 255 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_71[2] = { 'i', 's' } [static]
Definition at line 256 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_72[3] = { 'a', 'i', 's' } [static]
Definition at line 257 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_73[3] = { 'e', 'i', 's' } [static]
Definition at line 258 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_74[5] = { 'a', 'r', 'e', 'i', 's' } [static]
Definition at line 259 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_75[5] = { 'e', 'r', 'e', 'i', 's' } [static]
Definition at line 260 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_76[5] = { 'i', 'r', 'e', 'i', 's' } [static]
Definition at line 261 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_77[6] = { 0xC3, 0xA1, 'r', 'e', 'i', 's' } [static]
Definition at line 262 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_78[6] = { 0xC3, 0xA9, 'r', 'e', 'i', 's' } [static]
Definition at line 263 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_79[6] = { 0xC3, 0xAD, 'r', 'e', 'i', 's' } [static]
Definition at line 264 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_8[3] = { 'i', 'r', 'a' } [static]
Definition at line 193 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_80[7] = { 0xC3, 0xA1, 's', 's', 'e', 'i', 's' } [static]
Definition at line 265 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_81[7] = { 0xC3, 0xA9, 's', 's', 'e', 'i', 's' } [static]
Definition at line 266 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_82[7] = { 0xC3, 0xAD, 's', 's', 'e', 'i', 's' } [static]
Definition at line 267 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_83[6] = { 0xC3, 0xA1, 'v', 'e', 'i', 's' } [static]
Definition at line 268 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_84[5] = { 0xC3, 0xAD, 'e', 'i', 's' } [static]
Definition at line 269 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_85[7] = { 'a', 'r', 0xC3, 0xAD, 'e', 'i', 's' } [static]
Definition at line 270 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_86[7] = { 'e', 'r', 0xC3, 0xAD, 'e', 'i', 's' } [static]
Definition at line 271 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_87[7] = { 'i', 'r', 0xC3, 0xAD, 'e', 'i', 's' } [static]
Definition at line 272 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_88[4] = { 'a', 'd', 'o', 's' } [static]
Definition at line 273 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_89[4] = { 'i', 'd', 'o', 's' } [static]
Definition at line 274 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_9[3] = { 'a', 'v', 'a' } [static]
Definition at line 194 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_90[4] = { 'a', 'm', 'o', 's' } [static]
Definition at line 275 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_91[7] = { 0xC3, 0xA1, 'r', 'a', 'm', 'o', 's' } [static]
Definition at line 276 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_92[7] = { 0xC3, 0xA9, 'r', 'a', 'm', 'o', 's' } [static]
Definition at line 277 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_93[7] = { 0xC3, 0xAD, 'r', 'a', 'm', 'o', 's' } [static]
Definition at line 278 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_94[7] = { 0xC3, 0xA1, 'v', 'a', 'm', 'o', 's' } [static]
Definition at line 279 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_95[6] = { 0xC3, 0xAD, 'a', 'm', 'o', 's' } [static]
Definition at line 280 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_96[8] = { 'a', 'r', 0xC3, 0xAD, 'a', 'm', 'o', 's' } [static]
Definition at line 281 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_97[8] = { 'e', 'r', 0xC3, 0xAD, 'a', 'm', 'o', 's' } [static]
Definition at line 282 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_98[8] = { 'i', 'r', 0xC3, 0xAD, 'a', 'm', 'o', 's' } [static]
Definition at line 283 of file stem_UTF_8_portuguese.cpp.
const symbol s_6_99[4] = { 'e', 'm', 'o', 's' } [static]
Definition at line 284 of file stem_UTF_8_portuguese.cpp.
const symbol s_7[] = { 'a', 't' } [static]
Definition at line 471 of file stem_UTF_8_portuguese.cpp.
const symbol s_7_0[1] = { 'a' } [static]
Definition at line 430 of file stem_UTF_8_portuguese.cpp.
const symbol s_7_1[1] = { 'i' } [static]
Definition at line 431 of file stem_UTF_8_portuguese.cpp.
const symbol s_7_2[1] = { 'o' } [static]
Definition at line 432 of file stem_UTF_8_portuguese.cpp.
const symbol s_7_3[2] = { 'o', 's' } [static]
Definition at line 433 of file stem_UTF_8_portuguese.cpp.
const symbol s_7_4[2] = { 0xC3, 0xA1 } [static]
Definition at line 434 of file stem_UTF_8_portuguese.cpp.
const symbol s_7_5[2] = { 0xC3, 0xAD } [static]
Definition at line 435 of file stem_UTF_8_portuguese.cpp.
const symbol s_7_6[2] = { 0xC3, 0xB3 } [static]
Definition at line 436 of file stem_UTF_8_portuguese.cpp.
const symbol s_8[] = { 'a', 't' } [static]
Definition at line 472 of file stem_UTF_8_portuguese.cpp.
const symbol s_8_0[1] = { 'e' } [static]
Definition at line 449 of file stem_UTF_8_portuguese.cpp.
const symbol s_8_1[2] = { 0xC3, 0xA7 } [static]
Definition at line 450 of file stem_UTF_8_portuguese.cpp.
const symbol s_8_2[2] = { 0xC3, 0xA9 } [static]
Definition at line 451 of file stem_UTF_8_portuguese.cpp.
const symbol s_8_3[2] = { 0xC3, 0xAA } [static]
Definition at line 452 of file stem_UTF_8_portuguese.cpp.
const symbol s_9[] = { 'e' } [static]
Definition at line 473 of file stem_UTF_8_portuguese.cpp.