ME_Model::ME_Model::StringBag Struct Reference
Public Member Functions
int Put (const std::string &i)
std::string Str (const int id) const
int Size () const
void Clear ()
Public Attributes
std::vector< std::string > id2str
Detailed Description
Definition at line 170 of file maxent.h.
Member Function Documentation
void ME_Model::ME_Model::StringBag::Clear () [inline]
Reimplemented from ME_Model::ME_Model::MiniStringBag.
Definition at line 188 of file maxent.h.
References ME_Model::ME_Model::StringBag::id2str, and ME_Model::ME_Model::MiniStringBag::str2id.
int ME_Model::ME_Model::StringBag::Put (const std::string & i) [inline]
Reimplemented from ME_Model::ME_Model::MiniStringBag.
Definition at line 173 of file maxent.h.
References ME_Model::ME_Model::StringBag::id2str, and ME_Model::ME_Model::MiniStringBag::str2id.
Referenced by ME_Model::load_from_array().
int ME_Model::ME_Model::StringBag::Size () const [inline]
Reimplemented from ME_Model::ME_Model::MiniStringBag.
Definition at line 187 of file maxent.h.
References ME_Model::ME_Model::StringBag::id2str.
Referenced by ME_Model::load_from_array().
std::string ME_Model::ME_Model::StringBag::Str (const int id) const [inline]
Definition at line 183 of file maxent.h.
References ME_Model::ME_Model::StringBag::id2str.
Referenced by ME_Model::get_class_label().
Member Data Documentation
std::vector<std::string> ME_Model::ME_Model::StringBag::id2str
Definition at line 172 of file maxent.h.
Referenced by ME_Model::ME_Model::StringBag::Clear(), ME_Model::ME_Model::StringBag::Put(), ME_Model::ME_Model::StringBag::Size(), and ME_Model::ME_Model::StringBag::Str().
The documentation for this struct was generated from the following file:
/disk/workspace-cpp/la-manager/include/pos/maxent.h