ME_Model::ME_Model::ME_FeatureBag Struct Reference
Public Types
typedef __gnu_cxx::hash_map< unsigned int, int > map_type
Public Member Functions
int Put (const ME_Feature &i)
int Id (const ME_Feature &i) const
ME_Feature Feature (int id) const
int Size () const
void Clear ()
Public Attributes
map_type mef2id
std::vector< ME_Feature > id2mef
Detailed Description
Definition at line 81 of file maxent.h.
Member Typedef Documentation
typedef __gnu_cxx::hash_map<unsigned int, int> ME_Model::ME_Model::ME_FeatureBag::map_type
Definition at line 84 of file maxent.h.
Member Function Documentation
void ME_Model::ME_Model::ME_FeatureBag::Clear () [inline]
Definition at line 114 of file maxent.h.
References ME_Model::ME_Model::ME_FeatureBag::id2mef, and ME_Model::ME_Model::ME_FeatureBag::mef2id.
ME_Feature ME_Model::ME_Model::ME_FeatureBag::Feature (int id) const [inline]
Definition at line 107 of file maxent.h.
References ME_Model::ME_Model::ME_FeatureBag::id2mef.
Referenced by ME_Model::update_model_expectation().
int ME_Model::ME_Model::ME_FeatureBag::Id (const ME_Feature & i) const [inline]
Definition at line 100 of file maxent.h.
References ME_Model::ME_Model::ME_Feature::body(), and ME_Model::ME_Model::ME_FeatureBag::mef2id.
Referenced by ME_Model::conditional_probability(), and ME_Model::make_feature_bag().
int ME_Model::ME_Model::ME_FeatureBag::Put (const ME_Feature & i) [inline]
Definition at line 90 of file maxent.h.
References ME_Model::ME_Model::ME_Feature::body(), ME_Model::ME_Model::ME_FeatureBag::id2mef, and ME_Model::ME_Model::ME_FeatureBag::mef2id.
Referenced by ME_Model::load_from_array(), and ME_Model::make_feature_bag().
int ME_Model::ME_Model::ME_FeatureBag::Size () const [inline]
Definition at line 111 of file maxent.h.
References ME_Model::ME_Model::ME_FeatureBag::id2mef.
Referenced by ME_Model::perform_GIS(), ME_Model::perform_LMVM(), and ME_Model::update_model_expectation().
Member Data Documentation
std::vector<ME_Feature> ME_Model::ME_Model::ME_FeatureBag::id2mef
Definition at line 89 of file maxent.h.
Referenced by ME_Model::ME_Model::ME_FeatureBag::Clear(), ME_Model::ME_Model::ME_FeatureBag::Feature(), ME_Model::ME_Model::ME_FeatureBag::Put(), and ME_Model::ME_Model::ME_FeatureBag::Size().
map_type ME_Model::ME_Model::ME_FeatureBag::mef2id
Definition at line 88 of file maxent.h.
Referenced by ME_Model::ME_Model::ME_FeatureBag::Clear(), ME_Model::ME_Model::ME_FeatureBag::Id(), and ME_Model::ME_Model::ME_FeatureBag::Put().
The documentation for this struct was generated from the following file:
/disk/workspace-cpp/la-manager/include/pos/maxent.h