/disk/workspace-cpp/la-manager/test/t_Tokenizer.cpp File Reference
#include <Tokenizer.h>
Functions
int main ()
Function Documentation
int main ()
Definition at line 9 of file t_Tokenizer.cpp.
References la_manager::TokenizeConfig::addAllows(), la_manager::TokenizeConfig::addUnites(), la_manager::Tokenizer::setConfig(), and la_manager::Tokenizer::tokenize().