/disk/workspace-cpp/la-manager/source/stem/utilities.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stem/header.h>
Defines
#define unless(C) if(!(C))
#define CREATE_SIZE 1
Functions
symbol * create_s (void)
void lose_s (symbol *p)
int skip_utf8 (const symbol *p, int c, int lb, int l, int n)
static int get_utf8 (const symbol *p, int c, int l, int *slot)
static int get_b_utf8 (const symbol *p, int c, int lb, int *slot)
int in_grouping_U (struct SN_env *z, const unsigned char *s, int min, int max, int repeat)
int in_grouping_b_U (struct SN_env *z, const unsigned char *s, int min, int max, int repeat)
int out_grouping_U (struct SN_env *z, const unsigned char *s, int min, int max, int repeat)
int out_grouping_b_U (struct SN_env *z, const unsigned char *s, int min, int max, int repeat)
int in_grouping (struct SN_env *z, const unsigned char *s, int min, int max, int repeat)
int in_grouping_b (struct SN_env *z, const unsigned char *s, int min, int max, int repeat)
int out_grouping (struct SN_env *z, const unsigned char *s, int min, int max, int repeat)
int out_grouping_b (struct SN_env *z, const unsigned char *s, int min, int max, int repeat)
int eq_s (struct SN_env *z, int s_size, const symbol *s)
int eq_s_b (struct SN_env *z, int s_size, const symbol *s)
int eq_v (struct SN_env *z, const symbol *p)
int eq_v_b (struct SN_env *z, const symbol *p)
int find_among (struct SN_env *z, const struct among *v, int v_size)
int find_among_b (struct SN_env *z, const struct among *v, int v_size)
static symbol * increase_size (symbol *p, int n)
int replace_s (struct SN_env *z, int c_bra, int c_ket, int s_size, const symbol *s, int *adjptr)
static int slice_check (struct SN_env *z)
int slice_from_s (struct SN_env *z, int s_size, const symbol *s)
int slice_from_v (struct SN_env *z, const symbol *p)
int slice_del (struct SN_env *z)
int insert_s (struct SN_env *z, int bra, int ket, int s_size, const symbol *s)
int insert_v (struct SN_env *z, int bra, int ket, const symbol *p)
symbol * slice_to (struct SN_env *z, symbol *p)
symbol * assign_to (struct SN_env *z, symbol *p)
Define Documentation
#define CREATE_SIZE 1
Definition at line 10 of file utilities.cpp.
Referenced by create_s().
#define unless(C) if(!(C))
Definition at line 8 of file utilities.cpp.
Referenced by in_grouping_b_U(), in_grouping_U(), out_grouping(), out_grouping_b(), out_grouping_b_U(), out_grouping_U(), and replace_s().
Function Documentation
symbol* assign_to (struct SN_env * z, symbol * p)
Definition at line 446 of file utilities.cpp.
References CAPACITY, increase_size(), SN_env::l, SN_env::p, and SET_SIZE.
symbol* create_s (void)
Definition at line 12 of file utilities.cpp.
References CAPACITY, CREATE_SIZE, HEAD, SN_env::p, and SET_SIZE.
Referenced by replace_s(), and SN_create_env().
int eq_s (struct SN_env * z, int s_size, const symbol * s)
Definition at line 194 of file utilities.cpp.
References SN_env::c, SN_env::l, and SN_env::p.
Referenced by eq_v(), r_is_reserved_word(), r_postlude(), and r_prelude().
int eq_s_b (struct SN_env * z, int s_size, const symbol * s)
Definition at line 199 of file utilities.cpp.
References SN_env::c, SN_env::lb, and SN_env::p.
Referenced by eq_v_b(), french_UTF_8_stem(), portuguese_UTF_8_stem(), r_adjectival(), r_append_U_to_stems_ending_with_d_or_g(), r_attached_pronoun(), r_case_ending(), r_check_vowel_harmony(), r_e_ending(), r_en_ending(), r_main_suffix(), r_mark_ki(), r_mark_suffix_with_optional_n_consonant(), r_mark_suffix_with_optional_s_consonant(), r_mark_suffix_with_optional_y_consonant(), r_mark_yken(), r_other_endings(), r_other_suffix(), r_perfective_gerund(), r_possessive(), r_residual_form(), r_residual_suffix(), r_standard_suffix(), r_step_0(), r_Step_1c(), r_Step_2(), r_Step_4(), r_Step_5(), r_t_plural(), r_tidy(), r_tidy_up(), r_un_accent(), r_verb(), r_verb_suffix(), r_VI(), r_vowel_suffix(), r_y_verb_suffix(), and russian_UTF_8_stem().
int eq_v (struct SN_env * z, const symbol * p)
Definition at line 204 of file utilities.cpp.
References eq_s(), and SIZE.
int eq_v_b (struct SN_env * z, const symbol * p)
Definition at line 208 of file utilities.cpp.
References eq_s_b(), and SIZE.
Referenced by r_tidy(), and r_undouble().
int find_among (struct SN_env * z, const struct among * v, int v_size)
Definition at line 212 of file utilities.cpp.
References SN_env::c, among::function, SN_env::l, SN_env::p, among::result, among::s, among::s_size, and among::substring_i.
Referenced by r_exception1(), r_mark_regions(), r_postlude(), and r_prelude().
int find_among_b (struct SN_env * z, const struct among * v, int v_size)
Definition at line 272 of file utilities.cpp.
References SN_env::c, among::function, SN_env::lb, SN_env::p, among::result, among::s, among::s_size, and among::substring_i.
Referenced by r_adjectival(), r_adjective(), r_attached_pronoun(), r_case(), r_case_ending(), r_case_other(), r_case_special(), r_combo_suffix(), r_consonant_pair(), r_derivational(), r_double(), r_exception2(), r_factive(), r_i_plural(), r_i_verb_suffix(), r_instrum(), r_LONG(), r_main_suffix(), r_mark_cAsInA(), r_mark_DA(), r_mark_DAn(), r_mark_DUr(), r_mark_lAr(), r_mark_lArI(), r_mark_nA(), r_mark_ncA(), r_mark_ndA(), r_mark_ndAn(), r_mark_nU(), r_mark_nUn(), r_mark_nUz(), r_mark_possessives(), r_mark_sUn(), r_mark_sUnUz(), r_mark_yA(), r_mark_yDU(), r_mark_ylA(), r_mark_ymUs_(), r_mark_ysA(), r_mark_yUm(), r_mark_yUz(), r_noun(), r_other_endings(), r_other_suffix(), r_owned(), r_particle_etc(), r_perfective_gerund(), r_plur_owner(), r_plural(), r_possessive(), r_post_process_last_consonants(), r_reflexive(), r_residual_form(), r_residual_suffix(), r_sing_owner(), r_standard_suffix(), r_step_0(), r_Step_1a(), r_Step_1b(), r_Step_2(), r_Step_3(), r_Step_4(), r_Step_5(), r_t_plural(), r_tidy_up(), r_un_double(), r_undouble(), r_v_ending(), r_verb(), r_verb_suffix(), r_vowel_suffix(), and r_y_verb_suffix().
static int get_b_utf8 (const symbol * p, int c, int lb, int * slot) [static]
Definition at line 82 of file utilities.cpp.
Referenced by in_grouping_b_U(), and out_grouping_b_U().
static int get_utf8 (const symbol * p, int c, int l, int * slot) [static]
Definition at line 68 of file utilities.cpp.
Referenced by in_grouping_U(), and out_grouping_U().
int in_grouping (struct SN_env * z, const unsigned char * s, int min, int max, int repeat)
Definition at line 146 of file utilities.cpp.
References SN_env::c, SN_env::l, and SN_env::p.
int in_grouping_b (struct SN_env * z, const unsigned char * s, int min, int max, int repeat)
Definition at line 158 of file utilities.cpp.
References SN_env::c, SN_env::lb, and SN_env::p.
int in_grouping_b_U (struct SN_env * z, const unsigned char * s, int min, int max, int repeat)
Definition at line 108 of file utilities.cpp.
References SN_env::c, get_b_utf8(), SN_env::lb, SN_env::p, and unless.
Referenced by r_case_ending(), r_main_suffix(), r_mark_sU(), r_mark_suffix_with_optional_n_consonant(), r_mark_suffix_with_optional_s_consonant(), r_mark_suffix_with_optional_U_vowel(), r_mark_suffix_with_optional_y_consonant(), r_mark_yU(), r_particle_etc(), r_shortv(), r_standard_suffix(), r_Step_2(), r_t_plural(), r_tidy(), r_VI(), and r_vowel_suffix().
int in_grouping_U (struct SN_env * z, const unsigned char * s, int min, int max, int repeat)
Definition at line 96 of file utilities.cpp.
References SN_env::c, get_utf8(), SN_env::l, SN_env::p, and unless.
Referenced by r_mark_regions(), and r_prelude().
static symbol* increase_size (symbol * p, int n) [static]
Definition at line 329 of file utilities.cpp.
References CAPACITY, HEAD, and lose_s().
Referenced by assign_to(), replace_s(), and slice_to().
int insert_s (struct SN_env * z, int bra, int ket, int s_size, const symbol * s)
Definition at line 410 of file utilities.cpp.
References SN_env::bra, SN_env::ket, and replace_s().
Referenced by r_append_U_to_stems_ending_with_d_or_g(), and r_Step_1b().
int insert_v (struct SN_env * z, int bra, int ket, const symbol * p)
Definition at line 419 of file utilities.cpp.
References SN_env::bra, SN_env::ket, replace_s(), and SIZE.
void lose_s (symbol * p)
Definition at line 22 of file utilities.cpp.
References HEAD.
Referenced by increase_size(), slice_to(), and SN_close_env().
int out_grouping (struct SN_env * z, const unsigned char * s, int min, int max, int repeat)
Definition at line 170 of file utilities.cpp.
References SN_env::c, SN_env::l, SN_env::p, and unless.
int out_grouping_b (struct SN_env * z, const unsigned char * s, int min, int max, int repeat)
Definition at line 182 of file utilities.cpp.
References SN_env::c, SN_env::lb, SN_env::p, and unless.
int out_grouping_b_U (struct SN_env * z, const unsigned char * s, int min, int max, int repeat)
Definition at line 132 of file utilities.cpp.
References SN_env::c, get_b_utf8(), SN_env::lb, SN_env::p, and unless.
Referenced by r_append_U_to_stems_ending_with_d_or_g(), r_case_ending(), r_check_vowel_harmony(), r_e_ending(), r_en_ending(), r_i_verb_suffix(), r_main_suffix(), r_mark_suffix_with_optional_U_vowel(), r_residual_suffix(), r_shortv(), r_standard_suffix(), r_Step_1a(), r_Step_1b(), r_Step_1c(), r_tidy(), r_un_accent(), r_undouble(), and r_verb_suffix().
int out_grouping_U (struct SN_env * z, const unsigned char * s, int min, int max, int repeat)
Definition at line 120 of file utilities.cpp.
References SN_env::c, get_utf8(), SN_env::l, SN_env::p, and unless.
Referenced by r_mark_regions(), and r_more_than_one_syllable_word().
int replace_s (struct SN_env * z, int c_bra, int c_ket, int s_size, const symbol * s, int * adjptr)
Definition at line 348 of file utilities.cpp.
References SN_env::c, CAPACITY, create_s(), increase_size(), SN_env::l, SN_env::p, SET_SIZE, SIZE, and unless.
Referenced by insert_s(), insert_v(), slice_from_s(), and SN_set_current().
int skip_utf8 (const symbol * p, int c, int lb, int l, int n)
Definition at line 35 of file utilities.cpp.
Referenced by english_UTF_8_stem(), r_case_ending(), r_consonant_pair(), r_is_reserved_word(), r_mark_regions(), r_mark_suffix_with_optional_n_consonant(), r_mark_suffix_with_optional_s_consonant(), r_mark_suffix_with_optional_U_vowel(), r_mark_suffix_with_optional_y_consonant(), r_postlude(), r_prelude(), r_standard_suffix(), r_Step_1a(), r_Step_1b(), r_tidy(), r_un_double(), and r_undouble().
static int slice_check (struct SN_env * z) [static]
Definition at line 380 of file utilities.cpp.
References SN_env::bra, debug(), SN_env::ket, SN_env::l, SN_env::p, and SIZE.
Referenced by slice_from_s(), and slice_to().
int slice_del (struct SN_env * z)
Definition at line 406 of file utilities.cpp.
References slice_from_s().
Referenced by portuguese_UTF_8_stem(), r_adjectival(), r_adjective(), r_attached_pronoun(), r_case(), r_case_ending(), r_case_other(), r_consonant_pair(), r_derivational(), r_e_ending(), r_en_ending(), r_factive(), r_i_plural(), r_i_verb_suffix(), r_instrum(), r_main_suffix(), r_noun(), r_other_endings(), r_other_suffix(), r_owned(), r_particle_etc(), r_perfective_gerund(), r_plur_owner(), r_plural(), r_possessive(), r_prelude(), r_reflexive(), r_residual_form(), r_residual_suffix(), r_sing_owner(), r_standard_suffix(), r_stem_nominal_verb_suffixes(), r_stem_noun_suffixes(), r_stem_suffix_chain_before_ki(), r_step_0(), r_Step_1a(), r_Step_1b(), r_Step_2(), r_Step_3(), r_Step_4(), r_Step_5(), r_t_plural(), r_tidy(), r_tidy_up(), r_un_double(), r_undouble(), r_verb(), r_verb_suffix(), r_vowel_suffix(), r_y_verb_suffix(), and russian_UTF_8_stem().
int slice_from_s (struct SN_env * z, int s_size, const symbol * s)
Definition at line 397 of file utilities.cpp.
References SN_env::bra, SN_env::ket, replace_s(), and slice_check().
Referenced by french_UTF_8_stem(), r_attached_pronoun(), r_case_other(), r_case_special(), r_combo_suffix(), r_exception1(), r_main_suffix(), r_other_suffix(), r_owned(), r_plur_owner(), r_plural(), r_possessive(), r_post_process_last_consonants(), r_postlude(), r_prelude(), r_residual_form(), r_residual_suffix(), r_sing_owner(), r_standard_suffix(), r_step_0(), r_Step_1a(), r_Step_1b(), r_Step_1c(), r_Step_2(), r_Step_3(), r_un_accent(), r_v_ending(), slice_del(), and slice_from_v().
int slice_from_v (struct SN_env * z, const symbol * p)
Definition at line 402 of file utilities.cpp.
References SIZE, and slice_from_s().
symbol* slice_to (struct SN_env * z, symbol * p)
Definition at line 428 of file utilities.cpp.
References SN_env::bra, CAPACITY, increase_size(), SN_env::ket, lose_s(), SN_env::p, SET_SIZE, and slice_check().
Referenced by r_tidy(), and r_undouble().