WK_Eojul Class Reference
a class for a Eojul that is stored KMA results.
#include <wk_eojul.h>
Public Member Functions
virtual ~WK_Eojul ()
virtual void initialize (bool willBeTheDefaultState=false)=0
This function initializes a WK_Eojul object.
virtual void setString (const char *pString)=0
This function sets a string in a WK_Eojul object.
virtual char * getString (void)=0
This function gets a string in a WK_Eojul object.
virtual int getListSize (void)=0
This function gets the number of the list of morphological analyzed results in a WK_Eojul object.
virtual int getCount (int nPos)=0
This function gets the number of morphemes in each list of morphological analyzed results.
virtual char * getLexicon (int nPos, int nIdx)=0
This function gets the string of each morpheme in each list of morphological analyzed results.
virtual int getPOS (int nPos, int nIdx)=0
This function gets the POS value of each morpheme in each list of morphological analyzed results.
virtual char * getStrPOS (int nPos, int nIdx)=0
This function gets the POS string of each morpheme in each list of morphological analyzed results.
virtual bool isIndexWord (int nPos, int nIdx)=0
This function gets whether each morpheme in each list of morphological analyzed results is an index word or not.
virtual double getScore (int nPos)=0
This function gets the score of each list of morphological analyzed results.
virtual int getOneBestIndex (void)=0
This function gets the index number of the list, which has the most high score in morphological analyzed results.
virtual int getLinkedIndex (int nPos)=0
This function gets the index number of the list, which has the analysis result composed affix.
Static Public Member Functions
static WK_Eojul * createObject (void)
This function creates a WK_Eojul object.
Detailed Description
a class for a Eojul that is stored KMA results.
Date: 2008-10-31
Author: HeeGeun Park
Definition at line 15 of file wk_eojul.h.
Constructor & Destructor Documentation
WK_Eojul::~WK_Eojul () [virtual]
Definition at line 13 of file wk_eojul.cpp.
Member Function Documentation
WK_Eojul * WK_Eojul::createObject (void) [static]
This function creates a WK_Eojul object.
Date: 2008-10-31
Author: HeeGeun Park
Returns: a pointer of a WK_Eojul object.
Definition at line 17 of file wk_eojul.cpp.
Referenced by la_manager::KoreanNounFilter::KoreanNounFilter().
virtual int WK_Eojul::getCount (int nPos) [pure virtual]
This function gets the number of morphemes in each list of morphological analyzed results.
Date: 2008-11-04
Author: HeeGeun Park
Parameters:
nPos an integer - the index number of the list of morphological analyzed results.
Returns: an integer - the number of morphemes in each list of morphological analyzed results.
Implemented in kmaOrange::Eojul.
Referenced by la_manager::KoreanNounFilter::analyze().
virtual char* WK_Eojul::getLexicon (int nPos, int nIdx) [pure virtual]
This function gets the string of each morpheme in each list of morphological analyzed results.
Date: 2008-11-04
Author: HeeGeun Park
Parameters:
nPos an integer - the index number of the list of morphological analyzed results.
nIdx an integer - the index number of the morpheme in the list of morphological analyzed results.
Returns: a pointer of a character - the string of the nIdx-th morpheme in the nPos-th list of morphological analyzed results.
Implemented in kmaOrange::Eojul.
virtual int WK_Eojul::getLinkedIndex (int nPos) [pure virtual]
This function gets the index number of the list, which has the analysis result composed affix.
Date: 2009-01-05
Author: HeeGeun Park
Parameters:
nPos an integer - the index number of the list of morphological analyzed results.
Returns: an integer - the index number of the list, which has the analysis result composed affix.
Implemented in kmaOrange::Eojul.
virtual int WK_Eojul::getListSize (void) [pure virtual]
This function gets the number of the list of morphological analyzed results in a WK_Eojul object.
Date: 2008-11-04
Author: HeeGeun Park
Returns: an integer - the number of the lists of morphological analyzed results.
Implemented in kmaOrange::Eojul.
virtual int WK_Eojul::getOneBestIndex (void) [pure virtual]
This function gets the index number of the list, which has the most high score in morphological analyzed results.
Date: 2008-11-04
Author: HeeGeun Park
Returns: an integer - the index number of the list, which has the most high score in morphological analyzed results.
Implemented in kmaOrange::Eojul.
Referenced by la_manager::KoreanNounFilter::analyze().
virtual int WK_Eojul::getPOS (int nPos, int nIdx) [pure virtual]
This function gets the POS value of each morpheme in each list of morphological analyzed results.
Date: 2008-11-04
Author: HeeGeun Park
Parameters:
nPos an integer - the index number of the list of morphological analyzed results.
nIdx an integer - the index number of the morpheme in the list of morphological analyzed results.
Returns: an integer - the POS value of the nIdx-th morpheme in the nPos-th list of morphological analyzed results.
Implemented in kmaOrange::Eojul.
Referenced by la_manager::KoreanNounFilter::analyze().
virtual double WK_Eojul::getScore (int nPos) [pure virtual]
This function gets the score of each list of morphological analyzed results.
Date: 2008-11-04
Author: HeeGeun Park
Parameters:
nPos an integer - the index number of the list of morphological analyzed results.
Returns: a double - the score of the nPos-th list of morphological analyzed results.
Implemented in kmaOrange::Eojul.
virtual char* WK_Eojul::getString (void) [pure virtual]
This function gets a string in a WK_Eojul object.
Date: 2008-11-04
Author: HeeGeun Park
Returns: a pointer of a character - a set string in a WK_Eojul object.
Implemented in kmaOrange::Eojul.
virtual char* WK_Eojul::getStrPOS (int nPos, int nIdx) [pure virtual]
This function gets the POS string of each morpheme in each list of morphological analyzed results.
Date: 2008-11-04
Author: HeeGeun Park
Parameters:
nPos an integer - the index number of the list of morphological analyzed results.
nIdx an integer - the index number of the morpheme in the list of morphological analyzed results.
Returns: a pointer of a character - the POS string of the nIdx-th morpheme in the nPos-th list of morphological analyzed results.
Implemented in kmaOrange::Eojul.
virtual void WK_Eojul::initialize (bool willBeTheDefaultState = false) [pure virtual]
This function initializes a WK_Eojul object.
Date: 2008-10-31
Author: HeeGeun Park
Parameters:
willBeTheDefaultState a boolean.
 true - it entirely sets a Eojul object to initial statement.
 false - it only sets values in a Eojul object.
Implemented in kmaOrange::Eojul.
Referenced by la_manager::KoreanNounFilter::KoreanNounFilter().
virtual bool WK_Eojul::isIndexWord (int nPos, int nIdx) [pure virtual]
This function gets whether each morpheme in each list of morphological analyzed results is an index word or not.
Date: 2008-11-04
Author: HeeGeun Park
Parameters:
nPos an integer - the index number of the list of morphological analyzed results.
nIdx an integer - the index number of the morpheme in the list of morphological analyzed results.
Returns: a boolean.
 true - index word.
 false - no index word.
Implemented in kmaOrange::Eojul.
virtual void WK_Eojul::setString (const char * pString) [pure virtual]
This function sets a string in a WK_Eojul object.
Date: 2008-11-04
Author: HeeGeun Park
Parameters:
pString a pointer of a character - a setting string based on a word.
Implemented in kmaOrange::Eojul.
Referenced by la_manager::KoreanNounFilter::analyze().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/kma/wk_eojul.h
/disk/workspace-cpp/la-manager/source/kma/wk_eojul.cpp