kmaOrange::AuxVerb Class Reference
This class manages auxiliary verbs.
#include <AuxVerb.h>
Public Member Functions
AuxVerb ()
This function is a constructor of AuxVerb object.
~AuxVerb ()
This function is a destructor of AuxVerb object.
int setAVList ()
This function creates and initializes a WK_DaTrie object.
int setAVInfo (AVInfo &avInfo, int pos)
This function sets contents of static array AVInfo structure into a WK_DaTrie object.
int searchNgetInfoFromAvTrie (const StringEx &strex, InfoBuffer &infoBuffer, int len=0)
This function searches a WK_DaTrie object for input string.
int searchNgetInfoFromAvTrie (const char *str, InfoBuffer &infoBuffer, int len=0)
InfoBuffer * searchNgetInfoFromAvTrie (const StringEx &strex, int len=0)
This function searches a WK_DaTrie object for input string.
InfoBuffer * searchNgetInfoFromAvTrie (const char *str, int len=0)
This function searches a WK_DaTrie object for input string.
AVInfo * getAVInfo (int pos)
This function gets contents of static array AVInfo structure.
Public Attributes
WK_DaTrie _avTrie
a WK_DaTrie object of auxiliary verbs.
InfoBuffer _infoBuffer
temporary buffer.
Static Public Attributes
static AVInfo _avInfoPoolList []
the list of information of auxiliary verbs.
Detailed Description
This class manages auxiliary verbs.
Date: 2008-11-04
Author: YoungMin Ahn & HeeGeun Park
Definition at line 37 of file AuxVerb.h.
Constructor & Destructor Documentation
AuxVerb::AuxVerb ()
This function is a constructor of AuxVerb object.
Date: 2008-11-04
Author: YoungMin Ahn & HeeGeun Park
Definition at line 28 of file AuxVerb.cpp.
References setAVList().
AuxVerb::~AuxVerb ()
This function is a destructor of AuxVerb object.
Date: 2008-11-04
Author: YoungMin Ahn & HeeGeun Park
Definition at line 33 of file AuxVerb.cpp.
Member Function Documentation
AVInfo * AuxVerb::getAVInfo (int pos)
This function gets contents of static array AVInfo structure.
Date: 2008-11-04
Author: YoungMin Ahn & HeeGeun Park
Parameters:
pos an integer - the index number of static array AVInfo structure.
Returns: a pointer of AVInfo structure - contents of static array AVInfo structure.
Definition at line 37 of file AuxVerb.cpp.
References _avInfoPoolList.
InfoBuffer * AuxVerb::searchNgetInfoFromAvTrie (const char * str, int len = 0) [inline]
This function searches a WK_DaTrie object for input string.
Date: 2008-11-04
Author: YoungMin Ahn & HeeGeun Park
Parameters:
str a pointer of a character - input string.
len an integer - the length of input string.
Returns: a pointer of InfoBuffer object - temporary storage.
Definition at line 145 of file AuxVerb.cpp.
References _avTrie, _infoBuffer, kmaOrange::InfoBuffer::_posBuffer, kmaOrange::InfoBuffer::appendInfo(), kmaOrange::SyllableInfo::coda, CODA, kmaOrange::WK_DaTrie::findNode(), kmaOrange::WK_DaTrie_Node::getData(), kmaOrange::ExCP949::getInfo(), hlL, hlN, kmaOrange::SyllableInfo::info, and kmaOrange::WK_DaTrie_Node::mpData.
InfoBuffer * AuxVerb::searchNgetInfoFromAvTrie (const StringEx & strex, int len = 0)
This function searches a WK_DaTrie object for input string.
Date: 2008-11-04
Author: YoungMin Ahn & HeeGeun Park
Parameters:
strex an indirect referncing pointer of StringEx object - input string.
len an integer - the length of input string.
Returns: a pointer of InfoBuffer object - temporary storage.
Definition at line 140 of file AuxVerb.cpp.
References StringEx::buffer(), StringEx::length(), and searchNgetInfoFromAvTrie().
int AuxVerb::searchNgetInfoFromAvTrie (const char * str, InfoBuffer & infoBuffer, int len = 0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 104 of file AuxVerb.cpp.
References _avTrie, kmaOrange::InfoBuffer::appendInfo(), kmaOrange::SyllableInfo::coda, CODA, kmaOrange::WK_DaTrie::findNode(), kmaOrange::WK_DaTrie_Node::getData(), kmaOrange::ExCP949::getInfo(), hlL, hlN, kmaOrange::SyllableInfo::info, kmaOrange::InfoBuffer::initialize(), and kmaOrange::WK_DaTrie_Node::mpData.
int AuxVerb::searchNgetInfoFromAvTrie (const StringEx & strex, InfoBuffer & infoBuffer, int len = 0)
This function searches a WK_DaTrie object for input string.
Date: 2008-11-04
Author: YoungMin Ahn & HeeGeun Park
Parameters:
strex an indirect referncing pointer of StringEx object - input string.
infoBuffer an indirect referncing pointer of InfoBuffer object - temporary storage.
len an integer - the length of input string.
Returns: an integer.
 0 - fail.
 1 - success.
Definition at line 99 of file AuxVerb.cpp.
References StringEx::buffer(), and StringEx::length().
Referenced by kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::checkNanalyzeContraction_YUR(), kmaOrange::MAnalyzer::checkNanalyzeElision_hlL(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_HIUNG(), kmaOrange::MAnalyzer::checkNanalyzePreEomi(), kmaOrange::MAnalyzer::checkNanalyzeV_(), kmaOrange::MAnalyzer::checkNanalyzeXSDecliable(), and searchNgetInfoFromAvTrie().
int AuxVerb::setAVInfo (AVInfo & avInfo, int pos)
This function sets contents of static array AVInfo structure into a WK_DaTrie object.
Date: 2008-11-04
Author: YoungMin Ahn & HeeGeun Park
Parameters:
avInfo an indirect referncing pointer of AVInfo structure - the list of auxiliary verbs and these information.
pos an integer - the index number of the list of auxiliary verbs and these information.
Returns: an integer.
 0 - fail.
 1 - success.
Definition at line 62 of file AuxVerb.cpp.
References _avTrie, kmaOrange::WK_DaTrie_Node::getData(), kmaOrange::WK_DaTrie::insertKey(), kmaOrange::WK_DaTrie_Node::setData(), and kmaOrange::AVInfo::transForm.
Referenced by setAVList().
int AuxVerb::setAVList ()
This function creates and initializes a WK_DaTrie object.
Date: 2008-11-04
Author: YoungMin Ahn & HeeGeun Park
Returns: an integer.
 0 - fail.
 1 - success.
Definition at line 42 of file AuxVerb.cpp.
References _avInfoPoolList, _avTrie, kmaOrange::WK_DaTrie::create(), and setAVInfo().
Referenced by AuxVerb().
Member Data Documentation
AVInfo kmaOrange::AuxVerb::_avInfoPoolList[] [static]
the list of information of auxiliary verbs.
Definition at line 41 of file AuxVerb.h.
Referenced by getAVInfo(), and setAVList().
WK_DaTrie kmaOrange::AuxVerb::_avTrie
a WK_DaTrie object of auxiliary verbs.
Definition at line 40 of file AuxVerb.h.
Referenced by searchNgetInfoFromAvTrie(), setAVInfo(), and setAVList().
InfoBuffer kmaOrange::AuxVerb::_infoBuffer
temporary buffer.
Definition at line 43 of file AuxVerb.h.
Referenced by searchNgetInfoFromAvTrie().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/kma/AuxVerb.h
/disk/workspace-cpp/la-manager/source/kma/AuxVerb.cpp