kmaOrange::PreFinalEomi Class Reference
This class manages prefinal endings.
#include <PreFinalEomi.h>
Public Member Functions
PreFinalEomi ()
This function is a constructor of PreFinalEomi object.
~PreFinalEomi ()
This function is a destructor of PreFinalEomi object.
int setEPList ()
This function creates and initializes a WK_DaTrie object.
int setEPInfo (EPInfo &epInfo, int pos)
This function sets contents of static array EPInfo structure into a WK_DaTrie object.
int searchNgetInfoFromEpTrie (const StringEx &strex, InfoBuffer &infoBuffer, int len=0)
This function searches a WK_DaTrie object for input string.
int searchNgetInfoFromEpTrie (const char *str, InfoBuffer &infoBuffer, int len=0)
InfoBuffer * searchNgetInfoFromEpTrie (const StringEx &strex, int len=0)
This function searches a WK_DaTrie object for input string.
InfoBuffer * searchNgetInfoFromEpTrie (const char *str, int len=0)
EPInfo * getEPInfo (int pos)
This function gets contents of static array EPInfo structure.
Public Attributes
WK_DaTrie _epTrie
a WK_DaTrie object of prefinal endings.
InfoBuffer _infoBuffer
temporary buffer.
Static Public Attributes
static EPInfo _epInfoPoolList []
the list of information of prefinal endings.
Detailed Description
This class manages prefinal endings.
Date: 2008-11-07
Author: YoungMin Ahn & HeeGeun Park
Definition at line 38 of file PreFinalEomi.h.
Constructor & Destructor Documentation
PreFinalEomi::PreFinalEomi ()
This function is a constructor of PreFinalEomi object.
Date: 2008-11-07
Author: YoungMin Ahn & HeeGeun Park
Definition at line 55 of file PreFinalEomi.cpp.
References setEPList().
PreFinalEomi::~PreFinalEomi ()
This function is a destructor of PreFinalEomi object.
Date: 2008-11-07
Author: YoungMin Ahn & HeeGeun Park
Definition at line 60 of file PreFinalEomi.cpp.
Member Function Documentation
EPInfo * PreFinalEomi::getEPInfo (int pos)
This function gets contents of static array EPInfo structure.
Date: 2008-11-07
Author: YoungMin Ahn & HeeGeun Park
Parameters:
pos an integer - the index number of static array EPInfo structure.
Returns: a pointer of EPInfo structure - contents of static array EPInfo structure.
Definition at line 64 of file PreFinalEomi.cpp.
References _epInfoPoolList.
InfoBuffer * PreFinalEomi::searchNgetInfoFromEpTrie (const char * str, int len = 0) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 179 of file PreFinalEomi.cpp.
References _epTrie, _infoBuffer, kmaOrange::InfoBuffer::_posBuffer, kmaOrange::InfoBuffer::appendInfo(), kmaOrange::WK_DaTrie::findNode(), kmaOrange::WK_DaTrie_Node::getData(), and kmaOrange::WK_DaTrie_Node::mpData.
InfoBuffer * PreFinalEomi::searchNgetInfoFromEpTrie (const StringEx & strex, int len = 0)
This function searches a WK_DaTrie object for input string.
Date: 2008-11-07
Author: YoungMin Ahn & HeeGeun Park
Parameters:
strex an indirect referncing pointer of StringEx object - input string.
len an integer - the length of input string.
Returns: a pointer of InfoBuffer object - temporary storage.
Definition at line 174 of file PreFinalEomi.cpp.
References StringEx::buffer(), StringEx::length(), and searchNgetInfoFromEpTrie().
int PreFinalEomi::searchNgetInfoFromEpTrie (const char * str, InfoBuffer & infoBuffer, int len = 0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 131 of file PreFinalEomi.cpp.
References _epTrie, kmaOrange::InfoBuffer::appendInfo(), kmaOrange::WK_DaTrie::findNode(), kmaOrange::WK_DaTrie_Node::getData(), kmaOrange::InfoBuffer::initialize(), and kmaOrange::WK_DaTrie_Node::mpData.
int PreFinalEomi::searchNgetInfoFromEpTrie (const StringEx & strex, InfoBuffer & infoBuffer, int len = 0)
This function searches a WK_DaTrie object for input string.
Date: 2008-11-07
Author: YoungMin Ahn & HeeGeun Park
Parameters:
strex an indirect referncing pointer of StringEx object - input string.
infoBuffer an indirect referncing pointer of InfoBuffer object - temporary storage.
len an integer - the length of input string.
Returns: an integer.
 0 - fail.
 1 - success.
Definition at line 126 of file PreFinalEomi.cpp.
References StringEx::buffer(), and StringEx::length().
Referenced by kmaOrange::MAnalyzer::checkNanalyzePreEomi(), and searchNgetInfoFromEpTrie().
int PreFinalEomi::setEPInfo (EPInfo & epInfo, int pos)
This function sets contents of static array EPInfo structure into a WK_DaTrie object.
Date: 2008-11-07
Author: YoungMin Ahn & HeeGeun Park
Parameters:
epInfo an indirect referncing pointer of EPInfo structure - the list of prefinal endings and these information.
pos an integer - the index number of the list of prefinal endings and these information.
Returns: an integer.
 0 - fail.
 1 - success.
Definition at line 89 of file PreFinalEomi.cpp.
References _epTrie, kmaOrange::WK_DaTrie_Node::getData(), kmaOrange::WK_DaTrie::insertKey(), kmaOrange::WK_DaTrie_Node::setData(), and kmaOrange::EPInfo::transForm.
Referenced by setEPList().
int PreFinalEomi::setEPList ()
This function creates and initializes a WK_DaTrie object.
Date: 2008-11-07
Author: YoungMin Ahn & HeeGeun Park
Returns: an integer.
 0 - fail.
 1 - success.
Definition at line 69 of file PreFinalEomi.cpp.
References _epInfoPoolList, _epTrie, kmaOrange::WK_DaTrie::create(), and setEPInfo().
Referenced by PreFinalEomi().
Member Data Documentation
EPInfo kmaOrange::PreFinalEomi::_epInfoPoolList[] [static]
the list of information of prefinal endings.
Definition at line 42 of file PreFinalEomi.h.
Referenced by getEPInfo(), and setEPList().
WK_DaTrie kmaOrange::PreFinalEomi::_epTrie
a WK_DaTrie object of prefinal endings.
Definition at line 41 of file PreFinalEomi.h.
Referenced by searchNgetInfoFromEpTrie(), setEPInfo(), and setEPList().
InfoBuffer kmaOrange::PreFinalEomi::_infoBuffer
temporary buffer.
Definition at line 44 of file PreFinalEomi.h.
Referenced by searchNgetInfoFromEpTrie().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/kma/PreFinalEomi.h
/disk/workspace-cpp/la-manager/source/kma/PreFinalEomi.cpp