kmaOrange::SynonymContainer Class Reference
a class has and manages the list of synonym lists.
#include <Synonym.h>
Public Member Functions
SynonymContainer ()
This function is a constructor of SynonymContainer object.
~SynonymContainer ()
This function is a destructor of SynonymContainer object.
int createTrie ()
This function creates and initializes a WK_DaTrie object.
int loadSynonym (StringEx pathDic=`./knowledge`, StringEx nameDic=`synonym.txt`, StringEx strID=`SYN`)
This function loads contents of the synonym dictionary file into a WK_DaTrie object.
int loadSynonym (const char *pathDic, const char *nameDic)
void setSynonymDelimiter (const char *delim)
This function sets the delimiter between synonym entries in a synonym list.
void setWordDelimiter (const char *delim)
This function sets the delimiter between words in a synonym entry.
int searchNgetInfoFromSynonymTrie (const char *str, WK_Synonym *pwks)
This function searches a WK_DaTrie object for input string and gets contents of this WK_DaTrie object.
Public Attributes
vector< EntryNInfo > _synonymList
the list of synonym lists.
vector< vector< int > > _infoList
the list of synonym information.
Private Member Functions
int insertSynonym (EntryNInfo &ei, int posHeadword, const char *tPos)
This function inserts loaded contents of the synonym dictionary file into a WK_DaTrie object.
Private Attributes
WK_DaTrie _synonymTrie
a WK_DaTrie object of the synonym dictionary.
StringEx _synonymDelim
the first delimiter between synonym entries in a synonym list.
StringEx _wordDelim
the first delimiter between words in a synonym entry.
StringEx _ts
the delimiter between synonym entries in a synonym list.
StringEx _tw
the delimiter between words in a synonym entry.
Detailed Description
a class has and manages the list of synonym lists.
Date: 2008-11-03
Author: YoungMin Ahn
Definition at line 166 of file Synonym.h.
Constructor & Destructor Documentation
SynonymContainer::SynonymContainer ()
This function is a constructor of SynonymContainer object.
Date: 2008-11-03
Author: YoungMin Ahn
Definition at line 13 of file Synonym.cpp.
References _synonymDelim, and _wordDelim.
SynonymContainer::~SynonymContainer ()
This function is a destructor of SynonymContainer object.
Date: 2008-11-03
Author: YoungMin Ahn
Definition at line 19 of file Synonym.cpp.
Member Function Documentation
int SynonymContainer::createTrie ()
This function creates and initializes a WK_DaTrie object.
Date: 2008-11-03
Author: YoungMin Ahn
Returns: an integer.
 0 - fail.
 1 - success.
Definition at line 35 of file Synonym.cpp.
References _synonymTrie, kmaOrange::WK_DaTrie::create(), and TRIE_EXTEND_SIZE.
Referenced by loadSynonym().
int SynonymContainer::insertSynonym (EntryNInfo & ei, int posHeadword, const char * tPos) [private]
This function inserts loaded contents of the synonym dictionary file into a WK_DaTrie object.
Date: 2008-11-03
Author: YoungMin Ahn
Parameters:
ei a indirect referncing pointer of EntryNInfo object.
posHeadword an integer - the position of a headword of the synonym list.
tPos a pointer of a constant character - the string of the synonym list entry.
Returns: an integer.
 1 - input string is a synonym.
 0 - input string is not a synonym.
Definition at line 47 of file Synonym.cpp.
References _infoList, _synonymList, _synonymTrie, _wordDelim, StringEx::buffer(), kmaOrange::EntryNInfo::entry, kmaOrange::WK_DaTrie_Node::getData(), HEADWORD_FLAG, kmaOrange::EntryNInfo::info, kmaOrange::WK_DaTrie::insertKey(), OVERLAP_FLAG, StringEx::replaceString(), and kmaOrange::WK_DaTrie_Node::setData().
Referenced by loadSynonym().
int kmaOrange::SynonymContainer::loadSynonym (const char * pathDic, const char * nameDic) [inline, virtual]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Implements WK_SynonymContainer.
Definition at line 208 of file Synonym.h.
References loadSynonym().
Referenced by loadSynonym().
int SynonymContainer::loadSynonym (StringEx pathDic = `./knowledge`, StringEx nameDic = `synonym.txt`, StringEx strID = `SYN`)
This function loads contents of the synonym dictionary file into a WK_DaTrie object.
Date: 2008-11-03
Author: YoungMin Ahn
Parameters:
pathDic a pointer of a constant charater - the path of the directory, which the synonym dictionary file is stored.
nameDic a pointer of a constant charater - the name of the synonym dictionary file.
strID the ID of the synonym dictionary.
Returns: an integer.
 0 - fail.
 1 - success.
Definition at line 132 of file Synonym.cpp.
References _synonymDelim, _synonymList, _ts, _tw, _wordDelim, StringEx::buffer(), createTrie(), StringEx::endWith(), kmaOrange::EntryNInfo::entry, StringEx::getIndex(), HEADWORD_FLAG, kmaOrange::EntryNInfo::info, insertSynonym(), StringEx::length(), StringEx::replaceString(), StringEx::startWith(), StringEx::toLowerCase(), and StringEx::trimRight().
int SynonymContainer::searchNgetInfoFromSynonymTrie (const char * str, WK_Synonym * pwks) [virtual]
This function searches a WK_DaTrie object for input string and gets contents of this WK_DaTrie object.
Date: 2008-11-03
Author: YoungMin Ahn
Parameters:
str a pointer of a constant charater - input string.
pwks a pointer of a WK_Synonym object - contents of this WK_DaTrie object are stored.
Returns: an integer.
 1 - success.
 0 - fail.
Implements WK_SynonymContainer.
Definition at line 306 of file Synonym.cpp.
References _infoList, _synonymList, _synonymTrie, kmaOrange::WK_DaTrie::findNode(), kmaOrange::WK_DaTrie_Node::getData(), kmaOrange::WK_DaTrie_Node::mpData, kmaOrange::WK_DaTrie_Node::mState, OVERLAP_FLAG, kmaOrange::Synonym::setContainer(), kmaOrange::Synonym::setEntryNInfo(), kmaOrange::Synonym::setMoreLong(), kmaOrange::Synonym::setOverlapCount(), and kmaOrange::Synonym::setPosSynonymList().
void SynonymContainer::setSynonymDelimiter (const char * delim) [virtual]
This function sets the delimiter between synonym entries in a synonym list.
Date: 2008-11-03
Author: YoungMin Ahn
Parameters:
delim a pointer of a constant charater - the delimiter between synonym entries in a synonym list.
Implements WK_SynonymContainer.
Definition at line 23 of file Synonym.cpp.
References _synonymDelim, and _ts.
void SynonymContainer::setWordDelimiter (const char * delim) [virtual]
This function sets the delimiter between words in a synonym entry.
Date: 2008-11-03
Author: YoungMin Ahn
Parameters:
delim a pointer of a constant charater - the delimiter between words in a synonym entry.
Implements WK_SynonymContainer.
Definition at line 29 of file Synonym.cpp.
References _tw, and _wordDelim.
Member Data Documentation
vector< vector<int> > kmaOrange::SynonymContainer::_infoList
the list of synonym information.
Definition at line 262 of file Synonym.h.
Referenced by kmaOrange::Synonym::getHeadWord(), kmaOrange::Synonym::getOverlapCount(), kmaOrange::Synonym::getSynonymCountByIndex(), kmaOrange::Synonym::getWord(), insertSynonym(), and searchNgetInfoFromSynonymTrie().
StringEx kmaOrange::SynonymContainer::_synonymDelim [private]
the first delimiter between synonym entries in a synonym list.
Definition at line 255 of file Synonym.h.
Referenced by loadSynonym(), setSynonymDelimiter(), and SynonymContainer().
vector<EntryNInfo> kmaOrange::SynonymContainer::_synonymList
the list of synonym lists.
Definition at line 261 of file Synonym.h.
Referenced by kmaOrange::Synonym::getHeadWord(), kmaOrange::Synonym::getSynonymCountByIndex(), kmaOrange::Synonym::getWord(), insertSynonym(), loadSynonym(), and searchNgetInfoFromSynonymTrie().
WK_DaTrie kmaOrange::SynonymContainer::_synonymTrie [private]
a WK_DaTrie object of the synonym dictionary.
Definition at line 253 of file Synonym.h.
Referenced by createTrie(), insertSynonym(), and searchNgetInfoFromSynonymTrie().
StringEx kmaOrange::SynonymContainer::_ts [private]
the delimiter between synonym entries in a synonym list.
Definition at line 257 of file Synonym.h.
Referenced by loadSynonym(), and setSynonymDelimiter().
StringEx kmaOrange::SynonymContainer::_tw [private]
the delimiter between words in a synonym entry.
Definition at line 258 of file Synonym.h.
Referenced by loadSynonym(), and setWordDelimiter().
StringEx kmaOrange::SynonymContainer::_wordDelim [private]
the first delimiter between words in a synonym entry.
Definition at line 256 of file Synonym.h.
Referenced by insertSynonym(), loadSynonym(), setWordDelimiter(), and SynonymContainer().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/kma/Synonym.h
/disk/workspace-cpp/la-manager/source/kma/Synonym.cpp