la_manager::Tokenizer Class Reference
interface of Tokenizer This class tokenize the input string according to defined char type table
#include <Tokenizer.h>
Public Member Functions
Tokenizer ()
~Tokenizer ()
void setConfig (const TokenizeConfig &conf)
set the user defined char types
bool tokenize (const UString &inputString, TermList &rawTerms, TermList &primTerms)
tokenize the input text, output two term lists: raw term list and primary term list
bool tokenize (const UString &inputString, TermList &primTerms)
tokenize the input text, output two term lists: raw term list and primary term list
Private Member Functions
void setTermType (Term &term)
Private Attributes
MLRUCacheTermList cache_
cache
CharTypeTable table_
char type table
Detailed Description
interface of Tokenizer This class tokenize the input string according to defined char type table
Definition at line 159 of file Tokenizer.h.
Constructor & Destructor Documentation
la_manager::Tokenizer::Tokenizer () [inline]
Definition at line 166 of file Tokenizer.h.
la_manager::Tokenizer::~Tokenizer () [inline]
Definition at line 169 of file Tokenizer.h.
Member Function Documentation
void la_manager::Tokenizer::setConfig (const TokenizeConfig & conf)
set the user defined char types
Parameters:
list char type option list
Definition at line 48 of file Tokenizer.cpp.
References la_manager::CharTypeTable::setConfig(), and table_.
Referenced by la_manager::LAManager::analyze(), and main().
void la_manager::Tokenizer::setTermType (Term & term) [private]
Definition at line 51 of file Tokenizer.cpp.
References la_manager::CharTypeTable::isDefinedAllow(), la_manager::Term::length(), table_, la_manager::Term::TERM_TYPE_ALLOW, la_manager::Term::TERM_TYPE_DELIMITER, la_manager::Term::text, and la_manager::Term::type.
Referenced by tokenize().
bool la_manager::Tokenizer::tokenize (const UString & inputString, TermList & primTerms)
tokenize the input text, output two term lists: raw term list and primary term list
Parameters:
inputString input text string
primTerms the output primary term list
Definition at line 141 of file Tokenizer.cpp.
References la_manager::Term::begin, cache_, la_manager::Term::clear(), la_manager::Term::end, la_manager::CharTypeTable::isDefaultDivide(), la_manager::CharTypeTable::isDefinedAllow(), la_manager::CharTypeTable::isDefinedDivide(), setTermType(), table_, la_manager::Term::text, and la_manager::Term::wordOffset.
bool la_manager::Tokenizer::tokenize (const UString & inputString, TermList & rawTerms, TermList & primTerms)
tokenize the input text, output two term lists: raw term list and primary term list
Parameters:
inputString input text string
rawTerms the output raw term list
primTerms the output primary term list
Definition at line 58 of file Tokenizer.cpp.
References la_manager::Term::begin, la_manager::Term::clear(), la_manager::Term::end, la_manager::CharTypeTable::isDefaultDivide(), la_manager::CharTypeTable::isDefinedAllow(), la_manager::CharTypeTable::isDefinedDivide(), setTermType(), table_, la_manager::Term::text, and la_manager::Term::wordOffset.
Referenced by la_manager::LAManager::analyze(), and main().
Member Data Documentation
MLRUCacheTermList la_manager::Tokenizer::cache_ [private]
cache
Definition at line 160 of file Tokenizer.h.
Referenced by tokenize().
CharTypeTable la_manager::Tokenizer::table_ [private]
char type table
Definition at line 161 of file Tokenizer.h.
Referenced by setConfig(), setTermType(), and tokenize().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/Tokenizer.h
/disk/workspace-cpp/la-manager/source/Tokenizer.cpp