kmaOrange::Eojul Class Reference
This class is stored the results of KMA.
#include <Eojul.h>
Public Member Functions
void initialize (bool willBeTheDefaultState=true)
This function initializes a Eojul object.
void setString (const char *pString)
This function sets a string in a Eojul object.
char * getString (void)
This function gets a string in a Eojul object.
int getListSize (void)
This function gets the number of the list of morphological analyzed results in a Eojul object.
int getCount (int nPos)
This function gets the number of morphemes in each list of morphological analyzed results.
char * getLexicon (int nPos, int nIdx)
This function gets the string of each morpheme in each list of morphological analyzed results.
int getPOS (int nPos, int nIdx)
This function gets the POS value of each morpheme in each list of morphological analyzed results.
char * getStrPOS (int nPos, int nIdx)
This function gets the POS string of each morpheme in each list of morphological analyzed results.
bool isIndexWord (int nPos, int nIdx)
This function gets whether each morpheme in each list of morphological analyzed results is an index word or not.
double getScore (int nPos)
This function gets the score of each list of morphological analyzed results.
int getOneBestIndex (void)
This function gets the index number of the list, which has the most high score in morphological analyzed results.
int getLinkedIndex (int nPos)
This function gets the index number of the list, which has the analysis result composed affix.
int makeNBest (unsigned char nBest)
This function makes the score order list for the N-Best option.
void setOffset (int offset)
int getOffset (void) const
Eojul (unsigned int sizeBuffer=DEFAULT_EOJUL_BUFFER_SIZE)
This function is a constructor of Eojul object.
Eojul (const Eojul &eojul)
This function is a constructor of Eojul object.
~Eojul (void)
This function is a destructor of Eojul object.
const Eojul & operator= (const Eojul &eojul)
This function assigns a right-hand-side to a left-hand-side.
void freeBuffer ()
This function empties assigned buffers of the Eojul object.
int isDigit (StringEx &strex)
This function checks whether an input string is a digit or not.
int isDigit (const char ch)
int doubleBuffer ()
This function doubles the size of buffers.
int setEojulAndInfo (const char *word, unsigned int info)
This function sets a string and the information of a word.
int setMorphAndTag (const char *word, unsigned int tag)
This function sets a string and the information of a morpheme.
int setMorphAndTag (const char *str, char *word, unsigned int tag)
int setMorphAndTag (unsigned int tag)
void increaseAnalysisResults ()
This function increases 1 in the number of total lists.
void showInfomation (std::ostream &outStream, bool isPreAnalysis=false)
This function shows the results of KMA through outStream(a screen or a file).
unsigned int getBufferSize () const
This function gets the size of a string in a Eojul object.
char * getBufferPtr () const
This function gets the starting pointer of the string in a Eojul object.
unsigned int * getTagsPtr () const
This function gets the starting pointer of the POS tags in a Eojul object.
unsigned int * getCountsPtr () const
This function gets the starting pointer of the count numbers in a Eojul object.
double * getScoresPtr () const
This function gets the starting pointer of the scores in a Eojul object.
unsigned int getBufferPos () const
This function gets the position of the string in a Eojul object.
unsigned int getTagsPos () const
This function gets the position of the POS tags in a Eojul object.
unsigned int getCountsPos () const
This function gets the position of the count numbers in a Eojul object.
unsigned int getScoresPos () const
This function gets the position of the scores in a Eojul object.
unsigned int getEojulInfo () const
This function gets the information of a word in a Eojul object.
void setEojulInfo (unsigned int info)
This function sets the information of a word.
void addEojulInfo (unsigned int info)
This function adds the information of a word.
void append (const Eojul &peojul)
This function appends a Eojul object to another Eojul object.
void merge (const Eojul &eojul1, const Eojul &eojul2)
This function merges two Eojul objects.
void backmerge (const Eojul &eojul1, const Eojul &eojul2)
This function merges two Eojul objects.
void setScore (double score)
This function sets a score of the list of KMA results in a Eojul objects.
void setScore (int nPos, double score)
void close ()
This function closes setting contents of a Eojul object.
char * getBufferByIndex (int index)
This function gets a string of a stored morpheme in input index.
bool getNBestState ()
This function gets the state of N-Best mode.
bool getOrdersState ()
This function gets the state of orders list.
Public Attributes
char innerBuffer [DEFAULT_EOJUL_BUFFER_SIZE]
the inner buffers of strings.
unsigned int innerTags [(int)(DEFAULT_EOJUL_BUFFER_SIZE/RATIO_BUFFER_AND_TAGS)]
the inner buffers of POS tags.
unsigned int innerCounts [(int)(DEFAULT_EOJUL_BUFFER_SIZE/RATIO_BUFFER_AND_COUNTS)]
the inner buffers of counts.
double innerScores [(int)(DEFAULT_EOJUL_BUFFER_SIZE/RATIO_BUFFER_AND_COUNTS)]
the inner buffers of scores.
unsigned int innerOrders [(int)(DEFAULT_EOJUL_BUFFER_SIZE/RATIO_BUFFER_AND_COUNTS)*2]
the inner buffers of orders.
unsigned int mIndexTagSet
the set of index POS tags.
unsigned int mIndexLength
the length of DIGIT or ALPHABET, which is a index word.
Private Attributes
char * _buffer
the buffers of strings.
unsigned int * _tags
the buffers of POS tags.
unsigned int * _counts
the buffers of counts.
double * _scores
the buffers of scores.
unsigned int * _orders
the buffers of scores.
unsigned int _sizeBuffer
the size of a set string.
unsigned int _posBuffer
the position of a string buffer.
unsigned int _posTags
the position of a POS tag.
unsigned int _posCounts
the position of a count.
unsigned int _posScores
the position of a score.
unsigned int _posOrders
the position of a score.
int _offset
bool _isNBestMode
the state of N-Best mode.
bool _isOrdersExpanded
the state of orders list.
Static Private Attributes
static StringEx _charDelimiter = `?!.-,\`'()[]<>~\\:;`_/|+=*&^%$#@{}`
the set of 1 byte special characters.
static StringEx _wcharDelimiter = `£¡:£§:£¬:£®:£¯:£º:£»:£¿:£Þ:£ß:£à:£ü:£þ:¡¢:¡£:¡¤:¡¥:¡¦:¡§:¡¨:¡©:¡ª:¡«:¡¬:¡­:¢¥:¢¦:¢§:¢¨:¢©:¢ª:¢«:¢¬:¢­:¢®:¢¯:¢°:£¢:£¨:£©:£Û:£Ý:£û:£ý:¡®:¡¯:¡°:¡±:¡²:¡³:¡´:¡µ:¡¶:¡·:¡¸:¡¹:¡º:¡»:¡¼:¡½:£«:£­:£¼:£½:£¾:¡¾:¡¿:¡À:¡Á:¡Â:¡Ã:¡Ä:¡Å:¡Î:¡Ï:¡Ð:¡Ñ:¡Ò:¡Ó:¡Ô:¡Õ:¡Ö:¡ì:¡í:¡î:¡ï:¡ð:¡ñ:¡ò:¡ó:¡ô:¡õ:¡ö:¡÷:¡ø:¡ù:¡ú:¡û:¡ü:¡ý:¡þ:¢¡:¢¢:¢£:¢¤:¢±:¢²:¢³:£¤:£¥:£Ü:£Æ:¡Ç:¡È:¡É:¡Ê:¡Ë:¡Ì:¡Í:¢´:¢µ:¢¶:?:§¡:§¢:§£:§¥:§¦:§§:§¨:§©:§ª:§«:§¬:§­:§®:§¯:§°:§±:§²:§³:§´:§µ:§¶:§·:§¸:§¹:§º:§»:§¼:§½:§¾:§¿:§À:§Á:§Â:§Ã:§Ä:§Å:§Æ:§Ç:§È:§É:§Ê:§Ë:§Ì:§Í:§Î:§Ï:§Ð:§Ñ:§Ò:§Ó:§Ô:§Õ:§Ö:§×:§Ø:§Ù:§Ú:§Û:§Ü:§Ý:§Þ:§ß:§à:§á:§â:§ã:§ä:§å:§æ:§ç:§è:§é:§ê:§ë:§ì:§í:§î:§ï:££:£¦:£ª:£À:¡×:¡Ø:¡Ù:¡Ú:¡Û:¡Ü:¡Ý:¡Þ:¡ß:¡à:¡á:¡â:¡ã:¡ä:¡å:¡æ:¡ç:¡è:¡é:¡ê:¡ë:¢¹:¢¸:¢¹:¢º:¢»:¢¼:¢½:¢¾:¢¿:¢Á:¢Â:¢Ã:¢Ä:¢Å:¢Æ:¢Ç:¢È:¢É:¢Ê:¢Ë:¢Ì:¢Í:¢Î:¢Ï:¢Ð:¢Ñ:¢Ò:¢Ó:¢Ô:¢Õ:¢Ö:¢×:¢Ø:¢Ù:¢Ú:¢Û:¢Ü:¢Ý:¢Þ:¢ß:¢à:¢á:¢â:¢ã:¢ä:¢å:?:¨£:¨¬:¦¡:¦¢:¦£:¦¤:¦¥:¦¦:¦§:¦¨:¦©:¦ª:¦«:¦¬:¦­:¦®:¦¯:¦°:¦±:¦²:¦³:¦´:¦µ:¦¶:¦·:¦¸:¦¹:¦º:¦»:¦¼:¦½:¦¾:¦¿:¦À:¦Á:¦Â:¦Ã:¦Ä:¦Å:¦Æ:¦Ç:¦È:¦É:¦Ê:¦Ë:¦Ì:¦Í:¦Î:¦Ï:¦Ð:¦Ñ:¦Ò:¦Ô:¦Õ:¦Ö:¦×:¦Ø:¦Ù:¦Ú:¦Û:¦Ü:¦Ý:¦Þ:¦ß:¦à:¦á:¦â:¦ã:¦ä:¨±:¨²:¨³:¨´:¨µ:¨¶:¨·:¨¸:¨¹:¨º:¨»:¨¼:¨½:¨¾:¨¿:¨À:¨Á:¨Â:¨Ã:¨Ä:¨Å:¨Æ:¨Ç:¨È:¨É:¨Ê:¨Ë:¨Ì:©±:©²:©³:©´:©µ:©¶:©·:©¸:©¹:©º:©»:©¼:©½:©¾:©¿:©À:©Á:©Â:©Ã:©Ä:©Å:©Æ:©Ç:©È:©É:©Ê:©Ë:©Ì:¨Í:¨Î:¨Ï:¨Ð:¨Ñ:¨Ò:¨Ó:¨Ô:¨Õ:¨Ö:¨×:¨Ø:¨Ù:¨Ú:¨Û:¨Ü:¨Ý:¨Þ:¨ß:¨à:¨á:¨â:¨ã:¨ä:¨å:¨æ:¨ç:¨è:¨é:¨ê:¨ë:¨ì:¨í:¨î:¨ï:¨ð:¨ñ:¨ò:¨ó:¨ô:¨õ:©Í:©Î:©Ï:©Ð:©Ñ:©Ò:©Ó:©Ô:©Õ:©Ö:©×:©Ø:©Ù:©Ú:©Û:©Ü:©Ý:©Þ:©ß:©à:©á:©â:©ã:©ä:©å:©æ:©ç:©è:©é:©ê:©ë:©ì:©í:©î:©ï:©ð:©ñ:©ò:©ó:©ô:©õ:£°:£±:£²:£³:£´:£µ:£¶:£·:£¸:£¹:¥¡:¥¢:¥£:¥¤:¥¥:¥¦:¥§:¥¨:¥©:¥ª:¥°:¥±:¥²:¥³:¥´:¥µ:¥¶:¥·:¥¸:¥¹:¨ö:¨÷:¨ø:¨ù:¨ú:¨û:¨ü:¨ý:¨þ:©ö:©÷:©ø:©ù:©ú:©û:©ü:©ý:©þ`
the set of 2 bytes special characters.
Detailed Description
This class is stored the results of KMA.
Date: 2008-11-10
Author: YoungMin Ahn & HeeGeun Park
See also: WK_Eojul
Definition at line 29 of file Eojul.h.
Constructor & Destructor Documentation
Eojul::Eojul (unsigned int sizeBuffer = DEFAULT_EOJUL_BUFFER_SIZE)
This function is a constructor of Eojul object.
Date: 2008-11-10
Author: YoungMin Ahn
Parameters:
sizeBuffer an unsigned integer - the size of a set string in a Eojul object.
Definition at line 24 of file Eojul.cpp.
References _buffer, _counts, _scores, _sizeBuffer, _tags, DEFAULT_EOJUL_BUFFER_SIZE, innerBuffer, innerCounts, innerScores, innerTags, RATIO_BUFFER_AND_COUNTS, RATIO_BUFFER_AND_TAGS, and kmaOrange::Logger::SetMessage().
Eojul::Eojul (const Eojul & eojul)
This function is a constructor of Eojul object.
Date: 2008-11-10
Author: YoungMin Ahn
Parameters:
eojul an indirect referncing pointer of a constant Eojul object.
Definition at line 58 of file Eojul.cpp.
References _buffer, _counts, _offset, _posBuffer, _posCounts, _posScores, _posTags, _scores, _sizeBuffer, _tags, DEFAULT_EOJUL_BUFFER_SIZE, getBufferPos(), getBufferPtr(), getBufferSize(), getCountsPos(), getCountsPtr(), getOffset(), getScoresPos(), getScoresPtr(), getTagsPos(), getTagsPtr(), innerBuffer, innerCounts, innerScores, innerTags, RATIO_BUFFER_AND_COUNTS, and RATIO_BUFFER_AND_TAGS.
Eojul::~Eojul (void)
This function is a destructor of Eojul object.
Date: 2008-11-10
Author: YoungMin Ahn
Definition at line 98 of file Eojul.cpp.
References _sizeBuffer, DEFAULT_EOJUL_BUFFER_SIZE, and freeBuffer().
Member Function Documentation
void kmaOrange::Eojul::addEojulInfo (unsigned int info) [inline]
This function adds the information of a word.
Date: 2008-11-11
Author: YoungMin Ahn
Parameters:
info an unsigned integer - the information of a word.
Definition at line 382 of file Eojul.h.
References _tags.
void Eojul::append (const Eojul & peojul)
This function appends a Eojul object to another Eojul object.
Date: 2008-11-11
Author: HeeGeun Park
Parameters:
peojul an indirect referncing pointer of a constant Eojul object.
Definition at line 701 of file Eojul.cpp.
References _buffer, _counts, _posScores, _scores, _tags, setMorphAndTag(), and setScore().
Referenced by GuessCandidate::addNVC(), GuessCandidate::addNXSD(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NVC(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NXSD(), kmaOrange::MAnalyzer::analyzeEojul_NNR(), kmaOrange::MAnalyzer::analyzeSubHangulWordforFL(), kmaOrange::MAnalyzer::analyzeSubHangulWordforSN(), and kmaOrange::MAnalyzer::composeAffixes().
void Eojul::backmerge (const Eojul & eojul1, const Eojul & eojul2)
This function merges two Eojul objects.
Date: 2008-11-12
Author: HeeGeun Park
Parameters:
eojul1 an indirect referncing pointer of a constant Eojul object - it has only one list of KMA results.
eojul2 an indirect referncing pointer of a constant Eojul object - it has various lists of KMA results.
Definition at line 779 of file Eojul.cpp.
References _buffer, _counts, _scores, _tags, close(), getBufferPtr(), increaseAnalysisResults(), NNR, setMorphAndTag(), and setScore().
Referenced by kmaOrange::MAnalyzer::analyzeSubHangulWordforFL(), and kmaOrange::MAnalyzer::analyzeSubHangulWordforSN().
void Eojul::close ()
This function closes setting contents of a Eojul object.
Date: 2008-11-12
Author: YoungMin Ahn
Definition at line 554 of file Eojul.cpp.
References _counts, _posCounts, _posScores, and _scores.
Referenced by GuessCandidate::addAuxVerb(), kmaOrange::Tagger::addEojul(), GuessCandidate::addNVC(), GuessCandidate::addNXSD(), kmaOrange::MAnalyzer::analyzeDigitAlphabetWord(), kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NJ(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NVC(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NXSD(), kmaOrange::MAnalyzer::analyzeEojul_NNR(), kmaOrange::MAnalyzer::analyzeSimpleWord(), kmaOrange::MAnalyzer::analyzeSubHangulWordforFL(), kmaOrange::MAnalyzer::analyzeSubHangulWordforSN(), backmerge(), kmaOrange::MAnalyzer::checkNanalyzeContraction_CHEE(), kmaOrange::MAnalyzer::checkNanalyzeContraction_KEE(), kmaOrange::MAnalyzer::checkNanalyzeContraction_KEH(), kmaOrange::MAnalyzer::checkNanalyzeContraction_WAE(), kmaOrange::MAnalyzer::checkNanalyzeContraction_WAHWOH(), kmaOrange::MAnalyzer::checkNanalyzeContraction_YUR(), kmaOrange::MAnalyzer::checkNanalyzeElision_hlL(), kmaOrange::MAnalyzer::checkNanalyzeElision_HOMOPHONE(), kmaOrange::MAnalyzer::checkNanalyzeElision_OO(), kmaOrange::MAnalyzer::checkNanalyzeElision_UH(), kmaOrange::MAnalyzer::checkNanalyzeElision_UR(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_BIUP(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_DIGT(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_HIUNG(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_RUH(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_RUR(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_SIOT(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_UR(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_YUR(), kmaOrange::MAnalyzer::checkNanalyzeN_(), kmaOrange::MAnalyzer::checkNanalyzePreEomi(), kmaOrange::MAnalyzer::checkNanalyzeV_(), kmaOrange::MAnalyzer::checkNanalyzeXSDecliable(), kmaOrange::MAnalyzer::composeAffixes(), and merge().
int Eojul::doubleBuffer ()
This function doubles the size of buffers.
Date: 2008-11-11
Author: YoungMin Ahn
Returns: an integer.
Definition at line 565 of file Eojul.cpp.
References _buffer, _counts, _scores, _sizeBuffer, _tags, DEFAULT_EOJUL_BUFFER_SIZE, freeBuffer(), RATIO_BUFFER_AND_COUNTS, RATIO_BUFFER_AND_TAGS, and TWICE.
Referenced by setEojulAndInfo(), and setMorphAndTag().
void Eojul::freeBuffer ()
This function empties assigned buffers of the Eojul object.
Date: 2008-11-11
Author: YoungMin Ahn
Definition at line 425 of file Eojul.cpp.
References _buffer, _counts, _isOrdersExpanded, _orders, _scores, _tags, and innerOrders.
Referenced by doubleBuffer(), initialize(), operator=(), and ~Eojul().
char * Eojul::getBufferByIndex (int index)
This function gets a string of a stored morpheme in input index.
Date: 2008-11-12
Author: HeeGeun Park
Parameters:
index an integer.
Definition at line 826 of file Eojul.cpp.
References _buffer, _posTags, and _tags.
Referenced by kmaOrange::MAnalyzer::analyzeEojul_AuxVerb().
unsigned int kmaOrange::Eojul::getBufferPos () const [inline]
This function gets the position of the string in a Eojul object.
Date: 2008-11-11
Author: YoungMin Ahn
Returns: an unsigned integer.
Definition at line 334 of file Eojul.h.
References _posBuffer.
Referenced by Eojul(), and operator=().
char* kmaOrange::Eojul::getBufferPtr () const [inline]
This function gets the starting pointer of the string in a Eojul object.
Date: 2008-11-11
Author: YoungMin Ahn
Returns: a pointer of a character.
Definition at line 302 of file Eojul.h.
References _buffer.
Referenced by kmaOrange::MAnalyzer::analyzeDeclinableWord(), kmaOrange::MAnalyzer::analyzeDigitAlphabetWord(), kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::analyzeEojul_AuxVerb(), kmaOrange::MAnalyzer::analyzeEojul_Guess(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NJ(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NVC(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NXSD(), kmaOrange::MAnalyzer::analyzeEojul_NNR(), kmaOrange::MAnalyzer::analyzeHeadTail(), kmaOrange::MAnalyzer::analyzeSubHangulWordforFL(), kmaOrange::MAnalyzer::analyzeSubHangulWordforSN(), backmerge(), kmaOrange::MAnalyzer::checkNanalyzeCopular(), kmaOrange::MAnalyzer::checkNanalyzeElision_hlL(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_BIUP(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_HIUNG(), kmaOrange::MAnalyzer::checkNanalyzeN_(), kmaOrange::MAnalyzer::checkNanalyzePreEomi(), kmaOrange::MAnalyzer::checkNanalyzeV_(), kmaOrange::MAnalyzer::checkNanalyzeXSDecliable(), Eojul(), kmaOrange::MAnalyzer::makeSubRanking(), merge(), operator=(), and kmaOrange::MAnalyzer::warmUpAnalysis().
unsigned int kmaOrange::Eojul::getBufferSize () const [inline]
This function gets the size of a string in a Eojul object.
Date: 2008-11-11
Author: YoungMin Ahn
Returns: an unsigned integer.
Definition at line 294 of file Eojul.h.
References _sizeBuffer.
Referenced by Eojul(), and operator=().
int kmaOrange::Eojul::getCount (int nPos) [inline, virtual]
This function gets the number of morphemes in each list of morphological analyzed results.
Date: 2008-11-10
Author: HeeGeun Park
Parameters:
nPos an integer - the index number of the list of morphological analyzed results.
Returns: an integer - the number of morphemes in each list of morphological analyzed results.
Implements WK_Eojul.
Definition at line 84 of file Eojul.h.
References _counts, _isNBestMode, and _orders.
Referenced by kmaOrange::Tagger::addEojul(), kmaOrange::MAnalyzer::analyzeEojul_AuxVerb(), kmaOrange::MAnalyzer::analyzeSubHangulWordforSN(), kmaOrange::MAnalyzer::composeAffixes(), kmaOrange::MAnalyzer::makeSubRanking(), and kmaOrange::Tagger::runTagging().
unsigned int kmaOrange::Eojul::getCountsPos () const [inline]
This function gets the position of the count numbers in a Eojul object.
Date: 2008-11-11
Author: YoungMin Ahn
Returns: an unsigned integer.
Definition at line 350 of file Eojul.h.
References _posCounts.
Referenced by Eojul(), and operator=().
unsigned int* kmaOrange::Eojul::getCountsPtr () const [inline]
This function gets the starting pointer of the count numbers in a Eojul object.
Date: 2008-11-11
Author: YoungMin Ahn
Returns: a pointer of an unsigned character.
Definition at line 318 of file Eojul.h.
References _counts.
Referenced by kmaOrange::MAnalyzer::analyzeDigitAlphabetWord(), kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::analyzeEojul_AuxVerb(), kmaOrange::MAnalyzer::analyzeEojul_Guess(), kmaOrange::MAnalyzer::analyzeEojul_NNR(), kmaOrange::MAnalyzer::analyzeSubHangulWordforFL(), kmaOrange::MAnalyzer::analyzeSubHangulWordforSN(), Eojul(), and operator=().
unsigned int kmaOrange::Eojul::getEojulInfo () const [inline]
This function gets the information of a word in a Eojul object.
Date: 2008-11-11
Author: YoungMin Ahn
Returns: an unsigned integer.
Definition at line 366 of file Eojul.h.
References _tags.
Referenced by kmaOrange::MAnalyzer::analyzeDigitAlphabetWord(), kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::analyzeEojul_AuxVerb(), kmaOrange::MAnalyzer::analyzeHeadTail(), kmaOrange::MAnalyzer::analyzeSimpleWord(), kmaOrange::MAnalyzer::analyzeSubHangulWordforFL(), kmaOrange::MAnalyzer::analyzeSubHangulWordforSN(), kmaOrange::MAnalyzer::checkNanalyzeContraction_YUR(), kmaOrange::MAnalyzer::checkNanalyzeCopular(), kmaOrange::MAnalyzer::checkNanalyzeElision_hlL(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_HIUNG(), kmaOrange::MAnalyzer::checkNanalyzePreEomi(), kmaOrange::MAnalyzer::checkNanalyzeV_(), kmaOrange::MAnalyzer::checkNanalyzeXSDecliable(), kmaOrange::MAnalyzer::composeAffixes(), and kmaOrange::Tagger::runTagging().
char * Eojul::getLexicon (int nPos, int nIdx) [virtual]
This function gets the string of each morpheme in each list of morphological analyzed results.
Date: 2008-11-10
Author: HeeGeun Park
Parameters:
nPos an integer - the index number of the list of morphological analyzed results.
nIdx an integer - the index number of the morpheme in the list of morphological analyzed results.
Returns: a pointer of a character - the string of the nIdx-th morpheme in the nPos-th list of morphological analyzed results.
Implements WK_Eojul.
Definition at line 274 of file Eojul.cpp.
References _buffer, _counts, _isNBestMode, _orders, and _tags.
Referenced by kmaOrange::Tagger::addEojul(), kmaOrange::MAnalyzer::composeAffixes(), isIndexWord(), kmaOrange::MAnalyzer::makeSubRanking(), and kmaOrange::Tagger::runTagging().
int Eojul::getLinkedIndex (int nPos) [virtual]
This function gets the index number of the list, which has the analysis result composed affix.
Date: 2009-01-05
Author: HeeGeun Park
Parameters:
nPos an integer - the index number of the list of morphological analyzed results.
Returns: an integer - the index number of the list, which has the analysis result composed affix.
Implements WK_Eojul.
Definition at line 377 of file Eojul.cpp.
References _scores.
Referenced by kmaOrange::MAnalyzer::composeAffixes().
int kmaOrange::Eojul::getListSize (void) [inline, virtual]
This function gets the number of the list of morphological analyzed results in a Eojul object.
Date: 2008-11-10
Author: HeeGeun Park
Returns: an integer - the number of the list of morphological analyzed results.
Implements WK_Eojul.
Definition at line 71 of file Eojul.h.
References _counts, _isNBestMode, and _orders.
Referenced by kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::analyzeEojul_AuxVerb(), kmaOrange::MAnalyzer::analyzeEojul_NNR(), kmaOrange::MAnalyzer::analyzeSubHangulWordforSN(), kmaOrange::MAnalyzer::composeAffixes(), kmaOrange::MAnalyzer::makeRanking(), and kmaOrange::Tagger::runTagging().
bool kmaOrange::Eojul::getNBestState () [inline]
This function gets the state of N-Best mode.
Date: 2009-01-12
Author: HeeGeun Park
Returns: a boolean.
Definition at line 444 of file Eojul.h.
References _isNBestMode.
Referenced by operator=().
int kmaOrange::Eojul::getOffset (void) const [inline]
Definition at line 172 of file Eojul.h.
References _offset.
Referenced by Eojul(), operator=(), and kmaOrange::Tagger::runTagging().
int Eojul::getOneBestIndex (void) [virtual]
This function gets the index number of the list, which has the most high score in morphological analyzed results.
Date: 2008-11-10
Author: HeeGeun Park
Returns: an integer - the index number of the list, which has the most high score in morphological analyzed results.
Implements WK_Eojul.
Definition at line 345 of file Eojul.cpp.
References _counts, _isNBestMode, and _scores.
Referenced by makeNBest(), and kmaOrange::Tagger::runTagging().
bool kmaOrange::Eojul::getOrdersState () [inline]
This function gets the state of orders list.
Date: 2009-01-12
Author: HeeGeun Park
Returns: a boolean.
Definition at line 452 of file Eojul.h.
References _isOrdersExpanded.
Referenced by operator=().
int Eojul::getPOS (int nPos, int nIdx) [virtual]
This function gets the POS value of each morpheme in each list of morphological analyzed results.
Date: 2008-11-10
Author: HeeGeun Park
Parameters:
nPos an integer - the index number of the list of morphological analyzed results.
nIdx an integer - the index number of the morpheme in the list of morphological analyzed results.
Returns: an integer - the POS value of the nIdx-th morpheme in the nPos-th list of morphological analyzed results.
Implements WK_Eojul.
Definition at line 287 of file Eojul.cpp.
References _counts, _isNBestMode, _orders, and _tags.
Referenced by kmaOrange::Tagger::addEojul(), kmaOrange::MAnalyzer::analyzeEojul_AuxVerb(), kmaOrange::MAnalyzer::composeAffixes(), getStrPOS(), isIndexWord(), kmaOrange::MAnalyzer::makeSubRanking(), and kmaOrange::Tagger::runTagging().
double Eojul::getScore (int nPos) [virtual]
This function gets the score of each list of morphological analyzed results.
Date: 2008-11-10
Author: HeeGeun Park
Parameters:
nPos an integer - the index number of the list of morphological analyzed results.
Returns: a double - the score of the nPos-th list of morphological analyzed results.
Implements WK_Eojul.
Definition at line 331 of file Eojul.cpp.
References _isNBestMode, _orders, and _scores.
Referenced by kmaOrange::Tagger::addEojul(), and kmaOrange::MAnalyzer::composeAffixes().
unsigned int kmaOrange::Eojul::getScoresPos () const [inline]
This function gets the position of the scores in a Eojul object.
Date: 2008-11-11
Author: YoungMin Ahn
Returns: an unsigned integer.
Definition at line 358 of file Eojul.h.
References _posScores.
Referenced by Eojul(), and operator=().
double* kmaOrange::Eojul::getScoresPtr () const [inline]
This function gets the starting pointer of the scores in a Eojul object.
Date: 2008-11-11
Author: YoungMin Ahn
Returns: a pointer of a double.
Definition at line 326 of file Eojul.h.
References _scores.
Referenced by kmaOrange::MAnalyzer::composeAffixes(), Eojul(), kmaOrange::MAnalyzer::makeRanking(), and operator=().
char* kmaOrange::Eojul::getString (void) [inline, virtual]
This function gets a string in a Eojul object.
Date: 2008-11-10
Author: HeeGeun Park
Returns: a pointer of a character - a set string in a Eojul object.
Implements WK_Eojul.
Definition at line 63 of file Eojul.h.
References _buffer.
Referenced by kmaOrange::MAnalyzer::composeAffixes(), and kmaOrange::Tagger::runTagging().
char * Eojul::getStrPOS (int nPos, int nIdx) [virtual]
This function gets the POS string of each morpheme in each list of morphological analyzed results.
Date: 2008-11-10
Author: HeeGeun Park
Parameters:
nPos an integer - the index number of the list of morphological analyzed results.
nIdx an integer - the index number of the morpheme in the list of morphological analyzed results.
Returns: a pointer of a character - the POS string of the nIdx-th morpheme in the nPos-th list of morphological analyzed results.
Implements WK_Eojul.
Definition at line 300 of file Eojul.cpp.
References kmaOrange::TagSet::convertCodeToTagString(), and getPOS().
unsigned int kmaOrange::Eojul::getTagsPos () const [inline]
This function gets the position of the POS tags in a Eojul object.
Date: 2008-11-11
Author: YoungMin Ahn
Returns: an unsigned integer.
Definition at line 342 of file Eojul.h.
References _posTags.
Referenced by Eojul(), and operator=().
unsigned int* kmaOrange::Eojul::getTagsPtr () const [inline]
This function gets the starting pointer of the POS tags in a Eojul object.
Date: 2008-11-11
Author: YoungMin Ahn
Returns: a pointer of an unsigned integer.
Definition at line 310 of file Eojul.h.
References _tags.
Referenced by kmaOrange::MAnalyzer::analyzeEojul_AuxVerb(), Eojul(), and operator=().
void Eojul::increaseAnalysisResults ()
This function increases 1 in the number of total lists.
Date: 2008-11-11
Author: YoungMin Ahn
Definition at line 527 of file Eojul.cpp.
References _counts, _posCounts, _posScores, and _scores.
Referenced by GuessCandidate::addAuxVerb(), kmaOrange::Tagger::addEojul(), GuessCandidate::addNVC(), GuessCandidate::addNXSD(), kmaOrange::MAnalyzer::analyzeDigitAlphabetWord(), kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NJ(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NVC(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NXSD(), kmaOrange::MAnalyzer::analyzeEojul_NNR(), kmaOrange::MAnalyzer::analyzeSimpleWord(), kmaOrange::MAnalyzer::analyzeSubHangulWordforFL(), kmaOrange::MAnalyzer::analyzeSubHangulWordforSN(), backmerge(), kmaOrange::MAnalyzer::checkNanalyzeContraction_CHEE(), kmaOrange::MAnalyzer::checkNanalyzeContraction_KEE(), kmaOrange::MAnalyzer::checkNanalyzeContraction_KEH(), kmaOrange::MAnalyzer::checkNanalyzeContraction_WAE(), kmaOrange::MAnalyzer::checkNanalyzeContraction_WAHWOH(), kmaOrange::MAnalyzer::checkNanalyzeContraction_YUR(), kmaOrange::MAnalyzer::checkNanalyzeElision_hlL(), kmaOrange::MAnalyzer::checkNanalyzeElision_HOMOPHONE(), kmaOrange::MAnalyzer::checkNanalyzeElision_OO(), kmaOrange::MAnalyzer::checkNanalyzeElision_UH(), kmaOrange::MAnalyzer::checkNanalyzeElision_UR(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_BIUP(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_DIGT(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_HIUNG(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_RUH(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_RUR(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_SIOT(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_UR(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_YUR(), kmaOrange::MAnalyzer::checkNanalyzeN_(), kmaOrange::MAnalyzer::checkNanalyzePreEomi(), kmaOrange::MAnalyzer::checkNanalyzeV_(), kmaOrange::MAnalyzer::checkNanalyzeXSDecliable(), kmaOrange::MAnalyzer::composeAffixes(), and merge().
void Eojul::initialize (bool willBeTheDefaultState = true) [virtual]
This function initializes a Eojul object.
Date: 2008-11-10
Author: HeeGeun Park
Parameters:
willBeTheDefaultState a boolean.
 true - it entirely sets a Eojul object to initial statement.
 false - it only sets values in a Eojul object.
Implements WK_Eojul.
Definition at line 390 of file Eojul.cpp.
References _buffer, _counts, _isNBestMode, _isOrdersExpanded, _offset, _posBuffer, _posCounts, _posScores, _posTags, _scores, _sizeBuffer, _tags, DEFAULT_EOJUL_BUFFER_SIZE, freeBuffer(), innerBuffer, innerCounts, innerScores, and innerTags.
Referenced by kmaOrange::MAnalyzer::analyzeDigitAlphabetWord(), kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::analyzeEojul_AuxVerb(), kmaOrange::MAnalyzer::analyzeSubHangulWordforFL(), kmaOrange::MAnalyzer::analyzeSubHangulWordforSN(), kmaOrange::MAnalyzer::composeAffixes(), kmaOrange::Tagger::runTagging(), setEojulAndInfo(), and kmaOrange::MAnalyzer::tokenizeSentence().
int Eojul::isDigit (const char ch)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 113 of file Eojul.cpp.
int Eojul::isDigit (StringEx & strex)
This function checks whether an input string is a digit or not.
Date: 2008-11-11
Author: YoungMin Ahn
Parameters:
strex an indirect referncing pointer of StringEx object - an input string.
Returns: an integer.
 0 - not digit.
 1 - digit.
Definition at line 103 of file Eojul.cpp.
References StringEx::length().
bool Eojul::isIndexWord (int nPos, int nIdx) [virtual]
This function gets whether each morpheme in each list of morphological analyzed results is an index word or not.
Date: 2008-11-10
Author: HeeGeun Park
Parameters:
nPos an integer - the index number of the list of morphological analyzed results.
nIdx an integer - the index number of the morpheme in the list of morphological analyzed results.
Returns: a boolean.
 true - index word.
 false - no index word.
Implements WK_Eojul.
Definition at line 307 of file Eojul.cpp.
References FL, getLexicon(), getPOS(), mIndexLength, mIndexTagSet, and SN.
int Eojul::makeNBest (unsigned char nBest)
This function makes the score order list for the N-Best option.
Date: 2009-01-05
Author: HeeGeun Park
Parameters:
nBest an unsigned character - the number of the score order list.
Returns: an integer.
Definition at line 204 of file Eojul.cpp.
References _counts, _isNBestMode, _isOrdersExpanded, _orders, _scores, DEFAULT_EOJUL_BUFFER_SIZE, getOneBestIndex(), innerOrders, and RATIO_BUFFER_AND_COUNTS.
Referenced by kmaOrange::MAnalyzer::runWithEojul().
void Eojul::merge (const Eojul & eojul1, const Eojul & eojul2)
This function merges two Eojul objects.
Date: 2008-11-12
Author: HeeGeun Park
Parameters:
eojul1 an indirect referncing pointer of a constant Eojul object - it has various lists of KMA results.
eojul2 an indirect referncing pointer of a constant Eojul object - it has only one list of KMA results.
Definition at line 730 of file Eojul.cpp.
References _buffer, _counts, _scores, _tags, close(), getBufferPtr(), increaseAnalysisResults(), NNR, setMorphAndTag(), and setScore().
Referenced by kmaOrange::MAnalyzer::analyzeDigitAlphabetWord(), kmaOrange::MAnalyzer::analyzeEojul_AuxVerb(), kmaOrange::MAnalyzer::analyzeSubHangulWordforFL(), and kmaOrange::MAnalyzer::analyzeSubHangulWordforSN().
const Eojul & Eojul::operator= (const Eojul & eojul)
This function assigns a right-hand-side to a left-hand-side.
Date: 2008-11-11
Author: YoungMin Ahn
Definition at line 662 of file Eojul.cpp.
References _buffer, _counts, _isNBestMode, _isOrdersExpanded, _offset, _posBuffer, _posCounts, _posScores, _posTags, _scores, _sizeBuffer, _tags, DEFAULT_EOJUL_BUFFER_SIZE, freeBuffer(), getBufferPos(), getBufferPtr(), getBufferSize(), getCountsPos(), getCountsPtr(), getNBestState(), getOffset(), getOrdersState(), getScoresPos(), getScoresPtr(), getTagsPos(), getTagsPtr(), RATIO_BUFFER_AND_COUNTS, and RATIO_BUFFER_AND_TAGS.
int Eojul::setEojulAndInfo (const char * word, unsigned int info)
This function sets a string and the information of a word.
Date: 2008-11-11
Author: YoungMin Ahn
Parameters:
word a pointer of a character - an input string.
info an unsigned integer - the information of a word.
Returns: an integer.
Definition at line 438 of file Eojul.cpp.
References _buffer, _posBuffer, _posTags, _sizeBuffer, _tags, doubleBuffer(), initialize(), and RATIO_BUFFER_AND_TAGS.
Referenced by GuessCandidate::addAuxVerb(), GuessCandidate::addNVC(), GuessCandidate::addNXSD(), kmaOrange::MAnalyzer::analyzeDigitAlphabetWord(), kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::analyzeEojul_AuxVerb(), kmaOrange::MAnalyzer::analyzeSubHangulWordforFL(), kmaOrange::MAnalyzer::analyzeSubHangulWordforSN(), kmaOrange::MAnalyzer::checkNanalyzeContraction_KEE(), kmaOrange::MAnalyzer::checkNanalyzeContraction_KEH(), kmaOrange::MAnalyzer::checkNanalyzeContraction_YUR(), kmaOrange::MAnalyzer::checkNanalyzeElision_hlL(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_HIUNG(), kmaOrange::MAnalyzer::checkNanalyzePreEomi(), kmaOrange::MAnalyzer::checkNanalyzeV_(), kmaOrange::MAnalyzer::checkNanalyzeXSDecliable(), kmaOrange::MAnalyzer::composeAffixes(), kmaOrange::Tagger::runTagging(), setString(), and kmaOrange::MAnalyzer::tokenizeSentence().
void kmaOrange::Eojul::setEojulInfo (unsigned int info) [inline]
This function sets the information of a word.
Date: 2008-11-11
Author: YoungMin Ahn
Parameters:
info an unsigned integer - the information of a word.
Definition at line 374 of file Eojul.h.
References _tags.
int Eojul::setMorphAndTag (unsigned int tag)
overload int setMorphAndTag(unsigned int tag)
Definition at line 462 of file Eojul.cpp.
References _counts, _posCounts, _posTags, _sizeBuffer, _tags, doubleBuffer(), and RATIO_BUFFER_AND_TAGS.
int Eojul::setMorphAndTag (const char * str, char * word, unsigned int tag)
Definition at line 501 of file Eojul.cpp.
References _buffer, _counts, _posBuffer, _posCounts, _posTags, _sizeBuffer, _tags, doubleBuffer(), and RATIO_BUFFER_AND_TAGS.
int Eojul::setMorphAndTag (const char * word, unsigned int tag)
This function sets a string and the information of a morpheme.
Date: 2008-11-11
Author: YoungMin Ahn
Parameters:
word a pointer of a character - an input string.
tag an unsigned integer - the information of a morpheme.
Returns: an integer.
Definition at line 477 of file Eojul.cpp.
References _buffer, _counts, _posBuffer, _posCounts, _posTags, _sizeBuffer, _tags, doubleBuffer(), and RATIO_BUFFER_AND_TAGS.
Referenced by kmaOrange::Tagger::addEojul(), kmaOrange::MAnalyzer::analyzeDigitAlphabetWord(), kmaOrange::MAnalyzer::analyzeEojul(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NJ(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NVC(), kmaOrange::MAnalyzer::analyzeEojul_Guess_NXSD(), kmaOrange::MAnalyzer::analyzeEojul_NNR(), kmaOrange::MAnalyzer::analyzeSimpleWord(), kmaOrange::MAnalyzer::analyzeSubHangulWordforFL(), kmaOrange::MAnalyzer::analyzeSubHangulWordforSN(), append(), backmerge(), kmaOrange::MAnalyzer::checkNanalyzeContraction_CHEE(), kmaOrange::MAnalyzer::checkNanalyzeContraction_KEE(), kmaOrange::MAnalyzer::checkNanalyzeContraction_KEH(), kmaOrange::MAnalyzer::checkNanalyzeContraction_WAE(), kmaOrange::MAnalyzer::checkNanalyzeContraction_WAHWOH(), kmaOrange::MAnalyzer::checkNanalyzeContraction_YUR(), kmaOrange::MAnalyzer::checkNanalyzeElision_hlL(), kmaOrange::MAnalyzer::checkNanalyzeElision_HOMOPHONE(), kmaOrange::MAnalyzer::checkNanalyzeElision_OO(), kmaOrange::MAnalyzer::checkNanalyzeElision_UH(), kmaOrange::MAnalyzer::checkNanalyzeElision_UR(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_BIUP(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_DIGT(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_HIUNG(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_RUH(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_RUR(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_SIOT(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_UR(), kmaOrange::MAnalyzer::checkNanalyzeIrregularConjugation_YUR(), kmaOrange::MAnalyzer::checkNanalyzeN_(), kmaOrange::MAnalyzer::checkNanalyzePreEomi(), kmaOrange::MAnalyzer::checkNanalyzeV_(), kmaOrange::MAnalyzer::checkNanalyzeXSDecliable(), kmaOrange::MAnalyzer::composeAffixes(), and merge().
void kmaOrange::Eojul::setOffset (int offset) [inline]
Definition at line 171 of file Eojul.h.
References _offset.
Referenced by kmaOrange::Tagger::runTagging().
void Eojul::setScore (int nPos, double score)
overload void setScore(int nPos, double score)
Definition at line 549 of file Eojul.cpp.
References _scores.
void Eojul::setScore (double score)
This function sets a score of the list of KMA results in a Eojul objects.
Date: 2008-11-12
Author: YoungMin Ahn
Parameters:
score a double.
Definition at line 544 of file Eojul.cpp.
References _posScores, and _scores.
Referenced by kmaOrange::Tagger::addEojul(), kmaOrange::MAnalyzer::analyzeEojul_NNR(), append(), backmerge(), kmaOrange::MAnalyzer::checkNanalyzeN_(), kmaOrange::MAnalyzer::composeAffixes(), and merge().
void Eojul::setString (const char * pString) [virtual]
This function sets a string in a Eojul object.
Date: 2008-11-10
Author: HeeGeun Park
Parameters:
pString a pointer of a character - a setting string based on a word.
Implements WK_Eojul.
Definition at line 120 of file Eojul.cpp.
References _charDelimiter, _wcharDelimiter, kmaOrange::WK_Hanja::convertToHangul(), DEFAULT_LINE_BUFF_SIZE, DEFAULT_WORD_SIZE, EI_ALPHABET, EI_DIGIT, EI_HANGUL, EI_ILLEGAL, EI_TOOLONG, StringEx::getIndex(), setEojulAndInfo(), kmaOrange::Logger::SetMessage(), and TEI_INCLUDESC.
void kmaOrange::Eojul::showInfomation (std::ostream & outStream, bool isPreAnalysis = false)
This function shows the results of KMA through outStream(a screen or a file).
Date: 2008-11-11
Author: YoungMin Ahn
Parameters:
outStream an indirect referncing pointer of std::ostream object.
isPreAnalysis a boolean
 true - system pre-analysis dictionary making mode. flase - common mode.
Referenced by kmaOrange::MAnalyzer::preprocessBeforeAnalysis(), and kmaOrange::MAnalyzer::tokenizeSentence().
Member Data Documentation
char* kmaOrange::Eojul::_buffer [private]
the buffers of strings.
Definition at line 452 of file Eojul.h.
Referenced by append(), backmerge(), doubleBuffer(), Eojul(), freeBuffer(), getBufferByIndex(), getBufferPtr(), getLexicon(), getString(), initialize(), merge(), operator=(), setEojulAndInfo(), and setMorphAndTag().
StringEx Eojul::_charDelimiter = `?!.-,\`'()[]<>~\\:;`_/|+=*&^%$#@{}` [static, private]
the set of 1 byte special characters.
Definition at line 468 of file Eojul.h.
Referenced by setString().
unsigned int* kmaOrange::Eojul::_counts [private]
the buffers of counts.
Definition at line 457 of file Eojul.h.
Referenced by append(), backmerge(), close(), doubleBuffer(), Eojul(), freeBuffer(), getCount(), getCountsPtr(), getLexicon(), getListSize(), getOneBestIndex(), getPOS(), increaseAnalysisResults(), initialize(), makeNBest(), merge(), operator=(), and setMorphAndTag().
bool kmaOrange::Eojul::_isNBestMode [private]
the state of N-Best mode.
Definition at line 473 of file Eojul.h.
Referenced by getCount(), getLexicon(), getListSize(), getNBestState(), getOneBestIndex(), getPOS(), getScore(), initialize(), makeNBest(), and operator=().
bool kmaOrange::Eojul::_isOrdersExpanded [private]
the state of orders list.
Definition at line 474 of file Eojul.h.
Referenced by freeBuffer(), getOrdersState(), initialize(), makeNBest(), and operator=().
int kmaOrange::Eojul::_offset [private]
Definition at line 471 of file Eojul.h.
Referenced by Eojul(), getOffset(), initialize(), operator=(), and setOffset().
unsigned int* kmaOrange::Eojul::_orders [private]
the buffers of scores.
Definition at line 459 of file Eojul.h.
Referenced by freeBuffer(), getCount(), getLexicon(), getListSize(), getPOS(), getScore(), and makeNBest().
unsigned int kmaOrange::Eojul::_posBuffer [private]
the position of a string buffer.
Definition at line 462 of file Eojul.h.
Referenced by Eojul(), getBufferPos(), initialize(), operator=(), setEojulAndInfo(), and setMorphAndTag().
unsigned int kmaOrange::Eojul::_posCounts [private]
the position of a count.
Definition at line 464 of file Eojul.h.
Referenced by close(), Eojul(), getCountsPos(), increaseAnalysisResults(), initialize(), operator=(), and setMorphAndTag().
unsigned int kmaOrange::Eojul::_posOrders [private]
the position of a score.
Definition at line 466 of file Eojul.h.
unsigned int kmaOrange::Eojul::_posScores [private]
the position of a score.
Definition at line 465 of file Eojul.h.
Referenced by append(), close(), Eojul(), getScoresPos(), increaseAnalysisResults(), initialize(), operator=(), and setScore().
unsigned int kmaOrange::Eojul::_posTags [private]
the position of a POS tag.
Definition at line 463 of file Eojul.h.
Referenced by Eojul(), getBufferByIndex(), getTagsPos(), initialize(), operator=(), setEojulAndInfo(), and setMorphAndTag().
double* kmaOrange::Eojul::_scores [private]
the buffers of scores.
Definition at line 458 of file Eojul.h.
Referenced by append(), backmerge(), close(), doubleBuffer(), Eojul(), freeBuffer(), getLinkedIndex(), getOneBestIndex(), getScore(), getScoresPtr(), increaseAnalysisResults(), initialize(), makeNBest(), merge(), operator=(), and setScore().
unsigned int kmaOrange::Eojul::_sizeBuffer [private]
the size of a set string.
Definition at line 461 of file Eojul.h.
Referenced by doubleBuffer(), Eojul(), getBufferSize(), initialize(), operator=(), setEojulAndInfo(), setMorphAndTag(), and ~Eojul().
unsigned int* kmaOrange::Eojul::_tags [private]
the buffers of POS tags.
Definition at line 456 of file Eojul.h.
Referenced by addEojulInfo(), append(), backmerge(), doubleBuffer(), Eojul(), freeBuffer(), getBufferByIndex(), getEojulInfo(), getLexicon(), getPOS(), getTagsPtr(), initialize(), merge(), operator=(), setEojulAndInfo(), setEojulInfo(), and setMorphAndTag().
StringEx Eojul::_wcharDelimiter = `£¡:£§:£¬:£®:£¯:£º:£»:£¿:£Þ:£ß:£à:£ü:£þ:¡¢:¡£:¡¤:¡¥:¡¦:¡§:¡¨:¡©:¡ª:¡«:¡¬:¡­:¢¥:¢¦:¢§:¢¨:¢©:¢ª:¢«:¢¬:¢­:¢®:¢¯:¢°:£¢:£¨:£©:£Û:£Ý:£û:£ý:¡®:¡¯:¡°:¡±:¡²:¡³:¡´:¡µ:¡¶:¡·:¡¸:¡¹:¡º:¡»:¡¼:¡½:£«:£­:£¼:£½:£¾:¡¾:¡¿:¡À:¡Á:¡Â:¡Ã:¡Ä:¡Å:¡Î:¡Ï:¡Ð:¡Ñ:¡Ò:¡Ó:¡Ô:¡Õ:¡Ö:¡ì:¡í:¡î:¡ï:¡ð:¡ñ:¡ò:¡ó:¡ô:¡õ:¡ö:¡÷:¡ø:¡ù:¡ú:¡û:¡ü:¡ý:¡þ:¢¡:¢¢:¢£:¢¤:¢±:¢²:¢³:£¤:£¥:£Ü:£Æ:¡Ç:¡È:¡É:¡Ê:¡Ë:¡Ì:¡Í:¢´:¢µ:¢¶:?:§¡:§¢:§£:§¥:§¦:§§:§¨:§©:§ª:§«:§¬:§­:§®:§¯:§°:§±:§²:§³:§´:§µ:§¶:§·:§¸:§¹:§º:§»:§¼:§½:§¾:§¿:§À:§Á:§Â:§Ã:§Ä:§Å:§Æ:§Ç:§È:§É:§Ê:§Ë:§Ì:§Í:§Î:§Ï:§Ð:§Ñ:§Ò:§Ó:§Ô:§Õ:§Ö:§×:§Ø:§Ù:§Ú:§Û:§Ü:§Ý:§Þ:§ß:§à:§á:§â:§ã:§ä:§å:§æ:§ç:§è:§é:§ê:§ë:§ì:§í:§î:§ï:££:£¦:£ª:£À:¡×:¡Ø:¡Ù:¡Ú:¡Û:¡Ü:¡Ý:¡Þ:¡ß:¡à:¡á:¡â:¡ã:¡ä:¡å:¡æ:¡ç:¡è:¡é:¡ê:¡ë:¢¹:¢¸:¢¹:¢º:¢»:¢¼:¢½:¢¾:¢¿:¢Á:¢Â:¢Ã:¢Ä:¢Å:¢Æ:¢Ç:¢È:¢É:¢Ê:¢Ë:¢Ì:¢Í:¢Î:¢Ï:¢Ð:¢Ñ:¢Ò:¢Ó:¢Ô:¢Õ:¢Ö:¢×:¢Ø:¢Ù:¢Ú:¢Û:¢Ü:¢Ý:¢Þ:¢ß:¢à:¢á:¢â:¢ã:¢ä:¢å:?:¨£:¨¬:¦¡:¦¢:¦£:¦¤:¦¥:¦¦:¦§:¦¨:¦©:¦ª:¦«:¦¬:¦­:¦®:¦¯:¦°:¦±:¦²:¦³:¦´:¦µ:¦¶:¦·:¦¸:¦¹:¦º:¦»:¦¼:¦½:¦¾:¦¿:¦À:¦Á:¦Â:¦Ã:¦Ä:¦Å:¦Æ:¦Ç:¦È:¦É:¦Ê:¦Ë:¦Ì:¦Í:¦Î:¦Ï:¦Ð:¦Ñ:¦Ò:¦Ô:¦Õ:¦Ö:¦×:¦Ø:¦Ù:¦Ú:¦Û:¦Ü:¦Ý:¦Þ:¦ß:¦à:¦á:¦â:¦ã:¦ä:¨±:¨²:¨³:¨´:¨µ:¨¶:¨·:¨¸:¨¹:¨º:¨»:¨¼:¨½:¨¾:¨¿:¨À:¨Á:¨Â:¨Ã:¨Ä:¨Å:¨Æ:¨Ç:¨È:¨É:¨Ê:¨Ë:¨Ì:©±:©²:©³:©´:©µ:©¶:©·:©¸:©¹:©º:©»:©¼:©½:©¾:©¿:©À:©Á:©Â:©Ã:©Ä:©Å:©Æ:©Ç:©È:©É:©Ê:©Ë:©Ì:¨Í:¨Î:¨Ï:¨Ð:¨Ñ:¨Ò:¨Ó:¨Ô:¨Õ:¨Ö:¨×:¨Ø:¨Ù:¨Ú:¨Û:¨Ü:¨Ý:¨Þ:¨ß:¨à:¨á:¨â:¨ã:¨ä:¨å:¨æ:¨ç:¨è:¨é:¨ê:¨ë:¨ì:¨í:¨î:¨ï:¨ð:¨ñ:¨ò:¨ó:¨ô:¨õ:©Í:©Î:©Ï:©Ð:©Ñ:©Ò:©Ó:©Ô:©Õ:©Ö:©×:©Ø:©Ù:©Ú:©Û:©Ü:©Ý:©Þ:©ß:©à:©á:©â:©ã:©ä:©å:©æ:©ç:©è:©é:©ê:©ë:©ì:©í:©î:©ï:©ð:©ñ:©ò:©ó:©ô:©õ:£°:£±:£²:£³:£´:£µ:£¶:£·:£¸:£¹:¥¡:¥¢:¥£:¥¤:¥¥:¥¦:¥§:¥¨:¥©:¥ª:¥°:¥±:¥²:¥³:¥´:¥µ:¥¶:¥·:¥¸:¥¹:¨ö:¨÷:¨ø:¨ù:¨ú:¨û:¨ü:¨ý:¨þ:©ö:©÷:©ø:©ù:©ú:©û:©ü:©ý:©þ` [static, private]
the set of 2 bytes special characters.
Definition at line 469 of file Eojul.h.
Referenced by setString().
char kmaOrange::Eojul::innerBuffer[DEFAULT_EOJUL_BUFFER_SIZE]
the inner buffers of strings.
Definition at line 33 of file Eojul.h.
Referenced by Eojul(), and initialize().
unsigned int kmaOrange::Eojul::innerCounts[(int)(DEFAULT_EOJUL_BUFFER_SIZE/RATIO_BUFFER_AND_COUNTS)]
the inner buffers of counts.
Definition at line 35 of file Eojul.h.
Referenced by Eojul(), and initialize().
unsigned int kmaOrange::Eojul::innerOrders[(int)(DEFAULT_EOJUL_BUFFER_SIZE/RATIO_BUFFER_AND_COUNTS)*2]
the inner buffers of orders.
Definition at line 37 of file Eojul.h.
Referenced by freeBuffer(), and makeNBest().
double kmaOrange::Eojul::innerScores[(int)(DEFAULT_EOJUL_BUFFER_SIZE/RATIO_BUFFER_AND_COUNTS)]
the inner buffers of scores.
Definition at line 36 of file Eojul.h.
Referenced by Eojul(), and initialize().
unsigned int kmaOrange::Eojul::innerTags[(int)(DEFAULT_EOJUL_BUFFER_SIZE/RATIO_BUFFER_AND_TAGS)]
the inner buffers of POS tags.
Definition at line 34 of file Eojul.h.
Referenced by Eojul(), and initialize().
unsigned int kmaOrange::Eojul::mIndexLength
the length of DIGIT or ALPHABET, which is a index word.
Definition at line 200 of file Eojul.h.
Referenced by isIndexWord(), and kmaOrange::MAnalyzer::setOption().
unsigned int kmaOrange::Eojul::mIndexTagSet
the set of index POS tags.
Definition at line 199 of file Eojul.h.
Referenced by isIndexWord(), kmaOrange::MAnalyzer::setDefault(), and kmaOrange::MAnalyzer::setOption().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/kma/Eojul.h
/disk/workspace-cpp/la-manager/source/kma/Eojul.cpp