WK_Analyzer Class Reference
a class for KMA execution.
#include <wk_analyzer.h>
Public Member Functions
virtual ~WK_Analyzer ()
virtual void setKnowledge (WK_Knowledge *pKnowledge)=0
This function sets a WK_Knowledge object.
virtual void setEojul (WK_Eojul *pEojul)=0
This function sets a WK_Eojul object.
virtual void setOption (int nOption, int nValue)=0
This function sets Korean morphological analyzing options.
virtual void setExOption (int nOption)=0
This function sets execution options.
virtual int runWithEojul (void)=0
This function executes Korean morphological analysis based on a word.
virtual int runWithString (char *strLine, char *strNameOutFile)=0
This function executes Korean morphological analysis based on a sentence.
virtual int runWithString (char *strLine)=0
virtual int runWithStream (char *strNameInFile, char *strNameOutFile)=0
This function executes Korean morphological analysis based on a file.
virtual int runWithStream (char *strNameInFile)=0
virtual int runWithStream ()=0
virtual WK_Eojul * getEojulInSentence (int nPos)=0
This function gets a Eojul object for a word in a sentence.
virtual int getEojulCountInSentence (void)=0
This function gets the number of words in a sentence.
virtual void makePreAnalysisDic (void)=0
This function makes the pre-analysis dictionary file in the system dictionary.
virtual int getEojulOffsetInSentence (int nPos)=0
virtual void tagging (void)=0
Static Public Member Functions
static WK_Analyzer * createObject (WK_Knowledge *pKnowledge, WK_Eojul *pEojul)
This function creates a WK_Analyzer object.
static WK_Analyzer * createObject (WK_Knowledge *pKnowledge)
static WK_Analyzer * createObject (const char *path)
Detailed Description
a class for KMA execution.
Date: 2008-10-31
Author: HeeGeun Park
Definition at line 38 of file wk_analyzer.h.
Constructor & Destructor Documentation
WK_Analyzer::~WK_Analyzer () [virtual]
Definition at line 29 of file wk_analyzer.cpp.
Member Function Documentation
WK_Analyzer * WK_Analyzer::createObject (const char * path) [static]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 14 of file wk_analyzer.cpp.
WK_Analyzer * WK_Analyzer::createObject (WK_Knowledge * pKnowledge) [static]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 19 of file wk_analyzer.cpp.
WK_Analyzer * WK_Analyzer::createObject (WK_Knowledge * pKnowledge, WK_Eojul * pEojul) [static]
This function creates a WK_Analyzer object.
Date: 2008-10-31
Author: HeeGeun Park
Parameters:
pKnowledge a pointer of a WK_Knowledge object.
pEojul a pointer of a WK_Eojul object.
Returns: a pointer of a WK_Analyzer object.
Definition at line 24 of file wk_analyzer.cpp.
Referenced by la_manager::KoreanNounFilter::KoreanNounFilter().
virtual int WK_Analyzer::getEojulCountInSentence (void) [pure virtual]
This function gets the number of words in a sentence.
Date: 2008-10-31
Author: HeeGeun Park
Returns: an integer - the number of words in a sentence.
Implemented in kmaOrange::MAnalyzer.
virtual WK_Eojul* WK_Analyzer::getEojulInSentence (int nPos) [pure virtual]
This function gets a Eojul object for a word in a sentence.
Date: 2008-10-31
Author: HeeGeun Park
Parameters:
nPos an integer - the index number of a word in a sentence.
Returns: a pointer of a WK_Eojul object.
Implemented in kmaOrange::MAnalyzer.
virtual int WK_Analyzer::getEojulOffsetInSentence (int nPos) [pure virtual]
Implemented in kmaOrange::MAnalyzer.
virtual void WK_Analyzer::makePreAnalysisDic (void) [pure virtual]
This function makes the pre-analysis dictionary file in the system dictionary.
Date: 2009-01-07
Author: HeeGeun Park
Implemented in kmaOrange::MAnalyzer.
virtual int WK_Analyzer::runWithEojul (void) [pure virtual]
This function executes Korean morphological analysis based on a word.
Date: 2008-10-31
Author: HeeGeun Park
Returns: an integer.
 0 - fail.
 1 - success.
Implemented in kmaOrange::MAnalyzer.
Referenced by la_manager::KoreanNounFilter::analyze().
int WK_Analyzer::runWithStream () [pure virtual]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Implemented in kmaOrange::MAnalyzer.
int WK_Analyzer::runWithStream (char * strNameInFile) [pure virtual]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Implemented in kmaOrange::MAnalyzer.
virtual int WK_Analyzer::runWithStream (char * strNameInFile, char * strNameOutFile) [pure virtual]
This function executes Korean morphological analysis based on a file.
Date: 2008-10-31
Author: HeeGeun Park
Parameters:
strNameInFile a pointer of a character - input file.
strNameOutFile a pointer of a character - output file.
Returns: an integer.
 0 - fail.
 1 - success.
Implemented in kmaOrange::MAnalyzer.
int WK_Analyzer::runWithString (char * strLine) [pure virtual]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Implemented in kmaOrange::MAnalyzer.
virtual int WK_Analyzer::runWithString (char * strLine, char * strNameOutFile) [pure virtual]
This function executes Korean morphological analysis based on a sentence.
Date: 2008-10-31
Author: HeeGeun Park
Parameters:
strLine a pointer of a character - input string.
strNameOutFile a pointer of a character - the name of the output file.
Returns: an integer.
 0 - fail.
 1 - success.
Implemented in kmaOrange::MAnalyzer.
virtual void WK_Analyzer::setEojul (WK_Eojul * pEojul) [pure virtual]
This function sets a WK_Eojul object.
Date: 2008-10-31
Author: HeeGeun Park
Parameters:
pEojul a pointer of a WK_Eojul object.
Implemented in kmaOrange::MAnalyzer.
virtual void WK_Analyzer::setExOption (int nOption) [pure virtual]
This function sets execution options.
Date: 2008-10-31
Author: HeeGeun Park
Parameters:
nOption an integer - a kind of execution options.
Implemented in kmaOrange::MAnalyzer.
Referenced by la_manager::KoreanNounFilter::KoreanNounFilter().
virtual void WK_Analyzer::setKnowledge (WK_Knowledge * pKnowledge) [pure virtual]
This function sets a WK_Knowledge object.
Date: 2008-10-31
Author: HeeGeun Park
Parameters:
pKnowledge a pointer of a WK_Knowledge object.
Implemented in kmaOrange::MAnalyzer.
virtual void WK_Analyzer::setOption (int nOption, int nValue) [pure virtual]
This function sets Korean morphological analyzing options.
Date: 2008-10-31
Author: HeeGeun Park
Parameters:
nOption an integer - a kind of analyzing options.
nValue an integer - the value of a variable nOption.
Implemented in kmaOrange::MAnalyzer.
Referenced by la_manager::KoreanNounFilter::KoreanNounFilter().
virtual void WK_Analyzer::tagging (void) [pure virtual]
Implemented in kmaOrange::MAnalyzer.
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/kma/wk_analyzer.h
/disk/workspace-cpp/la-manager/source/kma/wk_analyzer.cpp