kmaOrange::JEBuffer Class Reference
This class is stored the string buffer and the information of a searched postposition or ending in a word.
#include <Buffer.h>
Public Member Functions
JEBuffer (unsigned int size=DEFAULT_BUFFER_BUFFER_SIZE)
This function is a constructor of a JEBuffer object.
~JEBuffer (void)
This function is a destructor of a JEBuffer object.
int appendInfo (int pos, unsigned int tag, short int info, unsigned char coda)
This function inserts the information of a postposition or ending in a word.
void freeJEBuffer ()
This function frees the allocated memories for a JEBuffer object.
int doubleJEBuffer ()
This function enlarges twice the allocated memories for a JEBuffer object.
unsigned int getPos () const
This function gets the current position of the buffer.
unsigned int getSize () const
This function gets the size of the buffer.
unsigned int * getIndexesPtr () const
This function gets the starting pointer of the list of starting positions.
unsigned int * getTagsPtr () const
This function gets the starting pointer of the list of POS tags.
short int * getInfosPtr () const
This function gets the starting pointer of the list of information codes.
unsigned char * getCodasPtr () const
This function gets the starting pointer of the list of codas.
void setPos (int pos)
This function sets the current position of the buffer.
void setSize (int size)
This function sets the size of the buffer.
void reserve (int size)
This function sets the size of the buffer.
Private Attributes
unsigned int * _indexes
the list of starting positions.
unsigned int * _tags
the list of POS tags.
short int * _infos
the list of information codes.
unsigned char * _codas
the list of codas.
unsigned int _size
the size of the buffer.
unsigned int _pos
the position of the buffer.
Detailed Description
This class is stored the string buffer and the information of a searched postposition or ending in a word.
Date: 2008-11-17
Author: YoungMin Ahn
See also: Buffer
Definition at line 266 of file Buffer.h.
Constructor & Destructor Documentation
JEBuffer::JEBuffer (unsigned int size = DEFAULT_BUFFER_BUFFER_SIZE)
This function is a constructor of a JEBuffer object.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
size an unsigned integer - the size of a set string in a JEBuffer object.
Definition at line 224 of file Buffer.cpp.
References _codas, _indexes, _infos, _pos, _size, _tags, DEFAULT_BUFFER_BUFFER_SIZE, and kmaOrange::Logger::SetMessage().
JEBuffer::~JEBuffer (void)
This function is a destructor of a JEBuffer object.
Date: 2008-11-17
Author: YoungMin Ahn
Definition at line 246 of file Buffer.cpp.
References freeJEBuffer().
Member Function Documentation
int JEBuffer::appendInfo (int pos, unsigned int tag, short int info, unsigned char coda)
This function inserts the information of a postposition or ending in a word.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
pos an integer - the starting position of a postposition or ending in a word.
tag an unsigned integer - the POS tag of a postposition or ending.
info a short integer - the information code of a postposition or ending.
coda an unsigned character - the KSSM code for the first byte of a postposition or ending, which has a coda(final consonant) as the first syllable.
Returns: an integer.
Definition at line 281 of file Buffer.cpp.
References _codas, _indexes, _infos, _pos, _size, _tags, and doubleJEBuffer().
Referenced by kmaOrange::Dictionary::readJosaEomiDictionary(), and kmaOrange::Dictionary::setOnsetEomi().
int JEBuffer::doubleJEBuffer ()
This function enlarges twice the allocated memories for a JEBuffer object.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: an interger.
Definition at line 298 of file Buffer.cpp.
References _codas, _indexes, _infos, _size, _tags, freeJEBuffer(), and TWICE.
Referenced by appendInfo().
void JEBuffer::freeJEBuffer ()
This function frees the allocated memories for a JEBuffer object.
Date: 2008-11-17
Author: YoungMin Ahn
Definition at line 273 of file Buffer.cpp.
References _codas, _indexes, _infos, and _tags.
Referenced by doubleJEBuffer(), and ~JEBuffer().
unsigned char* kmaOrange::JEBuffer::getCodasPtr () const [inline]
This function gets the starting pointer of the list of codas.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: a pointer of an unsigned character.
Definition at line 357 of file Buffer.h.
References _codas.
Referenced by kmaOrange::Dictionary::getJEInfo(), kmaOrange::Dictionary::readJosaEomiTrie(), and kmaOrange::Dictionary::writeJosaEomiTrie().
unsigned int* kmaOrange::JEBuffer::getIndexesPtr () const [inline]
This function gets the starting pointer of the list of starting positions.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: a pointer of an unsigned integer.
Definition at line 333 of file Buffer.h.
References _indexes.
Referenced by kmaOrange::Dictionary::getJEInfo(), kmaOrange::Dictionary::readJosaEomiTrie(), and kmaOrange::Dictionary::writeJosaEomiTrie().
short int* kmaOrange::JEBuffer::getInfosPtr () const [inline]
This function gets the starting pointer of the list of information codes.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: a pointer of an short integer.
Definition at line 349 of file Buffer.h.
References _infos.
Referenced by kmaOrange::Dictionary::getJEInfo(), kmaOrange::Dictionary::readJosaEomiTrie(), and kmaOrange::Dictionary::writeJosaEomiTrie().
unsigned int kmaOrange::JEBuffer::getPos () const [inline]
This function gets the current position of the buffer.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: an unsigned interger.
Definition at line 317 of file Buffer.h.
References _pos.
Referenced by kmaOrange::Dictionary::readJosaEomiDictionary(), kmaOrange::Dictionary::setOnsetEomi(), and kmaOrange::Dictionary::writeJosaEomiTrie().
unsigned int kmaOrange::JEBuffer::getSize () const [inline]
This function gets the size of the buffer.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: an unsigned interger.
Definition at line 325 of file Buffer.h.
References _size.
unsigned int* kmaOrange::JEBuffer::getTagsPtr () const [inline]
This function gets the starting pointer of the list of POS tags.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: a pointer of an unsigned integer.
Definition at line 341 of file Buffer.h.
References _tags.
Referenced by kmaOrange::Dictionary::getJEInfo(), kmaOrange::Dictionary::readJosaEomiTrie(), and kmaOrange::Dictionary::writeJosaEomiTrie().
void JEBuffer::reserve (int size)
This function sets the size of the buffer.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
size an integer - the size of the buffer.
Definition at line 251 of file Buffer.cpp.
References _codas, _indexes, _infos, _pos, _size, _tags, DEFAULT_BUFFER_BUFFER_SIZE, and kmaOrange::Logger::SetMessage().
Referenced by kmaOrange::Dictionary::readJosaEomiTrie().
void kmaOrange::JEBuffer::setPos (int pos) [inline]
This function sets the current position of the buffer.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
pos an integer - the current position of the buffer.
Definition at line 365 of file Buffer.h.
References _pos.
Referenced by kmaOrange::Dictionary::readJosaEomiTrie().
void kmaOrange::JEBuffer::setSize (int size) [inline]
This function sets the size of the buffer.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
size an integer - the size of the buffer.
Definition at line 373 of file Buffer.h.
References _size.
Member Data Documentation
unsigned char* kmaOrange::JEBuffer::_codas [private]
the list of codas.
Definition at line 387 of file Buffer.h.
Referenced by appendInfo(), doubleJEBuffer(), freeJEBuffer(), getCodasPtr(), JEBuffer(), and reserve().
unsigned int* kmaOrange::JEBuffer::_indexes [private]
the list of starting positions.
Definition at line 384 of file Buffer.h.
Referenced by appendInfo(), doubleJEBuffer(), freeJEBuffer(), getIndexesPtr(), JEBuffer(), and reserve().
short int* kmaOrange::JEBuffer::_infos [private]
the list of information codes.
Definition at line 386 of file Buffer.h.
Referenced by appendInfo(), doubleJEBuffer(), freeJEBuffer(), getInfosPtr(), JEBuffer(), and reserve().
unsigned int kmaOrange::JEBuffer::_pos [private]
the position of the buffer.
Definition at line 389 of file Buffer.h.
Referenced by appendInfo(), getPos(), JEBuffer(), reserve(), and setPos().
unsigned int kmaOrange::JEBuffer::_size [private]
the size of the buffer.
Definition at line 388 of file Buffer.h.
Referenced by appendInfo(), doubleJEBuffer(), getSize(), JEBuffer(), reserve(), and setSize().
unsigned int* kmaOrange::JEBuffer::_tags [private]
the list of POS tags.
Definition at line 385 of file Buffer.h.
Referenced by appendInfo(), doubleJEBuffer(), freeJEBuffer(), getTagsPtr(), JEBuffer(), and reserve().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/kma/Buffer.h
/disk/workspace-cpp/la-manager/source/kma/Buffer.cpp