kmaOrange::StrStream Class Reference
This class manages the input and output of the KMA.
#include <StrStream.h>
Public Member Functions
StrStream (StringEx nameinfile, StringEx nameoutfile)
This function is a constructor of a StrStream object.
StrStream (StringEx nameinfile)
StrStream ()
~StrStream ()
This function is a destructor of StrStream object.
void write (const char *pstr)
This function outputs the input string to the set output stream.
void write (const StringEx &strex)
void writeLine (const StringEx &strex)
This function outputs the input string to the set output stream on one line.
int getLine (StringEx &strex)
This function gets the string of a line in an input file.
StringEx getLine ()
This function gets the string of a line in an input file.
int cinGetLine (char *pstr, int MAX)
This function gets the string of a line from the standard input.
void setStream (StringEx nameinfile, StringEx nameoutfile)
This function sets both the input stream and the output stream to the file.
void setStream (StringEx nameinfile)
This function sets the input stream to the file, and sets the output stream to the standard output.
void setInStream (StringEx nameinfile)
This function sets the input stream to the file.
void setOutStream (StringEx nameoutfile)
This function sets the output stream to the file.
void close ()
This function closes both the input stream and the output stream.
int isInEOF ()
This function checks whether the current position of the input stream is the end of the input stream or not.
std::istream & getInStream ()
This function gets the input stream.
std::ostream & getOutStream ()
This function gets the output stream.
bool IsInFileOpen ()
This function checks whether the input stream is the file or not.
bool IsOutFileOpen ()
This function checks whether the output stream is the file or not.
Private Attributes
ifstream _fin
file input stream.
ofstream _fout
file output stream.
int _status
this variable stores whether the input stream or the output stream is created or not.
int _isInFile
this variable stores whether the input stream is the file or not.
int _isOutFile
this variable stores whether the output stream is the file or not.
Friends
StrStream & operator<< (StrStream &sout, const StringEx &strex)
This function outputs the input string to the set output stream.
StrStream & operator<< (StrStream &sout, const char *pstr)
StrStream & operator<< (StrStream &sout, const char ch)
StrStream & operator<< (StrStream &sout, const int n)
Detailed Description
This class manages the input and output of the KMA.
Date: 2008-11-17
Author: YoungMin Ahn
Definition at line 29 of file StrStream.h.
Constructor & Destructor Documentation
StrStream::StrStream (StringEx nameinfile, StringEx nameoutfile)
This function is a constructor of a StrStream object.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
nameinfile a StringEx object - the name of an input file.
nameoutfile a StringEx object - the name of an output file.
Definition at line 24 of file StrStream.cpp.
References setInStream(), and setOutStream().
StrStream::StrStream (StringEx nameinfile)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 19 of file StrStream.cpp.
References setInStream().
StrStream::StrStream ()
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 14 of file StrStream.cpp.
References _status.
StrStream::~StrStream ()
This function is a destructor of StrStream object.
Date: 2008-11-17
Author: YoungMin Ahn
Definition at line 30 of file StrStream.cpp.
References close().
Member Function Documentation
int StrStream::cinGetLine (char * pstr, int MAX)
This function gets the string of a line from the standard input.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
pstr a pointer of a character - a string repository.
MAX an integer - the maximum size of a string repository.
Returns: an integer - MAX.
Definition at line 93 of file StrStream.cpp.
void kmaOrange::StrStream::close () [inline]
This function closes both the input stream and the output stream.
Date: 2008-11-17
Author: YoungMin Ahn
Definition at line 146 of file StrStream.h.
References _fin, _fout, _isInFile, and _isOutFile.
Referenced by kmaOrange::MAnalyzer::commonRunWithStream(), and ~StrStream().
std::istream& kmaOrange::StrStream::getInStream () [inline]
This function gets the input stream.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: an indirect referencing pointer of a std::istream.
Definition at line 168 of file StrStream.h.
References _fin, and _isInFile.
StringEx StrStream::getLine ()
This function gets the string of a line in an input file.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: a StringEx object - a string of a line.
Definition at line 117 of file StrStream.cpp.
References _fin, _isInFile, StringEx::setLength(), and SIZE_LINE_BUFFER.
int StrStream::getLine (StringEx & strex)
This function gets the string of a line in an input file.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
strex an indirect referencing pointer of a constant StringEx object - a string repository.
Returns: an integer.
 0 - fail.
 1 - success.
Definition at line 152 of file StrStream.cpp.
References _fin, _isInFile, StringEx::getBufferSize(), StringEx::setBufferSize(), StringEx::setLength(), and SIZE_LINE_BUFFER.
Referenced by kmaOrange::MAnalyzer::commonRunWithStream().
std::ostream& kmaOrange::StrStream::getOutStream () [inline]
This function gets the output stream.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: an indirect referencing pointer of a std::ostream.
Definition at line 180 of file StrStream.h.
References _fout, and _isOutFile.
Referenced by kmaOrange::MAnalyzer::preprocessBeforeAnalysis(), kmaOrange::Tagger::showResult(), and kmaOrange::MAnalyzer::tokenizeSentence().
int StrStream::isInEOF ()
This function checks whether the current position of the input stream is the end of the input stream or not.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: an integer.
 0 - not the end of the input stream. 1 - the end of the input stream.
Definition at line 81 of file StrStream.cpp.
References _fin, and _isInFile.
Referenced by kmaOrange::MAnalyzer::commonRunWithStream().
bool kmaOrange::StrStream::IsInFileOpen () [inline]
This function checks whether the input stream is the file or not.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: a boolean.
 true - file.
 false - not file.
Definition at line 219 of file StrStream.h.
References _isInFile.
bool kmaOrange::StrStream::IsOutFileOpen () [inline]
This function checks whether the output stream is the file or not.
Date: 2008-11-17
Author: YoungMin Ahn
Returns: a boolean.
 true - file.
 false - not file.
Definition at line 229 of file StrStream.h.
References _isOutFile.
void StrStream::setInStream (StringEx nameinfile)
This function sets the input stream to the file.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
nameinfile a StringEx object - the name of an input file.
Definition at line 46 of file StrStream.cpp.
References _fin, _isInFile, _status, StringEx::getBuffer(), and kmaOrange::Logger::SetMessage().
Referenced by setStream(), and StrStream().
void StrStream::setOutStream (StringEx nameoutfile)
This function sets the output stream to the file.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
nameoutfile a StringEx object - the name of an output file.
Definition at line 64 of file StrStream.cpp.
References _fout, _isOutFile, _status, StringEx::getBuffer(), and kmaOrange::Logger::SetMessage().
Referenced by kmaOrange::MAnalyzer::runWithString(), setStream(), and StrStream().
void StrStream::setStream (StringEx nameinfile)
This function sets the input stream to the file, and sets the output stream to the standard output.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
nameinfile a StringEx object - the name of an input file.
Definition at line 35 of file StrStream.cpp.
References setInStream().
void StrStream::setStream (StringEx nameinfile, StringEx nameoutfile)
This function sets both the input stream and the output stream to the file.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
nameinfile a StringEx object - the name of an input file.
nameoutfile a StringEx object - the name of an output file.
Definition at line 40 of file StrStream.cpp.
References setInStream(), and setOutStream().
Referenced by kmaOrange::MAnalyzer::runWithStream().
void StrStream::write (const StringEx & strex)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 204 of file StrStream.cpp.
References _fout, and _isOutFile.
void StrStream::write (const char * pstr)
This function outputs the input string to the set output stream.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
pstr a pointer of a constant character - an input string.
Definition at line 216 of file StrStream.cpp.
References _fout, and _isOutFile.
void StrStream::writeLine (const StringEx & strex)
This function outputs the input string to the set output stream on one line.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
strex an indirect referencing pointer of a constant StringEx object - an input string.
Definition at line 190 of file StrStream.cpp.
References _fout, and _isOutFile.
Referenced by kmaOrange::Tagger::showResult().
Friends And Related Function Documentation
StrStream& operator<< (StrStream & sout, const int n) [friend]
Definition at line 272 of file StrStream.cpp.
StrStream& operator<< (StrStream & sout, const char ch) [friend]
Definition at line 258 of file StrStream.cpp.
StrStream& operator<< (StrStream & sout, const char * pstr) [friend]
Definition at line 244 of file StrStream.cpp.
StrStream& operator<< (StrStream & sout, const StringEx & strex) [friend]
This function outputs the input string to the set output stream.
Date: 2008-11-17
Author: YoungMin Ahn
Parameters:
sout an indirect referencing pointer of a StrStream object - the set output stream.
strex an indirect referencing pointer of a constant StringEx object - an input string.
Returns: an indirect referencing pointer of a StrStream object.
Definition at line 230 of file StrStream.cpp.
Member Data Documentation
ifstream kmaOrange::StrStream::_fin [private]
file input stream.
Definition at line 229 of file StrStream.h.
Referenced by close(), getInStream(), getLine(), isInEOF(), and setInStream().
ofstream kmaOrange::StrStream::_fout [private]
file output stream.
Definition at line 233 of file StrStream.h.
Referenced by close(), getOutStream(), kmaOrange::operator<<(), setOutStream(), write(), and writeLine().
int kmaOrange::StrStream::_isInFile [private]
this variable stores whether the input stream is the file or not.
Definition at line 236 of file StrStream.h.
Referenced by close(), getInStream(), getLine(), isInEOF(), IsInFileOpen(), and setInStream().
int kmaOrange::StrStream::_isOutFile [private]
this variable stores whether the output stream is the file or not.
Definition at line 237 of file StrStream.h.
Referenced by close(), getOutStream(), IsOutFileOpen(), kmaOrange::operator<<(), setOutStream(), write(), and writeLine().
int kmaOrange::StrStream::_status [private]
this variable stores whether the input stream or the output stream is created or not.
Definition at line 235 of file StrStream.h.
Referenced by setInStream(), setOutStream(), and StrStream().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/kma/StrStream.h
/disk/workspace-cpp/la-manager/source/kma/StrStream.cpp