kmaOrange::Logger Class Reference
#include <logger.h>
Public Member Functions
Logger ()
virtual ~Logger ()
Static Public Member Functions
static int SetMessage (StringEx name, StringEx message)
static int SetMessage (StringEx message)
Static Public Attributes
static StringEx pathlog = LOG_PATH
static StringEx namelog = ``
Detailed Description
Definition at line 16 of file logger.h.
Constructor & Destructor Documentation
Logger::Logger ()
Definition at line 30 of file logger.cpp.
Logger::~Logger () [virtual]
Definition at line 34 of file logger.cpp.
Member Function Documentation
int Logger::SetMessage (StringEx message) [static]
Definition at line 38 of file logger.cpp.
References pathlog, and StringEx::replaceString().
int Logger::SetMessage (StringEx name, StringEx message) [static]
Definition at line 73 of file logger.cpp.
References pathlog.
Referenced by kmaOrange::Eojul::Eojul(), kmaOrange::InfoBuffer::InfoBuffer(), kmaOrange::JEBuffer::JEBuffer(), kmaOrange::JEBuffer::reserve(), kmaOrange::Buffer::reserveBuffer(), kmaOrange::StrStream::setInStream(), kmaOrange::StrStream::setOutStream(), kmaOrange::Eojul::setString(), and kmaOrange::MAnalyzer::tokenizeSentence().
Member Data Documentation
StringEx Logger::namelog = `` [static]
Definition at line 25 of file logger.h.
StringEx Logger::pathlog = LOG_PATH [static]
Definition at line 24 of file logger.h.
Referenced by SetMessage().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/kma/logger.h
/disk/workspace-cpp/la-manager/source/kma/logger.cpp