kmaOrange::WK_DaTrie Class Reference
#include <daTrie.h>
Public Types
enum { BC_EXTEND_SIZE = 1024 * 100,
TAIL_EXTEND_SIZE = 1024 * 50,
KEY_LEN = 128,
TERMINAL = 0x3b
 }
Public Member Functions
WK_DaTrie ()
virtual ~WK_DaTrie ()
bool isCreated ()
int create (int bcSize=BC_EXTEND_SIZE, int tailSize=TAIL_EXTEND_SIZE, int bcExtendSize=BC_EXTEND_SIZE, int tailExtendSize=TAIL_EXTEND_SIZE)
int insertKey (const char *pKey, WK_DaTrie_Node &rNode)
int getBcPos (void)
int getTailPos (void)
int getBcEmptyStart (void)
int getBcEmptyEnd (void)
WK_DaTrie_BaseCheck * getBaseCheckArray (void)
unsigned char * getTailBuffer (void)
void free ()
void setBcPos (int bcPos)
void setTailPos (int tailPos)
void setBcEmptyStart (int bcEmptyStart)
void setBcEmptyEnd (int bcEmptyEnd)
int searchKey (const char *pKey, WK_DaTrie_Node &rNode)
int findNode (const char ch, WK_DaTrie_Node &rNode)
Private Member Functions
int compareTail (int index, unsigned char *pSingleString)
int getList (int index, unsigned char *pList)
int xCheck (unsigned char *pList)
int modify (int currentIndex, int index, unsigned char add, unsigned char *pList, int listsize)
int extendBc (void)
int extendTail (void)
void setEmptyLink (int index)
void setBase (int index, int value)
void setCheck (int index, int value)
void writeTailAt (int index, unsigned char *pkey, int tailpos)
void insertA (int index, unsigned char *pkey, WK_DaTrie_Node &rNode)
void insertB (int index, unsigned char *pkey, WK_DaTrie_Node &rNode)
void appendTerminator (const char *pKey, unsigned char *pBuff)
Private Attributes
WK_DaTrie_BaseCheck * mpBc
int mBcMax
int mBcExtendSize
int mBcPos
int mBcEmptyStart
int mBcEmptyEnd
unsigned char * mpTail
int mTailMax
int mTailExtendSize
int mTailPos
Detailed Description
Definition at line 58 of file daTrie.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
BC_EXTEND_SIZE
TAIL_EXTEND_SIZE
KEY_LEN
TERMINAL
Definition at line 108 of file daTrie.h.
Constructor & Destructor Documentation
WK_DaTrie::WK_DaTrie ()
Definition at line 32 of file daTrie.cpp.
References mBcEmptyEnd, mBcEmptyStart, mBcExtendSize, mBcMax, mBcPos, mpBc, mpTail, mTailExtendSize, mTailMax, and mTailPos.
WK_DaTrie::~WK_DaTrie () [virtual]
Definition at line 47 of file daTrie.cpp.
References free().
Member Function Documentation
void kmaOrange::WK_DaTrie::appendTerminator (const char * pKey, unsigned char * pBuff) [inline, private]
Definition at line 276 of file daTrie.h.
References KEY_LEN, and TERMINAL.
Referenced by insertKey(), and searchKey().
int WK_DaTrie::compareTail (int index, unsigned char * pSingleString) [private]
Definition at line 160 of file daTrie.cpp.
References kmaOrange::WK_DaTrie_BaseCheck::Base, mpBc, mpTail, and TERMINAL.
Referenced by insertKey(), and searchKey().
int WK_DaTrie::create (int bcSize = BC_EXTEND_SIZE, int tailSize = TAIL_EXTEND_SIZE, int bcExtendSize = BC_EXTEND_SIZE, int tailExtendSize = TAIL_EXTEND_SIZE)
check array에 index(s) 노드 값을 반환한다.
Parameters:
index(s) : 노드
Returns: index(s) 노드에 해당하는 값
Definition at line 393 of file daTrie.cpp.
References kmaOrange::WK_DaTrie_BaseCheck::Base, kmaOrange::WK_DaTrie_BaseCheck::Check, KEY_LEN, mBcEmptyEnd, mBcEmptyStart, mBcExtendSize, mBcMax, mBcPos, mpBc, mpTail, mTailExtendSize, mTailMax, mTailPos, kmaOrange::NUM_CODES, and TERMINAL.
Referenced by kmaOrange::SynonymContainer::createTrie(), kmaOrange::StopWordContainer::createTrie(), kmaOrange::Dictionary::loadKnowledge(), kmaOrange::Dictionary::loadPreAnalysis(), kmaOrange::Dictionary::readDivideInfo(), kmaOrange::Dictionary::readDivPosTrie(), kmaOrange::Dictionary::readJosaEomiTrie(), kmaOrange::Dictionary::readMainTrie(), kmaOrange::Dictionary::readPostionInfo(), kmaOrange::Dictionary::readPreAnalysisTrie(), kmaOrange::AuxVerb::setAVList(), kmaOrange::PreFinalEomi::setEPList(), and kmaOrange::PredicativeSuffix::setXSDList().
int WK_DaTrie::extendBc (void) [private]
Definition at line 441 of file daTrie.cpp.
References free(), mBcExtendSize, mBcMax, mpBc, and kmaOrange::NUM_CODES.
Referenced by setBase(), setCheck(), and writeTailAt().
int WK_DaTrie::extendTail (void) [private]
Definition at line 473 of file daTrie.cpp.
References free(), KEY_LEN, mpTail, mTailExtendSize, and mTailMax.
Referenced by writeTailAt().
int kmaOrange::WK_DaTrie::findNode (const char ch, WK_DaTrie_Node & rNode) [inline]
Definition at line 187 of file daTrie.h.
References kmaOrange::WK_DaTrie_BaseCheck::Base, kmaOrange::WK_DaTrie_BaseCheck::Check, kmaOrange::CODE, mBcPos, mpBc, kmaOrange::WK_DaTrie_Node::mpData, mpTail, kmaOrange::WK_DaTrie_Node::mState, and TERMINAL.
Referenced by kmaOrange::AuxVerb::searchNgetInfoFromAvTrie(), kmaOrange::Dictionary::searchNgetInfoFromDivTrie(), kmaOrange::PreFinalEomi::searchNgetInfoFromEpTrie(), kmaOrange::Dictionary::searchNgetInfoFromJosaEomiTrie(), kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Dictionary::searchNgetInfoFromPosTrie(), kmaOrange::Dictionary::searchNgetInfoFromPreAnalTrie(), kmaOrange::StopWordContainer::searchNgetInfoFromStopWordTrie(), kmaOrange::SynonymContainer::searchNgetInfoFromSynonymTrie(), and kmaOrange::PredicativeSuffix::searchNgetInfoFromXsdTrie().
void WK_DaTrie::free ()
Definition at line 428 of file daTrie.cpp.
References mBcMax, mBcPos, mpBc, mpTail, mTailMax, and mTailPos.
Referenced by extendBc(), extendTail(), and ~WK_DaTrie().
WK_DaTrie_BaseCheck * kmaOrange::WK_DaTrie::getBaseCheckArray (void) [inline]
Definition at line 248 of file daTrie.h.
References mpBc.
Referenced by kmaOrange::Dictionary::readDivPosTrie(), kmaOrange::Dictionary::readJosaEomiTrie(), kmaOrange::Dictionary::readMainTrie(), kmaOrange::Dictionary::readPreAnalysisTrie(), kmaOrange::Dictionary::writeDivPosTrie(), kmaOrange::Dictionary::writeJosaEomiTrie(), kmaOrange::Dictionary::writeMainTrie(), and kmaOrange::Dictionary::writePreAnalysisTrie().
int kmaOrange::WK_DaTrie::getBcEmptyEnd (void) [inline]
Definition at line 271 of file daTrie.h.
References mBcEmptyEnd.
Referenced by kmaOrange::Dictionary::writeDivPosTrie(), kmaOrange::Dictionary::writeJosaEomiTrie(), kmaOrange::Dictionary::writeMainTrie(), and kmaOrange::Dictionary::writePreAnalysisTrie().
int kmaOrange::WK_DaTrie::getBcEmptyStart (void) [inline]
Definition at line 266 of file daTrie.h.
References mBcEmptyStart.
Referenced by kmaOrange::Dictionary::writeDivPosTrie(), kmaOrange::Dictionary::writeJosaEomiTrie(), kmaOrange::Dictionary::writeMainTrie(), and kmaOrange::Dictionary::writePreAnalysisTrie().
int kmaOrange::WK_DaTrie::getBcPos (void) [inline]
Definition at line 251 of file daTrie.h.
References mBcPos.
Referenced by kmaOrange::Dictionary::writeDivPosTrie(), kmaOrange::Dictionary::writeJosaEomiTrie(), kmaOrange::Dictionary::writeMainTrie(), and kmaOrange::Dictionary::writePreAnalysisTrie().
int WK_DaTrie::getList (int index, unsigned char * pList) [private]
Definition at line 176 of file daTrie.cpp.
References kmaOrange::WK_DaTrie_BaseCheck::Base, mpBc, and kmaOrange::NUM_CODES.
Referenced by insertA().
unsigned char * kmaOrange::WK_DaTrie::getTailBuffer (void) [inline]
Definition at line 257 of file daTrie.h.
References mpTail.
Referenced by kmaOrange::Dictionary::readDivPosTrie(), kmaOrange::Dictionary::readJosaEomiTrie(), kmaOrange::Dictionary::readMainTrie(), kmaOrange::Dictionary::readPreAnalysisTrie(), kmaOrange::Dictionary::writeDivPosTrie(), kmaOrange::Dictionary::writeJosaEomiTrie(), kmaOrange::Dictionary::writeMainTrie(), and kmaOrange::Dictionary::writePreAnalysisTrie().
int kmaOrange::WK_DaTrie::getTailPos (void) [inline]
Definition at line 260 of file daTrie.h.
References mTailPos.
Referenced by kmaOrange::Dictionary::writeDivPosTrie(), kmaOrange::Dictionary::writeJosaEomiTrie(), kmaOrange::Dictionary::writeMainTrie(), and kmaOrange::Dictionary::writePreAnalysisTrie().
void WK_DaTrie::insertA (int index, unsigned char * pkey, WK_DaTrie_Node & rNode) [private]
Definition at line 327 of file daTrie.cpp.
References kmaOrange::WK_DaTrie_BaseCheck::Base, kmaOrange::WK_DaTrie_BaseCheck::Check, kmaOrange::CODE, getList(), modify(), mpBc, kmaOrange::WK_DaTrie_Node::mpData, mpTail, kmaOrange::WK_DaTrie_Node::mState, mTailPos, kmaOrange::NUM_CODES, and writeTailAt().
Referenced by insertKey().
void WK_DaTrie::insertB (int index, unsigned char * pkey, WK_DaTrie_Node & rNode) [private]
Definition at line 353 of file daTrie.cpp.
References kmaOrange::WK_DaTrie_BaseCheck::Base, kmaOrange::CODE, mpBc, kmaOrange::WK_DaTrie_Node::mpData, mpTail, kmaOrange::WK_DaTrie_Node::mState, mTailPos, setBase(), setCheck(), TERMINAL, writeTailAt(), and xCheck().
Referenced by insertKey().
int WK_DaTrie::insertKey (const char * pKey, WK_DaTrie_Node & rNode)
Definition at line 498 of file daTrie.cpp.
References appendTerminator(), kmaOrange::WK_DaTrie_BaseCheck::Base, kmaOrange::CODE, compareTail(), insertA(), insertB(), KEY_LEN, mBcPos, mpBc, kmaOrange::WK_DaTrie_Node::mpData, mpTail, kmaOrange::WK_DaTrie_Node::mState, kmaOrange::WK_DaTrie_Node::setRoot(), and TERMINAL.
Referenced by kmaOrange::SynonymContainer::insertSynonym(), kmaOrange::Dictionary::loadPreAnalysis(), kmaOrange::StopWordContainer::loadStopWord(), kmaOrange::Dictionary::readCommonDictionary(), kmaOrange::Dictionary::readDivideInfo(), kmaOrange::Dictionary::readJosaEomiDictionary(), kmaOrange::Dictionary::readPostionInfo(), kmaOrange::AuxVerb::setAVInfo(), kmaOrange::PreFinalEomi::setEPInfo(), and kmaOrange::PredicativeSuffix::setXSDInfo().
bool kmaOrange::WK_DaTrie::isCreated () [inline]
Definition at line 121 of file daTrie.h.
References mpBc.
Referenced by kmaOrange::Dictionary::loadPreAnalysis().
int WK_DaTrie::modify (int currentIndex, int index, unsigned char add, unsigned char * pList, int listsize) [private]
Definition at line 275 of file daTrie.cpp.
References kmaOrange::WK_DaTrie_BaseCheck::Base, kmaOrange::CODE, mpBc, kmaOrange::NUM_CODES, setBase(), setCheck(), and xCheck().
Referenced by insertA().
int kmaOrange::WK_DaTrie::searchKey (const char * pKey, WK_DaTrie_Node & rNode) [inline]
Definition at line 148 of file daTrie.h.
References appendTerminator(), kmaOrange::WK_DaTrie_BaseCheck::Base, kmaOrange::CODE, compareTail(), KEY_LEN, mBcPos, mpBc, kmaOrange::WK_DaTrie_Node::mpData, mpTail, kmaOrange::WK_DaTrie_Node::mState, kmaOrange::WK_DaTrie_Node::setRoot(), and TERMINAL.
void WK_DaTrie::setBase (int index, int value) [private]
base array에 index(s) 노드를 value로 설정한다.
Parameters:
index(s) : 노드 value : 값
Returns: void
Definition at line 84 of file daTrie.cpp.
References kmaOrange::WK_DaTrie_BaseCheck::Base, extendBc(), mBcMax, mBcPos, mpBc, and setEmptyLink().
Referenced by insertB(), modify(), and writeTailAt().
void kmaOrange::WK_DaTrie::setBcEmptyEnd (int bcEmptyEnd) [inline]
Definition at line 273 of file daTrie.h.
References mBcEmptyEnd.
Referenced by kmaOrange::Dictionary::readDivPosTrie(), kmaOrange::Dictionary::readJosaEomiTrie(), kmaOrange::Dictionary::readMainTrie(), and kmaOrange::Dictionary::readPreAnalysisTrie().
void kmaOrange::WK_DaTrie::setBcEmptyStart (int bcEmptyStart) [inline]
Definition at line 268 of file daTrie.h.
References mBcEmptyStart.
Referenced by kmaOrange::Dictionary::readDivPosTrie(), kmaOrange::Dictionary::readJosaEomiTrie(), kmaOrange::Dictionary::readMainTrie(), and kmaOrange::Dictionary::readPreAnalysisTrie().
void kmaOrange::WK_DaTrie::setBcPos (int bcPos) [inline]
Definition at line 254 of file daTrie.h.
References mBcPos.
Referenced by kmaOrange::Dictionary::readDivPosTrie(), kmaOrange::Dictionary::readJosaEomiTrie(), kmaOrange::Dictionary::readMainTrie(), and kmaOrange::Dictionary::readPreAnalysisTrie().
void WK_DaTrie::setCheck (int index, int value) [private]
check array에 index(s) 노드를 value로 설정한다.
Parameters:
index(s) : 노드 value : 값
Returns: void
Definition at line 96 of file daTrie.cpp.
References kmaOrange::WK_DaTrie_BaseCheck::Check, extendBc(), mBcEmptyEnd, mBcEmptyStart, mBcMax, mBcPos, mpBc, and setEmptyLink().
Referenced by insertB(), modify(), and writeTailAt().
void WK_DaTrie::setEmptyLink (int index) [private]
Definition at line 53 of file daTrie.cpp.
References kmaOrange::WK_DaTrie_BaseCheck::Base, kmaOrange::WK_DaTrie_BaseCheck::Check, mBcEmptyEnd, mBcEmptyStart, mBcPos, and mpBc.
Referenced by setBase(), and setCheck().
void kmaOrange::WK_DaTrie::setTailPos (int tailPos) [inline]
Definition at line 263 of file daTrie.h.
References mTailPos.
Referenced by kmaOrange::Dictionary::readDivPosTrie(), kmaOrange::Dictionary::readJosaEomiTrie(), kmaOrange::Dictionary::readMainTrie(), and kmaOrange::Dictionary::readPreAnalysisTrie().
void WK_DaTrie::writeTailAt (int index, unsigned char * pkey, int tailpos) [private]
Definition at line 198 of file daTrie.cpp.
References kmaOrange::WK_DaTrie_BaseCheck::Base, kmaOrange::CODE, extendBc(), extendTail(), mBcMax, mBcPos, mpBc, mpTail, mTailMax, mTailPos, setBase(), setCheck(), and TERMINAL.
Referenced by insertA(), and insertB().
int WK_DaTrie::xCheck (unsigned char * pList) [private]
Definition at line 248 of file daTrie.cpp.
References kmaOrange::WK_DaTrie_BaseCheck::Check, mBcEmptyStart, mBcPos, and mpBc.
Referenced by insertB(), and modify().
Member Data Documentation
int kmaOrange::WK_DaTrie::mBcEmptyEnd [private]
Definition at line 67 of file daTrie.h.
Referenced by create(), getBcEmptyEnd(), setBcEmptyEnd(), setCheck(), setEmptyLink(), and WK_DaTrie().
int kmaOrange::WK_DaTrie::mBcEmptyStart [private]
Definition at line 66 of file daTrie.h.
Referenced by create(), getBcEmptyStart(), setBcEmptyStart(), setCheck(), setEmptyLink(), WK_DaTrie(), and xCheck().
int kmaOrange::WK_DaTrie::mBcExtendSize [private]
Definition at line 64 of file daTrie.h.
Referenced by create(), extendBc(), and WK_DaTrie().
int kmaOrange::WK_DaTrie::mBcMax [private]
Definition at line 63 of file daTrie.h.
Referenced by create(), extendBc(), free(), setBase(), setCheck(), WK_DaTrie(), and writeTailAt().
int kmaOrange::WK_DaTrie::mBcPos [private]
Definition at line 65 of file daTrie.h.
Referenced by create(), findNode(), free(), getBcPos(), insertKey(), searchKey(), setBase(), setBcPos(), setCheck(), setEmptyLink(), WK_DaTrie(), writeTailAt(), and xCheck().
WK_DaTrie_BaseCheck* kmaOrange::WK_DaTrie::mpBc [private]
Definition at line 62 of file daTrie.h.
Referenced by compareTail(), create(), extendBc(), findNode(), free(), getBaseCheckArray(), getList(), insertA(), insertB(), insertKey(), isCreated(), modify(), searchKey(), setBase(), setCheck(), setEmptyLink(), WK_DaTrie(), writeTailAt(), and xCheck().
unsigned char* kmaOrange::WK_DaTrie::mpTail [private]
Definition at line 69 of file daTrie.h.
Referenced by compareTail(), create(), extendTail(), findNode(), free(), getTailBuffer(), insertA(), insertB(), insertKey(), searchKey(), WK_DaTrie(), and writeTailAt().
int kmaOrange::WK_DaTrie::mTailExtendSize [private]
Definition at line 71 of file daTrie.h.
Referenced by create(), extendTail(), and WK_DaTrie().
int kmaOrange::WK_DaTrie::mTailMax [private]
Definition at line 70 of file daTrie.h.
Referenced by create(), extendTail(), free(), WK_DaTrie(), and writeTailAt().
int kmaOrange::WK_DaTrie::mTailPos [private]
Definition at line 72 of file daTrie.h.
Referenced by create(), free(), getTailPos(), insertA(), insertB(), setTailPos(), WK_DaTrie(), and writeTailAt().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/kma/daTrie.h
/disk/workspace-cpp/la-manager/source/kma/daTrie.cpp