ME_Model Class Reference
#include <maxent.h>
Classes
struct hashfun_str
struct ME_Feature
struct ME_FeatureBag
struct MiniStringBag
struct Sample
struct StringBag
Public Member Functions
int train (const std::vector< ME_Sample > &train, const int cutoff=0, const double sigma=0, const double widthfactor=0)
std::vector< double > classify (ME_Sample &s) const
bool load_from_file (const std::string &filename)
bool save_to_file (const std::string &filename) const
int num_classes () const
std::string get_class_label (int i) const
int get_class_id (const std::string &s) const
void get_features (std::list< std::pair< std::pair< std::string, std::string >, double > > &fl)
void set_heldout (const int h, const int n)
bool load_from_array (const ME_Model_Data data[])
ME_Model ()
Private Member Functions
double heldout_likelihood ()
void conditional_probability (const Sample &nbs, std::vector< double > &membp) const
int make_feature_bag (const int cutoff)
int classify (const Sample &nbs, std::vector< double > &membp) const
double update_model_expectation ()
int perform_LMVM ()
int perform_GIS (int C)
Private Attributes
StringBag _label_bag
MiniStringBag _featurename_bag
double _sigma
double _inequality_width
std::vector< double > _vl
std::vector< double > _va
std::vector< double > _vb
ME_FeatureBag _fb
int _num_classes
std::vector< double > _vee
std::vector< double > _vme
std::vector< std::vector< int > > _sample2feature
std::vector< Sample > _train
std::vector< Sample > _heldout
double _train_error
double _heldout_error
int _nheldout
int _early_stopping_n
std::vector< double > _vhlogl
Detailed Description
Definition at line 40 of file maxent.h.
Constructor & Destructor Documentation
ME_Model::ME_Model () [inline]
Definition at line 56 of file maxent.h.
References _early_stopping_n, and _nheldout.
Member Function Documentation
int ME_Model::classify (const Sample & nbs, std::vector< double > & membp) const [private]
vector< double > ME_Model::classify (ME_Sample & s) const
Definition at line 564 of file maxent.cpp.
References _featurename_bag, _num_classes, ME_Sample::features, get_class_label(), ME_Model::ME_Model::MiniStringBag::Id(), ME_Sample::label, and ME_Model::ME_Model::Sample::positive_features.
Referenced by decode_no_context(), heldout_likelihood(), Hypothesis::Update(), and viterbi().
void ME_Model::conditional_probability (const Sample & nbs, std::vector< double > & membp) const [private]
Definition at line 154 of file maxent.cpp.
References _fb, _vl, ME_Model::ME_Model::ME_FeatureBag::Id(), num_classes(), and ME_Model::ME_Model::Sample::positive_features.
int ME_Model::get_class_id (const std::string & s) const [inline]
Definition at line 51 of file maxent.h.
References _label_bag, and ME_Model::ME_Model::MiniStringBag::Id().
Referenced by Hypothesis::Update().
std::string ME_Model::get_class_label (int i) const [inline]
Definition at line 50 of file maxent.h.
References _label_bag, and ME_Model::ME_Model::StringBag::Str().
Referenced by classify(), Hypothesis::Update(), and viterbi().
void ME_Model::get_features (std::list< std::pair< std::pair< std::string, std::string >, double > > & fl)
double ME_Model::heldout_likelihood () [private]
Definition at line 247 of file maxent.cpp.
References _heldout, _heldout_error, _num_classes, and classify().
Referenced by perform_GIS().
bool ME_Model::load_from_array (const ME_Model_Data data[])
Definition at line 502 of file maxent.cpp.
References _fb, _featurename_bag, _label_bag, _num_classes, _vl, ME_Model::ME_Model::ME_FeatureBag::Put(), ME_Model::ME_Model::MiniStringBag::Put(), ME_Model::ME_Model::StringBag::Put(), and ME_Model::ME_Model::StringBag::Size().
bool ME_Model::load_from_file (const std::string & filename)
int ME_Model::make_feature_bag (const int cutoff) [private]
Definition at line 179 of file maxent.cpp.
References _fb, _num_classes, _sample2feature, _train, ME_Model::ME_Model::ME_Feature::body(), ME_Model::ME_Model::ME_FeatureBag::Id(), and ME_Model::ME_Model::ME_FeatureBag::Put().
int ME_Model::num_classes () const [inline]
Definition at line 49 of file maxent.h.
References _num_classes.
Referenced by conditional_probability(), Hypothesis::Update(), and viterbi().
int ME_Model::perform_GIS (int C) [private]
Definition at line 74 of file maxent.cpp.
References _fb, _heldout, _heldout_error, _train_error, _vee, _vl, _vme, heldout_likelihood(), ME_Model::ME_Model::ME_FeatureBag::Size(), and update_model_expectation().
int ME_Model::perform_LMVM () [private]
Definition at line 111 of file maxent.cpp.
References _fb, _inequality_width, _va, _vb, _vl, and ME_Model::ME_Model::ME_FeatureBag::Size().
bool ME_Model::save_to_file (const std::string & filename) const
Referenced by bidir_train().
void ME_Model::set_heldout (const int h, const int n) [inline]
Definition at line 53 of file maxent.h.
References _early_stopping_n, and _nheldout.
int ME_Model::train (const std::vector< ME_Sample > & train, const int cutoff = 0, const double sigma = 0, const double widthfactor = 0)
Referenced by bidir_train().
double ME_Model::update_model_expectation () [private]
Definition at line 263 of file maxent.cpp.
References _fb, _inequality_width, _num_classes, _sample2feature, _sigma, _train, _train_error, _va, _vb, _vl, _vme, ME_Model::ME_Model::ME_FeatureBag::Feature(), ME_Model::ME_Model::ME_Feature::label(), and ME_Model::ME_Model::ME_FeatureBag::Size().
Referenced by perform_GIS().
Member Data Documentation
int ME_Model::_early_stopping_n [private]
Definition at line 211 of file maxent.h.
Referenced by ME_Model(), and set_heldout().
ME_FeatureBag ME_Model::_fb [private]
Definition at line 201 of file maxent.h.
Referenced by conditional_probability(), load_from_array(), make_feature_bag(), perform_GIS(), perform_LMVM(), and update_model_expectation().
MiniStringBag ME_Model::_featurename_bag [private]
Definition at line 195 of file maxent.h.
Referenced by classify(), and load_from_array().
std::vector< Sample > ME_Model::_heldout [private]
Definition at line 207 of file maxent.h.
Referenced by heldout_likelihood(), and perform_GIS().
double ME_Model::_heldout_error [private]
Definition at line 209 of file maxent.h.
Referenced by heldout_likelihood(), and perform_GIS().
double ME_Model::_inequality_width [private]
Definition at line 197 of file maxent.h.
Referenced by perform_LMVM(), and update_model_expectation().
StringBag ME_Model::_label_bag [private]
Definition at line 194 of file maxent.h.
Referenced by get_class_id(), get_class_label(), and load_from_array().
int ME_Model::_nheldout [private]
Definition at line 210 of file maxent.h.
Referenced by ME_Model(), and set_heldout().
int ME_Model::_num_classes [private]
Definition at line 202 of file maxent.h.
Referenced by classify(), heldout_likelihood(), load_from_array(), make_feature_bag(), num_classes(), and update_model_expectation().
std::vector< std::vector< int > > ME_Model::_sample2feature [private]
Definition at line 205 of file maxent.h.
Referenced by make_feature_bag(), and update_model_expectation().
double ME_Model::_sigma [private]
Definition at line 196 of file maxent.h.
Referenced by update_model_expectation().
std::vector< Sample > ME_Model::_train [private]
Definition at line 206 of file maxent.h.
Referenced by make_feature_bag(), and update_model_expectation().
double ME_Model::_train_error [private]
Definition at line 208 of file maxent.h.
Referenced by perform_GIS(), and update_model_expectation().
std::vector<double> ME_Model::_va [private]
Definition at line 199 of file maxent.h.
Referenced by perform_LMVM(), and update_model_expectation().
std::vector<double> ME_Model::_vb [private]
Definition at line 200 of file maxent.h.
Referenced by perform_LMVM(), and update_model_expectation().
std::vector<double> ME_Model::_vee [private]
Definition at line 203 of file maxent.h.
Referenced by perform_GIS().
std::vector<double> ME_Model::_vhlogl [private]
Definition at line 212 of file maxent.h.
std::vector<double> ME_Model::_vl [private]
Definition at line 198 of file maxent.h.
Referenced by conditional_probability(), load_from_array(), perform_GIS(), perform_LMVM(), and update_model_expectation().
std::vector<double> ME_Model::_vme [private]
Definition at line 204 of file maxent.h.
Referenced by perform_GIS(), and update_model_expectation().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/pos/maxent.h
/disk/workspace-cpp/la-manager/source/pos/maxent.cpp