ListEx< T > Class Template Reference
#include <listex.h>
Public Member Functions
ListEx ()
~ListEx ()
void free_ppList ()
void initialize ()
void addTuple (const T &tuple)
void assignTo_ppList ()
int sort (int(*compare)(const void *elem1, const void *elem2), bool flag=true)
Public Attributes
T ** _ppList
size_t _sizeppList
Private Member Functions
void quickSort (T **a, int lo0, int hi0, int(*compare)(const void *elem1, const void *elem2))
void swap (T **ppList, int i, int j)
Detailed Description
template<class T> class ListEx< T >
Definition at line 10 of file listex.h.
Constructor & Destructor Documentation
template<class T> ListEx< T >::ListEx () [inline]
Definition at line 17 of file listex.h.
template<class T> ListEx< T >::~ListEx () [inline]
Definition at line 21 of file listex.h.
Member Function Documentation
template<class T> void ListEx< T >::addTuple (const T & tuple) [inline]
Definition at line 45 of file listex.h.
Referenced by kmaOrange::Tagger::addEojul(), kmaOrange::Dictionary::loadKnowledge(), kmaOrange::Dictionary::readCommonDictionary(), kmaOrange::Dictionary::readJosaEomiDictionary(), kmaOrange::Dictionary::readJosaEomiTrie(), kmaOrange::Dictionary::readMainTrie(), kmaOrange::Tagger::runTagging(), kmaOrange::Dictionary::searchNgetInfoFromMainTrie(), kmaOrange::Dictionary::setOnsetEomi(), kmaOrange::MAnalyzer::tokenizeSentence(), and kmaOrange::MAnalyzer::warmUpAnalysis().
template<class T> void ListEx< T >::assignTo_ppList () [inline]
Definition at line 127 of file listex.h.
Referenced by ListEx< SearchInfo >::sort().
template<class T> void ListEx< T >::free_ppList () [inline]
Definition at line 26 of file listex.h.
Referenced by ListEx< SearchInfo >::assignTo_ppList(), ListEx< SearchInfo >::initialize(), and ListEx< SearchInfo >::~ListEx().
template<class T> void ListEx< T >::initialize () [inline]
Definition at line 39 of file listex.h.
Referenced by kmaOrange::MAnalyzer::commonRunWithStream(), kmaOrange::MAnalyzer::preprocessBeforeAnalysis(), kmaOrange::Tagger::runTagging(), kmaOrange::MAnalyzer::runWithString(), and kmaOrange::Tagger::showResult().
template<class T> void ListEx< T >::quickSort (T ** a, int lo0, int hi0, int(*)(const void *elem1, const void *elem2) compare) [inline, private]
Definition at line 174 of file listex.h.
Referenced by ListEx< SearchInfo >::quickSort(), and ListEx< SearchInfo >::sort().
template<class T> int ListEx< T >::sort (int(*)(const void *elem1, const void *elem2) compare, bool flag = true) [inline]
Definition at line 159 of file listex.h.
template<class T> void ListEx< T >::swap (T ** ppList, int i, int j) [inline, private]
Definition at line 205 of file listex.h.
Referenced by ListEx< SearchInfo >::quickSort().
Member Data Documentation
template<class T> T** ListEx< T >::_ppList
Definition at line 14 of file listex.h.
Referenced by ListEx< SearchInfo >::assignTo_ppList(), ListEx< SearchInfo >::free_ppList(), and ListEx< SearchInfo >::sort().
template<class T> size_t ListEx< T >::_sizeppList
Definition at line 15 of file listex.h.
Referenced by ListEx< SearchInfo >::assignTo_ppList(), and ListEx< SearchInfo >::free_ppList().
The documentation for this class was generated from the following file:
/disk/workspace-cpp/la-manager/include/kma/listex.h