kmaOrange::Tagger Class Reference
#include <tagger.h>
Public Member Functions
Tagger ()
~Tagger ()
void setSentence (Sentence *pSentence)
void setStream (StrStream *pStrStream)
void runTagging ()
void showResult ()
Sentence & getTaggedResult ()
Private Member Functions
void addEojul (int nPos)
Private Attributes
Eojul _eojul
Eojul _rtEojul
Sentence * _psentence
StrStream * _stream
Sentence _resultS
int _rCnt
int _flag
Detailed Description
Definition at line 22 of file tagger.h.
Constructor & Destructor Documentation
kmaOrange::Tagger::Tagger () [inline]
Definition at line 25 of file tagger.h.
kmaOrange::Tagger::~Tagger () [inline]
Definition at line 26 of file tagger.h.
Member Function Documentation
void Tagger::addEojul (int nPos) [private]
Definition at line 252 of file tagger.cpp.
References _eojul, _flag, _rCnt, _resultS, _rtEojul, ListEx< T >::addTuple(), kmaOrange::Eojul::close(), Sentence::eojulList, kmaOrange::Eojul::getCount(), kmaOrange::Eojul::getLexicon(), kmaOrange::Eojul::getPOS(), kmaOrange::Eojul::getScore(), kmaOrange::Eojul::increaseAnalysisResults(), kmaOrange::Eojul::setMorphAndTag(), and kmaOrange::Eojul::setScore().
Referenced by runTagging().
Sentence& kmaOrange::Tagger::getTaggedResult () [inline]
Definition at line 43 of file tagger.h.
References _resultS.
Referenced by kmaOrange::MAnalyzer::tagging().
void Tagger::runTagging ()
Definition at line 13 of file tagger.cpp.
References _eojul, _flag, _psentence, _rCnt, _resultS, _rtEojul, addEojul(), ListEx< T >::addTuple(), EM, Sentence::eojulList, ETM, FL, kmaOrange::Eojul::getCount(), kmaOrange::Eojul::getEojulInfo(), kmaOrange::Eojul::getLexicon(), kmaOrange::Eojul::getListSize(), kmaOrange::Eojul::getOffset(), kmaOrange::Eojul::getOneBestIndex(), kmaOrange::Eojul::getPOS(), kmaOrange::Eojul::getString(), kmaOrange::Eojul::initialize(), ListEx< T >::initialize(), J_, MA, MM, N_, NNB, NNG, NP, SC, kmaOrange::Eojul::setEojulAndInfo(), kmaOrange::Eojul::setOffset(), SN, V_, VV, and VX.
Referenced by kmaOrange::MAnalyzer::tagging().
void kmaOrange::Tagger::setSentence (Sentence * pSentence) [inline]
Definition at line 39 of file tagger.h.
References _psentence.
Referenced by kmaOrange::MAnalyzer::tagging().
void kmaOrange::Tagger::setStream (StrStream * pStrStream) [inline]
Definition at line 40 of file tagger.h.
References _stream.
Referenced by kmaOrange::MAnalyzer::setDefault().
void Tagger::showResult ()
Definition at line 270 of file tagger.cpp.
References _resultS, _stream, Sentence::eojulList, kmaOrange::StrStream::getOutStream(), ListEx< T >::initialize(), and kmaOrange::StrStream::writeLine().
Referenced by kmaOrange::MAnalyzer::tagging().
Member Data Documentation
Eojul kmaOrange::Tagger::_eojul [private]
Definition at line 26 of file tagger.h.
Referenced by addEojul(), and runTagging().
int kmaOrange::Tagger::_flag [private]
Definition at line 34 of file tagger.h.
Referenced by addEojul(), and runTagging().
Sentence* kmaOrange::Tagger::_psentence [private]
Definition at line 30 of file tagger.h.
Referenced by runTagging(), and setSentence().
int kmaOrange::Tagger::_rCnt [private]
Definition at line 33 of file tagger.h.
Referenced by addEojul(), and runTagging().
Sentence kmaOrange::Tagger::_resultS [private]
Definition at line 32 of file tagger.h.
Referenced by addEojul(), getTaggedResult(), runTagging(), and showResult().
Eojul kmaOrange::Tagger::_rtEojul [private]
Definition at line 26 of file tagger.h.
Referenced by addEojul(), and runTagging().
StrStream* kmaOrange::Tagger::_stream [private]
Definition at line 31 of file tagger.h.
Referenced by setStream(), and showResult().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/kma/tagger.h
/disk/workspace-cpp/la-manager/source/kma/tagger.cpp