la_manager::stem::Stemmer Class Reference
stem a word
#include <Stemmer.h>
Public Types
enum Language {
STEM_LANG_UNKNOWN = 0,
STEM_LANG_DANISH = 1,
STEM_LANG_DUTCH = 2,
STEM_LANG_ENGLISH,
STEM_LANG_FINNISH,
STEM_LANG_FRENCH,
STEM_LANG_GERMAN,
STEM_LANG_HUNGARIAN,
STEM_LANG_ITALIAN,
STEM_LANG_NORWEGIAN,
STEM_LANG_PORTUGUESE,
STEM_LANG_ROMANIAN,
STEM_LANG_RUSSIAN,
STEM_LANG_SPANISH,
STEM_LANG_SWEDISH,
STEM_LANG_TURKISH,
STEM_LANG_EOS
 }
Public Member Functions
Stemmer ()
virtual ~Stemmer ()
bool init (int language)
void deinit (void)
bool stem (const string &term, string &resultWord)
Private Attributes
int stemLang_
language for stemming
void * stemFunction_
stemming function
Detailed Description
stem a word
Definition at line 19 of file Stemmer.h.
Member Enumeration Documentation
enum la_manager::stem::Stemmer::Language
Enumerator:
STEM_LANG_UNKNOWN
STEM_LANG_DANISH
STEM_LANG_DUTCH
STEM_LANG_ENGLISH
STEM_LANG_FINNISH
STEM_LANG_FRENCH
STEM_LANG_GERMAN
STEM_LANG_HUNGARIAN
STEM_LANG_ITALIAN
STEM_LANG_NORWEGIAN
STEM_LANG_PORTUGUESE
STEM_LANG_ROMANIAN
STEM_LANG_RUSSIAN
STEM_LANG_SPANISH
STEM_LANG_SWEDISH
STEM_LANG_TURKISH
STEM_LANG_EOS
Definition at line 23 of file Stemmer.h.
Constructor & Destructor Documentation
la_manager::stem::Stemmer::Stemmer ()
constructor.
Definition at line 64 of file Stemmer.cpp.
References STEM_LANG_UNKNOWN, stemFunction_, and stemLang_.
la_manager::stem::Stemmer::~Stemmer () [virtual]
destructor.
Definition at line 70 of file Stemmer.cpp.
References deinit().
Member Function Documentation
void la_manager::stem::Stemmer::deinit (void)
delete stemming function
Parameters:
void
Returns: void
Definition at line 110 of file Stemmer.cpp.
References stemFunction_.
Referenced by init(), la_manager::StemAnalyzer::~StemAnalyzer(), and ~Stemmer().
bool la_manager::stem::Stemmer::init (int language)
Initialize supported language.
Parameters:
language stemming language, value is one of StemLanguage enumeration
Returns: if success true, else false.
Definition at line 75 of file Stemmer.cpp.
References la_manager::stem::StemFunc::close, la_manager::stem::StemFunc::create, deinit(), la_manager::stem::StemFunc::env, la_manager::stem::StemFunc::stem, la_manager::stem::STEM_FUNCTION, STEM_LANG_EOS, and stemFunction_.
Referenced by la_manager::StemAnalyzer::StemAnalyzer().
bool la_manager::stem::Stemmer::stem (const string & term, string & resultWord)
perform stemming
Parameters:
term word for stemming
resultWord the result word after stemming
if success true, else false.
Definition at line 120 of file Stemmer.cpp.
References SN_set_current(), and stemFunction_.
Referenced by la_manager::StemAnalyzer::analyze().
Member Data Documentation
void* la_manager::stem::Stemmer::stemFunction_ [private]
stemming function
Definition at line 78 of file Stemmer.h.
Referenced by deinit(), init(), stem(), and Stemmer().
int la_manager::stem::Stemmer::stemLang_ [private]
language for stemming
Definition at line 76 of file Stemmer.h.
Referenced by Stemmer().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/stem/Stemmer.h
/disk/workspace-cpp/la-manager/source/stem/Stemmer.cpp