la_manager::StemAnalyzer Class Reference
interface of StemAnalyzer This class extracts terms with stemming method
#include <StemAnalyzer.h>
Public Member Functions
StemAnalyzer (int lang, UString::EncodingType etype=UString::UTF_8)
~StemAnalyzer ()
bool analyze (const TermList &, TermList &)
analyze interface
bool analyze (TermList &)
analyze interface
Protected Attributes
Stemmer stemmer_
a stemmer provided by `libstemmer`
UString::EncodingType encodingType_
encoding type
int language_
language type
Private Attributes
MLRUCacheString cache_
Detailed Description
interface of StemAnalyzer This class extracts terms with stemming method
Definition at line 27 of file StemAnalyzer.h.
Constructor & Destructor Documentation
la_manager::StemAnalyzer::StemAnalyzer (int lang, UString::EncodingType etype = UString::UTF_8) [inline]
Definition at line 36 of file StemAnalyzer.h.
References la_manager::stem::Stemmer::init(), language_, and stemmer_.
la_manager::StemAnalyzer::~StemAnalyzer () [inline]
Definition at line 46 of file StemAnalyzer.h.
References la_manager::stem::Stemmer::deinit(), and stemmer_.
Member Function Documentation
bool la_manager::StemAnalyzer::analyze (TermList & InOutPut) [virtual]
analyze interface
Parameters:
InOutPut input (also output) term list This class analyze input terms and generate the output
Implements la_manager::Analyzer.
Definition at line 37 of file StemAnalyzer.cpp.
References cache_, encodingType_, la_manager::stem::Stemmer::stem(), and stemmer_.
bool la_manager::StemAnalyzer::analyze (const TermList & Input, TermList & Output) [virtual]
analyze interface
Parameters:
Input input term list
output output term list This class analyze input terms and generate the output
Implements la_manager::Analyzer.
Definition at line 15 of file StemAnalyzer.cpp.
References cache_, encodingType_, la_manager::stem::Stemmer::stem(), stemmer_, and la_manager::Term::text.
Member Data Documentation
MLRUCacheString la_manager::StemAnalyzer::cache_ [private]
Definition at line 29 of file StemAnalyzer.h.
Referenced by analyze().
UString::EncodingType la_manager::StemAnalyzer::encodingType_ [protected]
encoding type
Definition at line 32 of file StemAnalyzer.h.
Referenced by analyze().
int la_manager::StemAnalyzer::language_ [protected]
language type
Definition at line 33 of file StemAnalyzer.h.
Referenced by StemAnalyzer().
Stemmer la_manager::StemAnalyzer::stemmer_ [protected]
a stemmer provided by `libstemmer`
Definition at line 31 of file StemAnalyzer.h.
Referenced by analyze(), StemAnalyzer(), and ~StemAnalyzer().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/StemAnalyzer.h
/disk/workspace-cpp/la-manager/source/StemAnalyzer.cpp