la_manager::EnglishNounFilter Class Reference
todo
#include <NounFilter.h>
Public Member Functions
EnglishNounFilter (string modelPath=`../resource/enpos_models`)
~EnglishNounFilter ()
bool analyze (const TermList &Input, TermList &Output)
analyze interface
bool analyze (TermList &InOutPut)
analyze interface
Private Attributes
POSTaggerEnglish tagger_
Detailed Description
todo
Definition at line 26 of file NounFilter.h.
Constructor & Destructor Documentation
la_manager::EnglishNounFilter::EnglishNounFilter (string modelPath = `../resource/enpos_models`) [inline]
Definition at line 29 of file NounFilter.h.
la_manager::EnglishNounFilter::~EnglishNounFilter () [inline]
Definition at line 30 of file NounFilter.h.
Member Function Documentation
bool la_manager::EnglishNounFilter::analyze (TermList & InOutPut) [virtual]
analyze interface
Parameters:
InOutPut input (also output) term list This class analyze input terms and generate the output
Implements la_manager::Analyzer.
Definition at line 29 of file NounFilter.cpp.
References la_manager::POSTaggerEnglish::tag(), and tagger_.
bool la_manager::EnglishNounFilter::analyze (const TermList & Input, TermList & Output) [virtual]
analyze interface
Parameters:
Input input term list
output output term list This class analyze input terms and generate the output
Implements la_manager::Analyzer.
Definition at line 12 of file NounFilter.cpp.
References la_manager::POSTaggerEnglish::tag(), and tagger_.
Referenced by main().
Member Data Documentation
POSTaggerEnglish la_manager::EnglishNounFilter::tagger_ [private]
Definition at line 27 of file NounFilter.h.
Referenced by analyze().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/NounFilter.h
/disk/workspace-cpp/la-manager/source/NounFilter.cpp