WK_Knowledge Class Reference
a class for KMA system dictionary.
#include <wk_knowledge.h>
Public Member Functions
virtual ~WK_Knowledge ()
virtual int loadKnowledge (const char *pPath, bool hasKnowlege=true)=0
This function loads contents of the system dictionaries and the statistical data into a WK_Knowledge object.
virtual int loadUserNoun (const char *pPath=`/disk/workspace-cpp/kma/resource/dic`, const char *pName=`user.dic`, bool isOverWriting=true)=0
This function loads contents of the user-noun dictionary file into a WK_Knowledge object.
virtual int loadPreAnalysis (const char *pPath=`/disk/workspace-cpp/kma/resource/dic`, const char *pName=`preanal.dic`, bool isOverWriting=true)=0
This function loads contents of the pre-analysis dictionary file into a WK_Knowledge object.
virtual int makeKnowledge (const char *pSrcPath, const char *pTgtPath)=0
This function makes the binary system dictionary file.
Static Public Member Functions
static WK_Knowledge * createObject (bool willLoadByDefaultPath=false)
This function creates a WK_Knowledge object.
Detailed Description
a class for KMA system dictionary.
Date: 2008-11-04
Author: HeeGeun Park
Definition at line 15 of file wk_knowledge.h.
Constructor & Destructor Documentation
WK_Knowledge::~WK_Knowledge () [virtual]
Definition at line 13 of file wk_knowledge.cpp.
Member Function Documentation
WK_Knowledge * WK_Knowledge::createObject (bool willLoadByDefaultPath = false) [static]
This function creates a WK_Knowledge object.
Date: 2008-11-04
Author: HeeGeun Park
Parameters:
willLoadByDefaultPath a boolean.
 true - it loads the knowledge using the default path.
 false - it loads the knowledge using the loadKnowledge() method.
Returns: a pointer of WK_Knowledge object.
Definition at line 17 of file wk_knowledge.cpp.
Referenced by la_manager::KoreanNounFilter::KoreanNounFilter().
virtual int WK_Knowledge::loadKnowledge (const char * pPath, bool hasKnowlege = true) [pure virtual]
This function loads contents of the system dictionaries and the statistical data into a WK_Knowledge object.
Date: 2008-11-04
Author: HeeGeun Park
Parameters:
pPath a pointer of a constant charater - the path of the directory, which the system dictionaries and the statistical data files are stored.
hasKnowlege a boolean - It loads the system dictionary using the `wko.klg` file, which is a binary system dictionary file, whether or not.
Returns: an integer.
 0 - fail.
 1 - success.
Implemented in kmaOrange::Dictionary.
Referenced by la_manager::KoreanNounFilter::KoreanNounFilter().
virtual int WK_Knowledge::loadPreAnalysis (const char * pPath = `/disk/workspace-cpp/kma/resource/dic`, const char * pName = `preanal.dic`, bool isOverWriting = true) [pure virtual]
This function loads contents of the pre-analysis dictionary file into a WK_Knowledge object.
Date: 2008-11-04
Author: HeeGeun Park
Parameters:
pPath a pointer of a constant charater - the path of the directory, which the pre-analysis dictionary file is stored.
pName a pointer of a constant charater - the name of the pre-analysis dictionary file.
isOverWriting a boolean - It overwrites a word in the pre-analysys dictionary, which is a same word in the system dictionary, whether or not.
Returns: an integer.
 0 - fail.
 1 - success.
Implemented in kmaOrange::Dictionary.
Referenced by la_manager::KoreanNounFilter::KoreanNounFilter().
virtual int WK_Knowledge::loadUserNoun (const char * pPath = `/disk/workspace-cpp/kma/resource/dic`, const char * pName = `user.dic`, bool isOverWriting = true) [pure virtual]
This function loads contents of the user-noun dictionary file into a WK_Knowledge object.
Date: 2008-11-04
Author: HeeGeun Park
Parameters:
pPath a pointer of a constant charater - the path of the directory, which the user-noun dictionary file is stored.
pName a pointer of a constant charater - the name of the user-noun dictionary file.
isOverWriting a boolean - It overwrites a word in the user-noun dictioanry, which is a same word in the system dictionary, whether or not.
Returns: an integer.
 0 - fail.
 1 - success.
Implemented in kmaOrange::Dictionary.
Referenced by la_manager::KoreanNounFilter::KoreanNounFilter().
virtual int WK_Knowledge::makeKnowledge (const char * pSrcPath, const char * pTgtPath) [pure virtual]
This function makes the binary system dictionary file.
Date: 2009-01-07
Author: HeeGeun Park
Parameters:
pSrcPath a pointer of a constant charater - the path of the source files.
pTgtPath a pointer of a constant charater - the path of the target file.
Returns: an integer.
 0 - fail.
 1 - success.
Implemented in kmaOrange::Dictionary.
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/kma/wk_knowledge.h
/disk/workspace-cpp/la-manager/source/kma/wk_knowledge.cpp