kmaOrange::TagSet Class Reference
#include <TagSet.h>
Public Member Functions
TagSet ()
~TagSet ()
Static Public Member Functions
static unsigned int convertTagStringToCode (char *tag)
static char * convertCodeToTagString (unsigned int code)
static char getIndexTagString (char *tag)
Static Public Attributes
static TAGSET stringOrderTags []
static TAGSET largeGroupTags []
static TAGSET smallAGroupTags []
static TAGSET smallBGroupTags []
static unsigned int nStringOrderTags = sizeof(stringOrderTags) / sizeof(TAGSET)
static unsigned int nLargeGroupTags = sizeof(largeGroupTags) / sizeof(TAGSET)
static unsigned int nSmallAGroupTags = sizeof(smallAGroupTags) / sizeof(TAGSET)
static unsigned int nSmallBGroupTags = sizeof(smallBGroupTags) / sizeof(TAGSET)
Detailed Description
Definition at line 14 of file TagSet.h.
Constructor & Destructor Documentation
TagSet::TagSet ()
Definition at line 65 of file TagSet.cpp.
TagSet::~TagSet ()
Definition at line 69 of file TagSet.cpp.
Member Function Documentation
char * TagSet::convertCodeToTagString (unsigned int code) [static]
Definition at line 73 of file TagSet.cpp.
References HASHING_DIV_VALUE, largeGroupTags, smallAGroupTags, smallBGroupTags, and kmaOrange::tagcode::tag.
Referenced by kmaOrange::Eojul::getStrPOS().
unsigned int TagSet::convertTagStringToCode (char * tag) [static]
Definition at line 97 of file TagSet.cpp.
References kmaOrange::tagcode::code, nStringOrderTags, and stringOrderTags.
Referenced by kmaOrange::Dictionary::readCommonDictionary(), and kmaOrange::Dictionary::readJosaEomiDictionary().
char TagSet::getIndexTagString (char * tag) [static]
Definition at line 124 of file TagSet.cpp.
References nStringOrderTags, and stringOrderTags.
Referenced by kmaOrange::Dictionary::loadPreAnalysis().
Member Data Documentation
TAGSET TagSet::largeGroupTags [static]
Initial value:
 {
        { "UW", UW },   { "SC", SC },   { "SN", SN },   { "-1", 0 },    { "FL", FL },
        { "-1", 0 },    { "MM", MM },   { "-1", 0 },    { "XSN", XSN }, { "-1", 0 },
        { "-1", 0 },    { "-1", 0 },    { "MA", MA },   { "-1", 0 },    { "E_", E_ },
        { "-1", 0 },    { "XP", XP },   { "-1", 0 },    { "-1", 0 },    { "-1", 0 },
        { "-1", 0 },    { "-1", 0 },    { "-1", 0 },    { "-1", 0 },    { "IC", IC },
        { "-1", 0 },    { "-1", 0 },    { "-1", 0 },    { "J_", J_ },   { "-1", 0 },
        { "-1", 0 },    { "-1", 0 },    { "XSD", XSD }, { "-1", 0 },    { "N_", N_ },
        { "-1", 0 },    { "-1", 0 },    { "-1", 0 },    { "-1", 0 },    { "-1", 0 },
        { "-1", 0 },    { "-1", 0 },    { "V_", V_ },   { "-1", 0 },    { "-1", 0 },
        { "-1", 0 },    { "VX", VX },   { "-1", 0 },    { "VC", VC },   { "-1", 0 }
}
Definition at line 19 of file TagSet.h.
Referenced by convertCodeToTagString().
unsigned int TagSet::nLargeGroupTags = sizeof(largeGroupTags) / sizeof(TAGSET) [static]
Definition at line 24 of file TagSet.h.
unsigned int TagSet::nSmallAGroupTags = sizeof(smallAGroupTags) / sizeof(TAGSET) [static]
Definition at line 25 of file TagSet.h.
unsigned int TagSet::nSmallBGroupTags = sizeof(smallBGroupTags) / sizeof(TAGSET) [static]
Definition at line 26 of file TagSet.h.
unsigned int TagSet::nStringOrderTags = sizeof(stringOrderTags) / sizeof(TAGSET) [static]
Definition at line 23 of file TagSet.h.
Referenced by convertTagStringToCode(), and getIndexTagString().
TAGSET TagSet::smallAGroupTags [static]
Initial value:
 {
        { "-1", 0 },    { "NNG", NNG }, { "NNB", NNB }, { "-1", 0 },    { "NNP", NNP },
        { "-1", 0 },    { "VA", VA },   { "-1", 0 },    { "NNU", NNU }, { "-1", 0 },
        { "-1", 0 },    { "-1", 0 },    { "EM", EC },   { "-1", 0 },    { "NU", NU },
        { "-1", 0 },    { "NNR", NNR }, { "-1", 0 },    { "MA", MAJ },  { "-1", 0 },
        { "-1", 0 },    { "-1", 0 },    { "-1", 0 },    { "-1", 0 },    { "EM", EF },
        { "-1", 0 },    { "-1", 0 },    { "-1", 0 },    { "VV", VV },   { "-1", 0 },
        { "-1", 0 },    { "-1", 0 },    { "NP", NP },   { "-1", 0 },    { "MA", MAG },
        { "-1", 0 },    { "EM", EM },   { "-1", 0 },    { "-1", 0 },    { "-1", 0 },
        { "-1", 0 },    { "-1", 0 },    { "EP", EP },   { "-1", 0 },    { "-1", 0 },
        { "-1", 0 },    { "ETN", ETN }, { "-1", 0 },    { "ETM", ETM }, { "-1", 0 }
}
Definition at line 20 of file TagSet.h.
Referenced by convertCodeToTagString().
TAGSET TagSet::smallBGroupTags [static]
Initial value:
 {
        { "-1", 0 },    { "J_", JK },   { "J_", JKG },  { "-1", 0 },    { "J_", JX },
        { "-1", 0 },    { "XSD", XSV }, { "-1", 0 },    { "J_", JC },   { "-1", 0 },
        { "-1", 0 },    { "-1", 0 },    { "XSD", XSA }, { "-1", 0 },    { "-1", 0 },
        { "-1", 0 },    { "-1", 0 },    { "-1", 0 },    { "-1", 0 },    { "-1", 0 },
        { "-1", 0 },    { "-1", 0 },    { "-1", 0 },    { "-1", 0 },    { "NNI", NNI },
        { "-1", 0 },    { "-1", 0 },    { "-1", 0 },    { "-1", 0 },    { "-1", 0 },
        { "-1", 0 },    { "-1", 0 },    { "-1", 0 },    { "-1", 0 },    { "-1", 0 },
        { "-1", 0 },    { "-1", 0 },    { "-1", 0 },    { "-1", 0 },    { "-1", 0 },
        { "-1", 0 },    { "-1", 0 },    { "-1", 0 },    { "-1", 0 },    { "-1", 0 },
        { "-1", 0 },    { "NNF", NNF }, { "-1", 0 },    { "NNC", NNC }, { "-1", 0 }
}
Definition at line 21 of file TagSet.h.
Referenced by convertCodeToTagString().
TAGSET TagSet::stringOrderTags [static]
Initial value:
 {
        { "EC", EM },   { "EF", EM },   { "EM", EM },   { "EP", EP },   { "ETM", ETM },
        { "ETN", ETN }, { "E_", E_ },   { "FL", FL },   { "IC", IC },   { "JC", J_ },
        { "JK", J_ },   { "JKG", J_ },  { "JX", JX },   { "J_", J_ },   { "MA", MA },
        { "MAG", MA },  { "MAJ", MA },  { "MM", MM },   { "NNB", NNB }, { "NNC", NNC },
        { "NNF", NNF }, { "NNG", NNG }, { "NNI", NNI }, { "NNP", NNP }, { "NNR", NNR },
        { "NNU", NNU }, { "NP", NP },   { "NU", NU },   { "N_", N_ },   { "SC", SC },
        { "SN", SN },   { "UW", UW },   { "VA", VA },   { "VC", VC },   { "VV", VV },
        { "VX", VX },   { "V_", V_ },   { "XP", XP },   { "XSA", XSD }, { "XSD", XSD },
        { "XSN", XSN }, { "XSV", XSD }
}
Definition at line 17 of file TagSet.h.
Referenced by kmaOrange::MAnalyzer::analyzeEojul(), convertTagStringToCode(), and getIndexTagString().
The documentation for this class was generated from the following files:
/disk/workspace-cpp/la-manager/include/kma/TagSet.h
/disk/workspace-cpp/la-manager/source/kma/TagSet.cpp