/disk/workspace-cpp/la-manager/source/pos/postag.cpp File Reference
#include <stdio.h>
#include <fstream>
#include <map>
#include <list>
#include <iostream>
#include <sstream>
#include <cmath>
#include <set>
#include <pos/maxent.h>
#include <pos/common.h>
#include <pos/bidir.h>
Functions
string normalize (const string &s)
void viterbi (vector< Token > &vt, const ME_Model &me)
string postag (const string &s, const ME_Model &me)
Variables
const double BEAM_WIDTH = 3.0
Function Documentation
string normalize (const string & s)
Definition at line 22 of file postag.cpp.
Referenced by mesample().
string postag (const string & s, const ME_Model & me)
Definition at line 102 of file postag.cpp.
References tokenize(), and viterbi().
void viterbi (vector< Token > & vt, const ME_Model & me)
Definition at line 32 of file postag.cpp.
References BEAM_WIDTH, ME_Model::classify(), ME_Model::get_class_label(), mesample(), and ME_Model::num_classes().
Referenced by postag().
Variable Documentation
const double BEAM_WIDTH = 3.0
Definition at line 18 of file postag.cpp.
Referenced by viterbi().