/disk/workspace-cpp/la-manager/include/stem/stem_UTF_8_german.h File Reference
Functions
struct SN_env * german_UTF_8_create_env (void)
void german_UTF_8_close_env (struct SN_env *z)
int german_UTF_8_stem (struct SN_env *z)
Function Documentation
void german_UTF_8_close_env (struct SN_env * z)
Definition at line 509 of file stem_UTF_8_german.cpp.
References SN_close_env().
struct SN_env * german_UTF_8_create_env (void) [read]
Definition at line 507 of file stem_UTF_8_german.cpp.
References SN_create_env().
int german_UTF_8_stem (struct SN_env * z)
Definition at line 468 of file stem_UTF_8_german.cpp.
References SN_env::c, SN_env::l, SN_env::lb, r_mark_regions(), r_postlude(), r_prelude(), and r_standard_suffix().