/disk/workspace-cpp/la-manager/source/stem/stem_UTF_8_romanian.cpp File Reference
#include <stem/header.h>
Functions
int romanian_UTF_8_stem (struct SN_env *z)
static int r_vowel_suffix (struct SN_env *z)
static int r_verb_suffix (struct SN_env *z)
static int r_combo_suffix (struct SN_env *z)
static int r_standard_suffix (struct SN_env *z)
static int r_step_0 (struct SN_env *z)
static int r_R2 (struct SN_env *z)
static int r_R1 (struct SN_env *z)
static int r_RV (struct SN_env *z)
static int r_mark_regions (struct SN_env *z)
static int r_postlude (struct SN_env *z)
static int r_prelude (struct SN_env *z)
struct SN_env * romanian_UTF_8_create_env (void)
void romanian_UTF_8_close_env (struct SN_env *z)
Variables
static const symbol s_0_1 [1] = { 'I' }
static const symbol s_0_2 [1] = { 'U' }
static struct among a_0 [3]
static const symbol s_1_0 [2] = { 'e', 'a' }
static const symbol s_1_1 [5] = { 'a', 0xC5, 0xA3, 'i', 'a' }
static const symbol s_1_2 [3] = { 'a', 'u', 'a' }
static const symbol s_1_3 [3] = { 'i', 'u', 'a' }
static const symbol s_1_4 [5] = { 'a', 0xC5, 0xA3, 'i', 'e' }
static const symbol s_1_5 [3] = { 'e', 'l', 'e' }
static const symbol s_1_6 [3] = { 'i', 'l', 'e' }
static const symbol s_1_7 [4] = { 'i', 'i', 'l', 'e' }
static const symbol s_1_8 [3] = { 'i', 'e', 'i' }
static const symbol s_1_9 [4] = { 'a', 't', 'e', 'i' }
static const symbol s_1_10 [2] = { 'i', 'i' }
static const symbol s_1_11 [4] = { 'u', 'l', 'u', 'i' }
static const symbol s_1_12 [2] = { 'u', 'l' }
static const symbol s_1_13 [4] = { 'e', 'l', 'o', 'r' }
static const symbol s_1_14 [4] = { 'i', 'l', 'o', 'r' }
static const symbol s_1_15 [5] = { 'i', 'i', 'l', 'o', 'r' }
static struct among a_1 [16]
static const symbol s_2_0 [5] = { 'i', 'c', 'a', 'l', 'a' }
static const symbol s_2_1 [5] = { 'i', 'c', 'i', 'v', 'a' }
static const symbol s_2_2 [5] = { 'a', 't', 'i', 'v', 'a' }
static const symbol s_2_3 [5] = { 'i', 't', 'i', 'v', 'a' }
static const symbol s_2_4 [5] = { 'i', 'c', 'a', 'l', 'e' }
static const symbol s_2_5 [7] = { 'a', 0xC5, 0xA3, 'i', 'u', 'n', 'e' }
static const symbol s_2_6 [7] = { 'i', 0xC5, 0xA3, 'i', 'u', 'n', 'e' }
static const symbol s_2_7 [6] = { 'a', 't', 'o', 'a', 'r', 'e' }
static const symbol s_2_8 [6] = { 'i', 't', 'o', 'a', 'r', 'e' }
static const symbol s_2_9 [7] = { 0xC4, 0x83, 't', 'o', 'a', 'r', 'e' }
static const symbol s_2_10 [7] = { 'i', 'c', 'i', 't', 'a', 't', 'e' }
static const symbol s_2_11 [9] = { 'a', 'b', 'i', 'l', 'i', 't', 'a', 't', 'e' }
static const symbol s_2_12 [9] = { 'i', 'b', 'i', 'l', 'i', 't', 'a', 't', 'e' }
static const symbol s_2_13 [7] = { 'i', 'v', 'i', 't', 'a', 't', 'e' }
static const symbol s_2_14 [5] = { 'i', 'c', 'i', 'v', 'e' }
static const symbol s_2_15 [5] = { 'a', 't', 'i', 'v', 'e' }
static const symbol s_2_16 [5] = { 'i', 't', 'i', 'v', 'e' }
static const symbol s_2_17 [5] = { 'i', 'c', 'a', 'l', 'i' }
static const symbol s_2_18 [5] = { 'a', 't', 'o', 'r', 'i' }
static const symbol s_2_19 [7] = { 'i', 'c', 'a', 't', 'o', 'r', 'i' }
static const symbol s_2_20 [5] = { 'i', 't', 'o', 'r', 'i' }
static const symbol s_2_21 [6] = { 0xC4, 0x83, 't', 'o', 'r', 'i' }
static const symbol s_2_22 [7] = { 'i', 'c', 'i', 't', 'a', 't', 'i' }
static const symbol s_2_23 [9] = { 'a', 'b', 'i', 'l', 'i', 't', 'a', 't', 'i' }
static const symbol s_2_24 [7] = { 'i', 'v', 'i', 't', 'a', 't', 'i' }
static const symbol s_2_25 [5] = { 'i', 'c', 'i', 'v', 'i' }
static const symbol s_2_26 [5] = { 'a', 't', 'i', 'v', 'i' }
static const symbol s_2_27 [5] = { 'i', 't', 'i', 'v', 'i' }
static const symbol s_2_28 [7] = { 'i', 'c', 'i', 't', 0xC4, 0x83, 'i' }
static const symbol s_2_29 [9] = { 'a', 'b', 'i', 'l', 'i', 't', 0xC4, 0x83, 'i' }
static const symbol s_2_30 [7] = { 'i', 'v', 'i', 't', 0xC4, 0x83, 'i' }
static const symbol s_2_31 [9] = { 'i', 'c', 'i', 't', 0xC4, 0x83, 0xC5, 0xA3, 'i' }
static const symbol s_2_32 [11] = { 'a', 'b', 'i', 'l', 'i', 't', 0xC4, 0x83, 0xC5, 0xA3, 'i' }
static const symbol s_2_33 [9] = { 'i', 'v', 'i', 't', 0xC4, 0x83, 0xC5, 0xA3, 'i' }
static const symbol s_2_34 [4] = { 'i', 'c', 'a', 'l' }
static const symbol s_2_35 [4] = { 'a', 't', 'o', 'r' }
static const symbol s_2_36 [6] = { 'i', 'c', 'a', 't', 'o', 'r' }
static const symbol s_2_37 [4] = { 'i', 't', 'o', 'r' }
static const symbol s_2_38 [5] = { 0xC4, 0x83, 't', 'o', 'r' }
static const symbol s_2_39 [4] = { 'i', 'c', 'i', 'v' }
static const symbol s_2_40 [4] = { 'a', 't', 'i', 'v' }
static const symbol s_2_41 [4] = { 'i', 't', 'i', 'v' }
static const symbol s_2_42 [6] = { 'i', 'c', 'a', 'l', 0xC4, 0x83 }
static const symbol s_2_43 [6] = { 'i', 'c', 'i', 'v', 0xC4, 0x83 }
static const symbol s_2_44 [6] = { 'a', 't', 'i', 'v', 0xC4, 0x83 }
static const symbol s_2_45 [6] = { 'i', 't', 'i', 'v', 0xC4, 0x83 }
static struct among a_2 [46]
static const symbol s_3_0 [3] = { 'i', 'c', 'a' }
static const symbol s_3_1 [5] = { 'a', 'b', 'i', 'l', 'a' }
static const symbol s_3_2 [5] = { 'i', 'b', 'i', 'l', 'a' }
static const symbol s_3_3 [4] = { 'o', 'a', 's', 'a' }
static const symbol s_3_4 [3] = { 'a', 't', 'a' }
static const symbol s_3_5 [3] = { 'i', 't', 'a' }
static const symbol s_3_6 [4] = { 'a', 'n', 't', 'a' }
static const symbol s_3_7 [4] = { 'i', 's', 't', 'a' }
static const symbol s_3_8 [3] = { 'u', 't', 'a' }
static const symbol s_3_9 [3] = { 'i', 'v', 'a' }
static const symbol s_3_10 [2] = { 'i', 'c' }
static const symbol s_3_11 [3] = { 'i', 'c', 'e' }
static const symbol s_3_12 [5] = { 'a', 'b', 'i', 'l', 'e' }
static const symbol s_3_13 [5] = { 'i', 'b', 'i', 'l', 'e' }
static const symbol s_3_14 [4] = { 'i', 's', 'm', 'e' }
static const symbol s_3_15 [4] = { 'i', 'u', 'n', 'e' }
static const symbol s_3_16 [4] = { 'o', 'a', 's', 'e' }
static const symbol s_3_17 [3] = { 'a', 't', 'e' }
static const symbol s_3_18 [5] = { 'i', 't', 'a', 't', 'e' }
static const symbol s_3_19 [3] = { 'i', 't', 'e' }
static const symbol s_3_20 [4] = { 'a', 'n', 't', 'e' }
static const symbol s_3_21 [4] = { 'i', 's', 't', 'e' }
static const symbol s_3_22 [3] = { 'u', 't', 'e' }
static const symbol s_3_23 [3] = { 'i', 'v', 'e' }
static const symbol s_3_24 [3] = { 'i', 'c', 'i' }
static const symbol s_3_25 [5] = { 'a', 'b', 'i', 'l', 'i' }
static const symbol s_3_26 [5] = { 'i', 'b', 'i', 'l', 'i' }
static const symbol s_3_27 [4] = { 'i', 'u', 'n', 'i' }
static const symbol s_3_28 [5] = { 'a', 't', 'o', 'r', 'i' }
static const symbol s_3_29 [3] = { 'o', 's', 'i' }
static const symbol s_3_30 [3] = { 'a', 't', 'i' }
static const symbol s_3_31 [5] = { 'i', 't', 'a', 't', 'i' }
static const symbol s_3_32 [3] = { 'i', 't', 'i' }
static const symbol s_3_33 [4] = { 'a', 'n', 't', 'i' }
static const symbol s_3_34 [4] = { 'i', 's', 't', 'i' }
static const symbol s_3_35 [3] = { 'u', 't', 'i' }
static const symbol s_3_36 [5] = { 'i', 0xC5, 0x9F, 't', 'i' }
static const symbol s_3_37 [3] = { 'i', 'v', 'i' }
static const symbol s_3_38 [5] = { 'i', 't', 0xC4, 0x83, 'i' }
static const symbol s_3_39 [4] = { 'o', 0xC5, 0x9F, 'i' }
static const symbol s_3_40 [7] = { 'i', 't', 0xC4, 0x83, 0xC5, 0xA3, 'i' }
static const symbol s_3_41 [4] = { 'a', 'b', 'i', 'l' }
static const symbol s_3_42 [4] = { 'i', 'b', 'i', 'l' }
static const symbol s_3_43 [3] = { 'i', 's', 'm' }
static const symbol s_3_44 [4] = { 'a', 't', 'o', 'r' }
static const symbol s_3_45 [2] = { 'o', 's' }
static const symbol s_3_46 [2] = { 'a', 't' }
static const symbol s_3_47 [2] = { 'i', 't' }
static const symbol s_3_48 [3] = { 'a', 'n', 't' }
static const symbol s_3_49 [3] = { 'i', 's', 't' }
static const symbol s_3_50 [2] = { 'u', 't' }
static const symbol s_3_51 [2] = { 'i', 'v' }
static const symbol s_3_52 [4] = { 'i', 'c', 0xC4, 0x83 }
static const symbol s_3_53 [6] = { 'a', 'b', 'i', 'l', 0xC4, 0x83 }
static const symbol s_3_54 [6] = { 'i', 'b', 'i', 'l', 0xC4, 0x83 }
static const symbol s_3_55 [5] = { 'o', 'a', 's', 0xC4, 0x83 }
static const symbol s_3_56 [4] = { 'a', 't', 0xC4, 0x83 }
static const symbol s_3_57 [4] = { 'i', 't', 0xC4, 0x83 }
static const symbol s_3_58 [5] = { 'a', 'n', 't', 0xC4, 0x83 }
static const symbol s_3_59 [5] = { 'i', 's', 't', 0xC4, 0x83 }
static const symbol s_3_60 [4] = { 'u', 't', 0xC4, 0x83 }
static const symbol s_3_61 [4] = { 'i', 'v', 0xC4, 0x83 }
static struct among a_3 [62]
static const symbol s_4_0 [2] = { 'e', 'a' }
static const symbol s_4_1 [2] = { 'i', 'a' }
static const symbol s_4_2 [3] = { 'e', 's', 'c' }
static const symbol s_4_3 [4] = { 0xC4, 0x83, 's', 'c' }
static const symbol s_4_4 [3] = { 'i', 'n', 'd' }
static const symbol s_4_5 [4] = { 0xC3, 0xA2, 'n', 'd' }
static const symbol s_4_6 [3] = { 'a', 'r', 'e' }
static const symbol s_4_7 [3] = { 'e', 'r', 'e' }
static const symbol s_4_8 [3] = { 'i', 'r', 'e' }
static const symbol s_4_9 [4] = { 0xC3, 0xA2, 'r', 'e' }
static const symbol s_4_10 [2] = { 's', 'e' }
static const symbol s_4_11 [3] = { 'a', 's', 'e' }
static const symbol s_4_12 [4] = { 's', 'e', 's', 'e' }
static const symbol s_4_13 [3] = { 'i', 's', 'e' }
static const symbol s_4_14 [3] = { 'u', 's', 'e' }
static const symbol s_4_15 [4] = { 0xC3, 0xA2, 's', 'e' }
static const symbol s_4_16 [5] = { 'e', 0xC5, 0x9F, 't', 'e' }
static const symbol s_4_17 [6] = { 0xC4, 0x83, 0xC5, 0x9F, 't', 'e' }
static const symbol s_4_18 [3] = { 'e', 'z', 'e' }
static const symbol s_4_19 [2] = { 'a', 'i' }
static const symbol s_4_20 [3] = { 'e', 'a', 'i' }
static const symbol s_4_21 [3] = { 'i', 'a', 'i' }
static const symbol s_4_22 [3] = { 's', 'e', 'i' }
static const symbol s_4_23 [5] = { 'e', 0xC5, 0x9F, 't', 'i' }
static const symbol s_4_24 [6] = { 0xC4, 0x83, 0xC5, 0x9F, 't', 'i' }
static const symbol s_4_25 [2] = { 'u', 'i' }
static const symbol s_4_26 [3] = { 'e', 'z', 'i' }
static const symbol s_4_27 [4] = { 'a', 0xC5, 0x9F, 'i' }
static const symbol s_4_28 [5] = { 's', 'e', 0xC5, 0x9F, 'i' }
static const symbol s_4_29 [6] = { 'a', 's', 'e', 0xC5, 0x9F, 'i' }
static const symbol s_4_30 [7] = { 's', 'e', 's', 'e', 0xC5, 0x9F, 'i' }
static const symbol s_4_31 [6] = { 'i', 's', 'e', 0xC5, 0x9F, 'i' }
static const symbol s_4_32 [6] = { 'u', 's', 'e', 0xC5, 0x9F, 'i' }
static const symbol s_4_33 [7] = { 0xC3, 0xA2, 's', 'e', 0xC5, 0x9F, 'i' }
static const symbol s_4_34 [4] = { 'i', 0xC5, 0x9F, 'i' }
static const symbol s_4_35 [4] = { 'u', 0xC5, 0x9F, 'i' }
static const symbol s_4_36 [5] = { 0xC3, 0xA2, 0xC5, 0x9F, 'i' }
static const symbol s_4_37 [3] = { 0xC3, 0xA2, 'i' }
static const symbol s_4_38 [4] = { 'a', 0xC5, 0xA3, 'i' }
static const symbol s_4_39 [5] = { 'e', 'a', 0xC5, 0xA3, 'i' }
static const symbol s_4_40 [5] = { 'i', 'a', 0xC5, 0xA3, 'i' }
static const symbol s_4_41 [4] = { 'e', 0xC5, 0xA3, 'i' }
static const symbol s_4_42 [4] = { 'i', 0xC5, 0xA3, 'i' }
static const symbol s_4_43 [7] = { 'a', 'r', 0xC4, 0x83, 0xC5, 0xA3, 'i' }
static const symbol s_4_44 [8] = { 's', 'e', 'r', 0xC4, 0x83, 0xC5, 0xA3, 'i' }
static const symbol s_4_45 [9] = { 'a', 's', 'e', 'r', 0xC4, 0x83, 0xC5, 0xA3, 'i' }
static const symbol s_4_46 [10] = { 's', 'e', 's', 'e', 'r', 0xC4, 0x83, 0xC5, 0xA3, 'i' }
static const symbol s_4_47 [9] = { 'i', 's', 'e', 'r', 0xC4, 0x83, 0xC5, 0xA3, 'i' }
static const symbol s_4_48 [9] = { 'u', 's', 'e', 'r', 0xC4, 0x83, 0xC5, 0xA3, 'i' }
static const symbol s_4_49 [10] = { 0xC3, 0xA2, 's', 'e', 'r', 0xC4, 0x83, 0xC5, 0xA3, 'i' }
static const symbol s_4_50 [7] = { 'i', 'r', 0xC4, 0x83, 0xC5, 0xA3, 'i' }
static const symbol s_4_51 [7] = { 'u', 'r', 0xC4, 0x83, 0xC5, 0xA3, 'i' }
static const symbol s_4_52 [8] = { 0xC3, 0xA2, 'r', 0xC4, 0x83, 0xC5, 0xA3, 'i' }
static const symbol s_4_53 [5] = { 0xC3, 0xA2, 0xC5, 0xA3, 'i' }
static const symbol s_4_54 [2] = { 'a', 'm' }
static const symbol s_4_55 [3] = { 'e', 'a', 'm' }
static const symbol s_4_56 [3] = { 'i', 'a', 'm' }
static const symbol s_4_57 [2] = { 'e', 'm' }
static const symbol s_4_58 [4] = { 'a', 's', 'e', 'm' }
static const symbol s_4_59 [5] = { 's', 'e', 's', 'e', 'm' }
static const symbol s_4_60 [4] = { 'i', 's', 'e', 'm' }
static const symbol s_4_61 [4] = { 'u', 's', 'e', 'm' }
static const symbol s_4_62 [5] = { 0xC3, 0xA2, 's', 'e', 'm' }
static const symbol s_4_63 [2] = { 'i', 'm' }
static const symbol s_4_64 [3] = { 0xC4, 0x83, 'm' }
static const symbol s_4_65 [5] = { 'a', 'r', 0xC4, 0x83, 'm' }
static const symbol s_4_66 [6] = { 's', 'e', 'r', 0xC4, 0x83, 'm' }
static const symbol s_4_67 [7] = { 'a', 's', 'e', 'r', 0xC4, 0x83, 'm' }
static const symbol s_4_68 [8] = { 's', 'e', 's', 'e', 'r', 0xC4, 0x83, 'm' }
static const symbol s_4_69 [7] = { 'i', 's', 'e', 'r', 0xC4, 0x83, 'm' }
static const symbol s_4_70 [7] = { 'u', 's', 'e', 'r', 0xC4, 0x83, 'm' }
static const symbol s_4_71 [8] = { 0xC3, 0xA2, 's', 'e', 'r', 0xC4, 0x83, 'm' }
static const symbol s_4_72 [5] = { 'i', 'r', 0xC4, 0x83, 'm' }
static const symbol s_4_73 [5] = { 'u', 'r', 0xC4, 0x83, 'm' }
static const symbol s_4_74 [6] = { 0xC3, 0xA2, 'r', 0xC4, 0x83, 'm' }
static const symbol s_4_75 [3] = { 0xC3, 0xA2, 'm' }
static const symbol s_4_76 [2] = { 'a', 'u' }
static const symbol s_4_77 [3] = { 'e', 'a', 'u' }
static const symbol s_4_78 [3] = { 'i', 'a', 'u' }
static const symbol s_4_79 [4] = { 'i', 'n', 'd', 'u' }
static const symbol s_4_80 [5] = { 0xC3, 0xA2, 'n', 'd', 'u' }
static const symbol s_4_81 [2] = { 'e', 'z' }
static const symbol s_4_82 [6] = { 'e', 'a', 's', 'c', 0xC4, 0x83 }
static const symbol s_4_83 [4] = { 'a', 'r', 0xC4, 0x83 }
static const symbol s_4_84 [5] = { 's', 'e', 'r', 0xC4, 0x83 }
static const symbol s_4_85 [6] = { 'a', 's', 'e', 'r', 0xC4, 0x83 }
static const symbol s_4_86 [7] = { 's', 'e', 's', 'e', 'r', 0xC4, 0x83 }
static const symbol s_4_87 [6] = { 'i', 's', 'e', 'r', 0xC4, 0x83 }
static const symbol s_4_88 [6] = { 'u', 's', 'e', 'r', 0xC4, 0x83 }
static const symbol s_4_89 [7] = { 0xC3, 0xA2, 's', 'e', 'r', 0xC4, 0x83 }
static const symbol s_4_90 [4] = { 'i', 'r', 0xC4, 0x83 }
static const symbol s_4_91 [4] = { 'u', 'r', 0xC4, 0x83 }
static const symbol s_4_92 [5] = { 0xC3, 0xA2, 'r', 0xC4, 0x83 }
static const symbol s_4_93 [5] = { 'e', 'a', 'z', 0xC4, 0x83 }
static struct among a_4 [94]
static const symbol s_5_0 [1] = { 'a' }
static const symbol s_5_1 [1] = { 'e' }
static const symbol s_5_2 [2] = { 'i', 'e' }
static const symbol s_5_3 [1] = { 'i' }
static const symbol s_5_4 [2] = { 0xC4, 0x83 }
static struct among a_5 [5]
static const unsigned char g_v [] = { 17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 32, 0, 0, 4 }
static const symbol s_0 [] = { 'u' }
static const symbol s_1 [] = { 'U' }
static const symbol s_2 [] = { 'i' }
static const symbol s_3 [] = { 'I' }
static const symbol s_4 [] = { 'i' }
static const symbol s_5 [] = { 'u' }
static const symbol s_6 [] = { 'a' }
static const symbol s_7 [] = { 'e' }
static const symbol s_8 [] = { 'i' }
static const symbol s_9 [] = { 'a', 'b' }
static const symbol s_10 [] = { 'i' }
static const symbol s_11 [] = { 'a', 't' }
static const symbol s_12 [] = { 'a', 0xC5, 0xA3, 'i' }
static const symbol s_13 [] = { 'a', 'b', 'i', 'l' }
static const symbol s_14 [] = { 'i', 'b', 'i', 'l' }
static const symbol s_15 [] = { 'i', 'v' }
static const symbol s_16 [] = { 'i', 'c' }
static const symbol s_17 [] = { 'a', 't' }
static const symbol s_18 [] = { 'i', 't' }
static const symbol s_19 [] = { 0xC5, 0xA3 }
static const symbol s_20 [] = { 't' }
static const symbol s_21 [] = { 'i', 's', 't' }
static const symbol s_22 [] = { 'u' }
Function Documentation
static int r_combo_suffix (struct SN_env * z) [static]
Definition at line 777 of file stem_UTF_8_romanian.cpp.
References SN_env::B, SN_env::bra, SN_env::c, find_among_b(), SN_env::ket, SN_env::l, r_R1(), s_13, s_14, s_15, s_16, s_17, s_18, and slice_from_s().
Referenced by r_standard_suffix().
static int r_mark_regions (struct SN_env * z) [static]
Definition at line 586 of file stem_UTF_8_romanian.cpp.
References SN_env::c, g_v, SN_env::I, in_grouping_U(), SN_env::l, out_grouping_U(), SN_env::p, and skip_utf8().
static int r_postlude (struct SN_env * z) [static]
Definition at line 668 of file stem_UTF_8_romanian.cpp.
References SN_env::bra, SN_env::c, find_among(), SN_env::ket, SN_env::l, SN_env::p, s_4, s_5, skip_utf8(), and slice_from_s().
static int r_prelude (struct SN_env * z) [static]
Definition at line 544 of file stem_UTF_8_romanian.cpp.
References SN_env::bra, SN_env::c, eq_s(), g_v, in_grouping_U(), SN_env::ket, SN_env::l, SN_env::p, s_0, s_1, s_2, s_3, skip_utf8(), and slice_from_s().
static int r_R1 (struct SN_env * z) [static]
Definition at line 709 of file stem_UTF_8_romanian.cpp.
References SN_env::c, and SN_env::I.
static int r_R2 (struct SN_env * z) [static]
Definition at line 714 of file stem_UTF_8_romanian.cpp.
References SN_env::c, and SN_env::I.
static int r_RV (struct SN_env * z) [static]
Definition at line 704 of file stem_UTF_8_romanian.cpp.
References SN_env::c, and SN_env::I.
static int r_standard_suffix (struct SN_env * z) [static]
Definition at line 827 of file stem_UTF_8_romanian.cpp.
References SN_env::B, SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), SN_env::ket, SN_env::l, r_combo_suffix(), r_R2(), s_19, s_20, s_21, slice_del(), and slice_from_s().
static int r_step_0 (struct SN_env * z) [static]
Definition at line 719 of file stem_UTF_8_romanian.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), SN_env::ket, SN_env::l, SN_env::lb, SN_env::p, r_R1(), s_10, s_11, s_12, s_6, s_7, s_8, s_9, slice_del(), and slice_from_s().
Referenced by romanian_UTF_8_stem().
static int r_verb_suffix (struct SN_env * z) [static]
Definition at line 873 of file stem_UTF_8_romanian.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), g_v, SN_env::I, SN_env::ket, SN_env::l, SN_env::lb, out_grouping_b_U(), s_22, and slice_del().
static int r_vowel_suffix (struct SN_env * z) [static]
Definition at line 911 of file stem_UTF_8_romanian.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::ket, r_RV(), and slice_del().
void romanian_UTF_8_close_env (struct SN_env * z)
struct SN_env* romanian_UTF_8_create_env (void) [read]
int romanian_UTF_8_stem (struct SN_env * z)
Variable Documentation
struct among a_0[3] [static]
Initial value:
{
 { 0, 0, -1, 3, 0},
 { 1, s_0_1, 0, 1, 0},
 { 1, s_0_2, 0, 2, 0}
}
Definition at line 40 of file stem_UTF_8_romanian.cpp.
struct among a_1[16] [static]
Initial value:
{
 { 2, s_1_0, -1, 3, 0},
 { 5, s_1_1, -1, 7, 0},
 { 3, s_1_2, -1, 2, 0},
 { 3, s_1_3, -1, 4, 0},
 { 5, s_1_4, -1, 7, 0},
 { 3, s_1_5, -1, 3, 0},
 { 3, s_1_6, -1, 5, 0},
 { 4, s_1_7, 6, 4, 0},
 { 3, s_1_8, -1, 4, 0},
 { 4, s_1_9, -1, 6, 0},
 { 2, s_1_10, -1, 4, 0},
 { 4, s_1_11, -1, 1, 0},
 { 2, s_1_12, -1, 1, 0},
 { 4, s_1_13, -1, 3, 0},
 { 4, s_1_14, -1, 4, 0},
 { 5, s_1_15, 14, 4, 0}
}
Definition at line 64 of file stem_UTF_8_romanian.cpp.
struct among a_2[46] [static]
Definition at line 131 of file stem_UTF_8_romanian.cpp.
struct among a_3[62] [static]
Definition at line 244 of file stem_UTF_8_romanian.cpp.
struct among a_4[94] [static]
Definition at line 405 of file stem_UTF_8_romanian.cpp.
struct among a_5[5] [static]
Initial value:
{
 { 1, s_5_0, -1, 1, 0},
 { 1, s_5_1, -1, 1, 0},
 { 2, s_5_2, 1, 1, 0},
 { 1, s_5_3, -1, 1, 0},
 { 2, s_5_4, -1, 1, 0}
}
Definition at line 509 of file stem_UTF_8_romanian.cpp.
const unsigned char g_v[] = { 17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 32, 0, 0, 4 } [static]
Definition at line 518 of file stem_UTF_8_romanian.cpp.
const symbol s_0[] = { 'u' } [static]
Definition at line 520 of file stem_UTF_8_romanian.cpp.
const symbol s_0_1[1] = { 'I' } [static]
Definition at line 37 of file stem_UTF_8_romanian.cpp.
const symbol s_0_2[1] = { 'U' } [static]
Definition at line 38 of file stem_UTF_8_romanian.cpp.
const symbol s_1[] = { 'U' } [static]
Definition at line 521 of file stem_UTF_8_romanian.cpp.
const symbol s_10[] = { 'i' } [static]
Definition at line 530 of file stem_UTF_8_romanian.cpp.
const symbol s_11[] = { 'a', 't' } [static]
Definition at line 531 of file stem_UTF_8_romanian.cpp.
const symbol s_12[] = { 'a', 0xC5, 0xA3, 'i' } [static]
Definition at line 532 of file stem_UTF_8_romanian.cpp.
const symbol s_13[] = { 'a', 'b', 'i', 'l' } [static]
Definition at line 533 of file stem_UTF_8_romanian.cpp.
const symbol s_14[] = { 'i', 'b', 'i', 'l' } [static]
Definition at line 534 of file stem_UTF_8_romanian.cpp.
const symbol s_15[] = { 'i', 'v' } [static]
Definition at line 535 of file stem_UTF_8_romanian.cpp.
const symbol s_16[] = { 'i', 'c' } [static]
Definition at line 536 of file stem_UTF_8_romanian.cpp.
const symbol s_17[] = { 'a', 't' } [static]
Definition at line 537 of file stem_UTF_8_romanian.cpp.
const symbol s_18[] = { 'i', 't' } [static]
Definition at line 538 of file stem_UTF_8_romanian.cpp.
const symbol s_19[] = { 0xC5, 0xA3 } [static]
Definition at line 539 of file stem_UTF_8_romanian.cpp.
const symbol s_1_0[2] = { 'e', 'a' } [static]
Definition at line 47 of file stem_UTF_8_romanian.cpp.
const symbol s_1_1[5] = { 'a', 0xC5, 0xA3, 'i', 'a' } [static]
Definition at line 48 of file stem_UTF_8_romanian.cpp.
const symbol s_1_10[2] = { 'i', 'i' } [static]
Definition at line 57 of file stem_UTF_8_romanian.cpp.
const symbol s_1_11[4] = { 'u', 'l', 'u', 'i' } [static]
Definition at line 58 of file stem_UTF_8_romanian.cpp.
const symbol s_1_12[2] = { 'u', 'l' } [static]
Definition at line 59 of file stem_UTF_8_romanian.cpp.
const symbol s_1_13[4] = { 'e', 'l', 'o', 'r' } [static]
Definition at line 60 of file stem_UTF_8_romanian.cpp.
const symbol s_1_14[4] = { 'i', 'l', 'o', 'r' } [static]
Definition at line 61 of file stem_UTF_8_romanian.cpp.
const symbol s_1_15[5] = { 'i', 'i', 'l', 'o', 'r' } [static]
Definition at line 62 of file stem_UTF_8_romanian.cpp.
const symbol s_1_2[3] = { 'a', 'u', 'a' } [static]
Definition at line 49 of file stem_UTF_8_romanian.cpp.
const symbol s_1_3[3] = { 'i', 'u', 'a' } [static]
Definition at line 50 of file stem_UTF_8_romanian.cpp.
const symbol s_1_4[5] = { 'a', 0xC5, 0xA3, 'i', 'e' } [static]
Definition at line 51 of file stem_UTF_8_romanian.cpp.
const symbol s_1_5[3] = { 'e', 'l', 'e' } [static]
Definition at line 52 of file stem_UTF_8_romanian.cpp.
const symbol s_1_6[3] = { 'i', 'l', 'e' } [static]
Definition at line 53 of file stem_UTF_8_romanian.cpp.
const symbol s_1_7[4] = { 'i', 'i', 'l', 'e' } [static]
Definition at line 54 of file stem_UTF_8_romanian.cpp.
const symbol s_1_8[3] = { 'i', 'e', 'i' } [static]
Definition at line 55 of file stem_UTF_8_romanian.cpp.
const symbol s_1_9[4] = { 'a', 't', 'e', 'i' } [static]
Definition at line 56 of file stem_UTF_8_romanian.cpp.
const symbol s_2[] = { 'i' } [static]
Definition at line 522 of file stem_UTF_8_romanian.cpp.
const symbol s_20[] = { 't' } [static]
Definition at line 540 of file stem_UTF_8_romanian.cpp.
const symbol s_21[] = { 'i', 's', 't' } [static]
Definition at line 541 of file stem_UTF_8_romanian.cpp.
const symbol s_22[] = { 'u' } [static]
Definition at line 542 of file stem_UTF_8_romanian.cpp.
const symbol s_2_0[5] = { 'i', 'c', 'a', 'l', 'a' } [static]
Definition at line 84 of file stem_UTF_8_romanian.cpp.
const symbol s_2_1[5] = { 'i', 'c', 'i', 'v', 'a' } [static]
Definition at line 85 of file stem_UTF_8_romanian.cpp.
const symbol s_2_10[7] = { 'i', 'c', 'i', 't', 'a', 't', 'e' } [static]
Definition at line 94 of file stem_UTF_8_romanian.cpp.
const symbol s_2_11[9] = { 'a', 'b', 'i', 'l', 'i', 't', 'a', 't', 'e' } [static]
Definition at line 95 of file stem_UTF_8_romanian.cpp.
const symbol s_2_12[9] = { 'i', 'b', 'i', 'l', 'i', 't', 'a', 't', 'e' } [static]
Definition at line 96 of file stem_UTF_8_romanian.cpp.
const symbol s_2_13[7] = { 'i', 'v', 'i', 't', 'a', 't', 'e' } [static]
Definition at line 97 of file stem_UTF_8_romanian.cpp.
const symbol s_2_14[5] = { 'i', 'c', 'i', 'v', 'e' } [static]
Definition at line 98 of file stem_UTF_8_romanian.cpp.
const symbol s_2_15[5] = { 'a', 't', 'i', 'v', 'e' } [static]
Definition at line 99 of file stem_UTF_8_romanian.cpp.
const symbol s_2_16[5] = { 'i', 't', 'i', 'v', 'e' } [static]
Definition at line 100 of file stem_UTF_8_romanian.cpp.
const symbol s_2_17[5] = { 'i', 'c', 'a', 'l', 'i' } [static]
Definition at line 101 of file stem_UTF_8_romanian.cpp.
const symbol s_2_18[5] = { 'a', 't', 'o', 'r', 'i' } [static]
Definition at line 102 of file stem_UTF_8_romanian.cpp.
const symbol s_2_19[7] = { 'i', 'c', 'a', 't', 'o', 'r', 'i' } [static]
Definition at line 103 of file stem_UTF_8_romanian.cpp.
const symbol s_2_2[5] = { 'a', 't', 'i', 'v', 'a' } [static]
Definition at line 86 of file stem_UTF_8_romanian.cpp.
const symbol s_2_20[5] = { 'i', 't', 'o', 'r', 'i' } [static]
Definition at line 104 of file stem_UTF_8_romanian.cpp.
const symbol s_2_21[6] = { 0xC4, 0x83, 't', 'o', 'r', 'i' } [static]
Definition at line 105 of file stem_UTF_8_romanian.cpp.
const symbol s_2_22[7] = { 'i', 'c', 'i', 't', 'a', 't', 'i' } [static]
Definition at line 106 of file stem_UTF_8_romanian.cpp.
const symbol s_2_23[9] = { 'a', 'b', 'i', 'l', 'i', 't', 'a', 't', 'i' } [static]
Definition at line 107 of file stem_UTF_8_romanian.cpp.
const symbol s_2_24[7] = { 'i', 'v', 'i', 't', 'a', 't', 'i' } [static]
Definition at line 108 of file stem_UTF_8_romanian.cpp.
const symbol s_2_25[5] = { 'i', 'c', 'i', 'v', 'i' } [static]
Definition at line 109 of file stem_UTF_8_romanian.cpp.
const symbol s_2_26[5] = { 'a', 't', 'i', 'v', 'i' } [static]
Definition at line 110 of file stem_UTF_8_romanian.cpp.
const symbol s_2_27[5] = { 'i', 't', 'i', 'v', 'i' } [static]
Definition at line 111 of file stem_UTF_8_romanian.cpp.
const symbol s_2_28[7] = { 'i', 'c', 'i', 't', 0xC4, 0x83, 'i' } [static]
Definition at line 112 of file stem_UTF_8_romanian.cpp.
const symbol s_2_29[9] = { 'a', 'b', 'i', 'l', 'i', 't', 0xC4, 0x83, 'i' } [static]
Definition at line 113 of file stem_UTF_8_romanian.cpp.
const symbol s_2_3[5] = { 'i', 't', 'i', 'v', 'a' } [static]
Definition at line 87 of file stem_UTF_8_romanian.cpp.
const symbol s_2_30[7] = { 'i', 'v', 'i', 't', 0xC4, 0x83, 'i' } [static]
Definition at line 114 of file stem_UTF_8_romanian.cpp.
const symbol s_2_31[9] = { 'i', 'c', 'i', 't', 0xC4, 0x83, 0xC5, 0xA3, 'i' } [static]
Definition at line 115 of file stem_UTF_8_romanian.cpp.
const symbol s_2_32[11] = { 'a', 'b', 'i', 'l', 'i', 't', 0xC4, 0x83, 0xC5, 0xA3, 'i' } [static]
Definition at line 116 of file stem_UTF_8_romanian.cpp.
const symbol s_2_33[9] = { 'i', 'v', 'i', 't', 0xC4, 0x83, 0xC5, 0xA3, 'i' } [static]
Definition at line 117 of file stem_UTF_8_romanian.cpp.
const symbol s_2_34[4] = { 'i', 'c', 'a', 'l' } [static]
Definition at line 118 of file stem_UTF_8_romanian.cpp.
const symbol s_2_35[4] = { 'a', 't', 'o', 'r' } [static]
Definition at line 119 of file stem_UTF_8_romanian.cpp.
const symbol s_2_36[6] = { 'i', 'c', 'a', 't', 'o', 'r' } [static]
Definition at line 120 of file stem_UTF_8_romanian.cpp.
const symbol s_2_37[4] = { 'i', 't', 'o', 'r' } [static]
Definition at line 121 of file stem_UTF_8_romanian.cpp.
const symbol s_2_38[5] = { 0xC4, 0x83, 't', 'o', 'r' } [static]
Definition at line 122 of file stem_UTF_8_romanian.cpp.
const symbol s_2_39[4] = { 'i', 'c', 'i', 'v' } [static]
Definition at line 123 of file stem_UTF_8_romanian.cpp.
const symbol s_2_4[5] = { 'i', 'c', 'a', 'l', 'e' } [static]
Definition at line 88 of file stem_UTF_8_romanian.cpp.
const symbol s_2_40[4] = { 'a', 't', 'i', 'v' } [static]
Definition at line 124 of file stem_UTF_8_romanian.cpp.
const symbol s_2_41[4] = { 'i', 't', 'i', 'v' } [static]
Definition at line 125 of file stem_UTF_8_romanian.cpp.
const symbol s_2_42[6] = { 'i', 'c', 'a', 'l', 0xC4, 0x83 } [static]
Definition at line 126 of file stem_UTF_8_romanian.cpp.
const symbol s_2_43[6] = { 'i', 'c', 'i', 'v', 0xC4, 0x83 } [static]
Definition at line 127 of file stem_UTF_8_romanian.cpp.
const symbol s_2_44[6] = { 'a', 't', 'i', 'v', 0xC4, 0x83 } [static]
Definition at line 128 of file stem_UTF_8_romanian.cpp.
const symbol s_2_45[6] = { 'i', 't', 'i', 'v', 0xC4, 0x83 } [static]
Definition at line 129 of file stem_UTF_8_romanian.cpp.
const symbol s_2_5[7] = { 'a', 0xC5, 0xA3, 'i', 'u', 'n', 'e' } [static]
Definition at line 89 of file stem_UTF_8_romanian.cpp.
const symbol s_2_6[7] = { 'i', 0xC5, 0xA3, 'i', 'u', 'n', 'e' } [static]
Definition at line 90 of file stem_UTF_8_romanian.cpp.
const symbol s_2_7[6] = { 'a', 't', 'o', 'a', 'r', 'e' } [static]
Definition at line 91 of file stem_UTF_8_romanian.cpp.
const symbol s_2_8[6] = { 'i', 't', 'o', 'a', 'r', 'e' } [static]
Definition at line 92 of file stem_UTF_8_romanian.cpp.
const symbol s_2_9[7] = { 0xC4, 0x83, 't', 'o', 'a', 'r', 'e' } [static]
Definition at line 93 of file stem_UTF_8_romanian.cpp.
const symbol s_3[] = { 'I' } [static]
Definition at line 523 of file stem_UTF_8_romanian.cpp.
const symbol s_3_0[3] = { 'i', 'c', 'a' } [static]
Definition at line 181 of file stem_UTF_8_romanian.cpp.
const symbol s_3_1[5] = { 'a', 'b', 'i', 'l', 'a' } [static]
Definition at line 182 of file stem_UTF_8_romanian.cpp.
const symbol s_3_10[2] = { 'i', 'c' } [static]
Definition at line 191 of file stem_UTF_8_romanian.cpp.
const symbol s_3_11[3] = { 'i', 'c', 'e' } [static]
Definition at line 192 of file stem_UTF_8_romanian.cpp.
const symbol s_3_12[5] = { 'a', 'b', 'i', 'l', 'e' } [static]
Definition at line 193 of file stem_UTF_8_romanian.cpp.
const symbol s_3_13[5] = { 'i', 'b', 'i', 'l', 'e' } [static]
Definition at line 194 of file stem_UTF_8_romanian.cpp.
const symbol s_3_14[4] = { 'i', 's', 'm', 'e' } [static]
Definition at line 195 of file stem_UTF_8_romanian.cpp.
const symbol s_3_15[4] = { 'i', 'u', 'n', 'e' } [static]
Definition at line 196 of file stem_UTF_8_romanian.cpp.
const symbol s_3_16[4] = { 'o', 'a', 's', 'e' } [static]
Definition at line 197 of file stem_UTF_8_romanian.cpp.
const symbol s_3_17[3] = { 'a', 't', 'e' } [static]
Definition at line 198 of file stem_UTF_8_romanian.cpp.
const symbol s_3_18[5] = { 'i', 't', 'a', 't', 'e' } [static]
Definition at line 199 of file stem_UTF_8_romanian.cpp.
const symbol s_3_19[3] = { 'i', 't', 'e' } [static]
Definition at line 200 of file stem_UTF_8_romanian.cpp.
const symbol s_3_2[5] = { 'i', 'b', 'i', 'l', 'a' } [static]
Definition at line 183 of file stem_UTF_8_romanian.cpp.
const symbol s_3_20[4] = { 'a', 'n', 't', 'e' } [static]
Definition at line 201 of file stem_UTF_8_romanian.cpp.
const symbol s_3_21[4] = { 'i', 's', 't', 'e' } [static]
Definition at line 202 of file stem_UTF_8_romanian.cpp.
const symbol s_3_22[3] = { 'u', 't', 'e' } [static]
Definition at line 203 of file stem_UTF_8_romanian.cpp.
const symbol s_3_23[3] = { 'i', 'v', 'e' } [static]
Definition at line 204 of file stem_UTF_8_romanian.cpp.
const symbol s_3_24[3] = { 'i', 'c', 'i' } [static]
Definition at line 205 of file stem_UTF_8_romanian.cpp.
const symbol s_3_25[5] = { 'a', 'b', 'i', 'l', 'i' } [static]
Definition at line 206 of file stem_UTF_8_romanian.cpp.
const symbol s_3_26[5] = { 'i', 'b', 'i', 'l', 'i' } [static]
Definition at line 207 of file stem_UTF_8_romanian.cpp.
const symbol s_3_27[4] = { 'i', 'u', 'n', 'i' } [static]
Definition at line 208 of file stem_UTF_8_romanian.cpp.
const symbol s_3_28[5] = { 'a', 't', 'o', 'r', 'i' } [static]
Definition at line 209 of file stem_UTF_8_romanian.cpp.
const symbol s_3_29[3] = { 'o', 's', 'i' } [static]
Definition at line 210 of file stem_UTF_8_romanian.cpp.
const symbol s_3_3[4] = { 'o', 'a', 's', 'a' } [static]
Definition at line 184 of file stem_UTF_8_romanian.cpp.
const symbol s_3_30[3] = { 'a', 't', 'i' } [static]
Definition at line 211 of file stem_UTF_8_romanian.cpp.
const symbol s_3_31[5] = { 'i', 't', 'a', 't', 'i' } [static]
Definition at line 212 of file stem_UTF_8_romanian.cpp.
const symbol s_3_32[3] = { 'i', 't', 'i' } [static]
Definition at line 213 of file stem_UTF_8_romanian.cpp.
const symbol s_3_33[4] = { 'a', 'n', 't', 'i' } [static]
Definition at line 214 of file stem_UTF_8_romanian.cpp.
const symbol s_3_34[4] = { 'i', 's', 't', 'i' } [static]
Definition at line 215 of file stem_UTF_8_romanian.cpp.
const symbol s_3_35[3] = { 'u', 't', 'i' } [static]
Definition at line 216 of file stem_UTF_8_romanian.cpp.
const symbol s_3_36[5] = { 'i', 0xC5, 0x9F, 't', 'i' } [static]
Definition at line 217 of file stem_UTF_8_romanian.cpp.
const symbol s_3_37[3] = { 'i', 'v', 'i' } [static]
Definition at line 218 of file stem_UTF_8_romanian.cpp.
const symbol s_3_38[5] = { 'i', 't', 0xC4, 0x83, 'i' } [static]
Definition at line 219 of file stem_UTF_8_romanian.cpp.
const symbol s_3_39[4] = { 'o', 0xC5, 0x9F, 'i' } [static]
Definition at line 220 of file stem_UTF_8_romanian.cpp.
const symbol s_3_4[3] = { 'a', 't', 'a' } [static]
Definition at line 185 of file stem_UTF_8_romanian.cpp.
const symbol s_3_40[7] = { 'i', 't', 0xC4, 0x83, 0xC5, 0xA3, 'i' } [static]
Definition at line 221 of file stem_UTF_8_romanian.cpp.
const symbol s_3_41[4] = { 'a', 'b', 'i', 'l' } [static]
Definition at line 222 of file stem_UTF_8_romanian.cpp.
const symbol s_3_42[4] = { 'i', 'b', 'i', 'l' } [static]
Definition at line 223 of file stem_UTF_8_romanian.cpp.
const symbol s_3_43[3] = { 'i', 's', 'm' } [static]
Definition at line 224 of file stem_UTF_8_romanian.cpp.
const symbol s_3_44[4] = { 'a', 't', 'o', 'r' } [static]
Definition at line 225 of file stem_UTF_8_romanian.cpp.
const symbol s_3_45[2] = { 'o', 's' } [static]
Definition at line 226 of file stem_UTF_8_romanian.cpp.
const symbol s_3_46[2] = { 'a', 't' } [static]
Definition at line 227 of file stem_UTF_8_romanian.cpp.
const symbol s_3_47[2] = { 'i', 't' } [static]
Definition at line 228 of file stem_UTF_8_romanian.cpp.
const symbol s_3_48[3] = { 'a', 'n', 't' } [static]
Definition at line 229 of file stem_UTF_8_romanian.cpp.
const symbol s_3_49[3] = { 'i', 's', 't' } [static]
Definition at line 230 of file stem_UTF_8_romanian.cpp.
const symbol s_3_5[3] = { 'i', 't', 'a' } [static]
Definition at line 186 of file stem_UTF_8_romanian.cpp.
const symbol s_3_50[2] = { 'u', 't' } [static]
Definition at line 231 of file stem_UTF_8_romanian.cpp.
const symbol s_3_51[2] = { 'i', 'v' } [static]
Definition at line 232 of file stem_UTF_8_romanian.cpp.
const symbol s_3_52[4] = { 'i', 'c', 0xC4, 0x83 } [static]
Definition at line 233 of file stem_UTF_8_romanian.cpp.
const symbol s_3_53[6] = { 'a', 'b', 'i', 'l', 0xC4, 0x83 } [static]
Definition at line 234 of file stem_UTF_8_romanian.cpp.
const symbol s_3_54[6] = { 'i', 'b', 'i', 'l', 0xC4, 0x83 } [static]
Definition at line 235 of file stem_UTF_8_romanian.cpp.
const symbol s_3_55[5] = { 'o', 'a', 's', 0xC4, 0x83 } [static]
Definition at line 236 of file stem_UTF_8_romanian.cpp.
const symbol s_3_56[4] = { 'a', 't', 0xC4, 0x83 } [static]
Definition at line 237 of file stem_UTF_8_romanian.cpp.
const symbol s_3_57[4] = { 'i', 't', 0xC4, 0x83 } [static]
Definition at line 238 of file stem_UTF_8_romanian.cpp.
const symbol s_3_58[5] = { 'a', 'n', 't', 0xC4, 0x83 } [static]
Definition at line 239 of file stem_UTF_8_romanian.cpp.
const symbol s_3_59[5] = { 'i', 's', 't', 0xC4, 0x83 } [static]
Definition at line 240 of file stem_UTF_8_romanian.cpp.
const symbol s_3_6[4] = { 'a', 'n', 't', 'a' } [static]
Definition at line 187 of file stem_UTF_8_romanian.cpp.
const symbol s_3_60[4] = { 'u', 't', 0xC4, 0x83 } [static]
Definition at line 241 of file stem_UTF_8_romanian.cpp.
const symbol s_3_61[4] = { 'i', 'v', 0xC4, 0x83 } [static]
Definition at line 242 of file stem_UTF_8_romanian.cpp.
const symbol s_3_7[4] = { 'i', 's', 't', 'a' } [static]
Definition at line 188 of file stem_UTF_8_romanian.cpp.
const symbol s_3_8[3] = { 'u', 't', 'a' } [static]
Definition at line 189 of file stem_UTF_8_romanian.cpp.
const symbol s_3_9[3] = { 'i', 'v', 'a' } [static]
Definition at line 190 of file stem_UTF_8_romanian.cpp.
const symbol s_4[] = { 'i' } [static]
Definition at line 524 of file stem_UTF_8_romanian.cpp.
const symbol s_4_0[2] = { 'e', 'a' } [static]
Definition at line 310 of file stem_UTF_8_romanian.cpp.
const symbol s_4_1[2] = { 'i', 'a' } [static]
Definition at line 311 of file stem_UTF_8_romanian.cpp.
const symbol s_4_10[2] = { 's', 'e' } [static]
Definition at line 320 of file stem_UTF_8_romanian.cpp.
const symbol s_4_11[3] = { 'a', 's', 'e' } [static]
Definition at line 321 of file stem_UTF_8_romanian.cpp.
const symbol s_4_12[4] = { 's', 'e', 's', 'e' } [static]
Definition at line 322 of file stem_UTF_8_romanian.cpp.
const symbol s_4_13[3] = { 'i', 's', 'e' } [static]
Definition at line 323 of file stem_UTF_8_romanian.cpp.
const symbol s_4_14[3] = { 'u', 's', 'e' } [static]
Definition at line 324 of file stem_UTF_8_romanian.cpp.
const symbol s_4_15[4] = { 0xC3, 0xA2, 's', 'e' } [static]
Definition at line 325 of file stem_UTF_8_romanian.cpp.
const symbol s_4_16[5] = { 'e', 0xC5, 0x9F, 't', 'e' } [static]
Definition at line 326 of file stem_UTF_8_romanian.cpp.
const symbol s_4_17[6] = { 0xC4, 0x83, 0xC5, 0x9F, 't', 'e' } [static]
Definition at line 327 of file stem_UTF_8_romanian.cpp.
const symbol s_4_18[3] = { 'e', 'z', 'e' } [static]
Definition at line 328 of file stem_UTF_8_romanian.cpp.
const symbol s_4_19[2] = { 'a', 'i' } [static]
Definition at line 329 of file stem_UTF_8_romanian.cpp.
const symbol s_4_2[3] = { 'e', 's', 'c' } [static]
Definition at line 312 of file stem_UTF_8_romanian.cpp.
const symbol s_4_20[3] = { 'e', 'a', 'i' } [static]
Definition at line 330 of file stem_UTF_8_romanian.cpp.
const symbol s_4_21[3] = { 'i', 'a', 'i' } [static]
Definition at line 331 of file stem_UTF_8_romanian.cpp.
const symbol s_4_22[3] = { 's', 'e', 'i' } [static]
Definition at line 332 of file stem_UTF_8_romanian.cpp.
const symbol s_4_23[5] = { 'e', 0xC5, 0x9F, 't', 'i' } [static]
Definition at line 333 of file stem_UTF_8_romanian.cpp.
const symbol s_4_24[6] = { 0xC4, 0x83, 0xC5, 0x9F, 't', 'i' } [static]
Definition at line 334 of file stem_UTF_8_romanian.cpp.
const symbol s_4_25[2] = { 'u', 'i' } [static]
Definition at line 335 of file stem_UTF_8_romanian.cpp.
const symbol s_4_26[3] = { 'e', 'z', 'i' } [static]
Definition at line 336 of file stem_UTF_8_romanian.cpp.
const symbol s_4_27[4] = { 'a', 0xC5, 0x9F, 'i' } [static]
Definition at line 337 of file stem_UTF_8_romanian.cpp.
const symbol s_4_28[5] = { 's', 'e', 0xC5, 0x9F, 'i' } [static]
Definition at line 338 of file stem_UTF_8_romanian.cpp.
const symbol s_4_29[6] = { 'a', 's', 'e', 0xC5, 0x9F, 'i' } [static]
Definition at line 339 of file stem_UTF_8_romanian.cpp.
const symbol s_4_3[4] = { 0xC4, 0x83, 's', 'c' } [static]
Definition at line 313 of file stem_UTF_8_romanian.cpp.
const symbol s_4_30[7] = { 's', 'e', 's', 'e', 0xC5, 0x9F, 'i' } [static]
Definition at line 340 of file stem_UTF_8_romanian.cpp.
const symbol s_4_31[6] = { 'i', 's', 'e', 0xC5, 0x9F, 'i' } [static]
Definition at line 341 of file stem_UTF_8_romanian.cpp.
const symbol s_4_32[6] = { 'u', 's', 'e', 0xC5, 0x9F, 'i' } [static]
Definition at line 342 of file stem_UTF_8_romanian.cpp.
const symbol s_4_33[7] = { 0xC3, 0xA2, 's', 'e', 0xC5, 0x9F, 'i' } [static]
Definition at line 343 of file stem_UTF_8_romanian.cpp.
const symbol s_4_34[4] = { 'i', 0xC5, 0x9F, 'i' } [static]
Definition at line 344 of file stem_UTF_8_romanian.cpp.
const symbol s_4_35[4] = { 'u', 0xC5, 0x9F, 'i' } [static]
Definition at line 345 of file stem_UTF_8_romanian.cpp.
const symbol s_4_36[5] = { 0xC3, 0xA2, 0xC5, 0x9F, 'i' } [static]
Definition at line 346 of file stem_UTF_8_romanian.cpp.
const symbol s_4_37[3] = { 0xC3, 0xA2, 'i' } [static]
Definition at line 347 of file stem_UTF_8_romanian.cpp.
const symbol s_4_38[4] = { 'a', 0xC5, 0xA3, 'i' } [static]
Definition at line 348 of file stem_UTF_8_romanian.cpp.
const symbol s_4_39[5] = { 'e', 'a', 0xC5, 0xA3, 'i' } [static]
Definition at line 349 of file stem_UTF_8_romanian.cpp.
const symbol s_4_4[3] = { 'i', 'n', 'd' } [static]
Definition at line 314 of file stem_UTF_8_romanian.cpp.
const symbol s_4_40[5] = { 'i', 'a', 0xC5, 0xA3, 'i' } [static]
Definition at line 350 of file stem_UTF_8_romanian.cpp.
const symbol s_4_41[4] = { 'e', 0xC5, 0xA3, 'i' } [static]
Definition at line 351 of file stem_UTF_8_romanian.cpp.
const symbol s_4_42[4] = { 'i', 0xC5, 0xA3, 'i' } [static]
Definition at line 352 of file stem_UTF_8_romanian.cpp.
const symbol s_4_43[7] = { 'a', 'r', 0xC4, 0x83, 0xC5, 0xA3, 'i' } [static]
Definition at line 353 of file stem_UTF_8_romanian.cpp.
const symbol s_4_44[8] = { 's', 'e', 'r', 0xC4, 0x83, 0xC5, 0xA3, 'i' } [static]
Definition at line 354 of file stem_UTF_8_romanian.cpp.
const symbol s_4_45[9] = { 'a', 's', 'e', 'r', 0xC4, 0x83, 0xC5, 0xA3, 'i' } [static]
Definition at line 355 of file stem_UTF_8_romanian.cpp.
const symbol s_4_46[10] = { 's', 'e', 's', 'e', 'r', 0xC4, 0x83, 0xC5, 0xA3, 'i' } [static]
Definition at line 356 of file stem_UTF_8_romanian.cpp.
const symbol s_4_47[9] = { 'i', 's', 'e', 'r', 0xC4, 0x83, 0xC5, 0xA3, 'i' } [static]
Definition at line 357 of file stem_UTF_8_romanian.cpp.
const symbol s_4_48[9] = { 'u', 's', 'e', 'r', 0xC4, 0x83, 0xC5, 0xA3, 'i' } [static]
Definition at line 358 of file stem_UTF_8_romanian.cpp.
const symbol s_4_49[10] = { 0xC3, 0xA2, 's', 'e', 'r', 0xC4, 0x83, 0xC5, 0xA3, 'i' } [static]
Definition at line 359 of file stem_UTF_8_romanian.cpp.
const symbol s_4_5[4] = { 0xC3, 0xA2, 'n', 'd' } [static]
Definition at line 315 of file stem_UTF_8_romanian.cpp.
const symbol s_4_50[7] = { 'i', 'r', 0xC4, 0x83, 0xC5, 0xA3, 'i' } [static]
Definition at line 360 of file stem_UTF_8_romanian.cpp.
const symbol s_4_51[7] = { 'u', 'r', 0xC4, 0x83, 0xC5, 0xA3, 'i' } [static]
Definition at line 361 of file stem_UTF_8_romanian.cpp.
const symbol s_4_52[8] = { 0xC3, 0xA2, 'r', 0xC4, 0x83, 0xC5, 0xA3, 'i' } [static]
Definition at line 362 of file stem_UTF_8_romanian.cpp.
const symbol s_4_53[5] = { 0xC3, 0xA2, 0xC5, 0xA3, 'i' } [static]
Definition at line 363 of file stem_UTF_8_romanian.cpp.
const symbol s_4_54[2] = { 'a', 'm' } [static]
Definition at line 364 of file stem_UTF_8_romanian.cpp.
const symbol s_4_55[3] = { 'e', 'a', 'm' } [static]
Definition at line 365 of file stem_UTF_8_romanian.cpp.
const symbol s_4_56[3] = { 'i', 'a', 'm' } [static]
Definition at line 366 of file stem_UTF_8_romanian.cpp.
const symbol s_4_57[2] = { 'e', 'm' } [static]
Definition at line 367 of file stem_UTF_8_romanian.cpp.
const symbol s_4_58[4] = { 'a', 's', 'e', 'm' } [static]
Definition at line 368 of file stem_UTF_8_romanian.cpp.
const symbol s_4_59[5] = { 's', 'e', 's', 'e', 'm' } [static]
Definition at line 369 of file stem_UTF_8_romanian.cpp.
const symbol s_4_6[3] = { 'a', 'r', 'e' } [static]
Definition at line 316 of file stem_UTF_8_romanian.cpp.
const symbol s_4_60[4] = { 'i', 's', 'e', 'm' } [static]
Definition at line 370 of file stem_UTF_8_romanian.cpp.
const symbol s_4_61[4] = { 'u', 's', 'e', 'm' } [static]
Definition at line 371 of file stem_UTF_8_romanian.cpp.
const symbol s_4_62[5] = { 0xC3, 0xA2, 's', 'e', 'm' } [static]
Definition at line 372 of file stem_UTF_8_romanian.cpp.
const symbol s_4_63[2] = { 'i', 'm' } [static]
Definition at line 373 of file stem_UTF_8_romanian.cpp.
const symbol s_4_64[3] = { 0xC4, 0x83, 'm' } [static]
Definition at line 374 of file stem_UTF_8_romanian.cpp.
const symbol s_4_65[5] = { 'a', 'r', 0xC4, 0x83, 'm' } [static]
Definition at line 375 of file stem_UTF_8_romanian.cpp.
const symbol s_4_66[6] = { 's', 'e', 'r', 0xC4, 0x83, 'm' } [static]
Definition at line 376 of file stem_UTF_8_romanian.cpp.
const symbol s_4_67[7] = { 'a', 's', 'e', 'r', 0xC4, 0x83, 'm' } [static]
Definition at line 377 of file stem_UTF_8_romanian.cpp.
const symbol s_4_68[8] = { 's', 'e', 's', 'e', 'r', 0xC4, 0x83, 'm' } [static]
Definition at line 378 of file stem_UTF_8_romanian.cpp.
const symbol s_4_69[7] = { 'i', 's', 'e', 'r', 0xC4, 0x83, 'm' } [static]
Definition at line 379 of file stem_UTF_8_romanian.cpp.
const symbol s_4_7[3] = { 'e', 'r', 'e' } [static]
Definition at line 317 of file stem_UTF_8_romanian.cpp.
const symbol s_4_70[7] = { 'u', 's', 'e', 'r', 0xC4, 0x83, 'm' } [static]
Definition at line 380 of file stem_UTF_8_romanian.cpp.
const symbol s_4_71[8] = { 0xC3, 0xA2, 's', 'e', 'r', 0xC4, 0x83, 'm' } [static]
Definition at line 381 of file stem_UTF_8_romanian.cpp.
const symbol s_4_72[5] = { 'i', 'r', 0xC4, 0x83, 'm' } [static]
Definition at line 382 of file stem_UTF_8_romanian.cpp.
const symbol s_4_73[5] = { 'u', 'r', 0xC4, 0x83, 'm' } [static]
Definition at line 383 of file stem_UTF_8_romanian.cpp.
const symbol s_4_74[6] = { 0xC3, 0xA2, 'r', 0xC4, 0x83, 'm' } [static]
Definition at line 384 of file stem_UTF_8_romanian.cpp.
const symbol s_4_75[3] = { 0xC3, 0xA2, 'm' } [static]
Definition at line 385 of file stem_UTF_8_romanian.cpp.
const symbol s_4_76[2] = { 'a', 'u' } [static]
Definition at line 386 of file stem_UTF_8_romanian.cpp.
const symbol s_4_77[3] = { 'e', 'a', 'u' } [static]
Definition at line 387 of file stem_UTF_8_romanian.cpp.
const symbol s_4_78[3] = { 'i', 'a', 'u' } [static]
Definition at line 388 of file stem_UTF_8_romanian.cpp.
const symbol s_4_79[4] = { 'i', 'n', 'd', 'u' } [static]
Definition at line 389 of file stem_UTF_8_romanian.cpp.
const symbol s_4_8[3] = { 'i', 'r', 'e' } [static]
Definition at line 318 of file stem_UTF_8_romanian.cpp.
const symbol s_4_80[5] = { 0xC3, 0xA2, 'n', 'd', 'u' } [static]
Definition at line 390 of file stem_UTF_8_romanian.cpp.
const symbol s_4_81[2] = { 'e', 'z' } [static]
Definition at line 391 of file stem_UTF_8_romanian.cpp.
const symbol s_4_82[6] = { 'e', 'a', 's', 'c', 0xC4, 0x83 } [static]
Definition at line 392 of file stem_UTF_8_romanian.cpp.
const symbol s_4_83[4] = { 'a', 'r', 0xC4, 0x83 } [static]
Definition at line 393 of file stem_UTF_8_romanian.cpp.
const symbol s_4_84[5] = { 's', 'e', 'r', 0xC4, 0x83 } [static]
Definition at line 394 of file stem_UTF_8_romanian.cpp.
const symbol s_4_85[6] = { 'a', 's', 'e', 'r', 0xC4, 0x83 } [static]
Definition at line 395 of file stem_UTF_8_romanian.cpp.
const symbol s_4_86[7] = { 's', 'e', 's', 'e', 'r', 0xC4, 0x83 } [static]
Definition at line 396 of file stem_UTF_8_romanian.cpp.
const symbol s_4_87[6] = { 'i', 's', 'e', 'r', 0xC4, 0x83 } [static]
Definition at line 397 of file stem_UTF_8_romanian.cpp.
const symbol s_4_88[6] = { 'u', 's', 'e', 'r', 0xC4, 0x83 } [static]
Definition at line 398 of file stem_UTF_8_romanian.cpp.
const symbol s_4_89[7] = { 0xC3, 0xA2, 's', 'e', 'r', 0xC4, 0x83 } [static]
Definition at line 399 of file stem_UTF_8_romanian.cpp.
const symbol s_4_9[4] = { 0xC3, 0xA2, 'r', 'e' } [static]
Definition at line 319 of file stem_UTF_8_romanian.cpp.
const symbol s_4_90[4] = { 'i', 'r', 0xC4, 0x83 } [static]
Definition at line 400 of file stem_UTF_8_romanian.cpp.
const symbol s_4_91[4] = { 'u', 'r', 0xC4, 0x83 } [static]
Definition at line 401 of file stem_UTF_8_romanian.cpp.
const symbol s_4_92[5] = { 0xC3, 0xA2, 'r', 0xC4, 0x83 } [static]
Definition at line 402 of file stem_UTF_8_romanian.cpp.
const symbol s_4_93[5] = { 'e', 'a', 'z', 0xC4, 0x83 } [static]
Definition at line 403 of file stem_UTF_8_romanian.cpp.
const symbol s_5[] = { 'u' } [static]
Definition at line 525 of file stem_UTF_8_romanian.cpp.
const symbol s_5_0[1] = { 'a' } [static]
Definition at line 503 of file stem_UTF_8_romanian.cpp.
const symbol s_5_1[1] = { 'e' } [static]
Definition at line 504 of file stem_UTF_8_romanian.cpp.
const symbol s_5_2[2] = { 'i', 'e' } [static]
Definition at line 505 of file stem_UTF_8_romanian.cpp.
const symbol s_5_3[1] = { 'i' } [static]
Definition at line 506 of file stem_UTF_8_romanian.cpp.
const symbol s_5_4[2] = { 0xC4, 0x83 } [static]
Definition at line 507 of file stem_UTF_8_romanian.cpp.
const symbol s_6[] = { 'a' } [static]
Definition at line 526 of file stem_UTF_8_romanian.cpp.
const symbol s_7[] = { 'e' } [static]
Definition at line 527 of file stem_UTF_8_romanian.cpp.
const symbol s_8[] = { 'i' } [static]
Definition at line 528 of file stem_UTF_8_romanian.cpp.
const symbol s_9[] = { 'a', 'b' } [static]
Definition at line 529 of file stem_UTF_8_romanian.cpp.