/disk/workspace-cpp/la-manager/include/stem/stem_UTF_8_russian.h File Reference
Functions
struct SN_env * russian_UTF_8_create_env (void)
void russian_UTF_8_close_env (struct SN_env *z)
int russian_UTF_8_stem (struct SN_env *z)
Function Documentation
void russian_UTF_8_close_env (struct SN_env * z)
Definition at line 694 of file stem_UTF_8_russian.cpp.
References SN_close_env().
struct SN_env * russian_UTF_8_create_env (void) [read]
Definition at line 692 of file stem_UTF_8_russian.cpp.
References SN_create_env().
int russian_UTF_8_stem (struct SN_env * z)
Definition at line 599 of file stem_UTF_8_russian.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), SN_env::I, SN_env::ket, SN_env::l, SN_env::lb, r_adjectival(), r_derivational(), r_mark_regions(), r_noun(), r_perfective_gerund(), r_reflexive(), r_tidy_up(), r_verb(), s_9, and slice_del().