/disk/workspace-cpp/la-manager/source/stem/stem_UTF_8_dutch.cpp File Reference
#include <stem/header.h>
Functions
int dutch_UTF_8_stem (struct SN_env *z)
static int r_standard_suffix (struct SN_env *z)
static int r_undouble (struct SN_env *z)
static int r_R2 (struct SN_env *z)
static int r_R1 (struct SN_env *z)
static int r_mark_regions (struct SN_env *z)
static int r_en_ending (struct SN_env *z)
static int r_e_ending (struct SN_env *z)
static int r_postlude (struct SN_env *z)
static int r_prelude (struct SN_env *z)
struct SN_env * dutch_UTF_8_create_env (void)
void dutch_UTF_8_close_env (struct SN_env *z)
Variables
static const symbol s_0_1 [2] = { 0xC3, 0xA1 }
static const symbol s_0_2 [2] = { 0xC3, 0xA4 }
static const symbol s_0_3 [2] = { 0xC3, 0xA9 }
static const symbol s_0_4 [2] = { 0xC3, 0xAB }
static const symbol s_0_5 [2] = { 0xC3, 0xAD }
static const symbol s_0_6 [2] = { 0xC3, 0xAF }
static const symbol s_0_7 [2] = { 0xC3, 0xB3 }
static const symbol s_0_8 [2] = { 0xC3, 0xB6 }
static const symbol s_0_9 [2] = { 0xC3, 0xBA }
static const symbol s_0_10 [2] = { 0xC3, 0xBC }
static struct among a_0 [11]
static const symbol s_1_1 [1] = { 'I' }
static const symbol s_1_2 [1] = { 'Y' }
static struct among a_1 [3]
static const symbol s_2_0 [2] = { 'd', 'd' }
static const symbol s_2_1 [2] = { 'k', 'k' }
static const symbol s_2_2 [2] = { 't', 't' }
static struct among a_2 [3]
static const symbol s_3_0 [3] = { 'e', 'n', 'e' }
static const symbol s_3_1 [2] = { 's', 'e' }
static const symbol s_3_2 [2] = { 'e', 'n' }
static const symbol s_3_3 [5] = { 'h', 'e', 'd', 'e', 'n' }
static const symbol s_3_4 [1] = { 's' }
static struct among a_3 [5]
static const symbol s_4_0 [3] = { 'e', 'n', 'd' }
static const symbol s_4_1 [2] = { 'i', 'g' }
static const symbol s_4_2 [3] = { 'i', 'n', 'g' }
static const symbol s_4_3 [4] = { 'l', 'i', 'j', 'k' }
static const symbol s_4_4 [4] = { 'b', 'a', 'a', 'r' }
static const symbol s_4_5 [3] = { 'b', 'a', 'r' }
static struct among a_4 [6]
static const symbol s_5_0 [2] = { 'a', 'a' }
static const symbol s_5_1 [2] = { 'e', 'e' }
static const symbol s_5_2 [2] = { 'o', 'o' }
static const symbol s_5_3 [2] = { 'u', 'u' }
static struct among a_5 [4]
static const unsigned char g_v [] = { 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128 }
static const unsigned char g_v_I [] = { 1, 0, 0, 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128 }
static const unsigned char g_v_j [] = { 17, 67, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128 }
static const symbol s_0 [] = { 'a' }
static const symbol s_1 [] = { 'e' }
static const symbol s_2 [] = { 'i' }
static const symbol s_3 [] = { 'o' }
static const symbol s_4 [] = { 'u' }
static const symbol s_5 [] = { 'y' }
static const symbol s_6 [] = { 'Y' }
static const symbol s_7 [] = { 'i' }
static const symbol s_8 [] = { 'I' }
static const symbol s_9 [] = { 'y' }
static const symbol s_10 [] = { 'Y' }
static const symbol s_11 [] = { 'y' }
static const symbol s_12 [] = { 'i' }
static const symbol s_13 [] = { 'e' }
static const symbol s_14 [] = { 'g', 'e', 'm' }
static const symbol s_15 [] = { 'h', 'e', 'i', 'd' }
static const symbol s_16 [] = { 'h', 'e', 'i', 'd' }
static const symbol s_17 [] = { 'c' }
static const symbol s_18 [] = { 'e', 'n' }
static const symbol s_19 [] = { 'i', 'g' }
static const symbol s_20 [] = { 'e' }
static const symbol s_21 [] = { 'e' }
Function Documentation
void dutch_UTF_8_close_env (struct SN_env * z)
struct SN_env* dutch_UTF_8_create_env (void) [read]
int dutch_UTF_8_stem (struct SN_env * z)
static int r_e_ending (struct SN_env * z) [static]
Definition at line 353 of file stem_UTF_8_dutch.cpp.
References SN_env::B, SN_env::bra, SN_env::c, eq_s_b(), g_v, SN_env::ket, SN_env::l, out_grouping_b_U(), r_R1(), r_undouble(), s_13, and slice_del().
Referenced by r_standard_suffix().
static int r_en_ending (struct SN_env * z) [static]
Definition at line 377 of file stem_UTF_8_dutch.cpp.
References SN_env::c, eq_s_b(), g_v, SN_env::l, out_grouping_b_U(), r_R1(), r_undouble(), s_14, and slice_del().
Referenced by r_standard_suffix().
static int r_mark_regions (struct SN_env * z) [static]
Definition at line 257 of file stem_UTF_8_dutch.cpp.
References SN_env::c, g_v, SN_env::I, in_grouping_U(), SN_env::l, and out_grouping_U().
static int r_postlude (struct SN_env * z) [static]
Definition at line 289 of file stem_UTF_8_dutch.cpp.
References SN_env::bra, SN_env::c, find_among(), SN_env::ket, SN_env::l, SN_env::p, s_11, s_12, skip_utf8(), and slice_from_s().
Referenced by dutch_UTF_8_stem(), english_UTF_8_stem(), french_UTF_8_stem(), german_UTF_8_stem(), italian_UTF_8_stem(), portuguese_UTF_8_stem(), romanian_UTF_8_stem(), spanish_UTF_8_stem(), and turkish_UTF_8_stem().
static int r_prelude (struct SN_env * z) [static]
Definition at line 156 of file stem_UTF_8_dutch.cpp.
References SN_env::bra, SN_env::c, eq_s(), find_among(), g_v, in_grouping_U(), SN_env::ket, SN_env::l, SN_env::p, s_0, s_1, s_10, s_2, s_3, s_4, s_5, s_6, s_7, s_8, s_9, skip_utf8(), and slice_from_s().
Referenced by dutch_UTF_8_stem(), english_UTF_8_stem(), french_UTF_8_stem(), german_UTF_8_stem(), italian_UTF_8_stem(), portuguese_UTF_8_stem(), and romanian_UTF_8_stem().
static int r_R1 (struct SN_env * z) [static]
Definition at line 325 of file stem_UTF_8_dutch.cpp.
References SN_env::c, and SN_env::I.
Referenced by r_case(), r_case_other(), r_case_special(), r_combo_suffix(), r_e_ending(), r_en_ending(), r_factive(), r_instrum(), r_owned(), r_plur_owner(), r_plural(), r_sing_owner(), r_standard_suffix(), r_step_0(), r_Step_1b(), r_Step_2(), r_Step_3(), r_Step_5(), and r_v_ending().
static int r_R2 (struct SN_env * z) [static]
Definition at line 330 of file stem_UTF_8_dutch.cpp.
References SN_env::c, and SN_env::I.
Referenced by r_derivational(), r_particle_etc(), r_residual_suffix(), r_standard_suffix(), r_Step_3(), r_Step_4(), r_Step_5(), and r_verb_suffix().
static int r_standard_suffix (struct SN_env * z) [static]
Definition at line 402 of file stem_UTF_8_dutch.cpp.
References SN_env::B, SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), g_v, g_v_I, g_v_j, SN_env::ket, SN_env::l, SN_env::lb, out_grouping_b_U(), SN_env::p, r_e_ending(), r_en_ending(), r_R1(), r_R2(), r_undouble(), s_15, s_16, s_17, s_18, s_19, s_20, s_21, skip_utf8(), slice_del(), and slice_from_s().
Referenced by dutch_UTF_8_stem(), french_UTF_8_stem(), german_UTF_8_stem(), italian_UTF_8_stem(), portuguese_UTF_8_stem(), romanian_UTF_8_stem(), and spanish_UTF_8_stem().
static int r_undouble (struct SN_env * z) [static]
Definition at line 335 of file stem_UTF_8_dutch.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::ket, SN_env::l, SN_env::lb, SN_env::p, skip_utf8(), and slice_del().
Variable Documentation
struct among a_0[11] [static]
Initial value:
{
 { 0, 0, -1, 6, 0},
 { 2, s_0_1, 0, 1, 0},
 { 2, s_0_2, 0, 1, 0},
 { 2, s_0_3, 0, 2, 0},
 { 2, s_0_4, 0, 2, 0},
 { 2, s_0_5, 0, 3, 0},
 { 2, s_0_6, 0, 3, 0},
 { 2, s_0_7, 0, 4, 0},
 { 2, s_0_8, 0, 4, 0},
 { 2, s_0_9, 0, 5, 0},
 { 2, s_0_10, 0, 5, 0}
}
Definition at line 46 of file stem_UTF_8_dutch.cpp.
struct among a_1[3] [static]
Initial value:
{
 { 0, 0, -1, 3, 0},
 { 1, s_1_1, 0, 2, 0},
 { 1, s_1_2, 0, 1, 0}
}
Definition at line 64 of file stem_UTF_8_dutch.cpp.
struct among a_2[3] [static]
Initial value:
{
 { 2, s_2_0, -1, -1, 0},
 { 2, s_2_1, -1, -1, 0},
 { 2, s_2_2, -1, -1, 0}
}
Definition at line 75 of file stem_UTF_8_dutch.cpp.
struct among a_3[5] [static]
Initial value:
{
 { 3, s_3_0, -1, 2, 0},
 { 2, s_3_1, -1, 3, 0},
 { 2, s_3_2, -1, 2, 0},
 { 5, s_3_3, 2, 1, 0},
 { 1, s_3_4, -1, 3, 0}
}
Definition at line 88 of file stem_UTF_8_dutch.cpp.
struct among a_4[6] [static]
Initial value:
{
 { 3, s_4_0, -1, 1, 0},
 { 2, s_4_1, -1, 2, 0},
 { 3, s_4_2, -1, 1, 0},
 { 4, s_4_3, -1, 3, 0},
 { 4, s_4_4, -1, 4, 0},
 { 3, s_4_5, -1, 5, 0}
}
Definition at line 104 of file stem_UTF_8_dutch.cpp.
struct among a_5[4] [static]
Initial value:
{
 { 2, s_5_0, -1, -1, 0},
 { 2, s_5_1, -1, -1, 0},
 { 2, s_5_2, -1, -1, 0},
 { 2, s_5_3, -1, -1, 0}
}
Definition at line 119 of file stem_UTF_8_dutch.cpp.
const unsigned char g_v[] = { 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128 } [static]
Definition at line 127 of file stem_UTF_8_dutch.cpp.
const unsigned char g_v_I[] = { 1, 0, 0, 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128 } [static]
Definition at line 129 of file stem_UTF_8_dutch.cpp.
Referenced by r_standard_suffix().
const unsigned char g_v_j[] = { 17, 67, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128 } [static]
Definition at line 131 of file stem_UTF_8_dutch.cpp.
Referenced by r_standard_suffix().
const symbol s_0[] = { 'a' } [static]
Definition at line 133 of file stem_UTF_8_dutch.cpp.
const symbol s_0_1[2] = { 0xC3, 0xA1 } [static]
Definition at line 35 of file stem_UTF_8_dutch.cpp.
const symbol s_0_10[2] = { 0xC3, 0xBC } [static]
Definition at line 44 of file stem_UTF_8_dutch.cpp.
const symbol s_0_2[2] = { 0xC3, 0xA4 } [static]
Definition at line 36 of file stem_UTF_8_dutch.cpp.
const symbol s_0_3[2] = { 0xC3, 0xA9 } [static]
Definition at line 37 of file stem_UTF_8_dutch.cpp.
const symbol s_0_4[2] = { 0xC3, 0xAB } [static]
Definition at line 38 of file stem_UTF_8_dutch.cpp.
const symbol s_0_5[2] = { 0xC3, 0xAD } [static]
Definition at line 39 of file stem_UTF_8_dutch.cpp.
const symbol s_0_6[2] = { 0xC3, 0xAF } [static]
Definition at line 40 of file stem_UTF_8_dutch.cpp.
const symbol s_0_7[2] = { 0xC3, 0xB3 } [static]
Definition at line 41 of file stem_UTF_8_dutch.cpp.
const symbol s_0_8[2] = { 0xC3, 0xB6 } [static]
Definition at line 42 of file stem_UTF_8_dutch.cpp.
const symbol s_0_9[2] = { 0xC3, 0xBA } [static]
Definition at line 43 of file stem_UTF_8_dutch.cpp.
const symbol s_1[] = { 'e' } [static]
Definition at line 134 of file stem_UTF_8_dutch.cpp.
const symbol s_10[] = { 'Y' } [static]
Definition at line 143 of file stem_UTF_8_dutch.cpp.
Referenced by r_attached_pronoun(), r_case_ending(), r_mark_suffix_with_optional_s_consonant(), r_owned(), r_postlude(), r_prelude(), r_standard_suffix(), r_step_0(), and r_Step_1b().
const symbol s_11[] = { 'y' } [static]
Definition at line 144 of file stem_UTF_8_dutch.cpp.
Referenced by r_case_ending(), r_mark_suffix_with_optional_s_consonant(), r_owned(), r_postlude(), r_residual_form(), r_standard_suffix(), r_step_0(), and r_Step_1c().
const symbol s_12[] = { 'i' } [static]
Definition at line 145 of file stem_UTF_8_dutch.cpp.
Referenced by r_attached_pronoun(), r_mark_suffix_with_optional_y_consonant(), r_other_endings(), r_owned(), r_postlude(), r_residual_form(), r_standard_suffix(), r_step_0(), and r_Step_1c().
const symbol s_13[] = { 'e' } [static]
Definition at line 146 of file stem_UTF_8_dutch.cpp.
Referenced by r_combo_suffix(), r_e_ending(), r_mark_suffix_with_optional_y_consonant(), r_owned(), r_postlude(), r_residual_form(), r_standard_suffix(), r_Step_1c(), and r_t_plural().
const symbol s_14[] = { 'g', 'e', 'm' } [static]
Definition at line 147 of file stem_UTF_8_dutch.cpp.
Referenced by r_combo_suffix(), r_en_ending(), r_mark_ki(), r_residual_form(), r_sing_owner(), r_standard_suffix(), r_Step_2(), and r_t_plural().
const symbol s_15[] = { 'h', 'e', 'i', 'd' } [static]
Definition at line 148 of file stem_UTF_8_dutch.cpp.
Referenced by r_combo_suffix(), r_mark_yken(), r_residual_form(), r_sing_owner(), r_standard_suffix(), r_Step_2(), and r_tidy().
const symbol s_16[] = { 'h', 'e', 'i', 'd' } [static]
Definition at line 149 of file stem_UTF_8_dutch.cpp.
Referenced by portuguese_UTF_8_stem(), r_combo_suffix(), r_post_process_last_consonants(), r_sing_owner(), r_standard_suffix(), r_Step_2(), and r_tidy().
const symbol s_17[] = { 'c' } [static]
Definition at line 150 of file stem_UTF_8_dutch.cpp.
Referenced by portuguese_UTF_8_stem(), r_combo_suffix(), r_post_process_last_consonants(), r_sing_owner(), r_standard_suffix(), r_Step_2(), r_tidy(), and r_y_verb_suffix().
const symbol s_18[] = { 'e', 'n' } [static]
Definition at line 151 of file stem_UTF_8_dutch.cpp.
Referenced by r_combo_suffix(), r_post_process_last_consonants(), r_sing_owner(), r_standard_suffix(), r_Step_2(), r_tidy(), and r_verb_suffix().
const symbol s_19[] = { 'i', 'g' } [static]
Definition at line 152 of file stem_UTF_8_dutch.cpp.
Referenced by r_post_process_last_consonants(), r_sing_owner(), r_standard_suffix(), r_Step_2(), r_tidy(), and r_verb_suffix().
const symbol s_1_1[1] = { 'I' } [static]
Definition at line 61 of file stem_UTF_8_dutch.cpp.
const symbol s_1_2[1] = { 'Y' } [static]
Definition at line 62 of file stem_UTF_8_dutch.cpp.
const symbol s_2[] = { 'i' } [static]
Definition at line 135 of file stem_UTF_8_dutch.cpp.
const symbol s_20[] = { 'e' } [static]
Definition at line 153 of file stem_UTF_8_dutch.cpp.
Referenced by r_append_U_to_stems_ending_with_d_or_g(), r_residual_suffix(), r_sing_owner(), r_standard_suffix(), r_Step_2(), and r_vowel_suffix().
const symbol s_21[] = { 'e' } [static]
Definition at line 154 of file stem_UTF_8_dutch.cpp.
Referenced by r_append_U_to_stems_ending_with_d_or_g(), r_residual_suffix(), r_sing_owner(), r_standard_suffix(), r_Step_2(), and r_vowel_suffix().
const symbol s_2_0[2] = { 'd', 'd' } [static]
Definition at line 71 of file stem_UTF_8_dutch.cpp.
const symbol s_2_1[2] = { 'k', 'k' } [static]
Definition at line 72 of file stem_UTF_8_dutch.cpp.
const symbol s_2_2[2] = { 't', 't' } [static]
Definition at line 73 of file stem_UTF_8_dutch.cpp.
const symbol s_3[] = { 'o' } [static]
Definition at line 136 of file stem_UTF_8_dutch.cpp.
Referenced by r_adjectival(), r_case_special(), r_check_vowel_harmony(), r_postlude(), r_prelude(), and r_VI().
const symbol s_3_0[3] = { 'e', 'n', 'e' } [static]
Definition at line 82 of file stem_UTF_8_dutch.cpp.
const symbol s_3_1[2] = { 's', 'e' } [static]
Definition at line 83 of file stem_UTF_8_dutch.cpp.
const symbol s_3_2[2] = { 'e', 'n' } [static]
Definition at line 84 of file stem_UTF_8_dutch.cpp.
const symbol s_3_3[5] = { 'h', 'e', 'd', 'e', 'n' } [static]
Definition at line 85 of file stem_UTF_8_dutch.cpp.
const symbol s_3_4[1] = { 's' } [static]
Definition at line 86 of file stem_UTF_8_dutch.cpp.
const symbol s_4[] = { 'u' } [static]
Definition at line 137 of file stem_UTF_8_dutch.cpp.
Referenced by r_case_ending(), r_case_special(), r_check_vowel_harmony(), r_postlude(), r_prelude(), r_standard_suffix(), and r_verb().
const symbol s_4_0[3] = { 'e', 'n', 'd' } [static]
Definition at line 97 of file stem_UTF_8_dutch.cpp.
const symbol s_4_1[2] = { 'i', 'g' } [static]
Definition at line 98 of file stem_UTF_8_dutch.cpp.
const symbol s_4_2[3] = { 'i', 'n', 'g' } [static]
Definition at line 99 of file stem_UTF_8_dutch.cpp.
const symbol s_4_3[4] = { 'l', 'i', 'j', 'k' } [static]
Definition at line 100 of file stem_UTF_8_dutch.cpp.
const symbol s_4_4[4] = { 'b', 'a', 'a', 'r' } [static]
Definition at line 101 of file stem_UTF_8_dutch.cpp.
const symbol s_4_5[3] = { 'b', 'a', 'r' } [static]
Definition at line 102 of file stem_UTF_8_dutch.cpp.
const symbol s_5[] = { 'y' } [static]
Definition at line 138 of file stem_UTF_8_dutch.cpp.
Referenced by r_attached_pronoun(), r_case_ending(), r_case_other(), r_check_vowel_harmony(), r_postlude(), r_prelude(), r_standard_suffix(), r_Step_1a(), and r_verb().
const symbol s_5_0[2] = { 'a', 'a' } [static]
Definition at line 114 of file stem_UTF_8_dutch.cpp.
const symbol s_5_1[2] = { 'e', 'e' } [static]
Definition at line 115 of file stem_UTF_8_dutch.cpp.
const symbol s_5_2[2] = { 'o', 'o' } [static]
Definition at line 116 of file stem_UTF_8_dutch.cpp.
const symbol s_5_3[2] = { 'u', 'u' } [static]
Definition at line 117 of file stem_UTF_8_dutch.cpp.
const symbol s_6[] = { 'Y' } [static]
Definition at line 139 of file stem_UTF_8_dutch.cpp.
Referenced by r_attached_pronoun(), r_case_ending(), r_case_other(), r_check_vowel_harmony(), r_postlude(), r_prelude(), r_standard_suffix(), r_step_0(), r_Step_1a(), and r_tidy_up().
const symbol s_7[] = { 'i' } [static]
Definition at line 140 of file stem_UTF_8_dutch.cpp.
Referenced by r_attached_pronoun(), r_case_ending(), r_check_vowel_harmony(), r_plural(), r_postlude(), r_prelude(), r_standard_suffix(), r_step_0(), r_Step_1a(), and r_tidy_up().
const symbol s_8[] = { 'I' } [static]
Definition at line 141 of file stem_UTF_8_dutch.cpp.
Referenced by r_attached_pronoun(), r_case_ending(), r_mark_suffix_with_optional_n_consonant(), r_plural(), r_postlude(), r_prelude(), r_standard_suffix(), r_step_0(), r_Step_1b(), and r_tidy_up().
const symbol s_9[] = { 'y' } [static]
Definition at line 142 of file stem_UTF_8_dutch.cpp.
Referenced by r_attached_pronoun(), r_case_ending(), r_mark_suffix_with_optional_n_consonant(), r_owned(), r_postlude(), r_prelude(), r_standard_suffix(), r_step_0(), r_Step_1b(), and russian_UTF_8_stem().