/disk/workspace-cpp/la-manager/source/stem/stem_UTF_8_french.cpp File Reference
#include <stem/header.h>
Functions
int french_UTF_8_stem (struct SN_env *z)
static int r_un_accent (struct SN_env *z)
static int r_un_double (struct SN_env *z)
static int r_residual_suffix (struct SN_env *z)
static int r_verb_suffix (struct SN_env *z)
static int r_i_verb_suffix (struct SN_env *z)
static int r_standard_suffix (struct SN_env *z)
static int r_R2 (struct SN_env *z)
static int r_R1 (struct SN_env *z)
static int r_RV (struct SN_env *z)
static int r_mark_regions (struct SN_env *z)
static int r_postlude (struct SN_env *z)
static int r_prelude (struct SN_env *z)
struct SN_env * french_UTF_8_create_env (void)
void french_UTF_8_close_env (struct SN_env *z)
Variables
static const symbol s_0_0 [3] = { 'c', 'o', 'l' }
static const symbol s_0_1 [3] = { 'p', 'a', 'r' }
static const symbol s_0_2 [3] = { 't', 'a', 'p' }
static struct among a_0 [3]
static const symbol s_1_1 [1] = { 'I' }
static const symbol s_1_2 [1] = { 'U' }
static const symbol s_1_3 [1] = { 'Y' }
static struct among a_1 [4]
static const symbol s_2_0 [3] = { 'i', 'q', 'U' }
static const symbol s_2_1 [3] = { 'a', 'b', 'l' }
static const symbol s_2_2 [4] = { 'I', 0xC3, 0xA8, 'r' }
static const symbol s_2_3 [4] = { 'i', 0xC3, 0xA8, 'r' }
static const symbol s_2_4 [3] = { 'e', 'u', 's' }
static const symbol s_2_5 [2] = { 'i', 'v' }
static struct among a_2 [6]
static const symbol s_3_0 [2] = { 'i', 'c' }
static const symbol s_3_1 [4] = { 'a', 'b', 'i', 'l' }
static const symbol s_3_2 [2] = { 'i', 'v' }
static struct among a_3 [3]
static const symbol s_4_0 [4] = { 'i', 'q', 'U', 'e' }
static const symbol s_4_1 [6] = { 'a', 't', 'r', 'i', 'c', 'e' }
static const symbol s_4_2 [4] = { 'a', 'n', 'c', 'e' }
static const symbol s_4_3 [4] = { 'e', 'n', 'c', 'e' }
static const symbol s_4_4 [5] = { 'l', 'o', 'g', 'i', 'e' }
static const symbol s_4_5 [4] = { 'a', 'b', 'l', 'e' }
static const symbol s_4_6 [4] = { 'i', 's', 'm', 'e' }
static const symbol s_4_7 [4] = { 'e', 'u', 's', 'e' }
static const symbol s_4_8 [4] = { 'i', 's', 't', 'e' }
static const symbol s_4_9 [3] = { 'i', 'v', 'e' }
static const symbol s_4_10 [2] = { 'i', 'f' }
static const symbol s_4_11 [5] = { 'u', 's', 'i', 'o', 'n' }
static const symbol s_4_12 [5] = { 'a', 't', 'i', 'o', 'n' }
static const symbol s_4_13 [5] = { 'u', 't', 'i', 'o', 'n' }
static const symbol s_4_14 [5] = { 'a', 't', 'e', 'u', 'r' }
static const symbol s_4_15 [5] = { 'i', 'q', 'U', 'e', 's' }
static const symbol s_4_16 [7] = { 'a', 't', 'r', 'i', 'c', 'e', 's' }
static const symbol s_4_17 [5] = { 'a', 'n', 'c', 'e', 's' }
static const symbol s_4_18 [5] = { 'e', 'n', 'c', 'e', 's' }
static const symbol s_4_19 [6] = { 'l', 'o', 'g', 'i', 'e', 's' }
static const symbol s_4_20 [5] = { 'a', 'b', 'l', 'e', 's' }
static const symbol s_4_21 [5] = { 'i', 's', 'm', 'e', 's' }
static const symbol s_4_22 [5] = { 'e', 'u', 's', 'e', 's' }
static const symbol s_4_23 [5] = { 'i', 's', 't', 'e', 's' }
static const symbol s_4_24 [4] = { 'i', 'v', 'e', 's' }
static const symbol s_4_25 [3] = { 'i', 'f', 's' }
static const symbol s_4_26 [6] = { 'u', 's', 'i', 'o', 'n', 's' }
static const symbol s_4_27 [6] = { 'a', 't', 'i', 'o', 'n', 's' }
static const symbol s_4_28 [6] = { 'u', 't', 'i', 'o', 'n', 's' }
static const symbol s_4_29 [6] = { 'a', 't', 'e', 'u', 'r', 's' }
static const symbol s_4_30 [5] = { 'm', 'e', 'n', 't', 's' }
static const symbol s_4_31 [6] = { 'e', 'm', 'e', 'n', 't', 's' }
static const symbol s_4_32 [9] = { 'i', 's', 's', 'e', 'm', 'e', 'n', 't', 's' }
static const symbol s_4_33 [5] = { 'i', 't', 0xC3, 0xA9, 's' }
static const symbol s_4_34 [4] = { 'm', 'e', 'n', 't' }
static const symbol s_4_35 [5] = { 'e', 'm', 'e', 'n', 't' }
static const symbol s_4_36 [8] = { 'i', 's', 's', 'e', 'm', 'e', 'n', 't' }
static const symbol s_4_37 [6] = { 'a', 'm', 'm', 'e', 'n', 't' }
static const symbol s_4_38 [6] = { 'e', 'm', 'm', 'e', 'n', 't' }
static const symbol s_4_39 [3] = { 'a', 'u', 'x' }
static const symbol s_4_40 [4] = { 'e', 'a', 'u', 'x' }
static const symbol s_4_41 [3] = { 'e', 'u', 'x' }
static const symbol s_4_42 [4] = { 'i', 't', 0xC3, 0xA9 }
static struct among a_4 [43]
static const symbol s_5_0 [3] = { 'i', 'r', 'a' }
static const symbol s_5_1 [2] = { 'i', 'e' }
static const symbol s_5_2 [4] = { 'i', 's', 's', 'e' }
static const symbol s_5_3 [7] = { 'i', 's', 's', 'a', 'n', 't', 'e' }
static const symbol s_5_4 [1] = { 'i' }
static const symbol s_5_5 [4] = { 'i', 'r', 'a', 'i' }
static const symbol s_5_6 [2] = { 'i', 'r' }
static const symbol s_5_7 [4] = { 'i', 'r', 'a', 's' }
static const symbol s_5_8 [3] = { 'i', 'e', 's' }
static const symbol s_5_9 [5] = { 0xC3, 0xAE, 'm', 'e', 's' }
static const symbol s_5_10 [5] = { 'i', 's', 's', 'e', 's' }
static const symbol s_5_11 [8] = { 'i', 's', 's', 'a', 'n', 't', 'e', 's' }
static const symbol s_5_12 [5] = { 0xC3, 0xAE, 't', 'e', 's' }
static const symbol s_5_13 [2] = { 'i', 's' }
static const symbol s_5_14 [5] = { 'i', 'r', 'a', 'i', 's' }
static const symbol s_5_15 [6] = { 'i', 's', 's', 'a', 'i', 's' }
static const symbol s_5_16 [6] = { 'i', 'r', 'i', 'o', 'n', 's' }
static const symbol s_5_17 [7] = { 'i', 's', 's', 'i', 'o', 'n', 's' }
static const symbol s_5_18 [5] = { 'i', 'r', 'o', 'n', 's' }
static const symbol s_5_19 [6] = { 'i', 's', 's', 'o', 'n', 's' }
static const symbol s_5_20 [7] = { 'i', 's', 's', 'a', 'n', 't', 's' }
static const symbol s_5_21 [2] = { 'i', 't' }
static const symbol s_5_22 [5] = { 'i', 'r', 'a', 'i', 't' }
static const symbol s_5_23 [6] = { 'i', 's', 's', 'a', 'i', 't' }
static const symbol s_5_24 [6] = { 'i', 's', 's', 'a', 'n', 't' }
static const symbol s_5_25 [7] = { 'i', 'r', 'a', 'I', 'e', 'n', 't' }
static const symbol s_5_26 [8] = { 'i', 's', 's', 'a', 'I', 'e', 'n', 't' }
static const symbol s_5_27 [5] = { 'i', 'r', 'e', 'n', 't' }
static const symbol s_5_28 [6] = { 'i', 's', 's', 'e', 'n', 't' }
static const symbol s_5_29 [5] = { 'i', 'r', 'o', 'n', 't' }
static const symbol s_5_30 [3] = { 0xC3, 0xAE, 't' }
static const symbol s_5_31 [5] = { 'i', 'r', 'i', 'e', 'z' }
static const symbol s_5_32 [6] = { 'i', 's', 's', 'i', 'e', 'z' }
static const symbol s_5_33 [4] = { 'i', 'r', 'e', 'z' }
static const symbol s_5_34 [5] = { 'i', 's', 's', 'e', 'z' }
static struct among a_5 [35]
static const symbol s_6_0 [1] = { 'a' }
static const symbol s_6_1 [3] = { 'e', 'r', 'a' }
static const symbol s_6_2 [4] = { 'a', 's', 's', 'e' }
static const symbol s_6_3 [4] = { 'a', 'n', 't', 'e' }
static const symbol s_6_4 [3] = { 0xC3, 0xA9, 'e' }
static const symbol s_6_5 [2] = { 'a', 'i' }
static const symbol s_6_6 [4] = { 'e', 'r', 'a', 'i' }
static const symbol s_6_7 [2] = { 'e', 'r' }
static const symbol s_6_8 [2] = { 'a', 's' }
static const symbol s_6_9 [4] = { 'e', 'r', 'a', 's' }
static const symbol s_6_10 [5] = { 0xC3, 0xA2, 'm', 'e', 's' }
static const symbol s_6_11 [5] = { 'a', 's', 's', 'e', 's' }
static const symbol s_6_12 [5] = { 'a', 'n', 't', 'e', 's' }
static const symbol s_6_13 [5] = { 0xC3, 0xA2, 't', 'e', 's' }
static const symbol s_6_14 [4] = { 0xC3, 0xA9, 'e', 's' }
static const symbol s_6_15 [3] = { 'a', 'i', 's' }
static const symbol s_6_16 [5] = { 'e', 'r', 'a', 'i', 's' }
static const symbol s_6_17 [4] = { 'i', 'o', 'n', 's' }
static const symbol s_6_18 [6] = { 'e', 'r', 'i', 'o', 'n', 's' }
static const symbol s_6_19 [7] = { 'a', 's', 's', 'i', 'o', 'n', 's' }
static const symbol s_6_20 [5] = { 'e', 'r', 'o', 'n', 's' }
static const symbol s_6_21 [4] = { 'a', 'n', 't', 's' }
static const symbol s_6_22 [3] = { 0xC3, 0xA9, 's' }
static const symbol s_6_23 [3] = { 'a', 'i', 't' }
static const symbol s_6_24 [5] = { 'e', 'r', 'a', 'i', 't' }
static const symbol s_6_25 [3] = { 'a', 'n', 't' }
static const symbol s_6_26 [5] = { 'a', 'I', 'e', 'n', 't' }
static const symbol s_6_27 [7] = { 'e', 'r', 'a', 'I', 'e', 'n', 't' }
static const symbol s_6_28 [6] = { 0xC3, 0xA8, 'r', 'e', 'n', 't' }
static const symbol s_6_29 [6] = { 'a', 's', 's', 'e', 'n', 't' }
static const symbol s_6_30 [5] = { 'e', 'r', 'o', 'n', 't' }
static const symbol s_6_31 [3] = { 0xC3, 0xA2, 't' }
static const symbol s_6_32 [2] = { 'e', 'z' }
static const symbol s_6_33 [3] = { 'i', 'e', 'z' }
static const symbol s_6_34 [5] = { 'e', 'r', 'i', 'e', 'z' }
static const symbol s_6_35 [6] = { 'a', 's', 's', 'i', 'e', 'z' }
static const symbol s_6_36 [4] = { 'e', 'r', 'e', 'z' }
static const symbol s_6_37 [2] = { 0xC3, 0xA9 }
static struct among a_6 [38]
static const symbol s_7_0 [1] = { 'e' }
static const symbol s_7_1 [5] = { 'I', 0xC3, 0xA8, 'r', 'e' }
static const symbol s_7_2 [5] = { 'i', 0xC3, 0xA8, 'r', 'e' }
static const symbol s_7_3 [3] = { 'i', 'o', 'n' }
static const symbol s_7_4 [3] = { 'I', 'e', 'r' }
static const symbol s_7_5 [3] = { 'i', 'e', 'r' }
static const symbol s_7_6 [2] = { 0xC3, 0xAB }
static struct among a_7 [7]
static const symbol s_8_0 [3] = { 'e', 'l', 'l' }
static const symbol s_8_1 [4] = { 'e', 'i', 'l', 'l' }
static const symbol s_8_2 [3] = { 'e', 'n', 'n' }
static const symbol s_8_3 [3] = { 'o', 'n', 'n' }
static const symbol s_8_4 [3] = { 'e', 't', 't' }
static struct among a_8 [5]
static const unsigned char g_v [] = { 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 130, 103, 8, 5 }
static const unsigned char g_keep_with_s [] = { 1, 65, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128 }
static const symbol s_0 [] = { 'u' }
static const symbol s_1 [] = { 'U' }
static const symbol s_2 [] = { 'i' }
static const symbol s_3 [] = { 'I' }
static const symbol s_4 [] = { 'y' }
static const symbol s_5 [] = { 'Y' }
static const symbol s_6 [] = { 'y' }
static const symbol s_7 [] = { 'Y' }
static const symbol s_8 [] = { 'q' }
static const symbol s_9 [] = { 'u' }
static const symbol s_10 [] = { 'U' }
static const symbol s_11 [] = { 'i' }
static const symbol s_12 [] = { 'u' }
static const symbol s_13 [] = { 'y' }
static const symbol s_14 [] = { 'i', 'c' }
static const symbol s_15 [] = { 'i', 'q', 'U' }
static const symbol s_16 [] = { 'l', 'o', 'g' }
static const symbol s_17 [] = { 'u' }
static const symbol s_18 [] = { 'e', 'n', 't' }
static const symbol s_19 [] = { 'a', 't' }
static const symbol s_20 [] = { 'e', 'u', 'x' }
static const symbol s_21 [] = { 'i' }
static const symbol s_22 [] = { 'a', 'b', 'l' }
static const symbol s_23 [] = { 'i', 'q', 'U' }
static const symbol s_24 [] = { 'a', 't' }
static const symbol s_25 [] = { 'i', 'c' }
static const symbol s_26 [] = { 'i', 'q', 'U' }
static const symbol s_27 [] = { 'e', 'a', 'u' }
static const symbol s_28 [] = { 'a', 'l' }
static const symbol s_29 [] = { 'e', 'u', 'x' }
static const symbol s_30 [] = { 'a', 'n', 't' }
static const symbol s_31 [] = { 'e', 'n', 't' }
static const symbol s_32 [] = { 'e' }
static const symbol s_33 [] = { 's' }
static const symbol s_34 [] = { 's' }
static const symbol s_35 [] = { 't' }
static const symbol s_36 [] = { 'i' }
static const symbol s_37 [] = { 'g', 'u' }
static const symbol s_38 [] = { 0xC3, 0xA9 }
static const symbol s_39 [] = { 0xC3, 0xA8 }
static const symbol s_40 [] = { 'e' }
static const symbol s_41 [] = { 'Y' }
static const symbol s_42 [] = { 'i' }
static const symbol s_43 [] = { 0xC3, 0xA7 }
static const symbol s_44 [] = { 'c' }
Function Documentation
void french_UTF_8_close_env (struct SN_env * z)
struct SN_env* french_UTF_8_create_env (void) [read]
int french_UTF_8_stem (struct SN_env * z)
static int r_i_verb_suffix (struct SN_env * z) [static]
Definition at line 960 of file stem_UTF_8_french.cpp.
References SN_env::bra, SN_env::c, find_among_b(), g_v, SN_env::I, SN_env::ket, SN_env::l, SN_env::lb, out_grouping_b_U(), SN_env::p, and slice_del().
Referenced by french_UTF_8_stem().
static int r_mark_regions (struct SN_env * z) [static]
Definition at line 493 of file stem_UTF_8_french.cpp.
References SN_env::c, find_among(), g_v, SN_env::I, in_grouping_U(), SN_env::l, out_grouping_U(), SN_env::p, and skip_utf8().
static int r_postlude (struct SN_env * z) [static]
Definition at line 557 of file stem_UTF_8_french.cpp.
References SN_env::bra, SN_env::c, find_among(), SN_env::ket, SN_env::l, SN_env::p, s_11, s_12, s_13, skip_utf8(), and slice_from_s().
static int r_prelude (struct SN_env * z) [static]
Definition at line 420 of file stem_UTF_8_french.cpp.
References SN_env::bra, SN_env::c, eq_s(), g_v, in_grouping_U(), SN_env::ket, SN_env::l, SN_env::p, s_0, s_1, s_10, s_2, s_3, s_4, s_5, s_6, s_7, s_8, s_9, skip_utf8(), and slice_from_s().
static int r_R1 (struct SN_env * z) [static]
Definition at line 603 of file stem_UTF_8_french.cpp.
References SN_env::c, and SN_env::I.
static int r_R2 (struct SN_env * z) [static]
Definition at line 608 of file stem_UTF_8_french.cpp.
References SN_env::c, and SN_env::I.
static int r_residual_suffix (struct SN_env * z) [static]
Definition at line 1036 of file stem_UTF_8_french.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), g_keep_with_s, SN_env::I, SN_env::ket, SN_env::l, SN_env::lb, out_grouping_b_U(), r_R2(), s_33, s_34, s_35, s_36, s_37, slice_del(), and slice_from_s().
Referenced by french_UTF_8_stem(), portuguese_UTF_8_stem(), and spanish_UTF_8_stem().
static int r_RV (struct SN_env * z) [static]
Definition at line 598 of file stem_UTF_8_french.cpp.
References SN_env::c, and SN_env::I.
Referenced by portuguese_UTF_8_stem(), r_attached_pronoun(), r_residual_form(), r_residual_suffix(), r_standard_suffix(), and r_vowel_suffix().
static int r_standard_suffix (struct SN_env * z) [static]
Definition at line 613 of file stem_UTF_8_french.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), g_v, in_grouping_b_U(), SN_env::ket, SN_env::l, SN_env::lb, out_grouping_b_U(), SN_env::p, r_R1(), r_R2(), r_RV(), s_14, s_15, s_16, s_17, s_18, s_19, s_20, s_21, s_22, s_23, s_24, s_25, s_26, s_27, s_28, s_29, s_30, s_31, slice_del(), and slice_from_s().
static int r_un_accent (struct SN_env * z) [static]
Definition at line 1121 of file stem_UTF_8_french.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), g_v, SN_env::ket, SN_env::l, out_grouping_b_U(), s_38, s_39, s_40, and slice_from_s().
Referenced by french_UTF_8_stem().
static int r_un_double (struct SN_env * z) [static]
Definition at line 1103 of file stem_UTF_8_french.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::ket, SN_env::l, SN_env::lb, SN_env::p, skip_utf8(), and slice_del().
Referenced by french_UTF_8_stem().
static int r_verb_suffix (struct SN_env * z) [static]
Definition at line 987 of file stem_UTF_8_french.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), SN_env::I, SN_env::ket, SN_env::l, SN_env::lb, r_R2(), s_32, and slice_del().
Referenced by french_UTF_8_stem(), italian_UTF_8_stem(), portuguese_UTF_8_stem(), romanian_UTF_8_stem(), and spanish_UTF_8_stem().
Variable Documentation
struct among a_0[3] [static]
Initial value:
{
 { 3, s_0_0, -1, -1, 0},
 { 3, s_0_1, -1, -1, 0},
 { 3, s_0_2, -1, -1, 0}
}
Definition at line 42 of file stem_UTF_8_french.cpp.
struct among a_1[4] [static]
Initial value:
{
 { 0, 0, -1, 4, 0},
 { 1, s_1_1, 0, 1, 0},
 { 1, s_1_2, 0, 2, 0},
 { 1, s_1_3, 0, 3, 0}
}
Definition at line 53 of file stem_UTF_8_french.cpp.
struct among a_2[6] [static]
Initial value:
{
 { 3, s_2_0, -1, 3, 0},
 { 3, s_2_1, -1, 3, 0},
 { 4, s_2_2, -1, 4, 0},
 { 4, s_2_3, -1, 4, 0},
 { 3, s_2_4, -1, 2, 0},
 { 2, s_2_5, -1, 1, 0}
}
Definition at line 68 of file stem_UTF_8_french.cpp.
struct among a_3[3] [static]
Initial value:
{
 { 2, s_3_0, -1, 2, 0},
 { 4, s_3_1, -1, 1, 0},
 { 2, s_3_2, -1, 3, 0}
}
Definition at line 82 of file stem_UTF_8_french.cpp.
struct among a_4[43] [static]
Definition at line 133 of file stem_UTF_8_french.cpp.
struct among a_5[35] [static]
Definition at line 216 of file stem_UTF_8_french.cpp.
struct among a_6[38] [static]
Definition at line 294 of file stem_UTF_8_french.cpp.
struct among a_7[7] [static]
Initial value:
{
 { 1, s_7_0, -1, 3, 0},
 { 5, s_7_1, 0, 2, 0},
 { 5, s_7_2, 0, 2, 0},
 { 3, s_7_3, -1, 1, 0},
 { 3, s_7_4, -1, 2, 0},
 { 3, s_7_5, -1, 2, 0},
 { 2, s_7_6, -1, 4, 0}
}
Definition at line 344 of file stem_UTF_8_french.cpp.
struct among a_8[5] [static]
Initial value:
{
 { 3, s_8_0, -1, -1, 0},
 { 4, s_8_1, -1, -1, 0},
 { 3, s_8_2, -1, -1, 0},
 { 3, s_8_3, -1, -1, 0},
 { 3, s_8_4, -1, -1, 0}
}
Definition at line 361 of file stem_UTF_8_french.cpp.
const unsigned char g_keep_with_s[] = { 1, 65, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128 } [static]
Definition at line 372 of file stem_UTF_8_french.cpp.
Referenced by r_residual_suffix().
const unsigned char g_v[] = { 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 130, 103, 8, 5 } [static]
Definition at line 370 of file stem_UTF_8_french.cpp.
const symbol s_0[] = { 'u' } [static]
Definition at line 374 of file stem_UTF_8_french.cpp.
const symbol s_0_0[3] = { 'c', 'o', 'l' } [static]
Definition at line 38 of file stem_UTF_8_french.cpp.
const symbol s_0_1[3] = { 'p', 'a', 'r' } [static]
Definition at line 39 of file stem_UTF_8_french.cpp.
const symbol s_0_2[3] = { 't', 'a', 'p' } [static]
Definition at line 40 of file stem_UTF_8_french.cpp.
const symbol s_1[] = { 'U' } [static]
Definition at line 375 of file stem_UTF_8_french.cpp.
const symbol s_10[] = { 'U' } [static]
Definition at line 384 of file stem_UTF_8_french.cpp.
const symbol s_11[] = { 'i' } [static]
Definition at line 385 of file stem_UTF_8_french.cpp.
const symbol s_12[] = { 'u' } [static]
Definition at line 386 of file stem_UTF_8_french.cpp.
const symbol s_13[] = { 'y' } [static]
Definition at line 387 of file stem_UTF_8_french.cpp.
const symbol s_14[] = { 'i', 'c' } [static]
Definition at line 388 of file stem_UTF_8_french.cpp.
const symbol s_15[] = { 'i', 'q', 'U' } [static]
Definition at line 389 of file stem_UTF_8_french.cpp.
const symbol s_16[] = { 'l', 'o', 'g' } [static]
Definition at line 390 of file stem_UTF_8_french.cpp.
const symbol s_17[] = { 'u' } [static]
Definition at line 391 of file stem_UTF_8_french.cpp.
const symbol s_18[] = { 'e', 'n', 't' } [static]
Definition at line 392 of file stem_UTF_8_french.cpp.
const symbol s_19[] = { 'a', 't' } [static]
Definition at line 393 of file stem_UTF_8_french.cpp.
const symbol s_1_1[1] = { 'I' } [static]
Definition at line 49 of file stem_UTF_8_french.cpp.
const symbol s_1_2[1] = { 'U' } [static]
Definition at line 50 of file stem_UTF_8_french.cpp.
const symbol s_1_3[1] = { 'Y' } [static]
Definition at line 51 of file stem_UTF_8_french.cpp.
const symbol s_2[] = { 'i' } [static]
Definition at line 376 of file stem_UTF_8_french.cpp.
const symbol s_20[] = { 'e', 'u', 'x' } [static]
Definition at line 394 of file stem_UTF_8_french.cpp.
const symbol s_21[] = { 'i' } [static]
Definition at line 395 of file stem_UTF_8_french.cpp.
const symbol s_22[] = { 'a', 'b', 'l' } [static]
Definition at line 396 of file stem_UTF_8_french.cpp.
const symbol s_23[] = { 'i', 'q', 'U' } [static]
Definition at line 397 of file stem_UTF_8_french.cpp.
const symbol s_24[] = { 'a', 't' } [static]
Definition at line 398 of file stem_UTF_8_french.cpp.
const symbol s_25[] = { 'i', 'c' } [static]
Definition at line 399 of file stem_UTF_8_french.cpp.
const symbol s_26[] = { 'i', 'q', 'U' } [static]
Definition at line 400 of file stem_UTF_8_french.cpp.
const symbol s_27[] = { 'e', 'a', 'u' } [static]
Definition at line 401 of file stem_UTF_8_french.cpp.
const symbol s_28[] = { 'a', 'l' } [static]
Definition at line 402 of file stem_UTF_8_french.cpp.
const symbol s_29[] = { 'e', 'u', 'x' } [static]
Definition at line 403 of file stem_UTF_8_french.cpp.
const symbol s_2_0[3] = { 'i', 'q', 'U' } [static]
Definition at line 61 of file stem_UTF_8_french.cpp.
const symbol s_2_1[3] = { 'a', 'b', 'l' } [static]
Definition at line 62 of file stem_UTF_8_french.cpp.
const symbol s_2_2[4] = { 'I', 0xC3, 0xA8, 'r' } [static]
Definition at line 63 of file stem_UTF_8_french.cpp.
const symbol s_2_3[4] = { 'i', 0xC3, 0xA8, 'r' } [static]
Definition at line 64 of file stem_UTF_8_french.cpp.
const symbol s_2_4[3] = { 'e', 'u', 's' } [static]
Definition at line 65 of file stem_UTF_8_french.cpp.
const symbol s_2_5[2] = { 'i', 'v' } [static]
Definition at line 66 of file stem_UTF_8_french.cpp.
const symbol s_3[] = { 'I' } [static]
Definition at line 377 of file stem_UTF_8_french.cpp.
const symbol s_30[] = { 'a', 'n', 't' } [static]
Definition at line 404 of file stem_UTF_8_french.cpp.
const symbol s_31[] = { 'e', 'n', 't' } [static]
Definition at line 405 of file stem_UTF_8_french.cpp.
const symbol s_32[] = { 'e' } [static]
Definition at line 406 of file stem_UTF_8_french.cpp.
const symbol s_33[] = { 's' } [static]
Definition at line 407 of file stem_UTF_8_french.cpp.
const symbol s_34[] = { 's' } [static]
Definition at line 408 of file stem_UTF_8_french.cpp.
const symbol s_35[] = { 't' } [static]
Definition at line 409 of file stem_UTF_8_french.cpp.
const symbol s_36[] = { 'i' } [static]
Definition at line 410 of file stem_UTF_8_french.cpp.
const symbol s_37[] = { 'g', 'u' } [static]
Definition at line 411 of file stem_UTF_8_french.cpp.
const symbol s_38[] = { 0xC3, 0xA9 } [static]
Definition at line 412 of file stem_UTF_8_french.cpp.
const symbol s_39[] = { 0xC3, 0xA8 } [static]
Definition at line 413 of file stem_UTF_8_french.cpp.
const symbol s_3_0[2] = { 'i', 'c' } [static]
Definition at line 78 of file stem_UTF_8_french.cpp.
const symbol s_3_1[4] = { 'a', 'b', 'i', 'l' } [static]
Definition at line 79 of file stem_UTF_8_french.cpp.
const symbol s_3_2[2] = { 'i', 'v' } [static]
Definition at line 80 of file stem_UTF_8_french.cpp.
const symbol s_4[] = { 'y' } [static]
Definition at line 378 of file stem_UTF_8_french.cpp.
const symbol s_40[] = { 'e' } [static]
Definition at line 414 of file stem_UTF_8_french.cpp.
const symbol s_41[] = { 'Y' } [static]
Definition at line 415 of file stem_UTF_8_french.cpp.
const symbol s_42[] = { 'i' } [static]
Definition at line 416 of file stem_UTF_8_french.cpp.
const symbol s_43[] = { 0xC3, 0xA7 } [static]
Definition at line 417 of file stem_UTF_8_french.cpp.
const symbol s_44[] = { 'c' } [static]
Definition at line 418 of file stem_UTF_8_french.cpp.
const symbol s_4_0[4] = { 'i', 'q', 'U', 'e' } [static]
Definition at line 89 of file stem_UTF_8_french.cpp.
const symbol s_4_1[6] = { 'a', 't', 'r', 'i', 'c', 'e' } [static]
Definition at line 90 of file stem_UTF_8_french.cpp.
const symbol s_4_10[2] = { 'i', 'f' } [static]
Definition at line 99 of file stem_UTF_8_french.cpp.
const symbol s_4_11[5] = { 'u', 's', 'i', 'o', 'n' } [static]
Definition at line 100 of file stem_UTF_8_french.cpp.
const symbol s_4_12[5] = { 'a', 't', 'i', 'o', 'n' } [static]
Definition at line 101 of file stem_UTF_8_french.cpp.
const symbol s_4_13[5] = { 'u', 't', 'i', 'o', 'n' } [static]
Definition at line 102 of file stem_UTF_8_french.cpp.
const symbol s_4_14[5] = { 'a', 't', 'e', 'u', 'r' } [static]
Definition at line 103 of file stem_UTF_8_french.cpp.
const symbol s_4_15[5] = { 'i', 'q', 'U', 'e', 's' } [static]
Definition at line 104 of file stem_UTF_8_french.cpp.
const symbol s_4_16[7] = { 'a', 't', 'r', 'i', 'c', 'e', 's' } [static]
Definition at line 105 of file stem_UTF_8_french.cpp.
const symbol s_4_17[5] = { 'a', 'n', 'c', 'e', 's' } [static]
Definition at line 106 of file stem_UTF_8_french.cpp.
const symbol s_4_18[5] = { 'e', 'n', 'c', 'e', 's' } [static]
Definition at line 107 of file stem_UTF_8_french.cpp.
const symbol s_4_19[6] = { 'l', 'o', 'g', 'i', 'e', 's' } [static]
Definition at line 108 of file stem_UTF_8_french.cpp.
const symbol s_4_2[4] = { 'a', 'n', 'c', 'e' } [static]
Definition at line 91 of file stem_UTF_8_french.cpp.
const symbol s_4_20[5] = { 'a', 'b', 'l', 'e', 's' } [static]
Definition at line 109 of file stem_UTF_8_french.cpp.
const symbol s_4_21[5] = { 'i', 's', 'm', 'e', 's' } [static]
Definition at line 110 of file stem_UTF_8_french.cpp.
const symbol s_4_22[5] = { 'e', 'u', 's', 'e', 's' } [static]
Definition at line 111 of file stem_UTF_8_french.cpp.
const symbol s_4_23[5] = { 'i', 's', 't', 'e', 's' } [static]
Definition at line 112 of file stem_UTF_8_french.cpp.
const symbol s_4_24[4] = { 'i', 'v', 'e', 's' } [static]
Definition at line 113 of file stem_UTF_8_french.cpp.
const symbol s_4_25[3] = { 'i', 'f', 's' } [static]
Definition at line 114 of file stem_UTF_8_french.cpp.
const symbol s_4_26[6] = { 'u', 's', 'i', 'o', 'n', 's' } [static]
Definition at line 115 of file stem_UTF_8_french.cpp.
const symbol s_4_27[6] = { 'a', 't', 'i', 'o', 'n', 's' } [static]
Definition at line 116 of file stem_UTF_8_french.cpp.
const symbol s_4_28[6] = { 'u', 't', 'i', 'o', 'n', 's' } [static]
Definition at line 117 of file stem_UTF_8_french.cpp.
const symbol s_4_29[6] = { 'a', 't', 'e', 'u', 'r', 's' } [static]
Definition at line 118 of file stem_UTF_8_french.cpp.
const symbol s_4_3[4] = { 'e', 'n', 'c', 'e' } [static]
Definition at line 92 of file stem_UTF_8_french.cpp.
const symbol s_4_30[5] = { 'm', 'e', 'n', 't', 's' } [static]
Definition at line 119 of file stem_UTF_8_french.cpp.
const symbol s_4_31[6] = { 'e', 'm', 'e', 'n', 't', 's' } [static]
Definition at line 120 of file stem_UTF_8_french.cpp.
const symbol s_4_32[9] = { 'i', 's', 's', 'e', 'm', 'e', 'n', 't', 's' } [static]
Definition at line 121 of file stem_UTF_8_french.cpp.
const symbol s_4_33[5] = { 'i', 't', 0xC3, 0xA9, 's' } [static]
Definition at line 122 of file stem_UTF_8_french.cpp.
const symbol s_4_34[4] = { 'm', 'e', 'n', 't' } [static]
Definition at line 123 of file stem_UTF_8_french.cpp.
const symbol s_4_35[5] = { 'e', 'm', 'e', 'n', 't' } [static]
Definition at line 124 of file stem_UTF_8_french.cpp.
const symbol s_4_36[8] = { 'i', 's', 's', 'e', 'm', 'e', 'n', 't' } [static]
Definition at line 125 of file stem_UTF_8_french.cpp.
const symbol s_4_37[6] = { 'a', 'm', 'm', 'e', 'n', 't' } [static]
Definition at line 126 of file stem_UTF_8_french.cpp.
const symbol s_4_38[6] = { 'e', 'm', 'm', 'e', 'n', 't' } [static]
Definition at line 127 of file stem_UTF_8_french.cpp.
const symbol s_4_39[3] = { 'a', 'u', 'x' } [static]
Definition at line 128 of file stem_UTF_8_french.cpp.
const symbol s_4_4[5] = { 'l', 'o', 'g', 'i', 'e' } [static]
Definition at line 93 of file stem_UTF_8_french.cpp.
const symbol s_4_40[4] = { 'e', 'a', 'u', 'x' } [static]
Definition at line 129 of file stem_UTF_8_french.cpp.
const symbol s_4_41[3] = { 'e', 'u', 'x' } [static]
Definition at line 130 of file stem_UTF_8_french.cpp.
const symbol s_4_42[4] = { 'i', 't', 0xC3, 0xA9 } [static]
Definition at line 131 of file stem_UTF_8_french.cpp.
const symbol s_4_5[4] = { 'a', 'b', 'l', 'e' } [static]
Definition at line 94 of file stem_UTF_8_french.cpp.
const symbol s_4_6[4] = { 'i', 's', 'm', 'e' } [static]
Definition at line 95 of file stem_UTF_8_french.cpp.
const symbol s_4_7[4] = { 'e', 'u', 's', 'e' } [static]
Definition at line 96 of file stem_UTF_8_french.cpp.
const symbol s_4_8[4] = { 'i', 's', 't', 'e' } [static]
Definition at line 97 of file stem_UTF_8_french.cpp.
const symbol s_4_9[3] = { 'i', 'v', 'e' } [static]
Definition at line 98 of file stem_UTF_8_french.cpp.
const symbol s_5[] = { 'Y' } [static]
Definition at line 379 of file stem_UTF_8_french.cpp.
const symbol s_5_0[3] = { 'i', 'r', 'a' } [static]
Definition at line 180 of file stem_UTF_8_french.cpp.
const symbol s_5_1[2] = { 'i', 'e' } [static]
Definition at line 181 of file stem_UTF_8_french.cpp.
const symbol s_5_10[5] = { 'i', 's', 's', 'e', 's' } [static]
Definition at line 190 of file stem_UTF_8_french.cpp.
const symbol s_5_11[8] = { 'i', 's', 's', 'a', 'n', 't', 'e', 's' } [static]
Definition at line 191 of file stem_UTF_8_french.cpp.
const symbol s_5_12[5] = { 0xC3, 0xAE, 't', 'e', 's' } [static]
Definition at line 192 of file stem_UTF_8_french.cpp.
const symbol s_5_13[2] = { 'i', 's' } [static]
Definition at line 193 of file stem_UTF_8_french.cpp.
const symbol s_5_14[5] = { 'i', 'r', 'a', 'i', 's' } [static]
Definition at line 194 of file stem_UTF_8_french.cpp.
const symbol s_5_15[6] = { 'i', 's', 's', 'a', 'i', 's' } [static]
Definition at line 195 of file stem_UTF_8_french.cpp.
const symbol s_5_16[6] = { 'i', 'r', 'i', 'o', 'n', 's' } [static]
Definition at line 196 of file stem_UTF_8_french.cpp.
const symbol s_5_17[7] = { 'i', 's', 's', 'i', 'o', 'n', 's' } [static]
Definition at line 197 of file stem_UTF_8_french.cpp.
const symbol s_5_18[5] = { 'i', 'r', 'o', 'n', 's' } [static]
Definition at line 198 of file stem_UTF_8_french.cpp.
const symbol s_5_19[6] = { 'i', 's', 's', 'o', 'n', 's' } [static]
Definition at line 199 of file stem_UTF_8_french.cpp.
const symbol s_5_2[4] = { 'i', 's', 's', 'e' } [static]
Definition at line 182 of file stem_UTF_8_french.cpp.
const symbol s_5_20[7] = { 'i', 's', 's', 'a', 'n', 't', 's' } [static]
Definition at line 200 of file stem_UTF_8_french.cpp.
const symbol s_5_21[2] = { 'i', 't' } [static]
Definition at line 201 of file stem_UTF_8_french.cpp.
const symbol s_5_22[5] = { 'i', 'r', 'a', 'i', 't' } [static]
Definition at line 202 of file stem_UTF_8_french.cpp.
const symbol s_5_23[6] = { 'i', 's', 's', 'a', 'i', 't' } [static]
Definition at line 203 of file stem_UTF_8_french.cpp.
const symbol s_5_24[6] = { 'i', 's', 's', 'a', 'n', 't' } [static]
Definition at line 204 of file stem_UTF_8_french.cpp.
const symbol s_5_25[7] = { 'i', 'r', 'a', 'I', 'e', 'n', 't' } [static]
Definition at line 205 of file stem_UTF_8_french.cpp.
const symbol s_5_26[8] = { 'i', 's', 's', 'a', 'I', 'e', 'n', 't' } [static]
Definition at line 206 of file stem_UTF_8_french.cpp.
const symbol s_5_27[5] = { 'i', 'r', 'e', 'n', 't' } [static]
Definition at line 207 of file stem_UTF_8_french.cpp.
const symbol s_5_28[6] = { 'i', 's', 's', 'e', 'n', 't' } [static]
Definition at line 208 of file stem_UTF_8_french.cpp.
const symbol s_5_29[5] = { 'i', 'r', 'o', 'n', 't' } [static]
Definition at line 209 of file stem_UTF_8_french.cpp.
const symbol s_5_3[7] = { 'i', 's', 's', 'a', 'n', 't', 'e' } [static]
Definition at line 183 of file stem_UTF_8_french.cpp.
const symbol s_5_30[3] = { 0xC3, 0xAE, 't' } [static]
Definition at line 210 of file stem_UTF_8_french.cpp.
const symbol s_5_31[5] = { 'i', 'r', 'i', 'e', 'z' } [static]
Definition at line 211 of file stem_UTF_8_french.cpp.
const symbol s_5_32[6] = { 'i', 's', 's', 'i', 'e', 'z' } [static]
Definition at line 212 of file stem_UTF_8_french.cpp.
const symbol s_5_33[4] = { 'i', 'r', 'e', 'z' } [static]
Definition at line 213 of file stem_UTF_8_french.cpp.
const symbol s_5_34[5] = { 'i', 's', 's', 'e', 'z' } [static]
Definition at line 214 of file stem_UTF_8_french.cpp.
const symbol s_5_4[1] = { 'i' } [static]
Definition at line 184 of file stem_UTF_8_french.cpp.
const symbol s_5_5[4] = { 'i', 'r', 'a', 'i' } [static]
Definition at line 185 of file stem_UTF_8_french.cpp.
const symbol s_5_6[2] = { 'i', 'r' } [static]
Definition at line 186 of file stem_UTF_8_french.cpp.
const symbol s_5_7[4] = { 'i', 'r', 'a', 's' } [static]
Definition at line 187 of file stem_UTF_8_french.cpp.
const symbol s_5_8[3] = { 'i', 'e', 's' } [static]
Definition at line 188 of file stem_UTF_8_french.cpp.
const symbol s_5_9[5] = { 0xC3, 0xAE, 'm', 'e', 's' } [static]
Definition at line 189 of file stem_UTF_8_french.cpp.
const symbol s_6[] = { 'y' } [static]
Definition at line 380 of file stem_UTF_8_french.cpp.
const symbol s_6_0[1] = { 'a' } [static]
Definition at line 255 of file stem_UTF_8_french.cpp.
const symbol s_6_1[3] = { 'e', 'r', 'a' } [static]
Definition at line 256 of file stem_UTF_8_french.cpp.
const symbol s_6_10[5] = { 0xC3, 0xA2, 'm', 'e', 's' } [static]
Definition at line 265 of file stem_UTF_8_french.cpp.
const symbol s_6_11[5] = { 'a', 's', 's', 'e', 's' } [static]
Definition at line 266 of file stem_UTF_8_french.cpp.
const symbol s_6_12[5] = { 'a', 'n', 't', 'e', 's' } [static]
Definition at line 267 of file stem_UTF_8_french.cpp.
const symbol s_6_13[5] = { 0xC3, 0xA2, 't', 'e', 's' } [static]
Definition at line 268 of file stem_UTF_8_french.cpp.
const symbol s_6_14[4] = { 0xC3, 0xA9, 'e', 's' } [static]
Definition at line 269 of file stem_UTF_8_french.cpp.
const symbol s_6_15[3] = { 'a', 'i', 's' } [static]
Definition at line 270 of file stem_UTF_8_french.cpp.
const symbol s_6_16[5] = { 'e', 'r', 'a', 'i', 's' } [static]
Definition at line 271 of file stem_UTF_8_french.cpp.
const symbol s_6_17[4] = { 'i', 'o', 'n', 's' } [static]
Definition at line 272 of file stem_UTF_8_french.cpp.
const symbol s_6_18[6] = { 'e', 'r', 'i', 'o', 'n', 's' } [static]
Definition at line 273 of file stem_UTF_8_french.cpp.
const symbol s_6_19[7] = { 'a', 's', 's', 'i', 'o', 'n', 's' } [static]
Definition at line 274 of file stem_UTF_8_french.cpp.
const symbol s_6_2[4] = { 'a', 's', 's', 'e' } [static]
Definition at line 257 of file stem_UTF_8_french.cpp.
const symbol s_6_20[5] = { 'e', 'r', 'o', 'n', 's' } [static]
Definition at line 275 of file stem_UTF_8_french.cpp.
const symbol s_6_21[4] = { 'a', 'n', 't', 's' } [static]
Definition at line 276 of file stem_UTF_8_french.cpp.
const symbol s_6_22[3] = { 0xC3, 0xA9, 's' } [static]
Definition at line 277 of file stem_UTF_8_french.cpp.
const symbol s_6_23[3] = { 'a', 'i', 't' } [static]
Definition at line 278 of file stem_UTF_8_french.cpp.
const symbol s_6_24[5] = { 'e', 'r', 'a', 'i', 't' } [static]
Definition at line 279 of file stem_UTF_8_french.cpp.
const symbol s_6_25[3] = { 'a', 'n', 't' } [static]
Definition at line 280 of file stem_UTF_8_french.cpp.
const symbol s_6_26[5] = { 'a', 'I', 'e', 'n', 't' } [static]
Definition at line 281 of file stem_UTF_8_french.cpp.
const symbol s_6_27[7] = { 'e', 'r', 'a', 'I', 'e', 'n', 't' } [static]
Definition at line 282 of file stem_UTF_8_french.cpp.
const symbol s_6_28[6] = { 0xC3, 0xA8, 'r', 'e', 'n', 't' } [static]
Definition at line 283 of file stem_UTF_8_french.cpp.
const symbol s_6_29[6] = { 'a', 's', 's', 'e', 'n', 't' } [static]
Definition at line 284 of file stem_UTF_8_french.cpp.
const symbol s_6_3[4] = { 'a', 'n', 't', 'e' } [static]
Definition at line 258 of file stem_UTF_8_french.cpp.
const symbol s_6_30[5] = { 'e', 'r', 'o', 'n', 't' } [static]
Definition at line 285 of file stem_UTF_8_french.cpp.
const symbol s_6_31[3] = { 0xC3, 0xA2, 't' } [static]
Definition at line 286 of file stem_UTF_8_french.cpp.
const symbol s_6_32[2] = { 'e', 'z' } [static]
Definition at line 287 of file stem_UTF_8_french.cpp.
const symbol s_6_33[3] = { 'i', 'e', 'z' } [static]
Definition at line 288 of file stem_UTF_8_french.cpp.
const symbol s_6_34[5] = { 'e', 'r', 'i', 'e', 'z' } [static]
Definition at line 289 of file stem_UTF_8_french.cpp.
const symbol s_6_35[6] = { 'a', 's', 's', 'i', 'e', 'z' } [static]
Definition at line 290 of file stem_UTF_8_french.cpp.
const symbol s_6_36[4] = { 'e', 'r', 'e', 'z' } [static]
Definition at line 291 of file stem_UTF_8_french.cpp.
const symbol s_6_37[2] = { 0xC3, 0xA9 } [static]
Definition at line 292 of file stem_UTF_8_french.cpp.
const symbol s_6_4[3] = { 0xC3, 0xA9, 'e' } [static]
Definition at line 259 of file stem_UTF_8_french.cpp.
const symbol s_6_5[2] = { 'a', 'i' } [static]
Definition at line 260 of file stem_UTF_8_french.cpp.
const symbol s_6_6[4] = { 'e', 'r', 'a', 'i' } [static]
Definition at line 261 of file stem_UTF_8_french.cpp.
const symbol s_6_7[2] = { 'e', 'r' } [static]
Definition at line 262 of file stem_UTF_8_french.cpp.
const symbol s_6_8[2] = { 'a', 's' } [static]
Definition at line 263 of file stem_UTF_8_french.cpp.
const symbol s_6_9[4] = { 'e', 'r', 'a', 's' } [static]
Definition at line 264 of file stem_UTF_8_french.cpp.
const symbol s_7[] = { 'Y' } [static]
Definition at line 381 of file stem_UTF_8_french.cpp.
const symbol s_7_0[1] = { 'e' } [static]
Definition at line 336 of file stem_UTF_8_french.cpp.
const symbol s_7_1[5] = { 'I', 0xC3, 0xA8, 'r', 'e' } [static]
Definition at line 337 of file stem_UTF_8_french.cpp.
const symbol s_7_2[5] = { 'i', 0xC3, 0xA8, 'r', 'e' } [static]
Definition at line 338 of file stem_UTF_8_french.cpp.
const symbol s_7_3[3] = { 'i', 'o', 'n' } [static]
Definition at line 339 of file stem_UTF_8_french.cpp.
const symbol s_7_4[3] = { 'I', 'e', 'r' } [static]
Definition at line 340 of file stem_UTF_8_french.cpp.
const symbol s_7_5[3] = { 'i', 'e', 'r' } [static]
Definition at line 341 of file stem_UTF_8_french.cpp.
const symbol s_7_6[2] = { 0xC3, 0xAB } [static]
Definition at line 342 of file stem_UTF_8_french.cpp.
const symbol s_8[] = { 'q' } [static]
Definition at line 382 of file stem_UTF_8_french.cpp.
const symbol s_8_0[3] = { 'e', 'l', 'l' } [static]
Definition at line 355 of file stem_UTF_8_french.cpp.
const symbol s_8_1[4] = { 'e', 'i', 'l', 'l' } [static]
Definition at line 356 of file stem_UTF_8_french.cpp.
const symbol s_8_2[3] = { 'e', 'n', 'n' } [static]
Definition at line 357 of file stem_UTF_8_french.cpp.
const symbol s_8_3[3] = { 'o', 'n', 'n' } [static]
Definition at line 358 of file stem_UTF_8_french.cpp.
const symbol s_8_4[3] = { 'e', 't', 't' } [static]
Definition at line 359 of file stem_UTF_8_french.cpp.
const symbol s_9[] = { 'u' } [static]
Definition at line 383 of file stem_UTF_8_french.cpp.