/disk/workspace-cpp/la-manager/source/stem/stem_UTF_8_hungarian.cpp File Reference
#include <stem/header.h>
Functions
int hungarian_UTF_8_stem (struct SN_env *z)
static int r_double (struct SN_env *z)
static int r_undouble (struct SN_env *z)
static int r_factive (struct SN_env *z)
static int r_instrum (struct SN_env *z)
static int r_plur_owner (struct SN_env *z)
static int r_sing_owner (struct SN_env *z)
static int r_owned (struct SN_env *z)
static int r_plural (struct SN_env *z)
static int r_case_other (struct SN_env *z)
static int r_case_special (struct SN_env *z)
static int r_case (struct SN_env *z)
static int r_v_ending (struct SN_env *z)
static int r_R1 (struct SN_env *z)
static int r_mark_regions (struct SN_env *z)
struct SN_env * hungarian_UTF_8_create_env (void)
void hungarian_UTF_8_close_env (struct SN_env *z)
Variables
static const symbol s_0_0 [2] = { 'c', 's' }
static const symbol s_0_1 [3] = { 'd', 'z', 's' }
static const symbol s_0_2 [2] = { 'g', 'y' }
static const symbol s_0_3 [2] = { 'l', 'y' }
static const symbol s_0_4 [2] = { 'n', 'y' }
static const symbol s_0_5 [2] = { 's', 'z' }
static const symbol s_0_6 [2] = { 't', 'y' }
static const symbol s_0_7 [2] = { 'z', 's' }
static struct among a_0 [8]
static const symbol s_1_0 [2] = { 0xC3, 0xA1 }
static const symbol s_1_1 [2] = { 0xC3, 0xA9 }
static struct among a_1 [2]
static const symbol s_2_0 [2] = { 'b', 'b' }
static const symbol s_2_1 [2] = { 'c', 'c' }
static const symbol s_2_2 [2] = { 'd', 'd' }
static const symbol s_2_3 [2] = { 'f', 'f' }
static const symbol s_2_4 [2] = { 'g', 'g' }
static const symbol s_2_5 [2] = { 'j', 'j' }
static const symbol s_2_6 [2] = { 'k', 'k' }
static const symbol s_2_7 [2] = { 'l', 'l' }
static const symbol s_2_8 [2] = { 'm', 'm' }
static const symbol s_2_9 [2] = { 'n', 'n' }
static const symbol s_2_10 [2] = { 'p', 'p' }
static const symbol s_2_11 [2] = { 'r', 'r' }
static const symbol s_2_12 [3] = { 'c', 'c', 's' }
static const symbol s_2_13 [2] = { 's', 's' }
static const symbol s_2_14 [3] = { 'z', 'z', 's' }
static const symbol s_2_15 [2] = { 't', 't' }
static const symbol s_2_16 [2] = { 'v', 'v' }
static const symbol s_2_17 [3] = { 'g', 'g', 'y' }
static const symbol s_2_18 [3] = { 'l', 'l', 'y' }
static const symbol s_2_19 [3] = { 'n', 'n', 'y' }
static const symbol s_2_20 [3] = { 't', 't', 'y' }
static const symbol s_2_21 [3] = { 's', 's', 'z' }
static const symbol s_2_22 [2] = { 'z', 'z' }
static struct among a_2 [23]
static const symbol s_3_0 [2] = { 'a', 'l' }
static const symbol s_3_1 [2] = { 'e', 'l' }
static struct among a_3 [2]
static const symbol s_4_0 [2] = { 'b', 'a' }
static const symbol s_4_1 [2] = { 'r', 'a' }
static const symbol s_4_2 [2] = { 'b', 'e' }
static const symbol s_4_3 [2] = { 'r', 'e' }
static const symbol s_4_4 [2] = { 'i', 'g' }
static const symbol s_4_5 [3] = { 'n', 'a', 'k' }
static const symbol s_4_6 [3] = { 'n', 'e', 'k' }
static const symbol s_4_7 [3] = { 'v', 'a', 'l' }
static const symbol s_4_8 [3] = { 'v', 'e', 'l' }
static const symbol s_4_9 [2] = { 'u', 'l' }
static const symbol s_4_10 [4] = { 'n', 0xC3, 0xA1, 'l' }
static const symbol s_4_11 [4] = { 'n', 0xC3, 0xA9, 'l' }
static const symbol s_4_12 [4] = { 'b', 0xC3, 0xB3, 'l' }
static const symbol s_4_13 [4] = { 'r', 0xC3, 0xB3, 'l' }
static const symbol s_4_14 [4] = { 't', 0xC3, 0xB3, 'l' }
static const symbol s_4_15 [4] = { 'b', 0xC3, 0xB5, 'l' }
static const symbol s_4_16 [4] = { 'r', 0xC3, 0xB5, 'l' }
static const symbol s_4_17 [4] = { 't', 0xC3, 0xB5, 'l' }
static const symbol s_4_18 [3] = { 0xC3, 0xBC, 'l' }
static const symbol s_4_19 [1] = { 'n' }
static const symbol s_4_20 [2] = { 'a', 'n' }
static const symbol s_4_21 [3] = { 'b', 'a', 'n' }
static const symbol s_4_22 [2] = { 'e', 'n' }
static const symbol s_4_23 [3] = { 'b', 'e', 'n' }
static const symbol s_4_24 [7] = { 'k', 0xC3, 0xA9, 'p', 'p', 'e', 'n' }
static const symbol s_4_25 [2] = { 'o', 'n' }
static const symbol s_4_26 [3] = { 0xC3, 0xB6, 'n' }
static const symbol s_4_27 [5] = { 'k', 0xC3, 0xA9, 'p', 'p' }
static const symbol s_4_28 [3] = { 'k', 'o', 'r' }
static const symbol s_4_29 [1] = { 't' }
static const symbol s_4_30 [2] = { 'a', 't' }
static const symbol s_4_31 [2] = { 'e', 't' }
static const symbol s_4_32 [5] = { 'k', 0xC3, 0xA9, 'n', 't' }
static const symbol s_4_33 [7] = { 'a', 'n', 'k', 0xC3, 0xA9, 'n', 't' }
static const symbol s_4_34 [7] = { 'e', 'n', 'k', 0xC3, 0xA9, 'n', 't' }
static const symbol s_4_35 [7] = { 'o', 'n', 'k', 0xC3, 0xA9, 'n', 't' }
static const symbol s_4_36 [2] = { 'o', 't' }
static const symbol s_4_37 [4] = { 0xC3, 0xA9, 'r', 't' }
static const symbol s_4_38 [3] = { 0xC3, 0xB6, 't' }
static const symbol s_4_39 [3] = { 'h', 'e', 'z' }
static const symbol s_4_40 [3] = { 'h', 'o', 'z' }
static const symbol s_4_41 [4] = { 'h', 0xC3, 0xB6, 'z' }
static const symbol s_4_42 [3] = { 'v', 0xC3, 0xA1 }
static const symbol s_4_43 [3] = { 'v', 0xC3, 0xA9 }
static struct among a_4 [44]
static const symbol s_5_0 [3] = { 0xC3, 0xA1, 'n' }
static const symbol s_5_1 [3] = { 0xC3, 0xA9, 'n' }
static const symbol s_5_2 [8] = { 0xC3, 0xA1, 'n', 'k', 0xC3, 0xA9, 'n', 't' }
static struct among a_5 [3]
static const symbol s_6_0 [4] = { 's', 't', 'u', 'l' }
static const symbol s_6_1 [5] = { 'a', 's', 't', 'u', 'l' }
static const symbol s_6_2 [6] = { 0xC3, 0xA1, 's', 't', 'u', 'l' }
static const symbol s_6_3 [5] = { 's', 't', 0xC3, 0xBC, 'l' }
static const symbol s_6_4 [6] = { 'e', 's', 't', 0xC3, 0xBC, 'l' }
static const symbol s_6_5 [7] = { 0xC3, 0xA9, 's', 't', 0xC3, 0xBC, 'l' }
static struct among a_6 [6]
static const symbol s_7_0 [2] = { 0xC3, 0xA1 }
static const symbol s_7_1 [2] = { 0xC3, 0xA9 }
static struct among a_7 [2]
static const symbol s_8_0 [1] = { 'k' }
static const symbol s_8_1 [2] = { 'a', 'k' }
static const symbol s_8_2 [2] = { 'e', 'k' }
static const symbol s_8_3 [2] = { 'o', 'k' }
static const symbol s_8_4 [3] = { 0xC3, 0xA1, 'k' }
static const symbol s_8_5 [3] = { 0xC3, 0xA9, 'k' }
static const symbol s_8_6 [3] = { 0xC3, 0xB6, 'k' }
static struct among a_8 [7]
static const symbol s_9_0 [3] = { 0xC3, 0xA9, 'i' }
static const symbol s_9_1 [5] = { 0xC3, 0xA1, 0xC3, 0xA9, 'i' }
static const symbol s_9_2 [5] = { 0xC3, 0xA9, 0xC3, 0xA9, 'i' }
static const symbol s_9_3 [2] = { 0xC3, 0xA9 }
static const symbol s_9_4 [3] = { 'k', 0xC3, 0xA9 }
static const symbol s_9_5 [4] = { 'a', 'k', 0xC3, 0xA9 }
static const symbol s_9_6 [4] = { 'e', 'k', 0xC3, 0xA9 }
static const symbol s_9_7 [4] = { 'o', 'k', 0xC3, 0xA9 }
static const symbol s_9_8 [5] = { 0xC3, 0xA1, 'k', 0xC3, 0xA9 }
static const symbol s_9_9 [5] = { 0xC3, 0xA9, 'k', 0xC3, 0xA9 }
static const symbol s_9_10 [5] = { 0xC3, 0xB6, 'k', 0xC3, 0xA9 }
static const symbol s_9_11 [4] = { 0xC3, 0xA9, 0xC3, 0xA9 }
static struct among a_9 [12]
static const symbol s_10_0 [1] = { 'a' }
static const symbol s_10_1 [2] = { 'j', 'a' }
static const symbol s_10_2 [1] = { 'd' }
static const symbol s_10_3 [2] = { 'a', 'd' }
static const symbol s_10_4 [2] = { 'e', 'd' }
static const symbol s_10_5 [2] = { 'o', 'd' }
static const symbol s_10_6 [3] = { 0xC3, 0xA1, 'd' }
static const symbol s_10_7 [3] = { 0xC3, 0xA9, 'd' }
static const symbol s_10_8 [3] = { 0xC3, 0xB6, 'd' }
static const symbol s_10_9 [1] = { 'e' }
static const symbol s_10_10 [2] = { 'j', 'e' }
static const symbol s_10_11 [2] = { 'n', 'k' }
static const symbol s_10_12 [3] = { 'u', 'n', 'k' }
static const symbol s_10_13 [4] = { 0xC3, 0xA1, 'n', 'k' }
static const symbol s_10_14 [4] = { 0xC3, 0xA9, 'n', 'k' }
static const symbol s_10_15 [4] = { 0xC3, 0xBC, 'n', 'k' }
static const symbol s_10_16 [2] = { 'u', 'k' }
static const symbol s_10_17 [3] = { 'j', 'u', 'k' }
static const symbol s_10_18 [5] = { 0xC3, 0xA1, 'j', 'u', 'k' }
static const symbol s_10_19 [3] = { 0xC3, 0xBC, 'k' }
static const symbol s_10_20 [4] = { 'j', 0xC3, 0xBC, 'k' }
static const symbol s_10_21 [6] = { 0xC3, 0xA9, 'j', 0xC3, 0xBC, 'k' }
static const symbol s_10_22 [1] = { 'm' }
static const symbol s_10_23 [2] = { 'a', 'm' }
static const symbol s_10_24 [2] = { 'e', 'm' }
static const symbol s_10_25 [2] = { 'o', 'm' }
static const symbol s_10_26 [3] = { 0xC3, 0xA1, 'm' }
static const symbol s_10_27 [3] = { 0xC3, 0xA9, 'm' }
static const symbol s_10_28 [1] = { 'o' }
static const symbol s_10_29 [2] = { 0xC3, 0xA1 }
static const symbol s_10_30 [2] = { 0xC3, 0xA9 }
static struct among a_10 [31]
static const symbol s_11_0 [2] = { 'i', 'd' }
static const symbol s_11_1 [3] = { 'a', 'i', 'd' }
static const symbol s_11_2 [4] = { 'j', 'a', 'i', 'd' }
static const symbol s_11_3 [3] = { 'e', 'i', 'd' }
static const symbol s_11_4 [4] = { 'j', 'e', 'i', 'd' }
static const symbol s_11_5 [4] = { 0xC3, 0xA1, 'i', 'd' }
static const symbol s_11_6 [4] = { 0xC3, 0xA9, 'i', 'd' }
static const symbol s_11_7 [1] = { 'i' }
static const symbol s_11_8 [2] = { 'a', 'i' }
static const symbol s_11_9 [3] = { 'j', 'a', 'i' }
static const symbol s_11_10 [2] = { 'e', 'i' }
static const symbol s_11_11 [3] = { 'j', 'e', 'i' }
static const symbol s_11_12 [3] = { 0xC3, 0xA1, 'i' }
static const symbol s_11_13 [3] = { 0xC3, 0xA9, 'i' }
static const symbol s_11_14 [4] = { 'i', 't', 'e', 'k' }
static const symbol s_11_15 [5] = { 'e', 'i', 't', 'e', 'k' }
static const symbol s_11_16 [6] = { 'j', 'e', 'i', 't', 'e', 'k' }
static const symbol s_11_17 [6] = { 0xC3, 0xA9, 'i', 't', 'e', 'k' }
static const symbol s_11_18 [2] = { 'i', 'k' }
static const symbol s_11_19 [3] = { 'a', 'i', 'k' }
static const symbol s_11_20 [4] = { 'j', 'a', 'i', 'k' }
static const symbol s_11_21 [3] = { 'e', 'i', 'k' }
static const symbol s_11_22 [4] = { 'j', 'e', 'i', 'k' }
static const symbol s_11_23 [4] = { 0xC3, 0xA1, 'i', 'k' }
static const symbol s_11_24 [4] = { 0xC3, 0xA9, 'i', 'k' }
static const symbol s_11_25 [3] = { 'i', 'n', 'k' }
static const symbol s_11_26 [4] = { 'a', 'i', 'n', 'k' }
static const symbol s_11_27 [5] = { 'j', 'a', 'i', 'n', 'k' }
static const symbol s_11_28 [4] = { 'e', 'i', 'n', 'k' }
static const symbol s_11_29 [5] = { 'j', 'e', 'i', 'n', 'k' }
static const symbol s_11_30 [5] = { 0xC3, 0xA1, 'i', 'n', 'k' }
static const symbol s_11_31 [5] = { 0xC3, 0xA9, 'i', 'n', 'k' }
static const symbol s_11_32 [5] = { 'a', 'i', 't', 'o', 'k' }
static const symbol s_11_33 [6] = { 'j', 'a', 'i', 't', 'o', 'k' }
static const symbol s_11_34 [6] = { 0xC3, 0xA1, 'i', 't', 'o', 'k' }
static const symbol s_11_35 [2] = { 'i', 'm' }
static const symbol s_11_36 [3] = { 'a', 'i', 'm' }
static const symbol s_11_37 [4] = { 'j', 'a', 'i', 'm' }
static const symbol s_11_38 [3] = { 'e', 'i', 'm' }
static const symbol s_11_39 [4] = { 'j', 'e', 'i', 'm' }
static const symbol s_11_40 [4] = { 0xC3, 0xA1, 'i', 'm' }
static const symbol s_11_41 [4] = { 0xC3, 0xA9, 'i', 'm' }
static struct among a_11 [42]
static const unsigned char g_v [] = { 17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 17, 52, 14 }
static const symbol s_0 [] = { 'a' }
static const symbol s_1 [] = { 'e' }
static const symbol s_2 [] = { 'e' }
static const symbol s_3 [] = { 'a' }
static const symbol s_4 [] = { 'a' }
static const symbol s_5 [] = { 'a' }
static const symbol s_6 [] = { 'e' }
static const symbol s_7 [] = { 'a' }
static const symbol s_8 [] = { 'e' }
static const symbol s_9 [] = { 'e' }
static const symbol s_10 [] = { 'a' }
static const symbol s_11 [] = { 'e' }
static const symbol s_12 [] = { 'a' }
static const symbol s_13 [] = { 'e' }
static const symbol s_14 [] = { 'a' }
static const symbol s_15 [] = { 'e' }
static const symbol s_16 [] = { 'a' }
static const symbol s_17 [] = { 'e' }
static const symbol s_18 [] = { 'a' }
static const symbol s_19 [] = { 'e' }
static const symbol s_20 [] = { 'a' }
static const symbol s_21 [] = { 'e' }
static const symbol s_22 [] = { 'a' }
static const symbol s_23 [] = { 'e' }
static const symbol s_24 [] = { 'a' }
static const symbol s_25 [] = { 'e' }
static const symbol s_26 [] = { 'a' }
static const symbol s_27 [] = { 'e' }
static const symbol s_28 [] = { 'a' }
static const symbol s_29 [] = { 'e' }
static const symbol s_30 [] = { 'a' }
static const symbol s_31 [] = { 'e' }
static const symbol s_32 [] = { 'a' }
static const symbol s_33 [] = { 'e' }
static const symbol s_34 [] = { 'a' }
static const symbol s_35 [] = { 'e' }
Function Documentation
void hungarian_UTF_8_close_env (struct SN_env * z)
struct SN_env* hungarian_UTF_8_create_env (void) [read]
int hungarian_UTF_8_stem (struct SN_env * z)
static int r_case (struct SN_env * z) [static]
Definition at line 630 of file stem_UTF_8_hungarian.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::ket, r_R1(), r_v_ending(), and slice_del().
Referenced by hungarian_UTF_8_stem().
static int r_case_other (struct SN_env * z) [static]
Definition at line 680 of file stem_UTF_8_hungarian.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::ket, SN_env::lb, SN_env::p, r_R1(), s_5, s_6, slice_del(), and slice_from_s().
Referenced by hungarian_UTF_8_stem().
static int r_case_special (struct SN_env * z) [static]
Definition at line 648 of file stem_UTF_8_hungarian.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::ket, SN_env::lb, SN_env::p, r_R1(), s_2, s_3, s_4, and slice_from_s().
Referenced by hungarian_UTF_8_stem().
static int r_double (struct SN_env * z) [static]
Definition at line 568 of file stem_UTF_8_hungarian.cpp.
References SN_env::c, find_among_b(), SN_env::l, SN_env::lb, and SN_env::p.
Referenced by r_factive(), and r_instrum().
static int r_factive (struct SN_env * z) [static]
Definition at line 717 of file stem_UTF_8_hungarian.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::ket, SN_env::lb, SN_env::p, r_double(), r_R1(), r_undouble(), and slice_del().
Referenced by hungarian_UTF_8_stem().
static int r_instrum (struct SN_env * z) [static]
Definition at line 594 of file stem_UTF_8_hungarian.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::ket, SN_env::lb, SN_env::p, r_double(), r_R1(), r_undouble(), and slice_del().
Referenced by hungarian_UTF_8_stem().
static int r_mark_regions (struct SN_env * z) [static]
Definition at line 503 of file stem_UTF_8_hungarian.cpp.
References SN_env::c, find_among(), g_v, SN_env::I, in_grouping_U(), SN_env::l, out_grouping_U(), SN_env::p, and skip_utf8().
static int r_owned (struct SN_env * z) [static]
Definition at line 805 of file stem_UTF_8_hungarian.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::ket, SN_env::lb, SN_env::p, r_R1(), s_10, s_11, s_12, s_13, s_9, slice_del(), and slice_from_s().
Referenced by hungarian_UTF_8_stem().
static int r_plur_owner (struct SN_env * z) [static]
Definition at line 983 of file stem_UTF_8_hungarian.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::ket, SN_env::lb, SN_env::p, r_R1(), s_24, s_25, s_26, s_27, s_28, s_29, s_30, s_31, s_32, s_33, s_34, s_35, slice_del(), and slice_from_s().
Referenced by hungarian_UTF_8_stem().
static int r_plural (struct SN_env * z) [static]
Definition at line 753 of file stem_UTF_8_hungarian.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::ket, SN_env::lb, SN_env::p, r_R1(), s_7, s_8, slice_del(), and slice_from_s().
Referenced by hungarian_UTF_8_stem().
static int r_R1 (struct SN_env * z) [static]
Definition at line 536 of file stem_UTF_8_hungarian.cpp.
References SN_env::c, and SN_env::I.
static int r_sing_owner (struct SN_env * z) [static]
Definition at line 867 of file stem_UTF_8_hungarian.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::ket, r_R1(), s_14, s_15, s_16, s_17, s_18, s_19, s_20, s_21, s_22, s_23, slice_del(), and slice_from_s().
Referenced by hungarian_UTF_8_stem().
static int r_undouble (struct SN_env * z) [static]
Definition at line 577 of file stem_UTF_8_hungarian.cpp.
References SN_env::bra, SN_env::c, SN_env::ket, SN_env::l, SN_env::lb, SN_env::p, skip_utf8(), and slice_del().
static int r_v_ending (struct SN_env * z) [static]
Definition at line 541 of file stem_UTF_8_hungarian.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::ket, SN_env::lb, SN_env::p, r_R1(), s_0, s_1, and slice_from_s().
Referenced by r_case().
Variable Documentation
struct among a_0[8] [static]
Initial value:
{
 { 2, s_0_0, -1, -1, 0},
 { 3, s_0_1, -1, -1, 0},
 { 2, s_0_2, -1, -1, 0},
 { 2, s_0_3, -1, -1, 0},
 { 2, s_0_4, -1, -1, 0},
 { 2, s_0_5, -1, -1, 0},
 { 2, s_0_6, -1, -1, 0},
 { 2, s_0_7, -1, -1, 0}
}
Definition at line 49 of file stem_UTF_8_hungarian.cpp.
struct among a_1[2] [static]
Initial value:
{
 { 2, s_1_0, -1, 1, 0},
 { 2, s_1_1, -1, 2, 0}
}
Definition at line 64 of file stem_UTF_8_hungarian.cpp.
struct among a_10[31] [static]
Definition at line 340 of file stem_UTF_8_hungarian.cpp.
struct among a_11[42] [static]
Definition at line 418 of file stem_UTF_8_hungarian.cpp.
struct among a_2[23] [static]
Initial value:
{
 { 2, s_2_0, -1, -1, 0},
 { 2, s_2_1, -1, -1, 0},
 { 2, s_2_2, -1, -1, 0},
 { 2, s_2_3, -1, -1, 0},
 { 2, s_2_4, -1, -1, 0},
 { 2, s_2_5, -1, -1, 0},
 { 2, s_2_6, -1, -1, 0},
 { 2, s_2_7, -1, -1, 0},
 { 2, s_2_8, -1, -1, 0},
 { 2, s_2_9, -1, -1, 0},
 { 2, s_2_10, -1, -1, 0},
 { 2, s_2_11, -1, -1, 0},
 { 3, s_2_12, -1, -1, 0},
 { 2, s_2_13, -1, -1, 0},
 { 3, s_2_14, -1, -1, 0},
 { 2, s_2_15, -1, -1, 0},
 { 2, s_2_16, -1, -1, 0},
 { 3, s_2_17, -1, -1, 0},
 { 3, s_2_18, -1, -1, 0},
 { 3, s_2_19, -1, -1, 0},
 { 3, s_2_20, -1, -1, 0},
 { 3, s_2_21, -1, -1, 0},
 { 2, s_2_22, -1, -1, 0}
}
Definition at line 94 of file stem_UTF_8_hungarian.cpp.
struct among a_3[2] [static]
Initial value:
{
 { 2, s_3_0, -1, 1, 0},
 { 2, s_3_1, -1, 2, 0}
}
Definition at line 124 of file stem_UTF_8_hungarian.cpp.
struct among a_4[44] [static]
Definition at line 175 of file stem_UTF_8_hungarian.cpp.
struct among a_5[3] [static]
Initial value:
{
 { 3, s_5_0, -1, 2, 0},
 { 3, s_5_1, -1, 1, 0},
 { 8, s_5_2, -1, 3, 0}
}
Definition at line 227 of file stem_UTF_8_hungarian.cpp.
struct among a_6[6] [static]
Initial value:
{
 { 4, s_6_0, -1, 2, 0},
 { 5, s_6_1, 0, 1, 0},
 { 6, s_6_2, 0, 3, 0},
 { 5, s_6_3, -1, 2, 0},
 { 6, s_6_4, 3, 1, 0},
 { 7, s_6_5, 3, 4, 0}
}
Definition at line 241 of file stem_UTF_8_hungarian.cpp.
struct among a_7[2] [static]
Initial value:
{
 { 2, s_7_0, -1, 1, 0},
 { 2, s_7_1, -1, 2, 0}
}
Definition at line 254 of file stem_UTF_8_hungarian.cpp.
struct among a_8[7] [static]
Initial value:
{
 { 1, s_8_0, -1, 7, 0},
 { 2, s_8_1, 0, 4, 0},
 { 2, s_8_2, 0, 6, 0},
 { 2, s_8_3, 0, 5, 0},
 { 3, s_8_4, 0, 1, 0},
 { 3, s_8_5, 0, 2, 0},
 { 3, s_8_6, 0, 3, 0}
}
Definition at line 268 of file stem_UTF_8_hungarian.cpp.
struct among a_9[12] [static]
Initial value:
{
 { 3, s_9_0, -1, 7, 0},
 { 5, s_9_1, 0, 6, 0},
 { 5, s_9_2, 0, 5, 0},
 { 2, s_9_3, -1, 9, 0},
 { 3, s_9_4, 3, 4, 0},
 { 4, s_9_5, 4, 1, 0},
 { 4, s_9_6, 4, 1, 0},
 { 4, s_9_7, 4, 1, 0},
 { 5, s_9_8, 4, 3, 0},
 { 5, s_9_9, 4, 2, 0},
 { 5, s_9_10, 4, 1, 0},
 { 4, s_9_11, 3, 8, 0}
}
Definition at line 292 of file stem_UTF_8_hungarian.cpp.
const unsigned char g_v[] = { 17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 17, 52, 14 } [static]
Definition at line 464 of file stem_UTF_8_hungarian.cpp.
const symbol s_0[] = { 'a' } [static]
Definition at line 466 of file stem_UTF_8_hungarian.cpp.
const symbol s_0_0[2] = { 'c', 's' } [static]
Definition at line 40 of file stem_UTF_8_hungarian.cpp.
const symbol s_0_1[3] = { 'd', 'z', 's' } [static]
Definition at line 41 of file stem_UTF_8_hungarian.cpp.
const symbol s_0_2[2] = { 'g', 'y' } [static]
Definition at line 42 of file stem_UTF_8_hungarian.cpp.
const symbol s_0_3[2] = { 'l', 'y' } [static]
Definition at line 43 of file stem_UTF_8_hungarian.cpp.
const symbol s_0_4[2] = { 'n', 'y' } [static]
Definition at line 44 of file stem_UTF_8_hungarian.cpp.
const symbol s_0_5[2] = { 's', 'z' } [static]
Definition at line 45 of file stem_UTF_8_hungarian.cpp.
const symbol s_0_6[2] = { 't', 'y' } [static]
Definition at line 46 of file stem_UTF_8_hungarian.cpp.
const symbol s_0_7[2] = { 'z', 's' } [static]
Definition at line 47 of file stem_UTF_8_hungarian.cpp.
const symbol s_1[] = { 'e' } [static]
Definition at line 467 of file stem_UTF_8_hungarian.cpp.
const symbol s_10[] = { 'a' } [static]
Definition at line 476 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_0[1] = { 'a' } [static]
Definition at line 308 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_1[2] = { 'j', 'a' } [static]
Definition at line 309 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_10[2] = { 'j', 'e' } [static]
Definition at line 318 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_11[2] = { 'n', 'k' } [static]
Definition at line 319 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_12[3] = { 'u', 'n', 'k' } [static]
Definition at line 320 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_13[4] = { 0xC3, 0xA1, 'n', 'k' } [static]
Definition at line 321 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_14[4] = { 0xC3, 0xA9, 'n', 'k' } [static]
Definition at line 322 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_15[4] = { 0xC3, 0xBC, 'n', 'k' } [static]
Definition at line 323 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_16[2] = { 'u', 'k' } [static]
Definition at line 324 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_17[3] = { 'j', 'u', 'k' } [static]
Definition at line 325 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_18[5] = { 0xC3, 0xA1, 'j', 'u', 'k' } [static]
Definition at line 326 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_19[3] = { 0xC3, 0xBC, 'k' } [static]
Definition at line 327 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_2[1] = { 'd' } [static]
Definition at line 310 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_20[4] = { 'j', 0xC3, 0xBC, 'k' } [static]
Definition at line 328 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_21[6] = { 0xC3, 0xA9, 'j', 0xC3, 0xBC, 'k' } [static]
Definition at line 329 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_22[1] = { 'm' } [static]
Definition at line 330 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_23[2] = { 'a', 'm' } [static]
Definition at line 331 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_24[2] = { 'e', 'm' } [static]
Definition at line 332 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_25[2] = { 'o', 'm' } [static]
Definition at line 333 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_26[3] = { 0xC3, 0xA1, 'm' } [static]
Definition at line 334 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_27[3] = { 0xC3, 0xA9, 'm' } [static]
Definition at line 335 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_28[1] = { 'o' } [static]
Definition at line 336 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_29[2] = { 0xC3, 0xA1 } [static]
Definition at line 337 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_3[2] = { 'a', 'd' } [static]
Definition at line 311 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_30[2] = { 0xC3, 0xA9 } [static]
Definition at line 338 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_4[2] = { 'e', 'd' } [static]
Definition at line 312 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_5[2] = { 'o', 'd' } [static]
Definition at line 313 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_6[3] = { 0xC3, 0xA1, 'd' } [static]
Definition at line 314 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_7[3] = { 0xC3, 0xA9, 'd' } [static]
Definition at line 315 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_8[3] = { 0xC3, 0xB6, 'd' } [static]
Definition at line 316 of file stem_UTF_8_hungarian.cpp.
const symbol s_10_9[1] = { 'e' } [static]
Definition at line 317 of file stem_UTF_8_hungarian.cpp.
const symbol s_11[] = { 'e' } [static]
Definition at line 477 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_0[2] = { 'i', 'd' } [static]
Definition at line 375 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_1[3] = { 'a', 'i', 'd' } [static]
Definition at line 376 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_10[2] = { 'e', 'i' } [static]
Definition at line 385 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_11[3] = { 'j', 'e', 'i' } [static]
Definition at line 386 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_12[3] = { 0xC3, 0xA1, 'i' } [static]
Definition at line 387 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_13[3] = { 0xC3, 0xA9, 'i' } [static]
Definition at line 388 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_14[4] = { 'i', 't', 'e', 'k' } [static]
Definition at line 389 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_15[5] = { 'e', 'i', 't', 'e', 'k' } [static]
Definition at line 390 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_16[6] = { 'j', 'e', 'i', 't', 'e', 'k' } [static]
Definition at line 391 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_17[6] = { 0xC3, 0xA9, 'i', 't', 'e', 'k' } [static]
Definition at line 392 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_18[2] = { 'i', 'k' } [static]
Definition at line 393 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_19[3] = { 'a', 'i', 'k' } [static]
Definition at line 394 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_2[4] = { 'j', 'a', 'i', 'd' } [static]
Definition at line 377 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_20[4] = { 'j', 'a', 'i', 'k' } [static]
Definition at line 395 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_21[3] = { 'e', 'i', 'k' } [static]
Definition at line 396 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_22[4] = { 'j', 'e', 'i', 'k' } [static]
Definition at line 397 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_23[4] = { 0xC3, 0xA1, 'i', 'k' } [static]
Definition at line 398 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_24[4] = { 0xC3, 0xA9, 'i', 'k' } [static]
Definition at line 399 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_25[3] = { 'i', 'n', 'k' } [static]
Definition at line 400 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_26[4] = { 'a', 'i', 'n', 'k' } [static]
Definition at line 401 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_27[5] = { 'j', 'a', 'i', 'n', 'k' } [static]
Definition at line 402 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_28[4] = { 'e', 'i', 'n', 'k' } [static]
Definition at line 403 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_29[5] = { 'j', 'e', 'i', 'n', 'k' } [static]
Definition at line 404 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_3[3] = { 'e', 'i', 'd' } [static]
Definition at line 378 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_30[5] = { 0xC3, 0xA1, 'i', 'n', 'k' } [static]
Definition at line 405 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_31[5] = { 0xC3, 0xA9, 'i', 'n', 'k' } [static]
Definition at line 406 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_32[5] = { 'a', 'i', 't', 'o', 'k' } [static]
Definition at line 407 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_33[6] = { 'j', 'a', 'i', 't', 'o', 'k' } [static]
Definition at line 408 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_34[6] = { 0xC3, 0xA1, 'i', 't', 'o', 'k' } [static]
Definition at line 409 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_35[2] = { 'i', 'm' } [static]
Definition at line 410 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_36[3] = { 'a', 'i', 'm' } [static]
Definition at line 411 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_37[4] = { 'j', 'a', 'i', 'm' } [static]
Definition at line 412 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_38[3] = { 'e', 'i', 'm' } [static]
Definition at line 413 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_39[4] = { 'j', 'e', 'i', 'm' } [static]
Definition at line 414 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_4[4] = { 'j', 'e', 'i', 'd' } [static]
Definition at line 379 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_40[4] = { 0xC3, 0xA1, 'i', 'm' } [static]
Definition at line 415 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_41[4] = { 0xC3, 0xA9, 'i', 'm' } [static]
Definition at line 416 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_5[4] = { 0xC3, 0xA1, 'i', 'd' } [static]
Definition at line 380 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_6[4] = { 0xC3, 0xA9, 'i', 'd' } [static]
Definition at line 381 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_7[1] = { 'i' } [static]
Definition at line 382 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_8[2] = { 'a', 'i' } [static]
Definition at line 383 of file stem_UTF_8_hungarian.cpp.
const symbol s_11_9[3] = { 'j', 'a', 'i' } [static]
Definition at line 384 of file stem_UTF_8_hungarian.cpp.
const symbol s_12[] = { 'a' } [static]
Definition at line 478 of file stem_UTF_8_hungarian.cpp.
const symbol s_13[] = { 'e' } [static]
Definition at line 479 of file stem_UTF_8_hungarian.cpp.
const symbol s_14[] = { 'a' } [static]
Definition at line 480 of file stem_UTF_8_hungarian.cpp.
const symbol s_15[] = { 'e' } [static]
Definition at line 481 of file stem_UTF_8_hungarian.cpp.
const symbol s_16[] = { 'a' } [static]
Definition at line 482 of file stem_UTF_8_hungarian.cpp.
const symbol s_17[] = { 'e' } [static]
Definition at line 483 of file stem_UTF_8_hungarian.cpp.
const symbol s_18[] = { 'a' } [static]
Definition at line 484 of file stem_UTF_8_hungarian.cpp.
const symbol s_19[] = { 'e' } [static]
Definition at line 485 of file stem_UTF_8_hungarian.cpp.
const symbol s_1_0[2] = { 0xC3, 0xA1 } [static]
Definition at line 61 of file stem_UTF_8_hungarian.cpp.
const symbol s_1_1[2] = { 0xC3, 0xA9 } [static]
Definition at line 62 of file stem_UTF_8_hungarian.cpp.
const symbol s_2[] = { 'e' } [static]
Definition at line 468 of file stem_UTF_8_hungarian.cpp.
const symbol s_20[] = { 'a' } [static]
Definition at line 486 of file stem_UTF_8_hungarian.cpp.
const symbol s_21[] = { 'e' } [static]
Definition at line 487 of file stem_UTF_8_hungarian.cpp.
const symbol s_22[] = { 'a' } [static]
Definition at line 488 of file stem_UTF_8_hungarian.cpp.
const symbol s_23[] = { 'e' } [static]
Definition at line 489 of file stem_UTF_8_hungarian.cpp.
const symbol s_24[] = { 'a' } [static]
Definition at line 490 of file stem_UTF_8_hungarian.cpp.
const symbol s_25[] = { 'e' } [static]
Definition at line 491 of file stem_UTF_8_hungarian.cpp.
const symbol s_26[] = { 'a' } [static]
Definition at line 492 of file stem_UTF_8_hungarian.cpp.
const symbol s_27[] = { 'e' } [static]
Definition at line 493 of file stem_UTF_8_hungarian.cpp.
const symbol s_28[] = { 'a' } [static]
Definition at line 494 of file stem_UTF_8_hungarian.cpp.
const symbol s_29[] = { 'e' } [static]
Definition at line 495 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_0[2] = { 'b', 'b' } [static]
Definition at line 70 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_1[2] = { 'c', 'c' } [static]
Definition at line 71 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_10[2] = { 'p', 'p' } [static]
Definition at line 80 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_11[2] = { 'r', 'r' } [static]
Definition at line 81 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_12[3] = { 'c', 'c', 's' } [static]
Definition at line 82 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_13[2] = { 's', 's' } [static]
Definition at line 83 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_14[3] = { 'z', 'z', 's' } [static]
Definition at line 84 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_15[2] = { 't', 't' } [static]
Definition at line 85 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_16[2] = { 'v', 'v' } [static]
Definition at line 86 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_17[3] = { 'g', 'g', 'y' } [static]
Definition at line 87 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_18[3] = { 'l', 'l', 'y' } [static]
Definition at line 88 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_19[3] = { 'n', 'n', 'y' } [static]
Definition at line 89 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_2[2] = { 'd', 'd' } [static]
Definition at line 72 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_20[3] = { 't', 't', 'y' } [static]
Definition at line 90 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_21[3] = { 's', 's', 'z' } [static]
Definition at line 91 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_22[2] = { 'z', 'z' } [static]
Definition at line 92 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_3[2] = { 'f', 'f' } [static]
Definition at line 73 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_4[2] = { 'g', 'g' } [static]
Definition at line 74 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_5[2] = { 'j', 'j' } [static]
Definition at line 75 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_6[2] = { 'k', 'k' } [static]
Definition at line 76 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_7[2] = { 'l', 'l' } [static]
Definition at line 77 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_8[2] = { 'm', 'm' } [static]
Definition at line 78 of file stem_UTF_8_hungarian.cpp.
const symbol s_2_9[2] = { 'n', 'n' } [static]
Definition at line 79 of file stem_UTF_8_hungarian.cpp.
const symbol s_3[] = { 'a' } [static]
Definition at line 469 of file stem_UTF_8_hungarian.cpp.
const symbol s_30[] = { 'a' } [static]
Definition at line 496 of file stem_UTF_8_hungarian.cpp.
const symbol s_31[] = { 'e' } [static]
Definition at line 497 of file stem_UTF_8_hungarian.cpp.
const symbol s_32[] = { 'a' } [static]
Definition at line 498 of file stem_UTF_8_hungarian.cpp.
const symbol s_33[] = { 'e' } [static]
Definition at line 499 of file stem_UTF_8_hungarian.cpp.
const symbol s_34[] = { 'a' } [static]
Definition at line 500 of file stem_UTF_8_hungarian.cpp.
const symbol s_35[] = { 'e' } [static]
Definition at line 501 of file stem_UTF_8_hungarian.cpp.
const symbol s_3_0[2] = { 'a', 'l' } [static]
Definition at line 121 of file stem_UTF_8_hungarian.cpp.
const symbol s_3_1[2] = { 'e', 'l' } [static]
Definition at line 122 of file stem_UTF_8_hungarian.cpp.
const symbol s_4[] = { 'a' } [static]
Definition at line 470 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_0[2] = { 'b', 'a' } [static]
Definition at line 130 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_1[2] = { 'r', 'a' } [static]
Definition at line 131 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_10[4] = { 'n', 0xC3, 0xA1, 'l' } [static]
Definition at line 140 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_11[4] = { 'n', 0xC3, 0xA9, 'l' } [static]
Definition at line 141 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_12[4] = { 'b', 0xC3, 0xB3, 'l' } [static]
Definition at line 142 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_13[4] = { 'r', 0xC3, 0xB3, 'l' } [static]
Definition at line 143 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_14[4] = { 't', 0xC3, 0xB3, 'l' } [static]
Definition at line 144 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_15[4] = { 'b', 0xC3, 0xB5, 'l' } [static]
Definition at line 145 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_16[4] = { 'r', 0xC3, 0xB5, 'l' } [static]
Definition at line 146 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_17[4] = { 't', 0xC3, 0xB5, 'l' } [static]
Definition at line 147 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_18[3] = { 0xC3, 0xBC, 'l' } [static]
Definition at line 148 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_19[1] = { 'n' } [static]
Definition at line 149 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_2[2] = { 'b', 'e' } [static]
Definition at line 132 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_20[2] = { 'a', 'n' } [static]
Definition at line 150 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_21[3] = { 'b', 'a', 'n' } [static]
Definition at line 151 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_22[2] = { 'e', 'n' } [static]
Definition at line 152 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_23[3] = { 'b', 'e', 'n' } [static]
Definition at line 153 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_24[7] = { 'k', 0xC3, 0xA9, 'p', 'p', 'e', 'n' } [static]
Definition at line 154 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_25[2] = { 'o', 'n' } [static]
Definition at line 155 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_26[3] = { 0xC3, 0xB6, 'n' } [static]
Definition at line 156 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_27[5] = { 'k', 0xC3, 0xA9, 'p', 'p' } [static]
Definition at line 157 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_28[3] = { 'k', 'o', 'r' } [static]
Definition at line 158 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_29[1] = { 't' } [static]
Definition at line 159 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_3[2] = { 'r', 'e' } [static]
Definition at line 133 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_30[2] = { 'a', 't' } [static]
Definition at line 160 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_31[2] = { 'e', 't' } [static]
Definition at line 161 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_32[5] = { 'k', 0xC3, 0xA9, 'n', 't' } [static]
Definition at line 162 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_33[7] = { 'a', 'n', 'k', 0xC3, 0xA9, 'n', 't' } [static]
Definition at line 163 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_34[7] = { 'e', 'n', 'k', 0xC3, 0xA9, 'n', 't' } [static]
Definition at line 164 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_35[7] = { 'o', 'n', 'k', 0xC3, 0xA9, 'n', 't' } [static]
Definition at line 165 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_36[2] = { 'o', 't' } [static]
Definition at line 166 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_37[4] = { 0xC3, 0xA9, 'r', 't' } [static]
Definition at line 167 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_38[3] = { 0xC3, 0xB6, 't' } [static]
Definition at line 168 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_39[3] = { 'h', 'e', 'z' } [static]
Definition at line 169 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_4[2] = { 'i', 'g' } [static]
Definition at line 134 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_40[3] = { 'h', 'o', 'z' } [static]
Definition at line 170 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_41[4] = { 'h', 0xC3, 0xB6, 'z' } [static]
Definition at line 171 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_42[3] = { 'v', 0xC3, 0xA1 } [static]
Definition at line 172 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_43[3] = { 'v', 0xC3, 0xA9 } [static]
Definition at line 173 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_5[3] = { 'n', 'a', 'k' } [static]
Definition at line 135 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_6[3] = { 'n', 'e', 'k' } [static]
Definition at line 136 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_7[3] = { 'v', 'a', 'l' } [static]
Definition at line 137 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_8[3] = { 'v', 'e', 'l' } [static]
Definition at line 138 of file stem_UTF_8_hungarian.cpp.
const symbol s_4_9[2] = { 'u', 'l' } [static]
Definition at line 139 of file stem_UTF_8_hungarian.cpp.
const symbol s_5[] = { 'a' } [static]
Definition at line 471 of file stem_UTF_8_hungarian.cpp.
const symbol s_5_0[3] = { 0xC3, 0xA1, 'n' } [static]
Definition at line 223 of file stem_UTF_8_hungarian.cpp.
const symbol s_5_1[3] = { 0xC3, 0xA9, 'n' } [static]
Definition at line 224 of file stem_UTF_8_hungarian.cpp.
const symbol s_5_2[8] = { 0xC3, 0xA1, 'n', 'k', 0xC3, 0xA9, 'n', 't' } [static]
Definition at line 225 of file stem_UTF_8_hungarian.cpp.
const symbol s_6[] = { 'e' } [static]
Definition at line 472 of file stem_UTF_8_hungarian.cpp.
const symbol s_6_0[4] = { 's', 't', 'u', 'l' } [static]
Definition at line 234 of file stem_UTF_8_hungarian.cpp.
const symbol s_6_1[5] = { 'a', 's', 't', 'u', 'l' } [static]
Definition at line 235 of file stem_UTF_8_hungarian.cpp.
const symbol s_6_2[6] = { 0xC3, 0xA1, 's', 't', 'u', 'l' } [static]
Definition at line 236 of file stem_UTF_8_hungarian.cpp.
const symbol s_6_3[5] = { 's', 't', 0xC3, 0xBC, 'l' } [static]
Definition at line 237 of file stem_UTF_8_hungarian.cpp.
const symbol s_6_4[6] = { 'e', 's', 't', 0xC3, 0xBC, 'l' } [static]
Definition at line 238 of file stem_UTF_8_hungarian.cpp.
const symbol s_6_5[7] = { 0xC3, 0xA9, 's', 't', 0xC3, 0xBC, 'l' } [static]
Definition at line 239 of file stem_UTF_8_hungarian.cpp.
const symbol s_7[] = { 'a' } [static]
Definition at line 473 of file stem_UTF_8_hungarian.cpp.
const symbol s_7_0[2] = { 0xC3, 0xA1 } [static]
Definition at line 251 of file stem_UTF_8_hungarian.cpp.
const symbol s_7_1[2] = { 0xC3, 0xA9 } [static]
Definition at line 252 of file stem_UTF_8_hungarian.cpp.
const symbol s_8[] = { 'e' } [static]
Definition at line 474 of file stem_UTF_8_hungarian.cpp.
const symbol s_8_0[1] = { 'k' } [static]
Definition at line 260 of file stem_UTF_8_hungarian.cpp.
const symbol s_8_1[2] = { 'a', 'k' } [static]
Definition at line 261 of file stem_UTF_8_hungarian.cpp.
const symbol s_8_2[2] = { 'e', 'k' } [static]
Definition at line 262 of file stem_UTF_8_hungarian.cpp.
const symbol s_8_3[2] = { 'o', 'k' } [static]
Definition at line 263 of file stem_UTF_8_hungarian.cpp.
const symbol s_8_4[3] = { 0xC3, 0xA1, 'k' } [static]
Definition at line 264 of file stem_UTF_8_hungarian.cpp.
const symbol s_8_5[3] = { 0xC3, 0xA9, 'k' } [static]
Definition at line 265 of file stem_UTF_8_hungarian.cpp.
const symbol s_8_6[3] = { 0xC3, 0xB6, 'k' } [static]
Definition at line 266 of file stem_UTF_8_hungarian.cpp.
const symbol s_9[] = { 'e' } [static]
Definition at line 475 of file stem_UTF_8_hungarian.cpp.
const symbol s_9_0[3] = { 0xC3, 0xA9, 'i' } [static]
Definition at line 279 of file stem_UTF_8_hungarian.cpp.
const symbol s_9_1[5] = { 0xC3, 0xA1, 0xC3, 0xA9, 'i' } [static]
Definition at line 280 of file stem_UTF_8_hungarian.cpp.
const symbol s_9_10[5] = { 0xC3, 0xB6, 'k', 0xC3, 0xA9 } [static]
Definition at line 289 of file stem_UTF_8_hungarian.cpp.
const symbol s_9_11[4] = { 0xC3, 0xA9, 0xC3, 0xA9 } [static]
Definition at line 290 of file stem_UTF_8_hungarian.cpp.
const symbol s_9_2[5] = { 0xC3, 0xA9, 0xC3, 0xA9, 'i' } [static]
Definition at line 281 of file stem_UTF_8_hungarian.cpp.
const symbol s_9_3[2] = { 0xC3, 0xA9 } [static]
Definition at line 282 of file stem_UTF_8_hungarian.cpp.
const symbol s_9_4[3] = { 'k', 0xC3, 0xA9 } [static]
Definition at line 283 of file stem_UTF_8_hungarian.cpp.
const symbol s_9_5[4] = { 'a', 'k', 0xC3, 0xA9 } [static]
Definition at line 284 of file stem_UTF_8_hungarian.cpp.
const symbol s_9_6[4] = { 'e', 'k', 0xC3, 0xA9 } [static]
Definition at line 285 of file stem_UTF_8_hungarian.cpp.
const symbol s_9_7[4] = { 'o', 'k', 0xC3, 0xA9 } [static]
Definition at line 286 of file stem_UTF_8_hungarian.cpp.
const symbol s_9_8[5] = { 0xC3, 0xA1, 'k', 0xC3, 0xA9 } [static]
Definition at line 287 of file stem_UTF_8_hungarian.cpp.
const symbol s_9_9[5] = { 0xC3, 0xA9, 'k', 0xC3, 0xA9 } [static]
Definition at line 288 of file stem_UTF_8_hungarian.cpp.