/disk/workspace-cpp/la-manager/include/stem/stem_UTF_8_hungarian.h File Reference
Functions
struct SN_env * hungarian_UTF_8_create_env (void)
void hungarian_UTF_8_close_env (struct SN_env *z)
int hungarian_UTF_8_stem (struct SN_env *z)
Function Documentation
void hungarian_UTF_8_close_env (struct SN_env * z)
Definition at line 1234 of file stem_UTF_8_hungarian.cpp.
References SN_close_env().
struct SN_env * hungarian_UTF_8_create_env (void) [read]
Definition at line 1232 of file stem_UTF_8_hungarian.cpp.
References SN_create_env().
int hungarian_UTF_8_stem (struct SN_env * z)
Definition at line 1145 of file stem_UTF_8_hungarian.cpp.
References SN_env::c, SN_env::l, SN_env::lb, r_case(), r_case_other(), r_case_special(), r_factive(), r_instrum(), r_mark_regions(), r_owned(), r_plur_owner(), r_plural(), and r_sing_owner().