/disk/workspace-cpp/la-manager/source/stem/stem_UTF_8_danish.cpp File Reference
#include <stem/header.h>
Functions
int danish_UTF_8_stem (struct SN_env *z)
static int r_undouble (struct SN_env *z)
static int r_other_suffix (struct SN_env *z)
static int r_consonant_pair (struct SN_env *z)
static int r_main_suffix (struct SN_env *z)
static int r_mark_regions (struct SN_env *z)
struct SN_env * danish_UTF_8_create_env (void)
void danish_UTF_8_close_env (struct SN_env *z)
Variables
static const symbol s_0_0 [3] = { 'h', 'e', 'd' }
static const symbol s_0_1 [5] = { 'e', 't', 'h', 'e', 'd' }
static const symbol s_0_2 [4] = { 'e', 'r', 'e', 'd' }
static const symbol s_0_3 [1] = { 'e' }
static const symbol s_0_4 [5] = { 'e', 'r', 'e', 'd', 'e' }
static const symbol s_0_5 [4] = { 'e', 'n', 'd', 'e' }
static const symbol s_0_6 [6] = { 'e', 'r', 'e', 'n', 'd', 'e' }
static const symbol s_0_7 [3] = { 'e', 'n', 'e' }
static const symbol s_0_8 [4] = { 'e', 'r', 'n', 'e' }
static const symbol s_0_9 [3] = { 'e', 'r', 'e' }
static const symbol s_0_10 [2] = { 'e', 'n' }
static const symbol s_0_11 [5] = { 'h', 'e', 'd', 'e', 'n' }
static const symbol s_0_12 [4] = { 'e', 'r', 'e', 'n' }
static const symbol s_0_13 [2] = { 'e', 'r' }
static const symbol s_0_14 [5] = { 'h', 'e', 'd', 'e', 'r' }
static const symbol s_0_15 [4] = { 'e', 'r', 'e', 'r' }
static const symbol s_0_16 [1] = { 's' }
static const symbol s_0_17 [4] = { 'h', 'e', 'd', 's' }
static const symbol s_0_18 [2] = { 'e', 's' }
static const symbol s_0_19 [5] = { 'e', 'n', 'd', 'e', 's' }
static const symbol s_0_20 [7] = { 'e', 'r', 'e', 'n', 'd', 'e', 's' }
static const symbol s_0_21 [4] = { 'e', 'n', 'e', 's' }
static const symbol s_0_22 [5] = { 'e', 'r', 'n', 'e', 's' }
static const symbol s_0_23 [4] = { 'e', 'r', 'e', 's' }
static const symbol s_0_24 [3] = { 'e', 'n', 's' }
static const symbol s_0_25 [6] = { 'h', 'e', 'd', 'e', 'n', 's' }
static const symbol s_0_26 [5] = { 'e', 'r', 'e', 'n', 's' }
static const symbol s_0_27 [3] = { 'e', 'r', 's' }
static const symbol s_0_28 [3] = { 'e', 't', 's' }
static const symbol s_0_29 [5] = { 'e', 'r', 'e', 't', 's' }
static const symbol s_0_30 [2] = { 'e', 't' }
static const symbol s_0_31 [4] = { 'e', 'r', 'e', 't' }
static struct among a_0 [32]
static const symbol s_1_0 [2] = { 'g', 'd' }
static const symbol s_1_1 [2] = { 'd', 't' }
static const symbol s_1_2 [2] = { 'g', 't' }
static const symbol s_1_3 [2] = { 'k', 't' }
static struct among a_1 [4]
static const symbol s_2_0 [2] = { 'i', 'g' }
static const symbol s_2_1 [3] = { 'l', 'i', 'g' }
static const symbol s_2_2 [4] = { 'e', 'l', 'i', 'g' }
static const symbol s_2_3 [3] = { 'e', 'l', 's' }
static const symbol s_2_4 [5] = { 'l', 0xC3, 0xB8, 's', 't' }
static struct among a_2 [5]
static const unsigned char g_v [] = { 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 0, 128 }
static const unsigned char g_s_ending [] = { 239, 254, 42, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16 }
static const symbol s_0 [] = { 's', 't' }
static const symbol s_1 [] = { 'i', 'g' }
static const symbol s_2 [] = { 'l', 0xC3, 0xB8, 's' }
Function Documentation
void danish_UTF_8_close_env (struct SN_env * z)
Definition at line 339 of file stem_UTF_8_danish.cpp.
References SN_close_env().
struct SN_env * danish_UTF_8_create_env (void) [read]
Definition at line 337 of file stem_UTF_8_danish.cpp.
References SN_create_env().
int danish_UTF_8_stem (struct SN_env * z)
Definition at line 290 of file stem_UTF_8_danish.cpp.
References SN_env::c, SN_env::l, SN_env::lb, r_consonant_pair(), r_main_suffix(), r_mark_regions(), r_other_suffix(), and r_undouble().
static int r_consonant_pair (struct SN_env * z) [static]
Definition at line 192 of file stem_UTF_8_danish.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::I, SN_env::ket, SN_env::l, SN_env::lb, SN_env::p, skip_utf8(), and slice_del().
Referenced by danish_UTF_8_stem(), norwegian_UTF_8_stem(), r_other_suffix(), and swedish_UTF_8_stem().
static int r_main_suffix (struct SN_env * z) [static]
Definition at line 160 of file stem_UTF_8_danish.cpp.
References SN_env::bra, SN_env::c, find_among_b(), g_s_ending, SN_env::I, in_grouping_b_U(), SN_env::ket, SN_env::l, SN_env::lb, SN_env::p, and slice_del().
Referenced by danish_UTF_8_stem(), norwegian_UTF_8_stem(), and swedish_UTF_8_stem().
static int r_mark_regions (struct SN_env * z) [static]
Definition at line 136 of file stem_UTF_8_danish.cpp.
References SN_env::c, g_v, SN_env::I, in_grouping_U(), SN_env::l, out_grouping_U(), SN_env::p, and skip_utf8().
Referenced by danish_UTF_8_stem(), dutch_UTF_8_stem(), english_UTF_8_stem(), finnish_UTF_8_stem(), french_UTF_8_stem(), german_UTF_8_stem(), hungarian_UTF_8_stem(), italian_UTF_8_stem(), norwegian_UTF_8_stem(), portuguese_UTF_8_stem(), romanian_UTF_8_stem(), russian_UTF_8_stem(), spanish_UTF_8_stem(), and swedish_UTF_8_stem().
static int r_other_suffix (struct SN_env * z) [static]
Definition at line 219 of file stem_UTF_8_danish.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), SN_env::I, SN_env::ket, SN_env::l, SN_env::lb, SN_env::p, r_consonant_pair(), s_0, s_1, s_2, slice_del(), and slice_from_s().
Referenced by danish_UTF_8_stem(), norwegian_UTF_8_stem(), and swedish_UTF_8_stem().
static int r_undouble (struct SN_env * z) [static]
Definition at line 269 of file stem_UTF_8_danish.cpp.
References SN_env::bra, SN_env::c, eq_v_b(), g_v, SN_env::I, SN_env::ket, SN_env::l, SN_env::lb, out_grouping_b_U(), SN_env::S, slice_del(), and slice_to().
Referenced by danish_UTF_8_stem(), r_e_ending(), r_en_ending(), r_factive(), r_instrum(), and r_standard_suffix().
Variable Documentation
struct among a_0[32] [static]
Definition at line 64 of file stem_UTF_8_danish.cpp.
struct among a_1[4] [static]
Initial value:
{
 { 2, s_1_0, -1, -1, 0},
 { 2, s_1_1, -1, -1, 0},
 { 2, s_1_2, -1, -1, 0},
 { 2, s_1_3, -1, -1, 0}
}
Definition at line 105 of file stem_UTF_8_danish.cpp.
struct among a_2[5] [static]
Initial value:
{
 { 2, s_2_0, -1, 1, 0},
 { 3, s_2_1, 0, 1, 0},
 { 4, s_2_2, 1, 1, 0},
 { 3, s_2_3, -1, 1, 0},
 { 5, s_2_4, -1, 2, 0}
}
Definition at line 119 of file stem_UTF_8_danish.cpp.
const unsigned char g_s_ending[] = { 239, 254, 42, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16 } [static]
Definition at line 130 of file stem_UTF_8_danish.cpp.
Referenced by r_main_suffix(), and r_standard_suffix().
const unsigned char g_v[] = { 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 0, 128 } [static]
Definition at line 128 of file stem_UTF_8_danish.cpp.
Referenced by r_e_ending(), r_en_ending(), r_i_verb_suffix(), r_main_suffix(), r_mark_regions(), r_prelude(), r_shortv(), r_standard_suffix(), r_Step_1a(), r_Step_1b(), r_Step_1c(), r_un_accent(), r_undouble(), and r_verb_suffix().
const symbol s_0[] = { 's', 't' } [static]
Definition at line 132 of file stem_UTF_8_danish.cpp.
Referenced by r_check_vowel_harmony(), r_main_suffix(), r_other_suffix(), r_perfective_gerund(), r_possessive(), r_postlude(), r_prelude(), and r_v_ending().
const symbol s_0_0[3] = { 'h', 'e', 'd' } [static]
Definition at line 31 of file stem_UTF_8_danish.cpp.
const symbol s_0_1[5] = { 'e', 't', 'h', 'e', 'd' } [static]
Definition at line 32 of file stem_UTF_8_danish.cpp.
const symbol s_0_10[2] = { 'e', 'n' } [static]
Definition at line 41 of file stem_UTF_8_danish.cpp.
const symbol s_0_11[5] = { 'h', 'e', 'd', 'e', 'n' } [static]
Definition at line 42 of file stem_UTF_8_danish.cpp.
const symbol s_0_12[4] = { 'e', 'r', 'e', 'n' } [static]
Definition at line 43 of file stem_UTF_8_danish.cpp.
const symbol s_0_13[2] = { 'e', 'r' } [static]
Definition at line 44 of file stem_UTF_8_danish.cpp.
const symbol s_0_14[5] = { 'h', 'e', 'd', 'e', 'r' } [static]
Definition at line 45 of file stem_UTF_8_danish.cpp.
const symbol s_0_15[4] = { 'e', 'r', 'e', 'r' } [static]
Definition at line 46 of file stem_UTF_8_danish.cpp.
const symbol s_0_16[1] = { 's' } [static]
Definition at line 47 of file stem_UTF_8_danish.cpp.
const symbol s_0_17[4] = { 'h', 'e', 'd', 's' } [static]
Definition at line 48 of file stem_UTF_8_danish.cpp.
const symbol s_0_18[2] = { 'e', 's' } [static]
Definition at line 49 of file stem_UTF_8_danish.cpp.
const symbol s_0_19[5] = { 'e', 'n', 'd', 'e', 's' } [static]
Definition at line 50 of file stem_UTF_8_danish.cpp.
const symbol s_0_2[4] = { 'e', 'r', 'e', 'd' } [static]
Definition at line 33 of file stem_UTF_8_danish.cpp.
const symbol s_0_20[7] = { 'e', 'r', 'e', 'n', 'd', 'e', 's' } [static]
Definition at line 51 of file stem_UTF_8_danish.cpp.
const symbol s_0_21[4] = { 'e', 'n', 'e', 's' } [static]
Definition at line 52 of file stem_UTF_8_danish.cpp.
const symbol s_0_22[5] = { 'e', 'r', 'n', 'e', 's' } [static]
Definition at line 53 of file stem_UTF_8_danish.cpp.
const symbol s_0_23[4] = { 'e', 'r', 'e', 's' } [static]
Definition at line 54 of file stem_UTF_8_danish.cpp.
const symbol s_0_24[3] = { 'e', 'n', 's' } [static]
Definition at line 55 of file stem_UTF_8_danish.cpp.
const symbol s_0_25[6] = { 'h', 'e', 'd', 'e', 'n', 's' } [static]
Definition at line 56 of file stem_UTF_8_danish.cpp.
const symbol s_0_26[5] = { 'e', 'r', 'e', 'n', 's' } [static]
Definition at line 57 of file stem_UTF_8_danish.cpp.
const symbol s_0_27[3] = { 'e', 'r', 's' } [static]
Definition at line 58 of file stem_UTF_8_danish.cpp.
const symbol s_0_28[3] = { 'e', 't', 's' } [static]
Definition at line 59 of file stem_UTF_8_danish.cpp.
const symbol s_0_29[5] = { 'e', 'r', 'e', 't', 's' } [static]
Definition at line 60 of file stem_UTF_8_danish.cpp.
const symbol s_0_3[1] = { 'e' } [static]
Definition at line 34 of file stem_UTF_8_danish.cpp.
const symbol s_0_30[2] = { 'e', 't' } [static]
Definition at line 61 of file stem_UTF_8_danish.cpp.
const symbol s_0_31[4] = { 'e', 'r', 'e', 't' } [static]
Definition at line 62 of file stem_UTF_8_danish.cpp.
const symbol s_0_4[5] = { 'e', 'r', 'e', 'd', 'e' } [static]
Definition at line 35 of file stem_UTF_8_danish.cpp.
const symbol s_0_5[4] = { 'e', 'n', 'd', 'e' } [static]
Definition at line 36 of file stem_UTF_8_danish.cpp.
const symbol s_0_6[6] = { 'e', 'r', 'e', 'n', 'd', 'e' } [static]
Definition at line 37 of file stem_UTF_8_danish.cpp.
const symbol s_0_7[3] = { 'e', 'n', 'e' } [static]
Definition at line 38 of file stem_UTF_8_danish.cpp.
const symbol s_0_8[4] = { 'e', 'r', 'n', 'e' } [static]
Definition at line 39 of file stem_UTF_8_danish.cpp.
const symbol s_0_9[3] = { 'e', 'r', 'e' } [static]
Definition at line 40 of file stem_UTF_8_danish.cpp.
const symbol s_1[] = { 'i', 'g' } [static]
Definition at line 133 of file stem_UTF_8_danish.cpp.
Referenced by r_check_vowel_harmony(), r_main_suffix(), r_other_suffix(), r_perfective_gerund(), r_possessive(), r_postlude(), r_prelude(), and r_v_ending().
const symbol s_1_0[2] = { 'g', 'd' } [static]
Definition at line 100 of file stem_UTF_8_danish.cpp.
const symbol s_1_1[2] = { 'd', 't' } [static]
Definition at line 101 of file stem_UTF_8_danish.cpp.
const symbol s_1_2[2] = { 'g', 't' } [static]
Definition at line 102 of file stem_UTF_8_danish.cpp.
const symbol s_1_3[2] = { 'k', 't' } [static]
Definition at line 103 of file stem_UTF_8_danish.cpp.
const symbol s_2[] = { 'l', 0xC3, 0xB8, 's' } [static]
Definition at line 134 of file stem_UTF_8_danish.cpp.
Referenced by r_adjectival(), r_case_special(), r_check_vowel_harmony(), r_other_suffix(), r_possessive(), r_postlude(), and r_prelude().
const symbol s_2_0[2] = { 'i', 'g' } [static]
Definition at line 113 of file stem_UTF_8_danish.cpp.
const symbol s_2_1[3] = { 'l', 'i', 'g' } [static]
Definition at line 114 of file stem_UTF_8_danish.cpp.
const symbol s_2_2[4] = { 'e', 'l', 'i', 'g' } [static]
Definition at line 115 of file stem_UTF_8_danish.cpp.
const symbol s_2_3[3] = { 'e', 'l', 's' } [static]
Definition at line 116 of file stem_UTF_8_danish.cpp.
const symbol s_2_4[5] = { 'l', 0xC3, 0xB8, 's', 't' } [static]
Definition at line 117 of file stem_UTF_8_danish.cpp.