/disk/workspace-cpp/la-manager/source/stem/stem_UTF_8_italian.cpp File Reference
#include <stem/header.h>
Functions
int italian_UTF_8_stem (struct SN_env *z)
static int r_vowel_suffix (struct SN_env *z)
static int r_verb_suffix (struct SN_env *z)
static int r_standard_suffix (struct SN_env *z)
static int r_attached_pronoun (struct SN_env *z)
static int r_R2 (struct SN_env *z)
static int r_R1 (struct SN_env *z)
static int r_RV (struct SN_env *z)
static int r_mark_regions (struct SN_env *z)
static int r_postlude (struct SN_env *z)
static int r_prelude (struct SN_env *z)
struct SN_env * italian_UTF_8_create_env (void)
void italian_UTF_8_close_env (struct SN_env *z)
Variables
static const symbol s_0_1 [2] = { 'q', 'u' }
static const symbol s_0_2 [2] = { 0xC3, 0xA1 }
static const symbol s_0_3 [2] = { 0xC3, 0xA9 }
static const symbol s_0_4 [2] = { 0xC3, 0xAD }
static const symbol s_0_5 [2] = { 0xC3, 0xB3 }
static const symbol s_0_6 [2] = { 0xC3, 0xBA }
static struct among a_0 [7]
static const symbol s_1_1 [1] = { 'I' }
static const symbol s_1_2 [1] = { 'U' }
static struct among a_1 [3]
static const symbol s_2_0 [2] = { 'l', 'a' }
static const symbol s_2_1 [4] = { 'c', 'e', 'l', 'a' }
static const symbol s_2_2 [6] = { 'g', 'l', 'i', 'e', 'l', 'a' }
static const symbol s_2_3 [4] = { 'm', 'e', 'l', 'a' }
static const symbol s_2_4 [4] = { 't', 'e', 'l', 'a' }
static const symbol s_2_5 [4] = { 'v', 'e', 'l', 'a' }
static const symbol s_2_6 [2] = { 'l', 'e' }
static const symbol s_2_7 [4] = { 'c', 'e', 'l', 'e' }
static const symbol s_2_8 [6] = { 'g', 'l', 'i', 'e', 'l', 'e' }
static const symbol s_2_9 [4] = { 'm', 'e', 'l', 'e' }
static const symbol s_2_10 [4] = { 't', 'e', 'l', 'e' }
static const symbol s_2_11 [4] = { 'v', 'e', 'l', 'e' }
static const symbol s_2_12 [2] = { 'n', 'e' }
static const symbol s_2_13 [4] = { 'c', 'e', 'n', 'e' }
static const symbol s_2_14 [6] = { 'g', 'l', 'i', 'e', 'n', 'e' }
static const symbol s_2_15 [4] = { 'm', 'e', 'n', 'e' }
static const symbol s_2_16 [4] = { 's', 'e', 'n', 'e' }
static const symbol s_2_17 [4] = { 't', 'e', 'n', 'e' }
static const symbol s_2_18 [4] = { 'v', 'e', 'n', 'e' }
static const symbol s_2_19 [2] = { 'c', 'i' }
static const symbol s_2_20 [2] = { 'l', 'i' }
static const symbol s_2_21 [4] = { 'c', 'e', 'l', 'i' }
static const symbol s_2_22 [6] = { 'g', 'l', 'i', 'e', 'l', 'i' }
static const symbol s_2_23 [4] = { 'm', 'e', 'l', 'i' }
static const symbol s_2_24 [4] = { 't', 'e', 'l', 'i' }
static const symbol s_2_25 [4] = { 'v', 'e', 'l', 'i' }
static const symbol s_2_26 [3] = { 'g', 'l', 'i' }
static const symbol s_2_27 [2] = { 'm', 'i' }
static const symbol s_2_28 [2] = { 's', 'i' }
static const symbol s_2_29 [2] = { 't', 'i' }
static const symbol s_2_30 [2] = { 'v', 'i' }
static const symbol s_2_31 [2] = { 'l', 'o' }
static const symbol s_2_32 [4] = { 'c', 'e', 'l', 'o' }
static const symbol s_2_33 [6] = { 'g', 'l', 'i', 'e', 'l', 'o' }
static const symbol s_2_34 [4] = { 'm', 'e', 'l', 'o' }
static const symbol s_2_35 [4] = { 't', 'e', 'l', 'o' }
static const symbol s_2_36 [4] = { 'v', 'e', 'l', 'o' }
static struct among a_2 [37]
static const symbol s_3_0 [4] = { 'a', 'n', 'd', 'o' }
static const symbol s_3_1 [4] = { 'e', 'n', 'd', 'o' }
static const symbol s_3_2 [2] = { 'a', 'r' }
static const symbol s_3_3 [2] = { 'e', 'r' }
static const symbol s_3_4 [2] = { 'i', 'r' }
static struct among a_3 [5]
static const symbol s_4_0 [2] = { 'i', 'c' }
static const symbol s_4_1 [4] = { 'a', 'b', 'i', 'l' }
static const symbol s_4_2 [2] = { 'o', 's' }
static const symbol s_4_3 [2] = { 'i', 'v' }
static struct among a_4 [4]
static const symbol s_5_0 [2] = { 'i', 'c' }
static const symbol s_5_1 [4] = { 'a', 'b', 'i', 'l' }
static const symbol s_5_2 [2] = { 'i', 'v' }
static struct among a_5 [3]
static const symbol s_6_0 [3] = { 'i', 'c', 'a' }
static const symbol s_6_1 [5] = { 'l', 'o', 'g', 'i', 'a' }
static const symbol s_6_2 [3] = { 'o', 's', 'a' }
static const symbol s_6_3 [4] = { 'i', 's', 't', 'a' }
static const symbol s_6_4 [3] = { 'i', 'v', 'a' }
static const symbol s_6_5 [4] = { 'a', 'n', 'z', 'a' }
static const symbol s_6_6 [4] = { 'e', 'n', 'z', 'a' }
static const symbol s_6_7 [3] = { 'i', 'c', 'e' }
static const symbol s_6_8 [6] = { 'a', 't', 'r', 'i', 'c', 'e' }
static const symbol s_6_9 [4] = { 'i', 'c', 'h', 'e' }
static const symbol s_6_10 [5] = { 'l', 'o', 'g', 'i', 'e' }
static const symbol s_6_11 [5] = { 'a', 'b', 'i', 'l', 'e' }
static const symbol s_6_12 [5] = { 'i', 'b', 'i', 'l', 'e' }
static const symbol s_6_13 [6] = { 'u', 's', 'i', 'o', 'n', 'e' }
static const symbol s_6_14 [6] = { 'a', 'z', 'i', 'o', 'n', 'e' }
static const symbol s_6_15 [6] = { 'u', 'z', 'i', 'o', 'n', 'e' }
static const symbol s_6_16 [5] = { 'a', 't', 'o', 'r', 'e' }
static const symbol s_6_17 [3] = { 'o', 's', 'e' }
static const symbol s_6_18 [4] = { 'a', 'n', 't', 'e' }
static const symbol s_6_19 [5] = { 'm', 'e', 'n', 't', 'e' }
static const symbol s_6_20 [6] = { 'a', 'm', 'e', 'n', 't', 'e' }
static const symbol s_6_21 [4] = { 'i', 's', 't', 'e' }
static const symbol s_6_22 [3] = { 'i', 'v', 'e' }
static const symbol s_6_23 [4] = { 'a', 'n', 'z', 'e' }
static const symbol s_6_24 [4] = { 'e', 'n', 'z', 'e' }
static const symbol s_6_25 [3] = { 'i', 'c', 'i' }
static const symbol s_6_26 [6] = { 'a', 't', 'r', 'i', 'c', 'i' }
static const symbol s_6_27 [4] = { 'i', 'c', 'h', 'i' }
static const symbol s_6_28 [5] = { 'a', 'b', 'i', 'l', 'i' }
static const symbol s_6_29 [5] = { 'i', 'b', 'i', 'l', 'i' }
static const symbol s_6_30 [4] = { 'i', 's', 'm', 'i' }
static const symbol s_6_31 [6] = { 'u', 's', 'i', 'o', 'n', 'i' }
static const symbol s_6_32 [6] = { 'a', 'z', 'i', 'o', 'n', 'i' }
static const symbol s_6_33 [6] = { 'u', 'z', 'i', 'o', 'n', 'i' }
static const symbol s_6_34 [5] = { 'a', 't', 'o', 'r', 'i' }
static const symbol s_6_35 [3] = { 'o', 's', 'i' }
static const symbol s_6_36 [4] = { 'a', 'n', 't', 'i' }
static const symbol s_6_37 [6] = { 'a', 'm', 'e', 'n', 't', 'i' }
static const symbol s_6_38 [6] = { 'i', 'm', 'e', 'n', 't', 'i' }
static const symbol s_6_39 [4] = { 'i', 's', 't', 'i' }
static const symbol s_6_40 [3] = { 'i', 'v', 'i' }
static const symbol s_6_41 [3] = { 'i', 'c', 'o' }
static const symbol s_6_42 [4] = { 'i', 's', 'm', 'o' }
static const symbol s_6_43 [3] = { 'o', 's', 'o' }
static const symbol s_6_44 [6] = { 'a', 'm', 'e', 'n', 't', 'o' }
static const symbol s_6_45 [6] = { 'i', 'm', 'e', 'n', 't', 'o' }
static const symbol s_6_46 [3] = { 'i', 'v', 'o' }
static const symbol s_6_47 [4] = { 'i', 't', 0xC3, 0xA0 }
static const symbol s_6_48 [5] = { 'i', 's', 't', 0xC3, 0xA0 }
static const symbol s_6_49 [5] = { 'i', 's', 't', 0xC3, 0xA8 }
static const symbol s_6_50 [5] = { 'i', 's', 't', 0xC3, 0xAC }
static struct among a_6 [51]
static const symbol s_7_0 [4] = { 'i', 's', 'c', 'a' }
static const symbol s_7_1 [4] = { 'e', 'n', 'd', 'a' }
static const symbol s_7_2 [3] = { 'a', 't', 'a' }
static const symbol s_7_3 [3] = { 'i', 't', 'a' }
static const symbol s_7_4 [3] = { 'u', 't', 'a' }
static const symbol s_7_5 [3] = { 'a', 'v', 'a' }
static const symbol s_7_6 [3] = { 'e', 'v', 'a' }
static const symbol s_7_7 [3] = { 'i', 'v', 'a' }
static const symbol s_7_8 [6] = { 'e', 'r', 'e', 'b', 'b', 'e' }
static const symbol s_7_9 [6] = { 'i', 'r', 'e', 'b', 'b', 'e' }
static const symbol s_7_10 [4] = { 'i', 's', 'c', 'e' }
static const symbol s_7_11 [4] = { 'e', 'n', 'd', 'e' }
static const symbol s_7_12 [3] = { 'a', 'r', 'e' }
static const symbol s_7_13 [3] = { 'e', 'r', 'e' }
static const symbol s_7_14 [3] = { 'i', 'r', 'e' }
static const symbol s_7_15 [4] = { 'a', 's', 's', 'e' }
static const symbol s_7_16 [3] = { 'a', 't', 'e' }
static const symbol s_7_17 [5] = { 'a', 'v', 'a', 't', 'e' }
static const symbol s_7_18 [5] = { 'e', 'v', 'a', 't', 'e' }
static const symbol s_7_19 [5] = { 'i', 'v', 'a', 't', 'e' }
static const symbol s_7_20 [3] = { 'e', 't', 'e' }
static const symbol s_7_21 [5] = { 'e', 'r', 'e', 't', 'e' }
static const symbol s_7_22 [5] = { 'i', 'r', 'e', 't', 'e' }
static const symbol s_7_23 [3] = { 'i', 't', 'e' }
static const symbol s_7_24 [6] = { 'e', 'r', 'e', 's', 't', 'e' }
static const symbol s_7_25 [6] = { 'i', 'r', 'e', 's', 't', 'e' }
static const symbol s_7_26 [3] = { 'u', 't', 'e' }
static const symbol s_7_27 [4] = { 'e', 'r', 'a', 'i' }
static const symbol s_7_28 [4] = { 'i', 'r', 'a', 'i' }
static const symbol s_7_29 [4] = { 'i', 's', 'c', 'i' }
static const symbol s_7_30 [4] = { 'e', 'n', 'd', 'i' }
static const symbol s_7_31 [4] = { 'e', 'r', 'e', 'i' }
static const symbol s_7_32 [4] = { 'i', 'r', 'e', 'i' }
static const symbol s_7_33 [4] = { 'a', 's', 's', 'i' }
static const symbol s_7_34 [3] = { 'a', 't', 'i' }
static const symbol s_7_35 [3] = { 'i', 't', 'i' }
static const symbol s_7_36 [6] = { 'e', 'r', 'e', 's', 't', 'i' }
static const symbol s_7_37 [6] = { 'i', 'r', 'e', 's', 't', 'i' }
static const symbol s_7_38 [3] = { 'u', 't', 'i' }
static const symbol s_7_39 [3] = { 'a', 'v', 'i' }
static const symbol s_7_40 [3] = { 'e', 'v', 'i' }
static const symbol s_7_41 [3] = { 'i', 'v', 'i' }
static const symbol s_7_42 [4] = { 'i', 's', 'c', 'o' }
static const symbol s_7_43 [4] = { 'a', 'n', 'd', 'o' }
static const symbol s_7_44 [4] = { 'e', 'n', 'd', 'o' }
static const symbol s_7_45 [4] = { 'Y', 'a', 'm', 'o' }
static const symbol s_7_46 [4] = { 'i', 'a', 'm', 'o' }
static const symbol s_7_47 [5] = { 'a', 'v', 'a', 'm', 'o' }
static const symbol s_7_48 [5] = { 'e', 'v', 'a', 'm', 'o' }
static const symbol s_7_49 [5] = { 'i', 'v', 'a', 'm', 'o' }
static const symbol s_7_50 [5] = { 'e', 'r', 'e', 'm', 'o' }
static const symbol s_7_51 [5] = { 'i', 'r', 'e', 'm', 'o' }
static const symbol s_7_52 [6] = { 'a', 's', 's', 'i', 'm', 'o' }
static const symbol s_7_53 [4] = { 'a', 'm', 'm', 'o' }
static const symbol s_7_54 [4] = { 'e', 'm', 'm', 'o' }
static const symbol s_7_55 [6] = { 'e', 'r', 'e', 'm', 'm', 'o' }
static const symbol s_7_56 [6] = { 'i', 'r', 'e', 'm', 'm', 'o' }
static const symbol s_7_57 [4] = { 'i', 'm', 'm', 'o' }
static const symbol s_7_58 [3] = { 'a', 'n', 'o' }
static const symbol s_7_59 [6] = { 'i', 's', 'c', 'a', 'n', 'o' }
static const symbol s_7_60 [5] = { 'a', 'v', 'a', 'n', 'o' }
static const symbol s_7_61 [5] = { 'e', 'v', 'a', 'n', 'o' }
static const symbol s_7_62 [5] = { 'i', 'v', 'a', 'n', 'o' }
static const symbol s_7_63 [6] = { 'e', 'r', 'a', 'n', 'n', 'o' }
static const symbol s_7_64 [6] = { 'i', 'r', 'a', 'n', 'n', 'o' }
static const symbol s_7_65 [3] = { 'o', 'n', 'o' }
static const symbol s_7_66 [6] = { 'i', 's', 'c', 'o', 'n', 'o' }
static const symbol s_7_67 [5] = { 'a', 'r', 'o', 'n', 'o' }
static const symbol s_7_68 [5] = { 'e', 'r', 'o', 'n', 'o' }
static const symbol s_7_69 [5] = { 'i', 'r', 'o', 'n', 'o' }
static const symbol s_7_70 [8] = { 'e', 'r', 'e', 'b', 'b', 'e', 'r', 'o' }
static const symbol s_7_71 [8] = { 'i', 'r', 'e', 'b', 'b', 'e', 'r', 'o' }
static const symbol s_7_72 [6] = { 'a', 's', 's', 'e', 'r', 'o' }
static const symbol s_7_73 [6] = { 'e', 's', 's', 'e', 'r', 'o' }
static const symbol s_7_74 [6] = { 'i', 's', 's', 'e', 'r', 'o' }
static const symbol s_7_75 [3] = { 'a', 't', 'o' }
static const symbol s_7_76 [3] = { 'i', 't', 'o' }
static const symbol s_7_77 [3] = { 'u', 't', 'o' }
static const symbol s_7_78 [3] = { 'a', 'v', 'o' }
static const symbol s_7_79 [3] = { 'e', 'v', 'o' }
static const symbol s_7_80 [3] = { 'i', 'v', 'o' }
static const symbol s_7_81 [2] = { 'a', 'r' }
static const symbol s_7_82 [2] = { 'i', 'r' }
static const symbol s_7_83 [4] = { 'e', 'r', 0xC3, 0xA0 }
static const symbol s_7_84 [4] = { 'i', 'r', 0xC3, 0xA0 }
static const symbol s_7_85 [4] = { 'e', 'r', 0xC3, 0xB2 }
static const symbol s_7_86 [4] = { 'i', 'r', 0xC3, 0xB2 }
static struct among a_7 [87]
static const unsigned char g_v [] = { 17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 128, 8, 2, 1 }
static const unsigned char g_AEIO [] = { 17, 65, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 128, 8, 2 }
static const unsigned char g_CG [] = { 17 }
static const symbol s_0 [] = { 0xC3, 0xA0 }
static const symbol s_1 [] = { 0xC3, 0xA8 }
static const symbol s_2 [] = { 0xC3, 0xAC }
static const symbol s_3 [] = { 0xC3, 0xB2 }
static const symbol s_4 [] = { 0xC3, 0xB9 }
static const symbol s_5 [] = { 'q', 'U' }
static const symbol s_6 [] = { 'u' }
static const symbol s_7 [] = { 'U' }
static const symbol s_8 [] = { 'i' }
static const symbol s_9 [] = { 'I' }
static const symbol s_10 [] = { 'i' }
static const symbol s_11 [] = { 'u' }
static const symbol s_12 [] = { 'e' }
static const symbol s_13 [] = { 'i', 'c' }
static const symbol s_14 [] = { 'l', 'o', 'g' }
static const symbol s_15 [] = { 'u' }
static const symbol s_16 [] = { 'e', 'n', 't', 'e' }
static const symbol s_17 [] = { 'a', 't' }
static const symbol s_18 [] = { 'a', 't' }
static const symbol s_19 [] = { 'i', 'c' }
static const symbol s_20 [] = { 'i' }
static const symbol s_21 [] = { 'h' }
Function Documentation
void italian_UTF_8_close_env (struct SN_env * z)
struct SN_env* italian_UTF_8_create_env (void) [read]
int italian_UTF_8_stem (struct SN_env * z)
static int r_attached_pronoun (struct SN_env * z) [static]
Definition at line 728 of file stem_UTF_8_italian.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::ket, SN_env::lb, SN_env::p, r_RV(), s_12, slice_del(), and slice_from_s().
Referenced by italian_UTF_8_stem(), and spanish_UTF_8_stem().
static int r_mark_regions (struct SN_env * z) [static]
Definition at line 595 of file stem_UTF_8_italian.cpp.
References SN_env::c, g_v, SN_env::I, in_grouping_U(), SN_env::l, out_grouping_U(), SN_env::p, and skip_utf8().
static int r_postlude (struct SN_env * z) [static]
Definition at line 677 of file stem_UTF_8_italian.cpp.
References SN_env::bra, SN_env::c, find_among(), SN_env::ket, SN_env::l, SN_env::p, s_10, s_11, skip_utf8(), and slice_from_s().
static int r_prelude (struct SN_env * z) [static]
Definition at line 499 of file stem_UTF_8_italian.cpp.
References SN_env::bra, SN_env::c, eq_s(), find_among(), g_v, in_grouping_U(), SN_env::ket, SN_env::l, SN_env::p, s_0, s_1, s_2, s_3, s_4, s_5, s_6, s_7, s_8, s_9, skip_utf8(), and slice_from_s().
static int r_R1 (struct SN_env * z) [static]
Definition at line 718 of file stem_UTF_8_italian.cpp.
References SN_env::c, and SN_env::I.
static int r_R2 (struct SN_env * z) [static]
Definition at line 723 of file stem_UTF_8_italian.cpp.
References SN_env::c, and SN_env::I.
static int r_RV (struct SN_env * z) [static]
Definition at line 713 of file stem_UTF_8_italian.cpp.
References SN_env::c, and SN_env::I.
static int r_standard_suffix (struct SN_env * z) [static]
Definition at line 757 of file stem_UTF_8_italian.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), SN_env::ket, SN_env::l, SN_env::lb, SN_env::p, r_R1(), r_R2(), r_RV(), s_13, s_14, s_15, s_16, s_17, s_18, s_19, slice_del(), and slice_from_s().
static int r_verb_suffix (struct SN_env * z) [static]
Definition at line 940 of file stem_UTF_8_italian.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::I, SN_env::ket, SN_env::l, SN_env::lb, and slice_del().
static int r_vowel_suffix (struct SN_env * z) [static]
Definition at line 965 of file stem_UTF_8_italian.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), g_AEIO, g_CG, in_grouping_b_U(), SN_env::ket, SN_env::l, r_RV(), s_20, s_21, and slice_del().
Referenced by italian_UTF_8_stem(), and romanian_UTF_8_stem().
Variable Documentation
struct among a_0[7] [static]
Initial value:
{
 { 0, 0, -1, 7, 0},
 { 2, s_0_1, 0, 6, 0},
 { 2, s_0_2, 0, 1, 0},
 { 2, s_0_3, 0, 2, 0},
 { 2, s_0_4, 0, 3, 0},
 { 2, s_0_5, 0, 4, 0},
 { 2, s_0_6, 0, 5, 0}
}
Definition at line 45 of file stem_UTF_8_italian.cpp.
struct among a_1[3] [static]
Initial value:
{
 { 0, 0, -1, 3, 0},
 { 1, s_1_1, 0, 1, 0},
 { 1, s_1_2, 0, 2, 0}
}
Definition at line 59 of file stem_UTF_8_italian.cpp.
struct among a_2[37] [static]
Definition at line 104 of file stem_UTF_8_italian.cpp.
struct among a_3[5] [static]
Initial value:
{
 { 4, s_3_0, -1, 1, 0},
 { 4, s_3_1, -1, 1, 0},
 { 2, s_3_2, -1, 2, 0},
 { 2, s_3_3, -1, 2, 0},
 { 2, s_3_4, -1, 2, 0}
}
Definition at line 151 of file stem_UTF_8_italian.cpp.
struct among a_4[4] [static]
Initial value:
{
 { 2, s_4_0, -1, -1, 0},
 { 4, s_4_1, -1, -1, 0},
 { 2, s_4_2, -1, -1, 0},
 { 2, s_4_3, -1, 1, 0}
}
Definition at line 165 of file stem_UTF_8_italian.cpp.
struct among a_5[3] [static]
Initial value:
{
 { 2, s_5_0, -1, 1, 0},
 { 4, s_5_1, -1, 1, 0},
 { 2, s_5_2, -1, 1, 0}
}
Definition at line 177 of file stem_UTF_8_italian.cpp.
struct among a_6[51] [static]
Definition at line 236 of file stem_UTF_8_italian.cpp.
struct among a_7[87] [static]
Definition at line 379 of file stem_UTF_8_italian.cpp.
const unsigned char g_AEIO[] = { 17, 65, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 128, 8, 2 } [static]
Definition at line 472 of file stem_UTF_8_italian.cpp.
Referenced by r_vowel_suffix().
const unsigned char g_CG[] = { 17 } [static]
Definition at line 474 of file stem_UTF_8_italian.cpp.
Referenced by r_vowel_suffix().
const unsigned char g_v[] = { 17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 128, 8, 2, 1 } [static]
Definition at line 470 of file stem_UTF_8_italian.cpp.
const symbol s_0[] = { 0xC3, 0xA0 } [static]
Definition at line 476 of file stem_UTF_8_italian.cpp.
const symbol s_0_1[2] = { 'q', 'u' } [static]
Definition at line 38 of file stem_UTF_8_italian.cpp.
const symbol s_0_2[2] = { 0xC3, 0xA1 } [static]
Definition at line 39 of file stem_UTF_8_italian.cpp.
const symbol s_0_3[2] = { 0xC3, 0xA9 } [static]
Definition at line 40 of file stem_UTF_8_italian.cpp.
const symbol s_0_4[2] = { 0xC3, 0xAD } [static]
Definition at line 41 of file stem_UTF_8_italian.cpp.
const symbol s_0_5[2] = { 0xC3, 0xB3 } [static]
Definition at line 42 of file stem_UTF_8_italian.cpp.
const symbol s_0_6[2] = { 0xC3, 0xBA } [static]
Definition at line 43 of file stem_UTF_8_italian.cpp.
const symbol s_1[] = { 0xC3, 0xA8 } [static]
Definition at line 477 of file stem_UTF_8_italian.cpp.
const symbol s_10[] = { 'i' } [static]
Definition at line 486 of file stem_UTF_8_italian.cpp.
const symbol s_11[] = { 'u' } [static]
Definition at line 487 of file stem_UTF_8_italian.cpp.
const symbol s_12[] = { 'e' } [static]
Definition at line 488 of file stem_UTF_8_italian.cpp.
const symbol s_13[] = { 'i', 'c' } [static]
Definition at line 489 of file stem_UTF_8_italian.cpp.
const symbol s_14[] = { 'l', 'o', 'g' } [static]
Definition at line 490 of file stem_UTF_8_italian.cpp.
const symbol s_15[] = { 'u' } [static]
Definition at line 491 of file stem_UTF_8_italian.cpp.
const symbol s_16[] = { 'e', 'n', 't', 'e' } [static]
Definition at line 492 of file stem_UTF_8_italian.cpp.
const symbol s_17[] = { 'a', 't' } [static]
Definition at line 493 of file stem_UTF_8_italian.cpp.
const symbol s_18[] = { 'a', 't' } [static]
Definition at line 494 of file stem_UTF_8_italian.cpp.
const symbol s_19[] = { 'i', 'c' } [static]
Definition at line 495 of file stem_UTF_8_italian.cpp.
const symbol s_1_1[1] = { 'I' } [static]
Definition at line 56 of file stem_UTF_8_italian.cpp.
const symbol s_1_2[1] = { 'U' } [static]
Definition at line 57 of file stem_UTF_8_italian.cpp.
const symbol s_2[] = { 0xC3, 0xAC } [static]
Definition at line 478 of file stem_UTF_8_italian.cpp.
const symbol s_20[] = { 'i' } [static]
Definition at line 496 of file stem_UTF_8_italian.cpp.
const symbol s_21[] = { 'h' } [static]
Definition at line 497 of file stem_UTF_8_italian.cpp.
const symbol s_2_0[2] = { 'l', 'a' } [static]
Definition at line 66 of file stem_UTF_8_italian.cpp.
const symbol s_2_1[4] = { 'c', 'e', 'l', 'a' } [static]
Definition at line 67 of file stem_UTF_8_italian.cpp.
const symbol s_2_10[4] = { 't', 'e', 'l', 'e' } [static]
Definition at line 76 of file stem_UTF_8_italian.cpp.
const symbol s_2_11[4] = { 'v', 'e', 'l', 'e' } [static]
Definition at line 77 of file stem_UTF_8_italian.cpp.
const symbol s_2_12[2] = { 'n', 'e' } [static]
Definition at line 78 of file stem_UTF_8_italian.cpp.
const symbol s_2_13[4] = { 'c', 'e', 'n', 'e' } [static]
Definition at line 79 of file stem_UTF_8_italian.cpp.
const symbol s_2_14[6] = { 'g', 'l', 'i', 'e', 'n', 'e' } [static]
Definition at line 80 of file stem_UTF_8_italian.cpp.
const symbol s_2_15[4] = { 'm', 'e', 'n', 'e' } [static]
Definition at line 81 of file stem_UTF_8_italian.cpp.
const symbol s_2_16[4] = { 's', 'e', 'n', 'e' } [static]
Definition at line 82 of file stem_UTF_8_italian.cpp.
const symbol s_2_17[4] = { 't', 'e', 'n', 'e' } [static]
Definition at line 83 of file stem_UTF_8_italian.cpp.
const symbol s_2_18[4] = { 'v', 'e', 'n', 'e' } [static]
Definition at line 84 of file stem_UTF_8_italian.cpp.
const symbol s_2_19[2] = { 'c', 'i' } [static]
Definition at line 85 of file stem_UTF_8_italian.cpp.
const symbol s_2_2[6] = { 'g', 'l', 'i', 'e', 'l', 'a' } [static]
Definition at line 68 of file stem_UTF_8_italian.cpp.
const symbol s_2_20[2] = { 'l', 'i' } [static]
Definition at line 86 of file stem_UTF_8_italian.cpp.
const symbol s_2_21[4] = { 'c', 'e', 'l', 'i' } [static]
Definition at line 87 of file stem_UTF_8_italian.cpp.
const symbol s_2_22[6] = { 'g', 'l', 'i', 'e', 'l', 'i' } [static]
Definition at line 88 of file stem_UTF_8_italian.cpp.
const symbol s_2_23[4] = { 'm', 'e', 'l', 'i' } [static]
Definition at line 89 of file stem_UTF_8_italian.cpp.
const symbol s_2_24[4] = { 't', 'e', 'l', 'i' } [static]
Definition at line 90 of file stem_UTF_8_italian.cpp.
const symbol s_2_25[4] = { 'v', 'e', 'l', 'i' } [static]
Definition at line 91 of file stem_UTF_8_italian.cpp.
const symbol s_2_26[3] = { 'g', 'l', 'i' } [static]
Definition at line 92 of file stem_UTF_8_italian.cpp.
const symbol s_2_27[2] = { 'm', 'i' } [static]
Definition at line 93 of file stem_UTF_8_italian.cpp.
const symbol s_2_28[2] = { 's', 'i' } [static]
Definition at line 94 of file stem_UTF_8_italian.cpp.
const symbol s_2_29[2] = { 't', 'i' } [static]
Definition at line 95 of file stem_UTF_8_italian.cpp.
const symbol s_2_3[4] = { 'm', 'e', 'l', 'a' } [static]
Definition at line 69 of file stem_UTF_8_italian.cpp.
const symbol s_2_30[2] = { 'v', 'i' } [static]
Definition at line 96 of file stem_UTF_8_italian.cpp.
const symbol s_2_31[2] = { 'l', 'o' } [static]
Definition at line 97 of file stem_UTF_8_italian.cpp.
const symbol s_2_32[4] = { 'c', 'e', 'l', 'o' } [static]
Definition at line 98 of file stem_UTF_8_italian.cpp.
const symbol s_2_33[6] = { 'g', 'l', 'i', 'e', 'l', 'o' } [static]
Definition at line 99 of file stem_UTF_8_italian.cpp.
const symbol s_2_34[4] = { 'm', 'e', 'l', 'o' } [static]
Definition at line 100 of file stem_UTF_8_italian.cpp.
const symbol s_2_35[4] = { 't', 'e', 'l', 'o' } [static]
Definition at line 101 of file stem_UTF_8_italian.cpp.
const symbol s_2_36[4] = { 'v', 'e', 'l', 'o' } [static]
Definition at line 102 of file stem_UTF_8_italian.cpp.
const symbol s_2_4[4] = { 't', 'e', 'l', 'a' } [static]
Definition at line 70 of file stem_UTF_8_italian.cpp.
const symbol s_2_5[4] = { 'v', 'e', 'l', 'a' } [static]
Definition at line 71 of file stem_UTF_8_italian.cpp.
const symbol s_2_6[2] = { 'l', 'e' } [static]
Definition at line 72 of file stem_UTF_8_italian.cpp.
const symbol s_2_7[4] = { 'c', 'e', 'l', 'e' } [static]
Definition at line 73 of file stem_UTF_8_italian.cpp.
const symbol s_2_8[6] = { 'g', 'l', 'i', 'e', 'l', 'e' } [static]
Definition at line 74 of file stem_UTF_8_italian.cpp.
const symbol s_2_9[4] = { 'm', 'e', 'l', 'e' } [static]
Definition at line 75 of file stem_UTF_8_italian.cpp.
const symbol s_3[] = { 0xC3, 0xB2 } [static]
Definition at line 479 of file stem_UTF_8_italian.cpp.
const symbol s_3_0[4] = { 'a', 'n', 'd', 'o' } [static]
Definition at line 145 of file stem_UTF_8_italian.cpp.
const symbol s_3_1[4] = { 'e', 'n', 'd', 'o' } [static]
Definition at line 146 of file stem_UTF_8_italian.cpp.
const symbol s_3_2[2] = { 'a', 'r' } [static]
Definition at line 147 of file stem_UTF_8_italian.cpp.
const symbol s_3_3[2] = { 'e', 'r' } [static]
Definition at line 148 of file stem_UTF_8_italian.cpp.
const symbol s_3_4[2] = { 'i', 'r' } [static]
Definition at line 149 of file stem_UTF_8_italian.cpp.
const symbol s_4[] = { 0xC3, 0xB9 } [static]
Definition at line 480 of file stem_UTF_8_italian.cpp.
const symbol s_4_0[2] = { 'i', 'c' } [static]
Definition at line 160 of file stem_UTF_8_italian.cpp.
const symbol s_4_1[4] = { 'a', 'b', 'i', 'l' } [static]
Definition at line 161 of file stem_UTF_8_italian.cpp.
const symbol s_4_2[2] = { 'o', 's' } [static]
Definition at line 162 of file stem_UTF_8_italian.cpp.
const symbol s_4_3[2] = { 'i', 'v' } [static]
Definition at line 163 of file stem_UTF_8_italian.cpp.
const symbol s_5[] = { 'q', 'U' } [static]
Definition at line 481 of file stem_UTF_8_italian.cpp.
const symbol s_5_0[2] = { 'i', 'c' } [static]
Definition at line 173 of file stem_UTF_8_italian.cpp.
const symbol s_5_1[4] = { 'a', 'b', 'i', 'l' } [static]
Definition at line 174 of file stem_UTF_8_italian.cpp.
const symbol s_5_2[2] = { 'i', 'v' } [static]
Definition at line 175 of file stem_UTF_8_italian.cpp.
const symbol s_6[] = { 'u' } [static]
Definition at line 482 of file stem_UTF_8_italian.cpp.
const symbol s_6_0[3] = { 'i', 'c', 'a' } [static]
Definition at line 184 of file stem_UTF_8_italian.cpp.
const symbol s_6_1[5] = { 'l', 'o', 'g', 'i', 'a' } [static]
Definition at line 185 of file stem_UTF_8_italian.cpp.
const symbol s_6_10[5] = { 'l', 'o', 'g', 'i', 'e' } [static]
Definition at line 194 of file stem_UTF_8_italian.cpp.
const symbol s_6_11[5] = { 'a', 'b', 'i', 'l', 'e' } [static]
Definition at line 195 of file stem_UTF_8_italian.cpp.
const symbol s_6_12[5] = { 'i', 'b', 'i', 'l', 'e' } [static]
Definition at line 196 of file stem_UTF_8_italian.cpp.
const symbol s_6_13[6] = { 'u', 's', 'i', 'o', 'n', 'e' } [static]
Definition at line 197 of file stem_UTF_8_italian.cpp.
const symbol s_6_14[6] = { 'a', 'z', 'i', 'o', 'n', 'e' } [static]
Definition at line 198 of file stem_UTF_8_italian.cpp.
const symbol s_6_15[6] = { 'u', 'z', 'i', 'o', 'n', 'e' } [static]
Definition at line 199 of file stem_UTF_8_italian.cpp.
const symbol s_6_16[5] = { 'a', 't', 'o', 'r', 'e' } [static]
Definition at line 200 of file stem_UTF_8_italian.cpp.
const symbol s_6_17[3] = { 'o', 's', 'e' } [static]
Definition at line 201 of file stem_UTF_8_italian.cpp.
const symbol s_6_18[4] = { 'a', 'n', 't', 'e' } [static]
Definition at line 202 of file stem_UTF_8_italian.cpp.
const symbol s_6_19[5] = { 'm', 'e', 'n', 't', 'e' } [static]
Definition at line 203 of file stem_UTF_8_italian.cpp.
const symbol s_6_2[3] = { 'o', 's', 'a' } [static]
Definition at line 186 of file stem_UTF_8_italian.cpp.
const symbol s_6_20[6] = { 'a', 'm', 'e', 'n', 't', 'e' } [static]
Definition at line 204 of file stem_UTF_8_italian.cpp.
const symbol s_6_21[4] = { 'i', 's', 't', 'e' } [static]
Definition at line 205 of file stem_UTF_8_italian.cpp.
const symbol s_6_22[3] = { 'i', 'v', 'e' } [static]
Definition at line 206 of file stem_UTF_8_italian.cpp.
const symbol s_6_23[4] = { 'a', 'n', 'z', 'e' } [static]
Definition at line 207 of file stem_UTF_8_italian.cpp.
const symbol s_6_24[4] = { 'e', 'n', 'z', 'e' } [static]
Definition at line 208 of file stem_UTF_8_italian.cpp.
const symbol s_6_25[3] = { 'i', 'c', 'i' } [static]
Definition at line 209 of file stem_UTF_8_italian.cpp.
const symbol s_6_26[6] = { 'a', 't', 'r', 'i', 'c', 'i' } [static]
Definition at line 210 of file stem_UTF_8_italian.cpp.
const symbol s_6_27[4] = { 'i', 'c', 'h', 'i' } [static]
Definition at line 211 of file stem_UTF_8_italian.cpp.
const symbol s_6_28[5] = { 'a', 'b', 'i', 'l', 'i' } [static]
Definition at line 212 of file stem_UTF_8_italian.cpp.
const symbol s_6_29[5] = { 'i', 'b', 'i', 'l', 'i' } [static]
Definition at line 213 of file stem_UTF_8_italian.cpp.
const symbol s_6_3[4] = { 'i', 's', 't', 'a' } [static]
Definition at line 187 of file stem_UTF_8_italian.cpp.
const symbol s_6_30[4] = { 'i', 's', 'm', 'i' } [static]
Definition at line 214 of file stem_UTF_8_italian.cpp.
const symbol s_6_31[6] = { 'u', 's', 'i', 'o', 'n', 'i' } [static]
Definition at line 215 of file stem_UTF_8_italian.cpp.
const symbol s_6_32[6] = { 'a', 'z', 'i', 'o', 'n', 'i' } [static]
Definition at line 216 of file stem_UTF_8_italian.cpp.
const symbol s_6_33[6] = { 'u', 'z', 'i', 'o', 'n', 'i' } [static]
Definition at line 217 of file stem_UTF_8_italian.cpp.
const symbol s_6_34[5] = { 'a', 't', 'o', 'r', 'i' } [static]
Definition at line 218 of file stem_UTF_8_italian.cpp.
const symbol s_6_35[3] = { 'o', 's', 'i' } [static]
Definition at line 219 of file stem_UTF_8_italian.cpp.
const symbol s_6_36[4] = { 'a', 'n', 't', 'i' } [static]
Definition at line 220 of file stem_UTF_8_italian.cpp.
const symbol s_6_37[6] = { 'a', 'm', 'e', 'n', 't', 'i' } [static]
Definition at line 221 of file stem_UTF_8_italian.cpp.
const symbol s_6_38[6] = { 'i', 'm', 'e', 'n', 't', 'i' } [static]
Definition at line 222 of file stem_UTF_8_italian.cpp.
const symbol s_6_39[4] = { 'i', 's', 't', 'i' } [static]
Definition at line 223 of file stem_UTF_8_italian.cpp.
const symbol s_6_4[3] = { 'i', 'v', 'a' } [static]
Definition at line 188 of file stem_UTF_8_italian.cpp.
const symbol s_6_40[3] = { 'i', 'v', 'i' } [static]
Definition at line 224 of file stem_UTF_8_italian.cpp.
const symbol s_6_41[3] = { 'i', 'c', 'o' } [static]
Definition at line 225 of file stem_UTF_8_italian.cpp.
const symbol s_6_42[4] = { 'i', 's', 'm', 'o' } [static]
Definition at line 226 of file stem_UTF_8_italian.cpp.
const symbol s_6_43[3] = { 'o', 's', 'o' } [static]
Definition at line 227 of file stem_UTF_8_italian.cpp.
const symbol s_6_44[6] = { 'a', 'm', 'e', 'n', 't', 'o' } [static]
Definition at line 228 of file stem_UTF_8_italian.cpp.
const symbol s_6_45[6] = { 'i', 'm', 'e', 'n', 't', 'o' } [static]
Definition at line 229 of file stem_UTF_8_italian.cpp.
const symbol s_6_46[3] = { 'i', 'v', 'o' } [static]
Definition at line 230 of file stem_UTF_8_italian.cpp.
const symbol s_6_47[4] = { 'i', 't', 0xC3, 0xA0 } [static]
Definition at line 231 of file stem_UTF_8_italian.cpp.
const symbol s_6_48[5] = { 'i', 's', 't', 0xC3, 0xA0 } [static]
Definition at line 232 of file stem_UTF_8_italian.cpp.
const symbol s_6_49[5] = { 'i', 's', 't', 0xC3, 0xA8 } [static]
Definition at line 233 of file stem_UTF_8_italian.cpp.
const symbol s_6_5[4] = { 'a', 'n', 'z', 'a' } [static]
Definition at line 189 of file stem_UTF_8_italian.cpp.
const symbol s_6_50[5] = { 'i', 's', 't', 0xC3, 0xAC } [static]
Definition at line 234 of file stem_UTF_8_italian.cpp.
const symbol s_6_6[4] = { 'e', 'n', 'z', 'a' } [static]
Definition at line 190 of file stem_UTF_8_italian.cpp.
const symbol s_6_7[3] = { 'i', 'c', 'e' } [static]
Definition at line 191 of file stem_UTF_8_italian.cpp.
const symbol s_6_8[6] = { 'a', 't', 'r', 'i', 'c', 'e' } [static]
Definition at line 192 of file stem_UTF_8_italian.cpp.
const symbol s_6_9[4] = { 'i', 'c', 'h', 'e' } [static]
Definition at line 193 of file stem_UTF_8_italian.cpp.
const symbol s_7[] = { 'U' } [static]
Definition at line 483 of file stem_UTF_8_italian.cpp.
const symbol s_7_0[4] = { 'i', 's', 'c', 'a' } [static]
Definition at line 291 of file stem_UTF_8_italian.cpp.
const symbol s_7_1[4] = { 'e', 'n', 'd', 'a' } [static]
Definition at line 292 of file stem_UTF_8_italian.cpp.
const symbol s_7_10[4] = { 'i', 's', 'c', 'e' } [static]
Definition at line 301 of file stem_UTF_8_italian.cpp.
const symbol s_7_11[4] = { 'e', 'n', 'd', 'e' } [static]
Definition at line 302 of file stem_UTF_8_italian.cpp.
const symbol s_7_12[3] = { 'a', 'r', 'e' } [static]
Definition at line 303 of file stem_UTF_8_italian.cpp.
const symbol s_7_13[3] = { 'e', 'r', 'e' } [static]
Definition at line 304 of file stem_UTF_8_italian.cpp.
const symbol s_7_14[3] = { 'i', 'r', 'e' } [static]
Definition at line 305 of file stem_UTF_8_italian.cpp.
const symbol s_7_15[4] = { 'a', 's', 's', 'e' } [static]
Definition at line 306 of file stem_UTF_8_italian.cpp.
const symbol s_7_16[3] = { 'a', 't', 'e' } [static]
Definition at line 307 of file stem_UTF_8_italian.cpp.
const symbol s_7_17[5] = { 'a', 'v', 'a', 't', 'e' } [static]
Definition at line 308 of file stem_UTF_8_italian.cpp.
const symbol s_7_18[5] = { 'e', 'v', 'a', 't', 'e' } [static]
Definition at line 309 of file stem_UTF_8_italian.cpp.
const symbol s_7_19[5] = { 'i', 'v', 'a', 't', 'e' } [static]
Definition at line 310 of file stem_UTF_8_italian.cpp.
const symbol s_7_2[3] = { 'a', 't', 'a' } [static]
Definition at line 293 of file stem_UTF_8_italian.cpp.
const symbol s_7_20[3] = { 'e', 't', 'e' } [static]
Definition at line 311 of file stem_UTF_8_italian.cpp.
const symbol s_7_21[5] = { 'e', 'r', 'e', 't', 'e' } [static]
Definition at line 312 of file stem_UTF_8_italian.cpp.
const symbol s_7_22[5] = { 'i', 'r', 'e', 't', 'e' } [static]
Definition at line 313 of file stem_UTF_8_italian.cpp.
const symbol s_7_23[3] = { 'i', 't', 'e' } [static]
Definition at line 314 of file stem_UTF_8_italian.cpp.
const symbol s_7_24[6] = { 'e', 'r', 'e', 's', 't', 'e' } [static]
Definition at line 315 of file stem_UTF_8_italian.cpp.
const symbol s_7_25[6] = { 'i', 'r', 'e', 's', 't', 'e' } [static]
Definition at line 316 of file stem_UTF_8_italian.cpp.
const symbol s_7_26[3] = { 'u', 't', 'e' } [static]
Definition at line 317 of file stem_UTF_8_italian.cpp.
const symbol s_7_27[4] = { 'e', 'r', 'a', 'i' } [static]
Definition at line 318 of file stem_UTF_8_italian.cpp.
const symbol s_7_28[4] = { 'i', 'r', 'a', 'i' } [static]
Definition at line 319 of file stem_UTF_8_italian.cpp.
const symbol s_7_29[4] = { 'i', 's', 'c', 'i' } [static]
Definition at line 320 of file stem_UTF_8_italian.cpp.
const symbol s_7_3[3] = { 'i', 't', 'a' } [static]
Definition at line 294 of file stem_UTF_8_italian.cpp.
const symbol s_7_30[4] = { 'e', 'n', 'd', 'i' } [static]
Definition at line 321 of file stem_UTF_8_italian.cpp.
const symbol s_7_31[4] = { 'e', 'r', 'e', 'i' } [static]
Definition at line 322 of file stem_UTF_8_italian.cpp.
const symbol s_7_32[4] = { 'i', 'r', 'e', 'i' } [static]
Definition at line 323 of file stem_UTF_8_italian.cpp.
const symbol s_7_33[4] = { 'a', 's', 's', 'i' } [static]
Definition at line 324 of file stem_UTF_8_italian.cpp.
const symbol s_7_34[3] = { 'a', 't', 'i' } [static]
Definition at line 325 of file stem_UTF_8_italian.cpp.
const symbol s_7_35[3] = { 'i', 't', 'i' } [static]
Definition at line 326 of file stem_UTF_8_italian.cpp.
const symbol s_7_36[6] = { 'e', 'r', 'e', 's', 't', 'i' } [static]
Definition at line 327 of file stem_UTF_8_italian.cpp.
const symbol s_7_37[6] = { 'i', 'r', 'e', 's', 't', 'i' } [static]
Definition at line 328 of file stem_UTF_8_italian.cpp.
const symbol s_7_38[3] = { 'u', 't', 'i' } [static]
Definition at line 329 of file stem_UTF_8_italian.cpp.
const symbol s_7_39[3] = { 'a', 'v', 'i' } [static]
Definition at line 330 of file stem_UTF_8_italian.cpp.
const symbol s_7_4[3] = { 'u', 't', 'a' } [static]
Definition at line 295 of file stem_UTF_8_italian.cpp.
const symbol s_7_40[3] = { 'e', 'v', 'i' } [static]
Definition at line 331 of file stem_UTF_8_italian.cpp.
const symbol s_7_41[3] = { 'i', 'v', 'i' } [static]
Definition at line 332 of file stem_UTF_8_italian.cpp.
const symbol s_7_42[4] = { 'i', 's', 'c', 'o' } [static]
Definition at line 333 of file stem_UTF_8_italian.cpp.
const symbol s_7_43[4] = { 'a', 'n', 'd', 'o' } [static]
Definition at line 334 of file stem_UTF_8_italian.cpp.
const symbol s_7_44[4] = { 'e', 'n', 'd', 'o' } [static]
Definition at line 335 of file stem_UTF_8_italian.cpp.
const symbol s_7_45[4] = { 'Y', 'a', 'm', 'o' } [static]
Definition at line 336 of file stem_UTF_8_italian.cpp.
const symbol s_7_46[4] = { 'i', 'a', 'm', 'o' } [static]
Definition at line 337 of file stem_UTF_8_italian.cpp.
const symbol s_7_47[5] = { 'a', 'v', 'a', 'm', 'o' } [static]
Definition at line 338 of file stem_UTF_8_italian.cpp.
const symbol s_7_48[5] = { 'e', 'v', 'a', 'm', 'o' } [static]
Definition at line 339 of file stem_UTF_8_italian.cpp.
const symbol s_7_49[5] = { 'i', 'v', 'a', 'm', 'o' } [static]
Definition at line 340 of file stem_UTF_8_italian.cpp.
const symbol s_7_5[3] = { 'a', 'v', 'a' } [static]
Definition at line 296 of file stem_UTF_8_italian.cpp.
const symbol s_7_50[5] = { 'e', 'r', 'e', 'm', 'o' } [static]
Definition at line 341 of file stem_UTF_8_italian.cpp.
const symbol s_7_51[5] = { 'i', 'r', 'e', 'm', 'o' } [static]
Definition at line 342 of file stem_UTF_8_italian.cpp.
const symbol s_7_52[6] = { 'a', 's', 's', 'i', 'm', 'o' } [static]
Definition at line 343 of file stem_UTF_8_italian.cpp.
const symbol s_7_53[4] = { 'a', 'm', 'm', 'o' } [static]
Definition at line 344 of file stem_UTF_8_italian.cpp.
const symbol s_7_54[4] = { 'e', 'm', 'm', 'o' } [static]
Definition at line 345 of file stem_UTF_8_italian.cpp.
const symbol s_7_55[6] = { 'e', 'r', 'e', 'm', 'm', 'o' } [static]
Definition at line 346 of file stem_UTF_8_italian.cpp.
const symbol s_7_56[6] = { 'i', 'r', 'e', 'm', 'm', 'o' } [static]
Definition at line 347 of file stem_UTF_8_italian.cpp.
const symbol s_7_57[4] = { 'i', 'm', 'm', 'o' } [static]
Definition at line 348 of file stem_UTF_8_italian.cpp.
const symbol s_7_58[3] = { 'a', 'n', 'o' } [static]
Definition at line 349 of file stem_UTF_8_italian.cpp.
const symbol s_7_59[6] = { 'i', 's', 'c', 'a', 'n', 'o' } [static]
Definition at line 350 of file stem_UTF_8_italian.cpp.
const symbol s_7_6[3] = { 'e', 'v', 'a' } [static]
Definition at line 297 of file stem_UTF_8_italian.cpp.
const symbol s_7_60[5] = { 'a', 'v', 'a', 'n', 'o' } [static]
Definition at line 351 of file stem_UTF_8_italian.cpp.
const symbol s_7_61[5] = { 'e', 'v', 'a', 'n', 'o' } [static]
Definition at line 352 of file stem_UTF_8_italian.cpp.
const symbol s_7_62[5] = { 'i', 'v', 'a', 'n', 'o' } [static]
Definition at line 353 of file stem_UTF_8_italian.cpp.
const symbol s_7_63[6] = { 'e', 'r', 'a', 'n', 'n', 'o' } [static]
Definition at line 354 of file stem_UTF_8_italian.cpp.
const symbol s_7_64[6] = { 'i', 'r', 'a', 'n', 'n', 'o' } [static]
Definition at line 355 of file stem_UTF_8_italian.cpp.
const symbol s_7_65[3] = { 'o', 'n', 'o' } [static]
Definition at line 356 of file stem_UTF_8_italian.cpp.
const symbol s_7_66[6] = { 'i', 's', 'c', 'o', 'n', 'o' } [static]
Definition at line 357 of file stem_UTF_8_italian.cpp.
const symbol s_7_67[5] = { 'a', 'r', 'o', 'n', 'o' } [static]
Definition at line 358 of file stem_UTF_8_italian.cpp.
const symbol s_7_68[5] = { 'e', 'r', 'o', 'n', 'o' } [static]
Definition at line 359 of file stem_UTF_8_italian.cpp.
const symbol s_7_69[5] = { 'i', 'r', 'o', 'n', 'o' } [static]
Definition at line 360 of file stem_UTF_8_italian.cpp.
const symbol s_7_7[3] = { 'i', 'v', 'a' } [static]
Definition at line 298 of file stem_UTF_8_italian.cpp.
const symbol s_7_70[8] = { 'e', 'r', 'e', 'b', 'b', 'e', 'r', 'o' } [static]
Definition at line 361 of file stem_UTF_8_italian.cpp.
const symbol s_7_71[8] = { 'i', 'r', 'e', 'b', 'b', 'e', 'r', 'o' } [static]
Definition at line 362 of file stem_UTF_8_italian.cpp.
const symbol s_7_72[6] = { 'a', 's', 's', 'e', 'r', 'o' } [static]
Definition at line 363 of file stem_UTF_8_italian.cpp.
const symbol s_7_73[6] = { 'e', 's', 's', 'e', 'r', 'o' } [static]
Definition at line 364 of file stem_UTF_8_italian.cpp.
const symbol s_7_74[6] = { 'i', 's', 's', 'e', 'r', 'o' } [static]
Definition at line 365 of file stem_UTF_8_italian.cpp.
const symbol s_7_75[3] = { 'a', 't', 'o' } [static]
Definition at line 366 of file stem_UTF_8_italian.cpp.
const symbol s_7_76[3] = { 'i', 't', 'o' } [static]
Definition at line 367 of file stem_UTF_8_italian.cpp.
const symbol s_7_77[3] = { 'u', 't', 'o' } [static]
Definition at line 368 of file stem_UTF_8_italian.cpp.
const symbol s_7_78[3] = { 'a', 'v', 'o' } [static]
Definition at line 369 of file stem_UTF_8_italian.cpp.
const symbol s_7_79[3] = { 'e', 'v', 'o' } [static]
Definition at line 370 of file stem_UTF_8_italian.cpp.
const symbol s_7_8[6] = { 'e', 'r', 'e', 'b', 'b', 'e' } [static]
Definition at line 299 of file stem_UTF_8_italian.cpp.
const symbol s_7_80[3] = { 'i', 'v', 'o' } [static]
Definition at line 371 of file stem_UTF_8_italian.cpp.
const symbol s_7_81[2] = { 'a', 'r' } [static]
Definition at line 372 of file stem_UTF_8_italian.cpp.
const symbol s_7_82[2] = { 'i', 'r' } [static]
Definition at line 373 of file stem_UTF_8_italian.cpp.
const symbol s_7_83[4] = { 'e', 'r', 0xC3, 0xA0 } [static]
Definition at line 374 of file stem_UTF_8_italian.cpp.
const symbol s_7_84[4] = { 'i', 'r', 0xC3, 0xA0 } [static]
Definition at line 375 of file stem_UTF_8_italian.cpp.
const symbol s_7_85[4] = { 'e', 'r', 0xC3, 0xB2 } [static]
Definition at line 376 of file stem_UTF_8_italian.cpp.
const symbol s_7_86[4] = { 'i', 'r', 0xC3, 0xB2 } [static]
Definition at line 377 of file stem_UTF_8_italian.cpp.
const symbol s_7_9[6] = { 'i', 'r', 'e', 'b', 'b', 'e' } [static]
Definition at line 300 of file stem_UTF_8_italian.cpp.
const symbol s_8[] = { 'i' } [static]
Definition at line 484 of file stem_UTF_8_italian.cpp.
const symbol s_9[] = { 'I' } [static]
Definition at line 485 of file stem_UTF_8_italian.cpp.