/disk/workspace-cpp/la-manager/source/stem/stem_UTF_8_turkish.cpp File Reference
#include <stem/header.h>
Functions
int turkish_UTF_8_stem (struct SN_env *z)
static int r_stem_suffix_chain_before_ki (struct SN_env *z)
static int r_stem_noun_suffixes (struct SN_env *z)
static int r_stem_nominal_verb_suffixes (struct SN_env *z)
static int r_postlude (struct SN_env *z)
static int r_post_process_last_consonants (struct SN_env *z)
static int r_more_than_one_syllable_word (struct SN_env *z)
static int r_mark_suffix_with_optional_s_consonant (struct SN_env *z)
static int r_mark_suffix_with_optional_n_consonant (struct SN_env *z)
static int r_mark_suffix_with_optional_U_vowel (struct SN_env *z)
static int r_mark_suffix_with_optional_y_consonant (struct SN_env *z)
static int r_mark_ysA (struct SN_env *z)
static int r_mark_ymUs_ (struct SN_env *z)
static int r_mark_yken (struct SN_env *z)
static int r_mark_yDU (struct SN_env *z)
static int r_mark_yUz (struct SN_env *z)
static int r_mark_yUm (struct SN_env *z)
static int r_mark_yU (struct SN_env *z)
static int r_mark_ylA (struct SN_env *z)
static int r_mark_yA (struct SN_env *z)
static int r_mark_possessives (struct SN_env *z)
static int r_mark_sUnUz (struct SN_env *z)
static int r_mark_sUn (struct SN_env *z)
static int r_mark_sU (struct SN_env *z)
static int r_mark_nUz (struct SN_env *z)
static int r_mark_nUn (struct SN_env *z)
static int r_mark_nU (struct SN_env *z)
static int r_mark_ndAn (struct SN_env *z)
static int r_mark_ndA (struct SN_env *z)
static int r_mark_ncA (struct SN_env *z)
static int r_mark_nA (struct SN_env *z)
static int r_mark_lArI (struct SN_env *z)
static int r_mark_lAr (struct SN_env *z)
static int r_mark_ki (struct SN_env *z)
static int r_mark_DUr (struct SN_env *z)
static int r_mark_DAn (struct SN_env *z)
static int r_mark_DA (struct SN_env *z)
static int r_mark_cAsInA (struct SN_env *z)
static int r_is_reserved_word (struct SN_env *z)
static int r_check_vowel_harmony (struct SN_env *z)
static int r_append_U_to_stems_ending_with_d_or_g (struct SN_env *z)
struct SN_env * turkish_UTF_8_create_env (void)
void turkish_UTF_8_close_env (struct SN_env *z)
Variables
static const symbol s_0_0 [1] = { 'm' }
static const symbol s_0_1 [1] = { 'n' }
static const symbol s_0_2 [3] = { 'm', 'i', 'z' }
static const symbol s_0_3 [3] = { 'n', 'i', 'z' }
static const symbol s_0_4 [3] = { 'm', 'u', 'z' }
static const symbol s_0_5 [3] = { 'n', 'u', 'z' }
static const symbol s_0_6 [4] = { 'm', 0xC4, 0xB1, 'z' }
static const symbol s_0_7 [4] = { 'n', 0xC4, 0xB1, 'z' }
static const symbol s_0_8 [4] = { 'm', 0xC3, 0xBC, 'z' }
static const symbol s_0_9 [4] = { 'n', 0xC3, 0xBC, 'z' }
static struct among a_0 [10]
static const symbol s_1_0 [4] = { 'l', 'e', 'r', 'i' }
static const symbol s_1_1 [5] = { 'l', 'a', 'r', 0xC4, 0xB1 }
static struct among a_1 [2]
static const symbol s_2_0 [2] = { 'n', 'i' }
static const symbol s_2_1 [2] = { 'n', 'u' }
static const symbol s_2_2 [3] = { 'n', 0xC4, 0xB1 }
static const symbol s_2_3 [3] = { 'n', 0xC3, 0xBC }
static struct among a_2 [4]
static const symbol s_3_0 [2] = { 'i', 'n' }
static const symbol s_3_1 [2] = { 'u', 'n' }
static const symbol s_3_2 [3] = { 0xC4, 0xB1, 'n' }
static const symbol s_3_3 [3] = { 0xC3, 0xBC, 'n' }
static struct among a_3 [4]
static const symbol s_4_0 [1] = { 'a' }
static const symbol s_4_1 [1] = { 'e' }
static struct among a_4 [2]
static const symbol s_5_0 [2] = { 'n', 'a' }
static const symbol s_5_1 [2] = { 'n', 'e' }
static struct among a_5 [2]
static const symbol s_6_0 [2] = { 'd', 'a' }
static const symbol s_6_1 [2] = { 't', 'a' }
static const symbol s_6_2 [2] = { 'd', 'e' }
static const symbol s_6_3 [2] = { 't', 'e' }
static struct among a_6 [4]
static const symbol s_7_0 [3] = { 'n', 'd', 'a' }
static const symbol s_7_1 [3] = { 'n', 'd', 'e' }
static struct among a_7 [2]
static const symbol s_8_0 [3] = { 'd', 'a', 'n' }
static const symbol s_8_1 [3] = { 't', 'a', 'n' }
static const symbol s_8_2 [3] = { 'd', 'e', 'n' }
static const symbol s_8_3 [3] = { 't', 'e', 'n' }
static struct among a_8 [4]
static const symbol s_9_0 [4] = { 'n', 'd', 'a', 'n' }
static const symbol s_9_1 [4] = { 'n', 'd', 'e', 'n' }
static struct among a_9 [2]
static const symbol s_10_0 [2] = { 'l', 'a' }
static const symbol s_10_1 [2] = { 'l', 'e' }
static struct among a_10 [2]
static const symbol s_11_0 [2] = { 'c', 'a' }
static const symbol s_11_1 [2] = { 'c', 'e' }
static struct among a_11 [2]
static const symbol s_12_0 [2] = { 'i', 'm' }
static const symbol s_12_1 [2] = { 'u', 'm' }
static const symbol s_12_2 [3] = { 0xC4, 0xB1, 'm' }
static const symbol s_12_3 [3] = { 0xC3, 0xBC, 'm' }
static struct among a_12 [4]
static const symbol s_13_0 [3] = { 's', 'i', 'n' }
static const symbol s_13_1 [3] = { 's', 'u', 'n' }
static const symbol s_13_2 [4] = { 's', 0xC4, 0xB1, 'n' }
static const symbol s_13_3 [4] = { 's', 0xC3, 0xBC, 'n' }
static struct among a_13 [4]
static const symbol s_14_0 [2] = { 'i', 'z' }
static const symbol s_14_1 [2] = { 'u', 'z' }
static const symbol s_14_2 [3] = { 0xC4, 0xB1, 'z' }
static const symbol s_14_3 [3] = { 0xC3, 0xBC, 'z' }
static struct among a_14 [4]
static const symbol s_15_0 [5] = { 's', 'i', 'n', 'i', 'z' }
static const symbol s_15_1 [5] = { 's', 'u', 'n', 'u', 'z' }
static const symbol s_15_2 [7] = { 's', 0xC4, 0xB1, 'n', 0xC4, 0xB1, 'z' }
static const symbol s_15_3 [7] = { 's', 0xC3, 0xBC, 'n', 0xC3, 0xBC, 'z' }
static struct among a_15 [4]
static const symbol s_16_0 [3] = { 'l', 'a', 'r' }
static const symbol s_16_1 [3] = { 'l', 'e', 'r' }
static struct among a_16 [2]
static const symbol s_17_0 [3] = { 'n', 'i', 'z' }
static const symbol s_17_1 [3] = { 'n', 'u', 'z' }
static const symbol s_17_2 [4] = { 'n', 0xC4, 0xB1, 'z' }
static const symbol s_17_3 [4] = { 'n', 0xC3, 0xBC, 'z' }
static struct among a_17 [4]
static const symbol s_18_0 [3] = { 'd', 'i', 'r' }
static const symbol s_18_1 [3] = { 't', 'i', 'r' }
static const symbol s_18_2 [3] = { 'd', 'u', 'r' }
static const symbol s_18_3 [3] = { 't', 'u', 'r' }
static const symbol s_18_4 [4] = { 'd', 0xC4, 0xB1, 'r' }
static const symbol s_18_5 [4] = { 't', 0xC4, 0xB1, 'r' }
static const symbol s_18_6 [4] = { 'd', 0xC3, 0xBC, 'r' }
static const symbol s_18_7 [4] = { 't', 0xC3, 0xBC, 'r' }
static struct among a_18 [8]
static const symbol s_19_0 [7] = { 'c', 'a', 's', 0xC4, 0xB1, 'n', 'a' }
static const symbol s_19_1 [6] = { 'c', 'e', 's', 'i', 'n', 'e' }
static struct among a_19 [2]
static const symbol s_20_0 [2] = { 'd', 'i' }
static const symbol s_20_1 [2] = { 't', 'i' }
static const symbol s_20_2 [3] = { 'd', 'i', 'k' }
static const symbol s_20_3 [3] = { 't', 'i', 'k' }
static const symbol s_20_4 [3] = { 'd', 'u', 'k' }
static const symbol s_20_5 [3] = { 't', 'u', 'k' }
static const symbol s_20_6 [4] = { 'd', 0xC4, 0xB1, 'k' }
static const symbol s_20_7 [4] = { 't', 0xC4, 0xB1, 'k' }
static const symbol s_20_8 [4] = { 'd', 0xC3, 0xBC, 'k' }
static const symbol s_20_9 [4] = { 't', 0xC3, 0xBC, 'k' }
static const symbol s_20_10 [3] = { 'd', 'i', 'm' }
static const symbol s_20_11 [3] = { 't', 'i', 'm' }
static const symbol s_20_12 [3] = { 'd', 'u', 'm' }
static const symbol s_20_13 [3] = { 't', 'u', 'm' }
static const symbol s_20_14 [4] = { 'd', 0xC4, 0xB1, 'm' }
static const symbol s_20_15 [4] = { 't', 0xC4, 0xB1, 'm' }
static const symbol s_20_16 [4] = { 'd', 0xC3, 0xBC, 'm' }
static const symbol s_20_17 [4] = { 't', 0xC3, 0xBC, 'm' }
static const symbol s_20_18 [3] = { 'd', 'i', 'n' }
static const symbol s_20_19 [3] = { 't', 'i', 'n' }
static const symbol s_20_20 [3] = { 'd', 'u', 'n' }
static const symbol s_20_21 [3] = { 't', 'u', 'n' }
static const symbol s_20_22 [4] = { 'd', 0xC4, 0xB1, 'n' }
static const symbol s_20_23 [4] = { 't', 0xC4, 0xB1, 'n' }
static const symbol s_20_24 [4] = { 'd', 0xC3, 0xBC, 'n' }
static const symbol s_20_25 [4] = { 't', 0xC3, 0xBC, 'n' }
static const symbol s_20_26 [2] = { 'd', 'u' }
static const symbol s_20_27 [2] = { 't', 'u' }
static const symbol s_20_28 [3] = { 'd', 0xC4, 0xB1 }
static const symbol s_20_29 [3] = { 't', 0xC4, 0xB1 }
static const symbol s_20_30 [3] = { 'd', 0xC3, 0xBC }
static const symbol s_20_31 [3] = { 't', 0xC3, 0xBC }
static struct among a_20 [32]
static const symbol s_21_0 [2] = { 's', 'a' }
static const symbol s_21_1 [2] = { 's', 'e' }
static const symbol s_21_2 [3] = { 's', 'a', 'k' }
static const symbol s_21_3 [3] = { 's', 'e', 'k' }
static const symbol s_21_4 [3] = { 's', 'a', 'm' }
static const symbol s_21_5 [3] = { 's', 'e', 'm' }
static const symbol s_21_6 [3] = { 's', 'a', 'n' }
static const symbol s_21_7 [3] = { 's', 'e', 'n' }
static struct among a_21 [8]
static const symbol s_22_0 [4] = { 'm', 'i', 0xC5, 0x9F }
static const symbol s_22_1 [4] = { 'm', 'u', 0xC5, 0x9F }
static const symbol s_22_2 [5] = { 'm', 0xC4, 0xB1, 0xC5, 0x9F }
static const symbol s_22_3 [5] = { 'm', 0xC3, 0xBC, 0xC5, 0x9F }
static struct among a_22 [4]
static const symbol s_23_0 [1] = { 'b' }
static const symbol s_23_1 [1] = { 'c' }
static const symbol s_23_2 [1] = { 'd' }
static const symbol s_23_3 [2] = { 0xC4, 0x9F }
static struct among a_23 [4]
static const unsigned char g_vowel [] = { 17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 8, 0, 0, 0, 0, 0, 0, 1 }
static const unsigned char g_U [] = { 1, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 1 }
static const unsigned char g_vowel1 [] = { 1, 64, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }
static const unsigned char g_vowel2 [] = { 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 130 }
static const unsigned char g_vowel3 [] = { 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }
static const unsigned char g_vowel4 [] = { 17 }
static const unsigned char g_vowel5 [] = { 65 }
static const unsigned char g_vowel6 [] = { 65 }
static const symbol s_0 [] = { 'a' }
static const symbol s_1 [] = { 'e' }
static const symbol s_2 [] = { 0xC4, 0xB1 }
static const symbol s_3 [] = { 'i' }
static const symbol s_4 [] = { 'o' }
static const symbol s_5 [] = { 0xC3, 0xB6 }
static const symbol s_6 [] = { 'u' }
static const symbol s_7 [] = { 0xC3, 0xBC }
static const symbol s_8 [] = { 'n' }
static const symbol s_9 [] = { 'n' }
static const symbol s_10 [] = { 's' }
static const symbol s_11 [] = { 's' }
static const symbol s_12 [] = { 'y' }
static const symbol s_13 [] = { 'y' }
static const symbol s_14 [] = { 'k', 'i' }
static const symbol s_15 [] = { 'k', 'e', 'n' }
static const symbol s_16 [] = { 'p' }
static const symbol s_17 [] = { 0xC3, 0xA7 }
static const symbol s_18 [] = { 't' }
static const symbol s_19 [] = { 'k' }
static const symbol s_20 [] = { 'd' }
static const symbol s_21 [] = { 'g' }
static const symbol s_22 [] = { 'a' }
static const symbol s_23 [] = { 0xC4, 0xB1 }
static const symbol s_24 [] = { 0xC4, 0xB1 }
static const symbol s_25 [] = { 'e' }
static const symbol s_26 [] = { 'i' }
static const symbol s_27 [] = { 'i' }
static const symbol s_28 [] = { 'o' }
static const symbol s_29 [] = { 'u' }
static const symbol s_30 [] = { 'u' }
static const symbol s_31 [] = { 0xC3, 0xB6 }
static const symbol s_32 [] = { 0xC3, 0xBC }
static const symbol s_33 [] = { 0xC3, 0xBC }
static const symbol s_34 [] = { 'a', 'd' }
static const symbol s_35 [] = { 's', 'o', 'y', 'a', 'd' }
Function Documentation
static int r_append_U_to_stems_ending_with_d_or_g (struct SN_env * z) [static]
Definition at line 1983 of file stem_UTF_8_turkish.cpp.
References SN_env::c, eq_s_b(), g_vowel, insert_s(), SN_env::l, out_grouping_b_U(), s_20, s_21, s_22, s_23, s_24, s_25, s_26, s_27, s_28, s_29, s_30, s_31, s_32, and s_33.
Referenced by r_postlude().
static int r_check_vowel_harmony (struct SN_env * z) [static]
Definition at line 479 of file stem_UTF_8_turkish.cpp.
References SN_env::c, eq_s_b(), g_vowel, g_vowel1, g_vowel2, g_vowel3, g_vowel4, g_vowel5, g_vowel6, SN_env::l, out_grouping_b_U(), s_0, s_1, s_2, s_3, s_4, s_5, s_6, and s_7.
Referenced by r_mark_DA(), r_mark_DAn(), r_mark_DUr(), r_mark_lAr(), r_mark_nA(), r_mark_ncA(), r_mark_ndA(), r_mark_ndAn(), r_mark_nU(), r_mark_nUn(), r_mark_nUz(), r_mark_sU(), r_mark_sUn(), r_mark_yA(), r_mark_yDU(), r_mark_ylA(), r_mark_ymUs_(), r_mark_yU(), r_mark_yUm(), and r_mark_yUz().
static int r_is_reserved_word (struct SN_env * z) [static]
Definition at line 2101 of file stem_UTF_8_turkish.cpp.
References SN_env::c, eq_s(), SN_env::I, SN_env::l, SN_env::p, s_34, s_35, and skip_utf8().
Referenced by r_postlude().
static int r_mark_cAsInA (struct SN_env * z) [static]
Definition at line 931 of file stem_UTF_8_turkish.cpp.
References SN_env::c, find_among_b(), SN_env::lb, and SN_env::p.
Referenced by r_stem_nominal_verb_suffixes().
static int r_mark_DA (struct SN_env * z) [static]
Definition at line 784 of file stem_UTF_8_turkish.cpp.
References SN_env::c, find_among_b(), SN_env::lb, SN_env::p, and r_check_vowel_harmony().
Referenced by r_stem_noun_suffixes(), and r_stem_suffix_chain_before_ki().
static int r_mark_DAn (struct SN_env * z) [static]
Definition at line 804 of file stem_UTF_8_turkish.cpp.
References SN_env::c, find_among_b(), SN_env::lb, SN_env::p, and r_check_vowel_harmony().
Referenced by r_stem_noun_suffixes().
static int r_mark_DUr (struct SN_env * z) [static]
Definition at line 921 of file stem_UTF_8_turkish.cpp.
References SN_env::c, find_among_b(), SN_env::lb, SN_env::p, and r_check_vowel_harmony().
Referenced by r_stem_nominal_verb_suffixes().
static int r_mark_ki (struct SN_env * z) [static]
Definition at line 838 of file stem_UTF_8_turkish.cpp.
References eq_s_b(), and s_14.
Referenced by r_stem_suffix_chain_before_ki().
static int r_mark_lAr (struct SN_env * z) [static]
Definition at line 901 of file stem_UTF_8_turkish.cpp.
References SN_env::c, find_among_b(), SN_env::lb, SN_env::p, and r_check_vowel_harmony().
Referenced by r_stem_nominal_verb_suffixes(), r_stem_noun_suffixes(), and r_stem_suffix_chain_before_ki().
static int r_mark_lArI (struct SN_env * z) [static]
Definition at line 718 of file stem_UTF_8_turkish.cpp.
References SN_env::c, find_among_b(), SN_env::lb, and SN_env::p.
Referenced by r_stem_noun_suffixes(), and r_stem_suffix_chain_before_ki().
static int r_mark_nA (struct SN_env * z) [static]
Definition at line 774 of file stem_UTF_8_turkish.cpp.
References SN_env::c, find_among_b(), SN_env::lb, SN_env::p, and r_check_vowel_harmony().
Referenced by r_stem_noun_suffixes().
static int r_mark_ncA (struct SN_env * z) [static]
Definition at line 843 of file stem_UTF_8_turkish.cpp.
References SN_env::c, find_among_b(), SN_env::lb, SN_env::p, r_check_vowel_harmony(), and r_mark_suffix_with_optional_n_consonant().
Referenced by r_stem_noun_suffixes().
static int r_mark_ndA (struct SN_env * z) [static]
Definition at line 794 of file stem_UTF_8_turkish.cpp.
References SN_env::c, find_among_b(), SN_env::lb, SN_env::p, and r_check_vowel_harmony().
Referenced by r_stem_noun_suffixes(), and r_stem_suffix_chain_before_ki().
static int r_mark_ndAn (struct SN_env * z) [static]
Definition at line 814 of file stem_UTF_8_turkish.cpp.
References SN_env::c, find_among_b(), SN_env::lb, SN_env::p, and r_check_vowel_harmony().
Referenced by r_stem_noun_suffixes().
static int r_mark_nU (struct SN_env * z) [static]
Definition at line 737 of file stem_UTF_8_turkish.cpp.
References find_among_b(), and r_check_vowel_harmony().
Referenced by r_stem_noun_suffixes().
static int r_mark_nUn (struct SN_env * z) [static]
Definition at line 746 of file stem_UTF_8_turkish.cpp.
References SN_env::c, find_among_b(), SN_env::lb, SN_env::p, r_check_vowel_harmony(), and r_mark_suffix_with_optional_n_consonant().
Referenced by r_stem_noun_suffixes(), and r_stem_suffix_chain_before_ki().
static int r_mark_nUz (struct SN_env * z) [static]
Definition at line 911 of file stem_UTF_8_turkish.cpp.
References SN_env::c, find_among_b(), SN_env::lb, SN_env::p, and r_check_vowel_harmony().
Referenced by r_stem_nominal_verb_suffixes().
static int r_mark_possessives (struct SN_env * z) [static]
Definition at line 695 of file stem_UTF_8_turkish.cpp.
References SN_env::c, find_among_b(), SN_env::lb, SN_env::p, and r_mark_suffix_with_optional_U_vowel().
Referenced by r_stem_noun_suffixes(), and r_stem_suffix_chain_before_ki().
static int r_mark_sU (struct SN_env * z) [static]
Definition at line 705 of file stem_UTF_8_turkish.cpp.
References g_U, in_grouping_b_U(), r_check_vowel_harmony(), and r_mark_suffix_with_optional_s_consonant().
Referenced by r_stem_noun_suffixes(), and r_stem_suffix_chain_before_ki().
static int r_mark_suffix_with_optional_n_consonant (struct SN_env * z) [static]
Definition at line 527 of file stem_UTF_8_turkish.cpp.
References SN_env::c, eq_s_b(), g_vowel, in_grouping_b_U(), SN_env::l, SN_env::lb, SN_env::p, s_8, s_9, and skip_utf8().
Referenced by r_mark_ncA(), and r_mark_nUn().
static int r_mark_suffix_with_optional_s_consonant (struct SN_env * z) [static]
Definition at line 569 of file stem_UTF_8_turkish.cpp.
References SN_env::c, eq_s_b(), g_vowel, in_grouping_b_U(), SN_env::l, SN_env::lb, SN_env::p, s_10, s_11, and skip_utf8().
Referenced by r_mark_sU().
static int r_mark_suffix_with_optional_U_vowel (struct SN_env * z) [static]
Definition at line 653 of file stem_UTF_8_turkish.cpp.
References SN_env::c, g_U, g_vowel, in_grouping_b_U(), SN_env::l, SN_env::lb, out_grouping_b_U(), SN_env::p, and skip_utf8().
Referenced by r_mark_possessives().
static int r_mark_suffix_with_optional_y_consonant (struct SN_env * z) [static]
Definition at line 611 of file stem_UTF_8_turkish.cpp.
References SN_env::c, eq_s_b(), g_vowel, in_grouping_b_U(), SN_env::l, SN_env::lb, SN_env::p, s_12, s_13, and skip_utf8().
Referenced by r_mark_yA(), r_mark_yDU(), r_mark_yken(), r_mark_ylA(), r_mark_ymUs_(), r_mark_ysA(), r_mark_yU(), r_mark_yUm(), and r_mark_yUz().
static int r_mark_sUn (struct SN_env * z) [static]
Definition at line 871 of file stem_UTF_8_turkish.cpp.
References SN_env::c, find_among_b(), SN_env::lb, SN_env::p, and r_check_vowel_harmony().
Referenced by r_stem_nominal_verb_suffixes().
static int r_mark_sUnUz (struct SN_env * z) [static]
Definition at line 895 of file stem_UTF_8_turkish.cpp.
References SN_env::c, find_among_b(), SN_env::lb, and SN_env::p.
Referenced by r_stem_nominal_verb_suffixes().
static int r_mark_yA (struct SN_env * z) [static]
Definition at line 760 of file stem_UTF_8_turkish.cpp.
References SN_env::c, find_among_b(), SN_env::lb, SN_env::p, r_check_vowel_harmony(), and r_mark_suffix_with_optional_y_consonant().
Referenced by r_stem_noun_suffixes().
static int r_mark_yDU (struct SN_env * z) [static]
Definition at line 937 of file stem_UTF_8_turkish.cpp.
References find_among_b(), r_check_vowel_harmony(), and r_mark_suffix_with_optional_y_consonant().
Referenced by r_stem_nominal_verb_suffixes().
static int r_mark_yken (struct SN_env * z) [static]
Definition at line 974 of file stem_UTF_8_turkish.cpp.
References eq_s_b(), r_mark_suffix_with_optional_y_consonant(), and s_15.
Referenced by r_stem_nominal_verb_suffixes().
static int r_mark_ylA (struct SN_env * z) [static]
Definition at line 824 of file stem_UTF_8_turkish.cpp.
References SN_env::c, find_among_b(), SN_env::lb, SN_env::p, r_check_vowel_harmony(), and r_mark_suffix_with_optional_y_consonant().
Referenced by r_stem_noun_suffixes().
static int r_mark_ymUs_ (struct SN_env * z) [static]
Definition at line 960 of file stem_UTF_8_turkish.cpp.
References SN_env::c, find_among_b(), SN_env::lb, SN_env::p, r_check_vowel_harmony(), and r_mark_suffix_with_optional_y_consonant().
Referenced by r_stem_nominal_verb_suffixes().
static int r_mark_ysA (struct SN_env * z) [static]
Definition at line 950 of file stem_UTF_8_turkish.cpp.
References SN_env::c, find_among_b(), SN_env::lb, SN_env::p, and r_mark_suffix_with_optional_y_consonant().
Referenced by r_stem_nominal_verb_suffixes().
static int r_mark_yU (struct SN_env * z) [static]
Definition at line 724 of file stem_UTF_8_turkish.cpp.
References g_U, in_grouping_b_U(), r_check_vowel_harmony(), and r_mark_suffix_with_optional_y_consonant().
Referenced by r_stem_noun_suffixes().
static int r_mark_yUm (struct SN_env * z) [static]
Definition at line 857 of file stem_UTF_8_turkish.cpp.
References SN_env::c, find_among_b(), SN_env::lb, SN_env::p, r_check_vowel_harmony(), and r_mark_suffix_with_optional_y_consonant().
Referenced by r_stem_nominal_verb_suffixes().
static int r_mark_yUz (struct SN_env * z) [static]
Definition at line 881 of file stem_UTF_8_turkish.cpp.
References SN_env::c, find_among_b(), SN_env::lb, SN_env::p, r_check_vowel_harmony(), and r_mark_suffix_with_optional_y_consonant().
Referenced by r_stem_nominal_verb_suffixes().
static int r_more_than_one_syllable_word (struct SN_env * z) [static]
Definition at line 2078 of file stem_UTF_8_turkish.cpp.
References SN_env::c, g_vowel, and out_grouping_U().
Referenced by turkish_UTF_8_stem().
static int r_post_process_last_consonants (struct SN_env * z) [static]
Definition at line 1951 of file stem_UTF_8_turkish.cpp.
References SN_env::bra, SN_env::c, find_among_b(), SN_env::ket, s_16, s_17, s_18, s_19, and slice_from_s().
Referenced by r_postlude().
static int r_postlude (struct SN_env * z) [static]
Definition at line 2139 of file stem_UTF_8_turkish.cpp.
References SN_env::c, SN_env::l, SN_env::lb, r_append_U_to_stems_ending_with_d_or_g(), r_is_reserved_word(), and r_post_process_last_consonants().
static int r_stem_nominal_verb_suffixes (struct SN_env * z) [static]
Definition at line 983 of file stem_UTF_8_turkish.cpp.
References SN_env::B, SN_env::bra, SN_env::c, SN_env::ket, SN_env::l, r_mark_cAsInA(), r_mark_DUr(), r_mark_lAr(), r_mark_nUz(), r_mark_sUn(), r_mark_sUnUz(), r_mark_yDU(), r_mark_yken(), r_mark_ymUs_(), r_mark_ysA(), r_mark_yUm(), r_mark_yUz(), and slice_del().
Referenced by turkish_UTF_8_stem().
static int r_stem_noun_suffixes (struct SN_env * z) [static]
Definition at line 1440 of file stem_UTF_8_turkish.cpp.
References SN_env::bra, SN_env::c, SN_env::ket, SN_env::l, r_mark_DA(), r_mark_DAn(), r_mark_lAr(), r_mark_lArI(), r_mark_nA(), r_mark_ncA(), r_mark_ndA(), r_mark_ndAn(), r_mark_nU(), r_mark_nUn(), r_mark_possessives(), r_mark_sU(), r_mark_yA(), r_mark_ylA(), r_mark_yU(), r_stem_suffix_chain_before_ki(), and slice_del().
Referenced by turkish_UTF_8_stem().
static int r_stem_suffix_chain_before_ki (struct SN_env * z) [static]
Definition at line 1241 of file stem_UTF_8_turkish.cpp.
References SN_env::bra, SN_env::c, SN_env::ket, SN_env::l, r_mark_DA(), r_mark_ki(), r_mark_lAr(), r_mark_lArI(), r_mark_ndA(), r_mark_nUn(), r_mark_possessives(), r_mark_sU(), and slice_del().
Referenced by r_stem_noun_suffixes().
void turkish_UTF_8_close_env (struct SN_env * z)
struct SN_env* turkish_UTF_8_create_env (void) [read]
int turkish_UTF_8_stem (struct SN_env * z)
Variable Documentation
struct among a_0[10] [static]
Initial value:
{
 { 1, s_0_0, -1, -1, 0},
 { 1, s_0_1, -1, -1, 0},
 { 3, s_0_2, -1, -1, 0},
 { 3, s_0_3, -1, -1, 0},
 { 3, s_0_4, -1, -1, 0},
 { 3, s_0_5, -1, -1, 0},
 { 4, s_0_6, -1, -1, 0},
 { 4, s_0_7, -1, -1, 0},
 { 4, s_0_8, -1, -1, 0},
 { 4, s_0_9, -1, -1, 0}
}
Definition at line 77 of file stem_UTF_8_turkish.cpp.
struct among a_1[2] [static]
Initial value:
{
 { 4, s_1_0, -1, -1, 0},
 { 5, s_1_1, -1, -1, 0}
}
Definition at line 94 of file stem_UTF_8_turkish.cpp.
struct among a_10[2] [static]
Initial value:
{
 { 2, s_10_0, -1, -1, 0},
 { 2, s_10_1, -1, -1, 0}
}
Definition at line 191 of file stem_UTF_8_turkish.cpp.
struct among a_11[2] [static]
Initial value:
{
 { 2, s_11_0, -1, -1, 0},
 { 2, s_11_1, -1, -1, 0}
}
Definition at line 200 of file stem_UTF_8_turkish.cpp.
struct among a_12[4] [static]
Initial value:
{
 { 2, s_12_0, -1, -1, 0},
 { 2, s_12_1, -1, -1, 0},
 { 3, s_12_2, -1, -1, 0},
 { 3, s_12_3, -1, -1, 0}
}
Definition at line 211 of file stem_UTF_8_turkish.cpp.
struct among a_13[4] [static]
Initial value:
{
 { 3, s_13_0, -1, -1, 0},
 { 3, s_13_1, -1, -1, 0},
 { 4, s_13_2, -1, -1, 0},
 { 4, s_13_3, -1, -1, 0}
}
Definition at line 224 of file stem_UTF_8_turkish.cpp.
struct among a_14[4] [static]
Initial value:
{
 { 2, s_14_0, -1, -1, 0},
 { 2, s_14_1, -1, -1, 0},
 { 3, s_14_2, -1, -1, 0},
 { 3, s_14_3, -1, -1, 0}
}
Definition at line 237 of file stem_UTF_8_turkish.cpp.
struct among a_15[4] [static]
Initial value:
{
 { 5, s_15_0, -1, -1, 0},
 { 5, s_15_1, -1, -1, 0},
 { 7, s_15_2, -1, -1, 0},
 { 7, s_15_3, -1, -1, 0}
}
Definition at line 250 of file stem_UTF_8_turkish.cpp.
struct among a_16[2] [static]
Initial value:
{
 { 3, s_16_0, -1, -1, 0},
 { 3, s_16_1, -1, -1, 0}
}
Definition at line 261 of file stem_UTF_8_turkish.cpp.
struct among a_17[4] [static]
Initial value:
{
 { 3, s_17_0, -1, -1, 0},
 { 3, s_17_1, -1, -1, 0},
 { 4, s_17_2, -1, -1, 0},
 { 4, s_17_3, -1, -1, 0}
}
Definition at line 272 of file stem_UTF_8_turkish.cpp.
struct among a_18[8] [static]
Initial value:
{
 { 3, s_18_0, -1, -1, 0},
 { 3, s_18_1, -1, -1, 0},
 { 3, s_18_2, -1, -1, 0},
 { 3, s_18_3, -1, -1, 0},
 { 4, s_18_4, -1, -1, 0},
 { 4, s_18_5, -1, -1, 0},
 { 4, s_18_6, -1, -1, 0},
 { 4, s_18_7, -1, -1, 0}
}
Definition at line 289 of file stem_UTF_8_turkish.cpp.
struct among a_19[2] [static]
Initial value:
{
 { 7, s_19_0, -1, -1, 0},
 { 6, s_19_1, -1, -1, 0}
}
Definition at line 304 of file stem_UTF_8_turkish.cpp.
struct among a_2[4] [static]
Initial value:
{
 { 2, s_2_0, -1, -1, 0},
 { 2, s_2_1, -1, -1, 0},
 { 3, s_2_2, -1, -1, 0},
 { 3, s_2_3, -1, -1, 0}
}
Definition at line 105 of file stem_UTF_8_turkish.cpp.
struct among a_20[32] [static]
Definition at line 343 of file stem_UTF_8_turkish.cpp.
struct among a_21[8] [static]
Initial value:
{
 { 2, s_21_0, -1, -1, 0},
 { 2, s_21_1, -1, -1, 0},
 { 3, s_21_2, -1, -1, 0},
 { 3, s_21_3, -1, -1, 0},
 { 3, s_21_4, -1, -1, 0},
 { 3, s_21_5, -1, -1, 0},
 { 3, s_21_6, -1, -1, 0},
 { 3, s_21_7, -1, -1, 0}
}
Definition at line 388 of file stem_UTF_8_turkish.cpp.
struct among a_22[4] [static]
Initial value:
{
 { 4, s_22_0, -1, -1, 0},
 { 4, s_22_1, -1, -1, 0},
 { 5, s_22_2, -1, -1, 0},
 { 5, s_22_3, -1, -1, 0}
}
Definition at line 405 of file stem_UTF_8_turkish.cpp.
struct among a_23[4] [static]
Initial value:
{
 { 1, s_23_0, -1, 1, 0},
 { 1, s_23_1, -1, 2, 0},
 { 1, s_23_2, -1, 3, 0},
 { 2, s_23_3, -1, 4, 0}
}
Definition at line 418 of file stem_UTF_8_turkish.cpp.
struct among a_3[4] [static]
Initial value:
{
 { 2, s_3_0, -1, -1, 0},
 { 2, s_3_1, -1, -1, 0},
 { 3, s_3_2, -1, -1, 0},
 { 3, s_3_3, -1, -1, 0}
}
Definition at line 118 of file stem_UTF_8_turkish.cpp.
struct among a_4[2] [static]
Initial value:
{
 { 1, s_4_0, -1, -1, 0},
 { 1, s_4_1, -1, -1, 0}
}
Definition at line 129 of file stem_UTF_8_turkish.cpp.
struct among a_5[2] [static]
Initial value:
{
 { 2, s_5_0, -1, -1, 0},
 { 2, s_5_1, -1, -1, 0}
}
Definition at line 138 of file stem_UTF_8_turkish.cpp.
struct among a_6[4] [static]
Initial value:
{
 { 2, s_6_0, -1, -1, 0},
 { 2, s_6_1, -1, -1, 0},
 { 2, s_6_2, -1, -1, 0},
 { 2, s_6_3, -1, -1, 0}
}
Definition at line 149 of file stem_UTF_8_turkish.cpp.
struct among a_7[2] [static]
Initial value:
{
 { 3, s_7_0, -1, -1, 0},
 { 3, s_7_1, -1, -1, 0}
}
Definition at line 160 of file stem_UTF_8_turkish.cpp.
struct among a_8[4] [static]
Initial value:
{
 { 3, s_8_0, -1, -1, 0},
 { 3, s_8_1, -1, -1, 0},
 { 3, s_8_2, -1, -1, 0},
 { 3, s_8_3, -1, -1, 0}
}
Definition at line 171 of file stem_UTF_8_turkish.cpp.
struct among a_9[2] [static]
Initial value:
{
 { 4, s_9_0, -1, -1, 0},
 { 4, s_9_1, -1, -1, 0}
}
Definition at line 182 of file stem_UTF_8_turkish.cpp.
const unsigned char g_U[] = { 1, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 1 } [static]
Definition at line 428 of file stem_UTF_8_turkish.cpp.
Referenced by r_mark_sU(), r_mark_suffix_with_optional_U_vowel(), and r_mark_yU().
const unsigned char g_vowel[] = { 17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 8, 0, 0, 0, 0, 0, 0, 1 } [static]
Definition at line 426 of file stem_UTF_8_turkish.cpp.
Referenced by r_append_U_to_stems_ending_with_d_or_g(), r_check_vowel_harmony(), r_mark_suffix_with_optional_n_consonant(), r_mark_suffix_with_optional_s_consonant(), r_mark_suffix_with_optional_U_vowel(), r_mark_suffix_with_optional_y_consonant(), and r_more_than_one_syllable_word().
const unsigned char g_vowel1[] = { 1, 64, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 } [static]
Definition at line 430 of file stem_UTF_8_turkish.cpp.
Referenced by r_check_vowel_harmony().
const unsigned char g_vowel2[] = { 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 130 } [static]
Definition at line 432 of file stem_UTF_8_turkish.cpp.
Referenced by r_check_vowel_harmony().
const unsigned char g_vowel3[] = { 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 } [static]
Definition at line 434 of file stem_UTF_8_turkish.cpp.
Referenced by r_check_vowel_harmony().
const unsigned char g_vowel4[] = { 17 } [static]
Definition at line 436 of file stem_UTF_8_turkish.cpp.
Referenced by r_check_vowel_harmony().
const unsigned char g_vowel5[] = { 65 } [static]
Definition at line 438 of file stem_UTF_8_turkish.cpp.
Referenced by r_check_vowel_harmony().
const unsigned char g_vowel6[] = { 65 } [static]
Definition at line 440 of file stem_UTF_8_turkish.cpp.
Referenced by r_check_vowel_harmony().
const symbol s_0[] = { 'a' } [static]
Definition at line 442 of file stem_UTF_8_turkish.cpp.
const symbol s_0_0[1] = { 'm' } [static]
Definition at line 66 of file stem_UTF_8_turkish.cpp.
const symbol s_0_1[1] = { 'n' } [static]
Definition at line 67 of file stem_UTF_8_turkish.cpp.
const symbol s_0_2[3] = { 'm', 'i', 'z' } [static]
Definition at line 68 of file stem_UTF_8_turkish.cpp.
const symbol s_0_3[3] = { 'n', 'i', 'z' } [static]
Definition at line 69 of file stem_UTF_8_turkish.cpp.
const symbol s_0_4[3] = { 'm', 'u', 'z' } [static]
Definition at line 70 of file stem_UTF_8_turkish.cpp.
const symbol s_0_5[3] = { 'n', 'u', 'z' } [static]
Definition at line 71 of file stem_UTF_8_turkish.cpp.
const symbol s_0_6[4] = { 'm', 0xC4, 0xB1, 'z' } [static]
Definition at line 72 of file stem_UTF_8_turkish.cpp.
const symbol s_0_7[4] = { 'n', 0xC4, 0xB1, 'z' } [static]
Definition at line 73 of file stem_UTF_8_turkish.cpp.
const symbol s_0_8[4] = { 'm', 0xC3, 0xBC, 'z' } [static]
Definition at line 74 of file stem_UTF_8_turkish.cpp.
const symbol s_0_9[4] = { 'n', 0xC3, 0xBC, 'z' } [static]
Definition at line 75 of file stem_UTF_8_turkish.cpp.
const symbol s_1[] = { 'e' } [static]
Definition at line 443 of file stem_UTF_8_turkish.cpp.
const symbol s_10[] = { 's' } [static]
Definition at line 452 of file stem_UTF_8_turkish.cpp.
const symbol s_10_0[2] = { 'l', 'a' } [static]
Definition at line 188 of file stem_UTF_8_turkish.cpp.
const symbol s_10_1[2] = { 'l', 'e' } [static]
Definition at line 189 of file stem_UTF_8_turkish.cpp.
const symbol s_11[] = { 's' } [static]
Definition at line 453 of file stem_UTF_8_turkish.cpp.
const symbol s_11_0[2] = { 'c', 'a' } [static]
Definition at line 197 of file stem_UTF_8_turkish.cpp.
const symbol s_11_1[2] = { 'c', 'e' } [static]
Definition at line 198 of file stem_UTF_8_turkish.cpp.
const symbol s_12[] = { 'y' } [static]
Definition at line 454 of file stem_UTF_8_turkish.cpp.
const symbol s_12_0[2] = { 'i', 'm' } [static]
Definition at line 206 of file stem_UTF_8_turkish.cpp.
const symbol s_12_1[2] = { 'u', 'm' } [static]
Definition at line 207 of file stem_UTF_8_turkish.cpp.
const symbol s_12_2[3] = { 0xC4, 0xB1, 'm' } [static]
Definition at line 208 of file stem_UTF_8_turkish.cpp.
const symbol s_12_3[3] = { 0xC3, 0xBC, 'm' } [static]
Definition at line 209 of file stem_UTF_8_turkish.cpp.
const symbol s_13[] = { 'y' } [static]
Definition at line 455 of file stem_UTF_8_turkish.cpp.
const symbol s_13_0[3] = { 's', 'i', 'n' } [static]
Definition at line 219 of file stem_UTF_8_turkish.cpp.
const symbol s_13_1[3] = { 's', 'u', 'n' } [static]
Definition at line 220 of file stem_UTF_8_turkish.cpp.
const symbol s_13_2[4] = { 's', 0xC4, 0xB1, 'n' } [static]
Definition at line 221 of file stem_UTF_8_turkish.cpp.
const symbol s_13_3[4] = { 's', 0xC3, 0xBC, 'n' } [static]
Definition at line 222 of file stem_UTF_8_turkish.cpp.
const symbol s_14[] = { 'k', 'i' } [static]
Definition at line 456 of file stem_UTF_8_turkish.cpp.
const symbol s_14_0[2] = { 'i', 'z' } [static]
Definition at line 232 of file stem_UTF_8_turkish.cpp.
const symbol s_14_1[2] = { 'u', 'z' } [static]
Definition at line 233 of file stem_UTF_8_turkish.cpp.
const symbol s_14_2[3] = { 0xC4, 0xB1, 'z' } [static]
Definition at line 234 of file stem_UTF_8_turkish.cpp.
const symbol s_14_3[3] = { 0xC3, 0xBC, 'z' } [static]
Definition at line 235 of file stem_UTF_8_turkish.cpp.
const symbol s_15[] = { 'k', 'e', 'n' } [static]
Definition at line 457 of file stem_UTF_8_turkish.cpp.
const symbol s_15_0[5] = { 's', 'i', 'n', 'i', 'z' } [static]
Definition at line 245 of file stem_UTF_8_turkish.cpp.
const symbol s_15_1[5] = { 's', 'u', 'n', 'u', 'z' } [static]
Definition at line 246 of file stem_UTF_8_turkish.cpp.
const symbol s_15_2[7] = { 's', 0xC4, 0xB1, 'n', 0xC4, 0xB1, 'z' } [static]
Definition at line 247 of file stem_UTF_8_turkish.cpp.
const symbol s_15_3[7] = { 's', 0xC3, 0xBC, 'n', 0xC3, 0xBC, 'z' } [static]
Definition at line 248 of file stem_UTF_8_turkish.cpp.
const symbol s_16[] = { 'p' } [static]
Definition at line 458 of file stem_UTF_8_turkish.cpp.
const symbol s_16_0[3] = { 'l', 'a', 'r' } [static]
Definition at line 258 of file stem_UTF_8_turkish.cpp.
const symbol s_16_1[3] = { 'l', 'e', 'r' } [static]
Definition at line 259 of file stem_UTF_8_turkish.cpp.
const symbol s_17[] = { 0xC3, 0xA7 } [static]
Definition at line 459 of file stem_UTF_8_turkish.cpp.
const symbol s_17_0[3] = { 'n', 'i', 'z' } [static]
Definition at line 267 of file stem_UTF_8_turkish.cpp.
const symbol s_17_1[3] = { 'n', 'u', 'z' } [static]
Definition at line 268 of file stem_UTF_8_turkish.cpp.
const symbol s_17_2[4] = { 'n', 0xC4, 0xB1, 'z' } [static]
Definition at line 269 of file stem_UTF_8_turkish.cpp.
const symbol s_17_3[4] = { 'n', 0xC3, 0xBC, 'z' } [static]
Definition at line 270 of file stem_UTF_8_turkish.cpp.
const symbol s_18[] = { 't' } [static]
Definition at line 460 of file stem_UTF_8_turkish.cpp.
const symbol s_18_0[3] = { 'd', 'i', 'r' } [static]
Definition at line 280 of file stem_UTF_8_turkish.cpp.
const symbol s_18_1[3] = { 't', 'i', 'r' } [static]
Definition at line 281 of file stem_UTF_8_turkish.cpp.
const symbol s_18_2[3] = { 'd', 'u', 'r' } [static]
Definition at line 282 of file stem_UTF_8_turkish.cpp.
const symbol s_18_3[3] = { 't', 'u', 'r' } [static]
Definition at line 283 of file stem_UTF_8_turkish.cpp.
const symbol s_18_4[4] = { 'd', 0xC4, 0xB1, 'r' } [static]
Definition at line 284 of file stem_UTF_8_turkish.cpp.
const symbol s_18_5[4] = { 't', 0xC4, 0xB1, 'r' } [static]
Definition at line 285 of file stem_UTF_8_turkish.cpp.
const symbol s_18_6[4] = { 'd', 0xC3, 0xBC, 'r' } [static]
Definition at line 286 of file stem_UTF_8_turkish.cpp.
const symbol s_18_7[4] = { 't', 0xC3, 0xBC, 'r' } [static]
Definition at line 287 of file stem_UTF_8_turkish.cpp.
const symbol s_19[] = { 'k' } [static]
Definition at line 461 of file stem_UTF_8_turkish.cpp.
const symbol s_19_0[7] = { 'c', 'a', 's', 0xC4, 0xB1, 'n', 'a' } [static]
Definition at line 301 of file stem_UTF_8_turkish.cpp.
const symbol s_19_1[6] = { 'c', 'e', 's', 'i', 'n', 'e' } [static]
Definition at line 302 of file stem_UTF_8_turkish.cpp.
const symbol s_1_0[4] = { 'l', 'e', 'r', 'i' } [static]
Definition at line 91 of file stem_UTF_8_turkish.cpp.
const symbol s_1_1[5] = { 'l', 'a', 'r', 0xC4, 0xB1 } [static]
Definition at line 92 of file stem_UTF_8_turkish.cpp.
const symbol s_2[] = { 0xC4, 0xB1 } [static]
Definition at line 444 of file stem_UTF_8_turkish.cpp.
const symbol s_20[] = { 'd' } [static]
Definition at line 462 of file stem_UTF_8_turkish.cpp.
const symbol s_20_0[2] = { 'd', 'i' } [static]
Definition at line 310 of file stem_UTF_8_turkish.cpp.
const symbol s_20_1[2] = { 't', 'i' } [static]
Definition at line 311 of file stem_UTF_8_turkish.cpp.
const symbol s_20_10[3] = { 'd', 'i', 'm' } [static]
Definition at line 320 of file stem_UTF_8_turkish.cpp.
const symbol s_20_11[3] = { 't', 'i', 'm' } [static]
Definition at line 321 of file stem_UTF_8_turkish.cpp.
const symbol s_20_12[3] = { 'd', 'u', 'm' } [static]
Definition at line 322 of file stem_UTF_8_turkish.cpp.
const symbol s_20_13[3] = { 't', 'u', 'm' } [static]
Definition at line 323 of file stem_UTF_8_turkish.cpp.
const symbol s_20_14[4] = { 'd', 0xC4, 0xB1, 'm' } [static]
Definition at line 324 of file stem_UTF_8_turkish.cpp.
const symbol s_20_15[4] = { 't', 0xC4, 0xB1, 'm' } [static]
Definition at line 325 of file stem_UTF_8_turkish.cpp.
const symbol s_20_16[4] = { 'd', 0xC3, 0xBC, 'm' } [static]
Definition at line 326 of file stem_UTF_8_turkish.cpp.
const symbol s_20_17[4] = { 't', 0xC3, 0xBC, 'm' } [static]
Definition at line 327 of file stem_UTF_8_turkish.cpp.
const symbol s_20_18[3] = { 'd', 'i', 'n' } [static]
Definition at line 328 of file stem_UTF_8_turkish.cpp.
const symbol s_20_19[3] = { 't', 'i', 'n' } [static]
Definition at line 329 of file stem_UTF_8_turkish.cpp.
const symbol s_20_2[3] = { 'd', 'i', 'k' } [static]
Definition at line 312 of file stem_UTF_8_turkish.cpp.
const symbol s_20_20[3] = { 'd', 'u', 'n' } [static]
Definition at line 330 of file stem_UTF_8_turkish.cpp.
const symbol s_20_21[3] = { 't', 'u', 'n' } [static]
Definition at line 331 of file stem_UTF_8_turkish.cpp.
const symbol s_20_22[4] = { 'd', 0xC4, 0xB1, 'n' } [static]
Definition at line 332 of file stem_UTF_8_turkish.cpp.
const symbol s_20_23[4] = { 't', 0xC4, 0xB1, 'n' } [static]
Definition at line 333 of file stem_UTF_8_turkish.cpp.
const symbol s_20_24[4] = { 'd', 0xC3, 0xBC, 'n' } [static]
Definition at line 334 of file stem_UTF_8_turkish.cpp.
const symbol s_20_25[4] = { 't', 0xC3, 0xBC, 'n' } [static]
Definition at line 335 of file stem_UTF_8_turkish.cpp.
const symbol s_20_26[2] = { 'd', 'u' } [static]
Definition at line 336 of file stem_UTF_8_turkish.cpp.
const symbol s_20_27[2] = { 't', 'u' } [static]
Definition at line 337 of file stem_UTF_8_turkish.cpp.
const symbol s_20_28[3] = { 'd', 0xC4, 0xB1 } [static]
Definition at line 338 of file stem_UTF_8_turkish.cpp.
const symbol s_20_29[3] = { 't', 0xC4, 0xB1 } [static]
Definition at line 339 of file stem_UTF_8_turkish.cpp.
const symbol s_20_3[3] = { 't', 'i', 'k' } [static]
Definition at line 313 of file stem_UTF_8_turkish.cpp.
const symbol s_20_30[3] = { 'd', 0xC3, 0xBC } [static]
Definition at line 340 of file stem_UTF_8_turkish.cpp.
const symbol s_20_31[3] = { 't', 0xC3, 0xBC } [static]
Definition at line 341 of file stem_UTF_8_turkish.cpp.
const symbol s_20_4[3] = { 'd', 'u', 'k' } [static]
Definition at line 314 of file stem_UTF_8_turkish.cpp.
const symbol s_20_5[3] = { 't', 'u', 'k' } [static]
Definition at line 315 of file stem_UTF_8_turkish.cpp.
const symbol s_20_6[4] = { 'd', 0xC4, 0xB1, 'k' } [static]
Definition at line 316 of file stem_UTF_8_turkish.cpp.
const symbol s_20_7[4] = { 't', 0xC4, 0xB1, 'k' } [static]
Definition at line 317 of file stem_UTF_8_turkish.cpp.
const symbol s_20_8[4] = { 'd', 0xC3, 0xBC, 'k' } [static]
Definition at line 318 of file stem_UTF_8_turkish.cpp.
const symbol s_20_9[4] = { 't', 0xC3, 0xBC, 'k' } [static]
Definition at line 319 of file stem_UTF_8_turkish.cpp.
const symbol s_21[] = { 'g' } [static]
Definition at line 463 of file stem_UTF_8_turkish.cpp.
const symbol s_21_0[2] = { 's', 'a' } [static]
Definition at line 379 of file stem_UTF_8_turkish.cpp.
const symbol s_21_1[2] = { 's', 'e' } [static]
Definition at line 380 of file stem_UTF_8_turkish.cpp.
const symbol s_21_2[3] = { 's', 'a', 'k' } [static]
Definition at line 381 of file stem_UTF_8_turkish.cpp.
const symbol s_21_3[3] = { 's', 'e', 'k' } [static]
Definition at line 382 of file stem_UTF_8_turkish.cpp.
const symbol s_21_4[3] = { 's', 'a', 'm' } [static]
Definition at line 383 of file stem_UTF_8_turkish.cpp.
const symbol s_21_5[3] = { 's', 'e', 'm' } [static]
Definition at line 384 of file stem_UTF_8_turkish.cpp.
const symbol s_21_6[3] = { 's', 'a', 'n' } [static]
Definition at line 385 of file stem_UTF_8_turkish.cpp.
const symbol s_21_7[3] = { 's', 'e', 'n' } [static]
Definition at line 386 of file stem_UTF_8_turkish.cpp.
const symbol s_22[] = { 'a' } [static]
Definition at line 464 of file stem_UTF_8_turkish.cpp.
const symbol s_22_0[4] = { 'm', 'i', 0xC5, 0x9F } [static]
Definition at line 400 of file stem_UTF_8_turkish.cpp.
const symbol s_22_1[4] = { 'm', 'u', 0xC5, 0x9F } [static]
Definition at line 401 of file stem_UTF_8_turkish.cpp.
const symbol s_22_2[5] = { 'm', 0xC4, 0xB1, 0xC5, 0x9F } [static]
Definition at line 402 of file stem_UTF_8_turkish.cpp.
const symbol s_22_3[5] = { 'm', 0xC3, 0xBC, 0xC5, 0x9F } [static]
Definition at line 403 of file stem_UTF_8_turkish.cpp.
const symbol s_23[] = { 0xC4, 0xB1 } [static]
Definition at line 465 of file stem_UTF_8_turkish.cpp.
const symbol s_23_0[1] = { 'b' } [static]
Definition at line 413 of file stem_UTF_8_turkish.cpp.
const symbol s_23_1[1] = { 'c' } [static]
Definition at line 414 of file stem_UTF_8_turkish.cpp.
const symbol s_23_2[1] = { 'd' } [static]
Definition at line 415 of file stem_UTF_8_turkish.cpp.
const symbol s_23_3[2] = { 0xC4, 0x9F } [static]
Definition at line 416 of file stem_UTF_8_turkish.cpp.
const symbol s_24[] = { 0xC4, 0xB1 } [static]
Definition at line 466 of file stem_UTF_8_turkish.cpp.
const symbol s_25[] = { 'e' } [static]
Definition at line 467 of file stem_UTF_8_turkish.cpp.
const symbol s_26[] = { 'i' } [static]
Definition at line 468 of file stem_UTF_8_turkish.cpp.
const symbol s_27[] = { 'i' } [static]
Definition at line 469 of file stem_UTF_8_turkish.cpp.
const symbol s_28[] = { 'o' } [static]
Definition at line 470 of file stem_UTF_8_turkish.cpp.
const symbol s_29[] = { 'u' } [static]
Definition at line 471 of file stem_UTF_8_turkish.cpp.
const symbol s_2_0[2] = { 'n', 'i' } [static]
Definition at line 100 of file stem_UTF_8_turkish.cpp.
const symbol s_2_1[2] = { 'n', 'u' } [static]
Definition at line 101 of file stem_UTF_8_turkish.cpp.
const symbol s_2_2[3] = { 'n', 0xC4, 0xB1 } [static]
Definition at line 102 of file stem_UTF_8_turkish.cpp.
const symbol s_2_3[3] = { 'n', 0xC3, 0xBC } [static]
Definition at line 103 of file stem_UTF_8_turkish.cpp.
const symbol s_3[] = { 'i' } [static]
Definition at line 445 of file stem_UTF_8_turkish.cpp.
const symbol s_30[] = { 'u' } [static]
Definition at line 472 of file stem_UTF_8_turkish.cpp.
const symbol s_31[] = { 0xC3, 0xB6 } [static]
Definition at line 473 of file stem_UTF_8_turkish.cpp.
const symbol s_32[] = { 0xC3, 0xBC } [static]
Definition at line 474 of file stem_UTF_8_turkish.cpp.
const symbol s_33[] = { 0xC3, 0xBC } [static]
Definition at line 475 of file stem_UTF_8_turkish.cpp.
const symbol s_34[] = { 'a', 'd' } [static]
Definition at line 476 of file stem_UTF_8_turkish.cpp.
const symbol s_35[] = { 's', 'o', 'y', 'a', 'd' } [static]
Definition at line 477 of file stem_UTF_8_turkish.cpp.
const symbol s_3_0[2] = { 'i', 'n' } [static]
Definition at line 113 of file stem_UTF_8_turkish.cpp.
const symbol s_3_1[2] = { 'u', 'n' } [static]
Definition at line 114 of file stem_UTF_8_turkish.cpp.
const symbol s_3_2[3] = { 0xC4, 0xB1, 'n' } [static]
Definition at line 115 of file stem_UTF_8_turkish.cpp.
const symbol s_3_3[3] = { 0xC3, 0xBC, 'n' } [static]
Definition at line 116 of file stem_UTF_8_turkish.cpp.
const symbol s_4[] = { 'o' } [static]
Definition at line 446 of file stem_UTF_8_turkish.cpp.
const symbol s_4_0[1] = { 'a' } [static]
Definition at line 126 of file stem_UTF_8_turkish.cpp.
const symbol s_4_1[1] = { 'e' } [static]
Definition at line 127 of file stem_UTF_8_turkish.cpp.
const symbol s_5[] = { 0xC3, 0xB6 } [static]
Definition at line 447 of file stem_UTF_8_turkish.cpp.
const symbol s_5_0[2] = { 'n', 'a' } [static]
Definition at line 135 of file stem_UTF_8_turkish.cpp.
const symbol s_5_1[2] = { 'n', 'e' } [static]
Definition at line 136 of file stem_UTF_8_turkish.cpp.
const symbol s_6[] = { 'u' } [static]
Definition at line 448 of file stem_UTF_8_turkish.cpp.
const symbol s_6_0[2] = { 'd', 'a' } [static]
Definition at line 144 of file stem_UTF_8_turkish.cpp.
const symbol s_6_1[2] = { 't', 'a' } [static]
Definition at line 145 of file stem_UTF_8_turkish.cpp.
const symbol s_6_2[2] = { 'd', 'e' } [static]
Definition at line 146 of file stem_UTF_8_turkish.cpp.
const symbol s_6_3[2] = { 't', 'e' } [static]
Definition at line 147 of file stem_UTF_8_turkish.cpp.
const symbol s_7[] = { 0xC3, 0xBC } [static]
Definition at line 449 of file stem_UTF_8_turkish.cpp.
const symbol s_7_0[3] = { 'n', 'd', 'a' } [static]
Definition at line 157 of file stem_UTF_8_turkish.cpp.
const symbol s_7_1[3] = { 'n', 'd', 'e' } [static]
Definition at line 158 of file stem_UTF_8_turkish.cpp.
const symbol s_8[] = { 'n' } [static]
Definition at line 450 of file stem_UTF_8_turkish.cpp.
const symbol s_8_0[3] = { 'd', 'a', 'n' } [static]
Definition at line 166 of file stem_UTF_8_turkish.cpp.
const symbol s_8_1[3] = { 't', 'a', 'n' } [static]
Definition at line 167 of file stem_UTF_8_turkish.cpp.
const symbol s_8_2[3] = { 'd', 'e', 'n' } [static]
Definition at line 168 of file stem_UTF_8_turkish.cpp.
const symbol s_8_3[3] = { 't', 'e', 'n' } [static]
Definition at line 169 of file stem_UTF_8_turkish.cpp.
const symbol s_9[] = { 'n' } [static]
Definition at line 451 of file stem_UTF_8_turkish.cpp.
const symbol s_9_0[4] = { 'n', 'd', 'a', 'n' } [static]
Definition at line 179 of file stem_UTF_8_turkish.cpp.
const symbol s_9_1[4] = { 'n', 'd', 'e', 'n' } [static]
Definition at line 180 of file stem_UTF_8_turkish.cpp.