/disk/workspace-cpp/la-manager/source/stem/stem_UTF_8_spanish.cpp File Reference
#include <stem/header.h>
Functions
int spanish_UTF_8_stem (struct SN_env *z)
static int r_residual_suffix (struct SN_env *z)
static int r_verb_suffix (struct SN_env *z)
static int r_y_verb_suffix (struct SN_env *z)
static int r_standard_suffix (struct SN_env *z)
static int r_attached_pronoun (struct SN_env *z)
static int r_R2 (struct SN_env *z)
static int r_R1 (struct SN_env *z)
static int r_RV (struct SN_env *z)
static int r_mark_regions (struct SN_env *z)
static int r_postlude (struct SN_env *z)
struct SN_env * spanish_UTF_8_create_env (void)
void spanish_UTF_8_close_env (struct SN_env *z)
Variables
static const symbol s_0_1 [2] = { 0xC3, 0xA1 }
static const symbol s_0_2 [2] = { 0xC3, 0xA9 }
static const symbol s_0_3 [2] = { 0xC3, 0xAD }
static const symbol s_0_4 [2] = { 0xC3, 0xB3 }
static const symbol s_0_5 [2] = { 0xC3, 0xBA }
static struct among a_0 [6]
static const symbol s_1_0 [2] = { 'l', 'a' }
static const symbol s_1_1 [4] = { 's', 'e', 'l', 'a' }
static const symbol s_1_2 [2] = { 'l', 'e' }
static const symbol s_1_3 [2] = { 'm', 'e' }
static const symbol s_1_4 [2] = { 's', 'e' }
static const symbol s_1_5 [2] = { 'l', 'o' }
static const symbol s_1_6 [4] = { 's', 'e', 'l', 'o' }
static const symbol s_1_7 [3] = { 'l', 'a', 's' }
static const symbol s_1_8 [5] = { 's', 'e', 'l', 'a', 's' }
static const symbol s_1_9 [3] = { 'l', 'e', 's' }
static const symbol s_1_10 [3] = { 'l', 'o', 's' }
static const symbol s_1_11 [5] = { 's', 'e', 'l', 'o', 's' }
static const symbol s_1_12 [3] = { 'n', 'o', 's' }
static struct among a_1 [13]
static const symbol s_2_0 [4] = { 'a', 'n', 'd', 'o' }
static const symbol s_2_1 [5] = { 'i', 'e', 'n', 'd', 'o' }
static const symbol s_2_2 [5] = { 'y', 'e', 'n', 'd', 'o' }
static const symbol s_2_3 [5] = { 0xC3, 0xA1, 'n', 'd', 'o' }
static const symbol s_2_4 [6] = { 'i', 0xC3, 0xA9, 'n', 'd', 'o' }
static const symbol s_2_5 [2] = { 'a', 'r' }
static const symbol s_2_6 [2] = { 'e', 'r' }
static const symbol s_2_7 [2] = { 'i', 'r' }
static const symbol s_2_8 [3] = { 0xC3, 0xA1, 'r' }
static const symbol s_2_9 [3] = { 0xC3, 0xA9, 'r' }
static const symbol s_2_10 [3] = { 0xC3, 0xAD, 'r' }
static struct among a_2 [11]
static const symbol s_3_0 [2] = { 'i', 'c' }
static const symbol s_3_1 [2] = { 'a', 'd' }
static const symbol s_3_2 [2] = { 'o', 's' }
static const symbol s_3_3 [2] = { 'i', 'v' }
static struct among a_3 [4]
static const symbol s_4_0 [4] = { 'a', 'b', 'l', 'e' }
static const symbol s_4_1 [4] = { 'i', 'b', 'l', 'e' }
static const symbol s_4_2 [4] = { 'a', 'n', 't', 'e' }
static struct among a_4 [3]
static const symbol s_5_0 [2] = { 'i', 'c' }
static const symbol s_5_1 [4] = { 'a', 'b', 'i', 'l' }
static const symbol s_5_2 [2] = { 'i', 'v' }
static struct among a_5 [3]
static const symbol s_6_0 [3] = { 'i', 'c', 'a' }
static const symbol s_6_1 [5] = { 'a', 'n', 'c', 'i', 'a' }
static const symbol s_6_2 [5] = { 'e', 'n', 'c', 'i', 'a' }
static const symbol s_6_3 [5] = { 'a', 'd', 'o', 'r', 'a' }
static const symbol s_6_4 [3] = { 'o', 's', 'a' }
static const symbol s_6_5 [4] = { 'i', 's', 't', 'a' }
static const symbol s_6_6 [3] = { 'i', 'v', 'a' }
static const symbol s_6_7 [4] = { 'a', 'n', 'z', 'a' }
static const symbol s_6_8 [6] = { 'l', 'o', 'g', 0xC3, 0xAD, 'a' }
static const symbol s_6_9 [4] = { 'i', 'd', 'a', 'd' }
static const symbol s_6_10 [4] = { 'a', 'b', 'l', 'e' }
static const symbol s_6_11 [4] = { 'i', 'b', 'l', 'e' }
static const symbol s_6_12 [4] = { 'a', 'n', 't', 'e' }
static const symbol s_6_13 [5] = { 'm', 'e', 'n', 't', 'e' }
static const symbol s_6_14 [6] = { 'a', 'm', 'e', 'n', 't', 'e' }
static const symbol s_6_15 [6] = { 'a', 'c', 'i', 0xC3, 0xB3, 'n' }
static const symbol s_6_16 [6] = { 'u', 'c', 'i', 0xC3, 0xB3, 'n' }
static const symbol s_6_17 [3] = { 'i', 'c', 'o' }
static const symbol s_6_18 [4] = { 'i', 's', 'm', 'o' }
static const symbol s_6_19 [3] = { 'o', 's', 'o' }
static const symbol s_6_20 [7] = { 'a', 'm', 'i', 'e', 'n', 't', 'o' }
static const symbol s_6_21 [7] = { 'i', 'm', 'i', 'e', 'n', 't', 'o' }
static const symbol s_6_22 [3] = { 'i', 'v', 'o' }
static const symbol s_6_23 [4] = { 'a', 'd', 'o', 'r' }
static const symbol s_6_24 [4] = { 'i', 'c', 'a', 's' }
static const symbol s_6_25 [6] = { 'a', 'n', 'c', 'i', 'a', 's' }
static const symbol s_6_26 [6] = { 'e', 'n', 'c', 'i', 'a', 's' }
static const symbol s_6_27 [6] = { 'a', 'd', 'o', 'r', 'a', 's' }
static const symbol s_6_28 [4] = { 'o', 's', 'a', 's' }
static const symbol s_6_29 [5] = { 'i', 's', 't', 'a', 's' }
static const symbol s_6_30 [4] = { 'i', 'v', 'a', 's' }
static const symbol s_6_31 [5] = { 'a', 'n', 'z', 'a', 's' }
static const symbol s_6_32 [7] = { 'l', 'o', 'g', 0xC3, 0xAD, 'a', 's' }
static const symbol s_6_33 [6] = { 'i', 'd', 'a', 'd', 'e', 's' }
static const symbol s_6_34 [5] = { 'a', 'b', 'l', 'e', 's' }
static const symbol s_6_35 [5] = { 'i', 'b', 'l', 'e', 's' }
static const symbol s_6_36 [7] = { 'a', 'c', 'i', 'o', 'n', 'e', 's' }
static const symbol s_6_37 [7] = { 'u', 'c', 'i', 'o', 'n', 'e', 's' }
static const symbol s_6_38 [6] = { 'a', 'd', 'o', 'r', 'e', 's' }
static const symbol s_6_39 [5] = { 'a', 'n', 't', 'e', 's' }
static const symbol s_6_40 [4] = { 'i', 'c', 'o', 's' }
static const symbol s_6_41 [5] = { 'i', 's', 'm', 'o', 's' }
static const symbol s_6_42 [4] = { 'o', 's', 'o', 's' }
static const symbol s_6_43 [8] = { 'a', 'm', 'i', 'e', 'n', 't', 'o', 's' }
static const symbol s_6_44 [8] = { 'i', 'm', 'i', 'e', 'n', 't', 'o', 's' }
static const symbol s_6_45 [4] = { 'i', 'v', 'o', 's' }
static struct among a_6 [46]
static const symbol s_7_0 [2] = { 'y', 'a' }
static const symbol s_7_1 [2] = { 'y', 'e' }
static const symbol s_7_2 [3] = { 'y', 'a', 'n' }
static const symbol s_7_3 [3] = { 'y', 'e', 'n' }
static const symbol s_7_4 [5] = { 'y', 'e', 'r', 'o', 'n' }
static const symbol s_7_5 [5] = { 'y', 'e', 'n', 'd', 'o' }
static const symbol s_7_6 [2] = { 'y', 'o' }
static const symbol s_7_7 [3] = { 'y', 'a', 's' }
static const symbol s_7_8 [3] = { 'y', 'e', 's' }
static const symbol s_7_9 [4] = { 'y', 'a', 'i', 's' }
static const symbol s_7_10 [5] = { 'y', 'a', 'm', 'o', 's' }
static const symbol s_7_11 [3] = { 'y', 0xC3, 0xB3 }
static struct among a_7 [12]
static const symbol s_8_0 [3] = { 'a', 'b', 'a' }
static const symbol s_8_1 [3] = { 'a', 'd', 'a' }
static const symbol s_8_2 [3] = { 'i', 'd', 'a' }
static const symbol s_8_3 [3] = { 'a', 'r', 'a' }
static const symbol s_8_4 [4] = { 'i', 'e', 'r', 'a' }
static const symbol s_8_5 [3] = { 0xC3, 0xAD, 'a' }
static const symbol s_8_6 [5] = { 'a', 'r', 0xC3, 0xAD, 'a' }
static const symbol s_8_7 [5] = { 'e', 'r', 0xC3, 0xAD, 'a' }
static const symbol s_8_8 [5] = { 'i', 'r', 0xC3, 0xAD, 'a' }
static const symbol s_8_9 [2] = { 'a', 'd' }
static const symbol s_8_10 [2] = { 'e', 'd' }
static const symbol s_8_11 [2] = { 'i', 'd' }
static const symbol s_8_12 [3] = { 'a', 's', 'e' }
static const symbol s_8_13 [4] = { 'i', 'e', 's', 'e' }
static const symbol s_8_14 [4] = { 'a', 's', 't', 'e' }
static const symbol s_8_15 [4] = { 'i', 's', 't', 'e' }
static const symbol s_8_16 [2] = { 'a', 'n' }
static const symbol s_8_17 [4] = { 'a', 'b', 'a', 'n' }
static const symbol s_8_18 [4] = { 'a', 'r', 'a', 'n' }
static const symbol s_8_19 [5] = { 'i', 'e', 'r', 'a', 'n' }
static const symbol s_8_20 [4] = { 0xC3, 0xAD, 'a', 'n' }
static const symbol s_8_21 [6] = { 'a', 'r', 0xC3, 0xAD, 'a', 'n' }
static const symbol s_8_22 [6] = { 'e', 'r', 0xC3, 0xAD, 'a', 'n' }
static const symbol s_8_23 [6] = { 'i', 'r', 0xC3, 0xAD, 'a', 'n' }
static const symbol s_8_24 [2] = { 'e', 'n' }
static const symbol s_8_25 [4] = { 'a', 's', 'e', 'n' }
static const symbol s_8_26 [5] = { 'i', 'e', 's', 'e', 'n' }
static const symbol s_8_27 [4] = { 'a', 'r', 'o', 'n' }
static const symbol s_8_28 [5] = { 'i', 'e', 'r', 'o', 'n' }
static const symbol s_8_29 [5] = { 'a', 'r', 0xC3, 0xA1, 'n' }
static const symbol s_8_30 [5] = { 'e', 'r', 0xC3, 0xA1, 'n' }
static const symbol s_8_31 [5] = { 'i', 'r', 0xC3, 0xA1, 'n' }
static const symbol s_8_32 [3] = { 'a', 'd', 'o' }
static const symbol s_8_33 [3] = { 'i', 'd', 'o' }
static const symbol s_8_34 [4] = { 'a', 'n', 'd', 'o' }
static const symbol s_8_35 [5] = { 'i', 'e', 'n', 'd', 'o' }
static const symbol s_8_36 [2] = { 'a', 'r' }
static const symbol s_8_37 [2] = { 'e', 'r' }
static const symbol s_8_38 [2] = { 'i', 'r' }
static const symbol s_8_39 [2] = { 'a', 's' }
static const symbol s_8_40 [4] = { 'a', 'b', 'a', 's' }
static const symbol s_8_41 [4] = { 'a', 'd', 'a', 's' }
static const symbol s_8_42 [4] = { 'i', 'd', 'a', 's' }
static const symbol s_8_43 [4] = { 'a', 'r', 'a', 's' }
static const symbol s_8_44 [5] = { 'i', 'e', 'r', 'a', 's' }
static const symbol s_8_45 [4] = { 0xC3, 0xAD, 'a', 's' }
static const symbol s_8_46 [6] = { 'a', 'r', 0xC3, 0xAD, 'a', 's' }
static const symbol s_8_47 [6] = { 'e', 'r', 0xC3, 0xAD, 'a', 's' }
static const symbol s_8_48 [6] = { 'i', 'r', 0xC3, 0xAD, 'a', 's' }
static const symbol s_8_49 [2] = { 'e', 's' }
static const symbol s_8_50 [4] = { 'a', 's', 'e', 's' }
static const symbol s_8_51 [5] = { 'i', 'e', 's', 'e', 's' }
static const symbol s_8_52 [5] = { 'a', 'b', 'a', 'i', 's' }
static const symbol s_8_53 [5] = { 'a', 'r', 'a', 'i', 's' }
static const symbol s_8_54 [6] = { 'i', 'e', 'r', 'a', 'i', 's' }
static const symbol s_8_55 [5] = { 0xC3, 0xAD, 'a', 'i', 's' }
static const symbol s_8_56 [7] = { 'a', 'r', 0xC3, 0xAD, 'a', 'i', 's' }
static const symbol s_8_57 [7] = { 'e', 'r', 0xC3, 0xAD, 'a', 'i', 's' }
static const symbol s_8_58 [7] = { 'i', 'r', 0xC3, 0xAD, 'a', 'i', 's' }
static const symbol s_8_59 [5] = { 'a', 's', 'e', 'i', 's' }
static const symbol s_8_60 [6] = { 'i', 'e', 's', 'e', 'i', 's' }
static const symbol s_8_61 [6] = { 'a', 's', 't', 'e', 'i', 's' }
static const symbol s_8_62 [6] = { 'i', 's', 't', 'e', 'i', 's' }
static const symbol s_8_63 [4] = { 0xC3, 0xA1, 'i', 's' }
static const symbol s_8_64 [4] = { 0xC3, 0xA9, 'i', 's' }
static const symbol s_8_65 [6] = { 'a', 'r', 0xC3, 0xA9, 'i', 's' }
static const symbol s_8_66 [6] = { 'e', 'r', 0xC3, 0xA9, 'i', 's' }
static const symbol s_8_67 [6] = { 'i', 'r', 0xC3, 0xA9, 'i', 's' }
static const symbol s_8_68 [4] = { 'a', 'd', 'o', 's' }
static const symbol s_8_69 [4] = { 'i', 'd', 'o', 's' }
static const symbol s_8_70 [4] = { 'a', 'm', 'o', 's' }
static const symbol s_8_71 [7] = { 0xC3, 0xA1, 'b', 'a', 'm', 'o', 's' }
static const symbol s_8_72 [7] = { 0xC3, 0xA1, 'r', 'a', 'm', 'o', 's' }
static const symbol s_8_73 [8] = { 'i', 0xC3, 0xA9, 'r', 'a', 'm', 'o', 's' }
static const symbol s_8_74 [6] = { 0xC3, 0xAD, 'a', 'm', 'o', 's' }
static const symbol s_8_75 [8] = { 'a', 'r', 0xC3, 0xAD, 'a', 'm', 'o', 's' }
static const symbol s_8_76 [8] = { 'e', 'r', 0xC3, 0xAD, 'a', 'm', 'o', 's' }
static const symbol s_8_77 [8] = { 'i', 'r', 0xC3, 0xAD, 'a', 'm', 'o', 's' }
static const symbol s_8_78 [4] = { 'e', 'm', 'o', 's' }
static const symbol s_8_79 [6] = { 'a', 'r', 'e', 'm', 'o', 's' }
static const symbol s_8_80 [6] = { 'e', 'r', 'e', 'm', 'o', 's' }
static const symbol s_8_81 [6] = { 'i', 'r', 'e', 'm', 'o', 's' }
static const symbol s_8_82 [7] = { 0xC3, 0xA1, 's', 'e', 'm', 'o', 's' }
static const symbol s_8_83 [8] = { 'i', 0xC3, 0xA9, 's', 'e', 'm', 'o', 's' }
static const symbol s_8_84 [4] = { 'i', 'm', 'o', 's' }
static const symbol s_8_85 [5] = { 'a', 'r', 0xC3, 0xA1, 's' }
static const symbol s_8_86 [5] = { 'e', 'r', 0xC3, 0xA1, 's' }
static const symbol s_8_87 [5] = { 'i', 'r', 0xC3, 0xA1, 's' }
static const symbol s_8_88 [3] = { 0xC3, 0xAD, 's' }
static const symbol s_8_89 [4] = { 'a', 'r', 0xC3, 0xA1 }
static const symbol s_8_90 [4] = { 'e', 'r', 0xC3, 0xA1 }
static const symbol s_8_91 [4] = { 'i', 'r', 0xC3, 0xA1 }
static const symbol s_8_92 [4] = { 'a', 'r', 0xC3, 0xA9 }
static const symbol s_8_93 [4] = { 'e', 'r', 0xC3, 0xA9 }
static const symbol s_8_94 [4] = { 'i', 'r', 0xC3, 0xA9 }
static const symbol s_8_95 [3] = { 'i', 0xC3, 0xB3 }
static struct among a_8 [96]
static const symbol s_9_0 [1] = { 'a' }
static const symbol s_9_1 [1] = { 'e' }
static const symbol s_9_2 [1] = { 'o' }
static const symbol s_9_3 [2] = { 'o', 's' }
static const symbol s_9_4 [2] = { 0xC3, 0xA1 }
static const symbol s_9_5 [2] = { 0xC3, 0xA9 }
static const symbol s_9_6 [2] = { 0xC3, 0xAD }
static const symbol s_9_7 [2] = { 0xC3, 0xB3 }
static struct among a_9 [8]
static const unsigned char g_v [] = { 17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 17, 4, 10 }
static const symbol s_0 [] = { 'a' }
static const symbol s_1 [] = { 'e' }
static const symbol s_2 [] = { 'i' }
static const symbol s_3 [] = { 'o' }
static const symbol s_4 [] = { 'u' }
static const symbol s_5 [] = { 'i', 'e', 'n', 'd', 'o' }
static const symbol s_6 [] = { 'a', 'n', 'd', 'o' }
static const symbol s_7 [] = { 'a', 'r' }
static const symbol s_8 [] = { 'e', 'r' }
static const symbol s_9 [] = { 'i', 'r' }
static const symbol s_10 [] = { 'u' }
static const symbol s_11 [] = { 'i', 'c' }
static const symbol s_12 [] = { 'l', 'o', 'g' }
static const symbol s_13 [] = { 'u' }
static const symbol s_14 [] = { 'e', 'n', 't', 'e' }
static const symbol s_15 [] = { 'a', 't' }
static const symbol s_16 [] = { 'a', 't' }
static const symbol s_17 [] = { 'u' }
static const symbol s_18 [] = { 'u' }
static const symbol s_19 [] = { 'g' }
static const symbol s_20 [] = { 'u' }
static const symbol s_21 [] = { 'g' }
Function Documentation
static int r_attached_pronoun (struct SN_env * z) [static]
Definition at line 662 of file stem_UTF_8_spanish.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), SN_env::ket, SN_env::lb, SN_env::p, r_RV(), s_10, s_5, s_6, s_7, s_8, s_9, slice_del(), and slice_from_s().
static int r_mark_regions (struct SN_env * z) [static]
Definition at line 514 of file stem_UTF_8_spanish.cpp.
References SN_env::c, g_v, SN_env::I, in_grouping_U(), SN_env::l, out_grouping_U(), SN_env::p, and skip_utf8().
static int r_postlude (struct SN_env * z) [static]
Definition at line 596 of file stem_UTF_8_spanish.cpp.
References SN_env::bra, SN_env::c, find_among(), SN_env::ket, SN_env::l, SN_env::p, s_0, s_1, s_2, s_3, s_4, skip_utf8(), and slice_from_s().
static int r_R1 (struct SN_env * z) [static]
Definition at line 652 of file stem_UTF_8_spanish.cpp.
References SN_env::c, and SN_env::I.
static int r_R2 (struct SN_env * z) [static]
Definition at line 657 of file stem_UTF_8_spanish.cpp.
References SN_env::c, and SN_env::I.
static int r_residual_suffix (struct SN_env * z) [static]
Definition at line 983 of file stem_UTF_8_spanish.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), SN_env::ket, SN_env::l, r_RV(), s_20, s_21, and slice_del().
static int r_RV (struct SN_env * z) [static]
Definition at line 647 of file stem_UTF_8_spanish.cpp.
References SN_env::c, and SN_env::I.
static int r_standard_suffix (struct SN_env * z) [static]
Definition at line 722 of file stem_UTF_8_spanish.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), SN_env::ket, SN_env::l, SN_env::lb, SN_env::p, r_R1(), r_R2(), s_11, s_12, s_13, s_14, s_15, s_16, slice_del(), and slice_from_s().
static int r_verb_suffix (struct SN_env * z) [static]
Definition at line 943 of file stem_UTF_8_spanish.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), SN_env::I, SN_env::ket, SN_env::l, SN_env::lb, s_18, s_19, and slice_del().
static int r_y_verb_suffix (struct SN_env * z) [static]
Definition at line 917 of file stem_UTF_8_spanish.cpp.
References SN_env::bra, SN_env::c, eq_s_b(), find_among_b(), SN_env::I, SN_env::ket, SN_env::l, SN_env::lb, s_17, and slice_del().
Referenced by spanish_UTF_8_stem().
void spanish_UTF_8_close_env (struct SN_env * z)
struct SN_env* spanish_UTF_8_create_env (void) [read]
int spanish_UTF_8_stem (struct SN_env * z)
Variable Documentation
struct among a_0[6] [static]
Initial value:
{
 { 0, 0, -1, 6, 0},
 { 2, s_0_1, 0, 1, 0},
 { 2, s_0_2, 0, 2, 0},
 { 2, s_0_3, 0, 3, 0},
 { 2, s_0_4, 0, 4, 0},
 { 2, s_0_5, 0, 5, 0}
}
Definition at line 42 of file stem_UTF_8_spanish.cpp.
struct among a_1[13] [static]
Initial value:
{
 { 2, s_1_0, -1, -1, 0},
 { 4, s_1_1, 0, -1, 0},
 { 2, s_1_2, -1, -1, 0},
 { 2, s_1_3, -1, -1, 0},
 { 2, s_1_4, -1, -1, 0},
 { 2, s_1_5, -1, -1, 0},
 { 4, s_1_6, 5, -1, 0},
 { 3, s_1_7, -1, -1, 0},
 { 5, s_1_8, 7, -1, 0},
 { 3, s_1_9, -1, -1, 0},
 { 3, s_1_10, -1, -1, 0},
 { 5, s_1_11, 10, -1, 0},
 { 3, s_1_12, -1, -1, 0}
}
Definition at line 66 of file stem_UTF_8_spanish.cpp.
struct among a_2[11] [static]
Initial value:
{
 { 4, s_2_0, -1, 6, 0},
 { 5, s_2_1, -1, 6, 0},
 { 5, s_2_2, -1, 7, 0},
 { 5, s_2_3, -1, 2, 0},
 { 6, s_2_4, -1, 1, 0},
 { 2, s_2_5, -1, 6, 0},
 { 2, s_2_6, -1, 6, 0},
 { 2, s_2_7, -1, 6, 0},
 { 3, s_2_8, -1, 3, 0},
 { 3, s_2_9, -1, 4, 0},
 { 3, s_2_10, -1, 5, 0}
}
Definition at line 95 of file stem_UTF_8_spanish.cpp.
struct among a_3[4] [static]
Initial value:
{
 { 2, s_3_0, -1, -1, 0},
 { 2, s_3_1, -1, -1, 0},
 { 2, s_3_2, -1, -1, 0},
 { 2, s_3_3, -1, 1, 0}
}
Definition at line 115 of file stem_UTF_8_spanish.cpp.
struct among a_4[3] [static]
Initial value:
{
 { 4, s_4_0, -1, 1, 0},
 { 4, s_4_1, -1, 1, 0},
 { 4, s_4_2, -1, 1, 0}
}
Definition at line 127 of file stem_UTF_8_spanish.cpp.
struct among a_5[3] [static]
Initial value:
{
 { 2, s_5_0, -1, 1, 0},
 { 4, s_5_1, -1, 1, 0},
 { 2, s_5_2, -1, 1, 0}
}
Definition at line 138 of file stem_UTF_8_spanish.cpp.
struct among a_6[46] [static]
Definition at line 192 of file stem_UTF_8_spanish.cpp.
struct among a_7[12] [static]
Initial value:
{
 { 2, s_7_0, -1, 1, 0},
 { 2, s_7_1, -1, 1, 0},
 { 3, s_7_2, -1, 1, 0},
 { 3, s_7_3, -1, 1, 0},
 { 5, s_7_4, -1, 1, 0},
 { 5, s_7_5, -1, 1, 0},
 { 2, s_7_6, -1, 1, 0},
 { 3, s_7_7, -1, 1, 0},
 { 3, s_7_8, -1, 1, 0},
 { 4, s_7_9, -1, 1, 0},
 { 5, s_7_10, -1, 1, 0},
 { 3, s_7_11, -1, 1, 0}
}
Definition at line 255 of file stem_UTF_8_spanish.cpp.
struct among a_8[96] [static]
Definition at line 368 of file stem_UTF_8_spanish.cpp.
struct among a_9[8] [static]
Initial value:
{
 { 1, s_9_0, -1, 1, 0},
 { 1, s_9_1, -1, 2, 0},
 { 1, s_9_2, -1, 1, 0},
 { 2, s_9_3, -1, 1, 0},
 { 2, s_9_4, -1, 1, 0},
 { 2, s_9_5, -1, 2, 0},
 { 2, s_9_6, -1, 1, 0},
 { 2, s_9_7, -1, 1, 0}
}
Definition at line 477 of file stem_UTF_8_spanish.cpp.
const unsigned char g_v[] = { 17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 17, 4, 10 } [static]
Definition at line 489 of file stem_UTF_8_spanish.cpp.
const symbol s_0[] = { 'a' } [static]
Definition at line 491 of file stem_UTF_8_spanish.cpp.
const symbol s_0_1[2] = { 0xC3, 0xA1 } [static]
Definition at line 36 of file stem_UTF_8_spanish.cpp.
const symbol s_0_2[2] = { 0xC3, 0xA9 } [static]
Definition at line 37 of file stem_UTF_8_spanish.cpp.
const symbol s_0_3[2] = { 0xC3, 0xAD } [static]
Definition at line 38 of file stem_UTF_8_spanish.cpp.
const symbol s_0_4[2] = { 0xC3, 0xB3 } [static]
Definition at line 39 of file stem_UTF_8_spanish.cpp.
const symbol s_0_5[2] = { 0xC3, 0xBA } [static]
Definition at line 40 of file stem_UTF_8_spanish.cpp.
const symbol s_1[] = { 'e' } [static]
Definition at line 492 of file stem_UTF_8_spanish.cpp.
const symbol s_10[] = { 'u' } [static]
Definition at line 501 of file stem_UTF_8_spanish.cpp.
const symbol s_11[] = { 'i', 'c' } [static]
Definition at line 502 of file stem_UTF_8_spanish.cpp.
const symbol s_12[] = { 'l', 'o', 'g' } [static]
Definition at line 503 of file stem_UTF_8_spanish.cpp.
const symbol s_13[] = { 'u' } [static]
Definition at line 504 of file stem_UTF_8_spanish.cpp.
const symbol s_14[] = { 'e', 'n', 't', 'e' } [static]
Definition at line 505 of file stem_UTF_8_spanish.cpp.
const symbol s_15[] = { 'a', 't' } [static]
Definition at line 506 of file stem_UTF_8_spanish.cpp.
const symbol s_16[] = { 'a', 't' } [static]
Definition at line 507 of file stem_UTF_8_spanish.cpp.
const symbol s_17[] = { 'u' } [static]
Definition at line 508 of file stem_UTF_8_spanish.cpp.
const symbol s_18[] = { 'u' } [static]
Definition at line 509 of file stem_UTF_8_spanish.cpp.
const symbol s_19[] = { 'g' } [static]
Definition at line 510 of file stem_UTF_8_spanish.cpp.
const symbol s_1_0[2] = { 'l', 'a' } [static]
Definition at line 52 of file stem_UTF_8_spanish.cpp.
const symbol s_1_1[4] = { 's', 'e', 'l', 'a' } [static]
Definition at line 53 of file stem_UTF_8_spanish.cpp.
const symbol s_1_10[3] = { 'l', 'o', 's' } [static]
Definition at line 62 of file stem_UTF_8_spanish.cpp.
const symbol s_1_11[5] = { 's', 'e', 'l', 'o', 's' } [static]
Definition at line 63 of file stem_UTF_8_spanish.cpp.
const symbol s_1_12[3] = { 'n', 'o', 's' } [static]
Definition at line 64 of file stem_UTF_8_spanish.cpp.
const symbol s_1_2[2] = { 'l', 'e' } [static]
Definition at line 54 of file stem_UTF_8_spanish.cpp.
const symbol s_1_3[2] = { 'm', 'e' } [static]
Definition at line 55 of file stem_UTF_8_spanish.cpp.
const symbol s_1_4[2] = { 's', 'e' } [static]
Definition at line 56 of file stem_UTF_8_spanish.cpp.
const symbol s_1_5[2] = { 'l', 'o' } [static]
Definition at line 57 of file stem_UTF_8_spanish.cpp.
const symbol s_1_6[4] = { 's', 'e', 'l', 'o' } [static]
Definition at line 58 of file stem_UTF_8_spanish.cpp.
const symbol s_1_7[3] = { 'l', 'a', 's' } [static]
Definition at line 59 of file stem_UTF_8_spanish.cpp.
const symbol s_1_8[5] = { 's', 'e', 'l', 'a', 's' } [static]
Definition at line 60 of file stem_UTF_8_spanish.cpp.
const symbol s_1_9[3] = { 'l', 'e', 's' } [static]
Definition at line 61 of file stem_UTF_8_spanish.cpp.
const symbol s_2[] = { 'i' } [static]
Definition at line 493 of file stem_UTF_8_spanish.cpp.
const symbol s_20[] = { 'u' } [static]
Definition at line 511 of file stem_UTF_8_spanish.cpp.
const symbol s_21[] = { 'g' } [static]
Definition at line 512 of file stem_UTF_8_spanish.cpp.
const symbol s_2_0[4] = { 'a', 'n', 'd', 'o' } [static]
Definition at line 83 of file stem_UTF_8_spanish.cpp.
const symbol s_2_1[5] = { 'i', 'e', 'n', 'd', 'o' } [static]
Definition at line 84 of file stem_UTF_8_spanish.cpp.
const symbol s_2_10[3] = { 0xC3, 0xAD, 'r' } [static]
Definition at line 93 of file stem_UTF_8_spanish.cpp.
const symbol s_2_2[5] = { 'y', 'e', 'n', 'd', 'o' } [static]
Definition at line 85 of file stem_UTF_8_spanish.cpp.
const symbol s_2_3[5] = { 0xC3, 0xA1, 'n', 'd', 'o' } [static]
Definition at line 86 of file stem_UTF_8_spanish.cpp.
const symbol s_2_4[6] = { 'i', 0xC3, 0xA9, 'n', 'd', 'o' } [static]
Definition at line 87 of file stem_UTF_8_spanish.cpp.
const symbol s_2_5[2] = { 'a', 'r' } [static]
Definition at line 88 of file stem_UTF_8_spanish.cpp.
const symbol s_2_6[2] = { 'e', 'r' } [static]
Definition at line 89 of file stem_UTF_8_spanish.cpp.
const symbol s_2_7[2] = { 'i', 'r' } [static]
Definition at line 90 of file stem_UTF_8_spanish.cpp.
const symbol s_2_8[3] = { 0xC3, 0xA1, 'r' } [static]
Definition at line 91 of file stem_UTF_8_spanish.cpp.
const symbol s_2_9[3] = { 0xC3, 0xA9, 'r' } [static]
Definition at line 92 of file stem_UTF_8_spanish.cpp.
const symbol s_3[] = { 'o' } [static]
Definition at line 494 of file stem_UTF_8_spanish.cpp.
const symbol s_3_0[2] = { 'i', 'c' } [static]
Definition at line 110 of file stem_UTF_8_spanish.cpp.
const symbol s_3_1[2] = { 'a', 'd' } [static]
Definition at line 111 of file stem_UTF_8_spanish.cpp.
const symbol s_3_2[2] = { 'o', 's' } [static]
Definition at line 112 of file stem_UTF_8_spanish.cpp.
const symbol s_3_3[2] = { 'i', 'v' } [static]
Definition at line 113 of file stem_UTF_8_spanish.cpp.
const symbol s_4[] = { 'u' } [static]
Definition at line 495 of file stem_UTF_8_spanish.cpp.
const symbol s_4_0[4] = { 'a', 'b', 'l', 'e' } [static]
Definition at line 123 of file stem_UTF_8_spanish.cpp.
const symbol s_4_1[4] = { 'i', 'b', 'l', 'e' } [static]
Definition at line 124 of file stem_UTF_8_spanish.cpp.
const symbol s_4_2[4] = { 'a', 'n', 't', 'e' } [static]
Definition at line 125 of file stem_UTF_8_spanish.cpp.
const symbol s_5[] = { 'i', 'e', 'n', 'd', 'o' } [static]
Definition at line 496 of file stem_UTF_8_spanish.cpp.
const symbol s_5_0[2] = { 'i', 'c' } [static]
Definition at line 134 of file stem_UTF_8_spanish.cpp.
const symbol s_5_1[4] = { 'a', 'b', 'i', 'l' } [static]
Definition at line 135 of file stem_UTF_8_spanish.cpp.
const symbol s_5_2[2] = { 'i', 'v' } [static]
Definition at line 136 of file stem_UTF_8_spanish.cpp.
const symbol s_6[] = { 'a', 'n', 'd', 'o' } [static]
Definition at line 497 of file stem_UTF_8_spanish.cpp.
const symbol s_6_0[3] = { 'i', 'c', 'a' } [static]
Definition at line 145 of file stem_UTF_8_spanish.cpp.
const symbol s_6_1[5] = { 'a', 'n', 'c', 'i', 'a' } [static]
Definition at line 146 of file stem_UTF_8_spanish.cpp.
const symbol s_6_10[4] = { 'a', 'b', 'l', 'e' } [static]
Definition at line 155 of file stem_UTF_8_spanish.cpp.
const symbol s_6_11[4] = { 'i', 'b', 'l', 'e' } [static]
Definition at line 156 of file stem_UTF_8_spanish.cpp.
const symbol s_6_12[4] = { 'a', 'n', 't', 'e' } [static]
Definition at line 157 of file stem_UTF_8_spanish.cpp.
const symbol s_6_13[5] = { 'm', 'e', 'n', 't', 'e' } [static]
Definition at line 158 of file stem_UTF_8_spanish.cpp.
const symbol s_6_14[6] = { 'a', 'm', 'e', 'n', 't', 'e' } [static]
Definition at line 159 of file stem_UTF_8_spanish.cpp.
const symbol s_6_15[6] = { 'a', 'c', 'i', 0xC3, 0xB3, 'n' } [static]
Definition at line 160 of file stem_UTF_8_spanish.cpp.
const symbol s_6_16[6] = { 'u', 'c', 'i', 0xC3, 0xB3, 'n' } [static]
Definition at line 161 of file stem_UTF_8_spanish.cpp.
const symbol s_6_17[3] = { 'i', 'c', 'o' } [static]
Definition at line 162 of file stem_UTF_8_spanish.cpp.
const symbol s_6_18[4] = { 'i', 's', 'm', 'o' } [static]
Definition at line 163 of file stem_UTF_8_spanish.cpp.
const symbol s_6_19[3] = { 'o', 's', 'o' } [static]
Definition at line 164 of file stem_UTF_8_spanish.cpp.
const symbol s_6_2[5] = { 'e', 'n', 'c', 'i', 'a' } [static]
Definition at line 147 of file stem_UTF_8_spanish.cpp.
const symbol s_6_20[7] = { 'a', 'm', 'i', 'e', 'n', 't', 'o' } [static]
Definition at line 165 of file stem_UTF_8_spanish.cpp.
const symbol s_6_21[7] = { 'i', 'm', 'i', 'e', 'n', 't', 'o' } [static]
Definition at line 166 of file stem_UTF_8_spanish.cpp.
const symbol s_6_22[3] = { 'i', 'v', 'o' } [static]
Definition at line 167 of file stem_UTF_8_spanish.cpp.
const symbol s_6_23[4] = { 'a', 'd', 'o', 'r' } [static]
Definition at line 168 of file stem_UTF_8_spanish.cpp.
const symbol s_6_24[4] = { 'i', 'c', 'a', 's' } [static]
Definition at line 169 of file stem_UTF_8_spanish.cpp.
const symbol s_6_25[6] = { 'a', 'n', 'c', 'i', 'a', 's' } [static]
Definition at line 170 of file stem_UTF_8_spanish.cpp.
const symbol s_6_26[6] = { 'e', 'n', 'c', 'i', 'a', 's' } [static]
Definition at line 171 of file stem_UTF_8_spanish.cpp.
const symbol s_6_27[6] = { 'a', 'd', 'o', 'r', 'a', 's' } [static]
Definition at line 172 of file stem_UTF_8_spanish.cpp.
const symbol s_6_28[4] = { 'o', 's', 'a', 's' } [static]
Definition at line 173 of file stem_UTF_8_spanish.cpp.
const symbol s_6_29[5] = { 'i', 's', 't', 'a', 's' } [static]
Definition at line 174 of file stem_UTF_8_spanish.cpp.
const symbol s_6_3[5] = { 'a', 'd', 'o', 'r', 'a' } [static]
Definition at line 148 of file stem_UTF_8_spanish.cpp.
const symbol s_6_30[4] = { 'i', 'v', 'a', 's' } [static]
Definition at line 175 of file stem_UTF_8_spanish.cpp.
const symbol s_6_31[5] = { 'a', 'n', 'z', 'a', 's' } [static]
Definition at line 176 of file stem_UTF_8_spanish.cpp.
const symbol s_6_32[7] = { 'l', 'o', 'g', 0xC3, 0xAD, 'a', 's' } [static]
Definition at line 177 of file stem_UTF_8_spanish.cpp.
const symbol s_6_33[6] = { 'i', 'd', 'a', 'd', 'e', 's' } [static]
Definition at line 178 of file stem_UTF_8_spanish.cpp.
const symbol s_6_34[5] = { 'a', 'b', 'l', 'e', 's' } [static]
Definition at line 179 of file stem_UTF_8_spanish.cpp.
const symbol s_6_35[5] = { 'i', 'b', 'l', 'e', 's' } [static]
Definition at line 180 of file stem_UTF_8_spanish.cpp.
const symbol s_6_36[7] = { 'a', 'c', 'i', 'o', 'n', 'e', 's' } [static]
Definition at line 181 of file stem_UTF_8_spanish.cpp.
const symbol s_6_37[7] = { 'u', 'c', 'i', 'o', 'n', 'e', 's' } [static]
Definition at line 182 of file stem_UTF_8_spanish.cpp.
const symbol s_6_38[6] = { 'a', 'd', 'o', 'r', 'e', 's' } [static]
Definition at line 183 of file stem_UTF_8_spanish.cpp.
const symbol s_6_39[5] = { 'a', 'n', 't', 'e', 's' } [static]
Definition at line 184 of file stem_UTF_8_spanish.cpp.
const symbol s_6_4[3] = { 'o', 's', 'a' } [static]
Definition at line 149 of file stem_UTF_8_spanish.cpp.
const symbol s_6_40[4] = { 'i', 'c', 'o', 's' } [static]
Definition at line 185 of file stem_UTF_8_spanish.cpp.
const symbol s_6_41[5] = { 'i', 's', 'm', 'o', 's' } [static]
Definition at line 186 of file stem_UTF_8_spanish.cpp.
const symbol s_6_42[4] = { 'o', 's', 'o', 's' } [static]
Definition at line 187 of file stem_UTF_8_spanish.cpp.
const symbol s_6_43[8] = { 'a', 'm', 'i', 'e', 'n', 't', 'o', 's' } [static]
Definition at line 188 of file stem_UTF_8_spanish.cpp.
const symbol s_6_44[8] = { 'i', 'm', 'i', 'e', 'n', 't', 'o', 's' } [static]
Definition at line 189 of file stem_UTF_8_spanish.cpp.
const symbol s_6_45[4] = { 'i', 'v', 'o', 's' } [static]
Definition at line 190 of file stem_UTF_8_spanish.cpp.
const symbol s_6_5[4] = { 'i', 's', 't', 'a' } [static]
Definition at line 150 of file stem_UTF_8_spanish.cpp.
const symbol s_6_6[3] = { 'i', 'v', 'a' } [static]
Definition at line 151 of file stem_UTF_8_spanish.cpp.
const symbol s_6_7[4] = { 'a', 'n', 'z', 'a' } [static]
Definition at line 152 of file stem_UTF_8_spanish.cpp.
const symbol s_6_8[6] = { 'l', 'o', 'g', 0xC3, 0xAD, 'a' } [static]
Definition at line 153 of file stem_UTF_8_spanish.cpp.
const symbol s_6_9[4] = { 'i', 'd', 'a', 'd' } [static]
Definition at line 154 of file stem_UTF_8_spanish.cpp.
const symbol s_7[] = { 'a', 'r' } [static]
Definition at line 498 of file stem_UTF_8_spanish.cpp.
const symbol s_7_0[2] = { 'y', 'a' } [static]
Definition at line 242 of file stem_UTF_8_spanish.cpp.
const symbol s_7_1[2] = { 'y', 'e' } [static]
Definition at line 243 of file stem_UTF_8_spanish.cpp.
const symbol s_7_10[5] = { 'y', 'a', 'm', 'o', 's' } [static]
Definition at line 252 of file stem_UTF_8_spanish.cpp.
const symbol s_7_11[3] = { 'y', 0xC3, 0xB3 } [static]
Definition at line 253 of file stem_UTF_8_spanish.cpp.
const symbol s_7_2[3] = { 'y', 'a', 'n' } [static]
Definition at line 244 of file stem_UTF_8_spanish.cpp.
const symbol s_7_3[3] = { 'y', 'e', 'n' } [static]
Definition at line 245 of file stem_UTF_8_spanish.cpp.
const symbol s_7_4[5] = { 'y', 'e', 'r', 'o', 'n' } [static]
Definition at line 246 of file stem_UTF_8_spanish.cpp.
const symbol s_7_5[5] = { 'y', 'e', 'n', 'd', 'o' } [static]
Definition at line 247 of file stem_UTF_8_spanish.cpp.
const symbol s_7_6[2] = { 'y', 'o' } [static]
Definition at line 248 of file stem_UTF_8_spanish.cpp.
const symbol s_7_7[3] = { 'y', 'a', 's' } [static]
Definition at line 249 of file stem_UTF_8_spanish.cpp.
const symbol s_7_8[3] = { 'y', 'e', 's' } [static]
Definition at line 250 of file stem_UTF_8_spanish.cpp.
const symbol s_7_9[4] = { 'y', 'a', 'i', 's' } [static]
Definition at line 251 of file stem_UTF_8_spanish.cpp.
const symbol s_8[] = { 'e', 'r' } [static]
Definition at line 499 of file stem_UTF_8_spanish.cpp.
const symbol s_8_0[3] = { 'a', 'b', 'a' } [static]
Definition at line 271 of file stem_UTF_8_spanish.cpp.
const symbol s_8_1[3] = { 'a', 'd', 'a' } [static]
Definition at line 272 of file stem_UTF_8_spanish.cpp.
const symbol s_8_10[2] = { 'e', 'd' } [static]
Definition at line 281 of file stem_UTF_8_spanish.cpp.
const symbol s_8_11[2] = { 'i', 'd' } [static]
Definition at line 282 of file stem_UTF_8_spanish.cpp.
const symbol s_8_12[3] = { 'a', 's', 'e' } [static]
Definition at line 283 of file stem_UTF_8_spanish.cpp.
const symbol s_8_13[4] = { 'i', 'e', 's', 'e' } [static]
Definition at line 284 of file stem_UTF_8_spanish.cpp.
const symbol s_8_14[4] = { 'a', 's', 't', 'e' } [static]
Definition at line 285 of file stem_UTF_8_spanish.cpp.
const symbol s_8_15[4] = { 'i', 's', 't', 'e' } [static]
Definition at line 286 of file stem_UTF_8_spanish.cpp.
const symbol s_8_16[2] = { 'a', 'n' } [static]
Definition at line 287 of file stem_UTF_8_spanish.cpp.
const symbol s_8_17[4] = { 'a', 'b', 'a', 'n' } [static]
Definition at line 288 of file stem_UTF_8_spanish.cpp.
const symbol s_8_18[4] = { 'a', 'r', 'a', 'n' } [static]
Definition at line 289 of file stem_UTF_8_spanish.cpp.
const symbol s_8_19[5] = { 'i', 'e', 'r', 'a', 'n' } [static]
Definition at line 290 of file stem_UTF_8_spanish.cpp.
const symbol s_8_2[3] = { 'i', 'd', 'a' } [static]
Definition at line 273 of file stem_UTF_8_spanish.cpp.
const symbol s_8_20[4] = { 0xC3, 0xAD, 'a', 'n' } [static]
Definition at line 291 of file stem_UTF_8_spanish.cpp.
const symbol s_8_21[6] = { 'a', 'r', 0xC3, 0xAD, 'a', 'n' } [static]
Definition at line 292 of file stem_UTF_8_spanish.cpp.
const symbol s_8_22[6] = { 'e', 'r', 0xC3, 0xAD, 'a', 'n' } [static]
Definition at line 293 of file stem_UTF_8_spanish.cpp.
const symbol s_8_23[6] = { 'i', 'r', 0xC3, 0xAD, 'a', 'n' } [static]
Definition at line 294 of file stem_UTF_8_spanish.cpp.
const symbol s_8_24[2] = { 'e', 'n' } [static]
Definition at line 295 of file stem_UTF_8_spanish.cpp.
const symbol s_8_25[4] = { 'a', 's', 'e', 'n' } [static]
Definition at line 296 of file stem_UTF_8_spanish.cpp.
const symbol s_8_26[5] = { 'i', 'e', 's', 'e', 'n' } [static]
Definition at line 297 of file stem_UTF_8_spanish.cpp.
const symbol s_8_27[4] = { 'a', 'r', 'o', 'n' } [static]
Definition at line 298 of file stem_UTF_8_spanish.cpp.
const symbol s_8_28[5] = { 'i', 'e', 'r', 'o', 'n' } [static]
Definition at line 299 of file stem_UTF_8_spanish.cpp.
const symbol s_8_29[5] = { 'a', 'r', 0xC3, 0xA1, 'n' } [static]
Definition at line 300 of file stem_UTF_8_spanish.cpp.
const symbol s_8_3[3] = { 'a', 'r', 'a' } [static]
Definition at line 274 of file stem_UTF_8_spanish.cpp.
const symbol s_8_30[5] = { 'e', 'r', 0xC3, 0xA1, 'n' } [static]
Definition at line 301 of file stem_UTF_8_spanish.cpp.
const symbol s_8_31[5] = { 'i', 'r', 0xC3, 0xA1, 'n' } [static]
Definition at line 302 of file stem_UTF_8_spanish.cpp.
const symbol s_8_32[3] = { 'a', 'd', 'o' } [static]
Definition at line 303 of file stem_UTF_8_spanish.cpp.
const symbol s_8_33[3] = { 'i', 'd', 'o' } [static]
Definition at line 304 of file stem_UTF_8_spanish.cpp.
const symbol s_8_34[4] = { 'a', 'n', 'd', 'o' } [static]
Definition at line 305 of file stem_UTF_8_spanish.cpp.
const symbol s_8_35[5] = { 'i', 'e', 'n', 'd', 'o' } [static]
Definition at line 306 of file stem_UTF_8_spanish.cpp.
const symbol s_8_36[2] = { 'a', 'r' } [static]
Definition at line 307 of file stem_UTF_8_spanish.cpp.
const symbol s_8_37[2] = { 'e', 'r' } [static]
Definition at line 308 of file stem_UTF_8_spanish.cpp.
const symbol s_8_38[2] = { 'i', 'r' } [static]
Definition at line 309 of file stem_UTF_8_spanish.cpp.
const symbol s_8_39[2] = { 'a', 's' } [static]
Definition at line 310 of file stem_UTF_8_spanish.cpp.
const symbol s_8_4[4] = { 'i', 'e', 'r', 'a' } [static]
Definition at line 275 of file stem_UTF_8_spanish.cpp.
const symbol s_8_40[4] = { 'a', 'b', 'a', 's' } [static]
Definition at line 311 of file stem_UTF_8_spanish.cpp.
const symbol s_8_41[4] = { 'a', 'd', 'a', 's' } [static]
Definition at line 312 of file stem_UTF_8_spanish.cpp.
const symbol s_8_42[4] = { 'i', 'd', 'a', 's' } [static]
Definition at line 313 of file stem_UTF_8_spanish.cpp.
const symbol s_8_43[4] = { 'a', 'r', 'a', 's' } [static]
Definition at line 314 of file stem_UTF_8_spanish.cpp.
const symbol s_8_44[5] = { 'i', 'e', 'r', 'a', 's' } [static]
Definition at line 315 of file stem_UTF_8_spanish.cpp.
const symbol s_8_45[4] = { 0xC3, 0xAD, 'a', 's' } [static]
Definition at line 316 of file stem_UTF_8_spanish.cpp.
const symbol s_8_46[6] = { 'a', 'r', 0xC3, 0xAD, 'a', 's' } [static]
Definition at line 317 of file stem_UTF_8_spanish.cpp.
const symbol s_8_47[6] = { 'e', 'r', 0xC3, 0xAD, 'a', 's' } [static]
Definition at line 318 of file stem_UTF_8_spanish.cpp.
const symbol s_8_48[6] = { 'i', 'r', 0xC3, 0xAD, 'a', 's' } [static]
Definition at line 319 of file stem_UTF_8_spanish.cpp.
const symbol s_8_49[2] = { 'e', 's' } [static]
Definition at line 320 of file stem_UTF_8_spanish.cpp.
const symbol s_8_5[3] = { 0xC3, 0xAD, 'a' } [static]
Definition at line 276 of file stem_UTF_8_spanish.cpp.
const symbol s_8_50[4] = { 'a', 's', 'e', 's' } [static]
Definition at line 321 of file stem_UTF_8_spanish.cpp.
const symbol s_8_51[5] = { 'i', 'e', 's', 'e', 's' } [static]
Definition at line 322 of file stem_UTF_8_spanish.cpp.
const symbol s_8_52[5] = { 'a', 'b', 'a', 'i', 's' } [static]
Definition at line 323 of file stem_UTF_8_spanish.cpp.
const symbol s_8_53[5] = { 'a', 'r', 'a', 'i', 's' } [static]
Definition at line 324 of file stem_UTF_8_spanish.cpp.
const symbol s_8_54[6] = { 'i', 'e', 'r', 'a', 'i', 's' } [static]
Definition at line 325 of file stem_UTF_8_spanish.cpp.
const symbol s_8_55[5] = { 0xC3, 0xAD, 'a', 'i', 's' } [static]
Definition at line 326 of file stem_UTF_8_spanish.cpp.
const symbol s_8_56[7] = { 'a', 'r', 0xC3, 0xAD, 'a', 'i', 's' } [static]
Definition at line 327 of file stem_UTF_8_spanish.cpp.
const symbol s_8_57[7] = { 'e', 'r', 0xC3, 0xAD, 'a', 'i', 's' } [static]
Definition at line 328 of file stem_UTF_8_spanish.cpp.
const symbol s_8_58[7] = { 'i', 'r', 0xC3, 0xAD, 'a', 'i', 's' } [static]
Definition at line 329 of file stem_UTF_8_spanish.cpp.
const symbol s_8_59[5] = { 'a', 's', 'e', 'i', 's' } [static]
Definition at line 330 of file stem_UTF_8_spanish.cpp.
const symbol s_8_6[5] = { 'a', 'r', 0xC3, 0xAD, 'a' } [static]
Definition at line 277 of file stem_UTF_8_spanish.cpp.
const symbol s_8_60[6] = { 'i', 'e', 's', 'e', 'i', 's' } [static]
Definition at line 331 of file stem_UTF_8_spanish.cpp.
const symbol s_8_61[6] = { 'a', 's', 't', 'e', 'i', 's' } [static]
Definition at line 332 of file stem_UTF_8_spanish.cpp.
const symbol s_8_62[6] = { 'i', 's', 't', 'e', 'i', 's' } [static]
Definition at line 333 of file stem_UTF_8_spanish.cpp.
const symbol s_8_63[4] = { 0xC3, 0xA1, 'i', 's' } [static]
Definition at line 334 of file stem_UTF_8_spanish.cpp.
const symbol s_8_64[4] = { 0xC3, 0xA9, 'i', 's' } [static]
Definition at line 335 of file stem_UTF_8_spanish.cpp.
const symbol s_8_65[6] = { 'a', 'r', 0xC3, 0xA9, 'i', 's' } [static]
Definition at line 336 of file stem_UTF_8_spanish.cpp.
const symbol s_8_66[6] = { 'e', 'r', 0xC3, 0xA9, 'i', 's' } [static]
Definition at line 337 of file stem_UTF_8_spanish.cpp.
const symbol s_8_67[6] = { 'i', 'r', 0xC3, 0xA9, 'i', 's' } [static]
Definition at line 338 of file stem_UTF_8_spanish.cpp.
const symbol s_8_68[4] = { 'a', 'd', 'o', 's' } [static]
Definition at line 339 of file stem_UTF_8_spanish.cpp.
const symbol s_8_69[4] = { 'i', 'd', 'o', 's' } [static]
Definition at line 340 of file stem_UTF_8_spanish.cpp.
const symbol s_8_7[5] = { 'e', 'r', 0xC3, 0xAD, 'a' } [static]
Definition at line 278 of file stem_UTF_8_spanish.cpp.
const symbol s_8_70[4] = { 'a', 'm', 'o', 's' } [static]
Definition at line 341 of file stem_UTF_8_spanish.cpp.
const symbol s_8_71[7] = { 0xC3, 0xA1, 'b', 'a', 'm', 'o', 's' } [static]
Definition at line 342 of file stem_UTF_8_spanish.cpp.
const symbol s_8_72[7] = { 0xC3, 0xA1, 'r', 'a', 'm', 'o', 's' } [static]
Definition at line 343 of file stem_UTF_8_spanish.cpp.
const symbol s_8_73[8] = { 'i', 0xC3, 0xA9, 'r', 'a', 'm', 'o', 's' } [static]
Definition at line 344 of file stem_UTF_8_spanish.cpp.
const symbol s_8_74[6] = { 0xC3, 0xAD, 'a', 'm', 'o', 's' } [static]
Definition at line 345 of file stem_UTF_8_spanish.cpp.
const symbol s_8_75[8] = { 'a', 'r', 0xC3, 0xAD, 'a', 'm', 'o', 's' } [static]
Definition at line 346 of file stem_UTF_8_spanish.cpp.
const symbol s_8_76[8] = { 'e', 'r', 0xC3, 0xAD, 'a', 'm', 'o', 's' } [static]
Definition at line 347 of file stem_UTF_8_spanish.cpp.
const symbol s_8_77[8] = { 'i', 'r', 0xC3, 0xAD, 'a', 'm', 'o', 's' } [static]
Definition at line 348 of file stem_UTF_8_spanish.cpp.
const symbol s_8_78[4] = { 'e', 'm', 'o', 's' } [static]
Definition at line 349 of file stem_UTF_8_spanish.cpp.
const symbol s_8_79[6] = { 'a', 'r', 'e', 'm', 'o', 's' } [static]
Definition at line 350 of file stem_UTF_8_spanish.cpp.
const symbol s_8_8[5] = { 'i', 'r', 0xC3, 0xAD, 'a' } [static]
Definition at line 279 of file stem_UTF_8_spanish.cpp.
const symbol s_8_80[6] = { 'e', 'r', 'e', 'm', 'o', 's' } [static]
Definition at line 351 of file stem_UTF_8_spanish.cpp.
const symbol s_8_81[6] = { 'i', 'r', 'e', 'm', 'o', 's' } [static]
Definition at line 352 of file stem_UTF_8_spanish.cpp.
const symbol s_8_82[7] = { 0xC3, 0xA1, 's', 'e', 'm', 'o', 's' } [static]
Definition at line 353 of file stem_UTF_8_spanish.cpp.
const symbol s_8_83[8] = { 'i', 0xC3, 0xA9, 's', 'e', 'm', 'o', 's' } [static]
Definition at line 354 of file stem_UTF_8_spanish.cpp.
const symbol s_8_84[4] = { 'i', 'm', 'o', 's' } [static]
Definition at line 355 of file stem_UTF_8_spanish.cpp.
const symbol s_8_85[5] = { 'a', 'r', 0xC3, 0xA1, 's' } [static]
Definition at line 356 of file stem_UTF_8_spanish.cpp.
const symbol s_8_86[5] = { 'e', 'r', 0xC3, 0xA1, 's' } [static]
Definition at line 357 of file stem_UTF_8_spanish.cpp.
const symbol s_8_87[5] = { 'i', 'r', 0xC3, 0xA1, 's' } [static]
Definition at line 358 of file stem_UTF_8_spanish.cpp.
const symbol s_8_88[3] = { 0xC3, 0xAD, 's' } [static]
Definition at line 359 of file stem_UTF_8_spanish.cpp.
const symbol s_8_89[4] = { 'a', 'r', 0xC3, 0xA1 } [static]
Definition at line 360 of file stem_UTF_8_spanish.cpp.
const symbol s_8_9[2] = { 'a', 'd' } [static]
Definition at line 280 of file stem_UTF_8_spanish.cpp.
const symbol s_8_90[4] = { 'e', 'r', 0xC3, 0xA1 } [static]
Definition at line 361 of file stem_UTF_8_spanish.cpp.
const symbol s_8_91[4] = { 'i', 'r', 0xC3, 0xA1 } [static]
Definition at line 362 of file stem_UTF_8_spanish.cpp.
const symbol s_8_92[4] = { 'a', 'r', 0xC3, 0xA9 } [static]
Definition at line 363 of file stem_UTF_8_spanish.cpp.
const symbol s_8_93[4] = { 'e', 'r', 0xC3, 0xA9 } [static]
Definition at line 364 of file stem_UTF_8_spanish.cpp.
const symbol s_8_94[4] = { 'i', 'r', 0xC3, 0xA9 } [static]
Definition at line 365 of file stem_UTF_8_spanish.cpp.
const symbol s_8_95[3] = { 'i', 0xC3, 0xB3 } [static]
Definition at line 366 of file stem_UTF_8_spanish.cpp.
const symbol s_9[] = { 'i', 'r' } [static]
Definition at line 500 of file stem_UTF_8_spanish.cpp.
const symbol s_9_0[1] = { 'a' } [static]
Definition at line 468 of file stem_UTF_8_spanish.cpp.
const symbol s_9_1[1] = { 'e' } [static]
Definition at line 469 of file stem_UTF_8_spanish.cpp.
const symbol s_9_2[1] = { 'o' } [static]
Definition at line 470 of file stem_UTF_8_spanish.cpp.
const symbol s_9_3[2] = { 'o', 's' } [static]
Definition at line 471 of file stem_UTF_8_spanish.cpp.
const symbol s_9_4[2] = { 0xC3, 0xA1 } [static]
Definition at line 472 of file stem_UTF_8_spanish.cpp.
const symbol s_9_5[2] = { 0xC3, 0xA9 } [static]
Definition at line 473 of file stem_UTF_8_spanish.cpp.
const symbol s_9_6[2] = { 0xC3, 0xAD } [static]
Definition at line 474 of file stem_UTF_8_spanish.cpp.
const symbol s_9_7[2] = { 0xC3, 0xB3 } [static]
Definition at line 475 of file stem_UTF_8_spanish.cpp.