/disk/workspace-cpp/la-manager/include/stem/stem_UTF_8_finnish.h File Reference
Functions
struct SN_env * finnish_UTF_8_create_env (void)
void finnish_UTF_8_close_env (struct SN_env *z)
int finnish_UTF_8_stem (struct SN_env *z)
Function Documentation
void finnish_UTF_8_close_env (struct SN_env * z)
Definition at line 770 of file stem_UTF_8_finnish.cpp.
References SN_close_env().
struct SN_env * finnish_UTF_8_create_env (void) [read]
Definition at line 768 of file stem_UTF_8_finnish.cpp.
References SN_create_env().
int finnish_UTF_8_stem (struct SN_env * z)
Definition at line 689 of file stem_UTF_8_finnish.cpp.
References SN_env::B, SN_env::c, SN_env::l, SN_env::lb, r_case_ending(), r_i_plural(), r_mark_regions(), r_other_endings(), r_particle_etc(), r_possessive(), r_t_plural(), and r_tidy().