/disk/workspace-cpp/la-manager/include/stem/stem_UTF_8_norwegian.h File Reference
Functions
struct SN_env * norwegian_UTF_8_create_env (void)
void norwegian_UTF_8_close_env (struct SN_env *z)
int norwegian_UTF_8_stem (struct SN_env *z)
Function Documentation
void norwegian_UTF_8_close_env (struct SN_env * z)
Definition at line 299 of file stem_UTF_8_norwegian.cpp.
References SN_close_env().
struct SN_env * norwegian_UTF_8_create_env (void) [read]
Definition at line 297 of file stem_UTF_8_norwegian.cpp.
References SN_create_env().
int norwegian_UTF_8_stem (struct SN_env * z)
Definition at line 258 of file stem_UTF_8_norwegian.cpp.
References SN_env::c, SN_env::l, SN_env::lb, r_consonant_pair(), r_main_suffix(), r_mark_regions(), and r_other_suffix().