/disk/workspace-cpp/la-manager/source/kma/stringex.cpp File Reference
#include <stringex.h>
Defines
#define DEFAULT_divide_MAX 10
#define GROWINGSIZE 50
Functions
bool operator> (const StringEx &strex1, const StringEx &strex2)
bool operator< (const StringEx &strex1, const StringEx &strex2)
bool operator> (const StringEx &strex1, const char *str)
bool operator< (const StringEx &strex1, const char *str)
bool operator== (const StringEx &strex1, const StringEx &strex2)
bool operator== (const StringEx &strex1, const char *str)
bool operator!= (const StringEx &strex1, const StringEx &strex2)
bool operator!= (const StringEx &strex1, const char *str)
ostream & operator<< (ostream &sout, const StringEx &strex)
StringEx operator+ (const char *str, const StringEx &strex)
ostream & operator<< (ostream &sout, const Text &text)
Text operator+ (char *str, const Text &text1)
Text operator+ (const StringEx &strex1, const Text &text1)
Define Documentation
#define DEFAULT_divide_MAX 10
Definition at line 460 of file stringex.cpp.
Referenced by Text::divideStrings2Ptr(), and Text::divideStringsPtr().
#define GROWINGSIZE 50
Definition at line 688 of file stringex.cpp.
Referenced by Text::getStringsBetweenAnBs().
Function Documentation
bool operator!= (const StringEx & strex1, const char * str)
Definition at line 62 of file stringex.cpp.
bool operator!= (const StringEx & strex1, const StringEx & strex2)
Definition at line 55 of file stringex.cpp.
Text operator+ (const StringEx & strex1, const Text & text1)
Definition at line 289 of file stringex.cpp.
References StringEx::getBuffer().
Text operator+ (char * str, const Text & text1)
Definition at line 280 of file stringex.cpp.
References StringEx::getBuffer().
StringEx operator+ (const char * str, const StringEx & strex)
Definition at line 76 of file stringex.cpp.
bool operator< (const StringEx & strex1, const char * str)
Definition at line 34 of file stringex.cpp.
bool operator< (const StringEx & strex1, const StringEx & strex2)
Definition at line 20 of file stringex.cpp.
ostream& operator<< (ostream & sout, const Text & text)
Definition at line 208 of file stringex.cpp.
References StringEx::getBuffer().
ostream& operator<< (ostream & sout, const StringEx & strex)
Definition at line 69 of file stringex.cpp.
bool operator== (const StringEx & strex1, const char * str)
Definition at line 48 of file stringex.cpp.
bool operator== (const StringEx & strex1, const StringEx & strex2)
Definition at line 41 of file stringex.cpp.
bool operator> (const StringEx & strex1, const char * str)
Definition at line 27 of file stringex.cpp.
bool operator> (const StringEx & strex1, const StringEx & strex2)
Definition at line 13 of file stringex.cpp.