Hypothesis Struct Reference
#include <bidir.h>
Public Member Functions
bool operator< (const Hypothesis &h) const
Hypothesis (const vector< Token > &vt_, const multimap< string, string > &tagdic, const vector< ME_Model > &vme)
void Print ()
void Update (const int j, const multimap< string, string > &tagdic, const vector< ME_Model > &vme)
Public Attributes
vector< Token > vt
vector< double > vent
vector< int > order
vector< vector< pair< string, double > > > vvp
double prob
Detailed Description
Definition at line 40 of file bidir.h.
Constructor & Destructor Documentation
Hypothesis::Hypothesis (const vector< Token > & vt_, const multimap< string, string > & tagdic, const vector< ME_Model > & vme) [inline]
Definition at line 50 of file bidir.h.
References order, prob, Update(), vent, vt, and vvp.
Member Function Documentation
bool Hypothesis::operator< (const Hypothesis & h) const [inline]
Definition at line 47 of file bidir.h.
References prob.
void Hypothesis::Print () [inline]
Definition at line 65 of file bidir.h.
References vt.
void Hypothesis::Update (const int j, const multimap< string, string > & tagdic, const vector< ME_Model > & vme) [inline]
Definition at line 75 of file bidir.h.
References BEAM_WINDOW, ME_Model::classify(), entropy(), ME_Model::get_class_id(), ME_Model::get_class_label(), ME_Sample::label, mesample(), ME_Model::num_classes(), vent, vt, and vvp.
Referenced by generate_hypotheses(), and Hypothesis().
Member Data Documentation
vector<int> Hypothesis::order
Definition at line 44 of file bidir.h.
Referenced by generate_hypotheses(), and Hypothesis().
double Hypothesis::prob
Definition at line 46 of file bidir.h.
Referenced by generate_hypotheses(), Hypothesis(), and operator<().
vector<double> Hypothesis::vent
Definition at line 43 of file bidir.h.
Referenced by generate_hypotheses(), Hypothesis(), and Update().
vector<Token> Hypothesis::vt
Definition at line 42 of file bidir.h.
Referenced by bidir_decode_beam(), generate_hypotheses(), Hypothesis(), Print(), and Update().
vector< vector<pair<string, double> > > Hypothesis::vvp
Definition at line 45 of file bidir.h.
Referenced by generate_hypotheses(), Hypothesis(), and Update().
The documentation for this struct was generated from the following file:
/disk/workspace-cpp/la-manager/include/pos/bidir.h