ME_Model::ME_Model::ME_Feature Struct Reference
Public Member Functions
ME_Feature (const int l, const int f)
int label () const
int feature () const
unsigned int body () const
Private Attributes
unsigned int _body
Detailed Description
Definition at line 68 of file maxent.h.
Constructor & Destructor Documentation
ME_Model::ME_Model::ME_Feature::ME_Feature (const int l, const int f) [inline]
Definition at line 70 of file maxent.h.
Member Function Documentation
unsigned int ME_Model::ME_Model::ME_Feature::body () const [inline]
Definition at line 76 of file maxent.h.
References ME_Model::ME_Model::ME_Feature::_body.
Referenced by ME_Model::ME_Model::ME_FeatureBag::Id(), ME_Model::make_feature_bag(), and ME_Model::ME_Model::ME_FeatureBag::Put().
int ME_Model::ME_Model::ME_Feature::feature () const [inline]
Definition at line 75 of file maxent.h.
References ME_Model::ME_Model::ME_Feature::_body.
int ME_Model::ME_Model::ME_Feature::label () const [inline]
Definition at line 74 of file maxent.h.
References ME_Model::ME_Model::ME_Feature::_body.
Referenced by ME_Model::update_model_expectation().
Member Data Documentation
unsigned int ME_Model::ME_Model::ME_Feature::_body [private]
Definition at line 78 of file maxent.h.
Referenced by ME_Model::ME_Model::ME_Feature::body(), ME_Model::ME_Model::ME_Feature::feature(), and ME_Model::ME_Model::ME_Feature::label().
The documentation for this struct was generated from the following file:
/disk/workspace-cpp/la-manager/include/pos/maxent.h