la_manager::stem::StemFunc Struct Reference
Public Attributes
struct SN_env *(* create)(void)
void(* close)(struct SN_env *)
int(* stem)(struct SN_env *)
struct SN_env * env
Detailed Description
Definition at line 26 of file Stemmer.cpp.
Member Data Documentation
void(* la_manager::stem::StemFunc::close)(struct SN_env *)
Referenced by la_manager::stem::Stemmer::init().
struct SN_env*(* la_manager::stem::StemFunc::create)(void) [read]
Referenced by la_manager::stem::Stemmer::init().
struct SN_env* la_manager::stem::StemFunc::env [read]
Definition at line 32 of file Stemmer.cpp.
Referenced by la_manager::stem::Stemmer::init().
int(* la_manager::stem::StemFunc::stem)(struct SN_env *)
Referenced by la_manager::stem::Stemmer::init().
The documentation for this struct was generated from the following file:
/disk/workspace-cpp/la-manager/source/stem/Stemmer.cpp