/disk/workspace-cpp/la-manager/test/t_pos.cpp File Reference
#include <stdio.h>
#include <fstream>
#include <map>
#include <list>
#include <iostream>
#include <sstream>
#include <pos/POSTaggerEnglish.h>
#include <Tokenizer.h>
#include <NounFilter.h>
#include <LACache.h>
Functions
double etime ()
int main (int argc, char **argv)
Function Documentation
double etime ()
Definition at line 19 of file t_pos.cpp.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 28 of file t_pos.cpp.
References la_manager::TokenizeConfig::addAllows(), la_manager::EnglishNounFilter::analyze(), etime(), la_manager::Tokenizer::setConfig(), and la_manager::Tokenizer::tokenize().