/disk/workspace-cpp/la-manager/source/pos/tokenize.cpp File Reference
#include <list>
#include <string>
#include <sstream>
Functions
static void replace (string &s, const string &s1, const string &s2, const char skip=0)
void tokenize (const string &s1, list< string > &lt)
Function Documentation
static void replace (string & s, const string & s1, const string & s2, const char skip = 0) [static]
Definition at line 112 of file tokenize.cpp.
Referenced by StringEx::replaceString(), StringEx::replaceStringFromAToB(), and tokenize().
void tokenize (const string & s1, list< string > & lt)
Definition at line 11 of file tokenize.cpp.
References replace().
Referenced by bidir_postag(), and postag().